### ISSUE TITLE
Message Lock Expired

### ISSUE THREAD

**Issue by Jainit25** [Azure/azure-sdk-for-python#10113]
# Description
I am writing a python consumer to consume messages from service bus queue. I am running it in a while loop such that it consumes some messages and then process it and then repeatedly do the same. It works fine locally however, when I try to run it in Azure VM it throws the following error:
I tried to debug the issue and it is able to connect to the service bus and only fails when the message is marked complete. There is no lag between processing messages, all happens pretty much in seconds.

## Actual Behavior
```
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 14, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 14, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
```

## Expected Behavior
The consumer should start consuming the messages and mark it complete in the VM

**Comment by kaerm** [comment]
@SeanFeldman thanks for forwarding and @Jainit25 thanks for reporting. //cc: @KieranBrantnerMagee and @mayurid could you take a look at this

**Comment by Jainit25** [comment]
Thanks everyone for jumping into the conversation. I further debugged and found out that the following logic is failing in **message.py** being the root cause of the issue.
```
if self.locked_until and self.locked_until <= datetime.datetime.now():
    return True
```
On the VM I printed the locked_until time and the current time and found out that the locked_until time is less than the time when the message was read. For example, if I am reading/marking the message as complete at 10:00, the locked_until time is 9:45 which makes no sense. So I compared the VM time which is 15 mins ahead of actual UTC time.
On my local machine this error is not occurring as my machine is accurate with the EST time. The reason why it was passing locally and failing in the VM.

I want to ask for recommendations on fixing this issue now as we now know the root cause.

**Comment by SeanFeldman** [comment]
Time from the server is always in UTC. The servers on Azure might have a slight clock skew, but it should not be as big as 30 seconds. If it's a custom VM, perhaps time should be synchronized.

I'm no Python expert, but `datetime.datetime.now():` looks suspicious. Unless it's a UTC time. Perhaps it should be `datetime.now(timezone.utc)`?

**Comment by Jainit25** [comment]
`datetime.datetime.now():` is the logic from Service Bus python package when we import packages using `from azure.servicebus import Message`
I believe the `datetime.now()` picks up the system time. Since, the clock is skewed it is getting the time 15 mins prior from the current time. So the logic of service bus `message.complete()` is failing.

**Comment by SeanFeldman** [comment]
> I believe the `datetime.now()` picks up the system time.

In that case it could be the issue. The time should be always UTC and if the SDK is testing it against a non-UTC time, based on where the location/time zone, the condition will fail even the lock wasn't technically lost. I'm also starting to question this guarding statement. Rather send the message to the broker and if the time has elapsed, the broker will reject the completion, resulting in lock lost exception anyways.

**Comment by Jainit25** [comment]
When we run the command timedatectl, we saw a mismatch between the RTC and Universal time.
This is to update that the issue has been fixed by matching the RTC time to the Universal time when we update the `chronyd.conf` file to add the following command. 
`refclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0`

After updating the configuration we need to run the following command in the terminal to restart chronyd
`systemctl restart chronyd`

For more documentation please refer: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

**Comment by KieranBrantnerMagee** [comment]
Hey folks, 
Glad you were able to address the clock skew as a workaround, Jainit. 

Thanks as well for pointing this issue our way Sean, and for the assistance.  I'd agree that the non-UTC lock comparison is suspicious, but when obtaining the time from the message annotation we also extract the timestamp into local time, so the comparison is consistent, if surprising.  We've taken steps to address this for the upcoming GA version of this library (Currently in preview, 7.0.0b2), times are now all UTC.  

Regarding the guard, since your suggestion seemed on-point, I spoke with some of the folks with prior knowledge of the SDK and discovered that its (the guard) existence was in response to the service not giving useful feedback if the message to be settled was already expired; see [here](https://github.com/Azure/azure-uamqp-c/issues/274).  Now, this was a while back, and begs the question how the other languages have addressed this in the protocol layer, so I'll be resurrecting that discussion to try and get a better answer and potentially improve this scenario.  

Closing this issue now as the immediate problem appears to be resolved; as always don't hesitate to reopen and/or reach out if any further questions or discussion would be helpful.
