### ISSUE TITLE
VirtualMachinesOperations doesn't support change of api versions

### ISSUE THREAD

**Issue by jonasshen** [Azure/azure-sdk-for-python#1023]
Azure China Cloud vm get api doesn't support '2016-04-30-preview' yet
```python 
CHINA_COMPUTE_CLIENT = ComputeManagementClient(
    credentials=CHINA_SP_CREDENTIALS,
    subscription_id=CHINA_SUB_ID,
    base_url="https://management.chinacloudapi.cn"
)

CHINA_VM_03 = CHINA_COMPUTE_CLIENT.virtual_machines.get(
    "testcases03", "ma03mnictest")
print "china vm 03", CHINA_VM_03
```

Message: No registered resource provider found for location 'chinaeast' and API version '2016-04-30-preview' for type 'virtualMachines'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30'. The supported locations are 'chinanorth, chinaeast'.

**Comment by lmazuel** [comment]
Hi @jonasshen 
Yes, the latest `azure-mgmt-compute` is build for public Azure  and the new Managed Disks feature. I totally understand this is frustrating for non-public Azure users and we are currently working to allow our packages to have multi-version support.

In the meantime you have several solutions:

1. Install an old package
0.32.1 is compatible with 2016-03-30. This is the approach I recommend right now for `azure-mgmt-compute` The version 0.33.0 you use has just the new Managed Disks feature otherwise the content is similar.

2. Keep using this package, but changing the `api-version`
`api_version` is an attribute of the operation group, so you can write:
    ```python
    CHINA_COMPUTE_CLIENT.virtual_machines.api_version = '2016-03-30'
    ```
    This should allow you all basic operations, but there is a risk that the models of JSON described in the package does not fit what you will get from '2016-03-30', but it's unlikely for compute which is pretty stable backward compatible RestAPI.

**Comment by lmazuel** [comment]
I close this issue, I think I answered correctly to the initial question. Feel free to comment to re-open it if necessary, or open a new issue if you have any new problems.
Thank you,
