### ISSUE TITLE
Support Service Principal Certificate Login

### ISSUE THREAD

**Issue by MS-HerbChung** [Azure/azure-sdk-for-python#1024]
So far it only allows Service Principal login with password.

However, one of our biggest customer wants to use certificate for security reason.

Can you add this feature on?

**Comment by lmazuel** [comment]
Hi @MS-HerbChung 
We currently recommend to use [ADAL for Python](https://github.com/AzureAD/azure-activedirectory-library-for-python) to authenticate and to use our [ADAL wrapper](http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal) in the SDK. ADAL is maintained by the Active Directory team and will be always on top of the current authentication mechanism in Azure.
I think your feature is covered by ADAL. If you have an issue to authenticate with your scenario, please open an issue on their repository with your need.
I close this issue, since either the feature is covered by ADAL, either it's not and as to be added in the ADAL lib. Feel free to still comment here if I miss a point and I will re-open the issue in that case.
Thank you,
