### ISSUE TITLE
Mocking the sdk response.

### ISSUE THREAD

**Issue by madhugilla** [Azure/azure-sdk-for-python#1031]
Hi,

We are using the Python SDK for creating resources in our subscriptions, and its going great, couldn't thank you enough for building this library in python.

One stumbling block that we are facing is unit testing the sdk response objects, it will be helpful if you could point us to any of your tests or resources..

For example how can we mock the response "LocationPaged" object, from the list_locations method in this link 
[https://azure-sdk-for-python.readthedocs.io/en/latest/_modules/azure/mgmt/resource/subscriptions/operations/subscriptions_operations.html#SubscriptionsOperations.list_locations](url)

Thanks

**Comment by lmazuel** [comment]
Hi @madhugilla 

I wrote a wiki on how we do our testing (including tests locations):
https://github.com/Azure/azure-sdk-for-python/wiki/Contributing-to-the-tests

At a glance, we hook requests using vcrpy to record HTTP calls into files. When we replay the tests (in "playback" mode), the framework automatically open the files and answer what was recorded. This way, we do not need any mock, we use the regular Python code. We coded a wrapper around vcrpy, but it's just a tools for convenience and it's not mandatory (the Python CLI team uses vcrpy too with no wrapper).

Please read the wiki and tell me how (or not) this is answering to your question. This way I can help you more precisely and/or update my document if something is unclear.

**Comment by madhugilla** [comment]
Got it, the link is detailed and very helpful for contributors. But as a consumer of this SDK  we are exploring on how to mock SDK methods to unit test our own modules.

For example how can we mock/fake the response "LocationPaged" object, from the list_locations method ?

`    def list(self):
        logging.info("Azure Region Service list API")
        **regions** = self.provider.subscription_client.subscriptions.list_locations(self.provider.subscriptionid);

**Comment by lmazuel** [comment]
You can mock it at the HTTP level using vcrpy :)

You should be able to mock it at the object level using [mock](https://docs.python.org/3/library/unittest.mock.html?highlight=mock#module-unittest.mock) on the list_locations method. You can return a `list` of [Location](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.resource.subscriptions.models.html#azure.mgmt.resource.subscriptions.models.Location) instead of `LocationPaged`. In real life, `LocationPaged` is an iterable, not a list, but it's close enough if you write your tests remembering this is an iterable and you don't use directly list methods.

If you want something closer than `list`, you can create your own `LocationPaged` inherited from `collections.Iterable`

**Comment by madhugilla** [comment]
Thank you this make sense.
