### ISSUE TITLE
Add support for SQL database management

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#105]
Documentation for REST API:
http://msdn.microsoft.com/en-us/library/windowsazure/gg715283.aspx

**Comment by themaxx75** [comment]
In my case, the most useful and important features are related to BACPAC. Import to BACPAC on blob storage, Export to BACPAC to blob storage, and polling the status of requested jobs.

I work on an app that manages our deployments on Azure, and this would make a lot of people happy at my company. 

Thanks for all your great work!

**Comment by lmazuel** [comment]
I will close this bug for now, since:
- We will no more work on the ASM legacy code
- The ARM support for SQL management will be followed here: https://github.com/Azure/azure-rest-api-specs/issues/175
- For the BACPAC question, there is evidences that it's currently possible to[ deploy with BACPAC using ARM template](https://blogs.msdn.microsoft.com/kaevans/2016/03/28/deploy-bacpac-to-azure-sql-database-using-arm/). In addition [ARM template is covered by this SDK.](http://azure-sdk-for-python.readthedocs.org/en/latest/resourcemanagement.html#create-deployment-from-template)
