### ISSUE TITLE
Parent step doesnt wait until all child run steps complete

### ISSUE THREAD

**Issue by gargiulman** [Azure/azure-sdk-for-python#10502]
- **Package Name**:  azureml-sdk
- **Package Version**: 1.0.85
- **Operating System**:
- **Python Version**: 

**Describe the bug**
I have a pipeline run created, which has 4 steps. I want to create 4 child runs from step 2, each child is a pythonscriptstep and has a different script file. Though the child runs gets submitted , but the parent i.e step 2, doesnt wait until all its child have completed. I have used parent_run_id to link step 2's run id with its 4 child runs.

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sanpil** [comment]
Call wait_for_completion() from within step 2 for the step to wait until child runs are done.

**Comment by gargiulman** [comment]
i have done that. But the process is not clean. once you submit the child runs and try to check whether get_children() returns info on all child steps, it does not. there is a wait period which is not fixed. So i had to first wait till get_children() returns all 4 child runs, then i had to loop through each step within the child run and see its completed.

**Comment by gargiulman** [comment]
This i had done a month ago, has there been any recent upgrades done to aml package so i dont have to write code to poll whether each child has completed? If so, which sdk version should i refer

**Comment by gargiulman** [comment]
When is subgraph getting released, and does it solve this issue along with #10543

**Comment by sanpil** [comment]
We have a work item on our side to implement this. Unfortunately, there is no ETA at the moment.

**Comment by ManojBableshwar** [comment]
@gargiulman - I'm a new PM on the Pipelines team and trying to get full context of the issue. I ack that get_children() is unpredictable. We will look into fixing it. 
Can you explain why calling wait_for_completion() on the parent run not meet your needs? It is expected to wait on all child runs to complete before returning?

**Comment by mparq** [comment]
@ManojBableshwar, re-surfacing this issue in 2022 since I found this thread after running into a similar problem where calling `run.get_children()` too quickly seems to return incomplete set of child runs.

To work around this, instead of relying on `run.get_children()`, we just keep track of the child runs that we submit in the parent run and call wait_for_completion() in that loop. Is there a reason the documentation recommends `run.get_children()` instead of this approach?

e.g.

```python
parent_run = Run.get_context()

child_run_configs = construct_child_run_configs()

submitted_child_runs = []
for child_run_config in child_run_configs:
  child_run = parent_run.submit_child(child_run_config)
  submitted_child_runs.append(child_run)

# documentation recommends below, but we see issues where below can return incomplete set of child runs non-deterministically
# -> for child in parent_run.get_children()

# instead, loop over in-process child run list
for child_run in submitted_child_runs:
  child_run.wait_for_completion(show_output=False, raise_on_error=True)

```

**Comment by cloga** [comment]
@mparq , would you help to provide which doc are you referring to?

From this doc: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-track-monitor-analyze-runs?tabs=python#submit-child-runs

We already recommend the approach you have mentioned. We may need update the doc you have mentioned also.

Thanks.

**Comment by mparq** [comment]
@cloga that was the doc I was referring to. The important line is this one in published documentation which we were seeing leads to unexpected results due to the `run.get_children` issue which seems to be mentioned higher in this thread:
```python
...
# run.get_children() -> sometimes non-deterministically will not return all child runs which just got submitted
for child in run.get_children():
    child.wait_for_completion()
```

In code snippet I pasted above, I explicitly maintain a list of child run objects which get returned by `parent_run.submit_child` and iterate over that list to ensure that I am actually iterating over all submitted child runs.

The currently-recommended approach in docs led to some confusing behavior since a lot of times things would work fine but sometimes this parent step would complete too quickly causing following steps in the parent pipeline to fail (or worse, read partial data).
