### ISSUE TITLE
Clarity on use of checkpoint store

### ISSUE THREAD

**Issue by kwontae** [Azure/azure-sdk-for-python#10537]
Hello, I was unsure if this clarity question goes under bug or feature.
Anyways, our team is working on a project that will automate network device management and eventhub is an essential component. We've set up the blob storage for checkpoint store and created an application that will instantiate a consumer client to receive events. When we created multiple replicas in our kubernetes cluster, we noticed that only one pod will listen and other pods (Containers) will fail because there is already a listener receiving events on all partitions... Is there a recommended way of multi-threading receive? It seems to work when we create multiple instances of consumer client within an application, but not when we create multiple containers/processors

**Comment by YijunXieMS** [comment]
@kwontae The SDK's load balancing should balance the number of partitions among all clients if you use multiple containers and/or processes that use the same blob container. Could you turn on the logs and see the error message? 
Is it 5.0.0 or 5.0.1?

**Comment by YijunXieMS** [comment]
Could you please start the containers and wait a while because the load balancer takes some time to balance the the number of partitions among all clients?
The 1st client will take all partitions, then other clients will start to take partitions from it gradually and will balance.
How many partitions do you have, and how many containers?

**Comment by kwontae** [comment]
We are currently using 5.0.0

**Comment by kwontae** [comment]
we have 32 partitions and running 32 containers just for testing. We are trying to run some benchmark testing

**Comment by YijunXieMS** [comment]
The load_balancing_interval is 10 seconds. It shouldn't take very long time. I think it will be balanced in a a few minutes. If you see only one container is working for long time, there must be something wrong.
If the problem persists, could you try 5.0.1? We have a small change on the load balancer in 5.0.1

**Comment by kwontae** [comment]
this is the log we get 
`ConnectionClose('ErrorCodes.UnknownError: Connection in an unexpected error state.',)`

**Comment by YijunXieMS** [comment]
From this log, the client has taken the partition and is trying to receive from it but has a connection error so the client will give away the partition.
Does it keep happening or just occasionally? The client will try to grab a partition again  if it finds it doesn't have enough partitions every `load_balancing_interval` (default 10s).

**Comment by kwontae** [comment]
@YijunXieMS so does that mean it will load balance all clients every 10 seconds or it will sequentially add a client and load balance at 10 sec interval. For instance, if we spin up 32 containers, 1st container will take all partitions for the first run, after 10 seconds, it will load balance between a pool of 32 consumer clients or 2, 3, 4 and so on at 10 sec interval

**Comment by kwontae** [comment]
@YijunXieMS  This seems to keep happening when we use async receive. Seems to work without async.

**Comment by YijunXieMS** [comment]
@kwontae All other containers after the 1st one will steal their a random partition from the 1st one concurrently every 10s (configurable). If two happen to be stealing the same partition, only one will succeed. The failed one will wait 10s to steal another partition.

Good to know that the sync works. In theory the async should be the same as sync at the connection level. Do you see other detailed information around the ConnectionClose error? And do you see Python crashes?

BTW, my email is yijun.xie@microsoft.com. Please feel free to send me emails should have questions at any time.

**Comment by YijunXieMS** [comment]
@kwontae sure, no rush for that.

**Comment by dipanjan1201** [comment]
We currently have 32 containers listening to the eventhub for events, and we're using the synchronous version of EventhubConsumerClient. We're seeing issues like connection closing and error codes very frequently. 
EventProcessor instance '54ab3a90-de1a-4588-b121-8b6e71869b9c' of eventhub 'jobs' partition '5' consumer group '$Default'. An error occurred while receiving. The exception is ConnectionLostError('ErrorCodes.UnknownError\nError: unknown-error\nErrorCodes.UnknownError',).
ConnectionClose('ErrorCodes.UnknownError',)
ConnectionClose('ErrorCodes.UnknownError',)
ConnectionClose('ErrorCodes.UnknownError',)
ConnectionClose('ErrorCodes.UnknownError',)
EventProcessor instance '54ab3a90-de1a-4588-b121-8b6e71869b9c' of eventhub 'jobs' partition '6' consumer group '$Default'. An error occurred while receiving. The exception is ConnectionLostError('ErrorCodes.UnknownError\nError: unknown-error\nErrorCodes.UnknownError',).
LinkDetach("ErrorCodes.ConnectionCloseForced: The connection was inactive for more than the allowed 240000 milliseconds and is closed by container 'c602bba047c246a9b3e0647447d5c4a0_G18'.",)
ConnectionClose('ErrorCodes.UnknownError',)
ConnectionClose('ErrorCodes.UnknownError',)
ConnectionClose('ErrorCodes.UnknownError',)
ConnectionClose('ErrorCodes.UnknownError',)

Any idea why this might be happening?

**Comment by YijunXieMS** [comment]
@dipanjan1201 Could you send me the code of the callback (on_event) if possible?

**Comment by dipanjan1201** [comment]
@YijunXieMS Here you go. FYI, we're using 5.0.1

```
checkpoint_store = BlobCheckpointStore.from_connection_string(blob_storage_connection_string, blob_container_name)

consumer_client = EventHubConsumerClient.from_connection_string(jobs_eventhub_connection_string, '$Default', eventhub_name=eventhub_name, checkpoint_store=checkpoint_store,)

# Callback for when an event comes in
def on_event(partition_context, event):
    print("Received event from partition {}".format(partition_context.partition_id))
    print('Updating Checkpoint')
    partition_context.update_checkpoint(event)
    #Business logic 

with consumer_client:
    consumer_client.receive(on_event=on_event)
```

**Comment by YijunXieMS** [comment]
What did you do with the "#Business logic", or is it just a comment in your test?

**Comment by dipanjan1201** [comment]
> What did you do with the "#Business logic", or is it just a comment in your test?
I've redacted that piece of code. We're processing the event.body_as_str(), and doing some business logic.

**Comment by YijunXieMS** [comment]
@dipanjan1201 

When you don't do the update_checkpoint and the business logic, do you see the same problems?

However, some general optimization opportunities:
1. I suggest you do not update checkpoint every event if possible. It has http request/response, which is heavy.
2. If your business logic has a lot of I/O operations (time.sleep(), network, file, etc.), use multiple threads (The high level concurrent API ThreadPoolExecutor is a good choice). update_checkpoint() itself has http request too. The sync API is single-threaded because we don't want to expose internal threads to users. So the 32-partition's on_event callback are called in a single thread. It could be helpful to process your business logic in threads. We're thinking of allowing users to pass in an ThreadPoolExecutor to EventHubConsumerClient.receive( ) to run partitions callback in threads. But at this time I'm afraid you need to do it yourself.
The async API is even a better choice for I/O bound stuffs.
3. Increase the number of python processes with each process on average having 1 CPU core of the machine. Increasing threads in one Python process doesn't help much on the CPU usage because of the Python GIL. Usually one python process shouldn't process more than 4 ~ 8 partitions if there are large amounts of events coming in short time. (I don't know how many processes you have and how complex your business logic is. Just a general statement). 

Sorry I don't have more detailed information so I can't provide a more precise suggestion.
Let me know if any of these are helpful. You can also email me yijun.xie@microsoft.com if you want.

**Comment by dipanjan1201** [comment]
@YijunXieMS  Thanks for the pointers. I'll try them out and let you know what worked and what didn't.

**Comment by YijunXieMS** [comment]
@dipanjan1201 I'm closing this issue since it's been a while. Please create a new issue if you have more questions.
