### ISSUE TITLE
The docstring param for credentials is incorrectly set to None. 

### ISSUE THREAD

**Issue by dciborow** [Azure/azure-sdk-for-python#10539]
https://github.com/Azure/azure-sdk-for-python/blob/77d7c28427bac002469a494bf23e9e4a54210f2d/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/_configuration.py#L26

This should probably be AbstractAuthentication? Or Authentication? I can't really even tell and am just trying to guess now.

**Comment by lmazuel** [comment]
Hi @dciborow 
This is `from msrest.authentication import CognitiveServicesCredentials`

See also:
https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/master/samples/vision/computer_vision_samples.py

This is a known bug in the version of the code generator we used to do this client. This issue will be fixed eventually, since it has been fixed in the generator itself:
https://github.com/Azure/autorest.python/issues/210

Thanks!
