### ISSUE TITLE
[textanalytics] Investigate if it is too easy to send empty request

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#10567]
According to Assaf: 

"We see a large number of empty requests but on a deeper look these come from only 6 subscriptions, with the majority of requests come from a single one. 
It does seem that there are more Python users sending empty requests though, so I wonder if there’s something inherent the Python API that enables that more easily."

Possibly need to do more client side validation, but also make sure we don't go overboard.

**Comment by johanste** [comment]
It is very likely safe to do validation of non-empty input for all analyze method calls. However, it is probably worth pointing out that the only difference (from a customer perspective) is that I now get a new kind of exception. 

I don't think there is a problem in our API signature in this case that makes it more likely that a customer would assume that passing in an empty set of documents would somehow give them some actionable result (e.g. "give me the sentiments for each document in this empty set of empty documents")

Another option would have been to return an empty result set (please note that I don't suggest us doing that since that would have other issues; e.g. response hooks not getting raw responses etc.).

**Comment by assafi** [comment]
I think this is one of the rare cases where client-side validation makes sense. It also reduces the load on the service in many trivial cases. 

Note however that the validation needs to include whitespaces as well, not just empty strings.

**Comment by maririos** [comment]
According to that data, I am ok adding validation for empty strings. It looks like it will definitely help avoid unnecessary errors

**Comment by assafi** [comment]
@maririos agreed. I'm not very opinionated here as we'll mainly just shift a 400 from the server to the client. I can see the importance of consistency but also the saving it might have on the server. I think it really comes out to the code customer will have to write and intuitiveness of the API.

**Comment by johanste** [comment]
To be clear; from a customer's perspective, these are still errors. We are really only discussing if it should be a ValueError (in Python - most likely an ArgumentException in .NET) or a HTTP response error. The steps a customer is expected to prevent the error is still the same (make sure they have non-empty inputs). It does come with associated runtime cost for any request that is valid (which is presumably the 99.9%+ of all requests). 

The major upside is to reduce server load/cost/request quota usage. I'm also not very opinionated on this.

**Comment by maririos** [comment]
Thanks both for the input. 
Ok, I say let's add validation for empty documents for now. Later, if we receive other feedback from customer we can adjust

**Comment by maririos** [comment]
FYI @mssfang  and @willmtemple
