### ISSUE TITLE
Receive events seems to be missing from the sdk

### ISSUE THREAD

**Issue by Hoovs** [Azure/azure-sdk-for-python#1056]
I have looked at several other SDKs maintained by the Azure project and they all seem to have a way to receive events off the EventHub. This project seems to be missing that feature? Is this a limitation of AMQP or was there a reason it wasn't included? #

I have as of yet been able to get messages from python but can do so with Java no problem. This seems like a very common use case of an EventHub. Can you provide more insight as to why it is not included or if it is where I can find it?

I know the standard is AMQP from an earlier issue on this thread but after reading the doc and examples I still think this should be wrapped in this SDK.

**Comment by lmazuel** [comment]
Hi @Hoovs 

Just to be sure 100% we understand each other, `azure-servicebus` is a package over the HTTP RestAPI of Service bus. So when you say:

> Is this a limitation of AMQP

I have no idea if AMQP is able or not to receive from EventHub. You might want to ask on articles [like this one](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview) to reach directly the SB team.

However, for the package in this repo using RestAPI, yes, we know we miss this feature. This wasn't available at first and since now the Service Bus team considers that all effort should be in AMQP, the time available to update this library is reduced. I usually take a full day or two every 4/5 months to fix all Service Bus issues at once. But since I'm unsure if this is available in the RestAPI, I can't say if the feature will be available in Python.

Thanks,

**Comment by Hoovs** [comment]
Hi @lmazuel,
Sorry for the long delay. I did read the code and see you were sending it over HTTP. I have also read over most of the Azure AMQP documentation and seen that this is where they were going with it. However, since this seems like the only repo for python related to the service bus I wondered why it was using HTTP over AMQP and it seems like it is just due to time limitations.

Thank you for the clarification and I look forward (hope) that it will be rolled into this repo at some point in the future.

Thank you

**Comment by annatisch** [comment]
Hi @Hoovs - a new AMQP-based Python SDK for Event Hubs is now in preview:

https://pypi.org/project/azure-eventhub/#description
https://github.com/Azure/azure-event-hubs-python/tree/develop

It would be great if you could try it out and let us know any feedback you have :)
