### ISSUE TITLE
Azure Advisor API for Cost Category of Buy Reserved instance recommendation does not provide VM name in the Impacted field

### ISSUE THREAD

**Issue by sachin-mangalorkar** [Azure/azure-sdk-for-python#10918]
We are trying to fetch the Azure Advisor recommendations using the Azure Advisor API provided in MS Azure Docs. While we looked in to the API result, We see that for most of the recommendations listed we see the resource Impacted against the recommendation. 

However in Cost Category for "Buy Reserved instance" recommendation we do not see any the VM impacted for the recommended SKU size.   Only the affected resources are shown and not the resources that may be nested within.

However, In the portal we are able to see the VM impacted with "Buy Reserved Instance". we would like to achive the same results in API results as well. 

Could you please consider this feedback and enhance the feature which can meet our requirement?

**Comment by ZeeshanFastian** [comment]
I am also trying to achieve the same things but recommendation APIs do not bring the actual resource name. Were you able to find a way?

**Comment by jportugal0** [comment]
Hi @sachin-mangalorkar, @ZeeshanFastian. We don't provide the VM names in the API due to it being dynamic and based on the resources that you have. Reserved Instances are dynamic and not resource dependent, if you have a Reserved Instance for 2 VM, VM1 and VM2, and delete VM2 and create VM3, VM3 would be covered by the Reserved Instance. 

In the Portal, where we do display this information, we can ensure that it is up to date as well as provide clear messaging, which is the main reason for the resources being included there and not in the API.
