### ISSUE TITLE
[FEATURE REQ] Add support for AZURE_CLIENT_ID environment variable to ManagedIdentityCredential

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#10931]
**Library or service name.**
Azure Identity
 
**Is your feature request related to a problem? Please describe.**
Developers need to be able to specify which AZURE_CLIENT_ID Managed Identity Credential with an environment variable. 

#8094
#9321

**Comment by jongio** [comment]
#8094 
#9321

**Comment by jongio** [comment]
Please follow up with @schaabs before implementing.

**Comment by ms-lolo** [comment]
Could I convince you not to force this environment variable to be used in `DefaultAzureCredential`? This is currently breaking our code because we pass in `client_id` but this no longer works. Machines can have more than one identity assigned to them so being able to pass a client id in when creating an instance of the identity classes is important.

Not sure if you'd prefer I file a ticket for this and I wasn't sure if this should be called a bug.

**Comment by jongio** [comment]
The logic should be if the user provides a client id, then that would take precedence over the environment variable.  Are you saying that is not happening?

**Comment by ms-lolo** [comment]
That's correct. This line of code is hard-coding the client_id parameter without checking if it's in `kwargs`: https://github.com/Azure/azure-sdk-for-python/blob/c6388a01fc731ba8fba3de122aec799c384f59da/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L103

**Comment by jongio** [comment]
Thanks, Would you like to file an issue for this?  (I can if you'd like)

**Comment by ms-lolo** [comment]
sure I can give it a shot

**Comment by jongio** [comment]
Sounds great.  Thank you for doing that.
