### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.common' when depending on azure-common in combination with other packages from setup.py script

### ISSUE THREAD

**Issue by kennep** [Azure/azure-sdk-for-python#10956]
- **Package Name**: 
azure-common
- **Package Version**: 
1.1.25
- **Operating System**:
Ubuntu 18.04
- **Python Version**: 
3.6.9

**Describe the bug**
When depending on azure-common _in combination with other packages_ from a *setup.py* script, later attempts to import the `azure.common` package fails with `ModuleNotFoundError: No module named 'azure.common'`.

Depending on azure-common alone does not cause this error; it seems to be introduced when adding a dependency on _another_ azure package. The example setup script below reproduces this with the azure-cli-core package, but in an internal package we have, this seems to happen with other packages  as well, though I haven't been able to condense this down to which precise combination it happens with.

I would guess this is what causes the failure in issue #3950 as well.

**To Reproduce**
Copy this `setup.py` file into an empty directory:
```python
from setuptools import setup

setup(install_requires=[
	'azure-cli-core',
	'azure-common'])
```

Create a new virtual environment and activate it:
`python3 -mvenv .venv && . .venv/bin/activate`

Run setup.py install:
`python setup.py install`

Observe that azure.common cannot be loaded.
```
$ python -c 'import azure.common'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.common'
```

Note that installing the same two dependencies with pip does not cause the same failure. If you start with a clean venv, run `pip install azure-cli-core azure-common`, then try to import `azure.common`, then that will succeed. So there is some difference in how easy_install installs packages vs how pip installs them, that causes this.

**Expected behavior**
The import statement above would succeed.

**Comment by lmazuel** [comment]
Hi @kennep 

This is because when you use "python setup.py install", you install using setuptools egg folder:
![image](https://user-images.githubusercontent.com/1050156/79889653-33394f80-83b3-11ea-9e33-2de7ec91c5e8.png)

This could work only if all packages under the namespace package `azure` are using the same namespace package strategy. As of today, SDK (and azure-common) have moved to PEP420 (you can see the absence of `__init__.py` files), whereas azure-cli-core didn't yet (see this issue in CLI repo https://github.com/Azure/azure-cli/issues/8164)

If you use pip instead of setuptools with `pip install .`, you won't get the issue since it will first build a wheel and install in consistent folder.

Closing, this there is nothing we can do on the SDK side, if you need egg folder support for azure please upvote the CLI issue.

Final note, using setuptools to install is considered deprecated nowadays, I highly suggest you move to pip to install packages.
