### ISSUE TITLE
[Identity] ManagedIdentityCredential only accept client_id of a user-assigned identity which is a feature gap versus msrest authentication

### ISSUE THREAD

**Issue by qianwens** [Azure/azure-sdk-for-python#10989]
- **Package Name**: Azure.Identity

**Describe the bug**
ManagedIdentityCredential only accept client_id of a user-assigned identity, it misses the support of object_id and msi_res_id like https://github.com/Azure/msrestazure-for-python/blob/v0.6.1/msrestazure/azure_active_directory.py#L463-L549

**Additional context**
Az CLI support user to input client_id, object_id or msi_res_id for MSI authentication.

**Comment by jiasli** [comment]
Let's use `mi_res_id` instead of `msi_res_id` to be in sync with the doc [Get a token using HTTP for managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http). See https://github.com/MicrosoftDocs/azure-docs/issues/15288.
