### ISSUE TITLE
Paging for search

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#11025]
list APIs should return paged items - especially index and datasources.

**Comment by brjohnstmsft** [comment]
Indexes yes, but why data sources? CC @heaths

**Comment by heaths** [comment]
Apart from understanding why DataSources should be paged (keep in mind the service doesn't actually support paging currently, so the SDK would only return a single page), this would otherwise be a dup of #11008. For the new APIs we are making list_indexes return a pageable because there can be up to 3,000 for S3 plans and index models can be pretty large, but limits on other resources are pretty low and they tend to be smaller models. It would be helpful to understand why you'd want these in pages as opposed to all at once.

**Comment by rakshith91** [comment]
Wasn't aware service doesn't support paging currently. Closing this issue as a duplicate. Thanks for the clarification.
