### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Rodrigossz** [Azure/azure-sdk-for-python#11074]
The URL in the "Usage" section on https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-mgmt-cosmosdb links to an old page where people is suggested to install pydocumentdb .

**Comment by lmazuel** [comment]
Hi @Rodrigossz this brings you to a common page for both packages, see a few lines below:
https://docs.microsoft.com/en-us/python/api/overview/azure/cosmosdb?view=azure-python#management-library

Hope this clarifies, closing this issue since it's the expected link, thank you for your issue report thougt, always appreciate feedback :)
