### ISSUE TITLE
[docs] References to azure bundle package

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-sdk-for-python#11103]
A number of package READMEs (and therefore summary on pypi) hold a reference to the now-deprecated [azure](https://pypi.org/project/azure/) package on pypi.

Ex:
```text
For a more complete set of Azure libraries, see the azure bundle package.
```

We shouldn't point developers to deprecated packages.

References: ["azure bundle package"](https://github.com/Azure/azure-sdk-for-python/search?o=desc&q=%22azure+bundle+package%22&s=indexed)

**Comment by kaerm** [comment]
Thanks @noelbundick for posting this! @jongio is this something you could help out with?

**Comment by jongio** [comment]
@lmazuel 

We should search the python repo for any reference to the azure bundle and update.

**Comment by lmazuel** [comment]
The main template of auto-generated pacakges has been fixed, see for instance network doesn't mention it:
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/network/azure-mgmt-network

We shall check if there is any manual packages that still mention it

**Comment by lmazuel** [comment]
@noelbundick I looked the 11 pages of the search link, and I updated the two that were manual, the rest will be auto-updated slowly as mgmt packages goes out (and I expect a wave of new generation this summer with latest autorest)

I didn't updated the nspkg, since I think it's not worth doing a post-release and we won't update them on PyPI ever. The're not even installed anymore on Python 3.

Closing this issue then, feel free to ping me or re-comment if necessary (and I miss your re-comment, to ping me directly ;))

Thanks!
