### ISSUE TITLE
[keyvault] Invalid comparison in azure.keyvault.keys.crypto._internal.jose

### ISSUE THREAD

**Issue by zooba** [Azure/azure-sdk-for-python#11151]
https://github.com/Azure/azure-sdk-for-python/blob/8c819a4ee566e465b5438da5f987d484a2c6449a/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/jose.py#L97-L98

In the above code, the `if not (tuple-with-any-elements):` check will always evaluate to True.

I believe in this case you want `if not all((self.protected, ...))` to ensure that each specified element is not empty.

**Comment by kaerm** [comment]
Thanks @zooba, @chlowell can you take a look at this

**Comment by chlowell** [comment]
Looks like a bug to me, thanks @zooba. However, we don't (and may never) use this code. This `crypto._internal` code began as a prototype largely ported from C#, added wholesale when I needed an adapter between Key Vault and `cryptography`. I think the best way to resolve this issue is to delete the unused code. I'll assign this issue to myself and leave it on the backlog for now.
