### ISSUE TITLE
Support for retrieving/deleting resources by ID

### ISSUE THREAD

**Issue by madhukargilla** [Azure/azure-sdk-for-python#1126]
Hi,

The SDK supports retrieving resources by Name, but  can we have methods that take in an ID and get the  resource or delete the resource ? most of the other cloud providers like AWS have this implemented.

Thanks -Madhu

**Comment by lmazuel** [comment]
Hi @madhukargilla 

- [Get by id is available](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.resource.resources.v2016_09_01.operations.html#azure.mgmt.resource.resources.v2016_09_01.operations.ResourcesOperations.get_by_id) in the `azure-mgmt-resource` package, otherwise it will provide you a `dict` of the properties, not a Python object like a regular "get" will.
- [Delete by id is available](http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.resource.resources.v2016_09_01.operations.html#azure.mgmt.resource.resources.v2016_09_01.operations.ResourcesOperations.delete_by_id) (same package).

In a general way, "azure-mgmt-resource" will contains generic commands to help you deal with Azure resources in a generic way, but will not contains Python object definitions like specific packages will.

Thank you,

**Comment by madhukargilla** [comment]
can you please point us to the unit test or a example on the usage ?

Thank you.
