### ISSUE TITLE
os_profile metadata is missing

### ISSUE THREAD

**Issue by aleyou-css** [Azure/azure-sdk-for-python#11281]
When using the Azure Python SDK and parsing through servers to find the computer_name inside of os_profile.  We found that some servers are missing the os_profile in the metadata.  See attached error, code and metadata.

ICM 185158839 with more information on the issue

Failed
Traceback (most recent call last):  File 'C:\\Temp\\i3escdt1.rfw\\f4ce65b0-9c16-459e-b0b3-814ede83f69b', line 117, in    linux_vm_names=getVmsByOs('Linux',rg,key)  File 'C:\\Temp\\i3escdt1.rfw\\f4ce65b0-9c16-459e-b0b3-814ede83f69b', line 76, in getVmsByOs    print(vm_dict['os_profile']['computer_name'])KeyError: 'os_profile'

def getVmsByOs(os,rg,key):
    vm_names=[]
    for vm in compute_client.virtual_machines.list(rg):
        vm_dict=vm.as_dict()
        if vm_dict['storage_profile']['os_disk']['os_type'] == os:
            for i in vm_dict['tags']:
                if vm_dict['tags'][i] == key:
                    vm_names.append(vm_dict['os_profile']['computer_name'])
    return vm_names

**Comment by chunyu3** [comment]
I cannot created a vm without os_profile. And if I can get the os_profile metadata from the created VM by compute_client.virtual_machines.list.
Ask service team to check why there are compute vms who have no os_profile, or check if the service REST CALL return the os_profile correctly.

**Comment by Drewm3** [comment]
The OS profile is only required when a VM is deployed from a generalized image. If the VM is deployed from a specialized OS disk then an OS Profile is not required. This is because the primary use for the OSProfile is for configuration of the VM when it is deployed from a generalized image. 

Note: The compute name in the OSProfile is only the initial computer name. It is possible that the computer name (also known as host name within the guest OS) has changed since it was originally deployed. It is possible to get the current computer name for any running VM using the Instance View: [https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/instanceview](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/instanceview). However, if the VM is not running, then the computename property of the instance view will not be provided.
