### ISSUE TITLE
KeyVault VaultProperties vault_uri is not marked readonly

### ISSUE THREAD

**Issue by jeking3** [Azure/azure-sdk-for-python#11333]
- **Package Name**: azure-mgmt-keyvault
- **Package Version**: 2.2.0
- **Operating System**: Linux
- **Python Version**: 3.7.7

**Describe the bug**
In the [documentation](https://docs.microsoft.com/en-us/python/api/azure-mgmt-keyvault/azure.mgmt.keyvault.v2019_09_01.models.vaultproperties?view=azure-python) and [generated python](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-mgmt-keyvault/azure/mgmt/keyvault/v2019_09_01/models/_models_py3.py#L1067), `vault_uri` is not defined as readonly, however if you attempt to set it during a call to create_or_update of a KeyVault, it is ignored.  When you run as_dict(keep_readonly=False) on the result, the vault_uri is retained.

**To Reproduce**
This can be validated on the client using as_dict(keep_readonly=False) on a VaultProperties structure containing `vault_uri`.

**Expected behavior**
1. Expected a warning regarding `vault_uri` being ignored.
2. Expected as_dict(keep_readonly=False) to drop `vault_uri` from result.

**Comment by chlowell** [comment]
@iscai-msft is this because of the way `VaultProperties` is defined in the spec?

**Comment by iscai-msft** [comment]
> @iscai-msft is this because of the way `VaultProperties` is defined in the spec?

Yep, I checked the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/260aa3d5e9467700068787493861f92fc590800c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1107) and vaultUri is just defined as a string. In order to make it readonly, a line like [this](https://github.com/Azure/azure-rest-api-specs/blob/260aa3d5e9467700068787493861f92fc590800c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1160) needs to be added to its swagger definition

**Comment by sebansal** [comment]
Closing this issue as it is duplicate to Azure/azure-rest-api-specs#9432
