### ISSUE TITLE
VirtualMachineSizeTypes enum doesn't include H-series VMs

### ISSUE THREAD

**Issue by tstringer** [Azure/azure-sdk-for-python#1135]
The [`VirtualMachineSizeTypes` enum](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute/v2016_04_30_preview/models/compute_management_client_enums.py#L28-L92) doesn't include H-series VMs, like "Standard_H8".

This originally came up as an [issue in the ansible/ansible repo](https://github.com/ansible/ansible/issues/21825#issuecomment-298004639), and doing some digging it looks like [Ansible is doing a check to see if the passed in `vm_size` is contained in the `VirtualMachineSizeTypes` enum](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py#L514-L515).

Let me know if you'd like me to simply add the `Standard_Hx` VMs to this enum in a PR. Thanks! 😄

**Comment by hgoodrow** [comment]
The enum should not be a static list of VM Sizes.  There should be some way of listing the available VM Sizes to build the enum.  Otherwise when the next VM Size is released, the enum will be out of date.

**Comment by lmazuel** [comment]
@tstringer @hgoodrow The enum is provided as convenience list, but it has been discussed already with the Compute team that the list is not exhaustive (and cannot be).
It's why this enum is not strict in Python, and we take a random string OR an enum value.

Ansible must NOT force the VM size to be in the enum, it's an Ansible bug. Maybe they can log a warning, but they can't do more.

I'm closing this, since this is not a SDK bug and the code is as expected. Feel free to still comment if necessary :)

**Comment by tstringer** [comment]
That makes sense. I'll work on this on the Ansible side of dev to decouple this hard requirement.

Thanks!
