### ISSUE TITLE
Duplicate message to subscribers even using AutoLockRenew

### ISSUE THREAD

**Issue by deeagar** [Azure/azure-sdk-for-python#11611]
I am using AutoLockRenew class register method after receiving message from azure service bus topic subscription using azure sdk for python.

Even if you use AutoLockRenew.register() method in python which takes care of automatically renewing the lock for you - in case the renewable.renew_lock() throws an exception if message lock expired, it fails silently!

The parent thread which is still executing business logic keeps on executing (until it calls message.complete() when actually it would know about this) but the same time, the same message appears in the queue and second instance takes it up for processing! This mean the same message is now being processed simultaneously by 2 different receivers!

The exception should be propagated to the parent thread calling the auto renew so that it can stop processing the message and avoid duplicate message handling by another subscriber. 

Just wanted to understand is this by design and what was the original thought process in failing this exception silently on a different thread.

The code looks like below -

```
auto_renewer = AutoLockRenew()
with sub_client.get_receiver() as receiver:
    for message in receiver:
        auto_renewer.register(message)
        .......
```

**Comment by KieranBrantnerMagee** [comment]
Hey @deeagar, thanks for letting me pull you over here to continue the conversation, and again for coming to us with your question/your patience thus far.
Echoing my response from SO here with some verbosity (Due to lack of character limit)

You're correct that the purpose of locking is to prevent another subscriber from taking it, the subtlety here is that the lock _has_ been lost, it's just not doing so in a manner that throws an exception.  That is by design, and somewhat constrained by the language and calling pattern; we're limited in how we can expose an exception occuring out of band in a separate thread.  Instead we set the auto_renew_error property on the message to allow you to take action when you notice it, so it's hopefully not _entirely_ silent.  

(For other readers only seeing this half of the picture, I had previously detailed in SO [here](https://stackoverflow.com/questions/61888995/duplicate-message-to-subscribers-even-using-autolockrenew/61959869#61959869) a probable reason for this background expiry, and a way to proactively detect it sooner by observing the auto_lock_renew property)

Now, while this may be by design as it stands, you've asked this question at a very apt time; we're currently in the process of producing the GA version of this library, currently in preview. (7.0.0b2, excuse the large version gap, it's due to beurocratic reasons)  I mention this to give some context before I pose a question to you:  Given the above explanation and the prior details I provided on SO as to how this functionality works, is this still a source of confusion? (or would better documentation have addressed this)  If so, is there a pattern that would have been more intuitive to you as a user?  We've been contemplating this and other overlapping problems internally, and getting input from someone running up against this pragmatically would be very useful.

(To be clear; don't let the latter point distract from your core question, feel free to let me know if you had further followups or if I could clarify better, I just wanted to take this opportunity to try and get two birds with one stone)

**Comment by deeagar** [comment]
Thanks @KieranBrantnerMagee for detailed response. Few follow-up questions on this (I believe this would also take care of "two birds with one stone" you are talking about) - 
- I understand now this is by design and we could check the auto_renew_error property. However, question still remains as to how/when we should frequently check for auto_renew_error? Is there any callback (ideally)? We couldn't find any example or recommended practice of handling this in the main thread. It would be great if you can provide official comprehensive examples/sample code in an end-to-end way along with library release.

- When can we expect 7.0.0b2 to be GAed - as I understand this being more stable.

- You mentioned the library doesn't catch every possible exception but I do see a generic exception block `except Exception as e` - so I think it should take care of all exceptions, correct?

**Comment by KieranBrantnerMagee** [comment]
A few points in response.
1. Callback gets to my question of "what pattern do you expect" and unfortunately no, there is no callback in the existing library that would allow this, but I'll bring that suggestion up for 7.0 design; I can see the value in it.  I'll ensure we add samples for proper failure mode handling as well.  
To answer your question about watching for failure, I would check the value commensurate with how much processing too long is going to hurt you.  (e.g. if you have hours of work, maybe check every ten minutes or so).  For smaller workloads simply observing that the complete() failed is often enough feedback.  Let me emphasize though that I hope if you upgrade to 0.50.3 you may hit the lost-lock less often due to fixes we applied.

2. Retry is one of the many bits we're improving for the GA release, you're correct that there is not explicit settlement retry in the 0.50 libraries, but it will behave as you expect in 7.0.  You will have the ability to set the retry properties as well to dictate the nature of the behavior.  Ensuring the message doesn't reappear on the queue during retries is hard, as said there can be unavoidable reasons a lock can be lost, and trying to be too clever about addressing that in a distributed system as opposed to simply discarding the failure and trying again, can be a painful route.

3. A few points:  I would hope you can upgrade simply to 0.50.3 (our last non 7.0 release) for slightly more stability; I'm working under a hypothesis that you're seeing a known failure causing lock loss after 10 minutes of processing a single message (since we've seen other users hit this.)  7.0.0b2 is already released, but it is a preview release, 7.0.0 (no b's) will be GA, and we don't have a hard date on that yet other than that it is likely a few months out; we will be releasing b3 within the next few weeks, however.

4. Assuming you're talking about catching the complete() exception, yes, that would Catch All Exceptions pretty thoroughly.  (I should make some noises that "best practice" in python is to be targeted when catching exceptions, but in leiu of our having cleaned up exception hierarchy for V7.0, what you wrote might be the most effective approach without wasting your time catching edge cases.)

I believe this should address your questions but don't hesitate to let me know if I missed anything, or if something requires more drill-down, we'll be glad to help; thank you once again for your patience!

**Comment by deeagar** [comment]
Thank you Kieran for detailed explanation. However, I'm afraid, I still don't see much clarity on the solution. Comments below for some thoughts mentioned by you - 

_"To answer your question about watching for failure, I would check the value commensurate with how much processing too long is going to hurt you. (e.g. if you have hours of work, maybe check every ten minutes or so). For smaller workloads simply observing that the complete() failed is often enough feedback. "_
I don't think, writing a function in my main thread to watch for failures which executes every 'n' minutes/seconds would be a good design - it would be polling rather than event driven and that 'n' cannot be specified easily. I hope you understand, there would still be a possibility of ending up two instances processing the same message and we are back to square one. 
Consider this, how Azure function with service bus trigger work - it must also be using the locking and renew mechanisms and when locking doesn't happen, the Azure function code execution just aborts. We need to replicate exact same behavior here. If you can get details around this, would really help.


_"Ensuring the message doesn't reappear on the queue during retries is hard, as said there can be unavoidable reasons a lock can be lost, and trying to be too clever about addressing that in a distributed system as opposed to simply discarding the failure and trying again, can be a painful route."_
Again, I would cite the same example of how Azure function handles this internally. I hope you get that **it's business critical in production that same message cannot be processed/picked up by 2 or multiple instances simultaneously**. We can write code for idempotency check, but it has its own limits and we expect the libraries are smart enough to handle such basic cases for us out of the box - pre-empt the processing when such failure occurs. Again, we need to know how Azure function works and handles this behind the scenes - because we don't need to deal with such failures while writing business specific code - then wondering, why here?! Hoping you'll get back with more info on this... 

Let me know if anything is unclear from my end or need more information.

**Comment by deeagar** [comment]
Also, please note - I tried using the 0.50.3 library and it doesn't work when message LockTimeout period is maximum i.e. 5 minutes. Please try once at your end and let me know. The exception it gives is "AMQPConnectionError - Failed to open mgmt link: MgmtOpenStatus.Error".

With "7.0.0b2" it used to work earlier, but tried today and it is giving me lock lost exception almost every time. 
A sample python client code (recommended one) which is working (for both the package version) and taking original issue into account as an answer to this post would really help.

Looking forward for your response!

**Comment by KieranBrantnerMagee** [comment]
Hey Deeagar,

I'll address the two "thrusts" of the discussion I see us having above distinctly.
1. locking/guaranteed single-ownership.  You bring up Azure Functions.  I'd first observe that this isn't the most apt comparison, since they provide a full runtime, whereas we only provide an SDK.  As such, its their prerogative to do things such as interrupt your runtime if lock is about to be lost.  I would imagine (though I would need to reach out to the team to confirm this) they have an approach where a watchdog looks at the expiry time, and some delta beforehand, attempts to renew the lock.  If this fails and the message would be lost, processing is interrupted.  This is largely why I asked re: the callback approach, since this would let you be slightly more responsive to this same failure mode as opposed to having to poll the variable yourself, although the end result would be the same: if lock renewal fails, you must terminate your own processing to avoid concurrent ownership, if such a pattern is desired.  HOWEVER at the end of the day, recognize you still will have _some_ potential for double-processing, although not simultaneous.  The same would be true of Functions: You could have gotten 99% of the way through processing and written whatever result to your DB, only to have completion fail.  Without having those actions in a transactional scope this is unavoidable.  As a base "rule of distributed messaging" you either get receive-only-once (And if processing/locking fails it never gets received again) or receive-at-least-once, receive-exactly-once is a conceptual impossibility. (I don't think this is what you're asking for, I just want to be precise since the problem spaces overlap.)  I would hope the aformentioned explanation would answer the **simultaneous** double-processing concerns by ensuring you terminate the first processor before its lock would expire if you are unable to renew the lock.

2.  Now, I had earlier been assuming that you were running into _very rare_ occurances of lock renewal failure; or due to circumstance such as extremely long processing times.  Your post from Sunday implies you're running into something much more immediate; I would like to drill into this.  When you say LockTimeout, do you mean LockDuration, the property you set when creating a queue in ServiceBus?  This cannot be set more than 5 minutes as a service-level restriction.  If you meant a different LockTimeout period don't hesitate to clarify.  I have similar questions about the 7.0 release and the lock lost exception you're seeing, if you could show the code and exception/logs you're running into that would be appreciated, as we have this sample [here](https://github.com/Azure/azure-sdk-for-python/blob/f4aee7e3f8ff180a02d295c3686fb667201ddca9/sdk/servicebus/azure-servicebus/samples/sync_samples/sample_code_servicebus.py#L194) demonstrating basic autorenewer usage that seems to be working properly on my end.


Finally, two notes:
First, you asked regarding a sample; I have a feeling you won't like my response to this, since your snippet in the top post is _almost_ what you need, but the remaining bit will be VERY application specific (For instance, depending on app architecture, simply checking that you own the lock prior to committing the final result of your processing to an external store might be sufficient).  However, I'd emphasize that even in this happy-path case there can be pathological race conditions where, for instance, the lock would be renewed for N minutes, your code takes N+1 minutes to complete and all renewer threads are preempted such that it is not able to renew the lock.  This should almost never happen but CAN happen and thus application code should be written to be robust against it with idempotency at the synchronization point (e.g. DB) as you note above.  It is not sufficient to rely on thread-killing as well, as mentioned prior, this does not fully close the race.

```python
auto_renewer = AutoLockRenew()
with sub_client.get_receiver() as receiver:
    for message in receiver:
        auto_renewer.register(message)
        start_work()
        while not work_done():
            if message.auto_renew_error:
                stop_work()
                break
            time.sleep(max(0, (message.locked_until - datetime.now() - 1)).total_seconds)
```

Second, your customer support folks reached out to us over the weekend asking to set up a call, since this is a somewhat involved topic/conversation I'd be willing to hammer this out, so if that would help you let's get that set up so we can get you unblocked ASAP.

**Comment by deeagar** [comment]
Splendid ! Thanks Kieran for your detailed explanation - appreciate it!

- Internally here, we are also somewhat aligned with your thoughts on having those checks before committing to DB.
- Since you mentioned the code is working for you - I'll try from my end again today and let you know with complete stack trace if I get that exception.
- Yes, I mean LockDuration property of Service bus.
-  Yes, since this is more involved - a call would expedite closure. However, I'll get back to you and to our customer support regarding this - since what you mentioned is exactly what we discussed a while back internally as a possible design.

P.S.: When I mentioned Azure function, I am considering "Microsoft Azure" as one team and whatever we experience in different platforms on it, thought it should be consistent across in terms of architecture and design approach. Anyways, just my thought.

**Comment by deeagar** [comment]
@KieranBrantnerMagee  I verified and the renew_lock always fails with below error with 
`azure-servicebus==0.50.3` package giving below exception 
_'Management request failed: Failed to open mgmt link: MgmtOpenStatus.Error'_

Any reason why its not working with the stable version?

With `azure-servicebus==7.0.0b2`, it fails always with below exception
_Failed to complete mgmt operation.
Status code: 410
Message: b'The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:<some guid>, TrackingId:<some guid>_B2, SystemTracker:<service bus name>:Topic:<topic name>|<subscription name>, Timestamp:2020-06-02T07:16:19'_
Although, with 7.0.0b2 version, if I increase the renew_period in `AutoLockRenew `class of SDK from 10 to say 50, it works. I think its taking time to renew which is more than 10 seconds. 

So, immediate blocker on both version - would like to use the stable version in production anyways.
Looking forward for your response.

**Comment by deeagar** [comment]
@KieranBrantnerMagee Thanks for getting back. Sorry didn't get back to you soon, was caught up in other things.

Firstly, I don't understand why I'd need to supply 'timeout' parameter. The execution of code has (or might have) many external calls and its always difficult to find how much time it will take to execute in a distributed. We just hope for the best and prepare for the worst. IMO, once I register with auto_renew.register() method, as long as the program is running, it should just renew for me the lock when before it expires. 
When I see the library code, I see the use of timeout in below code and not sure why we need that if condition in first place. If main program execution stops abruptly due to any exception or something, or completes with message.complete() - shouldn't we consider that as an indication for the end of execution of auto_lock_renew thread for that message? 

```
            while self._renewable(renewable):

                # Don't understand why do we need this check in first place?
                if (utc_now() - starttime) >= datetime.timedelta(seconds=timeout):
                    _log.debug("Reached auto lock renew timeout - letting lock expire.")
                    raise AutoLockRenewTimeout("Auto-renew period ({} seconds) elapsed.".format(timeout))

```

Secondly, I tried with your suggestion and see same issue. The exception occurs after 5 minutes when we try to renew_lock. Below is the code and exception -
![error](https://user-images.githubusercontent.com/45327371/83943351-f4534200-a818-11ea-968a-0c0fd5be876e.png)

Let me know if I'm missing anything here. Looking forward for your response.

**Comment by KieranBrantnerMagee** [comment]
No worries whatsoever (Re: time to respond back).  I should be thanking you for your patience as we work through this.

The timeout long predates me so this is an assumption, but I believe it exists to try and avoid a scenario where a caller processes indefinitely (as a problem, not intentionally), and never releases a message back to the queue to be taken by another node.  Whether we should allow a user to say "None" with the implicit "caveat emptor" may be an option the team can discuss if that would make your life easier.

I would note that if the main thread terminates, the renewer would likely terminate as well, since it's only split off via a python thread.  Similarly, to your point about if complete() should stop renewal, it does:  observe `while self._renewable(renewable):` on line 214.

Now, your code and still observing the failure is fascinating.  I have the following sample code [here](https://gist.github.com/KieranBrantnerMagee/e403c4f77f630d6664243dd52721fae3) which I've been using for comparison and it appears _very similar_ to the point that i'd be hard pressed to say that we're even doing anything differently.  (I've done my sample with both queues and topics, to be precise, same behavior in both cases).  
This begs the question for me, "what is actually different" and my head starts going towards how the topic/subscription you're using were created, assuming you don't see anything glaringly different in my sample code above. @sagar027 actually pointed out something interesting when we synced on this, that when he created via the control_client code in python, the subscription when viewed in the Azure Portal had some _very strange_ settings, and his version of this code was failing as well, albeit with different symptoms.  I'd be curious how you did creation, and if you create the topic and subscription via the Azure Portal with default settings, if it behaves as expected.  So to be clear, here's the action I'd take (and as I understand we'll be having another call shortly to sync on this as well):
1. Create a clean topic and subscription via the Azure Portal, and perform this test against them, using default settings.
2. Enable logging as demonstrated in my example (for both 'azure' and 'uamqp' loggers, as well as setting debug=True when creating your ServiceBusClient).  This log would be invaluable for seeing what's going on behind the scenes if 1 does not fix the problem.

As always don't hesitate to let me know if I can clarify anything.

**Comment by deeagar** [comment]
Thanks @KieranBrantnerMagee for your response. With exactly the same code and enabling logging as you demonstrated for version 0.50.3 - same error. We can more deeper look over scheduled call of-course. 
Attached is the complete error trace which I get from logging. 
[error.txt](https://github.com/Azure/azure-sdk-for-python/files/4750964/error.txt)

Some important points to note - 

- Your suggestion of option 1 above of performing test by creating Azure portal - we can definitely do this. However, not sure how the findings will help. Even if it works, we would want this to make it work in our product which creates topic and subscriptions programmatically via .Net nuget package WindowsAzure.ServiceBus (3.4.6)
- Since this needs to be part of our product release soon, I'd like to focus this investigation on the current stable version of azure-servicebus python package i.e. 0.50.3
- Use LockDuration as 5 minutes for your testing if not already set. 

Below is my code for your reference
```
import logging
import sys
import time
import re
from datetime import datetime
from azure.servicebus import ServiceBusClient, AutoLockRenew

auto_renewer = AutoLockRenew()
service_bus_client = ServiceBusClient.from_connection_string(
    "REDACTED", debug=True)

sub_client = service_bus_client.get_subscription(topic_name="REDACTED", subscription_name="REDACTED")


def get_logger(level):
    azure_logger = logging.getLogger("azure")
    handler = logging.StreamHandler(stream=sys.stdout)
    if not azure_logger.handlers:
        azure_logger.setLevel(level)
        handler.setFormatter(logging.Formatter('%(asctime)s %(name)-12s %(levelname)-8s %(message)s'))
        azure_logger.addHandler(handler)

    uamqp_logger = logging.getLogger("uamqp")
    if not uamqp_logger.handlers:
        uamqp_logger.setLevel(logging.INFO)
        uamqp_logger.addHandler(handler)
    return azure_logger


get_logger(logging.DEBUG)

with sub_client.get_receiver() as receiver:
    for message in receiver:
        try:
            auto_renewer.register(message, timeout=420)
            # This is where the business logic executes. Takes more than 5 minutes
            time.sleep(360)
            message.complete()
        except Exception as ex:
            print('Exception: ' + str(ex))
```

**Comment by deeagar** [comment]
@KieranBrantnerMagee I see your code uses queues - I wonder why in this context. Anyways, I've used exactly your code with below change suggested by @sagar027

```
with service_bus_client.get_topic("test_topic").get_sender() as sender:
    print("Sending Message====================================")
    sender.send(Message("test1"))
    print("Sending Message====================================")
    sender.send(Message("test2"))
 
with service_bus_client.get_subscription("test_topic", "test").get_receiver() as receiver:
    for message in receiver:
        print("Got Message: " + str(message))
        auto_renewer.register(message, timeout=5*60)
        # This is where the business logic executes. Takes more than 5 minutes
        time.sleep(2 * 60) #... some business specific code... 
        message.complete()
        print("Done completing message")
 
print("Done")
input()
```


Update - Just for testing purpose, I created new topic-subscription from Azure portal (keeping all defaults) - create a new venv for my python code - installed 0.50.3 version of python service bus package - used your code with above changes - didn't work. 

Gives me following error - 

```
2020-06-09 15:56:31,778 uamqp.mgmt_operation ERROR    Failed to complete mgmt operation.
Status code: 410
Message: b'The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:REDACTED_GUID, TrackingId:REDACTED_GUID_B4, SystemTracker:deetestlockrenew:Topic:testtopic|testsubscription, Timestamp:2020-06-09T10:26:42'
2020-06-09 15:56:31,778 uamqp.c_uamqp INFO     b'-> [DISPOSITION]* {true,2,2,true,* {}}'
2020-06-09 15:56:31,778 azure.servicebus.common.utils DEBUG    Failed to auto-renew lock: ServiceBusError("Management request failed: b'The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference: REDACTED_GUID, TrackingId: REDACTED_GUID_B4, SystemTracker:deetestlockrenew:Topic:testtopic|testsubscription, Timestamp:2020-06-09T10:26:42'",). Closing thread

```

**Comment by KieranBrantnerMagee** [comment]
Echoing our out-of-band conversation for progeny who finds this thread:

Once again the logs to the rescue; the full logs you linked contained the key breadcrumb: That when you set the lock duration at 5 minutes, the supposed maximum on the server, for whatever reason the expiry would show up as > than the 5 minute threshold, and thus the lock would be expired by the time we went to renew it.

When tuning to a lower value than 5 minutes we found a second problem via the error "the connection was inactive for more than the allowed 240000 milliseconds".  This was caused by setting the renew_period to be >4 minutes, after which due to idle on the link, the service would close the connection.

We've worked around both these issues by setting lock duration on the service entity to be <5 minutes, and either leaving renew_period at its default value, or using a value below 4 minutes.

We'll be closing this thread as resolved and tracking the work to investigate and address the aformentioned issues [here](https://github.com/Azure/azure-sdk-for-python/issues/11935)

Thanks once again for all your patience as we worked through this @deeagar; feel free to reach out or reopen this if any further issues or anything we can help with.

**Comment by deeagar** [comment]
Hi @KieranBrantnerMagee,

Hope you are doing well..! 

We've been using this work-around mentioned above from past few months and while its working, we do get AutoLockRenew errors frequently with reasons all mentioned in our previous conversation.

Just wanted to check - do we have time frame when the 7.* version of this package will be GAed and we can expect some consistent and more deterministic behavior from this? It's been a while since its in preview.

Thanks!
Deepak Agarwal.
