### ISSUE TITLE
Outdated links to old "azure" package in READMEs

### ISSUE THREAD

**Issue by toelli-msft** [Azure/azure-sdk-for-python#11624]
The README files for the individual packages contain references to the old "azure" package, like

> For a more complete set of Azure libraries, see the azure bundle package.

For example, https://github.com/Azure/azure-sdk-for-python/blob/7a432a8240d7dd5766f7fd2cdb2e778a3308b11e/sdk/cognitiveservices/azure-cognitiveservices-anomalydetector/README.md

However, the ["azure" package](https://pypi.org/project/azure/) says

> Starting with v5.0.0, this package is deprecated. Please install the service specific packages prefixed by azure needed for your application.

so it looks like the individual packages' READMEs are outdated.

**Comment by lmazuel** [comment]
Hi @toelli-msft 

We changed our template and new packages does not refer to it anymore. However, every packages we didn't release since the change are still mentioning it, they will slowly auto-update as releases comes. We do not plan a massive repo change, since the content is actually the one of the latest release of PyPI.

Does that solve your question?

**Comment by toelli-msft** [comment]
OK, thanks!
