### ISSUE TITLE
[Key Vault] Using Key Vault quickly after create fails

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-python#1172]
Related issue from Azure CLI: https://github.com/Azure/azure-cli/issues/3348

Unlike other services which create DNS entries (storage, cdn, service bus, etc...), it seems that Key Vault instances are not directly addressable after initial creation. That is, after successfully creating an instance of a Key Vault, there is a period of time where any data plane action will fail.

**Comment by lmazuel** [comment]
FYI @schaabs

**Comment by schaabs** [comment]
This has been fixed in the 1.0.0b1 release of the azure-keyvault package.  The operation has been marked long running so the generated code now returns a polling result rather than returning the vault directly.  Accessing the result() method on the value returned from vaults.create_or_update will properly poll until the vault is finished provisioning and the DNS entries have replicated.
