### ISSUE TITLE
Deleting disks, NICs and other resources when deleting a VM

### ISSUE THREAD

**Issue by ashisa** [Azure/azure-sdk-for-python#11735]
- **Package Name**: Azure SDK for Python
- **Package Version**: *
- **Operating System**: Ubuntu 18
- **Python Version**: 3.6

**Describe the bug**
When we delete a VM, the disks and NICs etc are left behind. The SDK doesn't seem to delete everything related to the VM.

**To Reproduce**
1. Delete a VM using the SDK and observe the leftover artifacts

**Expected behavior**
Delete all the linked resources when a delete has been issued for a VM

**Screenshots**

**Additional context**
Looking at the SDK, I don't see an option to achieve this behavior. Is there something that I have missed?

**Comment by Drewm3** [comment]
This is the expected behavior. Disks and NICs which are no longer needed need to be deleted independently unless the resource group that contains the disks and/or NICs is deleted. 

We are investigating the possibility to have a simple manner to delete the VM and trigger Azure Resource Manager to automatically delete the associated disks and NICs, but this is a separate feature. For feature requests please use http://feedback.azure.com.
