### ISSUE TITLE
Python: Support 'Delete' eviction policy for Azure Spot Standalone VMs

### ISSUE THREAD

**Issue by rakeshakkera** [Azure/azure-sdk-for-python#11945]
**Is your feature request related to a problem? Please describe.**
Currently Azure Spot standalone VMs only support eviction policy of 'Deallocate'. We have made changes in the CRP service for standalone Spot VMs to support 'Delete' eviction policy as well. Changes need to be made in Python SDK should to support this.

**Describe the solution you'd like**
Currently Python SDK blocks choosing 'Delete' eviction policy for Standalone Spot VMs. Changes need to be made to support this. Here is the link to the swagger PR for this change: Azure/azure-rest-api-specs#9743

**Describe alternatives you've considered**
NA

**Additional context**
Swagger PR: Azure/azure-rest-api-specs#9743

**Comment by qiaozha** [comment]
@rakeshakkera  Hi, I am confused. The swagger PR link you attached only changed the description of evictionPolicy. and the description in python sdk has already include both 'Deallocate' and 'Delete' https://github.com/Azure/azure-sdk-for-python/blob/release/v3/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py#L7853. 
And since the enum value evictionPolicy has included 'Delete' for a long time. I don't think there's anything SDK can do to block the user pass 'Delete`.
What else do you need from us?
