### ISSUE TITLE
lint issue in azure core 

### ISSUE THREAD

**Issue by changlong-liu** [Azure/azure-sdk-for-python#11980]
The pipeline task PyLint failed In this PR: https://github.com/Azure/azure-sdk-for-python/pull/11949.

I found below in the task detail log:
************* Module azure.core.polling._poller
azure/core/polling/_poller.py:34: [W0611(unused-import), ] Unused Tuple imported from typing

It seems will block all PR, shall we have an urgent fix on it?

**Comment by lmazuel** [comment]
@scbedd is there a reason why pylint is failing here, and was not failing before?

**Comment by scbedd** [comment]
@lmazuel I spent a couple hours yesterday trying to track this down. This does not repro locally, and as far as I can tell the environment dep and python versions are identical. 

Submitted a [PR](https://github.com/Azure/azure-sdk-for-python/pull/11966) that has since been supplanted by Xiang, but could have unblocked CI with an approval and a merge. Check teams channel for further discussion.

I'm closing this issue in favor of this [other issue](https://github.com/Azure/azure-sdk-for-python/issues/11967) that details the problems.
