### ISSUE TITLE
Enable configuring HttpLoggingPolicy allow list at initialization

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#12153]
Key Vault has custom diagnostic headers whose values are by default redacted by `HttpLoggingPolicy`. Preventing that redaction requires instantiating a policy then modifying its allow list:
https://github.com/Azure/azure-sdk-for-python/blob/2c8bfa1277094260cf9d4b8a7b97aefa928d7d0f/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py#L29-L32

It would be nice if the policy instead accepted these as optional keyword arguments, enabling usage like
```py
HttpLoggingPolicy(additional_allowed_headers=["x-key-vault-stuff"])
```
or
```py
HttpLoggingPolicy(allowed_headers=HttpLoggingPolicy.DEFAULT_ALLOWED_HEADERS.union(["x-key-vault-stuff"]))
```

**Comment by lmazuel** [comment]
I remember @johanste got strong opinions on this, that this list was SDK specific and that we shall not expose a kwarg accessible to customers. Thoughts?

**Comment by iscai-msft** [comment]
As an added note, this would help with how the wrapped code interacts with the new autorest generated code. With this change, we would just be able to pass the kwarg directly to the generated client, instead of having to pass in the `policies` kwarg to the generated client that includes the [list of all the policies](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/_pipeline_client.py#L105)

**Comment by johanste** [comment]
The primary consumer of the allow list is indeed the service specific client library. I don't know of any scenarios where a caller of the library would write code to add more headers to the allow list rather than just enable network level logging. But, as always, I am game for being proved incorrect - so if there are valid scenarios where a user of a client library would need this, I'm all game. 

There is often a special case for hand-written code wrapping generated code where we can decide if we document the `kwargs` or not. Or we can add generator parameters to bake in the library specific data into the generated code.

**Comment by iscai-msft** [comment]
After talking to @lmazuel we have decided to expose property `http_logging_policy` on the Configuration object, which will allow users to individually set the http logging policy without having to pass in the whole [list of policies(https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/_pipeline_client.py#L105).

There will be one PR in azure-core and azure-mgmt-core, and one in autorest to support the full end to end scenario
