### ISSUE TITLE
Custom Credentials Class only called onced to retrieve AccessToken (no support for user authenticated long running script)

### ISSUE THREAD

**Issue by cccs-jc** [Azure/azure-sdk-for-python#12188]
- **Package Name**: 
azure-identity==1.3.1, azure-storage-file-datalake==12.0.1
- **Operating System**:
linux
- **Python Version**: 
3.6

**Describe the bug**
The DataLakeServiceClient does not call the custom credentials class get_token method every time it makes an API call. It is thus not possible to have long running scripts which use this client. The AccessToken returned by the custom credentials class sets an expiry however the SDK does not make use of it and calls the get_token method only once.  If the SDK called the get_token once the AccessToken expired it would enable the use of oauth user credentials in long running applications.

**To Reproduce**
```
import jwt
import adal
import time
from azure.core.credentials import AccessToken

# A custom credentials class which returns an AccessToken while checking for expiry.
class RefreshTokenCredential(object):
    def get_token(*scopes, **kwargs):
        global datalake_access_token
        global datalake_refresh_token
        global EXPIRY_THRESHOLD
        # Check if token is about to expire
        access_token_contents = jwt.decode(datalake_access_token)
        token_expiry = access_token_contents['exp']
        time_now = time.time()
        if token_expiry - time_now < EXPIRY_THRESHOLD:
            # Get a new access token using the refresh token
            authority_url = "https://login.microsoftonline.com/" + os.getenv('APP_TENANT_ID')
            authentication_context = adal.AuthenticationContext(authority_url)
            response = authentication_context.acquire_token_with_refresh_token(datalake_refresh_token, os.getenv('APP_CLIENT_ID'), "https://datalake.azure.net", os.getenv('APP_CLIENT_SECRET'))
            datalake_access_token = response['accessToken']
            # Determine new token expiration
            access_token_contents = jwt.decode(datalake_access_token)
            token_expiry = access_token_contents['exp']
            # Renew refresh token if we get one back
            if 'refreshToken' in response:
                datalake_refresh_token = response['refreshToken']
        return AccessToken(datalake_access_token, token_expiry)

service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
                "https", "storageaccountname"), credential=creds)

long running for loop
    service_client.get_file_system_client(file_system='somecontainer').get_paths(path='/', recursive=False)
```
**Expected behavior**
I was expecting the service client to call the get_token on every API call or at a minimum when the AccessToken which is returned expires.

**Comment by cccs-jc** [comment]
yes this is still an issue for long running scripts.

**Comment by jalauzon-msft** [comment]
Hi @cccs-jc, sorry for the long delay but I did some testing on this with the latest versions of datalake, core, and identity and was able to see that `get_token` is called when we detect a token that is within 300 seconds of expiring and this is evaluated on each HTTP request that is made. We use the `expires_on` field of the provided `AccessToken` to determine expiration time.

This is done through the `BearerTokenCredentialPolicy` from `azure.core` that we add to the HTTP pipeline for every client. This code is evaluated on every request based on the `AccessToken` that was returned via `get_token`.
https://github.com/Azure/azure-sdk-for-python/blob/2ea74b552e7f647f9f04ac484624f8ca58f962c6/sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py#L87-L89

And then you can see the definition of `self._need_new_token`
https://github.com/Azure/azure-sdk-for-python/blob/2ea74b552e7f647f9f04ac484624f8ca58f962c6/sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py#L65

I verified this functionality with a custom credential class that fetched a token and returned it with a very short expiration and then made many HTTP calls. Each HTTP call called `get_token` as expected.

From what I can tell this auto-refresh code should have been present in the versions of datalake and core you were originally using but since this was reported on quite old versions, I would try updating to the latest `azure-storage-file-datalake` and `azure-core`, if you have not done so already, and seeing if this fixes the issue (assuming you are still facing this issue). Thanks.
