### ISSUE TITLE
Throwing an error using Cognitive Services Custom Vision

### ISSUE THREAD

**Issue by datascinerd** [Azure/azure-sdk-for-python#12383]
I'm getting an error attempting to train a model using Custom Vision. My code hasn't changed in several months and worked as late as 6/9/2020. It seems to be attempting string functions against Custom Vision objects.

The images in question are URLs stored in a Pandas dataframe.

for index, row in train.loc[train['audit_label'] == tag].iterrows():
trainer.create_images_from_urls(project.id, [ImageUrlCreateEntry(url=row['image_url'], tag_ids=[project_tag.id])])

SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'ImageUrlCreateEntry' object has no attribute 'lower', DeserializationError: Unable to deserialize to object: type, AttributeError: 'ImageUrlCreateEntry' object has no attribute 'lower'

[Attribute Error Full Text.txt](https://github.com/Azure/azure-sdk-for-python/files/4880991/Attribute.Error.Full.Text.txt)

**Comment by lmazuel** [comment]
Hi @datascinerd 
I would assume that you updated customvision SDK from 2.x to 3.x, could you confirm the version of the SDK you are using? This API changed in 3.x
Thank you

**Comment by datascinerd** [comment]
Yes this is SDK 3.x.

**Comment by areddish** [comment]
@datascinerd The 3.0 SDK changed the signature of `create_images_from_urls` such that it now takes an ImageUrlCreateBatch instead of the raw list. You will need to update the code to construct the batch and pass that. For example:

`trainer.create_images_from_urls(project.id, ImageUrlCreateBatch(images=[ImageUrlCreateEntry(url=row['image_url'], tag_ids=[project_tag.id])]))`
