### ISSUE TITLE
 ATOM API update, should use distinct class from create for non-writeable fields

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#12414]
Should we limit the fields that we allow to be updateable when performing an Update operation vs Create?
(to better communicate to a user that certain fields cannot be changed and will error)

**Comment by KieranBrantnerMagee** [comment]
Transferring to Yijun due to accidental duplication of tracking issue; see prototype and arch review q&A here https://github.com/Azure/azure-sdk-for-python/pull/12741

**Comment by YijunXieMS** [comment]
Two changes made in PR #12829 regarding this issue. 
1. Removed updatable properties from **kwargs of update_queue method. Users should update the input queue object. Same applies to Topic, Subscription and Rule
2. create_queue now uses **kwargs instead of QueueProperties as input. Same for Topic, Subscription and Rule
