### ISSUE TITLE
migrate GraphRbacManagementClient to Microsoft Graph

### ISSUE THREAD

**Issue by GitelGeiger** [Azure/azure-sdk-for-python#12513]
Why does GraphRbacManagementClient from azure-sdk-python call to Azure AD Graph API (https://graph.windows.net/) and does not support Microsoft Graph (https://graph.microsoft.com/)?

https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-or-azure-ad-graph/ - "Starting June 30th, 2022, we will end support for and Azure AD Graph and will no longer provide technical support or security updates. Apps using Azure AD Graph after this time will no longer receive responses from the Azure AD Graph endpoint."

So what will happen to this library? There is a plan to refactor?

**Comment by lmazuel** [comment]
Hi @GitelGeiger 
The graph SDK you are looking for is here: https://github.com/microsoftgraph/msgraph-sdk-python-core

I could not give much update on it, since it's not part of Azure and our org. 

This also means that "azure-graphrbac" will keep its current status: Azure AD Graph API as its name suggest it. This will be stored in this repo, since it's part of the azure story.

Hope this clarifies! Let me know if there is anything else I can do to answer.

**Comment by GitelGeiger** [comment]
Hi @lmazuel , thanks for your answer!

Does Microsoft Azure plan to officially maintain or support this SDK? I don't see any officially documentation.
Or maybe will be another alternative?

**Comment by lmazuel** [comment]
Hi @GitelGeiger 
This SDK will stay operational as long as the endpoint is available. We will fix bugs that would apply to the Python wrapping layer, but bugs in the RestAPI service itself are unlikely to be addressed, neither new features (but this question would have to be addressed with the AD team as needed, we're just Python messenger :)).

**Comment by GitelGeiger** [comment]
Ok, thank you!
