### ISSUE TITLE
Issues are being unintentionally ignored when issues are marked closed and others continue to find problems.

### ISSUE THREAD

**Issue by fedler** [Azure/azure-sdk-for-python#12517]
First, can someone please look into issue #9076 It's affecting a lot of people and seems that it would not take a lot of work to close out.

Second, I believe when the following event order takes place that issues are effectively being unintentionally ignored.

1. Someone raises an issue.
1. A dev works on and closes the issue.
1. People return to the issue and leave comments that it is not resolved.

**Comment by lmazuel** [comment]
Hi @fedler 

Thanks for your report, I agree with you this is not ok to miss notifications because issues are closed :(. I'll take the opportunity of your issue to re-discuss this with our team at the next stand-up, and clarify expectation on Github follow-up.

I let you decide when to close this issue, I feel like closing it myself would sound like a paradox somehow :). But be sure the message is heard loud and clear.

Thanks! Appreciate your report.

**Comment by fedler** [comment]
Thanks for the quick response. I've seen an update to the original post and will close this one out.
