### ISSUE TITLE
KeyVault SDK must have the CustomHookPolicy in their pipeline

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-python#12603]
This allows the injection of kwargs raw_response_hook/raw_request_hook

FYI @johanste

**Comment by lmazuel** [comment]
Side note, there is an instance already in the generated code, but it's not plugged in the policies list:
https://github.com/Azure/azure-sdk-for-python/blob/117a6f509d5995ed2c56aca3d134b093e019b577/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/_generated/v7_0/_configuration.py#L46

https://github.com/Azure/azure-sdk-for-python/blob/117a6f509d5995ed2c56aca3d134b093e019b577/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py#L35-L45

**Comment by iscai-msft** [comment]
@lmazuel we have PRs out to switch all of the keyvault code to the new autorest generated code, ex [here](https://github.com/Azure/azure-sdk-for-python/pull/12101/files#diff-5226c27f7f7470a20755f1dd4078b214R33). We haven't merged these yet since we're waiting for the service to make the 7.1 swagger GA and will merge once we have that generated code. Once these are merged, this issue should be fixed as well

**Comment by lmazuel** [comment]
@iscai-msft given that KV has its own pipeline definition, a regeneration of code wouldn't be enough, unless you stop doing your own pipeline
