### ISSUE TITLE
Refactor proactive refresh logic for better reuse

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#12601]
This logic:

~~~ python
if not token:
  # get new token
elif should_refrsesh:
  try:
     # get new token
  except Exception:
     # swallow
~~~

seems to be present in most if not all the credentials. Perhaps it could be moved into a base or mixin, and have the implementation just provide a callback or an override for the `# get new token` functionality?

_Originally posted by @schaabs in https://github.com/Azure/azure-sdk-for-python/pull/12136_

That comment thread also has a sketch of a potential solution:
```py
class CredentialBase(ABC):
    def __init__(self, **kwargs):
        self._client = AadClient(...)

    def _get_token_impl(self, *scopes, **kwargs):
        if not scopes:
            raise ValueError('"get_token" requires at least one scope')

        token = self._client.get_cached_access_token(scopes)
        if not token:
            token = self._request_token(scopes, **kwargs)
        elif self._client.should_refresh(token):
            try:
                self._request_token(scopes, **kwargs)
            except Exception:  # pylint:disable=broad-except
                pass
        return token

    @abc.abstractmethod
    def _request_token(self, *scopes, **kwargs):
        pass

class Credential(CredentialBase):
    def get_token(*scopes, **kwargs):
        """user-facing docstring"""
        return self._get_token_impl(*scopes, **kwargs)

    def _request_token(*scopes, **kwargs):
        """get a new token according to this credential's personal idiom"""
        ...
```

**Comment by legra-ms** [comment]
Hi @chlowell, 

I have a potentially long running script that creates an  aio.AzureCliCredential object at the beginning and makes a whole bunch of requests. If the runtime lasts more than an hour (the default token expiry time), the script will break because the access token has expired.

I noticed that some other credential classes utilize the `should_refresh` function. Based on the talk around this issue/PR, would it be possible to add something like that for AsyncCredentialBase and/or AzureCliCredential as well and check for the refresh timeout before invoking the `az` command? 

If I need to create a new issue, lemme know. Thanks.

**Comment by chlowell** [comment]
#13053 added [`GetTokenMixin`](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py) as a general solution. The remaining work here is refactoring credentials to use it.
