### ISSUE TITLE
[azure-cognitiveservices-knowledge-qnamaker] Make it a major bump since it now has 2 packages

### ISSUE THREAD

**Issue by bingisbestest** [Azure/azure-sdk-for-python#12635]
- **Package Name**:  azure-cognitiveservices-knowledge-qnamaker
Please release a major version bump since it now has 2 packages

**Comment by bingisbestest** [comment]
Since the current package has some breaking changes I think the suggestion from @diberry  was to release it as a new major version rather than a minor version release. Hope that makes sense. Thanks.

**Comment by lmazuel** [comment]
Since it's a preview 0.x versioning scheme at this point, there is no concept of "major version" yet:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/CHANGELOG.md

We'll make sure that once this package is stable, we follow semver correctly. Thanks!
