### ISSUE TITLE
support azure storage table

### ISSUE THREAD

**Issue by xinyeah** [Azure/azure-sdk-for-python#12772]
Do we have any plan to support azure storage table?

**Comment by annatisch** [comment]
Thanks for your interest! We actually have an SDK in development:
Current development progress: https://github.com/Azure/azure-sdk-for-python/issues/12311
PR: https://github.com/Azure/azure-sdk-for-python/pull/12766

Rather than Storage Table - it will likely be published as `azure-data-tables` - and we are hoping to ship the first preview in September.

**Comment by xinyeah** [comment]
Thanks for your reply. Looking forward to that SDK.
