### ISSUE TITLE
[ServiceBus] Add dictionary support to more models in mgmt plane like *RuntimeProperties

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#12957]
(spawned from issue https://github.com/Azure/azure-sdk-for-python/issues/11865)

current we just add dictionary support (`DictMixin`) to *properties models in the `azure.servicebus.management` modules:

e.g.:

https://github.com/Azure/azure-sdk-for-python/blob/77a1abaea4d2bb07e3abf20020e82dc7195a5fe3/sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py#L124-L140

we have the python design guideline to support dictmixin for input configuration models.
Consider adding support to more models for consistency, *RuntimeProperties, rule info, etc.
please note that those `*RuntimeProperties` so far are for read-only purpose. If we feel converting them to be dict-like obj is of no use, then we can close the issue.

e.g.:

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/azure/servicebus/management/_models.py#L395-L396

**Comment by KieranBrantnerMagee** [comment]
There are a few considerations to keep in mind:

Do we want to maintain immutability of some of the models that come from the service ala RuntimeProperties?  Is this enough of a motivation to not dictify them, or would we want consistency and read-only dicts? (or are we overthinking this and since it's python just let them change everything?  I'm just concerned that if we have an opportunity to provide information/guardrail, it might be worth using, but am curious to hear what architects think)
