### ISSUE TITLE
[keyvault] add tests with premium SKU key vaults

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#13041]
adding since JS saw issues where we weren'nt supporting RSA-HSM operations

**Comment by chlowell** [comment]
Closing this because `KeyVaultPreparer` [defaults to creating premium vaults](https://github.com/Azure/azure-sdk-for-python/blob/b9cc959187e72ae5c6dc338c9fb7c2151156bf58/tools/azure-sdk-tools/devtools_testutils/keyvault_preparer.py#L39). We also have some coverage of [RSA-HSM keys](https://github.com/Azure/azure-sdk-for-python/blob/b9cc959187e72ae5c6dc338c9fb7c2151156bf58/sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py#L56).
