### ISSUE TITLE
[Checkpoint Store] Exception KeyError('ownerid')

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/azure-sdk-for-python#13060]
- **Package Name**: azure-eventhub-checkpointstoreblob-aio
- **Package Version**: 1.1.0
- **Operating System**: N/A
- **Python Version**:  3.x

**Describe the bug**
A user reported an error in [stackoverflow](https://stackoverflow.com/questions/63354884/azure-eventhubs-python-checkpointing-with-blob-storage-keyerror-issue-in-ev/63366461#63366461).
The following error message was printed out when the checkpoint store is used.

_EventProcessor instance 'xxxxxxxxxxx' of eventhub <name of my eventhub> consumer group <name of my consumer group>. An error occurred while load-balancing and claiming ownership. The exception is KeyError('ownerid'). Retrying after xxxx seconds_

According to the user, all blobs under the container have metadata "ownerid". This error should only happen when a retrieved blob doesn't have "ownerid" in metadata, which isn't supposed to happen. Currently it's not clear what caused the "ownerid" not exist in the blob metadata.

**To Reproduce**
Not known yet.

**Expected behavior**
No error happens

**Comment by YijunXieMS** [comment]
This problem might be related to storage service. The user said in stackoverflow:

_I might have found what's causing the issue; I tested in fresh a venv with python 3.7.7 64bit installed. I created two new storage accounts from scratch (azure general storage v1 and v2) and made new containers in each. The issue only occured (and kept occuring) when I used azure storage V2 for checkpointing; Everything ran fine when I instead connected to the azure storage V1 account. This might be worth looking into._

Then I tested both azure storage general v1 and v2. But I didn't see any problems in both versions.
Asked the user to tell more information about his storage account settings and his region to try again.

**Comment by yunhaoling** [comment]
conclusion:

The root cause is that the `list_blob` functionality when called on a v2 storage blob with data lake enabled will not only get the per-partition checkpoint/ownership but also get the parent blob node which contains no metadata.

To illustrate this better, let's say we have the following blob structures:
```
- fullqualifiednamespace (directory)
  - eventhubname (directory)
    - $default (directory)
        - ownership (directory)
          - 0 (blob)
          - 1 (blob)
          ...
```

in v2 storage with data lake enabled, when the code was using
`{<fully_qualified_namespace>/<eventhub_name>/<consumer_group>/ownership ` to search for blobs, the `{<fully_qualified_namespace>/<eventhub_name>/<consumer_group>/ownership ` directory itself would also be returned containing no metadata leading to the `KeyError` when we're trying to extract information.

What we want is the per-partition blob, the the fix is easy: we add a `/` at the end of the prefix search string such that `list_blob` won't return the parent node.
`{<fully_qualified_namespace>/<eventhub_name>/<consumer_group>/ownership /`

(Checkpoint would encounter the same problem)

**Comment by yunhaoling** [comment]
bug fix version released:

[azure-eventhub-checkpointstoreblob 1.1.2](https://pypi.org/project/azure-eventhub-checkpointstoreblob/)
[azure-eventhub-checkpointstoreblob-aio 1.1.2](https://pypi.org/project/azure-eventhub-checkpointstoreblob-aio/)

**Comment by GuyCarmy** [comment]
Hi @yunhaoling and @YijunXieMS 
Im getting the same error exactly on version 1.1.4.
It started when I have tried upgrading the storage account to premium (since the checkpoint doesn't really store anything, but do access the files metadata a lot, using premium will cut the costs and improve the performance!).
I have copied an existing set of blobs for checkpoints and ownerships, I have validated that the metadata has been copied.

I guess something similar to this issue happens because the response from the premium storage account is a bit different?

will appreciate any help :)
