### ISSUE TITLE
azure-servicebus python SDK to support AMQP

### ISSUE THREAD

**Issue by andreycpp** [Azure/azure-sdk-for-python#1312]
It turns out Azure ServiceBus supports two APIs: REST and AMQP:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview
https://docs.microsoft.com/en-us/rest/api/servicebus

It also turns out that C# and Java SDKs support AMQP, while python and nodejs do not.

This leads to interoperability issues like discussed here: https://stackoverflow.com/questions/33542509/interoperability-azure-service-bus-message-queue-messages

Messages received from an AMQP sender have a weird prefix @\x06string\x083http://schemas.microsoft.com/2003/10/Serialization/\x9a\x0e\x01 and \x01 suffix around the message.

This is a request for python SDK to support AMQP for message interoperability with C#/Java

**Comment by andreycpp** [comment]
The "AMQP support" article on microsoft.com has a link to 'Using Service Bus from Python with AMQP', however that link resolves to the standard python SDK article, nothing about AMQP:

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-python

**Comment by lmazuel** [comment]
Hi @andreycpp 
We are responsible for the RestAPI wrapper, and the Service Bus team for the AMQP experience. They tell customers to install [Proton](https://qpid.apache.org/proton/) to use AMQP in Python, I unfortunately don't know more :(

Thank you for the documentation issue, I will reach out immediately to the documentation writer.

**Comment by lmazuel** [comment]
Hi @andreycpp 
The SB team decided to remove the link completely, since they have no AMQP samples for now.
I close this issue, not because it's not interesting, but because it's not the right place to track AMQP support for SB (this repo has nothing to do with the SB core team).
Please comment on the documentation you pointed, asking for Python support (this documentation page is owned by the SB core team).
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-overview

Thank you,

**Comment by akshaybabloo** [comment]
I think an example with Django, celery and AMQP would be nice
