### ISSUE TITLE
"Parameter 'subscription_id' must be str." when using SDK Auth File for Client

### ISSUE THREAD

**Issue by jayden-at-arista** [Azure/azure-sdk-for-python#1322]
Recently SDK Auth File support was introduced in PR #1297, but when trying to use it I get the following error: `Parameter 'subscription_id' must be str.` I have seen this before when attempting to authorize a client with a subscription ID from a unicode object read-in from a JSON file, and to fix that error I converted the unicode object to a string.

Now that there is JSON parsing of the new Auth File format in the SDK itself, the unicode object is passed directly into the client instantiation without converting to a string, causing the error. This is only an issue with older versions of Python whose JSON library reads in strings as unicode objects, and should not be an issue with versions newer than Python 3.0.

I am working on a pull request to fix this issue now.

**Comment by lmazuel** [comment]
Hi @jayden-at-arista 
I'm confused about that, and how this was able to pass the CI on Py2.7....
Thanks for the PR! I need to figure out why the CI was ok, even with tests that should have covered that...

Note too that you talk about the client factory, but the problem is actually in the client itself that should have accepted in the first place this unicode string... I created a issue to fix the client code generator here: https://github.com/Azure/autorest/issues/2475

But I agree that it will take an entire release cycle to get this fix at the client level, so a fix in the factory is fair.

Thanks a lot!!!
