### ISSUE TITLE
Azure Keyvault Secrets - Possible wrong init type

### ISSUE THREAD

**Issue by victoraugustolls** [Azure/azure-sdk-for-python#13241]
- **Package Name**: azure-identity, azure-keyvault-secrets
- **Package Version**: 1.4.0, 4.2.0
- **Operating System**: Linux
- **Python Version**: 3.8.5

**Describe the bug**
SecretClient init complains about the credentials type.

**To Reproduce**
```python
credentials = DefaultAzureCredential()
client = SecretClient(
    vault_url="",
    credential=credentials,
)
```

**Expected behavior**
Expected no type complains.

**Screenshots**
![image](https://user-images.githubusercontent.com/7843637/90802192-415d9500-e2ed-11ea-9b67-db2f361100f1.png)

**Comment by chlowell** [comment]
The warning is incorrect. [TokenCredential is a Protocol](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/credentials.py#L16) implemented by every credential class in azure-identity. I suppose that could be too subtle for some typecheckers, because implementing a `Protocol` doesn't mean subclassing it (and `DefaultAzureCredential` does not subclass `TokenCredential`).

Looks like you're using PyCharm? I get correct results in version 2020.2:

![image](https://user-images.githubusercontent.com/10964656/90809231-0439d880-e2d6-11ea-9082-c5cb823e5a8a.png)

`mypy` gives the same result for that code:
```
types.py:5: error: Argument 2 to "SecretClient" has incompatible type "object"; expected "TokenCredential"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by victoraugustolls** [comment]
Hi! I'm actually using Pycharm Professional 2020.2....

**Comment by victoraugustolls** [comment]
What python version are you running?

**Comment by chlowell** [comment]
2.7, 3.5 and 3.8. I don't know what tool PyCharm is using for type checking but I should be using its default.

**Comment by victoraugustolls** [comment]
Still the same error... Don't know if it can be the cause, but I use `poetry` to manage my dependencies.

**Comment by chlowell** [comment]
Were you able to fix this or determine why it happens?

**Comment by victoraugustolls** [comment]
No :/. I will try with Pycharm in a Mac later today and see if I have the same results and update here!
