### ISSUE TITLE
[Schema Registry] Cached schema registry design

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#13292]
- Does the SRClient need cache?
  - built-in
  - or a separate CachedSRClient
  - or no cache, just let the *Serializer have the cache
    - if we don't cache for them, then they need to cache by themselves

see confluent design:

https://github.com/confluentinc/confluent-kafka-python/blob/5aa6439df081ead048932ee395085236ef0bca9d/confluent_kafka/schema_registry/schema_registry_client.py#L185

https://github.com/confluentinc/confluent-kafka-python/blob/master/confluent_kafka/avro/cached_schema_registry_client.py

**Comment by swathipil** [comment]
for now, going with : 

Option 3 - Single client with caching
In this option, there's only one client that can be created by making caching optional - on by default. If user creates the client with caching enabled, APIs can return cached responses when available.

```
public final class ConfigurationClientBuilder {

    // Setup cache policy. If this is not set, default caching policy will be applied.
    public ConfigurationClientBuilder cachePolicy(CachePolicy cachePolicy);

    // build clients
    public ConfigurationClient buildClient();
    public ConfigurationAsyncClient buildAsyncClient();

    // other configurations
}

public final class CachePolicy {
    private CacheMode cacheMode;
    private long maxCacheEntrySize;
    private Duration cacheEntryTimeToLive;

    // getter and setters
}

public enum CacheMode {
    NONE, // this will disable the cache
    LEAST_RECENTLY_USED,
    LEAST_FREQUENTLY_USED;
}
```
One open question with such clients is how to implement the withResponse methods that return the HTTP response information like status code and headers along with the actual response.

Option 3c - Do not offer withResponse APIs for APIs that are eligible for caching
The client will only return T instead of Response<T> for all cache-eligible APIs.
```
public final class ConfigurationClient {
    public ConfigurationSetting getSetting(String key);

    // max overload that may return a cached response
    public ConfigurationSetting getSetting(SettingSelector selector);

    // clear cache
    public void clearCache();
}
```

**Comment by swathipil** [comment]
questions for Anna:
- should CachePolicy be moved to azure-core, even though it's only used by the schema registry client?
- should the properties on CachePolicy have a default? Which defaults?
- should we make cache policy accessible/public to users with an instance var on client? (currently we don't do this, it's private)
