### ISSUE TITLE
Azure identity: Managed identity authentication does not handle rate limits 

### ISSUE THREAD

**Issue by gdippolito** [Azure/azure-sdk-for-python#13387]
- **Package Name**: azure-identity 
- **Package Version**: 1.4.0
- **Operating System**: Ubuntu 18.04
- **Python Version**:  3.6.6

**Describe the bug**
azure-identiy is not able to handle ratelimit when multiple processes try to authenticate at the same time using Managed Identities. 

**To Reproduce**
1. Start multiple process (e.g 48).
2. Initialise the authentication with DefaultAzureCredentials().
3. Interact via the pytohn SDK with the storage account.

**Expected behavior**
I'm able to run multiple processes authenticating with the storage account simultaneously. 

**Additional context**
`DefaultAzureCredentials()` does not perform any authentication when it is instantiated. This operation is done when a client (like azure-blob-storage) perform `get_token()`. This make the handling of the returned exception quite hard since the Pytohn SDK ignore this exception and pass it to the program. The retry_policy does not seem to work since we are not performing that many requests to the storage accounts.

**Comment by chlowell** [comment]
Credentials authenticate only as needed because we don't want to introduce network failure modes to `__init__`, and a credential can't know the scopes of access it should request.

I don't know how your application works, but assuming each subprocess performs similar operations, i.e. each needs the same scope of access, you could in principle trigger authentication before forking. Each subprocess would then begin with a credential that already has the necessary access. You could either instantiate a client and perform an operation with it or if you know the scope you need, request a token from the credential:

```py
# probably the scope you would want for Storage; using a client is more robust
credential.get_token("https://storage.azure.com/.default")
```

**Comment by gdippolito** [comment]
Hi @chlowell thanks for your response. 

The problem of not handling the exception in the identity module is that the exception will be thrown to the `azure-storage-blob`  module which does not really understand what to do with it. 

We could try to force the authentication before forking the process as you suggested, I think this approach would solve the problem if the token does not require to be renewed. In our use case it would be very possible that these processes will run for more than 24 hours. At that point, I think, we will face the same problem because each process will try to authenticate independently at the same time. 

We thought about creating a small proxy server that will cache the response but that seems a bit an overkill for this scope. At the moment we have added random delays before the first data are fetched to avoid hitting the concurrency rate limit imposed by Azure. However, this solution does not seem very elegant.

**Comment by chlowell** [comment]
`ManagedIdentityCredential` does attempt to handle this by retrying on 429. That doesn't help your application because its instances don't share state after the fork. A token valid for one instance is valid for all but after the fork each must request its own. In practice, I expect that means a minority of instances succeed while the rest exhaust their retries. And tokens do expire, so if your 48 instances start with the same one, they nevertheless request a replacement at roughly the same time, bringing you back to where you started.

I think the application needs some way to share state among its subprocesses. A caching proxy, even if not the best solution, seems in the right genre to me.

**Comment by chlowell** [comment]
Were you able to solve this problem?

**Comment by gdippolito** [comment]
> Were you able to solve this problem?

We have added a random delay and this seems to have solved the problem. Not ideal but I guess we can live with it for a job that run for multiple hours.

**Comment by chlowell** [comment]
Okay, I'll close this issue then. Thanks for opening it and please open another if you encounter other problems using the SDK.
