### ISSUE TITLE
Use SharedTokenCacheCredential in Container

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13404]
pacakge: azure-identity==1.4.0
Identity E2E test in containers
Live test every credential of azure-identity in container.

Is it possible to use SharedTokenCacheCredential in container?
Tried mapping volumes but no good, there's decode error. Most likely because container is Linux image and local is Windows system?
Need a good way to use SharedTokenCacheCredential in a container, thank you.

@jongio

**Comment by chlowell** [comment]
The scenario you tried, mounting a Windows host's cache into a container, won't work (even in a Windows container) because only the local user on the host can decrypt the cache. It is however possible when the cache is plaintext or was created in the container. But we wouldn't suggest people try to use this credential in container scenarios--really it isn't appropriate for them--so it's not important to test.
