### ISSUE TITLE
Use UsernamePasswordCredential in Container

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-python#13469]
pacakge: azure-identity==1.4.0
Identity E2E test in containers
Live test credentials of azure-identity in container.

Is it possible to avoid "multi-factor authentication" errors when using `UsernamePasswordCredential` in a container, and how?
Or is it not expected to work in a container?
Thank you.

@jongio

**Comment by chlowell** [comment]
The issue is the AAD tenant's configuration, not the container environment. [As the documentation states](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.4.0/azure.identity.html#azure.identity.UsernamePasswordCredential), this credential won't work with tenants requiring MFA. You can stand up your own tenant, add a user, and test the credential against it, which is what we've done for the test suite.
