### ISSUE TITLE
pip install --upgrade azureml-sdk[automl] fails on python 3.8 at requirement onnxruntime==1.0.0

### ISSUE THREAD

**Issue by chrisfcarroll** [Azure/azure-sdk-for-python#13577]
- **Package Name**:  azureml-sdk[automl]
- **Package Version**: 1.13.0
- **Operating System**: macos Catalina 10.15.6
- **Python Version**: 3.8.5

**Describe the bug**
I run `pip install --upgrade azureml-sdk[automl]` as per [the docs](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py).

Installation fails.

**To Reproduce**
1. `pip install --upgrade azureml-sdk[automl]`

**Screenshots**
```
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.0.0 (from azureml-train-automl-runtime~=1.13.0->azureml-train-automl~=1.13.0; extra == "automl"->azureml-sdk[automl]) (from versions: 1.2.0, 1.3.0, 1.4.0)
ERROR: No matching distribution found for onnxruntime==1.0.0 (from azureml-train-automl-runtime~=1.13.0->azureml-train-automl~=1.13.0; extra == "automl"->azureml-sdk[automl])
```

**Additional context**

- `azureml-sdk[explain]` succeeds
- `pip install onnxruntime==1.0.0` fails with the same `ERROR: Could not find a version that satisfies the requirement onnxruntime==1.0.0 (from versions: 1.2.0, 1.3.0, 1.4.0)`
- `pip install onnxruntime` succeeds and installs 1.4.0 
- `python -c 'import struct;print( 8 * struct.calcsize("P"))'` --> **64**

**Comment by 3Mcolab** [comment]
I am also having the same issues and still not able to connect to workspace from my location connection. Any new update?

**Comment by chrisfcarroll** [comment]
@3Mcolab - I'm not sure this issue will resolve 'not able to connect to workspace from my location'. Just doing `python -m pip install azureml-sdk` _does_ work on my system, it's only the `[automl]` extension that doesn't work

**Comment by githubkingchamp** [comment]
did anybody can able to solve the issue?

**Comment by githubkingchamp** [comment]
did anybody found the solve for this issue?

**Comment by jeff-shepherd** [comment]
@chrisfcarroll @githubkingchamp Unfortunately the full automl package does not currently support Python version 3.8.5 because of dependent packages.

However, you can use a client version of automl, which is in the `azureml-train-automl-client` package.  This package is installed by default when you install the `azureml-sdk` package.
It allows you to submit automl remote runs and do remote inferencing.  It does not support local training or inferencing.  
There is an experimental sample notebook that demonstrates remote inference at: [https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning/experimental/regression-model-proxy](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/automated-machine-learning/experimental/regression-model-proxy)
This notebook also requires pandas<1.0.0, numpy<1.19.0, azureml-widgets, matplotlib and sklearn.

**Comment by chrisfcarroll** [comment]
Yes, thanks, my main usecase was to submit azure runs. Otherwise I can probably live with dropping to Python 3.7.

**Comment by chrisfcarroll** [comment]
Closing because there's a workaround - drop to python 3.7 - and the issue is with dependent packages
