### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by andreacassioli** [Azure/azure-sdk-for-python#13676]
FYI the links about  `AutoLockRenewer` in the Service Bus README file seem to point to nowhere.

**Comment by KieranBrantnerMagee** [comment]
Hey Andrea, thanks for the pointer.  (Saw the other README issue you created as well, very appreciated.)  Have confirmed this and will be mitigating as part of the following issue :) https://github.com/Azure/azure-sdk-for-python/issues/13746

(Closing this now to dedup only because that issue has a link to the authoritative warning list, but don't take this as any negatives, very very thankful to have your eyes on this/calling this out :) )
