### ISSUE TITLE
azure-mgmt-security does't support the latest version of the API

### ISSUE THREAD

**Issue by jsenich-r7** [Azure/azure-sdk-for-python#13769]
- **azure-mgmt-security**: 
- **0.4.1**: 
- **any**:
- **any**: 

**Describe the bug**
The currently available version of the `azure-mgmt-security` sdk does not support the latest stable version of the API from the spec https://github.com/Azure/azure-rest-api-specs/tree/master/specification/security/resource-manager/Microsoft.Security/stable/2020-01-01. 

**To Reproduce**
1. `pip install azure-mgmt-security`
2. Look at the `self.api_version` in `security/operations/_alerts_operations.py`

**Expected behavior**
I would like the latest version of the sdk to support the latest version or the API.

**Comment by qiaozha** [comment]
@chlahav Which api are you referring to? Because I have checked several swagger inside https://github.com/Azure/azure-rest-api-specs/tree/master/specification/security/resource-manager/Microsoft.Security/stable/2020-01-01 folder. and the sdk code version indicates it's 2020-01-01. For example discoveredSecuritySolutions.json maps to https://github.com/Azure/azure-sdk-for-python/blob/7c5ca2eec6d6ee301d97f6375175a0443ccd0bb2/sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_discovered_security_solutions_operations.py#L38

**Comment by jsenich-r7** [comment]
@qiaozha It looks like it's only the `2020-01-01` version of alerts.json spec that hasn't made it into the sdk code yet.

**Comment by qiaozha** [comment]
@jsenich-r7 The sdk is released before the alert.json updated. @chlahav Could you please file an release request via aka.ms/openapihub for this issue? We need a new sdk to be released per @jsenich-r7's question.

**Comment by jsenich-r7** [comment]
@chlahav @qiaozha Any ETA on a new sdk release to address this?

**Comment by AddySanto** [comment]
@chlahav no longer handles these issues, we'll reroute to the appropriate owner soon.  Be aware that the next ~10 days are a local holiday here so expect delayed response.

**Comment by jsenich-r7** [comment]
@AddySanto Any updates on this?

**Comment by AddySanto** [comment]
We did an initial triage and found a team member to own the ticket.  I'm tracking our progress all-up but not at the per-ticket granularity so I can't comment yet on an ETA for this specific issue.
