### ISSUE TITLE
Missing option to restrict scope to specific storage account

### ISSUE THREAD

**Issue by FelixS90** [Azure/azure-sdk-for-python#13838]
**Is your feature request related to a problem? Please describe.**
When [requesting an access token](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token) using OAuth 2.0 auth code grant to access Azure Storage, I want to be able to restrict the scope to `https://{}.blob.core.windows.net/user_impersonation".format(STORAGE_NAME)`, i.e. keeping the [Azure Storage resource ID](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet#azure-storage-resource-id) to a specific storage account only.

However, when debugging the initialization of `azure.storage.blob.ContainerClient` like
```python
token = AuthorizationCodeCredential(tenant_id=TENANT_ID,
                                        client_id=CLIENT_ID,
                                        authorization_code=code,
                                        redirect_uri=redirect_uri)
container_client = ContainerClient(account_url="https://{}.blob.core.windows.net".format(STORAGE_NAME),
                                       container_name="test",
                                       credential=token)
```
where I obtained `code` like shown in #13834 (in short: specifying `scope=["https://{}.blob.core.windows.net/user_impersonation".format(STORAGE_NAME)]` when [requesting the authorization code](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code)), the scope as transmitted in the final request to retreive an access token is set to `https://storage.azure.com/.default` (when initializing `BearerTokenCredentialPolicy(credential, STORAGE_OAUTH_SCOPE)`).

Is this behaviour intended? If so, why?

**Describe the solution you'd like**
I would like to have a way to provide a more fine-granular access over the scope for which to request the token for, i.e. more like `BearerTokenCredentialPolicy(credential, kwargs.get('scopes', STORAGE_OAUTH_SCOPE))`.

**Describe alternatives you've considered**
Keeping as-is.

**Comment by amishra-dev** [comment]
the question is for the identity folks even though it uses the storage example

**Comment by chlowell** [comment]
This looks like a storage question to me. If something like "https://my-storage-account.blob.core.windows.net" is a valid Azure AD scope, then any credential in azure-identity can get a token for it. This particular scenario then requires `ContainerClient` to expose configuration or replacement of its `BearerTokenCredentialPolicy`. 

But taking a step back, I expect the best answer to the broader question doesn't involve azure-identity at all because storage already offers granular access control through RBAC and SAS tokens. @amishra-dev what do you think? I'm not greatly familiar with storage's access control mechanisms.

**Comment by xiafu-msft** [comment]
It looks like customer has got the answer. Close this issue for now.
