### ISSUE TITLE
servicebus `fetch_next` coarse timeout granularity

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#13872]
Not sure this is a bug or by design, just do not feel correct to me.

- **Package Name**:  `servicebus`
- **Package Version**: 0.50.3
- **Operating System**: OSX
- **Python Version**: 3.7

**Describe the bug**
Function `fetch_next` has a parameter `timeout` that is express in seconds. This is clearly a pretty coarse value for a message fetching, considering that the code internally switches to milliseconds. 

If set to `None` there is no timeout, as for docs. But if I set to `0` it defaults to `None` again! I would have expected `0` to mean check and exit, i.e. minimum timeout! Is it by design? If so, could you please make it more explicit in the docs?

**Comment by KieranBrantnerMagee** [comment]
Excellent callout as always.  For us this was by design in 0.50 (although as you say not well documented), but this is an item that we are looking to align cross-language-language for semantic-consistency in 7.0, for which a discussion is actually currently underway.

I have a personal opinion on this but I'll keep it close to the vest to not influence you yet; as I'm going to abuse this issue to check what your intuition would be for this behavior. (E.g., would you expect it do as you suggest and only poll once, immediately exiting if no messages are available?)

(And to be clear, whichever direction this is settled on will be rigorously documented.  Keep throwing anything unclear our way, I love all the rough edges we're sanding down thanks to your eyes.)

**Comment by andrea-cassioli-maersk** [comment]
I see. Just think that one second is a lot of time in some scenario, and I might just want to fetch was is there. But good that you have it on the radar.
