### ISSUE TITLE
Servicebus messages cannot be completed or abandoned outside the receiver context?

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#13873]
- **Package Name**: `servicebus`
- **Package Version**: 0.50.3
- **Operating System**: OSX
- **Python Version**: 3.7

**Describe the bug**
- **Package Name**: `servicebus`
- **Package Version**: 0.50.3
- **Operating System**: OSX
- **Python Version**: 3.7

**Describe the bug**
Not sure if it is by design I cannot find anything helpful in the docs. Here it is:

* I have a function that receives messages using a queue receiver as a context like

```
with queue.get_receiver(mode=ReceiveSettleMode.PeekLock) as receiver:
    msg_batch = receiver.fetch_next(max_batch_size=1, timeout=queue_read_timeout)
```

* then `msg_batch` is retuned by the function and processing happen.
* at the end I want to complete or abandon messages.

Problem is that I keep getting an exception `MessageSettleFailed` calling both `message.abandon` and `message.complete`

```
NULL message_receiver' (b'/Users/runner/runners/2.171.1/work/1/s/src/vendor/azure-uamqp-c/src/message_receiver.c':b'messagereceiver_send_message_disposition':494)
```

Looks like the receive is not set. Does this mean that I need to keep the processing in the receiver context? Or have a global receiver? With the old control client I could simply rely on the service bus client...

**Comment by KieranBrantnerMagee** [comment]
Hello again @andrea-cassioli-maersk  :)
So your assessment is pretty on-the-mark.  In 0.50 you won't be able to settle a message outside of the receiver context.  While I don't have _deep_ familiarity with the prior historical version I would postulate it worked there because it was almost purely REST based, which may have let operations happen with fewer constraints than in 0.50 and beyond when we utilized the AMQP channel.

To give some good news however; allowing settlement-after-client-close is a topic we've discussed and intend to release with the 7.0 GA.   I need to check where we are in that, since some components have already been emplaced, and will loop back here.

**Comment by andrea-cassioli-maersk** [comment]
OK, thanks. The overall logic makes sense (I get it that the message needs to retain some kind of connection object reference). 

I was surprise of such a change moving from 0.20 to 0.50, as they are minors. Moreover, I could not find any specific mention in the doc and the example are so basic!

On top of that, the error I got was pretty obscure and I could have a guess only because it printed out something like `Receiver NULL returned` in an error message from AMQP C code.

Anyway, that's it I guess. I will close the issue.

**Comment by KieranBrantnerMagee** [comment]
Doc gap is totally understood; an unfortunate bit of debt from the history of how these libraries grew more informally in the beginning.  I've added [an issue](https://github.com/Azure/azure-sdk-for-python/issues/13956) to create subsections in our GA version migration guide to specify coming from .2 vs .5 to hopefully mitigate this sort of confusion for the future.

**Comment by KieranBrantnerMagee** [comment]
Hey @andrea-cassioli-maersk ; Wanted to leave a followup here regarding settlement-out-of-context:

The b7/b8 transition contained substantial architect feedback, with their goal being to move settlement methods from the message entities onto the receiver, in order to allow those messages to be treated as pure data-objects and make the "operations requiring a receiver connection" clearly linked to the receiver, and, as such, tied to the receiver's lifecycle.

To be precise, this has the result that one will have to settle within the receiver lifespan.  Don't hesitate to shout (and you have my email if need be, since my github notifications are a brick wall) if this seems utterly insane to you; just wanted to make sure I left the direction this had settled and the reasoning here for posterity.  (the migration guide is, per our discussions, of course still being updated accordingly)
