### ISSUE TITLE
Importing SkuFamily from azure.mgmt.keyvault isn't supported in 2.2 (dependency isn't pinned down)

### ISSUE THREAD

**Issue by simonlindblad** [Azure/azure-sdk-for-python#14011]
- **Package Name**:  azure-sdk-tools
- **Package Version**:  master
- **Operating System**: Linux/Windows
- **Python Version**:  3.6

**Describe the bug**
[This setup.py](https://github.com/Azure/azure-sdk-for-python/blob/master/tools/azure-sdk-tools/setup.py) doesn't specify a specific azure-mgmt-keyvault, but importing SkuFamily as is done [here](https://github.com/Azure/azure-sdk-for-python/blob/master/tools/azure-sdk-tools/devtools_testutils/keyvault_preparer.py) doesn't work with azure-mgmt-keyvault 2.2.

**To Reproduce**
1. Install azure-mgmt-keyvault 2.2 prior to running setup.py
2. Run setup.py
3. Try anything from devtools_testutils/keyvault_preparer.py

**Expected behavior**
Imports working.

**Comment by lmazuel** [comment]
Hi @simonlindblad 
This package is not designed to be used outside of the repo, we apply changes to match the status of master, to be to be backward compatible with previous packages. You can see in the setup.py you mention for instance:

> # This is a "fake" package, meaning it's not supposed to be released but used
> # locally with "pip install -e"

We _coud_ add a `>=7.0.0`, but again that won't be any help here since this package is designed as helper tool while everything is installed from local branches.
