### ISSUE TITLE
Unable to authenticate to Azure GraphRBAC using DefaultAzureCredential OR CredentialWrapper

### ISSUE THREAD

**Issue by bensussman** [Azure/azure-sdk-for-python#14022]
- **Package Name**: azure-graphrbac
- **Package Version**: 0.61.1
- **Operating System**: Mac OS 10.14.6
- **Python Version**: Python 3.7.6

**Describe the bug**
We are unable to use the `DefaultAzureCredential` OR the [CredentialWrapper class (cred_wrapper.py)](https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d) to authenticate the `graphrbac` client to create an App, Service Principal, and secret key.

NOTE: I am able to get the API to work if i use `UserPassCredentials` instead.

**To Reproduce**
1. Log into azure using the `azure cli` locally.
2. Run `python`, import `azure-graphrbac`, and then use `DefaultAzureCredential` or the [CredentialWrapper class (cred_wrapper.py)](https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d) to create a `credential` object with the currently-logged-in-user credentials.
3. These credentials are valid to do other azure operations (for example creating a Blob storage container), but when used with `graphrbac` to create an App, it prints the following error:
```
azure.graphrbac.models.graph_error_py3.GraphErrorException: Access Token missing or malformed.
```

**Expected behavior**
I expect the `DefaultAzureCredential` or the [CredentialWrapper class (cred_wrapper.py)](https://gist.github.com/lmazuel/cc683d82ea1d7b40208de7c9fc8de59d) to return credentials that are valid for `graphrbac`. 

**Additional context**
In addition, this entire Python API is (admittedly newly) *legacy* and is being deprecated in favor of the Microsoft Graph API here https://docs.microsoft.com/en-us/graph/api/application-post-applications . However there does not seem to be a Python API client that allows us to use this new API yet...

**Comment by jeking3** [comment]
I am also unable to use a ClientSecretCredential, and I think it is because you cannot set the resource parameter to https://graph.windows.net/ (I am using the AzureIdentityCredentialAdapter that was posted by a Microsoft employee to adapt azure-identity for use by older azure sdk constructs, like graphrbac.  It works with all the other services I use but not with azure.graphrbac.

**Comment by jeking3** [comment]
@bensussman have you tried https://github.com/microsoftgraph/msgraph-sdk-python-core ?

**Comment by srusun** [comment]
@jeking3 We were actually able to figure out a way to use the GraphRBAC Client and the DefaultAzureCredential - However, when trying to use the new Microsoft Graph API, I was running into a 503 error - "503 Server Error: Service Unavailable for url: https://graph.microsoft.com/v1.0/applications". The response body was as follows,
{
  "error": {
    "code": "Service_ServiceUnavailable",
    "message": "Service is temporarily unavailable. Please wait and retry again.",
    "innerError": {
      "date": "2020-10-06T19:47:59",
      "request-id": "1da6f400-449f-4c70-a203-c9106823c502",
      "client-request-id": "1da6f400-449f-4c70-a203-c9106823c502"
    }
  }
}

**Comment by bensussman** [comment]
The issue is one of inconsistent permissions. The goal is:

1. Create a permissions object authenticated to the current logged in azure account (normally the azure cli)
2. Use that permissions object to create an `App` + `Service Principal` in that app
3. Use that permissions object to create a `Client Secret` for use authenticating our system as the newly created App/SP.
4. Use that permissions object to create a `Custom Role` to bind / attach to the SP created in 3
5. Use that permissions object to create a `Resource Group`, `Storage Account` (and storage container inside it), VNet, etc.


Here is a code sample:

```python
# credentials work for most resources (the ones listed in 6) above.
# NOTE The AzureIdentityCredentialAdapter() function is defined here: https://github.com/jongio/azidext
credentials = AzureIdentityCredentialAdapter()
credentials.set_token()
# graph_credentials work ONLY for creating the "Client Secret" from 4 above. 
graph_credentials = AzureIdentityCredentialAdapter(
    resource_id="https://graph.microsoft.com/"
)
graph_credentials.set_token()

# This is the best way (and it's not very good!) we could find to build a client that can create an App/SP
# NOTE it does NOT USE the standard credentials, nor the "graph" credentials.
# This seems like a bug or design flaw!
from azure.common.client_factory import get_client_from_cli_profile
from azure.graphrbac import GraphRbacManagementClient
graphrbac_client = get_client_from_cli_profile(GraphRbacManagementClient)
app = graphrbac_client.applications.create(
    {"available_to_other_tenants": False, "display_name": service_principal_name}
)
sp = graphrbac_client.service_principals.create({"app_id": app.app_id, "account_enabled": True})

# To create the client secret, we use the graph_credentials created at the top, and importantly:
# we go STRAIGHT TO HTTP!! 
# We were UNABLE to find an azure-sdk-for-python solution that supported this endpoint.
# This seems like a bug or a design flaw!
header = {
    "Content-Type": "application/json",
    "Authorization": "Bearer {}".format(graph_credentials.token["access_token"]),
}
url = "https://graph.microsoft.com/v1.0/servicePrincipals/{}/addPassword".format(sp.object_id)
payload = {
    "passwordCredential": {"displayName": "newlyCreatedClientSecret"},
}
response = requests.post(url, data=json.dumps(payload), headers=header)
response.raise_for_status()
secret_info = json.loads(response.text)

# To create a custom role, we use the standard credentials created at the top, and importantly:
# we go STRAIGHT TO HTTP!! 
# We were UNABLE to find an azure-sdk-for-python solution that supported this endpoint.
# This seems like a bug or a design flaw!
from azure.mgmt.authorization import AuthorizationManagementClient
authorization_client = AuthorizationManagementClient(credentials, subscription_id)
role_definition_id = str(uuid.uuid4())
header = {
    "Content-Type": "application/json",
    "Authorization": "Bearer {}".format(credentials.token["access_token"]),
}
role_name = "RoleName"
scope = "subscriptions/{}".format(subscription_id)
url = (
    "https://management.azure.com/{}/providers/Microsoft.Authorization/"
    "roleDefinitions/{}?api-version=2015-07-01".format(scope, role_definition_id)
)
payload = {
    "name": role_definition_id,
    "properties": {
        "roleName": role_name,
        "description": "lorem ipsum",
        "type": "CustomRole",
        "permissions": [{"actions": required_permissions}],
        "assignableScopes": [scope],
    },
}
response = requests.put(url, data=json.dumps(payload), headers=header)
response.raise_for_status()
roles = list(
    authorization_client.role_definitions.list(
        group_id, filter="roleName eq '{}'".format(role_name)
    )
)
assert len(roles) == 1, (
    "Found unexpected number of roles ({}) with name {}. "
    "Expected exactly 1".format(len(roles), role_name)
)
created_role = roles[0]

# Assign Custom Role to Service Principal. We *are* able to do this from the azure-sdk-for-python thankfully
authorization_client.role_assignments.create(
    group_id,
    uuid.uuid4(),
    {
        "role_definition_id": spell_role.id,
        "principal_id": object_id,
        "principal_type": "ServicePrincipal",
    },
)

# Create a resource group uses the normal credentials. We *are* able to do this from the azure-sdk-for-python thankfully
resource_client = ResourceManagementClient(credentials, subscription_id)
resource_group = resource_client.resource_groups.create_or_update(
    resource_group_name, {"location": region}
)
```


As you can see from the detailed example above, the azure-sdk-for python is missing valuable APIs, and is missing a clear credential provider that can be used consistently.

**Comment by bensussman** [comment]
Any update on this @lmazuel or @jeking3

**Comment by lmazuel** [comment]
@bensussman sorry for the late answer. We didn't upgraded azure-graphrbac to the new `azure-identity` system yet. I struggle to know if we should do it, considering as you said the API is deprecated, and we're working with MS graph people on their SDK as well. I do understand the gap is painful, should I take your feedback that regenerating with azure-identity would be valuable? In the meantime, any `msrestazure` auth would work: https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_active_directory.py

The tricky part to authenticate usually is to remember you need to change the resource_id: `'https://graph.windows.net/'`

```
from azure.graphrbac import GraphRbacManagementClient
from msrestazure.azure_active_directory import ServicePrincipalCredentials

credential = ServicePrincipalCredentials(
    client_id=client_id,
    secert=secret,
    tenant=tenant_id,
    resource="https://graph.windows.net/" # Don't forget this!
)

client = GraphRbacManagementClient(credential, tenant_id)
```

`get_client_from_cli_profile` is doing that auto-magically for you, which explains why it works your way.

Does that help? Thoughts?

**Comment by lmazuel** [comment]
Also, reading your snippet:
- Please create an issue for support of `addPassword`
- [Role definition PUT is available](https://docs.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2015_07_01.operations.roledefinitionsoperations?view=azure-python#create-or-update-scope--role-definition-id--role-definition----kwargs-)

**Comment by srusun** [comment]
Thanks @lmazeul for the response! Within the time we posted and the time of the response, there were many things we managed to figure out on our own (the resource_id, role definition PUT, etc..). However we believe there are still some key features missing from the Azure Python API that would have been very beneficial to our development process - specifically the following,

1. A python client that can generate a client secret [](https://docs.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http) - Instead of going directly to a HTTP request)

2. A python client for adding api permissions [](https://docs.microsoft.com/en-us/graph/api/resources/requiredresourceaccess?view=graph-rest-1.0) - Instead of going directly to a HTTP request)

3. A python client to create an sp/app using the modern API [](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http) - We were only able to create it using GraphRbacManagementClient which uses the legacy API

4. Getting the tenant id of a logged in user
(We currently shell out to `az account show` in python and parse the response)

**Comment by lmazuel** [comment]
1. I assume you're talking about the `addPassword`. Indeed it's missing feel free to open an issue (I like atomic issue, I don't want to bias this current issue topic with that :))
2. Are you talking about [role assignment](https://docs.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2015_07_01.operations.roleassignmentsoperations?view=azure-python#create-scope--role-assignment-name--parameters----kwargs-)?
3. Could you clarify in by "modern API", you mean azure-identity, or if you mean Microsoft Graph?. Both are not available yet, just to be sure we address the right thing
4. There is no concept of current logged in user in SDK, since this is a CLI concept. Sub-processing is the recommended for now ([even azure-identity is subprocessing to get the CLI token](https://github.com/Azure/azure-sdk-for-python/blob/0b51e64c97d8c4dbdbcf0d0ee3004f23f518433c/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L106))

**Comment by lmazuel** [comment]
Thanks for the clarification @srusun !

Microsoft Graph SDK is under development, I don't have timeline yet (it's actually not our team, since it's not Azure specific). The best repo is indeed so far https://github.com/microsoftgraph/msgraph-sdk-python-core

For #15971 , I realized I misguided you, I was thinking you need that in azure-graphrbac, but you need that from the Microsoft Graph and we dont' have it here. You might want to create your issue https://github.com/microsoftgraph/msgraph-sdk-python-core instead.

I'm keeping this issue opened as a placeholder of the question: should we re-release a version of azure-graphrbac that supports azure-identity, knowing that the endpoint is about to be deprecated finally and Microsoft Graph SDK is coming.

https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-or-azure-ad-graph/

**Comment by lmazuel** [comment]
Azure AD Graph API is now deprecated. We do not support SDK fixes to this product anymore. Please refer to this issue for additional way to get support to move to Microsoft Graph API:
https://github.com/azure-deprecation/dashboard/issues/60
