### ISSUE TITLE
[Storage.Datalake] Remove DataLakeAclChangeFailedError

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#14177]
We will add (or document) support for `continuation_token` to AzureError in azure.core: #14176 
Once this added we should remove this object and support raising the original error along with the continuation token.

This will need to happen before the GA release.

This also applies to the storage pageable operations - where the continuation token can be added to exceptions raised while iterating.

**Comment by xiafu-msft** [comment]
Hi Anna!

Just want to clarify a bit about the `error` field of `DataLakeAclChangeFailedError` class: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_models.py#L826
The error is a type of AzureError instead of the exact AzureError instance. For example, we caught `ServiceRequestError` which is a subclass of AzureError, we want to set that `ServiceRequestError` instance as the `error` field to let user know the precise error raised.

If we add continuation_token to AzureError, all it's subclasses will have a continuation token, which will only be used for recursive acl operation. I guess the coninuation_token is too precise to add to the super parent class?

**Comment by annatisch** [comment]
We would prefer not to have an "error within an error" for Python - in Python we use `try/except` syntax to have different handling for different error types - but you cannot use this syntax if the different error types are an attribute of only one error.
For example, we would prefer this:
```python
try:
    client.operation()
except ServiceRequestError as e:
    do_something(e.continuation_token)
except HttpResponseError as e:
    do_something_else(e.continuation_token)
```
Instead of:
```python
try:
    client.operation()
except FailedError as e:
    if isinstance(e.error, ServiceRequestError):
        do_something(e.continuation_token)
    elif isinstance(e.error, HttpResponseError):
        do_something_else(e.continuation_token)
```

**Comment by xiafu-msft** [comment]
Yeah you are absolutely right that we'd want to let user use the simplest syntax when dealing with error. 
Just the reason we decided to create DataLake specific error for all three platforms was we don't want  to use a generic error for a specific purpose. Here is the [original discussion](https://github.com/Azure/azure-sdk-for-net/pull/15317#discussion_r492978599).
Since that wasn't a random decision, all SDKs hesitate to break users experience. (Even it's a preview feature)

**Comment by tasherif-msft** [comment]
Will proceed to close this issue since it seems it has been resolved. If this needs to be discussed further please feel free to reopen :)
