### ISSUE TITLE
[EventHub] Custom exceptions should inherit from azure.core AzureError.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-python#14370]
**Is your feature request related to a problem? Please describe.**
Currently, our Exceptions simply derive from Exception.

**Describe the solution you'd like**
This should be improved to the standard/best practice of inheriting from AzureError at the base.

(not much for further detail as it's a "let's conform to guidelines" issue and somewhat truth-in-advertising per the title.)

**Comment by bradleydamato** [comment]
Hey @KieranBrantnerMagee , 

I used git grep "(Exception)" to search for custom exceptions in `azure-sdk-for-python/sdk/eventhub` that should be inheriting from AzureError. 

I modified the class definitions for those exceptions to inherit from AzureError 

Following my changes, git grep yielded no results. 

I ran tox tests (see below)
![image](https://user-images.githubusercontent.com/53579156/95754622-50b7e980-0c71-11eb-8f5e-080b08f91408.png)

I have a PR here (let me know if I missed anything or misunderstood!): https://github.com/Azure/azure-sdk-for-python/pull/14432

**Comment by KieranBrantnerMagee** [comment]
👍 Thanks heartily!  Looks like a cogent set of fixes, I'm getting a quick double-check from some of my peers on one of the aspects of it, but your approach was sound and any changes would be us piggybacking on you to make additional improvement :)

**Comment by bradleydamato** [comment]
Thanks @KieranBrantnerMagee !

**Comment by yunhaoling** [comment]
Echoing the [comment in the PR](https://github.com/Azure/azure-sdk-for-python/pull/14432#issuecomment-790954953):

We decided not to make the change due to the following reasons:
- This would be a breaking change to customers who build their error handling on both EventHubError and AzureError, e.g. code like below would be broken by the change:
```python
try:
   # pass
except AzureError:
   # do something
except EventHubError:
   # do else
```
- The change not only impacts the `EventHubConsumerClient` where errors are being passed into callback, but also `EventHubProducerClient` where errors are catchable.
- Based on the reachability of the azure-eventhub SDK ([non-trivial downloading amount](https://pepy.tech/project/azure-eventhub)), this would potentially impact a large amount of users.

To conclude with, the disadvantages outweigh the advantages so we decide not to make the change.

thanks @bradleydamato, you're an awesome open source contributor, looking forward to collaboration with you again!
