### ISSUE TITLE
Create Identity e2e tests for running in Azure Service Fabric

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-python#14372]
Tracking item to create new /sdk/e2e Azure.Identity smoke tests for running in Azure Service Fabric hosted environment.

1. Add new /sdk/e2e tests for Azure Service Fabric
2. Update Parent issue https://github.com/Azure/azure-sdk/issues/901 with instructions for Test team

**Comment by mccoyp** [comment]
A [personal repository](https://github.com/mccoyp/service-fabric-managed-identity-test) is currently tracking this, but will need some changes before being moved into /sdk/e2e. The tests currently use REST instead of the ManagedIdentityCredential (and underlying ServiceFabricCredential) to fetch tokens, and it may be desirable to use existing test images instead of constructing Docker images for the tests.

**Comment by mccoyp** [comment]
As I [mentioned](https://github.com/Azure/azure-sdk/issues/901#issuecomment-708605514) in the parent issue Azure/azure-sdk#901, the sample in my repository has been updated to use the correct credential when accessing Key Vault secrets. Using the team's Docker image for live managed identity testing would be ideal and is something that should be investigated further. As it is, though, the sample serves as a full end-to-end test for this scenario.
