### ISSUE TITLE
breaking change for azure-mgmt-avs?

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-python#14735]
I'm trying to fix correctness errors in the 2020-03-20 API for AVS. The python sdk is the only sdk reporting a breaking change:
https://github.com/Azure/azure-rest-api-specs/pull/11317#issuecomment-715471704

Can you help me understand what this breaking change means:
- Operation ClustersOperations.create_or_update has a new signature

 If you look at https://pypi.org/project/azure-mgmt-avs/#history, you will see two versions:
- 1.0.0rc1 on July 14 for the 2020-03-20 API
- 0.1.0 on June 19 for the 2019-08-09 API

Is there a way to check git to find out what microsoft.azure/autorest.python was used? I did not see any breaking change when using @3.0.62. The breaking change check used @~4.0.71.

Where is the source code for azure-mgmt-avs now? You can see that it was here:
git log --all -- sdk/compute/azure-mgmt-avs

**Comment by changlong-liu** [comment]
Hi @ctaggart , for breaking change about create_or_update:
It related to the "Cluster" model definition changes in your PR.  Originally there are only two properties in it is not readonly, (sku and clusterSize); currently there more properties become to non-readonly.   This make the cluster parameter in create_or_update can be flattened in Python.

For latest azure-mgmt-avs source code, it's in the release/v3 branch: https://github.com/Azure/azure-sdk-for-python/tree/release/v3/sdk/compute/azure-mgmt-avs

For autorest using in codegen: https://github.com/Azure/azure-sdk-for-python/blob/release/v3/swagger_to_sdk_config.json#L6

**Comment by ctaggart** [comment]
Thanks @changlong-liu, that helped. If I run this command, using the current specification from master, I see breaking changes in `create_or_update`. Do you know why?

```
autorest --input-file=../azure-rest-api-specs/specification/vmware/resource-manager/Microsoft.AVS/stable/2020-03-20/vmware.json --python --output-folder=sdk/compute/azure-mgmt-avs --namespace=azure.mgmt.avs --azure-arm=true --override-client-name=AVSClient --use=@microsoft.azure/autorest.python@~4.0.71
```

**Comment by changlong-liu** [comment]
Hi @ctaggart ,

The detail breaking change can be found here: https://github.com/AzureSDKAutomation/azure-sdk-for-python/pull/2527/files#diff-4db79dc989d60426c9b0788a2502c7c7c85acd73e15617a48794ca0691337080L237


The root cause should be your PR have changed the definition of "Cluster" model or any of it's children model.
Before your PR, there are only two properties in it is not readonly, (sku and clusterSize), they are flattened into the create_or_update() function; 
With your PR, there are more properties become to non-readonly.  (provisioningState). so the autorest.python combines them together as a Cluster parameter in the create_or_update() def signature.

**Comment by ctaggart** [comment]
Thank you for the explanation.
