### ISSUE TITLE
StackOverflow cleanup Track 1 references, answer unanswered questions for Event Hubs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15108]

**Comment by yunhaoling** [comment]
| Issue | Link | Status | Action | SDK Version | Python Version | Platform |
| ---- |---- | ---- | ---- | ---- | ---- | ---- |
| receiving can work but OWNERSHIP_LOST due to get any value from the events,  | [link](https://stackoverflow.com/questions/61385284/azure-eventhub-python-ownership-lost) | needs author feedback | try extracting value wrongly to reproduce and give suggestion to user. Potentially would be a bug fix/improvement in error handling | v5 | ND | ND |
