### ISSUE TITLE
Updated outdated content from bug bash in samples for Event Hubs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-python#15114]
Update from @ramya-rao-a :

Update the outdated content found in #15111

**Comment by swathipil** [comment]
Copying over bugs from issue #15111 for clarity:
**Comment/Docs/Etc. Bugs**
* [authenticate_with_sas_token.py, Line 9](https://github.com/Azure/azure-sdk-for-python/blob/da34e9d3bc41ec56c46a1a8c281b4a69d735bdc6/sdk/eventhub/azure-eventhub/samples/sync_samples/authenticate_with_sas_token.py#L9): replace ServiceBus with EventHub
* [EventHub docs](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/eventhub/azure-eventhub#publish-events-to-an-event-hub-asynchronously): fix "EventHubProcuer" typo
* [client_identity_authentication.py](https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/eventhub/azure-eventhub/samples/sync_samples/client_identity_authentication.py#L46): 

> * comments are not accurate/up-to-date? --> all of the configurations are not attempted
> * [no params are actually passed in to the EnvironmentCredential](https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/sdk/eventhub/azure-eventhub/samples/sync_samples/client_identity_authentication.py#L46)

* [recv_with_checkpoint_by_batch.py](https://github.com/Azure/azure-sdk-for-python/blob/b62d6a07037fa153b993be61959a1cb634178daa/sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_by_batch.py#L54): misnomer, since batch=False by default in .receive(), and True is not passed in. receive_batch() is also not used.

**Comment by swathipil** [comment]
Copying @yunhaoling 's comment on #15111 : 
- Event Hubs Python samples under docs.microsoft.com/samples

| Samples | Link | Status | Notes | Action |
|--------|---------|------|--------|--------|
| Azure Event Hubs client library for Python Samples | [link](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-samples/) | | | |
| Collecting Scheduled Events with Event Hub | [link](https://docs.microsoft.com/en-us/samples/azure-samples/virtual-machines-python-scheduled-events-central-logging/virtual-machines-python-scheduled-events-central-logging/) | | | |
| Azure Event Hubs client library samples with persistent checkpointing for Python | [link](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-checkpointstore-samples/) | | | |
| Azure Event Hubs client library samples with persistent checkpointing for Python | [link](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-python/eventhub-checkpointstore-aio-samples/) | | this is an async sample, but same title as the sync one, can we improve that? | |

- Event Hubs Python samples repos under Azure-samples org:
  - no sample code repo for python + eventhub (?)
  - keywords checked: eventhub(EventHub), event hub(Event Hub), event hubs(Event Hubs), event-hub(Event-Hub), event-hubs(Event-Hubs)

**Comment by swathipil** [comment]
all bugs in samples fixed, so all samples should work now
