### ISSUE TITLE
[Service Bus] Review Quick Start doc for Track 2 Service Bus

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15162]
This issue is to track the review of the quick start docs that @spelluru has written for the version 7 of the servicebus library.
Use either this issue or email to share feedback with @spelluru and close this issue once we are satisfied with the content.

- [Quick start for Queues](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-queues?branch=release-service-bus-track2-sdk-ga)
- [Quick start for Topics & Subscriptions](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-topics-subscriptions?branch=release-service-bus-track2-sdk-ga)

**Comment by spelluru** [comment]
Hi @KieranBrantnerMagee - Please wait until tomorrow morning to review the quick start. I am going to test with the latest preview packages and update the quick starts today. Thanks!

**Comment by KieranBrantnerMagee** [comment]
Ah, Thanks for the notice @spelluru , and for all your help getting this stood up+tidied.

I'll pend my review, leaving only the one note I'd gotten to when I saw your ping as a note-to-my-future-self, will populate this comment after tomorrow and CC you when done :)

**Observations**
- Prereq python version compat:  Currently says >3.5; we technically support 2.7, but if there is an initiative to deemphesize that in docs that I don't know about feel free to just LMK.

**Comment by spelluru** [comment]
Hi @KieranBrantnerMagee - Thanks. I have updated the prerequisite. The above two articles are ready for your review now. I tried to keep the quick start as simple as possible with the following in mind:

- Use Async
- Use batching

And, provide a link to all the samples on GitHub.

I appreciate if you could review and provide your feedback as soon as you can.

Thanks,
Sreedhar

**Comment by KieranBrantnerMagee** [comment]
So I spoke to our architects about the use Async guidance; was this something inherited from other languages?  AIO in python is still typically the exception more than the rule, sync being most common in quickstart and other high-level documentation.

Let me know if the preference for Async first is coming from "on high" and I can try and connect folks to hammer this out.  

Outside that, mostly only small comments, see bullets below, feel no hesitation to throw rocks/have differing opinions, glad to dig into any of this:

- for whichever of <sync, async> that is not shown, a snippet pointing at the opposite samples and addressing that both modes are supported with comparable naming is likely useful.
- In both samples you call receive as so `receive_messages(max_message_count=10, max_wait_time=5)`.  There are some subtleties here that I'd call out.    
  1. First, regardless of the following, is it worth giving an "important" (blue highlight) snippet (like is present for connection string above) to explain these two parameters?  
  2. Second, the subtle part, max_message_count is very literal, MAX message count.  What this means; if the user sent messages individually, not as a batch, if there was a slight delay in those messages being processed by the service backend, the receiver could very well call `receive_messages` and get only 1 or 2 messages from the service.  While that isn't an issue here because of batch, I could very readily see a user removing that and being confused.  Now, I may be overindexing on this fear, and a simple comment like the blue important snippet may be enough to clarify this behavior+the expected mitigation (pragmatically you'd just call this in a loop until you got no messages, or use the iterator-based receiver), so don't hesitate to ask me to clarify what I mean by this if I've been unclear at all, but I'm curious as to how you'd approach this and if you think it would need to be adjusted given the context.
- I MIGHT show both methods of sending, single message and batch, if only to give context for batch and not imply to users that they have to use the batch boilerplate (while still communicating that that's preferrable if any sort of volume or speed is desired), because e.g. in our basic send-receive sample we just do _the most basic_, but I understand the merit of holding up Batch as a best practice, so I'll leave this for your judgement as well. (as to whether you think there's room/an advantage to hold up both flows, or if this adds too much noise especially in context of max_message_count.  This may, as with the above, be solved by additional comments too, so I'm open to options.)
- Finally, in next steps, (if there's not a link elsewhere I'm missing) I might include links to our README or reference documentation.  Samples are a great jumping off point, but we've noticed in user studies there are different strata of folks who prefer various methods of exploring docs/code.


On a whole, very solid quickstart.  I hope this does not come off as too nitpicky, the structure is terse, clear/to-the-point, and covers the key bits, and whenever I was questioning "well maybe we should touch on other settlement" (or other additional functionality) I ended up coming back to this being the truly minimal and core flow; so very much appreciated for the effort and time to put this together and endure my bikeshedding here :)

**Comment by spelluru** [comment]
Hi @KieranBrantnerMagee - Thanks for the feedback. Appreciate it. 

I will update the quick start to use the Sync method. For .NET, I used Async. For Java, I used Sync based on input from Srikanta. 
I will go through the feedback tomorrow and update the quick start. I will ping you if I have questions or need clarifications. Thank you.

**Comment by spelluru** [comment]
Hi @KieranBrantnerMagee - Please review the updated articles when you get a chance. I will clean up a little and add details where needed after your review and send it for a final review. 

- I am using Sync now. In the Samples section, I provide links to both sync and async samples. 
- I have added methods for sending a single message, list of messages, batch of messages. This code is actually from the sample. I have added code comments. I have added step-by-step instructions as well as the full code. 
- I am using the iterator-based receiver now. This code is also from one of the samples in the Git repo. 
- I have added descriptions for max_message_count and max_wait_time. I got them from the SDK documentation. 
- I removed the highlighting of replacing connection string and queue/topic/subscription names
- In the next step, I add a link to the README doc for samples. The link to the Python reference content may not be accurate right now. I will have to update it once the API reference content goes live.

**Comment by spelluru** [comment]
Hi @KieranBrantnerMagee - could you review the updated quick as soon as you can? We need to release the quick start as soon as the SDK goes GA. Thanks.

**Comment by KieranBrantnerMagee** [comment]
A few minor thoughts.

- I may have been unclear when giving the info about max_message_count.  The comment "        # receive 16 messages you sent, waiting for max 5 seconds" has the same issue as before, namely that you will not necessarily receive all 16 messages, only _up to_ 16.  Adjusting the wording as so should help.
  - That said, you do get it correct below with the description you grabbed from the docs, regarding which: you took my meaning backwards for the blue comment.  I LIKED the callout for connstr/queue, and was wondering if we could have it for explaining the max_message_count complexity if you agreed that it'd be more clear than just the inline comment.
- I'd note, just to be clear, this is not the iterator-based receiver, but that's fine, I didn't have an issue with it, I was just saying you could mention that alongside the max_wait_time clarification as an option if more-than-one-off receiving is desired, not that switching out the entire sample was necessary.

Coming together well.  Thanks as always.

**Comment by spelluru** [comment]
Hi @KieranBrantnerMagee - 

-	In this quick start, the send code sends exactly 16 messages to the queue/topic. So, I mentioned about receiving 16 messages. Would there be case when the receive code receives fewer than 16 messages (in this example)? Do you mean there is a chance that the receive operation will timeout before receiving 16 messages and that’s why we need to say “up to 16 messages”? 
-	Oops. I agree that having a note would highlight them more. I will switch it back for the connection string and queue/topic name, and highlight max_wait_time and max_message_count
-	Could you point me to a sample that uses the iterator-based receiver? I will see if it's simple enough for a quick start and switch. 

Thanks,
Sreedhar

**Comment by spelluru** [comment]
@KieranBrantnerMagee - Took care of the first one. 

Working on the second one. I see the iterator based code here: 
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/sync_samples/receive_iterator_queue.py

I will update my test code, test it, and then update the articles. thanks.

**Comment by spelluru** [comment]
@KieranBrantnerMagee - I have updated the code now. Please review and feel free to provide more feedback. Thanks.

**Comment by KieranBrantnerMagee** [comment]
Thanks as always, you beat me to the punch on the iter link :P  (And no worries on the highlighting, looks good now.)

Fewer comments every time :)

- "Would there be case when the receive code receives fewer than 16 messages" Yes, that's the subtlety I'm calling out.  There are various reasons this can happen, and although it _most of the time doesn't_, if the service has not processed all messages it has in the queue yet by the time the first one is received, it will simply hand what ones it has to the user UP TO 16.  To be clear, a terrible diagram:
`
<make receive_messages call> --- (Can wait up to max_wait_time) --> <Receive first message, poll for more messages immediately, requesting UP TO max_message count> --- (If more messages are not immediately available after receiving the first, even if num_messages < max_message_count, we return what we have to the user) ----> <return from receive_messages_call>
`
- I would add max_wait_time to the get_queue_receiver or get_subscription_receiver calls so that this sample terminates.  As you have it now, it will continue waiting forever.  `max_wait_time=5` is my generic go-to; I would probably flesh out the context around "add this code below the print" to explain that you're calling a function that will continually receive new messages, and telling it to halt if it goes 5 seconds without receiving anything new.

Quick question for you spelluru while we're discussing this; if as we go forward we find users want a breadcrumb to a certain thing, or are hitting confusion, I assume this doc is flexible to take changes?  Would you be our contact for that, for my own knowledge?  (I ask because sometimes we get folks asking doc questions here that point into locations I can't touch so I like to make sure I have contacts)

**Comment by spelluru** [comment]
Np. Actually, thank you :)

For #1, since this is a quick start for someone new to the service, I would wait until at least a couple of customers run into the issue to add this detail. I have run the samples several times for past 10+ days and haven't seen the issue so far, so I would take that risk :). 

For #2, added the following statement. 
"This code continually receives new messages until it doesn't receive any new messages for 5 (`max_wait_time`) seconds. " 

Please see the articles. 
[Queues](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-queues?branch=release-service-bus-track2-sdk-ga#receive-messages-from-a-queue)
[Topics/Subscriptions](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-python-how-to-use-topics-subscriptions?branch=release-service-bus-track2-sdk-ga#receive-messages-from-a-subscription)

Yes. I would be the primary contact from the content team. We can update and publish the modified articles twice a day (10 AM and 3 PM PST). It's easy for you to make the update yourself too as the source content (MD files) behind these articles are all in a GitHub repo. To modify the article in the public repo (azure-docs), you don't need any special permissions, but internally we recommend that you work with the private repo (azure-docs-pr) as that would give you Acrolynx reports (spelling, grammar, style, etc...), and more importantly the staging links where you can verify how the changes look in a staging environment before you can sign off on the PR and take the updated content live. Please see this getting started guide for DOCS: 
https://review.docs.microsoft.com/en-us/help/contribute/docs-overview?branch=master

**Comment by KieranBrantnerMagee** [comment]
Looks good.  I'm admittedly torn about #1, because the dev in my head is screaming "but it's not TECHNICALLY precise", but I'll trust your judgement on this and simply ping you again if we hit any users who are confused as a result.

No other comments from me, I dropped this in the Python team channel and it passed the scream test as well, so thank you for all the help/info/patience working through this :)

**Comment by spelluru** [comment]
@KieranBrantnerMagee - Sure thing. I am open to updating the article if we hear from customers on this issue. Please close the issue when you get a chance. Thank you for the great feedback. I really appreciate it.
