### ISSUE TITLE
ServiceBus network disconnect detection & reconnect

### ISSUE THREAD

**Issue by fdarie** [Azure/azure-sdk-for-python#152]
Hi,
I'm using the python Service Bus class to receive messages from my SB topics.
My use case requires to detect if the client loses the connection with the cloud and to have some sort of retry mechanism.
I've done some testing by disabling the connection and the client seems to block forever even after restoring the connection.
Is there any way do get a notification in the event of network disconnection and to have a connection retry mechanism?

**Comment by lmazuel** [comment]
Just had a discussion with the ServiceBus team. For problem around performance and missing features, the current recommendation from the ServiceBus team is to use AMQP instead of HTTP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/

The ServiceBus team were not able to propose better performance using HTTP, due to HTTP limit.
