### ISSUE TITLE
Timeout does not work in receive_message and peek_message

### ISSUE THREAD

**Issue by shishirpy** [Azure/azure-sdk-for-python#15589]
- **Package Name**: azure.storage.queue
- **Package Version**: 12.1.3
- **Operating System**: macOS Catalina
- **Python Version**: 3.7.4

**Describe the bug**
When you `receive_message` or `peek_message` with a timeout, the timeout does not work.

**To Reproduce**
1. Create a QueueClient name it `client` and connect it to a queue.
2. Send a message to the queue.
3. Disconnect your internet.
4. `client.peek_messages(timeout=1)`

**Expected behavior**
Since, there is no network connection. I except the request to timeout, give me a timeout message, return the control to the shell.

**Comment by tasherif-msft** [comment]
Hey @shishirpy,
In this case you'd actually be looking to use `connection_timeout` since if you disconnect your internet before that call you wouldn't be able to connect to the service and therefore `timeout` wouldn't work.
For reference to optional parameters: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-queue/README.md#optional-configuration

**Comment by shishirpy** [comment]
`connection_timeout` does not work the way you say. With the following command `qc.send_message(msg, connection_timeout=3)` with network disconnected the control is not transferred back to the shell.

**Comment by tasherif-msft** [comment]
Hey! could you please try using the following: `queue_client.receive_message(retry_total=0, read_timeout=1)` 
Let me know if this works.
