### ISSUE TITLE
DefaultAzureCredential doesn't forward all arguments to all credential types

### ISSUE THREAD

**Issue by Itayazolay** [Azure/azure-sdk-for-python#15787]
- **Package Name**: azure-identity
- **Package Version**: 1.5.0
- **Operating System**: mac/linux/windows
- **Python Version**: 3.7.9

**Describe the bug**
DefaultAzureCredential does not pass client_id (and other optional parameters, given as keyword-arguments) to InteractiveBrowserCredential. 
It seems that InteractiveBrowserCredential can accept those parameters, so I guess there is no reason why not to pass kwargs to the constructor

**Expected behavior**
DefaultAzureCredential should pass all keyword-arguments to all authentication methods.

**Additional context**
Does client_id related to the interactive browser caching? Do I need to authenticate for each Instance(I use BlobServiceClient) I create or can it cache the token for the process/computer? 

I don't mind making the pull request, seems very straight forward.

**Comment by chlowell** [comment]
The main reason DefaultAzureCredential doesn't pass all arguments to all its inner credentials is that those credentials have irreconcilable options and interpret some arguments in different ways. To avoid mysterious errors and (more) daunting documentation we have tried to limit DefaultAzureCredential's configuration. We intend it to be an easy way to get started with the SDK without having to master all the complexities of authentication. We generally encourage users who want more control over DefaultAzureCredential to consider using [ChainedTokenCredential](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.5.0/azure.identity.html#azure.identity.ChainedTokenCredential) instead. Could you add some more detail about your scenario? What makes you prefer DefaultAzureCredential to using InteractiveBrowserCredential directly, either by itself or with ChainedTokenCredential?

To answer your other questions:
> Does client_id related to the interactive browser caching?
> 
In a sense. It's part of the cached authentication metadata because its value is the client or "application" ID of the Azure AD application to which the credential authenticates users.

>Do I need to authenticate for each Instance(I use BlobServiceClient) I create or can it cache the token for the process/computer?
>
Multiple client instances can share a single credential instance. If you want to cache authentication data persistently so your application can use it across executions, check out the [user authentication sample](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/samples/user_authentication.py). Note the API demonstrated in that sample is only available in the latest beta version (currently 1.5.0b2). We're redesigning it to meet new requirements in our next release.

**Comment by Itayazolay** [comment]
Thanks! 
Closing it for now, Your comment helped me a lot!
The chained credential was the missing link for me.
