### ISSUE TITLE
KeyVaultKey has examples showing up in the class description instead of the separate Examples section

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15795]
[The API Reference doc for KeyVaultKey class](https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys.keyvaultkey?view=azure-python) has the code snippets showing up in the class description instead of the separate Examples section like being done in [the API reference doc for KeyClient class](https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys.keyclient?view=azure-python).

This appears even more jarring in the [table view for classes](https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys?view=azure-python#classes)

![image](https://user-images.githubusercontent.com/16890566/102157221-f33c4680-3e33-11eb-8be9-d2a9278d2990.png)

We should be consistent in how we show examples.

Nice catch @mccoyp!

Found in #15110

**Comment by SHSongs** [comment]
Hi, @ramya-rao-a  
I have interest in this issue, and I wrote PR.  https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1614 
Could you review this PR?


i pr, could you review docs?

**Comment by SHSongs** [comment]
Hi, @ramya-rao-a  
I have interest in this issue, and I wrote PR.  https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1614 
Could you review this PR?

**Comment by mccoyp** [comment]
Hi @SHSongs, sorry about the delayed response! Thank you for taking the time to create a PR for this issue and contribute to the SDK 🙂

Your PR does fix the view of the class description, but unfortunately we'll need a different approach. The file that you fixed up is auto-generated, so the bug would return the next time docs are generated. I've closed the PR for now, since it looks like we may need to make the fix in our source code instead.

**Comment by mccoyp** [comment]
This is tracked by https://github.com/Azure/azure-sdk-for-python/issues/34788.
