### ISSUE TITLE
Title truncated in the overview page for Event Hubs Checkpoint store package

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#15793]
The [overview page for Event Hubs Checkpoint store package](https://docs.microsoft.com/en-us/python/api/overview/azure/eventhub-checkpointstoreblob-readme?view=azure-python) has content that has been pulled from the [readme](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub-checkpointstoreblob/README.md). The last three words `using Storage Blobs` for some reason is not part of the title

![image](https://user-images.githubusercontent.com/16890566/102152028-0269c700-3e29-11eb-83b9-112ae32816f6.png)

Nice catch @yunhaoling!

 Found as part of #15109

**Comment by danieljurek** [comment]
This is because the [metadata updating process](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Update-DocsMsMetadata.ps1#L78) which takes README.md content, appends metadata, updates the title, and pushes into the docs repo is set to look specifically for title content like: 

```regex 
(\#\s+(?<filetitle>Azure .+? (?:client|plugin|shared) library for (?:JavaScript|Java|Python|\.NET|C)))
```

In this case the title `Azure EventHubs Checkpoint Store client library for Python using Storage Blobs` is matched up to the point of `using Storage Blobs` and the version is inserted. 

Would it be possible to change the title to something like: 

> Azure EventHubs Checkpoint Store using Storage Blobs client library for Python

**Comment by danieljurek** [comment]
@annatisch -- You're the first owner in CODEOWNERS, can you route the above question?

**Comment by annatisch** [comment]
Adding @swathipil to help take a look :)
