### ISSUE TITLE
[EventGrid] Add a from_connection_string method

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#15937]
one of the feedback in ux study was to add a from_connection_string method similar for storage, keyvault.

**Comment by lmazuel** [comment]
- There is no concept of connection string in KeyVault (unsure what you're talking about then)
- Storage has one, because you can copy/paste a connection string from the portal
- As far as I'm aware, there is no way to get a connection string from the portal for EventGrid, and connection string builder are not recommended on client side (that's not why we have some).

To discuss with wider team, but I'm suspicious there is anything to do here.

**Comment by rakshith91** [comment]
Agree that there's no value in having a connection string builder for the sake of this, but would be worth to discuss it with service team and keep this in backlog.

**Comment by lmazuel** [comment]
Putting it in backlog, we shall not do it until service team provides a connection string on portal
