### ISSUE TITLE
Cannot set 'required_resource_access' during application create or patch. 

### ISSUE THREAD

**Issue by hutch34** [Azure/azure-sdk-for-python#1596]
I'm attempting to set the 'required_resource_access' for an Application either during creation or by patching after creation but am unable to do so. 

Passing as a parameter during creation gives me the following error: 

`msrest.exceptions.SerializationError: Unable to build a model: Cannot deserialize as [str] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [str] an object of type <class 'str'>`

example: 

`rbac_client.applications.create({
    'display_name': <display_name>,
    'home_page':<home_page>,
    'identifier_uris': 'localhost',
    'available_to_other_tenants': False,
    'required_resource_access': [<required_access_resources_list>]})`

Attempting to patch to update an application gives me a 204 empty response and doesn't update:

 `rbac_client.applications.patch(<object_id>, parameters = {'required_access_resource':
 [<required_access_resources_list>]})`

**Comment by lmazuel** [comment]
This is because you didn't pass the expected arguments (in pass a str when a list was expected).
See `required_resource_access` should be a list of RequiredResourceAccess:
https://docs.microsoft.com/en-us/python/api/azure.graphrbac.models.applicationcreateparameters?view=azure-python

And a RequiredResourceAccess must contains a list of ResourceAccess and optionally a resource_app_id:
https://docs.microsoft.com/en-us/python/api/azure.graphrbac.models.requiredresourceaccess?view=azure-python

And ResourceAccess must contain and id, and optionally a type:
https://docs.microsoft.com/en-us/python/api/azure.graphrbac.models.resourceaccess?view=azure-python

This means that code should looks like:
```python
rbac_client.applications.create({
  'display_name': <display_name>,
  'home_page':<home_page>,
  'identifier_uris': 'localhost',
  'available_to_other_tenants': False,
  'required_resource_access': [{
    'resource_access': [{
        'id': <resource_access_id>
    }]
  }]
})
```

**Comment by lmazuel** [comment]
I believe the question is solved, feel free to comment if not.
Thank you,
