### ISSUE TITLE
[EventHubs] Run samples in live test pipelines

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#16045]
see PR: https://github.com/Azure/azure-sdk-for-python/pull/15694

major steps (copying from formrecognizer):
- Indicate in your tests.yml that you want your samples to run by setting parameter TestSamples: true . Example:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/tests.yml#L9
- Add any environment variables used in your samples to your tests.yml and update them in the keyvault/devops variable group if needed. Example: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/tests.yml#L54-L71
- Run your live test pipeline. Samples will run as a separate step after tests complete.

for eventhub:
- most samples are running forever because of the push mode
    - either tweak them not to run forever
    - or exclude the sample via setting `IGNORED_SAMPLES ` inside `scripts/devops_tasks/test_run_samples.py` 
        - see PR: https://github.com/Azure/azure-sdk-for-python/pull/16033/files 
```python
IGNORED_SAMPLES = {
    "azure-eventhub": [
        "<sample not to be run>.py",
```

(add comment on why we need to ignore some of the samples)

**Comment by yunhaoling** [comment]
echoing issue https://github.com/Azure/azure-sdk-for-python/issues/10425:

# Summary

In order to ensure that our samples are up-to-date and in good working order, they should be routinely validated by smoke testing them as part of the nightly test runs.

# Scope of Work

- Devise an approach to allow published samples to be smoke tested and run as part of the live test suite.

- Validate the design with your language team, architect, and, if needed, the engineering team.

- Perform any implementation or enhancements necessary to integrate the samples with the nightly test runs.

# Success Criteria

- The approach for nightly test run integration of samples has been validated with stakeholders and is consistent with the team's direction.

- The published samples for the Event Hubs packages are smoke tested as part of the nightly test runs.

- The published samples for the Event Hubs packages can be run as part of the live test suite by contributors.

- Failures for the samples during the nightly test runs cause the run for that platform to fail; verification of the nightly results surfaces problems with the samples in the same manner that it does issues in the client library features.

**Comment by swathipil** [comment]
It looks like FormRecognizer is planning to use ARM templates to create resources going forward rather than adding env variables to `tests.yml` for samples, as per [this comment](https://github.com/Azure/azure-sdk-for-python/pull/15694/files?file-filters%5B%5D=.yml#r538868882) in the formrecognizer PR. An issue was created accordingly: #15736.

After a discussion with @lmazuel, SB/EH will also be moving in the direction of using ARM templates for testing samples. This may require transitioning to the use of an ARM template for creating resources, rather than preparers (ie. `servicebus_preparer.py`), for tests.

The ARM template to be used is copied from the azure-sdk-for-net: [`test-resources.json`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/test-resources.json).
