### ISSUE TITLE
[ServiceBus] Run samples in live test pipelines

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#16044]
see PR: https://github.com/Azure/azure-sdk-for-python/pull/15694

major steps (copying from formrecognizer):
- Indicate in your tests.yml that you want your samples to run by setting parameter TestSamples: true . Example:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/tests.yml#L9
- Add any environment variables used in your samples to your tests.yml and update them in the keyvault/devops variable group if needed. Example: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/tests.yml#L54-L71
- Run your live test pipeline. Samples will run as a separate step after tests complete.

for service bus:
- some samples are running forever (the iterator ones)
    - either tweak them not to run forever
    - or exclude the sample via setting `IGNORED_SAMPLES ` inside `scripts/devops_tasks/test_run_samples.py` 
        - see PR: https://github.com/Azure/azure-sdk-for-python/pull/16033/files 
```python
IGNORED_SAMPLES = {
    "azure-servicebus": [
        "<sample not to be run>.py",
```

**Comment by swathipil** [comment]
It looks like FormRecognizer is trying to use ARM templates to create resources going forward rather than adding env variables to `test.yml` for samples, as per [this comment](https://github.com/Azure/azure-sdk-for-python/pull/15694/files?file-filters%5B%5D=.yml#r538868882) in the formrecognizer PR. An issue was created accordingly: #15736.

After a discussion with @lmazuel, SB/EH will also be moving in the direction of using ARM templates to live test samples rather than adding env variables to `tests.yml`. This may require transitioning to the use of an ARM template for creating resources, rather than preparers (ie. `servicebus_preparer.py`), for tests.

The ARM template to be used is copied from the azure-sdk-for-net: [`test-resources.json`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/test-resources.json).
