### ISSUE TITLE
[FileShare]how to delete many? (File Share Batch Delete)

### ISSUE THREAD

**Issue by TiloGit** [Azure/azure-sdk-for-python#16060]
Tried one liner but didn't work. 

Expected: 
```bash
az storage share delete --account-name 'myacc' --name $(az storage share list --account-name 'myacc' --query "[?(name!='kubernetes-dynamic-pvc-keeper')].name" -o tsv)
```

but delete seems to only take one. so my workaround
```bash
for storage_pvc in $(az storage share list --account-name 'myacc' --query "[?(name!='kubernetes-dynamic-pvc-keeper')].name" -o tsv)
do
	az storage share delete --account-name 'myacc' --name $storage_pvc
	#echo $storage_pvc
done
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae881ef-ad75-32e6-6e64-6b526a2d9a5d
* Version Independent ID: 99971e2e-9ff6-f865-07f7-61efbcb16021
* Content: [az storage share](https://docs.microsoft.com/en-us/cli/azure/storage/share?view=azure-cli-latest#az-storage-share-delete)
* Content Source: [src/azure-cli/azure/cli/command_modules/storage/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/storage/_help.py)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by xiafu-msft** [comment]
we will consider toadd this as a service feature

**Comment by jalauzon-msft** [comment]
Hi @TiloGit, I know it has been quite a long time since you opened this issue, but it seems this is something where we need service support. To that end, if you still are looking for something like this to be part of the SDK/CLI, then please consider submitting this feedback to the Storage service team via upvoting or creating a new idea at https://aka.ms/AzStorageFeedback.

This will help the service team gauge interest and prioritize new features. If the feature becomes available in the service, it will be promptly added to the SDK.

On that, I'm going to close out this Issue in favor of submitting feedback directly to the service team.
