### ISSUE TITLE
readthedocs link is broken.

### ISSUE THREAD

**Issue by NoOrangeJuice** [Azure/azure-sdk-for-python#1612]
Hello, the link for the azure-mgmt-datafactory documentation is broken. Is there another source for this information, or perhaps a working link? Thanks.

**Comment by lmazuel** [comment]
Hi @NoOrangeJuice 
The doc is migrating here:
https://docs.microsoft.com/en-us/python/api/overview/azure/datafactory?view=azure-python

This does not answer your question, since there is no sample yet for ADF, but when they will exists, they will be there :)

@hvermis @sharonlo101 ? Is there sample for ADF in Python?

**Comment by NoOrangeJuice** [comment]
Thanks for the update Imazuel.

**Comment by lmazuel** [comment]
Links is fixed and brings correctly to https://docs.microsoft.com/en-us/python/api/overview/azure/datafactory?view=azure-python now

**Comment by hvermis** [comment]
We have sample for aDF documented here: https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-python
@lmazuel should we provide you the full script?

**Comment by lmazuel** [comment]
@hvermis let's discuss this by email (sending it right now)
