### ISSUE TITLE
Any way of retrieving first N sorted records out of a table in Table Storage?

### ISSUE THREAD

**Issue by simrigh** [Azure/azure-sdk-for-python#16196]
Apologies if that's not the best suited way of asking a question, but given how difficult it seems to be to get a shot at someone responding in SO or docs.microsoft.com, thought this place might be my best chance.

I am interested in retrieving top N recently inserted entities from a table in Table Storage. Given that every entity in a table has a timestamp, I imagine this is something that should be inherently possible? 

Alternatively, I could arrange my PartitionKey and/or RowKey so that they would contain the time information, and could sort on that. Since they form an index, I imagine this should be possible too?

Is there any way to achieve that using either azure-cosmosdb-table or azure-data-tables?

Thank you.

**Comment by seankane-msft** [comment]
Hi @simrigh! Unfortunately there is no 'sort_by' option for queries. You can adopt something similar to [this .NET Stackoverflow question](https://stackoverflow.com/questions/40593939/how-to-retrieve-latest-record-using-rowkey-or-timestamp-in-azure-table-storage). Using ticks since 01-01-0001 as the `RowKey` would be the best method and then you can use the `results_per_page` to get the top 'N' entities inserted.

```python
N = 10
with TableClient.from_connection_string(os.environ['conn_str'], table_name='myTable') as table_client:
    for page in table_client.list_entities(results_per_page=N):
         for entity in page:
             # there will be N entities in this page, the RowKeys will be in descending order.
             print(entity['RowKey'])
         break
```

Let me know if you have further questions!
