### ISSUE TITLE
'ClientSecretCredential' object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by spoloj** [Azure/azure-sdk-for-python#16520]
- **Package Name**:  azure-identity
- **Package Version**: 1.5.0
- **Package Name**:  azure-mgmt-managementgroups
- **Package Version**: 0.2.0
- **Operating System**:  linux
- **Python Version**:  3.8.5

**Describe the bug**
```
from azure.identity import ClientSecretCredential
import azure.mgmt.managementgroups

azure_credential = ClientSecretCredential(
    client_id=xxxxxxx,
    client_secret=xxxxxx,
    tenant_id=xxxxx)

management_client = azure.mgmt.managementgroups.ManagementGroupsAPI(azure_credential)
mgmt_groups = management_client.management_groups.get(
    "test",
    expand='children'
)
subs = []
for record in mgmt_groups.children:
    subs.append(record.name)
```
This is giving an error `AttributeError: 'ClientSecretCredential' object has no attribute 'signed_session'`

**Additional context**
Authentication with `ClientSecretCredential` to resources library and subscription library is working but not to Management Groups

**Comment by chlowell** [comment]
The latest version of ManagementGroupsAPI doesn't support credentials from azure-identity (a future version might, @msyyc for any comment on the roadmap). It expects an [msrestazure authentication class](https://docs.microsoft.com/python/api/msrestazure/msrestazure.azure_active_directory?view=azure-python). There are a couple ways you can move forward:
1. Use [msrestazure.azure_active_directory.ServicePrincipalCredentials](https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory.serviceprincipalcredentials?view=azure-python) instead of ClientSecretCredential
1. Use [AzureIdentityCredentialWrapper](https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py) to wrap ClientSecretCredential

AzureIdentityCredentialWrapper is convenient if your application also uses clients expecting azure-identity credentials. If your application uses only ManagementGroupsAPI, or uses only clients expecting the msrestazure API, I'd suggest using ServicePrincipalCredentials.

(Related: #9756, #10274, #14499, #15330)

**Comment by jsntcy** [comment]
Close this as it's duplicated with https://github.com/Azure/azure-sdk-for-python/issues/16923

**Comment by fxdgear** [comment]
@chlowell I appreciate the response but tbh I find the whole Azure Python SDK ecosystem to be totally incomprehensible.

There's like 3 or 4 different python packages that all have a `SubscriptionClient` and all have different levels of support for various features, auth etc.. 

Being someone who is brand new to the azure ecosystem I don't know how I am supposed to know what package I'm supposed to use which module I'm supposed to import the SubscriptionClient from... The documents seem to references the `azure-mgmt-subscription` and the `azure-mgmt-resources`. I found a GH issue with the `azure-mgmt-subscription` lib and it said to use the `azure-mgmt-resources` lib which is where I am now and _now_ you're telling me to use a different one... 

I apologize for this rant. But I'm frustrated and confused :( 

I'll try using the package you mentioned and report back with my success or failures.

**Comment by fxdgear** [comment]
so trying to use the `mgmtgroups` lib I tried the following: 

```
In [1]: from azure.mgmt.subscription import SubscriptionClient

In [2]: from azure.identity import EnvironmentCredential

In [3]: credential = EnvironmentCredential()

In [4]: subscription_client = SubscriptionClient(credential)

In [5]: subs = subscription_client.subscriptions.list()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-56748533d062> in <module>
----> 1 subs = subscription_client.subscriptions.list()

AttributeError: 'SubscriptionClient' object has no attribute 'subscriptions'
```

I can't even query for the subscriptions using this Client.
