### ISSUE TITLE
Authentication failed: load_pem_private_key() missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by xinyeah** [Azure/azure-sdk-for-python#16789]
This issue happened on 2021-02-09 00:27 PST. My job was running well before and it started to fail with the error "Authentication failed: load_pem_private_key() missing 1 required positional argument: 'backend'".
I believe the root cause is that a new version of Azure SDK pypl patch was rolled out, which created an incompatibility.
Please find attacked traceback and pip list.
[traceback.txt](https://github.com/Azure/azure-sdk-for-python/files/5999082/traceback.txt)
[pip list.txt](https://github.com/Azure/azure-sdk-for-python/files/5999083/pip.list.txt)

To reproduce:
``` 
import os
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential

keyVaultName = os.environ["KEY_VAULT_NAME"]
KVUri = f"https://{keyVaultName}.vault.azure.net"

credential = DefaultAzureCredential()
client = SecretClient(vault_url=KVUri, credential=credential)
secret = client.get_secret(secret_name, version=version)
```

Prerequisites
```
install the libraries from PyPI
azure-identity==1.5.0
azure-keyvault==4.1.0
```

To temporarily fix it, I added an additional fix version of the cryptography library from PyPI:
```
PyJWT==1.7.1
```

**Comment by chlowell** [comment]
Thanks for opening this issue. The fact that rolling back to an old PyJWT fixed it for you is interesting because PyJWT is a transitive dependency of azure-identity. That leaves me wondering whether this is a case of incompatible dependencies. I'm unable to reproduce the exception though. Could you please add the whole traceback and the output of pip freeze?
