### ISSUE TITLE
High CPU usage when sending a lot of messages to ServiceBus or EventHub

### ISSUE THREAD

**Issue by mihaiblidaru** [Azure/azure-sdk-for-python#16991]
- **Package Name**: azure-servicebus, azure-eventhub
- **Package Version**: 7.0.1
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.5

**Describe the bug**
First of all, this is a series of questions more than a bug report but I don't know how to flag the issue as a question.

Sending messages synchronously to Service Bus or Event Hub uses 100% of 1 CPU core ( Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz with Hyperthreading enabled so in reality it would not use the core completely). Running the same script with cProfile I see some kind of polling behavior (intended or not). When running on my PC (my region is North Europe and I am 1500km away from the datacenter) I get a throughput of 200-300ish messages/s. Running the same script on a Standard_D2s_v3 VM on Ubuntu Server 18.04 i only get around 100-150 messages/s. I assume that the performance is degraded because the single core performance of the Standard_D2s_v3 VM.

**To Reproduce**
Send 5000 messages of 3000 bytes each using batch mode with default max_size (256K) to a queue or topic or event hub as fast as you can. That would be 85 messages/batch sent to Service Bus. Monitor the CPU usage during that time. Run the same sending script using a profiler. I'm using the Standard Tier for both ServiceBus and EventHub

**Expected behavior**
I would assume that sending messages to ServiceBus would be more of a network intensive job rather than a CPU intensive workload.

**Screenshots**
cProfile output when sending to Service Bus
![sb](https://user-images.githubusercontent.com/24492443/109484974-63488900-7a81-11eb-9e06-27c4748bb7c9.png)
cProfile output when sending to Event Hub
![eh](https://user-images.githubusercontent.com/24492443/109485074-83784800-7a81-11eb-9f6d-3f7af501817f.png)

**Additional context**
In both cases I only sent 5000 messages of 3000 bytes each but the number of function calls I see with the profiler is insane. For instance, my scripts calls ServiceBusSender.send_messages 115 times which internally gets to call client:do_work more than 1 million times. Is this kind of polling behavior intended? Does it work the same way in other programming languages?

**Comment by mihaiblidaru** [comment]
As an update, I just tested again on a Standard_D2s_v3 and i got a much higher throughput around 600 messages/second which is more than acceptable for our use case. I guess the first time I tested I might have setup the VM in a different region than my Service Bus namespace and I had latency issues. 

Still, the CPU usage is still high, using 1 core completely just for sending messages.

**Comment by yunhaoling** [comment]
hey @mihaiblidaru , thanks for reaching out and the profiling figure, that's super illustrative.

So the sending performance is determined by multiple factors, and among all of them the most import two are:
- region:  same region between the client and service would give the best performance while the farther away the client (VM) is from the service, the lower performance due to the network latency.
- throughput unit: on the service side this a configuration called throughput unit, according to the service descrption:
> The throughput capacity of Event Hubs is controlled by throughput units. Throughput units are pre-purchased units of capacity. A single throughput lets you:
Ingress: Up to 1 MB per second or 1000 events per second (whichever comes first).
Egress: Up to 2 MB per second or 4096 events per second.

more details could be found [here](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-scalability).

So it is worthwhile to check the setting of throughput unit and increase the unit as per your requirements.

----

As for the high CPU usage:
- The sync implementation is based on the pulling mode -- within the sdk when send is called, there is while loop keeps calling underlying amqp connection to dowork (send and receive data) and checking if all the messages are being sent. Once the sending is finished, the send method shall return.
- This is bound to the implementation of the underlying amqp protocol library (which is pull based) and an expected behavior.

One thing I think you could try is to use a separate thread for sending or use the async module.

----

I hope your questions are answered and don't hesitate to ping me if you have more questions.

**Comment by mihaiblidaru** [comment]
Thank you for your suggestions @yunhaoling 

I will test again using a higher number of throughput units. I am pretty sure I hit the 1MB per second Ingress limit. I'm not really woried about EventHub sending performance because the number of events we will send to an eventhub is fairly limited. The test I ran was more of a stress test to know which is the max throughput my script can achive and that's when I accidentaly discovered the polling behaviour in the amqp library which is used by both eventhub and servicebus libraries. 

As for the cpu usage when sending to Service Hub, my use case is very simple. I just read from a file or a FIFO line by line and send each line as a message to a topic or queue to be read by other services. The messages have to be delivered in order so I cannot use multiple threads because that would mess with the message ordering. I know ServiceBus doesn't guarantee ordered delivery but from my tests as long as I use only one publisher per queue and one reader per queue I do receive them in order.

I will have a look into the async version of the library though. I did some preliminary testing using one of the code examples available ([send_queue_async.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/samples/async_samples/send_queue_async.py)) and I got  a little bit more throughput. Analyzing the script with cProfile I see number of internal calls is much lower than with the sync version. Python async programing always looked a bit daunting to me and that's why I avoided it initially but now I think it may be worthwhile.
