### ISSUE TITLE
Python storage pipeline warning

### ISSUE THREAD

**Issue by tasherif-msft** [Azure/azure-sdk-for-python#17001]
Currently the `python - storage` pipeline gets a warning the warning attached below. 
Please advise on what's causing this.
![image](https://user-images.githubusercontent.com/69483382/109578548-36f63200-7aac-11eb-9057-0672165b26d0.png)

**Comment by scbedd** [comment]
@praveenkuttappan can you jump in here?

**Comment by tasherif-msft** [comment]
AH I think @praveenkuttappan had mentioned that we'd be using whls in the APIViews instead now. I assume it has to do with that?

**Comment by praveenkuttappan** [comment]
@scbedd @tasherif-msft : Sorry for the delay. We are planning to change this check to hard error on March 5th. I am collecting all such failure candidates and sending email to architects to get them approved. @tasherif-msft Appreciate if you can share API review link to automatic review to architects and get it approved since manual reviews were created using json file.
