### ISSUE TITLE
Connect with JWT

### ISSUE THREAD

**Issue by nisani33** [Azure/azure-sdk-for-python#17155]
Hi, Is there any way to connect to Azure using Azure Python SDK with just the JWT? I have code that returns Valid JWTs and now I need to set a connection with these JWTs.
 I try to look here https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd but I didn't find anything useful

**Comment by yunhaoling** [comment]
hey @nisani33 , thanks for reaching out!

to better help you, may I ask a few more questions:
- which Azure Python SDK (Azure Service) you are you using.
- are you using the azure-identity library for authenticating the service you want to connect to

also looping in @chlowell who know more than me on authentication.
hey Charles, do you know whether we have such kind of support in the identity/core library?

**Comment by nisani33** [comment]
Hi,
thank you for the answer.
I am using the following Azure SDK services

azure-graphrbac
azure-mgmt-resource
azure-mgmt-authorization
azure-mgmt-keyvault
azure-mgmt-compute

I used to use the "UsernamePasswordCredential" from azure-identity.
but now I don't have the password of the user but only a valid JWT. I can't find anything in the Azure identity that would fit me.

**Comment by chlowell** [comment]
azure-identity doesn't include a credential type for this because it's a rare scenario with severe limitations (an access token will expire and is valid only for certain resources). We do have a sample showing how one could be implemented though: [custom_credentials.py](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/samples/custom_credentials.py#L19). You may hit a speedbump with azure-graphrbac because it expects a different credential API than azure-identity provides. You can use an adapter [like this](https://github.com/jongio/azidext/blob/master/python/azure_identity_credential_adapter.py) to work around that.

**Comment by nisani33** [comment]
Thank you very much for your response. It was very helpful.
I am having difficulties with azure-graphrbac, as you mentioned.
I worte the following code:
`if __name__ == '__main__':
    jwt = get_jwt()
    access_token = StaticTokenCredential(jwt)
    subscription = SubscriptionClient(access_token)
    for sub in subscription.tenants.list():
        print(sub.as_dict())
    wrapped_credential = AzureIdentityCredentialAdapter(access_token, resource_id="https://graph.microsoft.com/")
    g = GraphRbacManagementClient(wrapped_credential, TENANT_ID)
    for user in g.users.list():
        print(user)`
I was able to print tenants, however, I received an error when printing users.

`  File "/Users/yossinisani/work/cymptom/cymptom-collector/venv/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/yossinisani/work/cymptom/cymptom-collector/venv/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/yossinisani/work/cymptom/cymptom-collector/venv/lib/python3.7/site-packages/azure/graphrbac/operations/users_operations.py", line 158, in internal_paging
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Access Token missing or malformed.`

 When I look for this error, I see that I need to change the resource_id (like I did but I still get an error).
 Thanks

**Comment by chlowell** [comment]
Looks like you're running up against one of the limitations I mentioned: an access token is valid for specific resources, and you can't change which ones after the token's been issued. If the access token you have isn't valid for a resource you want to access, you will have to get another token. If you can't use one of the credentials in azure-identity, you might try writing your own custom credential, as in the sample, wrapping your code for acquiring access tokens.

**Comment by nisani33** [comment]
Thanks for your response. 
I'm getting a token for a management resource and I'm changing the resource for a graph resource using the API "DelegationToken". 
Does there exist a place I can find all the valid names for the resources name parameter of this API?

**Comment by chlowell** [comment]
> I'm getting a token for a management resource and I'm changing the resource for a graph resource using the API "DelegationToken".

If you mean you're modifying an access token issued for Azure Resource Manager (e.g. resource "https://management.core.windows.net/") to access a Graph API, that won't work. Any change to the token invalidates it. I don't know a way to exchange an ARM token for a Graph token. Normally you would request, from Azure Active Directory, an access token for whatever Graph scopes you need.

> Does there exist a place I can find all the valid names for the resources name parameter of this API?

None that I know. [Graph documentation](https://docs.microsoft.com/en-us/graph/permissions-reference) describes their permissions model, and what scopes are required for each API, so you should be able to find what you need there.

It normally isn't necessary to think about all that as an application developer though, because Azure SDK clients and credential types handle acquiring the right tokens. Are you trying to authenticate by a method the SDK doesn't have a credential type for?
