### ISSUE TITLE
AccessToken object could use some usability improvements

### ISSUE THREAD

**Issue by lengau** [Azure/azure-sdk-for-python#17295]
**Is your feature request related to a problem? Please describe.**
AccessToken objects are a bit messy to work with, especially with regards to checking whether they're expired (or indeed their expiration time) and using them for ODBC connections as specified in [the ODBC docs](https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver15#authenticating-with-an-access-token)

**Describe the solution you'd like**
Add the following properties to the `AccessToken` class:
* `is_expired` (returns a bool based on whether the token is expired or not.)
* `expires_datetime` (returns a datetime object of the expiry rather than just an int)
* `token_struct` (returns a `struct` object that matches the `AccessToken` struct defined [in the ODBC docs](https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver15#authenticating-with-an-access-token)

**Describe alternatives you've considered**
Currently I implement these myself, but that makes them less discoverable and makes separation of responsibilities strange.

**Additional context**
The context for the expiry is primarily for use when debugging or manually exploring using something like a Jupyter notebook. It makes things much nicer when doing either. 

For the struct and bytes, it makes code for connecting to Azure SQL (and possibly other Azure services where the primary connection mechanism is not another portion of the Azure SDK).

For example, in https://github.com/mkleehammer/pyodbc/issues/228 it shows that the correct way to create a pyodbc connection right now is:

```python
creds = identity.DefaultAzureCredential()
token = creds.get_token('https://database.windows.net/').token.encode('utf-16-le')
token_struct = struct.pack(f'<I{len(token)}s', len(token), token)
conn = pyodbc.connect(connection_string, attrs_before={1256:token_struct}
```

This requires everyone who wants to create an ODBC connection using Azure token credentials to know the format of the structure needed and how to pack it.

This would also make things like managed identities in SQLAlchemy (https://github.com/sqlalchemy/sqlalchemy/issues/6031) far easier.

**Comment by chlowell** [comment]
Thanks for opening this issue! I believe you're the first person to open an issue about AccessToken 🥇

I agree AccessToken is awkward in this scenario. Honestly, it wasn't designed with this in mind, our focus was on HTTP bearer authentication by Azure SDK clients. As for how we could make it less awkward, we're pretty well stuck with AccessToken as it stands. It's a namedtuple that must remain backward compatible. Augmenting it into a class while retaining functional namedtupleness is, I think, possible but too tricky and too clever.

Helper methods are pretty easy though. Of your desired properties, `token_struct` looks like the best candidate because it's only a couple lines of code but writing them requires documentation we don't have here. I don't know that we would incorporate it into one of our libraries. Someone on the review board would probably say "it's only a couple lines of code--is this a documentation problem? Should this be a sample instead?" Which are fair questions. If we had code for this in a [sample for our identity library](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/samples/README.md), would that have helped you?

**Comment by lengau** [comment]
Thanks for the quick response!

In response to the question about a sample - it probably would have, as I checked the Azure SDK documentation before I started Googling. To be honest though, for my particular use case the particular documentation page that would have been most useful is either in the Azure SQL docs (https://docs.microsoft.com/en-us/azure/azure-sql/database/connect-query-python) or as a section in the authentication docs (https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=bash).

It was only after I found the first step to my solution in the PyODBC issues board (https://github.com/mkleehammer/pyodbc/issues/228) that I backed into the question of why the AccessToken itself couldn't create the struct defined in the [Azure SQL ODBC docs](https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory#authenticating-with-an-access-token) (along with the frustration of not being able to easily check whether the token had expired or its expiry time, since further steps of what I needed to do ended up requiring me to create code that was able to generate SQLAlchemy engines to solve this: https://github.com/sqlalchemy/sqlalchemy/issues/6031).

With respect it being a namedtuple: namedtuples are just tuple subclasses with some of Raymond Hettinger's extra brilliance sprinkled on top, so what I've done in [the attached pull request](https://github.com/Azure/azure-sdk-for-python/pull/17300) should be backwards compatible in almost every case. The only case I can think of where it wouldn't be the same (other than if one checked for the nonexistence of the new properties) is if someone were to try to traverse the inheritance tree, as there's an extra layer of inheritance (`_AccessToken`) between `AccessToken` and `tuple`). However, it wouldn't break things like `isinstance` or `issubclass`. A future version (once Python 2.7 and 3.5 support are dropped) could be rewritten using `typing.NamedTuple` or, if the inheritance edge case I mentioned is problematic, the `typing.NamedTupleMeta` metaclass.

**Comment by lengau** [comment]
Actualy, thinking more about it another good place to document this would be in the Azure SQL pyodbc documentation. Perhaps as an additional example on [this page](https://docs.microsoft.com/en-us/sql/connect/python/pyodbc/step-3-proof-of-concept-connecting-to-sql-using-pyodbc?view=azuresqldb-current). I'll file that separately through the feedback form.

**Comment by chlowell** [comment]
Thanks for filing that doc feedback. There's a documentation gap here, and PyODBC or Azure SQL seem more likely to reach interested users with their documentation than the Azure SDK. Thank you also for the PR implementing your suggestions and for thinking through their compatibility. Having read your PR, let me summarize my thoughts here to keep all the context in one place.

Setting aside compatibility concerns, I have other doubts about adding these properties. As your PR shows, none is particularly difficult or painful to write. The first two are one-liners using well-known standard library methods for working with Unix timestamps. That is to say, we wouldn't give much help to typical Python developers by writing `is_expired` or `expires_datetime` for them. I think `token_struct` could be more helpful, by perhaps saving users from doing some research, but I doubt the scenario is common enough to warrant adding API for it at this time. If it does turn out to be a common and painful scenario, I think a helper method would be better than something on AccessToken because we have libraries in the SDK (e.g. for Azure Communication Services) that use AccessToken to carry tokens not issued by Azure Active Directory. `token_struct` undermines the generality of AccessToken--and wouldn't work--in those cases.

My overall view is that we should fill the documentation gap, then wait to learn more about usage before adding new API here. Does that make sense?

**Comment by lengau** [comment]
Agreed about the documentation issue - I've fixed it over in both PyODBC and in SQLAlchemy, and it looks like the identity credentials example is going to be added to the Azure SQL docs.

Whilst I agree that the additions in my PR aren't strictly necessary, I'd argue that they make working with access tokens more [pythonic](https://www.python.org/dev/peps/pep-0020/).

I also believe the `token_struct` scenario is going to become quite common as Microsoft (correctly, IMO) pushes companies to start using credentials like this over using usernames and passwords in the connection string. The mechanism for doing so was unfortunate, but unless the SQL Server developers add that functionality (seems unlikely), any Python application trying to connect to a SQL Server instance that requires access token based authorisation will need to implement this. (Putting the token in the connection string [as was done for MySQL connections](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-sign-in-azure-ad-authentication) seems like a better solution and wouldn't require this conversion, but it wasn't done this way for SQL Server.)

As far as I can tell, the only consistent dependency for performing this is the `azure.identity` package (and its dependencies such as `azure.core`), so even if it's not attached to the `AccessToken` class itself, at minimum it seems like the Azure SDK, rather than the user, should be responsible for providing the function that turns the Azure access token into the structure needed by Azure SQL. It's not strictly necessary, but neither are classes like `AppServiceCredential` or `AzureCLICredential`. In all cases, however, these make a developer's work much simpler, allowing us to focus on our own applications rather than manipulating data structures provided by one Microsoft product into a form accepted by another. So whether it's a part of the `AccessToken`, the various credential classes (or perhaps a Mixin to provide a `get_sql_token` method, since it can always then use the class's own `get_token` method) or even a utility function somewhere, placing this somewhat unfriendly to implement functionality somewhere in the Azure SDK rather than blindly copied and pasted into each client application seems like it would be a much cleaner solution for developers trying to use Microsoft's products.

**Comment by chlowell** [comment]
> it seems like the Azure SDK, rather than the user, should be responsible for providing the function that turns the Azure access token into the structure needed by Azure SQL.

The Azure SDK doesn't include a SQL client (that I know of 😆), so we aren't discussing an SDK scenario here. We welcome developers to use azure-identity wherever it's helpful. However, the library exists to provide Azure AD authentication to Azure SDK clients, so that's the focus of our API.

Transforming access tokens to ODBC structs may become a popular and important scenario for Azure SDK users. Until it has, I'm comfortable pointing them to documentation. I don't want to preemptively add API on the assumption that this will become a popular and important scenario best supported by an API we can design today. That could backfire to the detriment of overall user experience in predictable ways.
