### ISSUE TITLE
API to list permissions for a given KeyVault

### ISSUE THREAD

**Issue by asimarora** [Azure/azure-sdk-for-python#17537]
Hello,

I am using this python SDK for quite some time (It works quite well). However there is a suggestion (If it fits the design). I was trying to list (Applies to Purge and DEL also) all secrets from a given KeyVault then an exception was thrown Saying that 

"The user, group or application ----- does not have secrets list permission on key vault" 

However It would be a great to have a API something like "az keyvault show --name {KeyVault Name} which list all the permissions given Service Principle have" . 

**Reason for raising this:**
Sometimes we are half way performing the operation and it throws an exception  For eg In Our use case if someone is not having List, Del and Purge permission on KeyVault we should not progress. But If this API is added then it will save lot of CPU cycles.

Thanks 
Asim Arora

**Comment by chlowell** [comment]
Hi @asimarora! Such an API does exist, you can call it through KeyVaultManagementClient:
```py
from azure.mgmt.keyvault import KeyVaultManagementClient

service_principal_object_id = "a GUID; the principal's object ID, not its client or application ID"
client = KeyVaultManagementClient(credential, subscription_id)
vault = client.vaults.get(resource_group_name, vault_name)
permissions = [
    policy.permissions for policy in vault.properties.access_policies if policy.object_id == service_principal_object_id
]
print(permissions[0].secrets)  # e.g. ['Get', 'List', 'Set']
```
The return type of `vaults.get()` is documented [here](https://docs.microsoft.com/python/api/azure-mgmt-keyvault/azure.mgmt.keyvault.v2019_09_01.models.vault?view=azure-python-preview).

**Comment by asimarora** [comment]
Hello @chlowell,
Thanks for inputs and fast response. **This API perfectly solve my problem.** 

But I have an input  When we are already connected to Secrets part of KeyVault via "azure.keyvault.secrets" class object then I think API should be as verbose as getPermissionList() in  azure.keyvault.secrets class ?

**Comment by mccoyp** [comment]
Hi @asimarora, thanks for making this feature request! We'll be sure to keep this in mind when moving forward.

At the moment though, there aren't any immediate plans to add permissions listing to `azure-keyvault-secrets` (or `azure-keyvault-keys` and `azure-keyvault-certificates`). There are a couple of reasons for this -- some based on design and some based on functionality:
 - From a design perspective: the management package ([`azure-mgmt-keyvault`](https://docs.microsoft.com/python/api/azure-mgmt-keyvault/azure.mgmt.keyvault?view=azure-python)) is intended to be used for managing Key Vault resources like vaults. Managing the access policies for a vault falls into this category of behavior, which is why permissions APIs live there.
 - From a functionality perspective: it could be argued that listing permissions doesn't necessarily mean managing them, but it's also not very helpful to list permissions if you can't change them (which would require other APIs, and administrator privileges). Also, it's currently possible to see which permissions you _don't_ have when an operation fails -- so if you'd prefer to only use the secrets package, I would recommend following a try/except pattern.
