### ISSUE TITLE
Stop method to deallocate the VM lead to unnecessary billing of resources

### ISSUE THREAD

**Issue by smoolya17** [Azure/azure-sdk-for-python#17619]
- **Package Name**: azure-mgmt-compute
- **Operating System**:CentOS7
- **Python Version**: 3.6.8

**Describe the bug**
We use rundeck to start/deallocate the VM's daily. We tried the `client.stop()` method to deallocate the VM's, owing to the confusion that the Virtual Machine only shut downs the virtual machine and doesn't deallocate the resources. Howeved the Azure Console page `Stop` command deallocates the resources. Can the `client.stop()` be changed to `client.shutdown()` as this has lead our team to cause unnecessary storage & network billing charges to our customers?

**Comment by Drewm3** [comment]
@jaylabell, could you provide guidance on what is the correct function to use to get the stop-deallocate behavior in the Python SDK?

@smoolya17, generally we do not want to change the behavior of a function once it has been released. In this case it is arguable that the stop action maybe should have been mapped to deallocate when the SDK was created, but for whatever reason it was not. Once the SDK has shipped with this behavior we generally do not change it because it would be a breaking change for customers who may have came to rely on the behavior. For example, in the Azure Portal Stop was originally mapped to the same stop-allocated on VMs. We did not change this behavior in the portal until we had a full portal rewrite so that we didn't break customer expectations.

**Comment by smoolya17** [comment]
@Dream3 i am closing this issue as this function `client.stop()` was a wrapper that I used above `client.power_off()` which led to unnecessary billing to the customers.

If someone from the team could atleast mention in the docstring about the impact the function has on the resources, as in this case, power off does not deallocate the storage and network resources
