### ISSUE TITLE
Implement ExternalBearerTokenCredentialPolicy in azure-mgmt-core 

### ISSUE THREAD

**Issue by jsntcy** [Azure/azure-sdk-for-python#17764]
**Is your feature request related to a problem? Please describe.**
Customer wants to work around #8313 by adding a new custom policy called ExternalBearerTokenCredentialPolicy, but find it difficult.

**Describe the solution you'd like**
#16519

**Describe alternatives you've considered**

**Additional context**

**Comment by jiasli** [comment]
It is not easy to use this policy with Azure CLI `dev` branch because `dev` branch uses `external_tenant_token_retriever` to retrieve tokens for external tenants:

https://github.com/Azure/azure-cli/blob/039fa21db4fdf6dfb22958aaf1c3f614e1fc3b59/src/azure-cli-core/azure/cli/core/adal_authentication.py#L22

```py
    def __init__(self, token_retriever, external_tenant_token_retriever=None):
```

Adopting this Track 2-compatible policy would require an overhaul of `azure-cli-core` to switch from `external_tenant_token_retriever` to **external credentials**. I prefer not to use this policy for Azure CLI `dev`, as this will be throw-away code.
