### ISSUE TITLE
Can't pass `force_refresh` through `get_token` to MSAL's `acquire_token_silent_with_error`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-sdk-for-python#17825]
## Symptom

Due to the removal of `kwargs` when calling `acquire_token_silent_with_error` (https://github.com/Azure/azure-sdk-for-python/pull/16323#discussion_r566565254), it is now impossible to pass `force_refresh` through `get_token` to MSAL's `acquire_token_silent_with_error`.

## Impact

- This makes the proposed solution for CAE of using `force_refresh=True` or `exclude=old_at` impossible (https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/335#issuecomment-812283683).

- This makes `az account get-access-token --force-refresh` impossible (https://github.com/Azure/azure-cli/issues/17578).

**Comment by chlowell** [comment]
I'm closing this because we don't support passing arguments to MSAL, and this particular scenario is moot because the proposed solution wasn't implemented. More generally, we haven't added a `force_refresh` argument to `get_token` because we can't promise a new token. For example, managed identity endpoints typically maintain a token cache but not all endpoints provide a way to bypass that cache.
