### ISSUE TITLE
I can't use python sdk for chinese azure

### ISSUE THREAD

**Issue by LeiyuanBlog** [Azure/azure-sdk-for-python#17936]
soure code:
    AZURE_AUTH = settings.AZURE_AUTH.get(area)
    tenant_id = AZURE_AUTH.get("AZURE_TENANT_ID")
    client_id = AZURE_AUTH.get("AZURE_CLIENT_ID")
    client_secret = AZURE_AUTH.get("AZURE_CLIENT_SECRET")
    credential = ClientSecretCredential(tenant_id=tenant_id, client_id=client_id, client_secret=client_secret)
    nsg_client = NetworkManagementClient(credential, self.subscription_id, base_url=auth.AZURE_ENDPOINT)
    nsg = nsg_client.network_security_groups.list_all()

error logs:
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS500011: The resource principal named https://management.azure.com was not found in the tenant named {***********}. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by chlowell** [comment]
Both the credential and the client need configuration for Azure China because they default to Azure Public Cloud. The credential needs the authority; the client needs the scope of authentication in addition to a base URL. For example, adding to your code:

```py
from azure.identity import AzureAuthorityHosts

credential = ClientSecretCredential(
    tenant_id=tenant_id,
    client_id=client_id,
    client_secret=client_secret,
    authority=AzureAuthorityHosts.AZURE_CHINA
)
nsg_client = NetworkManagementClient(
    credential,
    self.subscription_id,
    base_url=auth.AZURE_ENDPOINT,  # should be https://management.core.chinacloudapi.cn/
    credential_scopes=["https://management.core.chinacloudapi.cn//.default"],
)
```

[This document](https://docs.microsoft.com/azure/developer/python/azure-sdk-sovereign-domain#using-pre-defined-sovereign-cloud-constants) gives some more detail and demonstrates using constants from the `msrestazure` package, which you may not have installed. If you have the Azure CLI installed, `az cloud show -n AzureChinaCloud` provides this information as well.
