### ISSUE TITLE
[ServiceBus] the constraint relationship between absolutely expiry time and time to live property on outgoing message

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#17970]
Problem:
- According to comment in JS's PR: https://github.com/Azure/azure-sdk-for-js/pull/14786#discussion_r610181135
the absolute_expiry_time on uamqp.message.MessageProperties should be calculated based on time_to_live on uamqp.message.MessageHeader:
![image](https://user-images.githubusercontent.com/47871814/114379693-f58e8300-9b3d-11eb-8ae2-0cddb31f65fb.png)

Reason:
- This is a service bus spec, not an amqp spec
  - Harsha mentioned that "service-bus service has a bug that required us to add this"

Todo:
- check with josh/harsha, cross-language consensus on this custom logic
- discuss and conclude on how to deal with it when we're sending AmqpAnnotatedMessage
  - should be we override the absolute_expiry_time/time_to_live? --> yes, it should be dealt with the same way the ServiceBusMessage deals with them (according to discussion with Josh/Harsha)
- Apply the custom logic to outgoing ServiceBusMessage if needed
- Apply the custom logic to outgoing AMQPAnnotatedMessage if needed
- code impacted:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py#L273-L283

as users set the `time_to_live`, we need to update the `absolute_expiry_time` of the MessageProperties of the internal amqp message `ServiceBusReceivedMessage.message`

**Comment by swathipil** [comment]
Multiple options to add this logic:
1) right before sending the uamqp object [here](https://github.com/Azure/azure-sdk-for-python/blob/3fac772039bf61f785c22202bacef6eb26f09a8f/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py#L253).
2) In some separate method like `calculate_absolute_expiry_time_using_ttl` right before this [line](https://github.com/Azure/azure-sdk-for-python/blob/3fac772039bf61f785c22202bacef6eb26f09a8f/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py#L97) and [this line](https://github.com/Azure/azure-sdk-for-python/blob/3fac772039bf61f785c22202bacef6eb26f09a8f/sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py#L390).
3) Inside the `transform_messages_to_sendable_if_needed` method, call a separate `calculate_absolute_expiry_time_using_ttl` [here](https://github.com/Azure/azure-sdk-for-python/blob/3fac772039bf61f785c22202bacef6eb26f09a8f/sdk/servicebus/azure-servicebus/azure/servicebus/_common/utils.py#L197).

Chosen: 2 - It separates the new logic from the existing code which is preferable because we don't want to create problems in existing code.

**Comment by swathipil** [comment]
MAX_DURATION_VALUE constant added, set from here: https://github.com/Azure/azure-sdk-for-js/blob/887eb013a7c9278b7eedb2c04c5e1bac0b984ebe/sdk/core/core-amqp/src/util/constants.ts
