### ISSUE TITLE
Planning and Roadmap Feedback - Second Half 2021

### ISSUE THREAD

**Issue by maggiepint** [Azure/azure-sdk-for-python#18182]
Hello Azure SDK community!

The Azure SDK team is beginning our next planning cycle as part of Azure's twice a year planning process. As a part of this effort, we want to hear from you about what new features and services you are most interested in having as part of the New SDK. In general, we can separate requests into two categories: 

1. Feature requests for various aspects of the SDK
2. Requests to move Azure services onto the new SDK paradigm

We would love to hear your thoughts on both!

There are three ways you can contribute feedback:

1. Browse existing issues labeled `feature-request` in [this repository](https://github.com/Azure/azure-sdk-for-python/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request). Use the thumbs up (+1) emoji to give us your indication it's a high priority for you. 
2. Reply to this issue with comments on new services and features you are looking for. 
3. Upvote comments in this thread using the thumbs up (+1) emoji.

Note: Being specific with your use case and sample code. The more information you can give us, the more likely we are to take your request.

## Please do not create new issues for new service requests - instead, reply inline.

We will be reviewing community feedback and incorporating it into the planning process starting May 10th 2021.

**Comment by sergey-ivanchuk** [comment]
Hi Azure team,

This looks like the right place to request a feature for consideration. 

For future releases, I'd like to see the return of an old, deprecated feature in the Azure Python SDK.

It would be great to use `azureml.pipeline.steps.python_script_step. PythonScriptStep(hash_paths= ...) ` . This parameter was depreciated a long time ago, but I feel it would benefit the Azure SDK user community.

Below is a use case I have, and a use case that's fairly practical for certain situations.

```bash
.
├── pipeline
│   ├── aml_process.py  # GOAL 2 -use  PythonScriptStep (allow_reuse=True , source_directory='./../',  script_name='./pipeline/step_1/math_check.py', hash_paths = './pipeline/step_1' …,… )
│   ├── step_1
│   │   └── math_check.py     # GOAL 1A - import from src/math.py & src/helper.py at runtime
│   └── step_2 
│       └── calculation.py.   # GOAL 1B - import from src/helper.py at runtime
├── requirements.txt
└── src
    ├── helper.py
    └── math.py
```

From my two goals above, I have them within a repository with source and pipeline code to run.

For goal 1 , I want to import`src` code. So, I need to make `source_directory='./../'` in the `PythonScriptStep` function

For goal 2, I want to use `allow_reuse=True` and `hash_paths = './pipeline/step_1'` so that I can do hashing on multiple sub-steps in a pipeline (e.g. use case where I need to _re-run_ `step_2` but still _re-use_ `step_1`).

 In reality, I might have 6 sub-steps in a repository. So, the value of `hash_paths` goes up greatly. Only re-running 1-of-6 steps is much better than re-running 6-of-6

thank you for taking this into consideration. I can elaborate on any follow up questions.

**Comment by sergey-ivanchuk** [comment]
@maggiepint , I wanted to check if there's any update on this thread? Seems that May 10th was the start of various sprint planning goals, so I'm curious if my proposal was taken into consideration.

**Comment by sergey-ivanchuk** [comment]
FWIW, I'd still like to see `azureml.pipeline.steps.python_script_step.PythonScriptStep(hash_paths= ...)` reintroduced as an argument
