### ISSUE TITLE
[AzureML] ParallelRunStep multiple outputs

### ISSUE THREAD

**Issue by emepetres** [Azure/azure-sdk-for-python#18440]
**Is your feature request related to a problem? Please describe.**
I have a batch inference pipeline of a model that outputs more than one output. I'd like `ParallelRunStep` could allow multiple outputs in the same way as `PythonScriptStep`.

**Describe the solution you'd like**
I want to define the output parameter of ParallelRunStep constructor as a list of PipelineData or OutputPortBinding instead of a single element.

**Describe alternatives you've considered**
Currently I have an output with subfolders. This is inefficient as I have to pass the whole output to next steps, that only use a part of it.

**Comment by shivanissambare** [comment]
@tracychms  can you please help with this issue, thank you :)

**Comment by tracychms** [comment]
Thanks for the feedback.
Could you please clarify how you want multiple outputs? Are you looking for one scoring script run() produces one output (one PipelineData or OutputPortBinding), and only one output will be used in the next step (either ParallelRunStep or other type of step)?

**Comment by emepetres** [comment]
What I'm looking for is to have a ParallelRunStep that produces two outputs (two PipelineData for example), so they can be consumed separatelly by two PythonScriptStep. Each PythonScriptStep would take only one previous output as input:
![parallel_outputs](https://user-images.githubusercontent.com/1446793/117037461-c7e4c600-ad06-11eb-99a2-74680cf650e8.png)

**Comment by tracychms** [comment]
Thanks for the clarification. 

Currently, ParallelRunStep cannot produce multiple outputs (OutputFileDatasetConfig or PipelineData) the same way as PythonScriptStep due to the difference of execution mode. PythonScriptStep executes on a single compute node, and ParallelRunStep distributes the workload across a compute cluster and executes multiple tasks (mini batches) in parallel. The results from each task (executed on different nodes) will then be combined into one output (one PipelineData or OutputDataset object).

As what you described above, one entry script produces two types of outputs (fgr & pha), the expectation is all fgr from N tasks (mini batches) will be combined into one final output (one PipelineData or OutputDataset object), and the same for pha.

**Comment by shivanissambare** [comment]
closing this issue, please reopen if you have more questions!
