### ISSUE TITLE
Single-version API clients are potentially not forward-compatible

### ISSUE THREAD

**Issue by nitzmahone** [Azure/azure-sdk-for-python#1851]
I keep forgetting to ask about this: single-version API clients are not being generated with the same patterns as multi-version APIs. The most notable omissions are the `api_version` and `profile` args on the main client `__init__`; this prevents the current API version from being "pinned" by a caller, so a future SDK upgrade that adds a new (potentially incompatible) version could break it. They're also missing the `models` static property on the main client class, and the `api_version` property on the operations classes. These omissions prevent the use of the same dynamic patterns used on a multi-version client, and can potentially introduce breaking changes when a new API version is eventually introduced to that resource type, as the caller is required to "float" its version to the latest. Since the SDK objects for single-version clients aren't generated with versioned namespaces, it's not even possible to pin them statically...

eg, ComputeManagementClient has multiple versions, where ContainerInstanceManagementClient only has one; note the significant differences required in the way they'd be used in a version-pinned fashion.

Was this an oversight, or is there a reason not to follow the multi-version pattern on all clients/models?

**Comment by lmazuel** [comment]
Linking this PR https://github.com/ansible/ansible/pull/35538 (copy/pasting my answer I put there here)

@nitzmahone Indeed, there is two types of packages:
1- Multi-api packages. Currently there is 5: storage, network, compute, resource, containerregistry. These packages have:
    - A `models` method on the client, that takes an ApiVersion as parameter
    - An `api_version` parameter in `__init__`
    - A `profile` parameter in `__init__`
2- Single-version package, that have no `models`, no `api_version`, no `profile`.

All of them should have a `models` attribute in operation groups.

Then you should:
- Check for `models` in the client to determine if the package is ready for multi-api. No need for inspect. You can also check if `DEFAULT_API_VERSION` or `DEFAULT_PROFILE`  is in the client.
- Always use `models` on the operation group directly. Since this will stay the same once/if the package goes to multi-api one day.

In real life, packages released since two months have the `models` on the operation group, but not the older. I would suggest that you tell me "I need package XXXX with `models` on operation group" if you integrate faster than I release. So I release a bugfix version adding that, to simplify your life.
Same for multi-api, I think resource and containerregistry doesn't have profile yet, but the new resource is planned for today, and I can release containerregistry with `profile`. So you can simplify your factory.

Thoughts?

**Comment by nitzmahone** [comment]
(response on https://github.com/ansible/ansible/pull/35538#issuecomment-362106392) - we should probably have further discussion here though so the thoughts aren't lost in a random Ansible PR ;)

**Comment by lmazuel** [comment]
I think we solved this, let me know and please remind me what I forget otherwise :)
Thanks!
