### ISSUE TITLE
Can't Kill Process when using InteractiveBrowserCredential

### ISSUE THREAD

**Issue by jobala** [Azure/azure-sdk-for-python#18533]
- **Package Name**: 
Azure Identity

- **Package Version**: 
1.4.0b7

- **Operating System**:
Windows

- **Python Version**: 
3.8

**Describe the bug**
When signing a user interactively and then the user presses Ctrl+C to kill the process. The process won't exit until after it receives a response from the browser.

**To Reproduce**
1. Sign in a user with InteractiveBrowserCredential
2. Once the browser is open, click Ctrl+C to exit the process
3. Observe that you can't exit

**Expected behavior**
I expect the process to exit.

**Screenshots**
N/A

**Additional context**
Clicking Ctrl+C exits the process successfully in MacOS.

**Comment by seankane-msft** [comment]
@jobala thank you for reporting the issue, we will investigate asap!

**Comment by chlowell** [comment]
During an interactive login the credential blocks to wait for an HTTP request. It won't wait forever--it respects a configurable timeout which defaults to 5 minutes--but it does feel like forever. Due to some quirk of Python on Windows, or just Windows' signal handling, Ctrl+C doesn't break this wait. Ctrl+Break does, however, so you can use that as a workaround. Does that unblock you?

**Comment by chlowell** [comment]
Great, I'll close this then. Thanks for raising the issue.
