### ISSUE TITLE
Large partition key has been enabled

### ISSUE THREAD

**Issue by Juggernaut1997** [Azure/azure-sdk-for-python#18637]
- **Package Name**: azure-cosmos-sdk-for-python
- **Package Version**: latest
- **Operating System**: Windows
- **Python Version**: 3.8

The bug is related to partition key addition while creating the container. When we use cosmos_client.create_container(id, partition_key=PartitionKey(path="/fieldName")), it will create the container but will set the large partition key enabled which creates issue while adding data to this created container. On console, we set the large partition key in the Advanced section. To confirm, if the large partition is enabled for the container, i went to Scale & Settings of the container then in the Settings at the bottom it says and I quote, "Larger partition key has been enabled"

**Comment by zfoster** [comment]
Hey @Juggernaut1997, can you elaborate on what issues it causes adding data to the created container? As far as I know this is expected behavior, new SDKs create collections with v2 partition keys which are the larger partition keys

**Comment by Juggernaut1997** [comment]
Hey @zfoster, keeping aside the second issue i.e. insertion of data. We have to focus on the first issue which is when we create a container from the SDK or the REST API (Management Plane), it keeps the large partition key enable by default. Is that done purposely? if not can you suggest how to overcome this.

Now coming to the second issue, when we are trying to push a data with around 0.4 million records it only writes about 20-30 records. So we cross checked the scenarios by creating containers from the console with no large partition key enabled and with large partition key enabled. But from console too SDK showed the same behavior, if enabled it just writes 20-30 rows and on the other side if disabled it writes all the records.

Can you help us out with this?

**Comment by zfoster** [comment]
1) Yes this is done on purpose, those large partition keys are v2 partition keys which are the default for all new containers.

2) This sounds like rate limiting. You're trying to bulk import data then? As far as I know python doesn't have a very good solution yet for that. I can try to find a sample or a workaround so that you can write more records

**Comment by Juggernaut1997** [comment]
@zfoster That sounds great Z! But for now I am using Spark Cosmos Connector for writing, which is working great for me but still if you could able to find something which will help writing bulk data using python that will be helpful. 

And do you happen to know why the writing is creating an issue for large partitions? I will be greatful if you could help me resolve the write to a container with large partition. 

Thanks in advance! Will be waiting for the resolution!

**Comment by Juggernaut1997** [comment]
@zfoster 

Spark Connector Version: com.databricks.training:databricks-cosmosdb-spark2.2.0-scala2.11:1.0.0
```
self.writeConfig = {
        "Endpoint": connection_uri,
        "Masterkey": connection_key,
        "Database": env_dict['cache_db_name'],
        "Collection": dataset_name,
        "Upsert": "true"
}

dataframe.write.mode("overwrite").format("com.microsoft.azure.cosmosdb.spark").options(**self.writeConfig).save()
```

- **dataframe** : a spark dataframe

When I try to use the code, it will only write just 20-30 records from around 400k records. 

Will this be enough, because I can't provide the sample code as of now.

**Comment by southpolesteve** [comment]
@Juggernaut1997 Can you refile this issue with the spark connector? https://github.com/Azure/azure-cosmosdb-spark It sounds like they are the best team to investigate if that project is what you are using to write the data. They will also likely need a more thorough sample that reproduces the issue

As @zfoster mentioned there should be no performance difference between v1 and v2 partitioning. All the latest SDKs use v2 partitioning when creating collections and this is by design.
