### ISSUE TITLE
Ability to create cosmos container with auto RU configured

### ISSUE THREAD

**Issue by bekraupov** [Azure/azure-sdk-for-python#18860]
**Is your feature request related to a problem? Please describe.**
Atm we can use database.create_container method and create manual RU, it woudl be great if python can support ability to switch to Auto RU when we create it. I know powershell supports it so it is feasible

**Describe the solution you'd like**
Ability to updtae auto ru container offer

**Describe alternatives you've considered**
we could go back to using powershell

**Additional context**

**Comment by swathipil** [comment]
@Rodrigossz Thanks for your feedback! Routing this to the right people.

**Comment by Rodrigossz** [comment]
This is a control plane capability, not present in the SDK by design. 

Use the Azure portal, Azure Resource Manager template, CLI or PowerShell to enable autoscale on an existing database or container. You can switch between autoscale and standard (manual) provisioned throughput at any time. See this [documentation ](https://docs.microsoft.com/azure/cosmos-db/provision-throughput-autoscale#enable-autoscale-on-existing-resources)for more information.
