### ISSUE TITLE
Do we have API to check azure marketplace image support accelerated network or not?

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-sdk-for-python#18899]
https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#enable-accelerated-networking-on-existing-vms

**Comment by LiliDeng** [comment]
Found it under VirtualMachineImageFeature, thanks.

**Comment by LiliDeng** [comment]
I use below way to check whether the image support SRIOV or not by below code, but found some images which support SRIOV don't have features property, is the raw data's issue or API issue?

![image](https://user-images.githubusercontent.com/10083705/120434404-070e4180-c3af-11eb-8965-f79636fa2f9a.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by amjads1** [comment]
Looking into the issue

**Comment by amjads1** [comment]
@LiliDeng  - Currently for accelerated network, it's not a mandatory field inside image features list. If the publisher don't specify any feature about it then it won't show up in the image features list. You can treat such cases with a default value as 'false'.

If you can get accelerated network feature from the image features list and its value = true, means the acceleration network is enabled otherwise it considered as disabled. It should be raw data issue but if you have any further questions, feel free to provide your publisher offer sku and version and we can look into it. Hope this helps.

**Comment by amjads1** [comment]
@LiliDeng - Let us know if you need any further help or information on this question.

**Comment by LiliDeng** [comment]
Thanks for your time. @amjads1

**Comment by amjads1** [comment]
Closing this item as we haven't heard back from the requestor. Feel free to re-open the issue if any further help is needed.

**Comment by amjads1** [comment]
Thanks for closing @LiliDeng!
