### ISSUE TITLE
Get Searchable PDF from Computer Vision READ API

### ISSUE THREAD

**Issue by mananshah1403** [Azure/azure-sdk-for-python#19085]
**Is your feature request related to a problem? Please describe.**
The issue is, I have a PDF document that I can send to the READ API to get OCR results, although I am trying to find a way to impose that text on pdf, so it can searchable

**Describe the solution you'd like**
READ API outputs a searchable pdf along with the results

**Describe alternatives you've considered**
A 3rd party library that will allow drawing invisible text on pdf

**Comment by annatisch** [comment]
Thanks for your question @mananshah1403 
To make sure I route your request to the right team for advice, could you give me a few more details about the service endpoint that you've been working with?
It sounds like you've been working directly with the REST API rather than one of the SDKs - is that the case?
Would you be able to link me to the API or SDK you've working with so far?

**Comment by mananshah1403** [comment]
Thanks for the response @annatisch. I am working with the python package for computer vision. Here is the link
https://pypi.org/project/azure-cognitiveservices-vision-computervision/. Let me know if you need any further information.

**Comment by annatisch** [comment]
Thanks @mananshah1403!
I think the service team would hopefully be able to provide some details - adding @TFR258 and @ryogok  - can you give us your thoughts on this scenario?
