### ISSUE TITLE
Customizable cache persistence for ManagedIdentityCredential

### ISSUE THREAD

**Issue by Yoni-Mantzur** [Azure/azure-sdk-for-python#19125]
- **Package Name**: 
azure-identity
- **Package Version**: 
1.6.0
- **Operating System**:
linux
- **Python Version**: 
3.7.10

**Describe the bug**
`_cache` parameter name in `ManagedIdentityCredential` changed from `cahce` in version 1.5.0 to `_cache` in 1.6.0.
This is a breaking change unless you recommend another way to send specific `TokenCache`

**To Reproduce**
1.  run
```
from azure.identity import ManagedIdentityCredential
from msal import TokenCache

cache = TokenCache()
cred = ManagedIdentityCredential(cache=cache)

id(cache) != id(cred._credential._client._cache)
```

**Expected behavior**
`ManagedIdentityCredential` should work with the `cache` argument. 
```
id(cache) == id(cred._credential._client._cache)
```

**Comment by yunhaoling** [comment]
@Yoni-Mantzur thanks for reaching out!
Looping in @chlowell to have a look.

**Comment by chlowell** [comment]
I'm sorry to have broken your code. The background here is that an internal class used the "cache" argument to simplify unit testing. The argument was therefore not documented and in fact didn't even work consistently. I replaced this internal class in 1.6.0 with another that uses "_cache" for the same purpose. I added the underscore to clarify for anyone who discovered the still undocumented argument that it isn't part of the public API. So my first question is, how did you learn about this argument?

To the larger issue, ManagedIdentityCredential doesn't have a cache configuration API because we haven't seen a compelling use for one. Why do you want to control the credential's cache?

**Comment by Yoni-Mantzur** [comment]
Thanks, @chlowell  for the quick response.

I learned about this use by understanding from the code that `ManagedIdentityCredential ` indeed using msal token cache.
Maybe it was my mistake to think as it was public indeed.

As for the caching, as you can see [here](https://msal-python.readthedocs.io/en/latest/#msal.SerializableTokenCache), there are suggestions on how to extend the cache and this is our use here.

Can you suggest other ways how to control the token cache when we're using `ManagedIdentityCredential` or maybe to use another client?

**Comment by chlowell** [comment]
There's no public API for controlling or configuring ManagedIdentityCredential's cache. Each credential instance uses its own in-memory cache instance. We could add API for that but as I wrote above, we haven't seen a need for it. Why are token caching details important in your application? For example, do you share a cache between credential instances to improve performance or synchronization?

**Comment by Yoni-Mantzur** [comment]
Exactly. Notice that `msal:ClientApplication` gets token cache in its API, hence, the same cache could use several token providers

**Comment by chlowell** [comment]
Can you give some more detail about why it's important for your application to share a cache instance among ManagedIdentityCredential instances? When this came up in the past, the solution was always to share a credential instance among clients. Does your application really need to control the cache?

**Comment by Yoni-Mantzur** [comment]
But what if we want to use another token cache object. For example, `SerializableTokenCache` as msal suggested?

**Comment by chlowell** [comment]
Why would you want to do that?

**Comment by Yoni-Mantzur** [comment]
Our application stack is using k8s. When the container is down, we still can use the token cache from the pod tmpfs. Hence we need to serialize the cache to the file system, and msal gives a nice extension for that.

**Comment by chlowell** [comment]
And the container that may be down is one of pod identity's containers, i.e. you're trying to make your application resilient when it's impossible to acquire tokens because the managed identity endpoint is unavailable?

**Comment by Yoni-Mantzur** [comment]
You are right! But also this way you are avoiding requesting a new token from the endpoint when you do not really need to since the token was not expired. But yes, the first reason is the main motivation

**Comment by chlowell** [comment]
> this way you are avoiding requesting a new token from the endpoint when you do not really need to since the token was not expired

ManagedIdentityCredential already does this, it maintains an in-memory cache and requests a token only when that cache doesn't contain a valid one. You can share a cache between clients by sharing a credential instance, e.g.
```py
credential = ManagedIdentityCredential()

# these clients share an in-memory token cache
key_client = KeyClient(VAULT_URL, credential)
resource_client = ResourceManagementClient(credential, SUBSCRIPTION_ID)
```

Given that, does your application really need to maintain its own cache on disk?

**Comment by Yoni-Mantzur** [comment]
Yes, since the cache in memory option doesn't cover the case when the container is down.

**Comment by Yoni-Mantzur** [comment]
@chlowell since I don't see any alternative, can we make the issue a feature request - meaning we would like to control ManagedIdentityCredential's cache, is it doable?

**Comment by chlowell** [comment]
Sure, this is a feature request, I'll tag it as such. I don't know whether it's doable. The simplest implementation, ManagedIdentityCredential taking an `msal.TokenCache` instance at construction, creates too much compatibility risk, so we would need something else. We already have a [cache configuration API](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/1.6.0/azure.identity.html#azure.identity.TokenCachePersistenceOptions) for user credentials. We could in principle add that to ManagedIdentityCredential but it doesn't allow the level of control you want and wouldn't work on all platforms. While designing that API we chose not to allow more control because we didn't see a need for it and in general want the cache to be an internal implementation detail.

That's the context behind me trying to understand your scenario. I still don't see the motivation for implementing your own cache persistence. Let me summarize my understanding. You seem concerned about two things:

1. Your application may not be able to acquire a token because the token endpoint is unreachable

I believe ManagedIdentityCredential already handles this internally. It's safe to share one credential instance with many clients and if you do that, they will all share the same in-memory cache and have access to every token your application acquires.

2. Your application must acquire a token every time it (re)starts

Naively, this seems like a problem only for the sort of high performance application we don't typically build with Python. Does your application (re)start very frequently? Is its performance so critical that it's worth building another caching layer to avoid an extra token request?

Perhaps you're also concerned about 1 and 2 occurring simultaneously--has that happened often enough to warrant implementing your own cache? Are there more concerns I'm missing? Please forgive me for asking so many perhaps obvious questions, you're the first person to ask for this feature and we (Azure SDK team) need to understand it before trying to design an API for it.
