### ISSUE TITLE
azure-storage-queue can't connect to Azurite if url doesn't start with 127.0.0.1 or localhost

### ISSUE THREAD

**Issue by JoaquinLeonArg** [Azure/azure-sdk-for-python#19202]
- **Package Name**: azure-storage-queue
- **Package Version**: 12.1.6
- **Operating System**: Ubuntu 21.04
- **Python Version**: 3.8

**Describe the bug**
When connecting to a local Azurite instance (through 127.0.0.1 or localhost), everything works. However, if the azurite url does not start with 127.0.0.1 nor localhost (for example, if trying to connect between Docker containers using the container name) it fails with a `ValueError("Unable to determine account name for shared key credential.")`.

I've found that in the `azure/storage/queue/_shared/base_client.py`, there is a special case only for urls starting with 127.0.0.1 or localhost, so I suspect that might be causing the issue:

```
if not self.account_name and parsed_url.netloc.startswith("localhost") or parsed_url.netloc.startswith("127.0.0.1"):
        self.account_name = parsed_url.path.strip("/")
```

**To Reproduce**

Try to connect to an Azurite instance with the following code:

```
queue_client = QueueClient.from_queue_url(
        f'http://azurite:10001/devstoreaccount1/my_queue',
        'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
    )
```

**Expected behavior**
The connection should be created and I should be able to connect to the queue.

**Comment by yunhaoling** [comment]
hey @JoaquinLeonArg , thanks for your feedback, we'll investigate ASAP.
adding @xiafu-msft to take a look.

**Comment by amishra-dev** [comment]
@tasherif-msft / @xiafu-msft fyi

**Comment by tasherif-msft** [comment]
Hi @JoaquinLeonArg, thank you for reporting this, I will investigate this issue and get back to you!

**Comment by navba-MSFT** [comment]
@JoaquinLeonArg Apologies for the late reply. We will update this thread once we have more details on this.

@tasherif-msft @xiafu-msft Could you please provide an update on this request ? Awaiting your reply.

**Comment by vincenttran-msft** [comment]
Hi @JoaquinLeonArg Joaquín, I just wanted to touch base with you to see if this has not been resolved yet? I do see that the issue may lie our parsing so that may require further investigation and we will get back to you if there are any updates. In the meantime, perhaps this work-around would help to unblock your workflow:

`from_queue_url` accepts a `credential parameter as seen [here](https://github.com/Azure/azure-sdk-for-python/blob/45415de1853cade48006c25e3fa2083ef40a854d/sdk/storage/azure-storage-queue/azure/storage/queue/_queue_client.py#L133). With that being said, you can alternatively provide the credentials directly in a dictionary format.

The format of this dictionary should be the following:
`cred_dict = {"account_name": <ACCOUNT_NAME>, "account_key": <ACCOUNT_KEY>}`
Then ensure you are passing this in as the `credential=` param for your call to the `from_queue_url` API.

Please give that a try if your problem is still persisting and hopefully that should do the trick!
Thanks!
