### ISSUE TITLE
ImportError: cannot import name KeyVaultClient

### ISSUE THREAD

**Issue by Dave-0-0** [Azure/azure-sdk-for-python#19245]
azure-keyvault              
4.1.0
Ubuntu Linux
2.7

**Describe the bug**
Attempt to utilize the library to create a KeyVaultClient. Python claims it does not exist, despite the package being installed. 

**To Reproduce**
1. Try to import KeyVaultClient 
2. from azure.keyvault import KeyVaultClient

**Expected behavior**
Successfully import KeyVaultClient
![2021-06-14_11-18-19](https://user-images.githubusercontent.com/51136463/121926076-30aa5f80-cd03-11eb-9b5b-a198e9d5fee4.jpg)

**Screenshots**

**Additional context**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by mccoyp** [comment]
Hello @Dave-0-0 , thanks for opening an issue! This is happening because you seem to have [azure-keyvault 4.1.0](https://pypi.org/project/azure-keyvault/) installed -- that version doesn't actually contain any code, but installs `azure-keyvault-certificates`, `azure-keyvault-keys`, and `azure-keyvault-secrets` for you. The last version of `azure-keyvault` with a functioning KeyVaultClient is [version 1.1.0](https://pypi.org/project/azure-keyvault/1.1.0/).

If you don't have a specific need for `azure-keyvault`, I would recommend using the new `azure-keyvault-*` packages if you're able -- those are where we're actively developing. In either case, I hope this unblocks you!

**Comment by Dave-0-0** [comment]
Thank you. I will look into that.
