### ISSUE TITLE
Getting error PrincipalNotFound while create AKS cluster with python sdk

### ISSUE THREAD

**Issue by skrish24** [Azure/azure-sdk-for-python#19397]
'Azure Error: PrincipalNotFound\\\\nMessage: Principal xxxxxxxxxx does not exist in the directory 4dederer-ssdsds-xxdsdsd.\\\\n'

They are using the following code block for the rold assignment:
role_assignment = authorization_client.role_assignments.create( resource_group_id, uuid.uuid4(), # Role assignment random name { 'role_definition_id': owner_role.id, 'principal_id': principle_id } )

This happens intermittently and let us know if there is any fix or suggestion to make this work consistently

**Comment by chlowell** [comment]
That error indicates the given principal ID doesn't exist in the Azure AD tenant. Where do you get the value of `principle_id`?

**Comment by ubsujit** [comment]
Hi @chlowell ,

The principle Id is nothing but object ID. This gets created automatically when we enable system assigned identity to vm.

Reagrds,
Sujit

**Comment by skrish24** [comment]
hello @chlowell is there any way we can make sure that the object id exists before moving to assign it. This code works most of the time however sometimes it gives error Pricipal id not found, may be a race condition?

**Comment by chlowell** [comment]
I suppose there could be a delay between requesting a system assigned identity and that identity being available. I don't understand your scenario if that's what's happening though, because to my knowledge AKS managed identity supports only user assigned identities and service principals (see e.g. [AKS docs](https://docs.microsoft.com/azure/aks/use-managed-identity)).

To answer your question, I think you could use the Graph API to check whether a principal exists. That's how the CLI does it for "az ad sp show" anyway. But mixing in Graph seems unnecessarily complex to me. If you know the principal has been created, could you handle the error by waiting a few seconds and retrying the role assignment?
