### ISSUE TITLE
[BUG] API reference docs not showing up for Farm Beats

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-python#19409]
Go to https://docs.microsoft.com/python/api and search for "farm" in the search box. There are 0 results. We should have seen results corresponding to the API reference docs for https://pypi.org/project/azure-agrifood-farming/

cc @RGKarthik

**Comment by iscai-msft** [comment]
I did a quick little look and I found the readme in [docs.microsoft.com](https://docs.microsoft.com/en-us/python/api/overview/azure/agrifood-farming-readme?view=azure-python-preview), but couldn't find the classes + client documentation. @scbedd this package was released around 2 weeks ago, do we have to wait longer for it to show up on docs.microsoft.com? thanks!

**Comment by scbedd** [comment]
No more waiting @iscai-msft, there is definitely something up here.

1. Manually fixed this in [this commit](https://github.com/MicrosoftDocs/azure-docs-sdk-python/commit/bd00a6bba73e637b4df9461dcd7178f5975cf940). I'll get these live probably tonight. (just waiting for CI to generate for these two new packages).
2. This issue is remaining open until I track down the bug that is causing these updates not to take place. Release for both `agrifood` packages reflects output I expect, but those changes don't look like they ended up in `main`.

**Comment by scbedd** [comment]
[We are merged to live](https://github.com/MicrosoftDocs/azure-docs-sdk-python/pull/1389)
[Issue covering why these didn't get automatically picked up.](https://github.com/Azure/azure-sdk-tools/issues/1744)

Closing this issue as resolved.
