### ISSUE TITLE
Deploy model on AKS ModuleNotFoundError: No module named 'main'

### ISSUE THREAD

**Issue by gison93** [Azure/azure-sdk-for-python#19493]
- **Python Version**:  3.7.6

**Describe the bug**
The deployment of a model on AKS fails with error

File "/var/azureml-server/aml_blueprint.py", line 29, in <module>
    import main
ModuleNotFoundError: No module named 'main'

**To Reproduce**
1. from the portal (or also from the cli) deploy a registered model with score.py and yaml configuration dependencies

**Expected behavior**
Successful deployment

**Additional context**
Starting from 2021/06/24 any deployment failed with tried of different models failed with the same error.

**Comment by shivanissambare** [comment]
Hi @gison93 

During which workflow you are facing this issue?
 
i.e.

![image](https://user-images.githubusercontent.com/61255242/123489474-e9f01b80-d5c6-11eb-8b24-6d62722cf1be.png)

**Deploying to web service or deploying to real time endpoint?**

option 1: deploying to real-time endpoint (preview)
![image](https://user-images.githubusercontent.com/61255242/123489557-19068d00-d5c7-11eb-85f5-5bf8b4d6f1de.png)

option 2: deploying to web-service
![image](https://user-images.githubusercontent.com/61255242/123489600-33d90180-d5c7-11eb-8ecd-4fcd003241b6.png)

**Comment by gison93** [comment]
Hi @shivanissambare, I am facing the issue deploying to web-service.

**Comment by shivanissambare** [comment]
Hi @gison93 

this issue might be because you have not configured your scoring script properly or your yaml 

can you use our [Azure Machine Learning Inference HTTP server](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-inference-server-http) and validate your scoring scripts and dependencies?

thank you!

**Comment by gison93** [comment]
@shivanissambare thank you for your suggestion. I validated the script and dependencies and they work.

I also tried to deploy again a service that I deployed successfully on 2021/06/23 and now it gives the same error.

Then I tried to deploy a score file with init and run containing just a print statement and dependencies containing only python version (3.6, 3.7, 3.8) and the error shows up again in all 3 cases.

**Comment by shivanissambare** [comment]
The no module named 'main' error occurs when the system is unable to locate the score script that is specified by the user in the container. This can happen if the score script is not properly uploaded to the container, or if there's a typo and the expected name or path to the score script is not found in the directory.

If [azure machine learning inference server](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-inference-server-http) is working fine, I'd recommend opening a support case with us, so that our css engineers can take a look and help debug.

hope this helps.

thank you!

**Comment by gison93** [comment]
Deploying the model via an Azure DevOps Pipeline I was able to get more details about the error.

By the way the score file has an if-else with different model path for Windows and Linux and there was an error in the Linux scenario, therefore debugging locally on Windows the error did not show up.

Anyway I have not yet understood why:

1. for a brief period of time a pipeline that was working before gave the same "no module named main"
2. there are not more details on the error when deploying via portal

**Comment by shivanissambare** [comment]
Hi, not sure if we can comment more on the root cause of the issue without investigating in detail. But we are working on providing more logs around "no module errors..". This might help to understand error better than today.

Can you elaborate more on not more details when deploying via portal? we provide deployment logs for web service and other endpoint details. If there's more you'd like to see, please let us know!

**Comment by gison93** [comment]
Hi @shivanissambare, sorry for the late reply! The deployment logs just show "ModuleNotFoundError: No module named 'main'" without further information on the main cause.

**Comment by shivanissambare** [comment]
thanks for clarifying! 
Yup, are working on adding more logs around module not found errors.

**Comment by shivanissambare** [comment]
#please-close

**Comment by herandy** [comment]
So what's the fix?

**Comment by joey7848** [comment]
> So what's the fix?

Is there a fix to this? We recurrently have the same issue, albeit sporadic. Sometimes it works and sometimes it doesn't with no obvious reason as to why.

**Comment by namwooo** [comment]
I, too, encounter the same error "ModuleNotFoundError: No module named 'main'" as I deploy model to AKS web service. It is occasion and irregular.

**Comment by doc** [comment]
Also seeing this error ... models that previously deployed fine now throw this issue every time

**Comment by wemoveon2** [comment]
did anyone get this fixed? I'm trying to deploy a MLFlow model locally, which I don't think requires a scoring script as shown in [the examples repo for the cli](https://github.com/Azure/azureml-examples/tree/main/cli/endpoints/online/mlflow).

Did the Azure ML CLI v1 not require a scoring script or something...?
