### ISSUE TITLE
UsernamePasswordCredential  using bad Request URL 

### ISSUE THREAD

**Issue by Nerigal** [Azure/azure-sdk-for-python#19511]
- **Package Name**:  
  azure-identity = 1.6.0
  azure-mgmt-resource = 18.0.0

- **Operating System**: Ubuntu 20.4 
- **Python Version**:  python 3.8

**Describe the bug**

For some reason that i don't know why, the url call to get the token is different from `ClientSecretCredential` to `UsernamePasswordCredential`
`ClientSecretCredential`   call a url like `https://login.microsoftonline.com/e294652g-215a-24d1-a887-xe6bd1a9367c/v2.0/.well-known/openid-configuration`
while the   `UsernamePasswordCredential`  for some unknown reason is calling h`ttps://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration`
and the authentication process end up in an error like
```
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS90002: Tenant '' not found. This may happen if there are no active subscriptions for the tenant.
```
and i have no idea how to change / override that url
does any body have an idea ?

This error not happening while authenticating with  `ClientSecretCredential` 

**To Reproduce**

```
import importlib
import azure.mgmt
import azure.identity
import azure.mgmt.resource

client_id=''
tenant_id=''
subscription_id=''
username=''
password=''

credentials = azure.identity.UsernamePasswordCredential(
client_id=client_id,
username=username,
password=password,             
tenant_id=tenant_id,   
)

map_value = "ResourceManagement"
module_name = "resource"
client_module = importlib.import_module("azure.mgmt." + module_name)
Client = getattr(client_module, "{}Client".format(map_value))

base_url='https://management.azure.com/'

client = Client(
credential=credentials,
subscription_id=subscription_id,
base_url=base_url,
)
az_conn_resouces = client
resconn = az_conn_resouces

provider_query = resconn.providers.get( resource_provider_namespace="Microsoft.Compute" )
```

**Comment by chlowell** [comment]
The key difference here is that these credentials authenticate different kinds of identities. ClientSecretCredential authenticates a service principal whereas UsernamePasswordCredential authenticates a user. The difference you point out in the URLs is the tenant. A user can authenticate in the "organizations" tenant, which with some hand-waving is an alias for that user's home tenant. UsernamePasswordCredential uses the "organizations" tenant by default; that's why `tenant_id` is optional for it, and you would pass that argument when you want to authenticate a user outside their home tenant. So to answer your question, you override the "organizations" part of the URL by passing a different value for `tenant_id`. I see in your code that you do pass this argument, so I don't expect you would see any requests to the "organizations" tenant unless you're passing "organizations" or perhaps an empty string.

Turning to the error you get, it suggests that the tenant you're authenticating in doesn't have a subscription. If that isn't the case, I imagine you aren't authenticating in the tenant you expect. Did you edit the tenant ID out of the error message, or is it actually warning you about tenant ''?

**Comment by Nerigal** [comment]
The tenant ID  does have a subscription and it is the same used with ClientSecretCredential which also require a valid tenant ID 
and if i dont pass  the tenant ID i get the error 
`azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.
Trace ID: 448aa757-91eb-49eb-bbc4-ea72ebd21600`

This error does suggest that `UsernamePasswordCredential` require a valid `tenant_id`

**Comment by Nerigal** [comment]
update with this case plz

**Comment by chlowell** [comment]
Sorry for the wait, I was on vacation. Is this "no tenant-identifying information found" error from UsernamePasswordCredential?

As I wrote above, UsernamePasswordCredential doesn't require `tenant_id` because it can authenticate to the "organizations" endpoint, which is effectively the user's home tenant. The credential still needs a tenant but has a reasonable default, so it doesn't require you to tell it which tenant to use.

That said, UsernamePasswordCredential (really, [Azure AD password authentication](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth-ropc)) has some important limitations:
1. it can authenticate only work or school accounts i.e. no consumer accounts such as @outlook.com, @live.com, @hotmail.com
1. it can't authenticate if any kind of multi-factor authentication is required
1. `client_id` must identify an application configured to allow public client flows
1. the user or tenant admin must already have consented to that application

You may be running in to one of these limitations. If you're just trying to authenticate as yourself during local development, you may find [InteractiveBrowserCredential](https://aka.ms/azsdk/python/identity/docs#azure.identity.InteractiveBrowserCredential) or a credential that authenticates through a developer tool such as the [Azure CLI](https://aka.ms/azsdk/python/identity/docs#azure.identity.AzureCliCredential) or [VS Code](https://aka.ms/azsdk/python/identity/docs#azure.identity.VisualStudioCodeCredential) easier to use.

**Comment by Nerigal** [comment]
@chlowell 
 
>     4. the user or tenant admin must already have consented to that application
Hi, 

Can you give more detail about this

**Comment by chlowell** [comment]
The basic problem there is that applications need user (and/or tenant admin) consent. Password authentication isn't interactive, so there's no way to present a consent prompt to the user during authentication; the application must have consent before the authentication attempt. [MSAL Python docs](https://github.com/AzureAD/microsoft-authentication-library-for-python/wiki/Username-Password-Authentication) have a good summary of this with links into Azure AD docs describing how to grant consent to applications.

**Comment by Nerigal** [comment]
@chlowell 

well not sure why but look like there is a disconnect between that MSAL doc and the Azure portal 
no where i could find that _Treat application as a public client_ setting 

here is what i see il all iteration of app i cloud tried 

https://imgur.com/Im7o1QH

**Comment by chlowell** [comment]
That's the correct setting, password authentication is a public client flow.
