### ISSUE TITLE
Inconsistency in argument naming in `virtual_machine_scale_set_vms`

### ISSUE THREAD

**Issue by wessm** [Azure/azure-sdk-for-python#19644]
**Is your feature request related to a problem? Please describe.**
It's only a small thing, but I needed some time to figure out that some of the operations in `virtual_machine_scale_set_vms` expect the scale set name as `vm_scale_set_name`, while others as `virtual_machine_scale_set_name`. I don't know if this inconsistency exists anywhere else, too, or if this is the only occurrence; I just came across this while starting to use the python azure SDK.

Examples:

https://github.com/Azure/azure-sdk-for-python/blob/369603ef8e77a637614169967d7e8f1ebd698948/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2021_03_01/operations/_virtual_machine_scale_set_vms_operations.py#L805-L813

and 

https://github.com/Azure/azure-sdk-for-python/blob/369603ef8e77a637614169967d7e8f1ebd698948/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2021_03_01/operations/_virtual_machine_scale_set_vms_operations.py#L471-L478

I don't know the reason for this, but I would argue it would be less surprising to users if the parameters were named in a consistent way.

**Comment by kristapratico** [comment]
Thanks for the feedback, we'll investigate asap.

**Comment by jaylabell** [comment]
@avirishuv can you take a look at this issue?

**Comment by avirishuv** [comment]
hi @kristapratico , were you able to investigate this - would you mind providing an update? Thanks!

**Comment by avirishuv** [comment]
hi @wessm the naming in the underlying APIs is inconsistent: https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list and https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-sets/create-or-update 
Unfortunately we will not be able to change the naming in the APIs at this point, as it will be a breaking change.

Agree with you suggestion going forward. However, I will be closing this issue due to the reason I mentioned here. Please feel free to reopen if you have additional questions or comments for us. Thanks.
