### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by sbenthall** [Azure/azure-sdk-for-python#19659]
- **Package Name**: azure-storage-blob 
- **Operating System**: Ubuntu 20.04.2 LTS
- **Python Version**: 3.8.10

**Describe the bug**
I'm getting a ModuleNotFoundError when trying to use this package

**To Reproduce**
```
$ pip install azure-storage-blob --upgrade --force-reinstall
$ python

>>> from azure.storage.blob import BlobServiceClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure'
```

**Expected behavior**
I expect a successful import of BlobServiceClient

**Additional context**

Ubuntu 20.04.2 LTS

**Comment by kristapratico** [comment]
Thanks for your question. Is azure-storage-blob being installed in a virtual environment?

**Comment by xiafu-msft** [comment]
Hi @sbenthall 

thanks for reaching out, can you paste the pip freeze result here? We suspect that azure-storage was installed accidentally.

**Comment by sbenthall** [comment]
This is my pip freeze.

https://gist.github.com/sbenthall/cbe9f573dd991381a015499eb2f217c8

**Comment by xiafu-msft** [comment]
Hi @sbenthall  
can you try to uninstall azure-storage-common and see if it works?

**Comment by sbenthall** [comment]
I `Successfully uninstalled azure-storage-common-1.4.2`

but I'm still getting the same error when I try to `import azure`

**Comment by sbenthall** [comment]
yes this is in a virtual environment

**Comment by xiafu-msft** [comment]
Hi @sbenthall 
could you please create a new virtual environment and just do 
`pip install azure-storage-blob` 
and see if that works?

**Comment by sbenthall** [comment]
I created a new virtual env and installed azure-storage-blob. Same error.

https://gist.github.com/sbenthall/1a9ef65d73b6769ff2662e5d0ec861a8

**Comment by sbenthall** [comment]
Hello. I'm still getting this problem.
Does this work on other operating systems?

**Comment by xiafu-msft** [comment]
Hi @sbenthall 
It works for other operating systems, did you activate the new virtual env when you try to import? also make sure you only do pip install azure-storage-blob in the new virtual env.

**Comment by sbenthall** [comment]
Yes. I've tried again now, with a different way of making a fresh virtualenv.

I get this:
https://gist.github.com/sbenthall/2aacbd1142b979a15797197690767404

Here is my `pip freeze` in this new virtualenv:

https://gist.github.com/sbenthall/614745bb265b79d19c5612096b9c7052

**Comment by lmazuel** [comment]
@sbenthall , if you look carefully, you will see you run `pip` under Python 3.6 (see you download cffi cp36), while when you type `python` you open Python 3.8. 

So your $PATH is configured in a way that `pip` and `python` are not calling the same interpreter. The right solution to solve it is machine dependent:
- Uninstall one of the two you don't need
- Reset your $PATH to clarify which python to use
- Call `python -m pip` instead of `pip` to force the pip from python 3.8
- You may have a `pip3.8` alias on your machine (dependent of installation) that would force pip to be 3.8

We don't believe this is SDK dependent based on the trace you share, so I'm tagging this issue as "addressed" but feel free to reply if once you run the same interpreter in both pip and python you are still broken.

Thanks!

**Comment by sbenthall** [comment]
@lmazuel That worked. Thank you so much!

**Comment by amishra-dev** [comment]
@xiafu-msft can we add this to a TSG article somewhere?
