### ISSUE TITLE
ClientId in UsernamePasswordCredential Class

### ISSUE THREAD

**Issue by sushilchand** [Azure/azure-sdk-for-python#19680]
Observed one thing that in the previous versions of SDK clientId was not a compulsory field and in this SDK version if we don't pass the clientId then there is exception. Can someone help in understanding why clientId is needed for ADFS as for ADFS authentication only username and password is required. Also wanted to know if there is any other class present in latest python SDK which can be used for ADFS authentication instead of this one ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6deb41c6-57ce-9902-1cb0-3868dd615a37
* Version Independent ID: e20063bc-7fb4-2b34-817f-c3e50d7797ac
* Content: [azure.identity.UsernamePasswordCredential class](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.usernamepasswordcredential?view=azure-python)
* Content Source: [docs-ref-autogen/azure-identity/azure.identity.UsernamePasswordCredential.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-identity/azure.identity.UsernamePasswordCredential.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Thanks for your question, we'll get back to you asap.

**Comment by chlowell** [comment]
So far as I know, Azure AD always always requires a client ID--you must authenticate to a specific registered application. The authentication library for the prior version of the SDK [uses a default client ID](https://github.com/Azure/msrestazure-for-python/blob/8849f398b6ebd4607de63c2f5d1318f44ec1d822/msrestazure/azure_active_directory.py#L298) for password authentication when one isn't otherwise specified. Some credential types in the SDK's new authentication library (azure-identity) do the same. UsernamePasswordCredential does not, because that default client ID is most appropriate for local development and other credential types are better for that.

Other credential types do support ADFS authentication. Generally, any credential in the `azure.identity` namespace that takes `tenant_id` and `authority` arguments can authenticate to an Azure Stack ADFS endpoint (one known exception is VisualStudioCodeCredential). You need to pass `tenant_id="adfs"` and `authority="your ADFS URL"`. For example, authenticating a service principal with a secret:
```py
ClientSecretCredential(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    authority="https://adfs.contoso.com",
    tenant_id="adfs"
)
```

**Comment by sushilchand** [comment]
But how does the previous class used to authenticate when UserPassCredential class was being used for ADFS authentication. There I can see tenant id was not mandatory and in order to keep the similar behavior which class in the latest SDKs can be used to do the same ?

**Comment by chlowell** [comment]
UsernamePasswordCredential and UserPassCredential use the same authentication flow but have different APIs. To maintain the same behavior in your application--authenticating a user with a password--use UsernamePasswordCredential. A tenant ID actually isn't required in general. ADFS is a special case though ([also for UserPassCredential](https://github.com/Azure/msrestazure-for-python/blob/8849f398b6ebd4607de63c2f5d1318f44ec1d822/msrestazure/azure_active_directory.py#L105)). I don't expect the default tenant to work with an ADFS authority.

**Comment by pyprateek** [comment]
@chlowell if UsernamePasswordCredential and UserPassCredential use the same authentication flow then why doesn't the default client id works for UsernamePasswordCredential also. If the authentication was working with the old SDK version and there is no change in the AzureStack configuration, shouldn't there be the same behavior with the latest version also?
If we use UserPassCredential with the latest python SDK then we get the following error:
`AttributeError: 'UserPassCredentials' object has no attribute 'get_token'`

**Comment by chlowell** [comment]
> if UsernamePasswordCredential and UserPassCredential use the same authentication flow then why doesn't the default client id works for UsernamePasswordCredential also.

Can you please add some more detail? What error do you see?

> If we use UserPassCredential with the latest python SDK then we get the following error:
> `AttributeError: 'UserPassCredentials' object has no attribute 'get_token'`

As I wrote above, credential types from azure-identity (UsernamePasswordCredential) and azure-common/msrestazure (UserPassCredential) have different APIs. In particular, the former have a `get_token` method that the latter do not. The latest Azure SDK clients call this method, so you will see this error when you give them a UserPassCredential instance.

**Comment by pyprateek** [comment]
Following is the stack trace
`File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/msrestazure/azure_active_directory.py", line 308, in __init__
    self.set_token()
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/msrestazure/azure_active_directory.py", line 326, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/msrestazure/azure_active_directory.py", line 318, in set_token
    token = self._context.acquire_token_with_username_password(
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/authentication_context.py", line 164, in acquire_token_with_username_password
    return self._acquire_token(token_func)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/authentication_context.py", line 162, in token_func
    return token_request.get_token_with_username_password(username, password)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/token_request.py", line 295, in get_token_with_username_password
    token = self._get_token_username_password_managed(username, password)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/token_request.py", line 177, in _get_token_username_password_managed
    return self._oauth_get_token(oauth_parameters)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
msrest.exceptions.AuthenticationError: , AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_client","error_description":"MSIS9607: The \u0027client_id\u0027 parameter in the request is invalid. No registered client is found with this identifier."}`

I am using this client id: 04b07795-8ddb-461a-bbee-02f9e1bf7b46

**Comment by chlowell** [comment]
That trace isn't from UsernamePasswordCredential, so I assume you used UserPassCredentials? In any case, the error message is from Active Directory: the client ID is not registered. The SDK can't work around that, unless you aren't using the client ID you expect e.g. because you mixed up arguments or something similar. Can you share a code snippet to show how you construct the credential object?

**Comment by pyprateek** [comment]
Yes, I sent the stack trace of UserPassCredentials instead of UsernamePasswordCredential.

Following code snippet is to fetch credentials:
`credentials = UsernamePasswordCredential(self.client_id, 'username', 'password', verify=False)`
And below one is to create the compute client
`ComputeClient = ComputeManagementClient(config.get_azure_credential(),
                                   config.get_subscription_id(), 
                                   base_url=config.get_base_url(),
                                   credential_scopes=[config.get_audience_url() + '/.default'])`

Following stack trace i got for UsernamePasswordCredential:
`Exception occurred while running discovery: Authentication failed: AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.
Trace ID: 283002ff-8c4a-4e85-81b3-e54fdd762400
Correlation ID: b41e1ce1-6938-4c9d-8ecc-29aae738459e
Timestamp: 2021-07-13 15:46:47ZTraceback (most recent call last):
  File "/opt/VRTSsfmh/adm/AzureDiscover.py", line 1063, in main
    ret = func(azure_discover_object, **kwargs)
  File "/opt/VRTSsfmh/adm/AzureDiscover.py", line 64, in __call__
    discovery_response = self.method(*args, **kwargs)
  File "/opt/VRTSsfmh/adm/AzureDiscover.py", line 151, in discover_virtual_machines
    rest_api_output = self.get_output(vms_iter, location=self.location)
  File "/opt/VRTSsfmh/adm/AzureDiscover.py", line 114, in get_output
    for page in paged_iter:
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/compute/v2021_03_01/operations/_virtual_machines_operations.py", line 1158, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 117, in send
    self.on_request(request)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/core/pipeline/policies/_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
  File "/opt/VRTSitrptpcims/python-virtual-environments/azure/lib/python3.9/site-packages/azure/identity/_internal/interactive.py", line 145, in get_token
    raise ClientAuthenticationError(message=message, response=response)
azure.core.exceptions.ClientAuthenticationError: Authentication failed: AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials.
Trace ID: 283002ff-8c4a-4e85-81b3-e54fdd762400
Correlation ID: b41e1ce1-6938-4c9d-8ecc-29aae738459e
Timestamp: 2021-07-13 15:46:47Z`

**Comment by chlowell** [comment]
> UsernamePasswordCredential(self.client_id, 'username', 'password', verify=False)

This issue was specifically about ADFS authentication but with this code the credential will authenticate to Azure Active Directory in the public cloud. Are you working in a similar environment to @sushilchand or reporting an unrelated issue?

> AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials

UsernamePasswordCredential defaults to Azure AD's "organizations" endpoint, which can only authenticate work or school accounts. This error typically means you tried to authenticate a Microsoft Account (MSA) e.g. @hotmail.com, @live.com, @outlook.com. For these accounts you need to specify a tenant to authenticate in:

```py
UsernamePasswordCredential(self.client_id, 'username', 'password', tenant_id='...')
```
(also, the credential doesn't use a `verify` argument)

**Comment by pyprateek** [comment]
>  Are you working in a similar environment to @sushilchand or reporting an unrelated issue?

Yes.

Following line of code worked for me:
`credentials = UsernamePasswordCredential(self.client_id, 'username', 'password', authority=self.auth_url,  tenant_id='tenant_id', connection_verify=False)`

Thank you for your help. @chlowell

**Comment by sushilchand** [comment]
Hi @chlowell thanks for your input but I wanted to confirm one thing for ADFS authentication only.
If we want to do ADFS authentication with the latest SDKs then do we always have to provide clientId along with username and password in UsernamePasswordCredential class ? 
In our application earlier we used to use only username and password with UserPassCredential class it used to work for us but now if we try to use UsernamePasswordCredential class then we get this error that cleintid field is missing. 

Code snippet:
credentials = UserPassCredentials(c["username"], c["password"], cloud_environment=cloud, resource=auth_resource)

but the above code won't work for UsernamePasswordCredential class as it asks for cleintId too.

**Comment by chlowell** [comment]
UsernamePasswordCredential requires `client_id` in all cases, not only for ADFS. As I wrote above, the underlying authentication flow requires a client ID, it's just that UserPassCredentials has a default value (which you can use with UsernamePasswordCredential, but you do need to explicitly pass that value).

Other API differences affect your code snippet as well. Updated for the latest SDK libraries, it would look something like this:

```py
credential = UsernamePasswordCredential(
    client_id,
    c["username"],
    c["password"],
    authority="https://adfs.contoso.com",
    tenant_id="adfs"
)

# other management clients use the same keyword arguments, this is just one example
ResourceManagementClient(
    credential,
    subscription_id,

    # assuming your "cloud" is an msrestazure Cloud object
    base_url=cloud.endpoints.resource_manager,

    # a reasonable guess but this varies for private clouds
    credential_scopes=[auth_resource + "/.default"]
)
```

**Comment by pyprateek** [comment]
Hi @chlowell 

It seems that for ADFS, tenant_id is a mandatory parameter in UsernamePasswordCredential but it was not the case for UserPassCredentials. 
How does UserPassCredentials determines the tenant?

From what I understand, ADFS only supports single tenant. So, does UserPassCredentials internally determines the tenant id or it was not required?

**Comment by chlowell** [comment]
`tenant_id` isn't exactly an Azure AD tenant in this context. These credential types use the tenant to determine the base URL for authentication requests. In terms of UsernamePasswordCredential's API, that's `https://{authority}/{tenant_id}`. `tenant_id` is optional because there's a reasonable default for public/sovereign clouds. However, so far as I know, for ADFS authentication on Azure Stack, you want to send requests to `https://{authority}/adfs`. This is why I don't expect your code to work without specifying `tenant_id="adfs"`. [UserPassCredentials](https://github.com/Azure/msrestazure-for-python/blob/8849f398b6ebd4607de63c2f5d1318f44ec1d822/msrestazure/azure_active_directory.py#L105) and its [underlying authentication library](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/e5f662f26b81f23a19e6caeab7f19f578d1306d1/adal/authority.py#L59) also expect an "adfs" tenant.

**Comment by copdips** [comment]
@chlowell 
Known that azcli is based on Python, do you have any information why azcli without `client_id` works ?
```bash
az login --username --password
```
I cannot figure it out from the source code.

**Comment by chlowell** [comment]
The Azure CLI is an application registered in Azure AD, so it simply sends its own client ID in token requests.
