### ISSUE TITLE
azure storage blob download: ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by fengzhuye** [Azure/azure-sdk-for-python#19753]
Hi 

I installed the azure-storage-blob python sdk(12.8.1) from pip.
And setup a cron job to read all the blob files from the container, however, i find many error message from the log:

Unable to stream download: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

Why the connection will be reset by azure? 
Any feedback will be appreciated.

Thanks
Wei

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f60c47f1-e4d8-f68e-5f9c-460c4fdc6da8
* Version Independent ID: 172e9f9b-25fb-2121-cb72-d383cc21763a
* Content: [Azure Storage Blobs client library for Python](https://docs.microsoft.com/zh-cn/python/api/overview/azure/storage-blob-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/storage-blob-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/storage-blob-readme.md)
* Service: **storagestorage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiafu-msft** [comment]
Hi @fengzhuye 

Thanks for reporting this. Is there any extra info in the stacktrace? Can you paste them here?
Also, did you check if the blob was downloaded successfully finally, ideally we will auto retry it if the error is caught properly. Can you tell if the requests are retired based on the stacktrace?

Thanks for helping on our investigation!

**Comment by xiafu-msft** [comment]
Hi @fengzhuye 

Can you check which version of azure-storage-blob sdk you are using?
if it's not >=12.8.1 can you upgrade to that and see if that can help?

**Comment by fengzhuye** [comment]
Hi @xiafu-msft 

Thanks for the reply. I am currently using version 12.8.1

Only the log message shows up, there is no stacktrace or other info.

It seems the exception is already handled by the sdk. I am not aware of this error in my program.
But not sure if the blob is downloaed in this situation.

**Comment by xiafu-msft** [comment]
Hi @fengzhuye 

Sounds like this is not a bug, storage retry for 3 times on this error, the sdk is working as expected if your blob is downloaded successfully.

Let me know if you have any concern!

**Comment by fengzhuye** [comment]
Hi @xiafu-msft 

It's that possible "ConnectionResetError(104, 'Connection reset by peer'))" will happens 3 times?
I want to know why this error happens, or what can I do to avoid this kind of error?

Sorry about the bothering.

**Comment by jaymegordo** [comment]
I also get this error frequently, ~2 times per day, while running code on a 15min interval on an azure functions app. The error never occurs while testing locally though. Is there a way to increase the retries?

**Comment by amishra-dev** [comment]
@tasherif-msft we should have a sample about how to setup retry policy and modify it

**Comment by gmotasilva** [comment]
Is there any update on that? Any workaround? I'm having this errors intermittently.

**Comment by amishra-dev** [comment]
@jalauzon-msft Jacob was working on this. Jacob can you please post an update here?

**Comment by jalauzon-msft** [comment]
To update everyone on the thread. @fengzhuye @jaymegordo @gmotasilva 

Connection Reset errors come from the service and there is not much that can be done to eliminate them from the client-side. The best that can be done from the client is to have retries when this error occurs. The SDK will automatically retry these errors 3 times with an exponential backoff policy.

If you are seeing these errors, but retries are succeeding, then there is not much more that can be done from the client side.

If, however, your operations are failing with this error after the default 3 retries there are a couple of options.
- You can open a support ticket with your Storage account to have the service team investigate the connection reset errors. 
- You can try increasing the number of retries by providing your own custom retry policy. This can be achieved with by providing a retry policy when creating any client (blob, datalake, file share, queue).

```python
from azure.storage.blob import ExponentialRetry, BlobServiceClient

retry_policy = ExponentialRetry(
    retry_total=5
)

service_client = BlobServiceClient(
    'https://myaccount.blob.core.windows.net',
    retry_policy=retry_policy
)
```

The default value for `retry_total` is 3 so you could try 5, for example. There are also other parameters such as `initial_backoff` and `increment_base` that can be tweaked to change the time in between retries.

We are also currently investigating why this issue seems to be happening more often in our Python SDK, when compared to our other languages. From this investigation, we may end up tweaking the default retry values or something similar. We also plan to start an internal discussion with the service team on this issue.

**Comment by jalauzon-msft** [comment]
Hi all, while investigating #22784 it seems there was, at one point, an issue where blob download was not properly retrying connection reset errors. I think this was addressed in a later release of `azure-storage-blob` or (more like) `azure-core` so updating to latest may help with error in blob download specifically.

**Comment by cheryl-catalog** [comment]
/unresolved
I am seeing this error as well:

2022-05-27T21:51:42+0000 __next__():186 Unable to stream download: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
2022-05-27T21:51:42+0000 wrapped():79 Download stream interrupted.

pip3 freeze | grep azure
azure-common==1.1.28
azure-core==1.24.0
azure-storage-blob==12.12.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.8.0

I will try the suggested tweaks above and see how it goes. I just started see this error this week
