### ISSUE TITLE
Unable to fetch all subnet parameters from route table

### ISSUE THREAD

**Issue by IshirDutta-bsn** [Azure/azure-sdk-for-python#1990]
Subnets returned by route_table.subnets only show subnet id. All other parameters are returned as "None". Checked with the Java API and it doesn't have the same issue. 

https://github.com/Azure/azure-sdk-for-python/blob/fbc86e377617b7c20b7876f5cc8198c381d362ce/azure-mgmt-network/azure/mgmt/network/v2017_11_01/models/route_table.py#L59

**Comment by lmazuel** [comment]
Hi @IshirDutta-bsn 
Java SDK is fetching for you the list from the ids in the list. The RestAPI is the same, no magic :)

I might want to do that as well, I keep this issue open until I find time to address a recursive call to fill the model. Note that this would be optional, since this has performance impact that I can't afford if users is not interested by the subnets.

**Comment by xiangyan99** [comment]
@IshirDutta-bsn the latest azure-mgmt-network is 19.3.0. Does this work?
