### ISSUE TITLE
Azure RBAC doesn't seem to provide granuar access of certificate secret

### ISSUE THREAD

**Issue by Jordan0928** [Azure/azure-sdk-for-python#19919]
Hello,

I am unable to provide read access to a specific key vault certificate content (including its private key) to  my virtual machine. Azure RBAC does NOT seem to support granular access of certificate secret - content of the certificate including private key.

I can assign custom/buit-in roles with permission "Read Certificate" to specific key vault certificates. This allows certificate metadata access ONLY. I can not access the certificate/private key content. Adding "Get Secret" permission to the custom role does Not make a difference. I get error message "ForbiddenByRbac" when I try to access the certificate secret content using Azure key vault secrets client for python using certificate name as secret name.

Since the certificate secret is not listed under the Azure key vault secrets list, I can't assign exclusive role with permission "Get Secret" to it.

Assigning a role with permission "Get secret" to the entire key vault works but I want to provide the least privilege permission.

**Comment by mccoyp** [comment]
Hi @Jordan0928, thank you for opening an issue! I'll look into this for you and provide an update as soon as possible.

**Comment by mccoyp** [comment]
@jlichwa, would you have any context for this?

**Comment by jlichwa** [comment]
In general key vault is security boundary, so you should always assign roles on Key Vault level and have one key vault per applications, region, and environment. Least privilege is for minimum role assignment on key vault itself as a security boundary unit - i.e. Application who just reads secrets should not have access to create secrets.

Per object should only for very rare scenario when same secret/certificate is shared between applications - it should be avoided when possible. In case if your scenario fit in this example - for accessing entire certificate for VM the role is "Key Vault Secrets User" needs to be assign on Secret portion of certificate - it is only possible with CLI or PowerShell since secret portion is not visible in Portal.

**Comment by mccoyp** [comment]
Thank you for the quick reply! @Jordan0928, please let us know if this doesn't resolve your issue. [This documentation](https://docs.microsoft.com/azure/key-vault/general/rbac-guide?tabs=azure-cli#secret-scope-role-assignment) about secret-level role assignments should be able to help (if you haven't referenced it already). A CLI command such as
```cmd
az role assignment create --role "Key Vault Secrets User" --assignee {VM identity} --scope /subscriptions/{subscriptionid}/resourcegroups/{resource-group-name}/providers/Microsoft.KeyVault/vaults/{key-vault-name}/secrets/{certificate-name}
```
should do the trick.

**Comment by Jordan0928** [comment]
Thank you both for the tips. I will consider using "least privilege permissions" at key vault level.

The CLI command with narrower scope .../{key-vault-name}/secrets/{certificate-name} did the trick. But I couldn't delete the role/permissions I added with this narrow scope. I tried "az role definition delete --name" with name returned when creating the role. I don't see any roles from portal and CLI but I can still access the secret from my virtual machine. 
bruce@Azure:~$ az role definition list --custom-role-only
[]

Any tips how to get rid of such narrower custom role?

**Comment by mccoyp** [comment]
To remove the permissions you added, you would actually have to delete the role assignment since a built-in role definition was assigned. The documentation for the CLI command to do so is [here](https://docs.microsoft.com/cli/azure/role/assignment?view=azure-cli-latest#az_role_assignment_delete) -- you can remove the role by running
```cmd
az role assignment delete --assignee {VM identity} --role "Key Vault Secrets User"
```
or
```cmd
az role assignment delete --ids {role-assignment-id}
```
(where `role-assignment-id` looks like `/subscriptions/{subscriptionid}/resourcegroups/{resource-group-name}/providers/Microsoft.KeyVault/vaults/{key-vault-name}/secrets/{certificate-name}/providers/Microsoft.Authorization/roleAssignments/{role-assignment-name}`)

**Comment by Jordan0928** [comment]
Perfect. Got deleted using "az role assignment delete --id" Found the id from "az role assignment list --all"
Agreed, this is quite tricky. I will go for key vault level access management.

Thanks for the quick and valuable help.
