### ISSUE TITLE
azure-mgmt-sql: LICENSE missing from PyPi

### ISSUE THREAD

**Issue by major** [Azure/azure-sdk-for-python#20183]
- **Package Name**: azure-mgmt-sql
- **Package Version**: 3.0.1
- **Operating System**: Linux
- **Python Version**: 3.9.6

**Describe the bug**
The `LICENSE` file is missing from azure-mgmt-sql in PyPi.

**Additional context**
I am making a PR for this now.

**Comment by lmazuel** [comment]
Hi @major 

Most of packages are auto-generated from a template system, so I won't accept your PRs since they will be overwritten by the template anyway. Can you PR the template maybe? This would simplify your work.

https://github.com/Azure/azure-sdk-for-python/tree/main/tools/azure-sdk-tools/packaging_tools/templates

Thanks!

**Comment by major** [comment]
@lmazuel Thanks for the tip. I saw that code there but I wasn't sure how or when it was used. I'll try doing a PR there instead.

**Comment by major** [comment]
@lmazuel I'm new to the templating setup. Could you take a look at #20193 and let me know if this is the right way to do it? Thanks! 🤗
