### ISSUE TITLE
client library for Python example does not use Python

### ISSUE THREAD

**Issue by dciborow** [Azure/azure-sdk-for-python#20728]
The guide here completes SEVERAL steps using Azure CLI, and not Python. For example in order to access a KeyVault I must first authorize the SP. These are the provided instructions...

![image](https://user-images.githubusercontent.com/9027725/133686537-534aa391-86b3-4e77-8c36-702e3c2f6198.png)

This does not help me to complete this with Python.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414e1303-766e-58be-23d6-494dd15952fb
* Version Independent ID: 333cafe8-4fe6-b020-5309-01191620807c
* Content: [Azure Key Vault Secrets client library for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/keyvault-secrets-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/keyvault-secrets-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/keyvault-secrets-readme.md)
* Service: **keyvault**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by xiangyan99** [comment]
Thanks for your feedback. 

This is key vault client SDK which is used to operate Azure Key Vault services. 

E.g. you can use our SDK to set/get/delete/etc. secrets.

In order to demo how to use the SDK, we have some prerequisites such as provisioning a key vault service and grant proper permissions which are the usage of other SDKs (key vault management SDK).

Hence we use CLI rather than python code to take care of the prerequisites.

Does this make sense?

Thanks.
