### ISSUE TITLE
[Storage SDKs] Please add "create_if_not_exists" methods for blob container, file share and queue

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-sdk-for-python#21044]
**Is your feature request related to a problem? Please describe.**
All other Storage SDKs have this handy functionality where you can ask SDK to create a resource (blob container, file share or a queue) if it does not exist. Surprisingly this feature is not available in any of the Python Storage SDKs.

**Describe the solution you'd like**
Please add `create_if_not_exists` method on respective clients (`BlobContainerClient`, `FIleShareClient` and `QueueClient`). This method would try to create a resource and returns true or false if it was able to create the resource successfully or the request was failed with `Conflict (409)` error. For all other errors, exception should be thrown by this method.

**Describe alternatives you've considered**
Currently we have to do something like the following:

```
    if not queue.exists():
        queue.create_queue()
```

**Additional context**
This functionality exist is all other Storage SDKs.

**Comment by Seerfer** [comment]
Agree. I can t understand how this is not available

**Comment by kristapratico** [comment]
Thanks for your feedback, @xiafu-msft please see the above feature request.

**Comment by vincenttran-msft** [comment]
Hi all, as you can see, we have been quite busy regarding this issue! Although we anticipated to have this feature added in the next release (as seen in PR #23574), after further discussion we have decided to side-line this feature request (currently in progress in #23857), citing idempotency issues when using `create_if_not_exists()` methods in certain cases may actually leave the state not as intended by the user, which may lead into larger issues down the line (and difficult to trace the root cause).

I apologize for any inconvenience this may have caused, and after speaking with the team, the (currently) correct way to emulate the behavior of a `create_if_not_exists()` method would be to use the code-logic as provided in the original post, and reposted here for clarity:

```
    if not queue.exists():
        queue.create_queue()
```
