### ISSUE TITLE
Update async samples to use asyncio.run instead of loop

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#21207]
- since Python 3.10 `asyncio.get_event_loop` is deprecated, a deprecation warning will be emitted if there is no running event loop. (For more context on the deprecation, please check doc: https://docs.python.org/3/library/asyncio-eventloop.html#event-loop)
- In our repo, asyncio.get_event_loop is used broadly in async samples for execution which means our users will get warning when they execute async samples. example in EH:
![image](https://user-images.githubusercontent.com/47871814/136870256-be555c91-2551-4d9f-a1c2-9280bfa802e2.png)
- we should try our best to update our async samples to use `asyncio.run` instead of loop as suggested by the Python community:
> Application developers should typically use the high-level asyncio functions, such as asyncio.run(), and should rarely need to reference the loop object or call its methods. This section is intended mostly for authors of lower-level code, libraries, and frameworks, who need finer control over the event loop behavior.

cc: @lmazuel

**Comment by Codejune** [comment]
I have a question about this issue.

As asyncio.get_event_loop is deprecated, we can suggest several methods.

The first method, this is the lower-level method.
``` python
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```

The second method, this method was added in Python 3.7. The reference document officially recommends the following method.
``` python
loop = asyncio.get_running_loop()
```

Last method, this method was also added in Python 3.7.
``` python
asyncio.run(...)
```

I found out that the Azure SDK will be deprecated for Python 2.7 soon.
However, I don't know of any future plans to support the Azure SDK Python version.
Which method is better? I need an answer on this.

**Comment by lmazuel** [comment]
Hi @Codejune ,

First on the Python versions: the baseline we support today is 3.6, that is going EOL this December 2021. We are not sure yet if we will deprecate 3.6 support immediately at its EOL, but soon in 2022 we will stop supporting 3.6 completely anyway. Which will make 3.7 the new baseline. There are no "lower users", since we stopped supporting 3.5 and below for a few months already.

The documented way in the Python doc today is `asyncio.run`, since 3.7:
https://docs.python.org/3.7/library/asyncio.html
![image](https://user-images.githubusercontent.com/1050156/137785944-8cce8a24-c34a-4d52-9088-f1cc09f90f86.png)

> This function always creates a new event loop and closes it at the end. **It should be used as a main entry point for asyncio programs**, and should ideally only be called once.

Following the recommendation of Python documentation do not prevent you to use `loop.run_until_complete(...)` :). It just means we believe we should follow the latest guidance, and sync with the official doc in our samples.
