### ISSUE TITLE
Read timeout should be set dynamically

### ISSUE THREAD

**Issue by tasherif-msft** [Azure/azure-sdk-for-python#21500]
There are three different timeouts, a timeout set on the service, `read_timeout` and `connection_timeout`.
Some customers hit an issue where the service never receives the request and we end up with a 20hr timeout (read_timeout).

Given that the default block size is 4MB (data broken down into 4MB blocks on uploads) and can be set up to 4000MB (in newer service versions), customers using the default block size value can set the read_timeout to be a small interval (for example 2 min). However, this can be improved upon in the SDK by dynamically changing the read_timeout depending on the block_size that the user defines.

**Comment by jalauzon-msft** [comment]
After some further investigation and testing it turns out this does not need to be set dynamically since it's a socket level timeout and does not depend on our data chunk size. We have created #25950 to adjust the default `read_timout` to a fixed value of 60 seconds and update the documetnation.

Closing this issue accodingly.
