### ISSUE TITLE
azure-cosmos not able to disable "endpoint_discovery"

### ISSUE THREAD

**Issue by gavinHuang** [Azure/azure-sdk-for-python#21750]
- **Package Name**: Azure-cosmos
- **Package Version**: 4.2.0 (and all other version)
- **Operating System**:Windows
- **Python Version**: 3.7

**Describe the bug**
"enable_endpoint_discovery" can't set to False at Cosmos_Client.py (line 82):
`policy.EnableEndpointDiscovery = kwargs.pop('enable_endpoint_discovery', None) or policy.EnableEndpointDiscovery
`
Even specifically set the value to False, this code will alway use the default value which is True.

**To Reproduce**
1.
`
cosmos_client = CosmosClient(
    url="https://accountname.documents.azure.com:443",
    credential="account_key",
    enable_endpoint_discovery=False
)
`

**Expected behavior**
Disable endpoint discovery 

**Screenshots**

**Additional context**
I don't need account discovery, the discovery change the url to something like:
`accountname-[region_name].documents.azure.com`
which in my environment is not a valid domain name, so I get error:
`
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x0000029C0E3B0588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
`

**Comment by swathipil** [comment]
@gavinHuang Thanks for the feedback - directing this to the right people!

**Comment by simorenoh** [comment]
Hi @gavinHuang, thank you for reporting this. You are completely right, this is a current gap in the SDK; the line you outlined will always evaluate to True since the second condition (policy.EnableEndpointDiscovery) is set to True (and naturally any or statement with one True condition ends up being True).

I have gone ahead and fixed this here: https://github.com/Azure/azure-sdk-for-python/pull/21778

Thanks again for reporting this and helping us improve the SDK! :)

**Comment by gavinHuang** [comment]
Thanks for the quick turn around!
