### ISSUE TITLE
ResourcesOperations.check_existence returns Bad Request

### ISSUE THREAD

**Issue by ksridhar57** [Azure/azure-sdk-for-python#21934]
- **Package Name**: azure-mgmt-resource
- **Package Version**: 20.0.0
- **Operating System**: Linux/Ubuntu 18.04
- **Python Version**:  3.6.9

**Describe the bug**
Using the method check_existence returns azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'

**To Reproduce**

    exists = resource_mgmt_client.resources.check_existence(
        resource_group_name=resource_group,
        resource_provider_namespace="Microsoft.Compute",
        parent_resource_path="",
        resource_type="virtualMachines",
        resource_name=vhub_name,
        api_version="2019-10-01"
    )

**Expected behavior**
Should return True/False

**Comment by YalinLi0312** [comment]
@ksridhar57 Thanks for your feedback, we'll investigate asap.

**Comment by SaurabhSharma-MSFT** [comment]
@ksridhar57 I could see the same behavior, when I use the resource type as 'virtualMachines'.  
![image](https://user-images.githubusercontent.com/38112130/144341517-68a605f7-353d-45b4-88bb-e7816e48010a.png)

Additionally, when I use the api version as `2021-04-01` then I get `Operation returned an invalid status 'Method Not Allowed'` error.
![image](https://user-images.githubusercontent.com/38112130/144341662-e9f5c907-0bec-4711-8b50-328211619163.png)

I am checking on internally on this one and get back to you.

Thanks
Saurabh

**Comment by msyyc** [comment]
Hi @service team, it seems that the parameter is not valid for service. Please provide some doc or examples for customers to refer.

**Comment by SaurabhSharma-MSFT** [comment]
@ksridhar57 Sorry for the delay on this.  As per internal discussion this looks like a limitation as check_existence is a head call and HEAD is not supported by Compute for a VM url.  
Workaround is to use [GET](https://docs.azure.cn/en-us/dotnet/api/azure.resourcemanager.resources.resourcesoperations.get?view=azure-dotnet-preview) instead of HEAD when it's a VM. However, using a GET does not have a Boolean return type instead you will get a typed return type (i.e. resource exists) if resource exists or an exception `ResourceNotFoundError` if it does not.
![image](https://user-images.githubusercontent.com/38112130/152233366-42f1ae8e-a872-4c97-b68a-918da61195d4.png)
Please let me know if you have any other questions.

Thanks
Saurabh
