### ISSUE TITLE
The documentation needs to be updated after the version 2.0.0 released.

### ISSUE THREAD

**Issue by caiyiJu** [Azure/azure-sdk-for-python#21995]
- **Package Name**: azure-mgmt-subscription
- **Package Version**: 2.0.0

https://docs.microsoft.com/en-us/python/api/azure-mgmt-subscription/azure.mgmt.subscription.subscriptionclient?view=azure-python This document does not apply to the 2.0.0 version any more. Because the SubscriptionsOperations was removed in the 2.0.0 version. Please update the document accordingly. It will confuse users.

**Comment by YalinLi0312** [comment]
@caiyiJu Thanks for your feedback, we'll investigate asap.

**Comment by msyyc** [comment]
Hi @caiyiJu ` azure-mgmt-subscription==2.0.0` really delete [SubscriptionsOperations](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/subscription/azure-mgmt-subscription/CHANGELOG.md#200-2021-11-25). But the [doc](https://docs.microsoft.com/en-us/python/api/azure-mgmt-subscription/azure.mgmt.subscription.operations.subscriptionoperations?view=azure-python) shows `SubscriptionOperations` not `SubscriptionsOperations`. It is really confusing since [swagger](https://github.com/Azure/azure-rest-api-specs/blob/81ab10cd9d46a85258b710c6150ec48021c6d202/specification/subscription/resource-manager/Microsoft.Subscription/stable/2021-10-01/subscriptions.json#L21) defines it. You could make an issue in [swagger repo](https://github.com/Azure/azure-rest-api-specs) to ask service team to change swagger definition then SDK will release new package with new definition to avoid the ambiguity.
