### ISSUE TITLE
[storage-queue] unicode strings in samples

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#22057]
Do we need to send the queue messages specified with unicode strings like this? Or was this a compatibility issue with py2.7? Since we are dropping 2.7 in a few weeks, might be nice to update the samples without it since py3 uses unicode by default.

https://github.com/Azure/azure-sdk-for-python/blob/78e22ebd91587ad53a0abe49d1346bc262afb140/sdk/storage/azure-storage-queue/samples/queue_samples_hello_world.py#L50-L55

**Comment by wonhyeongseo** [comment]
Hello @kristapratico, may I try this issue? I also found cognitive-language to have samples with unicode strings. Is it possible to PR multiple libraries at once? Thank you!

**Comment by kristapratico** [comment]
Hey @wonhyeongseo it's recommended to keep PRs specific to one library only. Feel free to work on the cognitive-language samples (I can help review these ones 😄). For the storage queue samples, I would like to check with @jalauzon-msft or @vincenttran-msft first to make sure that this is the right approach.

**Comment by jalauzon-msft** [comment]
@wonhyeongseo, definitely feel free to work on this issue for Queues as well! Removing the Unicode strings should be totally fine since we no longer support Python 2. As Krista mentioned, its best to have separate PRs for each library but I'd be happy to help review these changes for Storage. Thanks!
