### ISSUE TITLE
list_by_resource_group of azure-mgmt-resource does not work correctly

### ISSUE THREAD

**Issue by ksridhar57** [Azure/azure-sdk-for-python#22295]
- **Package Name**: azure-mgmt-resource
- **Package Version**: 20.0.0
- **Operating System**: Linux
- **Python Version**: 3.6.9

**Describe the bug**
Resource Management Client's list_by_resource_group() API does not list all resources correctly. This has been observed with Microsoft.Compute/disks resource types. There are 2 OsDisk resources created for each VM instance in the resource group, however the list operation only returns the OS Disk associated with the first VM.  

**To Reproduce**
`def list_resources_in_group(resource_group):
    try:
        resource_list = []
        resources = resource_mgmt_client.resources.list_by_resource_group(resource_group)
        for res in resources:
            print(res)
            print("\n")
    except ResourceNotFoundError as err:
        print("Resource Not Found")
    except Exception as err:
        print(err)
`

**Expected behavior**
All resources in resource group should be listed.

**Screenshots**
Attached is a screenshot showing the OS Disk resources shown in the portal that is associated with the 2 VM instances. Also attached is the output of the code which only lists one of the OS Disk resources. 

**Additional context**
<img width="1281" alt="Screenshot 2021-12-31 at 11 03 19 PM" src="https://user-images.githubusercontent.com/83217033/147834189-ced928ce-0053-42cd-b149-724b25b85ec1.png">
[out.txt](https://github.com/Azure/azure-sdk-for-python/files/7796773/out.txt)

**Comment by tjprescott** [comment]
@msyyc could you please take a look?

**Comment by msyyc** [comment]
Hi, Python SDK is generated automatically with swagger. Since SDK team can't reproduce your error, we should think about whether it is problem of service. You could use [rest api](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json#L2409) to call service directly and see the return result.
If result is expected, it proves that SDK has problems;
If result is not right, it proves that service has problem. Then you could make issue in https://github.com/Azure/azure-rest-api-specs to ask help from service team.

**Comment by ksridhar57** [comment]
I notice different behaviour with different APIs - REST, Az CLI and Python SDK. None of them results in the expected output. I will also raise this issue with the service team as suggested. Thanks.

**Comment by BigCat20196** [comment]
Hi @ksridhar57, I noticed your out Txt file has detailed output. Is it obtained through the python SDK?

If so, you can see that the name value in each dictionary returned roughly corresponds to the name in your screenshot above.

Did you do the operation at the same time without changing the resources?

Thank you for providing more information to help us solve this issue faster.
