### ISSUE TITLE
[Batch Management] Pool update - Non updatable properties

### ISSUE THREAD

**Issue by andreamigotto** [Azure/azure-sdk-for-python#22338]
Since the same _Pool_ class is, correctly, referenced both in the _create_ and _update_ methods as the type of the _parameters_ parameter, it should be indicated which properties are actually updatable, since the vast majority of them are not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d8bfb49-29d9-bf61-b3e1-18ff455a1e1b
* Version Independent ID: 153bd51a-0fbc-e754-aee9-12d82bd32648
* Content: [azure.mgmt.batch.models.BatchPoolIdentity class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-batch/azure.mgmt.batch.models.batchpoolidentity?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-batch/azure.mgmt.batch.models.BatchPoolIdentity.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-mgmt-batch/azure.mgmt.batch.models.BatchPoolIdentity.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
@andreamigotto thanks for bringing to our attention, we'll get this fixed asap.

**Comment by BigCat20196** [comment]
Hi @andreamigotto, thanks for your feedback !

Because the parameters are nested in multiple models, there is no detailed description yet.

There is a compromised solution.  

You can refer to [here ](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_models_py3.py#L3811)for a detailed description of the models.

FYR:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_models_py3.py#L3811

**Comment by 3ttp** [comment]
?? ???? 12 ??????? 2022 ?? 11:03 ?? ??? msftbot[bot] ***@***.***>:
Closed #22338.

?Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
