### ISSUE TITLE
Azure REST API returned keys and secrets that don't show up in the UI

### ISSUE THREAD

**Issue by abbytran1996** [Azure/azure-sdk-for-python#22347]
I used the API endpoints below to get the keys, secrets and certifications of my keyvault **olmkeyvault**. However, they returned a key "AndroidESRPIntegration" and a secret "AndroidESRPIntegration", which I don't see in the UI.

I'm using these endpoints to create alerts for expiring secrets, keys and certifications, so this bug has created a lot of false alerts.

---

GET https://olmkeyvault.vault.azure.net/keys?api-version=7.1
`{
    "value": [
        {
            "kid": "https://olmkeyvault.vault.azure.net/keys/AndroidESRPIntegration",
            "attributes": {
                "enabled": true,
                "nbf": 1596766414,
                "exp": 1635646414,
                "created": 1596767326,
                "updated": 1596767326,
                "recoveryLevel": "Recoverable+Purgeable",
                "recoverableDays": 90
            },
            "managed": true
        }
    ],
    "nextLink": null
}
`
GET https://olmkeyvault.vault.azure.net/secrets?api-version=7.1
`{
    "value": [
        {
            "contentType": "application/x-pkcs12",
            "id": "https://olmkeyvault.vault.azure.net/secrets/AndroidESRPIntegration",
            "managed": true,
            "attributes": {
                "enabled": true,
                "nbf": 1596766414,
                "exp": 1635646414,
                "created": 1596767326,
                "updated": 1596767326,
                "recoveryLevel": "Recoverable+Purgeable",
                "recoverableDays": 90
            }
        },
    ],
    "nextLink": null
}`

And here are the screenshots of my keyvault in the portal:

![Screen Shot 2022-01-05 at 4 58 52 PM](https://user-images.githubusercontent.com/22625926/148301802-907d8214-11ae-4f2f-b7a0-efb9e00eea4d.png)

![Screen Shot 2022-01-05 at 4 58 59 PM](https://user-images.githubusercontent.com/22625926/148301815-f6348a27-8cc4-4e83-890a-033108584d0f.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564796c6-e861-f1d5-c7c0-f19107a8ef11
* Version Independent ID: 5e980725-2f01-4a11-af4f-99a08609bc85
* Content: [azure.keyvault.keys.KeyClient class](https://docs.microsoft.com/en-us/python/api/azure-keyvault-keys/azure.keyvault.keys.keyclient?view=azure-python)
* Content Source: [docs-ref-autogen/azure-keyvault-keys/azure.keyvault.keys.KeyClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-autogen/azure-keyvault-keys/azure.keyvault.keys.KeyClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by kristapratico** [comment]
Hi @abbytran1996, thanks for your issue. Are you seeing this returned with the SDK as well? @YalinLi0312 and @mccoyp can you take a look?

**Comment by mccoyp** [comment]
Hi @abbytran1996, thank you for opening an issue! This happens because of the way certificates are represented by Key Vault. The [Get started with Key Vault certificates](https://docs.microsoft.com/azure/key-vault/certificates/certificate-scenarios) documentation briefly describes the structure of a certificate in the [Certificates are complex objects](https://docs.microsoft.com/azure/key-vault/certificates/certificate-scenarios#certificates-are-complex-objects) section.

A Key Vault certificate is represented by a certificate object, which you would see in the Certificates page in the Portal UI -- but each certificate is also associated with a key and secret. This key and secret don't show up in the Portal UI since they're really just part of a certificate, but they can be fetched with REST (or SDK client) requests.

To tell which keys/secrets are coming from certificates, and which are standalone objects unrelated to a certificate, you can use the `managed` property. The key and secret you shared each have `"managed": true` in their attributes, which indicates that their lifetimes are "managed" by Key Vault -- in other words, they'll be deleted if their associated certificate, AndroidESRPIntegration, is deleted.

If you're fetching keys and secrets to validate that the list is what you'd expect, you can filter out certificate keys and secrets by excluding objects that have `managed` set to True.

**Comment by abbytran1996** [comment]
@mccoyp Thank you for the explanation! That makes sense and I was able to filter out the associated keys and secrets.

Also, just a small thing that I noticed:
I'm using python 3.9.
In the SecretProperties model, there is no definition of the @property "managed". Therefore, returned secret objects have a property named `_managed`, instead of `managed`, like the key objects. The inconsistency is not a problem for us now, but when this issue is resolved, we will have to change our codes a little bit.

**Comment by mccoyp** [comment]
@abbytran1996 I'm glad you were able to find a solution!

On the point of the missing `managed` property on SecretProperties, you're completely right. This issue actually made me realize the omission, so there's a PR up (https://github.com/Azure/azure-sdk-for-python/pull/22368) to add the property. This will be included in the next release of `azure-keyvault-secrets`. Thank you for pointing it out!
