### ISSUE TITLE
azure-storage-file-datalake - DataLakeFileClient.delete_file() throws HttpResponseError with code None.

### ISSUE THREAD

**Issue by verikono** [Azure/azure-sdk-for-python#22445]
**Package Name**: 
azure-storage-file-datalake 12.5.0
**Dependent Packages**
azure-core 1.21.1
azure-identity 1.7.1
**Operating System**
Ubuntu 20.04
**Python Version**
3.7.12

**Describe the bug**
DataLakeFileCLient.delete_file() throws a HttpResponseError with an error code of None even though it has successfully removed the blob in the ADLG2. See below:

```python
with DataLakeFileClient(
  account_url="https://myadlg2.core.windows.net"
  file_system_name="someblobcontainer",
  file_path="somefolder/somefile.txt",
  credential=DefaultAzureCredential()
) as client:
  result = client.delete_file()
```

throws:

```python
Traceback (most recent call last):
  File "/mnt/myproject/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_path_client.py", line 259, in _delete
    return self._client.path.delete(**options)
  File "/mnt/myproject/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_generated/operations/_path_operations.py", line 1094, in delete
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Accepted'

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: must be real number, not type
Call stack:
 ... bunch of local code calls ...
  File "/mnt/myproject/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_path_client.py", line 261, in _delete
    process_storage_error(error)
  File "/mnt/myproject/venv/lib/python3.7/site-packages/azure/storage/filedatalake/_deserialize.py", line 139, in process_storage_error
    'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.', type(error_body))
Message: 'Unexpected return type % from ContentDecodePolicy.deserialize_from_http_generics.'
Arguments: (<class 'NoneType'>,)
```

**To Reproduce**
set a 3.7 with the above requirements and attempt to delete a known asset in a valid ADLG2 instance.

**Expected behavior**
delete_file() deletes the datalake resource without throwing a HttpResponseError

**Screenshots**

**Additional context**
This may relate to closed issue https://github.com/Azure/azure-sdk-for-python/issues/21872

**Comment by mccoyp** [comment]
Hi @verikono, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by vincenttran-msft** [comment]
Hi @verikono, thanks for your inquiry! Unfortuantely we have not been able to reproduce your findings on our end. However, there a couple things to note that may help to resolve your issue:

1. Your `account_url` seems to be missing an endpoint (typically `dfs` or `core`). For our attempt to reproduce, the URL is in the following format: `"https://<STORAGE_ACCOUNT_NAME>.dfs.core.windows.net"`.
2. I see that you were running version `12.5.0` of `azure-storage-file-datalake` when this behavior was observed. We would recommend installing the latest version of the package (`12.7.0`) and seeing if that resolves your issue, as our attempt to reproduce the issue have been unsuccessful.

**Note:** Since `azure-core` and `azure-identity` are dependencies they will be automatically updated if the latest version of `azure-storage-file-datalake` is installed, but just for completeness, the following versions of those two packages used were:
`1.23.1` for `azure-core`
`1.10.0` for `azure-identity`

With that being said, hopefully one of the above helps to resolve your issue!
Thanks!

**Comment by verikono** [comment]
> Hi @verikono, thanks for your inquiry! Unfortuantely we have not been able to reproduce your findings on our end. However, there a couple things to note that may help to resolve your issue:
> 
> 1. Your `account_url` seems to be missing an endpoint (typically `dfs` or `core`). For our attempt to reproduce, the URL is in the following format: `"https://<STORAGE_ACCOUNT_NAME>.dfs.core.windows.net"`.
> 2. I see that you were running version `12.5.0` of `azure-storage-file-datalake` when this behavior was observed. We would recommend installing the latest version of the package (`12.7.0`) and seeing if that resolves your issue, as our attempt to reproduce the issue have been unsuccessful.
> 
> **Note:** Since `azure-core` and `azure-identity` are dependencies they will be automatically updated if the latest version of `azure-storage-file-datalake` is installed, but just for completeness, the following versions of those two packages used were: `1.23.1` for `azure-core` `1.10.0` for `azure-identity`
> 
> With that being said, hopefully one of the above helps to resolve your issue! Thanks!

Sorry for a "no response" on this. I appreciate your time and was probably "in the thick of it" at the time. I apologise! Trust all is well.
