### ISSUE TITLE
Error while reusing  BatchMessage object 

### ISSUE THREAD

**Issue by Vprashant** [Azure/azure-sdk-for-python#22529]
- **Package Name**: azure-servicebus
- **Package Version**: 7.4.0
- **Operating System**:Linux (Ubuntu 18.04)
- **Python Version**: 3.8.12

**Describe the bug**
from this we have created service bus client :
servicebus_client = ServiceBusClient.from_connection_string(conn_str=sender_connection_string)

**created a sender object:**
sender = servicebus_client.get_topic_sender(topic_name=topic_name)
batch_message = sender.create_message_batch()

**So when we deepcopying the batch_message instance we got following issue**
topic_message_batch = copy.deepcopy(batch_message)

File "/usr/local/lib/python3.8/site-packages/uamqp/message.py", line 141, in __getstate__
state = deepcopy(state, memo)
File "/usr/local/lib/python3.8/copy.py", line 146, in deepcopy
state["state"] = self.state.value
AttributeError: 'BatchMessage' object has no attribute 'state' 

**while using 7.0.0 of azure_servicebus  we haven't faced any issues and everying was running fine.**

**Comment by mccoyp** [comment]
Hi @Vprashant, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible.

**Comment by swathipil** [comment]
Hey @Vprashant - apologies for the late response! I was able to reproduce the error with `azure-servicebus==7.4.0`, and I believe that this is related to some changes that were made in the underlying `uamqp` library dependency. More specifically, we added support for pickling to `uamqp==1.3.0`: https://github.com/Azure/azure-uamqp-python/blob/master/HISTORY.rst#130-2021-04-05.

You may not have noticed these changes if you updated directly from `azure-servicebus==7.0.0` (uamqp < 1.3.0) to `azure-servicebus==7.4.0`  (uamqp >= 1.4.3).

Just to double check, can you confirm the `uamqp` dependency versions that you are using for servicebus 7.0.0 and 7.4.0?

**Comment by Vprashant** [comment]
Hey @swathipil - uamqp dependency versions 

uamqp==1.2.12
azure-servicebus==7.0.0
--------------------------
uamqp==1.4.3
azure-servicebus==7.4.0 
Yes , I haven't used 7.1.1 , I directly move to azure-servicebus==7.4.0 from azure-servicebus==7.0.0

**Comment by swathipil** [comment]
@Vprashant thanks for the quick response!
As a follow-up:
You mentioned that `copy.deepcopy(message_batch)` worked when you used azure-servicebus 7.0.0 and uamqp 1.2.12. When I try to do the same, I get the following error:
`  File "stringsource", line 2, in uamqp.c_uamqp.StringValue.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__`. Is this not an error that you encounter?
(It's surprising that you didn't, given that we added the uamqp pickling support originally due to this error.)

**Comment by Vprashant** [comment]
Hi  @swathipil, 
No, I had't faced that above mentioned error; while working with azure-servicebus 7.0.0 and uamqp 1.2.12

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7329007/151309397-cfba2302-9d49-45ed-bf5d-ba38a005c436.png)

**Comment by swathipil** [comment]
Hey @Vprashant - thanks for your patience!

I tested `azure-servicebus==7.0.0` with the uamqp version you had, and I am still getting the `non-trivial __cinit__` error. Would you be able to run `pip freeze` on your `azure-servicebus==7.0.0` that was working and share it here?

The problem here is with the underlying `uamqp.BatchMessage` C object. We would need to overload the `__reduce__` method in `BatchMessage`. To modify the uamqp library and release it, it will take a little bit of time.

As a temporary solution, would you be able to add the `ServiceBusMessage` objects to a list, copy the list, and send the messages? The `ServiceBusMessage` objects can be deepcopied. Example here:
```python
sender = servicebus_client.get_topic_sender(topic_name=topic_name)
messages = [ServiceBusMessage("Message in list") for _ in range(10)]
messages_copy = copy.deepcopy(messages)
sender.send_messages(messages)
sender.send_messages(messages_copy)
```

Just in case you are curious, here are a few issues related to this same error: 
https://github.com/Azure/azure-sdk-for-python/issues/12901
https://github.com/Azure/azure-sdk-for-python/issues/15772

**Comment by Vprashant** [comment]
Hi @swathipil ,We are using a premium tier service and we need to use batching in our solution, for azure-servicebus==7.0.0 version. In my last message I mention the version in the attached image ( pip list | grep azure-servicebus).

**$ pip freeze | grep "azure"**
azure-common==1.1.26
azure-core==1.9.0
azure-eventhub==5.2.0
azure-functions==1.7.2
azure-servicebus==7.0.0
**$ pip freeze | grep "uamqp"**
uamqp==1.2.12

So for now, the temporary solution is not solving our batching issue. Let me know if you find something that works on batching service.

**Comment by swathipil** [comment]
Will update you on our plans after I discuss with the team. Thanks!

**Comment by swathipil** [comment]
Hey @Vprashant - we were able to fix this issue in the following PR: https://github.com/Azure/azure-uamqp-python/pull/310

This will fix will be out in the next `uamqp` release and the `uamqp` dependency version will be bumped for the next `azure-servicebus` release. To avoid waiting for the `azure-servicebus` release, you can install `uamqp==1.5.2` after it is released.

More details if you're interested: The `uamqp.BatchMessage` inherited `__getstate__/__setstate__` methods (used in `copy.deepcopy`) from the `Message` superclass. The methods needed to be overridden in `BatchMessage`.

**Comment by Vprashant** [comment]
issue-addressed
