### ISSUE TITLE
Pypi code examples links to this page, but no code

### ISSUE THREAD

**Issue by QuetzalcoatlRosso** [Azure/azure-sdk-for-python#22569]
On the [pypi site](https://pypi.org/project/azure-servicefabric/
) to install the service fabric python sdk, the Usage section directs to [this page](https://docs.microsoft.com/en-us/python/api/overview/azure/servicefabric/management?view=azure-python) "For code examples", but there are no immediate code examples listed.

Recommendation: update the pypi Usage link recommendation to where a user can click not more than two links and see code.

For example, one path currently requires five clicks:
[Management](https://docs.microsoft.com/en-us/python/api/overview/azure/servicefabric/management?view=azure-python) -> [mgt service fabric package](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicefabric/?view=azure-python) -> [service fabric package](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicefabric/azure.mgmt.servicefabric?view=azure-python) -> [models package](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicefabric/azure.mgmt.servicefabric.models?view=azure-python) -> [application resource class](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicefabric/azure.mgmt.servicefabric.models.applicationresource?view=azure-python)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa9a8b1-be30-0421-68e3-40f685b70db2
* Version Independent ID: d84ff036-d2b5-fb5d-aaa7-667c1193e980
* Content: [Service Fabric](https://docs.microsoft.com/en-us/python/api/overview/azure/servicefabric?view=azure-python)
* Content Source: []()
* Git Login: **lmazuel**
* Microsoft Alias: **lmazuel**

**Comment by msyyc** [comment]
It is common flow and needs doc team to help

**Comment by QuetzalcoatlRosso** [comment]
thanks for the context -- is it part of "common flow" to have a link for code examples that does not (directly) link to code examples?  would it be helpful if members of the "doc team" were added to this issue?

**Comment by msyyc** [comment]
Hi @scbedd, could you help give more context or address other expert?

**Comment by scbedd** [comment]
@msyyc The document they're referring to on [pypi ](https://pypi.org/project/azure-servicefabric/) is powered by the readme associated with your package here: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicefabric/azure-mgmt-servicefabric.

The request is to update the readme with more useful links. The package mentioned above was last published december 2021, and the readme was updated with new content since then. The link to the quickstart will help, but it doesn't reduce the amount of clicks to get to the ref docs themselves.

To functionally reduce the amount of clicks (aka reduce the depth of the ToC), we would need to link directly into it. Something like here: https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicefabric/azure.mgmt.servicefabric?view=azure-python

The issue with this is we're getting into generated parts of the URL that output directly from the docs processing. Namely, we will need to drop the package namespace in there if we want a direct link. For the vast majority of packages, we could assume based on package name. For _some_ though (mostly extension packages), this assumption would break.  I think we should add an additional step to `update_pr` to ensure that this fully qualified link to the actual doc details is generated. If we did it in a step there, we could use our existing engsys python scripts to evaluate the package and ensure the namespace dropped into the README link is actually correct. What do you think? 

@danieljurek does this simplify at all with the new ToC generation work you were pushing through? Or does the world still look the same after you're done with that.

**Comment by msyyc** [comment]
Hi @scbedd , I think using `update_pr` is good idea. But we need to very careful to avoid break current flow.^^

**Comment by danieljurek** [comment]
Where are the code samples that we want to link? 

If I'm reading correctly the scenario here is: 

1. Land on PyPI page and click on the link for examples: 
![image](https://user-images.githubusercontent.com/2158838/156069766-1ca024ab-5b1c-4c23-8f72-a0d652d4f093.png)

2. Arrive at Service Fabric's "Service-Level Overview" page: 
![image](https://user-images.githubusercontent.com/2158838/156069825-1053434e-9639-4ee3-aade-442eb83f857c.png)

Since there is no Service-Level Overview markdown file setup at this time the generated page provides links deeper into the package ref docs which can be misleading for someone looking for code samples. 

It seems that the fix here is to update [this link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicefabric/azure-servicefabric/README.md?plain=1#L13) at the package-level readme and the updated link will appear at the next release.

**Comment by scbedd** [comment]
@danieljurek exactly. Given that the readme is generated, @msyyc will need to use the functionalities from [this function](https://github.com/Azure/azure-sdk-for-python/blob/5166ee94acdb80f2217a1ce694e169ea2b33219d/eng/tox/tox_helper_tasks.py#L28) to extract a namespace from a package and generate that package link correctly.

[Usage Example](https://github.com/Azure/azure-sdk-for-python/blob/5166ee94acdb80f2217a1ce694e169ea2b33219d/eng/tox/import_all.py#L44)
