### ISSUE TITLE
A way to get event from eventhub once a time

### ISSUE THREAD

**Issue by poting-lin** [Azure/azure-sdk-for-python#22583]
**Is your feature request related to a problem? Please describe.**
currently, I implement eventhub receiver as below and working well, I can handle events in **on_event** function:
```
with client:
        client.receive(
            on_event=on_event,
            max_batch_size=100,
            starting_position="-1", 
        )
```
but it will keep receiving.

**Describe the solution you'd like**
is any way I can call the function directly to get an instant response, such as:
```
response = client.receive(
                       max_batch_size=100,
                       starting_position="-1", 
                    )
```
so the response could be an event or none?  thanks.

**Describe alternatives you've considered**
No idea

**Additional context**
No

**Comment by swathipil** [comment]
Hey @poting-lin - thanks for the question.
So, `receive` on `EventHubConsumerClient` is a blocking call which will receive forever (push mode). Unfortunately, it is not possible to receive an event per call to `receive`. 

Without knowing too much about your application, here are some things that you may find useful:
1) Utilizing the `[CheckpointStoreBlob](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/eventhub/azure-eventhub-checkpointstoreblob#checkpointing)` ([sample here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/samples/sync_samples/recv_with_checkpoint_store.py)): Checkpointing allows you to mark your position within a partition event sequence, so that you can continue consuming at the last checkpointed event.
2) Using ServiceBus: Another messaging service similar to EventHubs (which you can read more about [here]((https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus#azure-service-bus-client-library-for-python))). However, `receive_messages` on a `ServiceBusQueue` is non-blocking (pull mode), so it allows you to receive one message (or more) at a time (sample [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/receive_queue.py)).

Both of these options may not be feasible/useful for you. To try to figure out a better solution, can you provide more details about your application? Specifically:
 * Why do you want pull mode with EventHubs and why is push mode not suitable?
 * How do you interact with the received event?
 
 Thanks!

**Comment by poting-lin** [comment]
Thanks for the reply @swathipil,

the case from my side is, I would like to build an event hub receiver in Airflow, it will trigger Dags by event message, such as when the event hub receiver gets an event message: user created, it will trigger a pipeline in Airflow to run the process.

so what you mentioned in the reply is quite detailed for me, at least it guides me some possibility to solve my questions.

I will consider closing this question and thank you for the support!
