### ISSUE TITLE
request for version_id keyword argument in ContainerClient download_blob function

### ISSUE THREAD

**Issue by lilygrierjil** [Azure/azure-sdk-for-python#22742]
**Is your feature request related to a problem? Please describe.**
I'd like to download a specific version of a storage blob using the ContainerClient download_blob() function (in the azure-storage-blob package).

**Describe the solution you'd like**
The ContainerClient's delete_blob() function allows the user to specify a version_id as a keyword argument, and it would be great if the download_blob() function allowed for this same kind of version specification.

**Describe alternatives you've considered**
Perhaps there's a way to download a specific version of a blob using a client aside from the ContainerClient (and if so, do let me know!), but the most recent version of the python SDK seems to lean more heavily on the ContainerClient for accessing individual blobs.

**Additional context**

**Comment by tjprescott** [comment]
@tasherif-msft can you please take a look?

**Comment by jalauzon-msft** [comment]
Hi @lilygrierjil,

You are correct that currently the `ContainerClient` does not document that it supports `version_id` however `donwload_blob()` on a `BlobClient` does have a keyword parameter for `version_id`. See [here](https://github.com/Azure/azure-sdk-for-python/blob/a5ea4bf7d0decafbe355467ddb0bdd334b9f953b/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L777).

So, I think there are two options for what you would like to do:
- Create a `BlobClient` from your `ContainerClient` and call `download_blob()` on that blob client passing the `version_id`.
- Or you should be able to just pass `version_id` to the `ContainerClient.download_blob()` as a keyword argument, even though it is not documented, and since `ContainerClient.download_blob()` calls `BlobClient.download_blob()` and passes through the `kwargs`, it should work.

NOTE: This `version_id` argument is only supported after version 12.4.0.

Hope that helps. Please let me know if these suggestions do not work for you.

**Comment by jalauzon-msft** [comment]
I've created a PR to add the missing documentation and linked it here.
