### ISSUE TITLE
Python SDK circular import error

### ISSUE THREAD

**Issue by deepak6422** [Azure/azure-sdk-for-python#22860]
I am trying to make a connection to the azure queue in Python but I am getting a circular import error.

Here's my code:
`from azure.storage.queue import (QueueClient)

connection_str =  "",

q_name = "test2"
queue_client = QueueClient.from_connection_string(connection_str, q_name)
queue_client.create_queue()`

Error I am getting:
`from azure.storage.queue import (QueueClient)
ImportError: cannot import name 'QueueClient' from partially initialized module 'azure.storage.queue' (most likely due to a circular import) (/home/deepak/azure-env/lib/python3.8/site-packages/azure/storage/queue/__init__.py)`

**Comment by swathipil** [comment]
Hi @deepak6422 - thanks for your question! We'll investigate asap!

**Comment by deepak6422** [comment]
@swathipil Any updates on this issue?

**Comment by swathipil** [comment]
Hey @tasherif-msft - would you be able to take a look at this?

**Comment by tasherif-msft** [comment]
Hi @deepak6422 we will investigate this asap and update you!
thanks for your patience

**Comment by jalauzon-msft** [comment]
Hi @deepak6422, we are having difficulty reproducing this issue. Would you mind sharing the following information so we can try and narrow it down?

- OS version
- Queue package version
- How are you installing the package? Are you using either `conda` or `virtualenv` and are you using `pip` to install?
- Do you have any other azure packages installed in the same env? (Besides the dependencies for Queue)

**Comment by deepak6422** [comment]
@jalauzon-msft Sure. 
OS Version - Ubuntu 20.04
Queue package version - 12.1.6
I have installed the queue package inside a virtual env.
No, I don't have any other azure packages installed.

**Comment by jalauzon-msft** [comment]
Hi again @deepak6422, thanks for the info and apologies for the delay! We are still looking into this and trying to reproduce the issue.

I think our next step is to try and exactly re-create your environment on our end to see if we can reproduce the issue. For that could you please share the following:
- Python version (both global and venv if they are different)
- The output of `pip list`

**Comment by deepak6422** [comment]
hey @jalauzon-msft  I figured out the issue. It was due to the file name which was queue.py. 
I think python causes this circular import error for any modules if their file name matches with the modules package file name.

**Comment by jalauzon-msft** [comment]
Hi @deepak6422, thanks for following up on this. It looks like this was indeed the cause as I was able to reproduce this on our end by naming the file `queue.py`. Interestingly this is not actually conflicting with our module since it's called `azure.storage.queue` but instead with one of our dependencies, `six` (used by `urllib`). They have a module named `queue` which is causing this error. Unfortunately, there is not a lot we can do about that right now so just using a different file name is probably the best solution.

Thanks again for helping to find this. We can now recommend others against that file name if we see this issue in the future.
