### ISSUE TITLE
[azure-mgmt-network] Delete operation on non-existent NSG securityrule returns "Successful"

### ISSUE THREAD

**Issue by twacn** [Azure/azure-sdk-for-python#22934]
- **Package Name**: azure.mgmt.network.NetworkManagementClient.security_rules.begin_delete
- **Package Version**: 2020-06-01
- **Operating System**: Linux, macOS
- **Python Version**: 3.9.7

**Describe the bug**
Performing a NetworkManagementClient.security_rules.begin_delete does not return an error when the rule does not exist.  

I confirmed that the Azure CLI responds in the same manner.

**To Reproduce**
1. Instantiate a NetworkManagementClient instance, `nmclient`
2. Call `nmclient.security_rules.begin_delete` using a valid subscription_id, nsg_name, and resource_group name, but use a non-existent rule name
3. The call will return a status of "Successful" and a result of `None`

**Expected behavior**
The Azure REST API, https://docs.microsoft.com/en-us/rest/api/virtualnetwork/security-rules/delete, the delete operation returns a 204 if the resource does not exist. I expected that the Python SDK would do the same to provide feedback that the delete operation didn't truly "Succeed", but rather was not able to perform the requested operation. 

This could be indicated with either an alternative `status` value or a flag in `result` .

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by kazrael2119** [comment]
Hello @twacn ,After my attempt, I found that whether the rules already exist or not, begin_ delete will return the status value of 204. But when you have created this rule, begin_ delete can indeed delete it. So I don't think this should be the problem of SDK. Moreover, in our opinion, there is no difference between the three status values of 200，202，204. We can get the result that the rule is deleted in the end without reporting an error. This is due to the design. Most delete operations are like this. If you want to change it, it's the architecture, so if you have any questions, you may visit 'https://github.com/Azure/azure-rest-api-specs/issues’ to publish this issue
