### ISSUE TITLE
how can i write hive sql in this sdk?

### ISSUE THREAD

**Issue by wuyazi** [Azure/azure-sdk-for-python#230]
1. this TableService is NoSql, how can i execute hive sql use this sdk.

  i find 'Submit Hive jobs using HDInsight .NET SDK' at 
  http://azure.microsoft.com/en-us/documentation/articles/hdinsight-submit-hadoop-jobs-programmatically/
  can python sdk do this?
2. and how can i see the table file in FileBrowser， 
like * \  *\  hive \  warehouse \  hivesampletable \  hivesampletable.txt

**Comment by lmazuel** [comment]
Hi, sorry for the late answer, but we were not expert in HiveSQL :(
The final answer I got from a Python user, is to upload your script with Hive SQL into a storage account blob, and then use WebHCat RestAPI calls (directly with `requests`, since there is no Python SDK) to launch your script.
I hope this helps, feel free to open a new issue if you have a problem.

This might be useful too:
https://azure.microsoft.com/en-us/documentation/articles/hdinsight-python/
