### ISSUE TITLE
Cosmos async operations produces aiohttp error - unexpected keyword argument `loop`

### ISSUE THREAD

**Issue by Miroslaw94** [Azure/azure-sdk-for-python#23007]
- **Package Name**: azure-cosmos
- **Package Version**: 4.3.0b2
- **Operating System**: macOS 12.1
- **Python Version**: 3.8.9

**Describe the bug**
I wanted to test new async functionalities of azure-cosmos package but I'm getting an error: 
```
System.Private.CoreLib: Exception while executing function: Functions.my_func_name. System.Private.CoreLib: Result: Failure
Exception: TypeError: __init__() got an unexpected keyword argument 'loop'
```
end of traceback:
```
File "/Users/me/.local/share/virtualenvs/azure_functions-gQWEzaNU/lib/python3.8/site-packages/azure/core/pipeline/_base_async.py", line 116, in send
     await self._sender.send(request.http_request, **request.context.options),
   File "/Users/me/.local/share/virtualenvs/azure_functions-gQWEzaNU/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 195, in send
     await self.open()
   File "/Users/me/.local/share/virtualenvs/azure_functions-gQWEzaNU/lib/python3.8/site-packages/azure/core/pipeline/transport/_aiohttp.py", line 100, in open
     self.session = aiohttp.ClientSession(
```

I checked that line in `_aiohttp.py` file and there is an initialization of `aiohttp.ClientSession` with `loop` argument but `aiohttp.ClientSession` doesn't have that argument in __init__(). The documentation of `aiohttp` says passing `loop` argument to `ClientSession` was deprecated in version 2.0.0 (the most current version is 3.8.1). 

**To Reproduce**
```python
from azure.cosmos.aio import CosmosClient

cosmos_client = CosmosClient("URL", credential="KEY")
db_client = cosmos_client.get_database_client("DB_NAME")
pos_container = db_client.get_container_client("CONTAINER_NAME")
await pos_container.upsert_item(body=my_item)

# This one produces the same error:
await pos_container.create_item(body=my_item)
```

**Expected behavior**
The same code in standard (non-async) version works well, so I expect to be able to use async version without getting an error. 

**Additional context**
Versions of libraries which I use:
```
aiohttp = "3.8.1"
azure-core = "1.22.1"
azure-cosmos = "4.3.0b2"
```

**Comment by simorenoh** [comment]
Hi @Miroslaw94, thank you for raising this issue with us.

I'm not sure exactly what is happening here since the aiohttp package is not managed by us, but I would recommend you take a look at the way our async samples are set up in order to see the recommended way of using the async client. On one point for instance, in order to use the `await` keyword you'd generally need to have that in a function. With the code you provided above I was unable to reproduce your issue (fails when not in a function due to await keyword, succeeds otherwise). 

If following the formatting in the async samples doesn't work, do let me know and we can see what's wrong then. Thank you!
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cosmos/azure-cosmos/samples

**Comment by lmazuel** [comment]
Hi @Miroslaw94 

I do see `loop` in the init of 3.8.1 aiohttp:
https://github.com/aio-libs/aiohttp/blob/v3.8.1/aiohttp/client.py#L201

But I agree `loop` is deprecated, so this is a ticking bomb, and our code is not ready for that. It has even been removed from Python itself starting 3.10. I created a bug for that one:
https://github.com/Azure/azure-sdk-for-python/issues/23196

But again, this should not cause your problem, since aiohttp 3.8.1 stills has it. Could you share your entire stacktrace?
