### ISSUE TITLE
Blob query has limited SQL interpretation

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [Azure/azure-sdk-for-python#23159]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.9.0
- **Operating System**: Linux
- **Python Version**: 3.8.8

**Describe the bug**
When using BlobClient.query_blob the process does not return when using aggregate functions in SQL such as min, max, avg. Similarly does not return when using as within the column names.

**To Reproduce**
1. Make query to a blob using "SELECT _1 as column FROM BlobStorage"
or
"SELECT AVG(_1) FROM BlobStorage"
2. The process just times out and we an error returned.

**Expected behavior**
For it to return the the data as requested.

**Additional context**
The documentation for this function isn't the best about what queries we are allowed.

**Comment by jalauzon-msft** [comment]
Hi @AWendland-CryptoCompare Alex, you are correct that this API is not well documented from the client, and it is also a bit picky. This service documentation is a good reference for what is/is not supported.
https://docs.microsoft.com/en-us/azure/storage/blobs/query-acceleration-sql-reference

I was able to get `AS` to work with column names so I believe that is supported. The service seems to be pretty picky about the names you use, however. In your example `column` is a SQL keyword which causes the service to throw an error. Please try using a different name as your column name and I think it should work.

That being said, I was also not able to get certain aggregate functions to work as well. It seems that `COUNT` and `SUM` work but I was not able to get `AVE`, `MIN`, or `MAX` to work. This is likely just a limitation the service has rather than a client-side issue. I will reach out to the service team internally to clarify and report back here. Once I hear back, we will also consider ways to improve the client documentation.

**Comment by AWendland-CryptoCompare** [comment]
Hi @jalauzon-msft Jacob, thank you for looking into this. 

The documentation there is very helpful. Could this be linked to the documentation for the [query_blob](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-query-blob) function? 

Sorry about my poor knowledge of SQL, I believe when I tried as previously I used names such as 'price' and 'quantity' but I will have another go.

Thanks for asking about the aggregate functions, this would really help us.

**Comment by jalauzon-msft** [comment]
Hi @AWendland-CryptoCompare Alex, I've heard back from our service team and have some updates.

It looks like using `AS` to rename columns in not officially supported. It does seem to work in some cases but that is not an intended feature. You could either provide the column names in your file as a header and use the `has_header=True` parameter to have them read in or you can rename them after the data comes back. 
NOTE: If you wish to sepcify column names in your query, it is advised to escape them using `"` (this was tripping me up in my testing). Something like `SELECT \"Value\" FROM BlobStorage`

As for the aggregate functions, it turns out all of them listed in [the doc](https://docs.microsoft.com/en-us/azure/storage/blobs/query-acceleration-sql-reference#aggregate-expressions) are supported.
NOTE: `AVERAGE` should be `AVG`. The service team is working on correcting the doc.

I believe the issues you were seeing were due to the fact that, with CSV data, all columns are read as strings by default. See [here](https://docs.microsoft.com/en-us/azure/storage/blobs/query-acceleration-sql-reference#data-types)
```
When reading values from CSV-formatted data, all values are read as strings. String values may be converted to other types using CAST expressions.
```

This means, to perform an aggregate function, you need to use a `CAST` so something like:
```sql
SELECT AVG(CAST(_2 AS INT)) FROM BlobStorage
```

Hope that helps! Let us know if you have any other questions.

**Comment by AWendland-CryptoCompare** [comment]
Hi @jalauzon-msft Jacob, thank you for looking into this. It is really helpful to know all this.

The only thing would be for this information to be more discoverable, as I previously mentioned linking it to the query_blob function in the [documentation](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-query-blob) would help users like me.
