### ISSUE TITLE
Unable to Install Azure CLI ML Extension

### ISSUE THREAD

**Issue by mkrdip** [Azure/azure-sdk-for-python#23187]
- **Package Name**: azure-cli-ml
- **Package Version**: 
- **Operating System**: macOS
- **Python Version**: 3.10

**Describe the bug**
Unable to install Azure ML CLI extension on macOS with M1.

**To Reproduce**
1. Install Azure CLI as described here: [Install Azure CLI on macOS](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-macos)
2. Try installing Azure ML CLI extension by running: `az extension add --name azure-cli-ml`

**Expected behavior**
A successful install as another extension e.g. `az extension add --name azure-iot` got installed fine.

**Error Messages**

```
Failed to delete '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml'. Retrying ...
Failed to delete '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml'. Retrying ...
Failed to delete '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml'. Retrying ...
Failed to delete '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml': [Errno 2] No such file or directory: '/Users/mrinal.roy/.azure/cliextensions/azure-cli-ml'. You may try to delete it manually.
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

**Comment by annatisch** [comment]
Thanks for the report @mkrdip!
Unfortunately it looks like this issue is more related to the CLI rather than the underlying Azure SDK.
I would recommend opening your issue at the Azure CLI repo where they should be able to assist:
https://github.com/Azure/azure-cli

I'll close this issue for now - but if during debugging you find any errors being triggered from the SDK underneath, please reopen the issue and we'll make sure to route it to the correct team :)
