### ISSUE TITLE
[BUG] Unable to connect to Storage from IoT Edge Device

### ISSUE THREAD

**Issue by UtkarshShrivastava16** [Azure/azure-sdk-for-python#23256]
### Library name and version

Azure.Storage.Blob 12.9.0

### Describe the bug

I was trying to connect with the [local blob storage for IOT Edge device](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2018-06) using python SDK.
This is my code:

```
import os, uuid
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

try:
    connect_str = '<local_blob_storage_connection_string>'
    # Create the BlobServiceClient object which will be used to create a container client
    blob_service_client = BlobServiceClient.from_connection_string(connect_str)
    # Create the container
    container_client = blob_service_client.get_container_client('report-update-test')
    blobs_list = container_client.list_blobs()
    for blob in blobs_list:
       print(blob.name, blob.size)

except Exception as ex:
    print('Exception:')
    print(ex)
```

I created the local connection string as follows:
`DefaultEndpointsProtocol=https;BlobEndpoint=<myBlobEndpoint>;AccountName=<myAccountName>;AccountKey=<myAccountKey>`

Here <myBlobEndPoint> was defined as follows:
`http://<local blob module name>:11002/<account name>`

I am unable to identify why the code doesn't run correctly and gives an Exception as follows:
```
Exception:
<urllib3.connection.HTTPConnection object at 0x7fb4d226d8>: Failed to establish a new connection: [Errno -2] Name or service not known
```

### Expected behavior

The code should enlist the blob names and their file sizes respectively.

### Actual behavior

Exception occurs as follows:
```
Exception:
<urllib3.connection.HTTPConnection object at 0x7fb4d226d8>: Failed to establish a new connection: [Errno -2] Name or service not known
```

### Reproduction Steps

1. Create an IoT Edge device in IoT Hub.
2. Create a local blob storage module on the edge device using the following [tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-blob?view=iotedge-2020-11#deploy-from-the-azure-portal). 
3. Connect with the blob storage module using the above python code within the edge device.

### Environment

ARM 64 System with the OS as L4T for nvidia arm64 devices. IoT edge version 1.1.8.

**Comment by yunhaoling** [comment]
thanks @UtkarshShrivastava16 for reaching out. We'll investigate it ASAP.

**Comment by jalauzon-msft** [comment]
Hi @UtkarshShrivastava16 Utkarsh, this is likely an issue with Storage on IoT Edge devices that is not specific to Python. Adding @amishra-dev and @jaschrep-msft to have a look.

**Comment by jaschrep-msft** [comment]
> Here was defined as follows:
> `http://<local blob module name>:11002/<account name>`

While I am unfamiliar with Python SDK internals, this is url structure is giving me concern. The SDK currently expects account names to be in the host, not the path, as that is how the Storage service is organized. Technically, you can just construct a client with any URI and the SDK will assume you got it right, but when you start traversing clients (e.g. going from a service client to a container client) the SDK behaves as if its URI expectations have been met and manipulates it as such.

I would encourage you to observe HTTP requests going across your wire and see what urls requests are actually being sent to. I have a feeling moving to a container client could be wiping the account name from the path, as the SDK expects a container name to be the root path segment, not the account name.

**Comment by jalauzon-msft** [comment]
Hi @UtkarshShrivastava16 Utkarsh, are you still experiencing this issue? I did some verification of what James had mentioned above and it does seem like the SDK *should* support traversing clients with this form of endpoint so I think you may just have a configuration issue with your IoT device or the like.

If you are still experiencing the issue, here are some things to check:
- Did you verify you are using the correct endpoint based on your scenario as documented [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2018-06#connect-to-your-blob-storage-module)? For example, are you using the correct endpoint based on your network setup (or running locally)?
- Can you try replacing the `DefaultEndpointsProtocol=https` with `DefaultEndpointsProtocol=http` (http instead of https) in your connection string since the endpoint URL you are using is using `http`? I don't think this should make a difference but a good thing to check.
- Have you verified your Storage on IoT setup is working correctly via any other means? Perhaps you could try with Storage Explorer to see if everything is configured correctly. [Documentation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2018-06#connect-to-your-local-storage-with-azure-storage-explorer).
