### ISSUE TITLE
Key vault authentication error retrieving first secret

### ISSUE THREAD

**Issue by Ellebaek** [Azure/azure-sdk-for-python#23252]
From an Azure Data Science Virtual Machine I'm able to retrieve secrets from my key vault, but retrieving the first secret always produces an 401 authentication error in the key vault log. Very confusing, since the Python script seems to run flawless and no exception reaches the Python environment.

### Example from log:
{ "time": "2022-03-01T12:16:03.1306734Z", "category": "AuditEvent", "operationName": "Authentication", "resultType": "Success", "correlationId": "[an id]", "callerIpAddress": "[my ip]", "identity": {}, "properties": {"clientInfo":"azsdk-python-keyvault-secrets/4.2.0 Python/3.7.9 (Windows-10-10.0.17763-SP0)","subnetId":"/subscriptions/[another id]/resourcegroups/[one resource group]/providers/microsoft.network/virtualnetworks/[my virtual net]/subnets/[my subnet]","httpStatusCode":401,"requestUri":"https://[my-key-vault].vault.azure.net/secrets/**[my-first-secret]**/?api-version=7.1"}, "resourceId": "/SUBSCRIPTIONS/[another id]/RESOURCEGROUPS/[another resource group]/PROVIDERS/MICROSOFT.KEYVAULT/VAULTS/[MY-KEY-VAULT]", "operationVersion": "7.1", "resultSignature": "Unauthorized", "durationMs": "38"}

### Sample code
`from azure.identity import ManagedIdentityCredential
from azure.keyvault.secrets import SecretClient

credential = ManagedIdentityCredential()
secret_client = SecretClient(vault_url="https://[my-key-vault].vault.azure.net/", credential=credential)
__first_secret = secret_client.get_secret("my-first-secret").value
__second_secret = secret_client.get_secret("my-second-secret").value
__third_secret = secret_client.get_secret("my-third-secret").value`

The error caught my attention since it is visible in the "Key vault -> Insight" page in the tab "Failures":
![image](https://user-images.githubusercontent.com/11288859/156181551-05f77e16-e8e6-40ab-860a-caf15947a53e.png)

Miniconda environment (Python 3.7.9):
 - azure-keyvault-secrets==4.2.0
 - azure-identity==1.5.0

(pip installed)

**Comment by yunhaoling** [comment]
thank @Ellebaek for reaching out, we'll investigate it ASAP.

**Comment by xiangyan99** [comment]
@mccoyp Could you take a look?

**Comment by josiahlaivins** [comment]
I am getting a similar/identical(?) issue. The same code works for my home lan, but fails in a different location (sometimes). I am seeing authentication errors in the app insights also. The credentials worked fine yesterday. The error:
```
Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```
Which isn't true since I'm seeing auth errors in the cloud. I also tried the credentials using regular az login and they work. Is there a DNS flush that needs to happen?

**Comment by mccoyp** [comment]
Hi @Ellebaek, thank you for opening an issue! Seeing a 401 response on your first service request is expected because Key Vault uses challenge-based authentication. For example, our test recordings will show a [`401 Unauthorized` response](https://github.com/Azure/azure-sdk-for-python/blob/a7e3bf4ece801e49f3cfcf7e098881326a731158/sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_crud_operations_7_2.yaml#L19), which includes [auth challenge details](https://github.com/Azure/azure-sdk-for-python/blob/a7e3bf4ece801e49f3cfcf7e098881326a731158/sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_crud_operations_7_2.yaml#L38), at the start of each test.

When we don't have a cached challenge for a request URL, the first service request won't include an access token. This prompts the `Unauthorized` error, from which we can fetch details to get a token and authorize future requests. The exception isn't raised by the SDK because we expect this interaction and silently handle the error.

**Comment by Ellebaek** [comment]
Thank you all for looking into this. Sounds like a reasonable explanation. However, I still consider it confusing it appear as an error in the Key Vaults insights page in the portal.

**Comment by mccoyp** [comment]
@sebansal Do you know if the service team would be able to take a look at this? Hiding expected errors sounds like a reasonable request, though I'm not sure how doable it would be.
