### ISSUE TITLE
[linter] don't allow people to alias

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-python#23324]
When SDK writers alias model names to rename the generated code, i.e. `from ._generated import AuthenticationTypeEnum as DatasourceAuthenticationType`, this breaks apiview, sphinx documentation, and does not show up well for end users

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/43154838/156662964-9eb89095-e331-4bdd-abab-643427d042ae.png)

We should look through the `__init__` files and raise an error if the aliased name is included in the `__all__` (it's ok if internal models are aliased) and ensure there is no `x as x` importing.

We want to see how many aliasing issues we are running into.

In terms of mitigation for aliasing cases (thanks @lmazuel ):
1. If handwritten code: don't do it, you don't need it
2. If rename generated: use directive
3. Else: talk to Johan/Anna

**Comment by lmazuel** [comment]
There is many solutions to avoid this problem:
- Create an handcrafted class with from_generated/to_generated
- Rename the Swagger. Even a directive if necessary, so the name is right.
- Inherit the internal class:
```python
class NewName(OldName):
   pass
```

But the nbame alias is confusing for all automation, since this is a local name alias in the SDK code, and doesn't reflect nicely in outside code.
