### ISSUE TITLE
azure-storage-file-datalake AIO capability not working

### ISSUE THREAD

**Issue by afogarty85** [Azure/azure-sdk-for-python#23513]
- **azure-storage-file-datalake --pre**: 
- **12.5.0**: 
- **Windows 10**:
- **3.8**: 

**Describe the bug**
The `AIO` version runs no faster than without AIO

**To Reproduce**
```
# get AAD credential
credential = ClientSecretCredential(TENANT, CLIENTID, CLIENTSECRET)
# get access to ADLS
datalake_service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
    "https", 'lakefs'), credential=credential)

# file system client
file_system_client = datalake_service_client.get_file_system_client("lakefs")
# paths
paths = file_system_client.get_paths(path="/loc_of_interest")
# begin work
async with datalake_service_client:
    pathing = []
    async for path in paths:
        pathing.append(path.name)
```

**Expected behavior**
AIO-level speed.

**Screenshots**
N/A

**Additional context**
Contrast this with the same method for blob storage (which actually works) in terms of speed:

```
from azure.identity.aio import ClientSecretCredential
from azure.storage.blob.aio import BlobServiceClient
from azure.storage.blob.aio import ContainerClient
token_credential = ClientSecretCredential(TENANT,
                                          CLIENTID,
                                          CLIENTSECRET)

service = BlobServiceClient(account_url="https://blob_of_interest.blob.core.windows.net/", credential=token_credential)
container_client = service.get_container_client("folder_of_interest")

async with service:
    blobs_list = []
    async for blob in container_client.list_blobs():
        blobs_list.append(blob)
len(blobs_list)

```

**Comment by vincenttran-msft** [comment]
Hi @afogarty85 Andrew, thanks for your inquiry! Just to clarify, are you comparing the `azure-storage-file-datalake` asynchronous performance against the `azure-storage-blob` asynchronous performance or is your context referring to `azure-storage-blob` asynchronous performance being greater than it's synchronous counter-part, and that this performance gain is not present in the `azure-storage-file-datalake` library?

For the former case, it is expected behavior that `azure-storage-file-datalake` is slower than `azure-storage-blob` as there is more overhead in the `DataLake` library due to its increased complexity.

For the latter case, further investigation is required and we will get back to you when we have an update.

Thanks!
