### ISSUE TITLE
Can we add Address space using some API or SDK "WITHOUT" deleting the Peerings.

### ISSUE THREAD

**Issue by ankitmounty2008** [Azure/azure-sdk-for-python#23590]
A current feature which allows you to add CIDR without deleting peering from the portal but is there any SDK or API available to do the same? I tried begin_create_or_update but it doesn't work if peering exists. 
The second part of this activity will be to resync peering and I could find a REST API to resync peering but what I need is to add CIDR without deleting the peering.

**Comment by kashifkhan** [comment]
Hi @ankitmounty2008, thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by BigCat20196** [comment]
Hi @ankitmounty2008, thanks for the feedback. There is no denying that this is a good proposal. But the order is reversed, because Python SDK is automatically generated based on [RestAPI](https://github.com/Azure/azure-rest-api-specs). Please go [here ](https://github.com/Azure/azure-rest-api-specs/issues)to open this problem. Thanks!
