### ISSUE TITLE
Cannot configure HTTP proxy in `azure-keyvault-secrets` 

### ISSUE THREAD

**Issue by lundholmx** [Azure/azure-sdk-for-python#23623]
- **Package Name**: azure-keyvault-secrets
- **Package Version**: 1.22.1
- **Operating System**: linux
- **Python Version**: 3.9.7

**Describe the bug**
According to [this](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-configure-proxy?tabs=bash#global-configuration) documentation it should be possible to configure proxies globally by using the `HTTP*_PROXY` environment variables.

However, they do not seem to have any effect on `azure.keyvault.secrets.SecretClient`. Instead the request to KeyVault just hangs.

**To Reproduce**
```python
def get_secret():
    credential = DefaultAzureCredential()
    secret_client = SecretClient(vault_url="...", credential=credential)
    v = secret_client.get_secret("mysecret").value
    print(f"My secret: {v}")
```

The code snippet does work in an environment without a corporate proxy.

**Expected behavior**
To be able to configure proxy according to the documentation.

**Comment by kashifkhan** [comment]
Hi @lundholmx , thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by mccoyp** [comment]
Hi @lundholmx, thank you again for opening an issue! I apologize for the delayed response.

@xiangyan99 proxy support comes from `azure-core`, and it seems like the base client for `SecretClient` is [using RequestsTransport](https://github.com/Azure/azure-sdk-for-python/blob/c39db1cc0d9b4a97cce086b8d040acdfcbda6988/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py#L59) in a way that should support this scenario. Do you have any ideas as to what could be happening here?

**Comment by xiangyan99** [comment]
For sync code, we use requests library underneath.

Could you just try

```py
requests.get('http://bing.com')
```

to see if it works?

**Comment by lundholmx** [comment]
> @xiangyan99 proxy support comes from `azure-core`, and it seems like the base client for `SecretClient` is [using RequestsTransport](https://github.com/Azure/azure-sdk-for-python/blob/c39db1cc0d9b4a97cce086b8d040acdfcbda6988/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py#L59) in a way that should support this scenario. Do you have any ideas as to what could be happening here?

We saw that in the source code and also thought the default settings would support proxy (ultimately via `requests.Session` if we understand it correctly). We also tried setting the transport on `SecretClient` explicitly without success.

**Comment by lundholmx** [comment]
> For sync code, we use requests library underneath.
> 
> Could you just try
> 
> ```python
> requests.get('http://bing.com')
> ```
> 
> to see if it works?

That actually works, and other libraries using `requests` underneath seem to pickup the proxy configuration correctly from environment variables as well.

**Comment by mccoyp** [comment]
Hi @lundholmx, thank you for confirming that `requests` is at least picking up the configuration correctly. Have you seen other SDK clients successfully make requests with a proxy, if you're using anything other than a `SecretClient`?

**Comment by lundholmx** [comment]
> Hi @lundholmx, thank you for confirming that `requests` is at least picking up the configuration correctly. Have you seen other SDK clients successfully make requests with a proxy, if you're using anything other than a `SecretClient`?

I don't think so. Any suggestion that may work or that I can try with?

**Comment by mccoyp** [comment]
@lundholmx if you have a Storage account, using something like a `ContainerClient` to do something simple -- for example, [creating a container](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob#create-a-container) -- might be a good way to test it out. If you only own a Key Vault, you could also try using other KV clients, like a `KeyClient` from `azure-keyvault-keys` or `CertificateClient` from `azure-keyvault-secrets`. I would be really surprised to see different behavior from any KV client though, since they all use the same base client logic.

I'll set up a proxy server tomorrow to try to reproduce this in the meantime. I haven't yet found why the proxy configuration wouldn't work, but stepping through a live process will help more than visual inspection.

**Comment by mccoyp** [comment]
Hi @lundholmx -- as an update on this, I was able to use a proxy server (specifically, PortSwigger's [Burp Proxy](https://portswigger.net/burp/documentation/desktop/tools/proxy)) to call `SecretClient.get_secret` successfully. I'm wondering if this issue could for some reason be related to the specific proxy configuration you're trying to use, even though it would be a bit surprising since you were able to call `requests.get('http://bing.com')` without a problem.

Would you be able to try your code with another proxy, like the one used by [Burp Suite Community Edition](https://portswigger.net/burp/communitydownload)?

**Comment by lmazuel** [comment]
Additional thoughts @mccoyp @xiangyan99 
- We should split the problem into identity and KV. Can @lundholmx even get a token?
- We should try with the `proxies` kwarg on both: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core#configurations. Maybe it's just env variables issue, and the kwarg work
- Enable DEBUG and check where it is stuck more precisely

**Comment by xiangyan99** [comment]
@lundholmx as Laurent suggested, let's try separate the issue. Can you try the code:

```py
credential = DefaultAzureCredential()
token = credential.get_token("https://vault.azure.net/.default")
print(token)
```
?

This will verify if you can get token successfully (if identity library works correctly or not).

Thanks.
