### ISSUE TITLE
TokenCachePersistenceOptions not retrieving cached token from keychain on macOS?

### ISSUE THREAD

**Issue by flixman** [Azure/azure-sdk-for-python#23620]
- **Package Name**: azure-identity
- **Package Version**: 1.8.0
- **Operating System**: macOS 12.3
- **Python Version**: 3.10

**Describe the bug**
Running ```InteractiveBrowserCredential(cache_persistence_options=TokenCachePersistenceOptions())``` twice results in two authentication requests.

**To Reproduce**
1. Execute twice the following code
```python
from azure.keyvault.secrets import SecretClient
from azure.identity import InteractiveBrowserCredential, TokenCachePersistenceOptions

tenant_id = <valid tenant_id>
vault_uri = <valid vault_uri>
secret_name = <valid secret_name>
secrets = SecretClient(vault_uri, InteractiveBrowserCredential(tenant_id=tenant_id, cache_persistence_options=TokenCachePersistenceOptions()))
print(secrets.get_secret(secret_name).value)
```

**Expected behavior**
The first time this is script is run, authentication is required. Any subsequent run uses the previously valid token.

**Comment by kashifkhan** [comment]
Hi @flixman , thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by flixman** [comment]
@xiangyan99 Absolutely, I have both files ready. How can I share them with you?

**Comment by xiangyan99** [comment]
You can send it to xiangyan@microsoft.com

**Comment by xiangyan99** [comment]
@flixman Thanks for the feedback.

I double checked the expected behavior of 

```py
InteractiveBrowserCredential(tenant_id=tenant_id, cache_persistence_options=TokenCachePersistenceOptions())
```

If we only specify the tenant_id, there could be thousands of different clients in that tenant and InteractiveBrowserCredential does not have enough information to know which one to use. Hence, on the second time you run the code, it pops up the browser to ask you to sign in again.

In order to use the TokenCache, you need to get the auth_record and pass the auth_record when creating the second InteractiveBrowserCredential. The code snippet is like:

```py
cred = InteractiveBrowserCredential(tenant_id=tenant_id, cache_persistence_options=TokenCachePersistenceOptions())
token = cred.get_token(YOUR_SCOPE)
auth_record = cred.authenticate()
cred1 = InteractiveBrowserCredential(tenant_id=tenant_id,
                                         cache_persistence_options=TokenCachePersistenceOptions(),
                                         authentication_record=auth_record)
token1 = cred1.get_token(YOUR_SCOPE)
```

Please let us know if it works.

Thanks.
