### ISSUE TITLE
ResourceWarning: unclosed transport

### ISSUE THREAD

**Issue by Nolent** [Azure/azure-sdk-for-python#23645]
- **Package Name**: azure.storage.blob
- **Package Version**: tested with 12.9.0 and 12.10.0
- **Operating System**: Debian Bullseye
- **Python Version**: 3.9.2

**Describe the bug**
We get a ResourceWarning even when using BlobServiceClient as a context manager
```
Exception ignored in: <function _SelectorTransport.__del__ at 0x7f488aa8c050>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 704, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: unclosed transport <_SelectorSocketTransport fd=12>
Exception ignored in: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.10.24.34', 57330), raddr=('52.239.134.100', 443)>
ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.10.24.34', 57330), raddr=('52.239.134.100', 443)>
```

**To Reproduce**
```python
from azure.storage.blob.aio import BlobServiceClient

from warnings import filterwarnings

filterwarnings('error')
async with BlobServiceClient(
    account_url=f"https://{ accountName }.{ accountDomain }/",
    credential=accountKey
) as serviceClient:
    async with serviceClient.get_container_client(accountName) as container:
        await container.exists()
```

**Expected behavior**
We should not have a warning here

**Comment by kashifkhan** [comment]
Hi @Nolent  , thanks for the feedback. We'll take a look at this and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @Nolent Hebert, it looks like this is a known issue with the underlying async library `aiohttp` and is documented [here](https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown). That being I said, I did try their workaround of adding `loop.run_until_complete(asyncio.sleep(0.250))` and it did not help with the warning (I also tried much higher sleep values just in case).

Since this is an issue with the underlying library and likely not specific to Storage, I'm going to redirect this to someone who works with `azure-core` as they may be able to better assist.

**Comment by xiangyan99** [comment]
Could you tell us which is the type of accountKey? (e.g. Is it a string? or a azure.identity.TokenCredentials? or None?

Thank you.

**Comment by Nolent** [comment]
Hello, sorry for the wait.
Account key is a `str`.

**Comment by jalauzon-msft** [comment]
Hi @xiangyan99, I was hoping to get some help from someone who works on Core on this since the Blob clients just call the generated client's `__aexit__` so I don't think the issue is specific to `azure-storage-blob`.
https://github.com/Azure/azure-sdk-for-python/blob/b0f9e02b2d597a57dcef33bb265c4b5c47ad0a85/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client_async.py#L59-L60

Is this something anyone has seen in other packages, or do you have insight into what might be going wrong here? I have verified we do get this warning despite testing with the workaround that `aiohttp` suggests [here](https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown). Any help would be appreciated, thanks!

**Comment by xiangyan99** [comment]
I instrumented the code and seemed like aiohttp session was successfully closed.

Also, I cannot reproduce the issue in other service libraries. (IIRC, that was the reason I assigned the issue back to you 3 months ago)

Feel free to ping me and we can investigate further offline. @jalauzon-msft

**Comment by xiangyan99** [comment]
And it is possible because of this https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=unclosed#graceful-shutdown.
