### ISSUE TITLE
autorest doesn't support  --sync-methods for python

### ISSUE THREAD

**Issue by tingqin2017** [Azure/azure-sdk-for-python#2374]
We would like to generate async call for our python client using autorest. It looks like the option --sync-methods=all is not working for python. The version of autorest:
AutoRest code generation utility [version: 2.0.4262; node: v7.10.0]
core       @microsoft.azure/autorest-core           2.0.4274
extension  @microsoft.azure/autorest.python         2.1.34

Could this feature be added for python generator? 
Thanks.

**Comment by annatisch** [comment]
Thanks @tingqin2017 - the async generator for Python is almost complete.
You can track progress here:
https://github.com/Azure/autorest.python/tree/async

If you wish to try out this async version of the generator, you can follow these instructions to run autorest from a fork/branch:
https://github.com/Azure/autorest/blob/master/docs/developer/autorest-extension.md

Though bare in mind that in order to run the async generated clients you will also need async supported versions of the runtime:
https://github.com/Azure/msrest-for-python/tree/async2
https://github.com/Azure/msrestazure-for-python/tree/async

**Comment by lmazuel** [comment]
I'm closing this issue, since the answer to the initial question is: we won't support `--sync-methods`, once async will be in, Autorest will generate async all the time, will not be configurable (don't see the point of making it configurable, since the async methods will auto-disabled themselves on 2.7).

You can follow the async support question here:
https://github.com/Azure/azure-sdk-for-python/issues/496

Thanks!
