### ISSUE TITLE
BlobServiceClient find_blobs_by_tags should return a reduced / empty iterator when not matching.

### ISSUE THREAD

**Issue by petoor** [Azure/azure-sdk-for-python#23883]
```
bsc = BlobServiceClient.from_connection_string("Some_connection_string)
matches = bsc.find_blobs_by_tags("ID='1' \ ID='2') 
matches.next()
```
Returns a StopIteration error today if no blob exists with the ID 1 or 2. 

We have a usecase where the tag might not exist, thus causing the entire search to fail.

Idearly find_blobs_by_tags would only return an iterator for the matching cases.

**Comment by l0lawrence** [comment]
Thanks for the feedback, we will investigate asap.

**Comment by petoor** [comment]
So I can solve my problem with the following code : 
```
    match_cases = []
    not_match_cases = []
    for case in cases:
        try:
            blob_service_client.find_blobs_by_tags(f"ID='{case}'").next()
            match_cases.append(case)
        except Exception:
            not_match_cases.append(case)
            print(f"Could not find match for {case}")
```
yielding a two lists, one of the matches and one where there is no match.
Iterating over the matches now looks like.
```
for case in match_cases:
        match = blob_service_client.find_blobs_by_tags(self.case_list_to_string([case]))
        for blob in match:
            Do your thing with the blob here
```

Apparently  find_blobs_by_tags("ID='1' \ ID='2'") is valid syntax, however the iterator will only return the first match, that is ID=1 and then never return the ID=2 cases. This should **_not_** be allowed. (This is why I have the for case in match_cases for loop and not just one big query)

The better and more beautiful way of solving this is to have an OR statement, this have been suggested two years ago https://github.com/MicrosoftDocs/azure-docs/issues/55912 and as we can see it is still not implemented : https://docs.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags#constructing-a-search-expression

**Comment by jalauzon-msft** [comment]
Hi @petoor Peter, unfortunately the service still does not support a logical `OR` for this case. It seems there has not been enough demand for this feature to make it into a release. 

That being said, I can offer a suggestion on a modification to your solution which may make it a little cleaner and avoid duplicate calls to the service for each ID. You could try using a `dict` to track your matches in the first request. Additionally, using the `list` constructor rather than `.next()` will avoid the `StopIteration` exception and just yield an empty list if there were no results. So something like this:
```python
all_matches = {}
for case in cases:
    matches = list(service_client.find_blobs_by_tags(f"ID='{case}'"))
    if len(matches) > 0:    # If you care about non-matches, you can leave out this if
        all_matches[case] = matches

for case, matches in all_matches.items():
    # Do something with matches for each case
```

Hopefully that helps a bit. Please let me know if this doesn't meet your requirements.

**Comment by jalauzon-msft** [comment]
I have made a formal, internal request to the service team to add logical `OR` in `FindBlobsByTags` as this is the second GitHub request for it. However, it is unlikely this will be prioritized anytime soon if I'm honest.

I think for now the best approach is to implement something like you had originally posted or my suggestion above.
