### ISSUE TITLE
containerclient from container url

### ISSUE THREAD

**Issue by EysteinWaade** [Azure/azure-sdk-for-python#24227]
azure-storage-blob==12.11.0

Hi,

I have problems making authorized requests using a container client based on a sas URL.

Are there any limitations on a ContainerClient initiated through from_container_url?
```   
permission = ContainerSasPermissions(read=True, write=True, delete=True, list=True)
account_key=''
account_name=''
container_name=''
sas = generate_container_sas(
        account_key=account_key,
        account_name=account_name,
        container_name=container_name,
        permission=permission,
        start=datetime.utcnow() - timedelta(hours=1),
        expiry=datetime.utcnow() + timedelta(hours=24),
    )

sas_url = 'https://' + account_name + '.blob.core.windows.net/' + container_name + '?' + sas
container = ContainerClient.from_container_url(sas_url)
container.exists()
```
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation.
RequestId:2bb3b4ac-f01e-007d-25ea-5a37c9000000
Time:2022-04-28T10:29:09.0336057Z
ErrorCode:AuthorizationFailure
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:2bb3b4ac-f01e-007d-25ea-5a37c9000000
Time:2022-04-28T10:29:09.0336057Z</Message></Error>

However, this works
```
account_key=''
sas_url = 'https://' + account_name + '.blob.core.windows.net/' + container_name
container = ContainerClient.from_container_url(sas_url, credential=account_key)
container.exists()
```

**Comment by tjprescott** [comment]
Hi @EysteinWaade thanks for your inquiry. @jalauzon-msft can you take a look at this?

**Comment by jalauzon-msft** [comment]
Hi @EysteinWaade, I believe this is caused by a permission issue rather than a URL issue. `ContainerClient.exists()` calls [Get Container Properties](https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-properties) to check for existence of the container. This is a service level operation and therefore can only be performed by the account owner ([doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-properties#authorization)). In other words, you must either use a SharedKey or an Account SAS (via `generate_account_sas`) to perform this operation.

Other operations within the container, like uploading, downloading, listing blobs, etc., should work as expected with the container client you've created in you example.

Hope that helps, thanks!

**Comment by EysteinWaade** [comment]
@jalauzon-msft
Thank you very much!
