### ISSUE TITLE
Delete_directory API could not delete folders which contain large amount of file pieces

### ISSUE THREAD

**Issue by IssacH** [Azure/azure-sdk-for-python#24421]
- **Package Name**:   azure.storage.filedatalake.DataLakeDirectoryClient
- **Package Version**: v12.10.0
- **Operating System**: Windows
- **Python Version**: python 3.9.10

**Describe the bug**

Basically when we call the delete_directory API against a folder with small amount of file pieces, it is working fine and None will be returned.

But when we call this api against a folder with large amount of file pieces, it seems that the folder is not deleted, only part of the files in the folder are deleted. (There are 5000 files in the folder, and each file is around 200K). Actually in this case the delete_directory API will return a dictionary of response headers(See snapshot). **This behavior is not well documented in** [delete_directory](https://docs.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.datalakedirectoryclient?view=azure-python#azure-storage-filedatalake-datalakedirectoryclient-delete-directory)

**To Reproduce**
Call delete_directory API in package azure.storage.filedatalake.DataLakeDirectoryClient against a folder with around 5000 files, and each file is around 200k

```python
from azure.storage.filedatalake import DataLakeServiceClient

datalake_service_client = DataLakeServiceClient.from_connection_string(self.connection_string)

file_system_client = datalake_service_client.get_file_system_client(container_name)

directory_client = file_system_client.get_directory_client(directory_name)

header = directory_client.delete_directory()

print(header)
```

**Expected behavior**
Could take one of below options, we prefer the second one:

  1. Add more descriptions to this API according to the two different behaviors mentioned above.
**2. Fix it as a bug, just delete the folder no matter how many files are contained.**

**Screenshots**
[Return value of delete_directory API against a folder with large amount of files](https://user-images.githubusercontent.com/17758420/168091899-8da262ac-c41e-4d06-a35e-9a7ea59c316e.png)

**Additional context**
According to the document of rest api(https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/delete), there is a parameter "continuation" which should be attached to the request header for the next deletion call.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by vincenttran-msft** [comment]
Hi @IssacH, sorry for the delay in response as I have been trying to reproduce your findings with no success. Looking at it from a code perspective, I absolutely agree that the documentation does need to be expanded and revised to better reflect this behavior, and possibly that we may alter the behavior of `delete_directory` to match your suggestion raised in point 2 under 'Expected behavior'. Rest assured, these points have been brought to the attention of the team and we will update you when a resolution has been reached.

With that being said, I am still having issues with reproducing your findings here, as every single test case I have thrown at the `delete_directory` API call has returned with a non-empty header, but with a `None` value for the `continuation` field of the header. If you could please provide answers to the following questions (or could provide any other information you think is useful), that would be great as I would like to be able to reproduce your exact behavior before moving forward with any possible code changes.

1. What version of `azure-storage-file-datalake` was used when running into this behavior? _you have v12.10.0 listed, but the most recent version is v12.7.0 so I believe that was a typo?_
2. What version of `azure-storage-blob` was used when running into this behavior?
3. Any other information that may help me reproduce your behavior?

You also have mentioned here that you are calling `delete_directory` on a directory of 5,000 files with each file being approximately 200kb, but I have tried the following combinations with no success:

- 5,000, 6,000, and 8,000 files with each file being approx. 13kb
- 5,000, 5,500, and 9,000 files with each file being approx. 200kb (205.08KiB to be exact)

Again, sorry for the delay, but we really appreciate your feedback and hopefully can come to a resolution together.
Thanks!

**Comment by vincenttran-msft** [comment]
Hi @IssacH, after some more investigating and pulling in some SME from the team, I was able to reproduce your issue. I believe that you are running into this issue as DataLake operations are intended to be used on an HNS-enabled account (hierarchical namespace), but some operations may still work on flat namespace accounts (but are **not** officially supported by the SDK).

With that being said, our plan going forward is to improve the documentation as it may be misleading to some customers, but again your issue is related to using a flat namespace account with DataLake, which is **not** an officially supported workflow by the SDK.

If you are able to switch to an HNS-enabled account for your use-case, then the `delete_directory` API will always completely delete the folder and work as intended. However, if you choose to continue using the DataLake library without an HNS-enabled account, any odd behaviors cannot be investigated or supported by the SDK team.

Attached below is a workaround code snippet that will help ensure `delete_directory` completely clears out the directory when using a flat namespace account, but again, this is **not** officially supported and it is _highly_ recommended to use an HNS-enabled account with DataLake libraries as intended 😄 

**Code Snippet** (workaround **not** officially supported by the SDK team)
```
ret = directory_client.delete_directory()
    cont_token = ret['continuation']

    while cont_token is not None:
        ret = directory_client.delete_directory(continuation=cont_token)
        cont_token = ret['continuation']
```

Again, sorry for the delay but thank you for your patience and hopefully this resolves your issue.
Thanks!
