### ISSUE TITLE
azure-storage-blob : BlobClient creates an unwanted subsirectory inside the container 

### ISSUE THREAD

**Issue by stockersky** [Azure/azure-sdk-for-python#24785]
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.12.0
- **Operating System**: Windows
- **Python Version**: 3.10.4

**Describe the bug**
When creating a blob inside a container with BlobClient, the blob is created but inside a subfolder having the same name as the container.
Note : I use BlobClient directly and the parameter "account_url" is not the one of the whole storage account but the one of the container (with a SAS Token).
In fact, I do not really understand that the parameter "container_name" is mandatory if the connexion_string already points to the container_adresse (see additionnal content of this post.

--EDIT--
Just to emphase my last sentence about the "container_name" argument to the BlobClient constructor. It has a strange behaviour : if I put a random dummy value there, it will create a subfoler with this name in the right Container (because the right Container is specified in the connexion_string)... (see additionnal content of this post.)

**To Reproduce**

```python
def az_blob_storage(connection_string, az_container):
    blob_client = BlobClient(account_url=connection_string, container_name=az_container, blob_name="retest.test" )
    
    # Upload the created file
    with open(Path("test.test"), "rb") as data:
        try:
            blob_client.upload_blob(data=data, overwrite=True)
        except Exception as e:
            print(e)

az_blob_url_asa_token_connection_string = "https://xxxxxx.blob.core.windows.net/testcont?sp=racwdl&st=2022-06-09T14:05:02Z&se=2022-06-09T22:05:02Z&sip=xxxxxxx&spr=https&sv=2021-06-08&sr=c&sig=xxxxxxxx"
az_blob_storage(az_blob_url_asa_token_connection_string, "testcont")

```

**Expected behavior**
A file "restest.test" is created inside the container, at the root of the container.

**What i got**

Indeed the retest.test is created but inside a folder having the same name as the container:
- container: "testcont"
    - subfolder ??? "testcont"
         - the file : "retest.test"

![image](https://user-images.githubusercontent.com/22478549/172868031-f94a227a-074f-4e3a-9760-1b2757c47bfd.png)

**Additional context**

Most of the examples show the connexion_string as the connexion string of the Storage Instance.
I would like to narrow it to the container for security reasons.
This is why i use connexion_string to this exact container.
In fact, BobClient should not need the container name if its provided in the connexion_string.
For exemple, if I write this :
`blob_client = BlobClient(account_url=connection_string, container_name="blabla" blob_name="retest.test" )`
Then a subfoler named "blabla" is created... But still in the right Container (because the Container name is specified in the connexion_string).

**Comment by vincenttran-msft** [comment]
Hi @stockersky, thanks for inquiry. I think that you may have some of your terms mixed up, so hopefully my response will help to clarify what these terms mean and where to most easily locate them in Azure Portal, as well as provide a code sample to achieve what you are trying to do!

When providing `account_url` for the `BlobClient` constructor, `account_url` in this context is generally in this format:
`'https://<STORAGE_ACCOUNT_NAME>.<ENDPOINT>.core.windows.net'`
It will typically only include your storage account name, and the endpoint (for blob operations endpoint would be `blob`, for DataLake it would be `dfs`)

With that being said, that is why for the constructor you had chosen to use, you would also need to provide `container_name` and `blob_name` as none of that information should be included in the `account_url`.

Furthermore, I see that you reference to a `connection_string` variable. I think you may have that mixed up with a `Blob SAS URL`.

Typically, if you are the owner of the storage account, your connection string can be obtained in Azure Portal under 'Security + networking', under 'Access keys' and your connection string will be present there.
![image](https://user-images.githubusercontent.com/101599632/172964320-c6dda14c-f799-4b46-9214-342f9d7ddf05.png)

If you are instead using a SAS generated through Azure Portal, you will find that string under `Blob SAS URL` in the same prompt you used to generate the SAS token. 

For example, the **Storage account connection string url** is typically used with `from_connection_string()`, while **SAS URLs** are generally used with `from_container_url` (if, for example it is a container-level SAS).

Hopefully that clears up some of the terminology used, and below is a code snippet achieving what I believe you are trying to accomplish (with annotations).

```
from azure.storage.blob import ContainerClient

container_client = ContainerClient.from_container_url(container_url=<CONTAINER_SAS>)
blob_client = container_client.get_blob_client(blob=<FILE_NAME>)

 # Upload the created file
with open((<FILE_NAME>), "rb") as data:
    try:
        blob_client.upload_blob(data=data, overwrite=True)
    except Exception as e:
        print(e)
```
`CONTAINER_SAS` would refer to something like the `Blob SAS URL` from a Azure Portal generated SAS. Since in this example I used a container-level SAS, what container it is operating on is implied from the SAS.
`FILE_NAME` would refer to the file you want to upload to Azure Storage. 

Hopefully this clears up any confusion. Thanks!

**Comment by stockersky** [comment]
Hi @vincenttran-msft, thank a lot for your support :)
Your explanations really helped me to understand : now it works perfectly.

**Comment by vincenttran-msft** [comment]
Hi @stockersky glad that my previous post was able to clear up any confusion! In regard to your question about setting chunk size, that is correct that it is in bytes. Here is the docstring that may provide more useful information: 
[BlobClient Constructor Docstring](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L117)

Generally the easiest way to get familiar with the SDK and its capabilities is to read through the docstrings found under the APIs you want to call. 

In this case, I am not sure what you mean by 'not seeing any increment of size until it finishes', as in this case if you are setting it to 64 bytes, it will simply cause the `PUT` request to be chunked in 64 byte requests. In contrast, if you don't set `max_single_put_size`, the default behavior is to finishes your upload all in one `PUT` request (assuming your file is under 64MB). Again, please take a look at the docstring and see if that clears up any confusion!
Thanks!

**Comment by jalauzon-msft** [comment]
Hi @stockersky, one small clarification that may help to clear up the confusion. `max_single_put_size` only affects whether the client will decide to use chunks to upload the blob or not. Setting this to 64 will just mean that any blob over 64 Bytes will be uploaded in chunks rather than in a single request. However, the chunk size is controlled by a different argument, `max_block_size` which defaults to 4 MiB. So, if you do not also adjust that value, a blob up to 4 MiB will still be uploaded in a "single chunk".

If you wish to use smaller chunk sizes, you'd also want to set `max_block_size`. That being said, changing the chunk size is an advanced feature and only recommended if you are experiencing networking trouble with the defaults. We do recommend that you do not modify the chunk size unless you have a strong reason to do so, as it could affect performance.

**Comment by stockersky** [comment]
Hi @vincenttran-msft and @jalauzon-msft. Thanks a lot for your precious support.

Yes, this is very interesting. I have a first Proof of Concept that works well : point is to manage backup & restore of CosmosDB database with the MongoDB API. 

Here is a little code snippet:

```python
    def _backup_collection_azure(self, collection, connection_string):
        # initialisation du client Azure
        container_client = ContainerClient.from_container_url(
            container_url=connection_string, max_single_put_size=64
        )
        
        blob_client = container_client.get_blob_client(blob=f"{collection}.bson")

        print(f"Backup collection { collection } to stream...", end=" ", flush=True)
        with io.BytesIO() as buf:
            for doc in self.database[collection].find():
                buf.write(bson.BSON.encode(doc))
            buf.seek(0)
            print("done")

            print(f"Upload to Azure Blob Storage...", end=" ", flush=True)
            try:
                blob_client.upload_blob(data=buf, overwrite=True)
            except Exception as e:
                print(e)
            print("done")
```

As you can see, my use of the BytesIO object is really sub-optimal. Because, in the end, it holds the whole database in memory.
Database is small by now, but it's growing !

what i'd like to achieve is to only hold each MongoDB doc in the BytesIO object and upload it in "append mode" to the blob Object.
Well, probably more optimal for memory use, maybe not for Blob Storage, but I'll find out...

I also tried with "stage_block()" and "commit_block_list()".
From [this example]( https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py#L116)

```python
        block_list = []
        print(f"Upload to Azure Blob Storage...", end=" ", flush=True)
        for doc in self.database[collection].find():
            print("one doc")
            try:
                block_id = str(uuid.uuid4())
                blob_client.stage_block(block_id=block_id, data=bson.BSON.encode(doc))
                block_list.append(BlobBlock(block_id))
            except Exception as e:
                print("Erreur écriture sur Blob Storage: STAGING")
                print(e.__class__.__name__)
                print(e)
        try:
            ret = blob_client.commit_block_list(block_list)
            # print(ret)
        except Exception as e:
            print("Erreur écriture sur Blob Storage : COMMIT")
            print(e.__class__.__name__)
            print(e)
 ```

Definitly very slow ! And I really don't see where I would save memory as the list will contain the whole data at the end...

I found this ["AppendBlobService"](https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.appendblobservice.appendblobservice?view=azure-python-previous&viewFallbackFrom=azure-python) object in Python Azure SDK. Is this the right lib to use for this use case ?
I'll give it a try.

**Comment by stockersky** [comment]
Actually, I ended up trying this :

```python
def _backup_collection_azure(self, collection, connection_string):
        # initialisation du client Azure
        container_client = ContainerClient.from_container_url(
            container_url=connection_string, max_single_put_size=64
        )
        
        blob_client = container_client.get_blob_client(blob=f"{collection}.bson")
        blob_client.create_append_blob()

        print(f"Backup collection { collection } to stream...")

        buf = io.BytesIO()
        for doc in self.database[collection].find():
            
            nb_bytes = buf.write(bson.BSON.encode(doc))
            if nb_bytes >= 10000:
                print("writing...")
                buf.seek(0)
                blob_client.append_block(data=buf)
                buf.close()
                buf = io.BytesIO()
            
        buf.close()
        print(done)
```

Pretty fast and no objects growing in memory.
