### ISSUE TITLE
Check if path is a file or directory

### ISSUE THREAD

**Issue by jenhagg** [Azure/azure-sdk-for-python#24814]
**Is your feature request related to a problem? Please describe.**
I'm using the `azure-storage-file-datalake` python package together with a storage account with hierarchical namespace enabled. It seems like the only way to check if a path is a file or directory is using the `FileSystemClient.get_paths` method, which returns an iterable, and checking the `is_directory` property in the matching result (list of dictionary entries). This isn't ideal if a directory has a lot of files. 

Additionally, both file and directory clients say that a path exists, which seems counterintuitive, but unrelated other than that it did not solve the original problem.
```
In [131]: fsc
Out[131]: <azure.storage.filedatalake._file_system_client.FileSystemClient at 0x104853a60>

In [132]: [f for f in fsc.get_paths("wow/ooh/")]
Out[132]:
[{'name': 'wow/ooh/okay', 'owner': '$superuser', 'group': '$superuser', 'permissions': 'rwxr-x---', 'last_modified': datetime.datetime(2022, 6, 8, 0, 33, 43), 'is_directory': True, 'etag': '0x8DA48E68A9D753A', 'content_length': 0, 'creation_time': datetime.datetime(2022, 6, 8, 0, 33, 43, 159942, tzinfo=datetime.timezone.utc), 'expiry_time': None},
 {'name': 'wow/ooh/omg', 'owner': '$superuser', 'group': '$superuser', 'permissions': 'rwxr-x---', 'last_modified': datetime.datetime(2022, 6, 8, 0, 33, 37), 'is_directory': True, 'etag': '0x8DA48E6876E2A41', 'content_length': 0, 'creation_time': datetime.datetime(2022, 6, 8, 0, 33, 37, 816839, tzinfo=datetime.timezone.utc), 'expiry_time': None}]

In [133]: dir_client = fsc.get_directory_client("wow")

In [134]: dir_client.exists()
Out[134]: True

In [135]: file_client = fsc.get_file_client("wow")

In [136]: file_client.exists()
Out[136]: True

```
**Describe the solution you'd like**
I'd like to check if a specific path is a file or directory without listing all the paths in a directory. I imagine it should be a constant time operation. Alternatively, if I missed something in the docs, please point me to that. 

**Describe alternatives you've considered**
I tried using the `DataLakeFileClient` and `DataLakeDirectoryClient` as in the example above, but didn't see a way to disambiguate files from directories. 

**Additional context**
n/a

**Comment by vincenttran-msft** [comment]
Hi @jenhagg thanks for your inquiry! This sounds like a feature request that would require Service support, and so I would hesitate to put any timelines on when we would get a feature like this in due to there being several high priority items currently on their docket.
However, after some digging and some investigation, I believe I have come up with a workaround that can be implemented in our current system and still achieve that constant time complexity you are seeking.

Once you have a `FileSystemClient`, we can see [here](https://github.com/Azure/azure-sdk-for-python/blob/b92ba2add707936565279bc7d6981debae0d1bda/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_file_system_client.py#L909) that there is a `get_file_client` API that supports both files and directories. You can then call `get_file_properties` (docstring found [here](https://github.com/Azure/azure-sdk-for-python/blob/b92ba2add707936565279bc7d6981debae0d1bda/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py#L255)) which again works on both files and directories.
If you print the response from calling `get_file_properties` on a test file and a test directory, in my local testing I found a consistent indicator of truth as to whether the API was called on a file or a directory -- the response contains a `metadata` dict that maintains a property `hdi_isfolder`.

`get_file_properties` response on a directory:
![image](https://user-images.githubusercontent.com/101599632/174408143-35f9d779-8db7-44cc-9ca3-df24d1fceb85.png)

`get_file_properties` response on a file:
![image](https://user-images.githubusercontent.com/101599632/174408193-f2128e9a-1310-4379-afac-ca394fdcf125.png)

And so, I believe you can simply build a quick helper function to assert against this value and thus would be able to resolve whether a path is to a file or a directory in constant time.

**Sample Code:**
```
def is_file(blob):
    metadata = blob['metadata']
    if metadata:
        if 'hdi_isfolder' in metadata:
            if metadata['hdi_isfolder'] == 'true':
                return False
    return True
```
Where `blob` is the response from a `get_file_properties` API call
**Note:** This simply does an existence check of header values -- and so some false-positives (saying a path _is_ a file even if it _is not_) may slip through if the header values are not set properly or a source of truth
**Note 2:** This is _not_ an officially supported scenario by Microsoft and is simply a workaround to be used at your own discretion

With that being said, hopefully the above findings will help to achieve the functionality you desire of checking whether a path is a file or directory in constant time! 
Thanks!

**Comment by jenhagg** [comment]
Hi @vincenttran-msft, thanks for the detailed response! I think this solution is sufficient, assuming the `hdi_isfolder` property continues to be supported, so feel free to close this issue.
