### ISSUE TITLE
Inconsistent version indexing

### ISSUE THREAD

**Issue by keriksson-rosenqvist** [Azure/azure-sdk-for-python#25019]
- **Package Name**: azure-keyvault-secrets
- **Package Version**: 4.4.0
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.9.13

**Describe the bug**
Using the same command to get and iterate through versions of two different secrets starts with different version "offsets". One where the first version is the current version as shown in the Azure portal view, and the other starts from the most recent "Older version". The only difference I can see between the two secrets is that the first only has one older version while the second has more than ~45 older versions. 
Example
If the current versions of Secret_1 and Secret_2 are a000000 and b000000, respectively the current implementation returns versions as:
```
Offset      Secret_1       Secret_2
0           a000000        b000001
1           a000001        b000002
2           a000002        b000003
```

**To Reproduce**
```
for secret in [secret_1, secret_2]:
    print(f"Current:\t{secret.name}\n\t{secret.properties.version}")
    versions = secret_client.list_properties_of_secret_versions(secret.name)
    for i, v in enumerate(versions):
        print(f"{i}:\t{v.name}\n\t{v.version}")
```

**Expected behavior**
Expect indexing to be consistent.
Example
```
Offset      Secret_1       Secret_2
0           a000000        b000000
1           a000001        b000001
2           a000002        b000002
```

**Comment by l0lawrence** [comment]
Hi @keriksson-rosenqvist, thanks for the feedback. We'll investigate asap.

**Comment by mccoyp** [comment]
Hi @keriksson-rosenqvist, thank you again for opening an issue! This behavior seems to be because of how the list of secret version properties is returned by the Key Vault service. Rather than ordering the version properties by the time at which the secret version was created, the service appears to order the list by the name of the secret version string (0-9, then a-z).

For example, if I run the code snippet you provided when I have `secret_one` and `secret_two` which each have five versions, I get (with adjusted formatting post-execution):
```
Current:        secret-one        86114ff30d1341eb910309d0ef143326

0:              secret-one        03ad90deaf5b4d91b809ac6abd35dc9e
1:              secret-one        573180db6a2240b3b28badf3e2000e54
2:              secret-one        86114ff30d1341eb910309d0ef143326
3:              secret-one        8a371b4b30f74151ac5a1bcf378a457f
4:              secret-one        91792547ac9243e4a83695f0691ae70f
5:              secret-one        e9a8b3216f9e4afda28823caaf66030f


Current:        secret-two        d56f3e18824b4bbf92850259d4303a89

0:              secret-two        34aa75bb2a184701823e621c263cf73d
1:              secret-two        5b0a36b68c7442d18bb6440aad934961
2:              secret-two        d56f3e18824b4bbf92850259d4303a89
3:              secret-two        e04a6ad1e6434659a818fffbabadc6fc
4:              secret-two        eca7728ea7a141a88341b919bd871222
5:              secret-two        f03f7e331f36469783e7449450953b5e
```

This output order is produced deterministically, consistent the alphanumeric ordering of the version strings. Is this consistent with what you've seen? Please let me know if I misunderstood your question and if there's something else that you're asking about.

cc: @jlichwa, is this ordering in the Key Vault response intentional and correct?

**Comment by keriksson-rosenqvist** [comment]
@mccoyp Yes you are correct. Apologies for misinterpreting the functionality of `list_properties_of_secret_versions()`. However is there a key word argument or other input to that I can use to get the versions ordered by date?

**Comment by mccoyp** [comment]
@keriksson-rosenqvist The results of `list_properties_of_secret_versions` unfortunately can't be sorted through function input because of limitations in what we receive from the service response. However, it shouldn't take too much work to do some sorting on the application end -- for example:
```python
secret_one_version_properties = [props for props in secret_client.list_properties_of_secret_versions("secret-one")]
sorted_properties = sorted(secret_one_version_properties, key=lambda props: props.updated_on, reverse=True)
```
This gives us the properties for each secret version, ordered from newest to oldest. The limitation here is that the `updated_on` property is only accurate to the second, so versions that were updated in the same second will be ordered alphanumerically by version string:
```
Current:        86114ff30d1341eb910309d0ef143326

03ad90deaf5b4d91b809ac6abd35dc9e        2022-06-30 00:44:27+00:00
86114ff30d1341eb910309d0ef143326        2022-06-30 00:44:27+00:00
573180db6a2240b3b28badf3e2000e54        2022-06-30 00:44:26+00:00
8a371b4b30f74151ac5a1bcf378a457f        2022-06-30 00:44:26+00:00
91792547ac9243e4a83695f0691ae70f        2022-06-30 00:44:26+00:00
e9a8b3216f9e4afda28823caaf66030f        2022-06-30 00:44:26+00:00
```
This should suffice, though, for the more common case when there aren't many secret versions being generated within the same second.
