### ISSUE TITLE
list_blobs() leading to ServiceRequestError and CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by vholmer** [Azure/azure-sdk-for-python#25046]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.12.0
- **Operating System**: Ubuntu 20.04
- **Python Version**: 3.8.9

**Describe the bug**
list_blobs() leads to azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125) on a completely fresh install on an Ubuntu 20.04 VM.

**To Reproduce**
Run this code:
```
import os

from azure.storage.blob import ContainerClient

def try_list_blobs():
	account_url = "https://mystorageaccount.blob.corewindows.net<SAS>"
	container_name = "mycontainer"

	cc = ContainerClient(account_url, container_name)

	for blob in cc.list_blobs():
		print(blob)

try_list_blobs()
```

**Expected behavior**
No crash, printing listed blobs

**Additional context**
This happened on 3 separate machines on completely clean python installs. We tried with both correct and incorrect values in account_url and they all yield the same result.

We tried using Shared Access Signatures (as above) and environment credentials.

**Comment by vholmer** [comment]
My URL was incorrect, it contained "blob.corewindows.net" instead of the correct "blob.core.windows.net". Perhaps a better error message would be a good idea?

**Comment by vincenttran-msft** [comment]
Hi @vholmer Viktor, thanks for reaching out to us with this issue. I see that you were able to resolve your issue. In terms of your follow-up question, I am not exactly sure how we can provide a more helpful error message. This is because we don't really have a way of determining what you (the user) are intending to do, and what endpoint you are intending to target (as we support several endpoints, not to mention CDNs and custom URLs).

With that being said, if you have any concrete ideas on how we can improve the error message, please let us know as we want to provide the best user experience possible. Otherwise, may we move on with the closure of this issue?

Thanks!
