### ISSUE TITLE
Provide a function for fetching schema from Schema Registry using group name, schema name and schema version.

### ISSUE THREAD

**Issue by harshdeep78singh** [Azure/azure-sdk-for-python#25072]
Currently, I am fetching the schema from the Schema Registry using the following endpoint

/$schemaGroups/{groupName}/schemas/{schemaName}/versions/{version}

There is no function provided in the **azure.schemaregistry.SchemaRegistryClient** class for pulling the schema from Event Hub Schema Registry using group name, schema name, and version.

Can we have a function for the same?

Also, let me know if you are open to a PR?

**Comment by mccoyp** [comment]
Hi @harshdeep78singh, thank you for opening an issue! I'll tag the appropriate folks so we can answer your question about the potential availability of this API.

As for opening a pull request, we're always happy to accept PRs 🙂 For something like adding a client method there will need to be some design discussion, but opening a PR could kickstart that conversation! I'd recommend waiting just a bit before doing any work so that someone who works with the service can provide some input in this case.

**Comment by swathipil** [comment]
Hi @harshdeep78singh - Thanks for bringing this to our attention! I have discussed this with the team and we will be adding this functionality asap. I saw that you created a PR and took a look.

Unfortunately, we will not be able to merge this, because the changes you made were to our "generated" code. This code is automatically generated from our internal "swagger" file that describes operations that we allow. So, ultimately, the changes that you made will actually be added upon re-generation after we update our swagger file to match. Really appreciate your efforts here, however.

We are currently making changes to the swagger file and will be having API design discussions after that. I'll keep you updated as we continue to make progress. Thanks again!

**Comment by swathipil** [comment]
Hi @harshdeep78singh - Appreciate your patience here! I just merged the feature. (sample [[here](https://github.com/Azure/azure-sdk-for-python/blob/376224e541576c351e6b5cec27fcbc030ca5685f/sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py#L100)]), and it'll be out in our next release. I'll update this issue as soon as it's out.

In the meantime, if you're interested, you can manually build and install the wheel:
1) `azure-sdk-for-python/sdk/schemaregistry/azure-schemaregistry> python setup.py bdist_wheel -d [dest_folder]`
2) `[dest_folder]> pip install azure_schemaregistry-1.2.0-py3-none-any.whl`

Thanks!

**Comment by harshdeep78singh** [comment]
Thank you for the update

**Comment by harshdeep78singh** [comment]
@swathipil thank you for the update

**Comment by swathipil** [comment]
Hey @harshdeep78singh! After a review from our architects, the API to get schema by version has been updated. Rather than a separate `get_schema_by_version` method, the get_schema method now takes group_name, name, and version as keyword arguments: `get_schema(group_name=group_name, name=name, version=version)`. The updated sample is [[here](https://github.com/Azure/azure-sdk-for-python/blob/bef8204e10a8cf6449426f1f9ec8fcfd881382f4/sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py#L99))].

**Comment by swathipil** [comment]
azure-schemaregistry 1.2.0 has been released: https://pypi.org/project/azure-schemaregistry/1.2.0
