### ISSUE TITLE
[Data Factory] Convert PipelineResource to JSON

### ISSUE THREAD

**Issue by romanzdk** [Azure/azure-sdk-for-python#25081]
I am creating Azure Data Factory pipeline using Python SDK (`azure.mgmt.datafactory.models.PipelineResource`). I need to convert `PipelineResource` object to JSON file. Is it possible anyhow?

I tried `json.loads(pipeline_object)` , `json.dumps(pipeline_object)` but no luck.

**Comment by mccoyp** [comment]
Hi @romanzdk, thank you for opening an issue! I'll tag the appropriate folks so we can take a closer look.

In the meantime, you may be able to get unblocked by adding a `default` argument to `json.dumps` in order to make objects that aren't JSON serializable into `dict`s first. For example:
```python
import json
from azure.mgmt.datafactory.models import Activity, PipelineResource

activity = Activity(name="activity-name")
resource = PipelineResource(activities=[activity])

json_dict = json.dumps(resource, default=lambda obj: obj.__dict__)
print(json_dict)
```

**Comment by romanzdk** [comment]
(I added `resource.name = "my-name"`)

Unfortunately, when I use this Azure Data Factory returns an error `Could not load resource 'my-name'. Please ensure no mistakes in the JSON and that referenced resources exist. Status: Cannot read properties of undefined (reading 'policy'), Possible reason: Cannot read properties of undefined (reading 'policy')`

**Comment by Wzb123456789** [comment]
Hi @romanzdk 

According to the error message you gave, I judged that it was an error in your policy information, which has nothing to do with the above code and the code you gave.

It is recommended that you check your Azure policy information to see if it works.

**Comment by romanzdk** [comment]
Well, not really, apparently. It looks like some issue with the generated JSON file. All activities and the pipeline has `policy=null`. I also tried to remove all these policy keys, but the same issue.

**Comment by Wzb123456789** [comment]
Hi @romanzdk 

You want to modify the parameters through resource.name = "my-name" above, but in the swagger definition, name is a read-only parameter, so it cannot be modified. SDK is generated by swagger.
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
![image](https://user-images.githubusercontent.com/51410816/178430728-f3cb7d0a-4047-4490-a3be-9a7b5d652709.png)


Because the code mentioned by @mccoyp above is only tested locally and not through Azure, all activities and the pipeline has policy=null.

**Comment by romanzdk** [comment]
Hi @Wzb123456789 , I know that name parameter is read-only, but when I convert the class to JSON, the name is not defined, so the pipeline is not valid for the ADF. The name has to be present - that's the reason I changed the name.

**Comment by Wzb123456789** [comment]
Hi @romanzdk 

There are two ways to pass parameters to the model:
```python
1.
activity1 = Activity(depends_on=...)
2.
activity1 = Activity(
    "dependsOn": ...
)
```
So, if you need to use the model to get data, it is recommended that you pass the parameters you want in json, like：
![image](https://user-images.githubusercontent.com/51410816/178925200-3d8d3184-6140-411c-a6f8-a431fc866916.png)

Regarding some keys that are not in the format you need, I cannot modify this, because this parameter returned by the service response is also a read-only parameter, which is defined by swagger, but it is useless to modify it.

**Comment by romanzdk** [comment]
There is still a misunderstanding.. I am generating the entire ADF pipeline using just Python SDK. No JSON files. And I need to convert the result Pipeline object into JSON because I need to upload it into GIT repository associated with the ADF.

The problem is that converting the ADF python models into JSON objects is not working correctly - dictionary keys have wrong case - e.g. instead of `dependsOn` converted object has key `depends_on` which is not accepted by the ADF.

**Comment by Wzb123456789** [comment]
Hi @romanzdk 

Since the model of `PipelineResource` is fixed, I have no way to modify what comes out after model deserialization.

I found a method that might work for you based on your description, like:

```python
origin_req = None


def callback(request):
    global origin_req
    origin_req = request.http_request.body
    return origin_req


res = ADF_client.pipelines.create_or_update(
    resource_group_name='resource_group_name',
    factory_name='factory_name',
    pipeline_name='pipeline_name',
    pipeline=PipelineResource(
        activities=[activity],
        folder=PipelineFolder(name="someFolder")
    ),
    raw_request_hook=callback
)
print(origin_req)
```

This method is to obtain the serialized content of the model in the sent request.

Hope it helps you.
