### ISSUE TITLE
`compute_client.virtual_machines.list()` not returning newly created VM

### ISSUE THREAD

**Issue by chester-leung** [Azure/azure-sdk-for-python#25095]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 25.0.0
- **Operating System**: Ubuntu 18.04
- **Python Version**:  3.7

**Describe the bug**

I am seeing the exact same issue as [here](https://github.com/Azure/azure-sdk-for-python/issues/8985). Non-deterministically after launching VMs via the `resource_client.deployments.begin_create_or_update()` call and seeing the newly launched VMs in the Azure portal, the `compute_client.virtual_machines.list()` function returns a list that does not contain the newly launched VMs. 

**To Reproduce**
1. Create a VM using `resource_client.deployments.begin_create_or_update`
2. Confirm via Azure portal that a VM has been launched.
3.  Call `compute_client.virtual_machines.list()` to check for the VM. You may need to run it a couple times, as this issue is non-deterministic.

**Expected behavior**

The newly created VM should be returned by the function call.

**Screenshots**

**Additional context**

**Comment by mccoyp** [comment]
Hi @chester-leung, thank you for opening an issue! I'll tag the appropriate folks so we can look into this as soon as possible. I see that @Drewm3 offered help on #8985, so I'll include them here as well.

**Comment by chester-leung** [comment]
To follow up, I also tried retrieving the VM via `az vm list --resource-group` CLI command, and found that when the Python API call (incorrectly) returns nothing, the CLI call also returns nothing. i.e. the CLI mirrors the (non-deterministically unexpected) behavior of the Python API.

**Comment by Wzb123456789** [comment]
Hi @chester-leung 

According to my investigation, some reaction time is required after `begin_create_or_update`, so if `compute_client.virtual_machines.list()` is used immediately in the code, it will return a list that does not contain newly started VMs.

It is recommended to add `.result()` after `resource_client.deployments.begin_create_or_update()`, that is, `resource_client.deployments.begin_create_or_update().result()`, so that it can be obtained after the operation is completed.

If the above operations do not solve your problem, you can provide your code to better solve your problem.

**Comment by Wzb123456789** [comment]
Hi @chester-leung 

In this case, it is recommended that you use the synchronous method to execute, because `compute_client.virtual_machines.list()` needs to be executed after `resource_client.deployments.begin_create_or_update()` is completed to obtain the newly started virtual machine.
So it is recommended that you use the synchronous method and add `.result()` after `resource_client.deployments.begin_create_or_update()`.

**Comment by chester-leung** [comment]
Hi @Wzb123456789 thank you for your response.

By the synchronous method are you referring to `resource_client.deployments.begin_create_or_update()`? My understanding is that it is a non-blocking call. When I call `.wait()` with it, i.e. `resource_client.deployments.begin_create_or_update().wait()`, the `.wait()` call is a blocking call, and will only return when the VM has launched.

So what is the difference in behavior between `.wait()` and `.result()` here?

**Comment by Wzb123456789** [comment]
Hi @chester-leung 

`.wait()`: Call the wait function to block itself immediately, then run `compute_client.virtual_machines.list()` directly, and release the blocking after the child processes are all running.

`.result()`: Wait until `resource_client.deployments.begin_create_or_update()` is executed and return the result before executing `compute_client.virtual_machines.list()`

The synchronous method is recommended because the two function calls are in sequential order. If it is called asynchronously, it will cause the `list` to be called before the new VM is created.
