### ISSUE TITLE
[Cosmos] Concurrent (asynchronous) gathering of query_items results

### ISSUE THREAD

**Issue by tomasvanpottelbergh** [Azure/azure-sdk-for-python#25164]
**Context**
The Python Cosmos SDK introduced an async CosmosClient under `azure.cosmos.aio`. The `query_items` method of that package returns an `AsyncItemPaged`, for which the [documentation](https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.aio.containerproxy?view=azure-python#azure-cosmos-aio-containerproxy-query-items) suggests to iterate over using `async for`.

**Problem**
As far as I can see, using an `async for` list comprehension won't gather the queried items concurrently. This might be not be obvious to everyone, while concurrent gathering might give the greatest performance boost in the case of large query results.

**Describe the solution you'd like**
- A clarification of the documentation/examples about concurrent gathering of queried items
- An implementation and example of a concurrent gathering of the queried items

**Describe alternatives you've considered**
The only way I could think of to gather the queried items concurrently, is as follows:
```
iterator = container.query_items(
    query='SELECT * FROM products p WHERE p.productModel <> "DISCONTINUED"',
    enable_cross_partition_query=True,
)

items = await asyncio.gather(*iterator)
```
, but this results in the following error: `TypeError: asyncio.tasks.gather() argument after * must be an iterable, not AsyncItemPaged`.

Any help is much appreciated, since I'm fairly new to asynchronous programming in Python!

**Comment by simorenoh** [comment]
Hi @tomasvanpottelbergh, thank you for using our SDK. You are technically correct in what you are saying - we use `async for` in our SDK in order to allow for the sequential iteration of the async source that is our `AsyncItemPaged`, not the parallelization of processes/ iterations to fetch results the way you are mentioning (this is also why using a normal `for` loop would not fetch your results). We do this is in order to respect the order in which the operations are completed - if you were running a query that was looking for a particular order of items to be returned, the parallelization would not guarantee this.

You could potentially try to use the "get next page" callback to run some kind of `asyncio.gather` with, but it is not a guarantee that it would work nor is it a scenario we currently have samples for. Hope this answers your question!
