### ISSUE TITLE
Set ACLs recursively with an owning group

### ISSUE THREAD

**Issue by dkreeft** [Azure/azure-sdk-for-python#25238]
**Is your feature request related to a problem? Please describe.**
We would like to set ACLs recursively and specify an owning group in the process.

**Describe the solution you'd like**
3 solutions I could work with in order of preference (feel free to propose alternatives):
1. Add a "group" parameter to `DataLakeDirectoryClient.set_access_control_recursive`, similar to `DataLakeDirectoryClient.set_access_control`;
2. Support specifying the owning group in the ACL itself, like `user::rwx,group:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:r-x,other::rwx`;
3. Add a "set_owning_group" (or something similar) to set the owning group of a folder. The alternative described below could then be applied. (not my personal preference).

**Describe alternatives you've considered**
First setting the owning group on the parent folder and then making use of `DataLakeDirectoryClient.set_access_control_recursive`. According to the documentation, ACLs then inherit the owning group form the parent folder. However, there is no programmatic way to set the owning group as far as I know and therefore I do not prefer to go this route.

**Comment by jalauzon-msft** [comment]
Hi @dkreeft, thanks for reaching out. This is an interesting topic. It seems the SDK may have this "gap" because of some specifics on what the service accepts. See the [service docs](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) for the API that backs these functions. 

The docs are a bit hard to read through since the Update Path API can do a whole lot of different things but if you look specifically at the [request headers section](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update#request-headers) and find the `x-ms-group` header. It says its only supported for the `setAccessControl` action and does not mention `setAccessControlRecursive`.

And if you look at the description for `x-ms-acl` in the request headers section, it does seem to indicate that you can specify the owning group within the ACL like in your Option 2.
> "group" grants rights to the owning group or a named group

Have you tried specifying the group within the ACL? I guess this would adjust permission for a specific group and not necessarily set the owning group. 

I will need to do some more testing and likely talk with the service team and get back to you on this. Thanks

**Comment by dkreeft** [comment]
Thank you for your swift reply. To answer your question: yes, I have tried that, but then Azure will return an error message stating "invalid ACL" (or something similar). The service docs for `x-ms-acl` state:

> The user or group identifier is also omitted for the owner and owning group. 

Which might be a cryptic way of describing that providing an owning group in the ACL itself is not supported.

As a quick possible work-around, if Azure works as I described in the alternatives I have considered, then maybe `DataLakeDirectoryClient.set_access_control_recursive` could first make a call for `x-ms-group` after which the existing call(s) from the method are made to the API. In either case, for completion, I think the Python SDK could benefit from a "set_owning_group" method (using `x-ms-group`, basically solution 3 I have described above) as that currently does not exist.

**Comment by jalauzon-msft** [comment]
Hi @dkreeft, sorry for my long delay.

Looking back at this, and maybe I'm missing/forgetting something, but would it not be possible to use `set_access_control` (non-recursive) to set the owning group of a directory? This function accepts the `group` parameter and should pass it as `x-ms-group`. While this wouldn't be recursive, it should cover solution 3 you described? You could do this on whatever parent directory you choose, and the ACL should inherit it.

**Comment by dkreeft** [comment]
That could work, I think. I am not sure about the workflow, though, so I would need to experiment with it. I think it should be either 1 or 2:

*workflow 1*
1. use `set_access_control(acl=<desired acl>, group=<desired owning group>)` on the root folder
2. use `set_access_control_recursive(acl=<desired acl>)` on the underlying folders/files

*workflow 2*
1. use `set_access_control(group=<desired owning group>)` on the root folder
2. use `set_access_control_recursive(acl=<desired acl>)` on the root folder

I am not sure how `set_access_control_recursive` traverses through the folders/files (highest level to lowest level?) and whether that is consistent. That determines whether the owning group is correctly inherited or not.

**Comment by jalauzon-msft** [comment]
Hi @dkreeft, were you able to try either of these workflows out? Did one of them work for you? Thanks
