### ISSUE TITLE
get_blob_names in Azure Python SDK

### ISSUE THREAD

**Issue by pathumd** [Azure/azure-sdk-for-python#25287]
Hello,

Recently I've been building a Python application that acts as a search tool for an Azure storage account containing several containers. One container has nearly 1,100,000 blobs. When my script searches through this container, it takes nearly 23 minutes to fully complete.

I'm currently using the 'list_blobs' method to retrieve a generator containing all of the blobs in each container. However, this method seems to be very CPU intensive and ultimately is not ideal to use for e.g. a search tool.
I came across the 'Listing blobs names is very slow #19755' issue, and noticed that a new method called 'get_blob_names' is in the works which will be much faster in terms of getting blob names using the list_blobs method.

I was wondering if the get_blob_names method is available for use in the Azure Python SDK currently, and if not, when we can expect this method to be available for use. Thank you!

**Comment by vincenttran-msft** [comment]
Hi @pathumd Pathum, thanks for your inquiry. Unfortunately, this functionality has not yet been implemented and I have no good on ETA on when this feature will be implemented and released. As you have pointed out, this issue seems to be the same request feature request as linked (issue #19755). 

Therefore, I will continue with the closure of this issue as a duplicate. However, please post your personal inquiry as a follow up to that linked issue, so that any updates regarding this feature request can be centralized in one GitHub issue thread (and by posting your follow up in that thread, you will be notified anytime there is updates regarding this feature).
Thanks!
