### ISSUE TITLE
Unable to query Blob storage by date using "find_blobs_by_tags" method from python SDK and REST API

### ISSUE THREAD

**Issue by enjis** [Azure/azure-sdk-for-python#25385]
- **Package Name**:   azure-storage-blob
- **Package Version**:  12.13.0
- **Operating System**:  Linux
- **Python Version**:  3.10.5

**Describe the bug**
Container client method "find_blobs_by_tags" is returning **ErrorCode:InvalidQueryParameterValue.**
The requirement is to list the blobs by the 'last_modified' date.
The REST API for the same is giving the same error despite following the documentation.
https://docs.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags

**To Reproduce**
1.
```
container_client = blob_service_client.get_container_client(AZURE_BLOB_CONTAINER) 

list(container_client.find_blobs_by_tags(f"last_modified>'2022-06-18 20:51:26Z'"))
list(container_client.find_blobs_by_tags(filter_expression= "\"last_modified\">'2022-06-18 20:51:26Z'"))
```

while using APIs the normal format and url encoded format both are not working.

**Expected behavior**
The find_blobs_by_tags should return a list of metadata of blobs by querying on the last_modified date.

**Screenshots**
![image](https://user-images.githubusercontent.com/38658739/180710915-5e7af3d6-592c-428c-b5de-cfc5ffea1191.png)

**Additional context**
Authorization using SAS key.

**Comment by swathipil** [comment]
@enjis - Thanks for your question! We'll investigate this as soon as possible.

**Comment by vincenttran-msft** [comment]
Hi @enjis Anjali, thank you for your inquiry. Unfortunately, I was unable to reproduce your issue when testing locally. Could you please do me a favor and check the following as possible sources of the error?

- Upgrade to latest `azure-storage-blob` version 12.13.0 (I know you have this listed above, but just want to provide for the sake of completeness. There are some dependencies that are installed alongside this, so perhaps a clean reinstall may resolve your issue)
- What type of SAS are you using? Please ensure the SAS has all the permissions necessary (for example, I was using an Account-level SAS with all permissions enabled)

The only other thing I can think of is that your `filter_expression` is not properly formatted. However, I did test with exactly the query you provided (in both manners you described above, both explicitly `filter_expression=` and implicitly)
![image](https://user-images.githubusercontent.com/101599632/180886537-6d7aa3cc-f5c3-4ac2-80ec-461cabe489fb.png)
and it did not encounter the error, so perhaps try retyping / copy-pasting your expression as maybe there is some non-standard character that is messing up the expression (i.e. non-standard ASCII characters)

Please try the above and let me know if the problem still persists (and provide more context, if possible!)
Thanks!

**Comment by enjis** [comment]
@[vincenttran-msft](https://github.com/vincenttran-msft) Hi, Thanks for the reply.
I did try your suggestions. Out of the possible sources of errors you suggested, I think it's an issue with the SAS.

I am also using an Account-level SAS but when I investigated the SAS URI, I found that all the permissions are not enabled
```
sp=rwdlacupx
```
Permissions for tag and filter are not enabled.
What does `x` stand for in the signed permission??

**Comment by vincenttran-msft** [comment]
Hi @enjis Anjali, the `x` in the signed permission stands for 'Delete version'. Here is some helpful links regarding SAS permissions:
[Create a service SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas)
[Create an account SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas)

Do you happen to know how you are generating your account-level SAS? For example, in my local testing, I was using the 'Shared access signature' tab in Azure Portal to generate my account SAS. It is possible that your SAS token was generated with an older version of the SDK (before `find_blobs_by_tags` was added), and so that SAS token's permissions is not formatted properly to support `find_blobs_by_tags`.

If possible, can you try to regenerate the account-level SAS token? I would also suggest attempting a simpler `filter_expression` in order to isolate that the issue is indeed with the client and not your expression itself.

Lastly, I see that the signed permissions you have provided are missing the `f` permission. If you follow either of the above links regarding SAS permissions, you can see that find blobs by tags requires the `f` permission.

![image](https://user-images.githubusercontent.com/101599632/181098229-4f1f1e45-86a2-498d-b565-32f8062b1e7d.png)
![image](https://user-images.githubusercontent.com/101599632/181098262-97cc1638-8d7d-4dd8-aa2a-826b0d2a2e6c.png)
So when looking at your SAS token again, please ensure you have the `f` permission. 

Hopefully one of the above suggestions will help you resolve your issue, but again please do not hesitate to reach out!
Thanks!

**Comment by vincenttran-msft** [comment]
Hi @enjis Anjali, I believe I have come to the conclusion as to why you are running into this issue. 

I see that in the screenshot you provided, you are missing the options for 'Allowed blob permissions' as seen in this screenshot below:
![image](https://user-images.githubusercontent.com/101599632/181347724-9ac7ade3-76c8-43e3-a53e-883e7f6d5aec.png)

I believe this is because you are on an HNS-enabled account (hierarchical namespace account). To verify this, please go back to the 'Overview' tab on the left hand side of Azure Portal, then under the next screen you will see 'Blob service' and under that a property called 'Hierarchical namespace' which will either be `Enabled` or `Disabled`.

![image](https://user-images.githubusercontent.com/101599632/181345826-c717270d-f8c1-4b27-b132-c4171b723ba4.png)
This is the option on the left hand side

![image](https://user-images.githubusercontent.com/101599632/181345990-ad6804a4-1346-4123-8246-6c54a77e32a2.png)
This is what value in the 'Properties' we are looking for

Generally speaking, HNS namespace accounts are used with the [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake/) package which supports HNS namespace accounts and operations, while flat namespace accounts will be using [azure-storage-blob](https://pypi.org/project/azure-storage-blob/)

With that being said, I believe the following actions will help to resolve your issue:

1. Create a new Storage account, and ensure that HNS is not enabled (this is because you cannot turn off HNS once it has been enabled)
2. After creating the new Storage account, generate a new SAS token using the 'Shared access signature' window, and be sure to have `Filter` checked under 'Allowed blob index permissions'. Here is a sample of what values I have on my SAS token that I have used to successfully call `find_blobs_by_tags` API with your provided `filter_expression`
![image](https://user-images.githubusercontent.com/101599632/181347364-fff89821-1c26-4e21-be4a-487ae1ce17bf.png)
3. Retry the workflow you have in the original post and see if you can now successfully call the `find_blobs_by_tags` API with this new SAS token and flat namespace storage account.

I am confident that the above suggestions will resolve your issue, so please give it a try and let us know if it works out.
Thanks!

**Comment by enjis** [comment]
@vincenttran-msft Creating a new Storage account is not an option for me as there is a lot of data in the current blob storage.
Does that mean even if we create a SAS token without using the azure portal (i.e. generating by code), it will not be able to assign us filter permission as long as it is a hierarchical namespace??

**Comment by vincenttran-msft** [comment]
Hi @enjis Anjali, unfortunately I am not sure where to proceed from here. From my local testing, I was unable to get a successful SAS token generation that both:
1. Is valid for HNS Storage accounts
2. Contains the `f` flag which allows filter permission

It would seem that the crux of the issue is that the `datalake` package does not support tags, while the `blob` package does. So in short, yes it would also unfortunately seem that even when creating a SAS token using the several `generate` SAS token APIs, you are unable to use `find_blob_by_tags` with an HNS enabled Storage account. 

Furthermore, even if it were possible, this would not be recommended as this would not be an officially supported scenario (i.e. we can only guarantee support on issue items for `blob` when using flat namespace and `datalake` when using HNS account).

Although I am not completely sure what you are trying to accomplish with the use of `find_blobs_by_tags`, it would seem to me that the end goal is to run a query and return all the blobs that have been modified past a certain date and time. If that is the case, I can suggest the following workaround (using the `datalake` package):

1. Create a `FileSystemClient` 
2. Use `list_paths` to generate a list of paths to all the files and directories that are in your container
3. Use a loop to iterate through all of the paths, creating a `FileClient` for each file you want to access
4. Use the `get_file_properties()` API to get the file's properties, which will contain a `last_modified` value
5. Conditionally append any files that fall under your criteria (i.e. asserting against `last_modified` or any of the other file properties) to a list
I believe that with the above, you _should_ be able to accomplish what you are seeking to do, albeit a little more inefficient and more manual than simply calling a `find_blobs_by_tags` API.


With that being said, I am sorry that we were unable to get to a resolution that would unblock your workflow, but as I don't see any way we can further investigate this issue, we will continue with the closure of the issue. If you have any other doubts, feel free to re-open this thread, or start a new one if it is unrelated.

Thanks!

**Comment by jalauzon-msft** [comment]
Hi @enjis Anjali, to add on to what Vincent mentioned above as to why this is not supported.

It is actually possible to generate a SAS using the Blob SDK for an HNS account that has the 'f' permission. That _could_ be done like this:
```python
from datetime import datetime, timedelta
from azure.storage.blob import generate_account_sas, AccountSasPermissions, ResourceTypes

sas = generate_account_sas(
    account_name=HNS_ACCOUNT_NAME,
    account_key=HNS_ACCOUNT_KEY,
    resource_types=ResourceTypes(service=True, container=True, object=True),
    permission=AccountSasPermissions(tag=True, filter_by_tags=True),
    expiry=datetime.utcnow() + timedelta(hours=3)
)
```

The issue is that the blobs tags feature is not supported for HNS account from the service side, not just the SDK side. This is why none of the datalake APIs or SAS generation functions in the datalake SDK, mention tags. This is ultimately the reason you get the error you do when calling `find_blobs_by_tags` API on your HNS account. The `find_blobs_by_tags` API relies on [blob tags](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-portal) to be set on the blob for it to work. The example with `LastModified` [here](https://docs.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags#constructing-a-search-expression) is purely an example of if you had set a tag called `LastModified` yourself. It is not something that is automatically set.

To set tags on a blob you would need to call `set_blob_tags` from the Blob SDK like this:
```python
blob_client.set_blob_tags({'LastModified': 'value1'})
```

But this is also not supported on HNS accounts and will return a more helpful error message `<Error><Code>BlobApiNotYetSupportedForHierarchicalNamespaceAccounts</Code><Message>Blob API is not yet supported for hierarchical namespace accounts.` This is again, because the entire blob tags feature is not supported for HNS accounts.

In general, as Vincent mentioned, using the Blob SDK for an HNS account is not supported and you should be using the datalake package: [azure-storage-files-datalake](https://pypi.org/project/azure-storage-file-datalake/).

Hopefully this adds some additional context and hopefully, if you are just interested in `last_modified` times, the workflow suggested above can help. Thanks

**Comment by enjis** [comment]
@vincenttran-msft @jalauzon-msft Thanks for your reply.
My only concern while using` list_paths` to generate a list of paths to all the files and directories that are in the container is that it will be very slow like `list_blobs`.
Can you confirm if the `list_paths` is better than `list_blobs` in terms of space and time complexity??

**Comment by vincenttran-msft** [comment]
Hi @enjis Anjali, unfortunately I cannot confirm whether `list_paths` is better than `list_blobs` in terms of time and space complexity for your specific workflow. However I think comparing their performance may be trivial, as you mentioned previously it is not an option for you to change from your preexisting HNS enabled storage account with data to a new FNS enabled storage account (which would allow you to use `list_blobs`). 

Furthermore, if you were to instead continue using the `azure-storage-blob` package when operating on an HNS enabled storage account, this is technically not an officially supported scenario by us and so I would not recommend this route.

In this case, I would go ahead and try using the above stated workflow using `list_paths` and seeing if the time and space complexity suits your needs. If the performance is not sufficient, I would then begin to explore other avenues (i.e. migrating your data, thinking of other ways to accomplish the same end result, etc.)

Thanks!
