### ISSUE TITLE
Missing objects.inv for intersphinx cross-reference

### ISSUE THREAD

**Issue by viktorfreiman** [Azure/azure-sdk-for-python#25456]
I am using sphinx for my own code and want to do cross-reference
with intersphinx to azure-sdk, but I can't find the objects.inv

I found links to the objects.inv but both intersphinx_mapping's are returning 404
https://github.com/Azure/azure-sdk-for-python/blob/4d3d99bc7062ecc9c2ff8bfc1fce431b796acfdb/doc/sphinx/conf.py#L70-L71

~~~sh
$ curl https://azuresdkdocs.blob.core.windows.net/$web/python/azure-identity/latest/objects.inv
<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:e0e6008e-001e-00c6-27ca-a22aff000000
Time:2022-07-28T21:39:56.0791837Z</Message></Error>
~~~

Is there someway to get it working again?

**Comment by swathipil** [comment]
@viktorfreiman - Thanks for opening an issue! We'll investigate as soon as possible.

**Comment by scbedd** [comment]
@viktorfreiman there is something strange going on here. We definitely didn't cease publishing the objects.inv. In fact, it's still there and accessible.

```
curl "https://azuresdkdocs.blob.core.windows.net/`$web/python/azure-core/latest/objects.inv" --output objects.inv
```

^ note that I ran this in pshell, and needed to provide 

```
`$web
```

so that it didn't treat that container name as a variable.

Additionally when building our sphinx docs, I am not seeing any failures to reach the intersphinx dictionary for azure-core or azure-identity. I do see failures when reaching out to readthedocs for msrest and msrestazure though, so it's definitely checking those intersphinx mappings.

**Comment by viktorfreiman** [comment]
@scbedd Thank for clarifying the problem. I totally missed "$web" being no escaped for bash shell.
I checked again and the urls are correct and working when escaped.

~~~sh
$ python -m sphinx.ext.intersphinx "https://azuresdkdocs.blob.core.windows.net/\$web/python/azure-identity/latest/objects.inv"

py:attribute
        azure.identity...
~~~

Thank for all the help
