### ISSUE TITLE
Typo for the error code "IncrementalCopyOfEarlierVersionSnapshotNotAllowed"

### ISSUE THREAD

**Issue by DarknessChen** [Azure/azure-sdk-for-python#25477]
**Describe the bug**
I think the error code "IncrementalCopyOf**Eralier**VersionSnapshotNotAllowed" here has a typo right? It should be "IncrementalCopyOf**Earlier**VersionSnapshotNotAllowed".

https://github.com/Azure/azure-sdk-for-python/blob/1d5096eb1bc8cbd77223ecc7a628738a5f88751c/sdk/storage/azure-storage-blob/azure/storage/blob/_generated/models/_azure_blob_storage_enums.py#L291

If the user uses it to parse the error code, they will never get it if the server sends a correctly spelled error.

- **Package Name**:  Azure Blob Storage

**Comment by DarknessChen** [comment]
Besides, it should be "Snap**shot**OperationRateExceeded" instead of "Snap**hot**OperationRateExceeded".

https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/eventhub/azure-eventhub-checkpointstoreblob/azure/eventhub/extensions/checkpointstoreblob/_vendor/storage/blob/_generated/models/_azure_blob_storage_enums.py#L321

**Comment by jalauzon-msft** [comment]
Hi @DarknessChen, thanks for reporting this.

You are correct that `IncrementalCopyOfEralierVersionSnapshotNotAllowed` would be a typo but just to note, the code reference you linked is generated code and not the class that is actually exported as part of the blob package. The exported class would be from the shared module. The typo still exists there though so this issue is still valid.
https://github.com/Azure/azure-sdk-for-python/blob/ddf94c61aa82e163904b3726876a95416bfaf4ed/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/models.py#L21

We will work to fix this but unfortunately, it's not as straightforward as just fixing the typo as that would be considered a breaking change (in the off chance someone is already using the value with a typo in their code).

As for the other typo reported in the eventhub code: EventHub has a fork of the blob code, and that typo has already been fixed in the blob SDKs generated code so EventHub will eventually pick that up. But this still exists in the exported class I mentioned above so we'll fix that one at the same time.
