### ISSUE TITLE
Calling get_paths on publicly accessible container raises auth error

### ISSUE THREAD

**Issue by jenhagg** [Azure/azure-sdk-for-python#25476]
- **Package Name**: azure-storage-file-datalake
- **Package Version**: 12.8.0
- **Operating System**: mac os
- **Python Version**: 3.9.12

**Describe the bug**
I have a blob container, hierarchical namespace enabled, with container level public access. I'm able to download files as expected, but listing paths using `get_paths` raises a `ClientAuthenticationError`. I am not totally sure if this is considered a bug, however I am able to do the equivalent operation on a blob container _without_ hierarchical namespace, using the `azure-storage-blob` package. 

**To Reproduce**

```
In [4]: from azure.storage.filedatalake import DataLakeServiceClient

In [5]: account_name = "my_account_name"
   ...: container = "my_container"

In [6]: svc = DataLakeServiceClient(
   ...:     account_url=f"https://{account_name}.dfs.core.windows.net",
   ...: )

In [7]: fc = svc.get_file_system_client(container)

In [8]: paths = fc.get_paths(recursive=False)

In [9]: list(paths)
---------------------------------------------------------------------------
ClientAuthenticationError                 Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 list(paths)

File ~/code/fs-azureblob/.env/lib/python3.9/site-packages/azure/core/paging.py:128, in ItemPaged.__next__(self)
    126 if self._page_iterator is None:
    127     self._page_iterator = itertools.chain.from_iterable(self.by_page())
--> 128 return next(self._page_iterator)

File ~/code/fs-azureblob/.env/lib/python3.9/site-packages/azure/core/paging.py:76, in PageIterator.__next__(self)
     74     raise StopIteration("End of paging")
     75 try:
---> 76     self._response = self._get_next(self.continuation_token)
     77 except AzureError as error:
     78     if not error.continuation_token:

File ~/code/fs-azureblob/.env/lib/python3.9/site-packages/azure/storage/filedatalake/_list_paths_helper.py:158, in PathPropertiesPaged._get_next_cb(self, continuation_token)
    150     return self._command(
    151         self.recursive,
    152         continuation=continuation_token or None,
   (...)
    155         upn=self.upn,
    156         cls=return_headers_and_deserialized_path_list)
    157 except HttpResponseError as error:
--> 158     process_storage_error(error)

File ~/code/fs-azureblob/.env/lib/python3.9/site-packages/azure/storage/filedatalake/_deserialize.py:214, in process_storage_error(storage_error)
    211 error.args = (error.message,)
    212 try:
    213     # `from None` prevents us from double printing the exception (suppresses generated layer error context)
--> 214     exec("raise error from None")   # pylint: disable=exec-used # nosec
    215 except SyntaxError:
    216     raise error

File <string>:1, in <module>

ClientAuthenticationError: (AuthenticationFailed) Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:[redacted]
Time:2022-07-29T23:47:21.0558396Z
Code: AuthenticationFailed
Message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:[redacted]
Time:2022-07-29T23:47:21.0558396Z


```

**Expected behavior**
Listing paths should work without credentials, if the container is configured to allow public access.  This would be consistent with the classic blob storage behavior.

**Comment by jalauzon-msft** [comment]
Hi @jenhagg, thanks for opening the issue. 

Unfortunately, this is by design from the service side. Operations on the `dfs` endpoint such as `get_paths` ([Path List](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/list) from the service) do not support anonymous access.

To work around this, you can use the [azure-storage-blob](https://pypi.org/project/azure-storage-blob/) SDK to utilize the List Blobs API which is supported for anonymous access. The blob SDKs `list_blobs` should return most of the same information as datalake `get_paths`. Here is a sample of that:
```python
from azure.storage.blob import BlobServiceClient

account_name = "<ACCOUNT_NAME>"
file_system = "<ADLS Filesystem Name>"
# Note the use of 'blob' here
bsc = BlobServiceClient(account_url=f"https://{account_name}.blob.core.windows.net")
container_client = bsc.get_container_client(file_system)
paths = list(container_client.list_blobs())
```

NOTE: Using the blob SDK for an ADLS Gen2 (HNS enabled) account is generally not supported as not all operations will behave as expected but, in this case, it may meet your needs.

Hopefully that workaround can work for you to help unblock your scenario. Thanks!

**Comment by jenhagg** [comment]
Hi @jalauzon-msft, thanks for the suggestion. I have confirmed that this will work for my use case. Just wondering what level of support/stability I should expect using the `azure-storage-blob` sdk for an HNS enabled account? E.g. is the `list_blobs` operation supported, but not necessarily others? Or is support for any operation subject to change.

**Comment by vincenttran-msft** [comment]
Hi @jenhagg, I am glad that the above suggestion is sufficient for your use case! In regard to the level of support one should expect using the `azure-storage-blob` SDK for an HNS enabled account, because this is not an officially supported scenario, support for any operation is subject to change and thus no real stability can be guaranteed. 
In general, our only officially supported scenarios (and items we can provide support on) are the usage of `azure-storage-blob` with flat namespace storage accounts, and `azure-storage-file-datalake` with hierarchical namespace storage accounts.

With that being said, hopefully we have been able to address all of your concerns, and with that I will continue with the closure of the ticket. Please feel free to reopen the ticket if you feel that it has not been resolved and thank you for your inquiry!

Thanks!
