### ISSUE TITLE
explore management api link returns 404

### ISSUE THREAD

**Issue by lozanov95** [Azure/azure-sdk-for-python#25739]
Explore management API link in the article doesn't work - https://docs.microsoft.com/en-us/python/api/overview/azure/authorization/management It goes to a 404 page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ae83ca-48ac-213a-611d-1efd1d41b170
* Version Independent ID: 33c94d96-111b-f933-69c1-a811fe0a78fb
* Content: [Azure Authorization SDK for Python](https://docs.microsoft.com/en-us/python/api/overview/azure/authorization?view=azure-python)
* Content Source: [docs-ref-services/latest/authorization.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/authorization.md)
* Service: **authorization**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by annatisch** [comment]
Thank you for reporting @lozanov95!
@msyyc , @lmazuel - do you where we can repoint this reference URL to?

**Comment by msyyc** [comment]
I also find some similar broken link:
https://docs.microsoft.com/en-us/python/api/overview/azure/webapps/management
https://docs.microsoft.com/en-us/python/api/overview/azure/commerce/management
https://docs.microsoft.com/en-us/python/api/overview/azure/batch/management
https://docs.microsoft.com/en-us/python/api/overview/azure/redis/management
https://docs.microsoft.com/en-us/python/api/overview/azure/consumption/management

But this link is effective:
https://docs.microsoft.com/en-us/python/api/overview/azure/containerregistry/management

Since I am not familiar with doc repo, @scbedd could you help us about how to fix these broken link or address relative experts?

**Comment by navba-MSFT** [comment]
@lozanov95 Thanks for reporting this issue. We have created the above PR to fix this. It is currently under review. In the meantime if you have any questions, please feel free to ask.
