### ISSUE TITLE
Azure Blob Storage can't create blob service client for storage accounts in Azure Edge Zone 

### ISSUE THREAD

**Issue by GeorgeH-MS** [Azure/azure-sdk-for-python#25766]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.13.1
- **Operating System**: Windows 11
- **Python Version**: 3.8.6

**Describe the bug**
New a BlobServiceClient for a storage account created in Azure Edge Zone with account URL and credential, raised ValueError("Unable to determine account name for shared key credential")

**To Reproduce**
1. Create a storage account in Edge Zone
2. Retrieve the account URL and key of the storage account
3. New a BlobServiceClient with the account URL and key.

**Expected behavior**
Be able to create BlobServiceClient for storage accounts in Azure Edge Zone (which was supported in previous version)

**Screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/30331846/185384885-da426a61-5d12-4388-b651-f5db2c0943a0.png)
.

**Comment by GeorgeH-MS** [comment]
Potential issue exists in https://github.com/Azure/azure-sdk-for-python/blob/afce4523ab32e6f3b12bc7f65f2076b99516972e/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py#L87-L94, which hardcoded the storage endpoints

**Comment by Zhupku** [comment]
Any update on this?

**Comment by vincenttran-msft** [comment]
Hi @GeorgeH-MS George, thanks for bringing this issue to our attention and sorry for the delay in response. I believe that the issue does lie with how the parser operates. We are aware of this issue and are working on developing a solution that will not break pre-existing customer workflows and will only be additive in its nature.

For now, I believe this workaround should resolve your issue. As seen [here](https://github.com/Azure/azure-sdk-for-python/blob/7a82567d35ff75d0848553aaf892cf8a00914851/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_service_client.py#L123) for the `credential` parameter, one of the supported types is a `Dict[str,str]`.
Thus, instead of simply providing the account key for the `credential` parameter, one can create a dictionary in this form: 
`CREDENTIAL = {"account_name": ACCOUNT_NAME, "account_key": ACCOUNT_KEY}`

And so in the case I believe `ACCOUNT_NAME` would be `darrendengrr4` and your `ACCOUNT_KEY` would be the key that is in the screenshot above.
Please give that a try and let us know how it goes!

Tagging @Zhupku for visibility of this update.

**NOTE:** @GeorgeH-MS Please consider rotating your keys as you have posted your account information in full.

Thanks!

**Comment by GeorgeH-MS** [comment]
Thanks @vincenttran-msft for suggesting the workaround, it works. But we found the CLI behavior related the Edge Zone was broken. And the regression should be caused by its dependency on Python, which is exactly this issue. So the fix of this issue seems to be critical. Thanks.

**Comment by jalauzon-msft** [comment]
As discussed offline this is not a regression in v12 of the SDK but rather something that needs to be handled in the CLI after their Track2 migration. Closing this issue. Please open a feature request to CLI if this is needed. Thanks.
