### ISSUE TITLE
[ServiceBus] Need type  hints

### ISSUE THREAD

**Issue by SHSongs** [Azure/azure-sdk-for-python#25794]
**Is your feature request related to a problem? Please describe.**
As the python version goes up to version 3.6, I think it would be better to write type hints as well.

**Describe the solution you'd like**
Write the parameter type referring to the [python typing docs](https://docs.python.org/3/library/typing.html)  

**Additional context**
[servicebus example](https://github.com/Azure/azure-sdk-for-python/blob/388efaaa2b8f4a14a4c306dc5ea6f77f1ba7fa6b/sdk/servicebus/azure-servicebus/azure/servicebus/management/_management_client.py#L166)

**Comment by SaidBySolo** [comment]
https://github.com/Azure/azure-sdk-for-python/tree/388efaaa2b8f4a14a4c306dc5ea6f77f1ba7fa6b/sdk/servicebus/azure-servicebus/azure/servicebus/aio

I am trying to migrate type annotations with a focus here.

**Comment by annatisch** [comment]
Thanks for reporting @SHSongs, @SaidBySolo!
Since we officially dropped support for 2.7 at the beginning of 2022, we have slowly been cleaning up legacy code to reflect the latest Python 3 best practices.
While I can't commit to an exact time frame for when the full ServiceBus SDK will have the typehints migrated - rest assured that we are making progress as part of an internal refactor for the AMQP transport.
@swathipil - do you know if we have an exiting open issue for this one?

**Comment by swathipil** [comment]
Yes, we have a related issue here: #25471

**Comment by SaidBySolo** [comment]
Hello @swathipil!
If you haven't already done the migration here servicebus/azure-servicebus/azure/servicebus/aio, i want to contribute.
Do you have any plans?

**Comment by swathipil** [comment]
I haven't already done the migration, so feel free to open a PR and tag me for a review. :)
Thank you!

**Comment by swathipil** [comment]
need to update type aliases as well to the following: https://github.com/Azure/azure-sdk-tools/issues/3138

**Comment by JJHWAN** [comment]
@swathipil 
I changed type annotations to type hints in servicebus/amqp/

I saw your comment to update as following [Azure/azure-sdk-tools#3138](https://github.com/Azure/azure-sdk-tools/pull/4036)

In my case, I cannot find way to apply NewType.
Will these changes to just alright?
