### ISSUE TITLE
[Service Bus] Create Troubleshooting Guide

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-python#25826]
Here is the [template]( https://gist.github.com/JoshLove-msft/4b3ffbc041067602612a2d81fe514a97) that each language can follow to ensure all topics are covered in a consistent way.

As part of this work, we should update relevant exceptions to link out to aka.ms links that point to the corresponding section of the Troubleshooting guide, similar to what we did for [Identity](https://azure.grep.app/search?q=aka.ms&filter%5Brepo%5D%5B0%5D=Azure/azure-sdk-for-net&filter%5Blang%5D%5B0%5D=C%23&filter%5Bpath%5D%5B0%5D=sdk/identity/Azure.Identity/).

**Comment by eqvyoo** [comment]
i am interested in this issue. Can @kyc5644 and i work with it ?

**Comment by kashifkhan** [comment]
> i am interested in this issue. Can @kyc5644 and i work with it ?

Hi @eqvyoo, thank you so much for wanting to help us out with this effort, we really appreciate it 😀. This particular issue would be a little tricky since it requires working with some teams internally etc, which can lead up to a lot of back and forth + rework. I would encourage you to look at some of the other issues within the SDK where engagement can be easier.

Thank you for help :)
