### ISSUE TITLE
Passing kwargs into `ContainerClient.get_blob_client` method

### ISSUE THREAD

**Issue by jinlow** [Azure/azure-sdk-for-python#25871]
**Is your feature request related to a problem? Please describe.**
I have been creating `BlobClient` objects using the `ContainerClient.get_blob_client` method. However, I want to be able to specify any valid parameter that can be passed to the `BlobClient` constructor, specifically the `max_chunk_get_size` argument. However, the `get_blob_client` method does not allow for arbitrary keyword arguments to be passed to the `BlobClient` when it's instantiated.

Essentially I want to be able to do the following.
```python
from azure.storage.blob import ContainerClient
client_ = ContainerClient.from_connection_string(
                conn_str="my connection string", container_name="my container name"
            )
blob_client = client_.get_blob_client("my-blob", max_chunk_get_size=1_000)
```

**Describe the solution you'd like**
I would like the signature of the `get_blob_client` method to change to allow additional kwargs to be passed to the `BlobClient` constructor.

**Describe alternatives you've considered**
The alternative is to set this when instantiating the container client, but I would like this to be able to be dynamic, so every new blob I create from the container client has the flexibility to configure parameters such as `max_chunk_get_size`. Or, I am not sure if there is a way to set these parameters, on the `BlobClient` after it's been instantiated?

**Comment by catalinaperalta** [comment]
Thanks for reaching out @jinlow! Adding @jalauzon-msft to help out with this issue.

**Comment by jalauzon-msft** [comment]
Hi @jinlow James, while I understand the potential need for this, it may be difficult to implement correctly. The idea with the `create_x_client` functions is that everything on the "parent" client carries over into the child client. This includes many things such as configuration settings like `max_chunk_get_size`, pipeline polices, the transport layer, retry settings, etc. There would need to be some mechanism where these, at least certain ones, can be overridden by the presence of `kwargs` which may be the difficult part to get right since these options are set/stored in many different ways. Let us spend some time investigating and thinking this one over and I'll get back to you.

In the meantime, it is technically possible to override values like `max_chunk_get_size` on the new client object if you are okay modifying private members. Here is how this _could_ be done:
```py
blob_client = client_.get_blob_client("my-blob", max_chunk_get_size=1_000)
blob_client._config.max_chunk_get_size = 1_000
```

Since this would be overriding a private member, we cannot guarantee support for it and it could change in the future, but it should work for now and we do occasionally do this in tests. This is also something we could consider making public as a solution to this problem, but we'll need to consider that internally as well.

**Comment by jinlow** [comment]
@jalauzon-msft 
Hi Jacob, thanks for this additional info and context!
That makes sense, I did see the `_config` member and had tested modifying that, and it does seem to work as expected! However, as you point out it has greater potential to break in the future, however I think that might be a good enough solution for now.
Yes, maybe there could be some `update_configuration` method that could be added to these client classes. I think that would be helpful in situations such as this. However, if the decision is made that it would be acceptable to edit the configuration of the client class, maybe it's also OK, to allow the `get_*_client` methods to accept `**kwargs` that would possibly overwrite options of the parent client. Although an `update_configuration` method would probably be more explicit?

**Comment by jalauzon-msft** [comment]
Thanks @jinlow,

An `upload_configuration` function is definitely also a possibility. We can also consider something like this when investigating a solution. The issue with an override via `kwargs` approach is that we may not be able to support all of the `kwargs` that a client constructor would take since not all of them affect the configuration. It is possible to just support the ones we can and document it though so also something we'll consider.
