### ISSUE TITLE
[metricsadvisor] update min dependency package

### ISSUE THREAD

**Issue by wonder6845** [Azure/azure-sdk-for-python#25917]
>ref
>> #25814 
>> #25731

I find a issue during updating about drop python 3.6  at metricsadvisor (ref #https://github.com/Azure/azure-sdk-for-python/pull/25814)

I think it's better updating min dependency package autorest.

-autorest-
https://github.com/Azure/azure-sdk-for-python/issues/25731

please inform me if anything problem found 
Thank you.

**Comment by iscai-msft** [comment]
@wonder6845 metrics advisor currently doesn't use autorest to generate its setup.py, I will work on updating the mindep for metricsadvisor though

**Comment by wonder6845** [comment]
@iscai-msft  Hello, first of all i want to apologize to post a rather unfriendly and not detailed issue.
I want to add the latest dependency package with reference to #25731 
I pull requested drop python 3.6 and I found and It has been found that the Autorest package is not the latest version.
So, if there is no problem, I would like to update the autorest on the metrics advisor, Is it okay?

Thanks 
Hong

**Comment by iscai-msft** [comment]
No worries @wonder6845 , thanks for the clarification!

The setup.py that metrics advisor has actually isn't generated by AutoRest. There are some specific dependencies that we've added, so the SDK author currently has full control of the setup.py, and AutoRest generation won't change anything about the setup.py.

That being said, I'm not opposed to an AutoRest regeneration PR, it has been a while since we've regenerated, and the generated code will change a decent amount. The setup.py will remain the same though with generation, so if you do regenerate please take care to update the setup.py mindep. This isn't high priority though, thanks for asking!

**Comment by xiangyan99** [comment]
Is this still valid?
