### ISSUE TITLE
Azure ML model endpoint rollouts: add `maxUnavailable` and `maxSurge` fields

### ISSUE THREAD

**Issue by janluke** [Azure/azure-sdk-for-python#25938]
**Is your feature request related to a problem? Please describe.**
There's currently no control over how a service rolling update is performed. The k8s deployment configuration says `maxUnavailable: 1` and `maxSurge: 1` (but I've seen multiple pods created at once, so I'm not sure the `maxSurge` value is even respected). For my use case, I'd like to have `maxUnavailable` to 0. Different people may have different needs.

**Describe the solution you'd like**
It'd be great if you added the equivalent of `maxUnavailable` and `maxSurge` (see [here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment)) to `AksWebservice.deploy_configuration`.

**Comment by iscai-msft** [comment]
@azureml-github

**Comment by jiaochenlu** [comment]
Hi @janluke , thansk for your feedback! For your request, I want wo explain that:

1. Since AKSwebservice your are using is our legacy model deploy version, and v1 is only in maintainance right now.
2. Currently we have GA the [new stack v2](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-attach-kubernetes-anywhere#kubernetes-usage-scenarios )that provide the capability of using SDKv2/CLIv2 to deploy your models to be online endpoints, and all new features/requests will be considered in v2.

This requirement has been asked by some other our v2 customers, we will consider this support in v2. If possible, you can migrate to v2 for more feature supports.

**Comment by janluke** [comment]
Thanks for the answer. Closing the issue as we've already decided to stop using azure ml for model deployment.
