### ISSUE TITLE
Azure Blob Module installation issue in azure Virtual machine 

### ISSUE THREAD

**Issue by rushikesh0900** [Azure/azure-sdk-for-python#25993]
1) **Describe the bug**

Azure.storage.blob module 12.9.0 is installed in Python 2.7.13 but still its failing with no module found 

2) ***Code Snippet***

Error added in same issue .

3) **Expected behavior**

Python 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.storage.blob 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named azure.storage.blob

**Setup (please complete the following information):**
 - Python Version: Python 2.7.13
 - SDK Version: azure-storage-blob==12.2.0

Commands we used -->

1-Created a SLES 12 sp4 gen2 VM, as your VM
2-Downloaded pip:
linux:/tmp # wget -c https://bootstrap.pypa.io/pip/2.7/get-pip.py
--2022-08-25 09:14:09--  https://bootstrap.pypa.io/pip/2.7/get-pip.py
3- -Installed pip, and got the same deprecation message, but pip installed successfully (the installed version is 20.3.4 , and the one that does not support Python 2.7 will be version 21.0);
linux:/tmp # python2 get-pip.py
4- linux:/tmp # pip --version
pip 20.3.4 from /usr/lib/python2.7/site-packages/pip (python 2.7)
 
Per the above, the running version of pip will still support python 2.7, only the upcoming pip version 21.0 will not
 
Trying to update pip will not upgrade from 20.3.4 to a newer version:
 
linux:/tmp # pip install --upgrade pip

5 - Installed same package
linux:/tmp # pip install azure-storage-blob

6 - Installed the missing dependency "requests" with version 2.18.4, as asked by azure storage-blob
linux:/tmp # pip install requests==2.18.4

7 - Uninstalled azure-storage-blob:
linux:/tmp # pip uninstall azure-storage-blob

8 - And installed azure-storage-blob again 
linux:/tmp # pip install azure-storage-blob

9  - But yes after this still we are getting error like : no module found

**Comment by vincenttran-msft** [comment]
Hi @rushikesh0900 , thanks for bringing this to our attention. We'll investigate and get back to you ASAP.

Thanks!

**Comment by rushikesh0900** [comment]
> Hi @rushikesh0900 , thanks for bringing this to our attention. We'll investigate and get back to you ASAP.
> 
> Thanks!

**Comment by jalauzon-msft** [comment]
Hi @rushikesh0900, module errors such as this typically indicate a setup issue. There are a couple of things that I suspect could be the culprit here:

- You may have multiple Python's/pips installed on the system and where you are using `pip install` is not the same location where your Python code is running. We can see that your `pip` is coming from `/usr/lib/python2.7/site-packages/pip (python 2.7)`. Can you please verify your Python script is running in the same envorment?
  - You can check where your currently executing Python executable from inside your script using something like below.
  - You may also want to check you `path` to see where things are pointing.

```py
import os
import sys
print(os.path.dirname(sys.executable))
```

- Using `pip install azure-storage-blob` I would expect would give you the latest version of blob (currently 12.13.1) which does not support Python 2.7 and should give you an install error. This may be causing an issue. We recommend using Python 3, since 2.7 is deprecated, and installing the latest version of blob but the last version of blob to support 2.7 should be 12.9.0.
