### ISSUE TITLE
AttributeError when using invalid base64-encoded AccountKey for BlobClient.download_blob

### ISSUE THREAD

**Issue by k-oellers** [Azure/azure-sdk-for-python#26028]
- **Package Name**:  azure.storage.blob
- **azure.storage.blob**: 12.13.1
- **12.13.1**: Windows 10
- **Python Version**: Python 3.7

**Describe the bug**

If an invalid base64-encoded AccountKey is used for downloading blobs, after some time the following exception is thrown instead of the correct error message:

AttributeError: 'NoneType' object has no attribute 'status_code'.

This is because the raised exception AzureSigningError: 'Invalid base64-encoded string: number of data characters (85) cannot be 1 more than a multiple of 4, Error: Invalid base64-encoded string: number of data characters (85) cannot be 1 more than a multiple of 4' has no response object

**To Reproduce**
Use AccountKey with 87 signs for authentication:

```
conn_str = '...;AccountKey=XWGse8ad1sfge2vSvesPlsFF+aswxxCLs7a9s88wdfsgdFDEExvrfe+eFXXsaweRGHbjnUBsnBv15ws05w8sa==;...'
with BlobClient.from_connection_string(conn_str, container_name=container, blob_name=name) as client:
    blob = client.download_blob()
```

**Expected behavior**
AuthenticationError response

**Comment by kashifkhan** [comment]
Thanks for the feedback @k-oellers , we’ll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @k-oellers Konstantin, thanks for the report!

I took a look at this and can confirm that this is a bug. It is specific to `download_blob` since we have an additional check against status code on a failed request, but we are missing the check for `None` first. Other operations should properly show the `AzureSigningError`.

We will work to get this addressed in the upcoming release, thanks again!

---

An additional note that should probably be tracked separately is that we are retrying these client-side authentication errors which is what is causing the delay before you see the error. We probably should not be retrying these types of errors so I will follow-up and investigate that as well.
