### ISSUE TITLE
Add support for service bus send message batch

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-sdk-for-python#261]
http://msdn.microsoft.com/en-us/library/azure/dn798894.aspx

**Comment by lmazuel** [comment]
Just had a discussion with the ServiceBus team. For problem around performance and missing features, the current recommendation from the ServiceBus team is to use AMQP instead of HTTP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/

The ServiceBus team were not able to propose better performance using HTTP, due to HTTP limit.
