### ISSUE TITLE
Why was Extractive Text Summarization removed from azure-ai-textanalytics==5.2.0b5

### ISSUE THREAD

**Issue by isham-iqbal** [Azure/azure-sdk-for-python#26156]
I found a PR with that implementation however I couldn't open it (getting unicorn error page). Is there a specific reason for doing it?

**Comment by kristapratico** [comment]
Hi @isham-iqbal, thanks for reaching out. The Extractive Summarization feature is a beta/preview feature. azure-ai-textanalytics==5.2.0b5 was the first version to target the stable/GA version of the Language service API (2022-05-01). Since this was a stable version, only GA features were included and so Extractive Summarization was removed. You can still access the feature if you install azure-ai-textanalytics==5.2.0b4. Let me know if you have any questions.

**Comment by isham-iqbal** [comment]
Hi, yes I was able to access the functionality via azure-ai-textanalytics==5.2.0b4. Just keen to know if this feature will be available in any future GA packages.

**Comment by kristapratico** [comment]
@isham-iqbal it will be added back in a future release. I do not have a timeline for you as of yet.
