### ISSUE TITLE
ImportError: cannot import name 'DocumentModelAdministrationClient'

### ISSUE THREAD

**Issue by dsabarinathan** [Azure/azure-sdk-for-python#26524]
- **Package Name**: azure-ai-formrecognizer-3.1.2
- **Package Version**: azure-ai-formrecognizer-3.1.2
- **Operating System**: windows 10
- **Python Version**:  Python 3.6.4 |

**Describe the bug**
A clear and concise description of what the bug is.  I am trying to import the  **from azure.ai.formrecognizer import DocumentModelAdministrationClient**  but I am getting the below error. 

**To Reproduce**
1. 

`from azure.ai.formrecognizer import DocumentModelAdministrationClient

I used the below code for training the custom model. But the import packages are not working.

https://github.com/Azure/azure-sdk-for-python/blob/azure-ai-formrecognizer_3.2.0b3/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2-beta/sample_build_model.py

![image](https://user-images.githubusercontent.com/40907627/192911977-7cace912-eb32-4884-818b-68222f93d8ae.png)

**Comment by mccoyp** [comment]
Hi @dsabarinathan, thank you for opening an issue! I'll tag the package owners for a second opinion, but it looks like the `DocumentModelAdministrationClient` was added to the library in version [3.2.0b1](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md#320b1-2021-10-07) and isn't available in version 3.1.2. I would recommend updating your package to version 3.2.0 (or one of the version's betas, if necessary and feasible for your scenario).

**Comment by catalinaperalta** [comment]
Hi @dsabarinathan! Thanks for the question. @mccoyp is right, the `DocumentModelAdministrationClient` was added in version 3.2.0. If you can do so, please update to this version of the package to get the latest clients and operations which also target the latest service version and showcase new features. I recommend using `3.2.0` directly since this is our latest stable package release.

**Comment by dsabarinathan** [comment]
@catalinaperalta, Thank you for the reply. I will use the new version.

**Comment by dsabarinathan** [comment]
@catalinaperalta, When I gave the SAS URL for my blob. I am getting the below error. 

![image](https://user-images.githubusercontent.com/40907627/193031327-1d236fce-7382-4597-be08-b33db535ada0.png)


My Blob container has so many folders. I want to give a specific folder for training the custom model. 

![image](https://user-images.githubusercontent.com/40907627/193031123-4bcdda13-a26f-4e62-b72f-ab77ef48f09c.png)

**Comment by catalinaperalta** [comment]
Hi @dsabarinathan, the build document model method supports a `prefix` kwarg which would help in this case, see the docs [here](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-ai-formrecognizer/latest/azure.ai.formrecognizer.html#azure.ai.formrecognizer.DocumentModelAdministrationClient.begin_build_document_model). Also, it would be best to move on to the stable version of the package which is `3.2.0` since the betas had changes that no longer exist in the stable package version. There are changes in the stable package that are not included in the betas, such as some method renames.

**Comment by dsabarinathan** [comment]
Hi @catalinaperalta  , when I tried to install the 3.2.0 on local. I am getting the below error. 

![image](https://user-images.githubusercontent.com/40907627/193163105-c93b3d21-ea3b-423f-9367-8c8bdd53f9aa.png)

**Comment by catalinaperalta** [comment]
Hi @dsabarinathan! Could you try the command using the `--upgrade` flag?

**Comment by dsabarinathan** [comment]
@catalinaperalta . It is working now. Thank you. I am closing the issue now.
