### ISSUE TITLE
Azure OCR JSON file creation 

### ISSUE THREAD

**Issue by dsabarinathan** [Azure/azure-sdk-for-python#26592]
- **Package Name**:  DocumentAnalysisClient
- **Package Version**:  3.2.0b5
- **Operating System**: windows 10 
- **Python Version**: Python 3.6.4

**Describe the bug**
how to create the below ocr.json file using the azure documentanalysisclient or other OCR functions.  when I load the blob folder in form recognizer studio, it creates the below ocr json for the pdf document automatically. I want to create the same JSON ocr file with the azure python ocr function. 

[train_docs.zip](https://github.com/Azure/azure-sdk-for-python/files/9697712/train_docs.zip)

**To Reproduce**
I used the below code but it is not returning the results in the OCR json format. 
https://learn.microsoft.com/en-us/python/api/azure-ai-formrecognizer/azure.ai.formrecognizer.documentanalysisclient?source=recommendations&view=azure-python
**Expected behavior**

**Comment by pvaneck** [comment]
Hey, @dsabarinathan! Thanks for opening an issue. I can tag people who should be able to help. However, from a cursory look, have you tried looking through the form recognizer samples? I know we have one [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_convert_to_and_from_dict.py#L60) that appears to outline the process of going converting some results to JSON.

**Comment by catalinaperalta** [comment]
Hi @dsabarinathan! Thanks for the question. The way to create the OCR files is through Form Recognizer Studio. Those files can then be used to train a new custom analysis model with the SDK. You can use `begin_build_document_model()` on  `DocumentModelAdministrationClient` to do so. The `DocumentModelAdministrationClient` has methods that can be used to build, compose, copy, get, list, and delete document models, among others. Since the OCR files need to be labeled, the user interface in Form Recognizer Studio provides a way to easily do that. For unlabeled document analysis you could use `begin_analyze_document()` on `DocumentAnalysisClient` with the `prebuilt-document` model ID.

**Comment by dsabarinathan** [comment]
Thank you for the suggestion. @pvaneck @catalinaperalta . 

The below code is working for me. 
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_convert_to_and_from_dict.py#L60
