### ISSUE TITLE
Bug azure-identity version 1.11.0 vs 1.10.0 

### ISSUE THREAD

**Issue by mikeleuer** [Azure/azure-sdk-for-python#26602]
- **Package Name**: azure-identity
- **Package Version**: 1.11.0
- **Operating System**: Linux (https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/python/python39/python39-core-tools.Dockerfile)
- **Python Version**: 3.9

**Describe the bug**
Version 1.10.0 of azure-identity works great DefaultAzureCredential works great, but after updating to 1.11.0 it fails when using it to access keyvault. See example bellow.

**To Reproduce**
Using (https://github.com/Azure/azure-functions-python-library and the docker file https://github.com/Azure/azure-functions-docker/blob/dev/host/4/bullseye/amd64/python/python39/python39-core-tools.Dockerfile)

Use AZ LOGIN to login

```
        credential = DefaultAzureCredential()
        key_client = SecretClient(
            vault_url= "********",
            credential=credential
        )
        print(key_client.get_secret("*****").value)
```

**Expected behavior**
Be able to login

**Screenshots**
```
Exception has occurred: ClientAuthenticationError       (note: full exception trace is shown but execution is paused at: _run_sync_func)
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
	SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
	VisualStudioCodeCredential: The current credential is not configured to acquire tokens for tenant [REMOVED]. To enable acquiring tokens for this tenant add it to the additionally_allowed_tenants when creating the credential, or add "*" to additionally_allowed_tenants to allow acquiring tokens for any tenant.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Additional context**
I have tried clearing login, using az extension in vs code to login, a lot of work arounds tried but nothing works. The only fix is to switch to 1.10.0

**Comment by mikeleuer** [comment]
@pvaneck 
That seems to fix the issue, thank you!  

How do I see what the default tenant is assigned to my DefaultAzureCredential()? How to set my default tenant in code?

**Comment by pvaneck** [comment]
Each credential type has a different way of determining the tenant ID. For example, EnvironmentCredential will check for the `AZURE_TENANT_ID` envvar. AzureCliCredential will check for the tenant of the current logged in user (`az account show`).

As you can probably see by the error message, DefaultAzureCredential is going through an authentication flow, successively checking different credentials until one works. However, because of the multi-auth breaking change, when VisualStudioCodeCredential is checked, the flow is halted due to the ClientAuthenticationError. This is likely raised because the tenant ID is defaulting to the special ID "organizations" unless you have "azure.tenant" in your vscode settings,json set as the correct tenant ID. 

Ideally, we'd just continue on with the flow, but even if you were logged in via Azure CLI, due to the flow order and premature halting, the CLI credentials are never checked (as VSCodeCred is checked before AzureCliCred). There is current ongoing discussion about changing the behavior of DAC to always continue the flow despite an error being raised by a checked credential.

VisualStudioCodeCredential has a few issues right now due to implementation changes in the VS Code Azure Account extension. The next `azure-identity` release will remove it from the [DAC token chain](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity#defaultazurecredential) until we can get it properly working again. This will help alleviate some of the pain points for users trying to use DAC with the Azure CLI. 

In the meantime, I will add an additional troubleshooting entry to the DAC troubleshooting section regarding this VSCodeCred shenanigans.

**Comment by mikeleuer** [comment]
Thank you for the explanation.

**Comment by pvaneck** [comment]
@nicolaschaillan It's possible you have have environment variables configured (i.e. `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, `AZURE_TENANT_ID`, etc.), but those credentials are invalid which causes a `ClientAuthenticationError` and halts the DefaultAzureCredential flow. This was by design in order to surface possible misconfigurations/errors to the user because if those envvars are set, it is assumed that the user wants to use them. If your intention is not to use them, then you can try unsetting one of the checked envvars like `AZURE_CLIENT_ID`. This should then cause `EnvironmentCredential` to be skipped and the next credentials in the DefaultAzureCredential flow to be checked.
