### ISSUE TITLE
[KeyVault] Update the LRO link that polls on recovery of deleted secrets

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-python#26707]
https://github.com/Azure/azure-sdk-for-net/issues/31581 for more information.

**Comment by mccoyp** [comment]
This doesn't seem to be an issue in the Python SDK since our recovery pollers across KV libraries don't use the resource version in polling requests.

Secrets: https://github.com/Azure/azure-sdk-for-python/blob/47133e7957fe731c69ca7bcb4299b45d7da5e62d/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py#L459-L462

Keys: https://github.com/Azure/azure-sdk-for-python/blob/47133e7957fe731c69ca7bcb4299b45d7da5e62d/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py#L552-L558

Certificates: https://github.com/Azure/azure-sdk-for-python/blob/47133e7957fe731c69ca7bcb4299b45d7da5e62d/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py#L335-L338
