### ISSUE TITLE
[BUG Bash]

### ISSUE THREAD

**Issue by tomek2311** [Azure/azure-sdk-for-python#26792]
**Describe the bug**
I am running 2 containers in **Windows** (10) environemnt setup as iotedge:
- first: my application (APP) that receives messages and stores data in azure blob storage (APP is running in container)
-  second: mcr.microsoft.com/azure-blob-storage:latest

App code is written in python3 
I have installed blob storage package package :(pip3 install azure-storage-blob)  and after that created directory "iotedgeblobstorage"
Created binding in my deployment file

When I try to send data from APP to BLOB the file is created (I can see it in my BloclBlob/APP dicrectory but it is empty 

This issue happens on **WINDOWS** only I have tried the same setup (with same docker images) deployed in LINUX env (different setup for bindings and so on) - but it worked

***Exception or Stack Trace***
Add the exception log and stack trace if available
------------ Axecptions from APP ----------------------
files with exceptions for blob and app are attached

[app_logs.txt](https://github.com/Azure/azure-sdk-for-python/files/9769152/app_logs.txt)
[blob_logs.txt](https://github.com/Azure/azure-sdk-for-python/files/9769153/blob_logs.txt)

**To Reproduce**
send message from APP to blob storage

***Code Snippet***
Add the code snippet that causes the issue.

  see can we read the file from BLOB storage ?

   blob_client = self.container_client.get_blob_client(fileName)

    try:
      blob_client.get_block_list()
    except ResourceNotFoundError as ex:
      # Note, blob does not exist but we can access container,
      # save the file
      print("Uploading data into: ", fileName)
      blob_client.upload_blob(data=StringIO(str(json.dumps(data))).getvalue())
      return
    except Exception as ex:
      info = "Error while accessing data from:" + str(fileName)
      print(info)
      print(ex)
      return

    #looks like blob already exists, delete it and put new data
    blob_client.delete_blob()
    print("Uploading data into: ", fileName)
    blob_client.upload_blob(data=StringIO(str(json.dumps(data))).getvalue())

I dot not see delete_blob() being called ever in Windows env  (even if empty file is present)

**Expected behavior**
Data should be stored in the file

**Screenshots**
N/A

**Setup (please complete the following information):**
 - Python Version: [e.g. Python 3.8]
 - SDK Version: [e.g. azure-mgmt-resource-15.0.0b1]
using: arm32v7/python:3.8-slim-buster to build my docker image
Not sure about SDK
development of this test is done in visual studio code
running Docker Desktop 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vincenttran-msft** [comment]
Hi @tomek2311, thanks for your inquiry. Unfortunately, I am having a little bit of a difficult time understanding what exactly your issue is. If you could please respond with the following information, it would help greatly in diagnosing the issue and reaching a resolution!

1. Version of SDK used (it seems like you are using `azure-storage-blob`)
2. Provide the sample upload code
3. Provide the sample download code

Furthermore, if you could just clarify what the issue is. Is the issue that you are uploading a file from your 'app' and it is not showing up in your container? 

Thanks!

**Comment by tomek2311** [comment]
The issue on Windows 10 only:
when writing into blob storage from another container, the file is created
but nothing is written (file size is 0).
The same code executed in redhat works great, no problems at all.
I suspect that problems could be with permissions


setup in deployment file:
"azureiotblobstorageoniotedge": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azure-blob-storage:latest",
              "createOptions": {
                "Env": [
                  "LOCAL_STORAGE_ACCOUNT_NAME=iotedgeblobstorage",
                  "LOCAL_STORAGE_ACCOUNT_KEY="....value..."
                ],
                "HostConfig": {
                  "Binds": [
                    "c:/Users/etomdre/iotedgeblobstorage:/blobroot"
                  ],
                  "PortBindings": {
                    "11002/tcp": [
                      {
                        "HostPort": "11002"
                      }
                    ]
                  }
                }
              }
            }
          }
1. I am using Azure-storage-blob: (
mcr.microsoft.com/azure-blob-storage:latest)
2. code
--- creation
self.blob_service_client =
BlobServiceClient.from_connection_string(self.connectionString)

    # in case of unknown exception - exit, aoiformatter should be restarted
by system
    try:
      self.container_client = None
      # Create the container
      print('Creating container: '+ self.storageName)
      self.container_client =
self.blob_service_client.create_container(self.storageName)
      self.properties       =
self.container_client.get_container_properties()
      print('blob storage container properties: \n'+str(self.properties))
    except ResourceExistsError:
      print("Container already exists: ", self.storageName)
      self.container_client =
self.blob_service_client.get_container_client(self.storageName)
      self.properties = self.container_client.get_container_properties()
      print('blob storage container properties: \n'+str(self.properties))

-- upload
def saveData (self, fileName, data):

    # can we read the file from BLOB storage ?
    blob_client = self.container_client.get_blob_client(fileName)

    try:
      blob_client.get_block_list()
    except ResourceNotFoundError as ex:
      # Note, blob does not exist but we can access container,
      # save the file
      print("Uploading data into: ", fileName)

blob_client.upload_blob(data=StringIO(str(json.dumps(data))).getvalue())
      return
    except Exception as ex:
      info = "Error while accessing data from:" + str(fileName)
      print(info)
      print(ex)
      return

    #looks like blob already exists, delete it and put new data
    blob_client.delete_blob()
    print("Uploading data into: ", fileNam

- download
 we are not there yet - I believe when uploading is done, downloading will
be OK

Thanks, Tomasz

**Comment by vincenttran-msft** [comment]
Hi @tomek2311 Tomasz, I am still a little unclear on where the issue lies. If the same code provided executes successfully on your redhat environment and unsuccessfully Windows 10, then my suspicion is that this is **not** an SDK issue and _instead_ likely a configuration issue (i.e. your redhat env. is setup properly whereas your Windows 10 env. is not) or a misunderstanding of how to utilize the Python SDK properly.

To help rule out using the possibility of using the Python SDK improperly:
[Here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob/samples#readme) is a link to  our sample code which includes the functionality you are attempting to do (namely setting up a container, uploading a blob, and deleting a blob in `blob_samples_hello_world.py` found [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py)). Please take a look at the sample and see if you are able to identify any differences between your workflow and the suggested workflow that may be the root cause of your issue.

Additionally, to further clarify some of the functions you are using:

- `get_blob_client` [API](https://github.com/Azure/azure-sdk-for-python/blob/96b6314d61e1062300d8412cf9ba5e92cdc586a0/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L1660) returns a `BlobClient` to interact with a blob matching the name provided to param `blob` when calling this API. At this point, there is no data associated and no file created, but simply a `BlobClient` created with the intention of interacting with a `blob` matching the name provided to param `blob`
- `upload_blob` [API](https://github.com/Azure/azure-sdk-for-python/blob/96b6314d61e1062300d8412cf9ba5e92cdc586a0/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L591) is when the `BlobClient` previously mentioned provides the data to upload through param `data` and actually creates the file that will appear in your container on Azure Storage

With that being said, hopefully the provided sample and taking a look back through your code and/or environment configuration can help you alleviate any issues you are running into with using the Python SDK. It may also be helpful to open up an issue on the [iotedge repository](https://github.com/Azure/iotedge) if you believe this is a configuration issue, as they will be able to better assist with iotedge configuration issues there, as this repository is only for actual Python SDK (client-side) issues.

Thanks!
