### ISSUE TITLE
list_blobs typo on Parameter 'include'

### ISSUE THREAD

**Issue by jlester-msft** [Azure/azure-sdk-for-python#26816]
list_blobs has a typo for the Parameter 'include':
`or str include [list](str]`
Should be:
`include list[str] or str`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37584723-65eb-0794-8ec5-fcae40b28717
* Version Independent ID: 21d8c29d-77a6-6743-25b2-1cbf855e37a3
* Content: [azure.storage.blob.ContainerClient class](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-list-blobs)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml)
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by jalauzon-msft** [comment]
Hi @jlester-msft, thanks for the report.

These docs are auto-generated from our code docstrings and this was fixed in code a while back in #25335. It can usually take some time for the docs to update but I would have expected it to happen by now. I'll investigate why the docs page isn't updated yet. Thanks.

**Comment by jalauzon-msft** [comment]
The docs have been updated to reflect that latest changes which has improved the `include` documentation but the type hint is still missing. This was due to a small error in the docstring has been addressed as part of #26836.

Once #26836 is merged and released, this doc should eventually be entirely fixed.
