### ISSUE TITLE
[Doc] misunderstanding in test proxy

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#26883]
in https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/test_proxy_migration_guide.md#fetch-environment-variables, it indroduces `EnvironmentVariableLoader` but there is no sample to show how to use it. And the [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/tables/azure-data-tables/tests/preparers.py) contains nothing about it.
![image](https://user-images.githubusercontent.com/70930885/196327480-c41e1f8a-9b14-4598-a45d-4dd5316f54db.png)

 This issue causes confusion of customer:
![image](https://user-images.githubusercontent.com/70930885/196327235-8e27935f-2140-4721-bc57-af46c70d87c5.png)
So we hope to update the doc to improve usage experience of customers

**Comment by mccoyp** [comment]
Thank you for opening an issue, @msyyc! I agree that the documentation here is unfortunately sparse; the Tables preparers that are linked to in that section do use the `EnvironmentVariableLoader`, but they use its outdated alias (`PowerShellPreparer`). That's a bit confusing, so I'll leave this issue open to track using a better example.

As for documentation about the `EnvironmentVariableLoader` itself, rather than generally linking to the `TestResources` script documentation, I have a separate tracking issue: https://github.com/Azure/azure-sdk-for-python/issues/24934
