### ISSUE TITLE
Duplicate code snippet: storage

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#26900]
storage\azure-storage-blob\samples\blob_samples_authentication.py:create_blob_service_client_oauth

**Comment by vincenttran-msft** [comment]
Hi @xiangyan99 could you please clarify what the issue is? I see that the same tags
`# [START create_blob_service_client_oauth]` and `# [END create_blob_service_client_oauth]` appear twice, but I believe the two samples provide two different use cases (the first one using `ClientSecretCredential`, the other using `DefaultAzureCredential`). Please correct me if I am misunderstanding 😄

**Comment by xiangyan99** [comment]
Yes. The problem is the same tag. :)

Same tag confuses who references the snippet.

Please rename one of them to make sure they have different tags.
