### ISSUE TITLE
[CLU] authoring LROs may need return types

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-python#26933]
per @heaths

> After regenerating CLU for 2022-10-01-preview, I see the following method signatures and want to confirm they are right.	
AssignDeploymentResources -> LRO (no result)
DeleteDeploymentFromResources -> LRO (no result)
ExportProject -> LRO (project result)	
GetAssignDeploymentResourcesStatus -> job status
GetAssignedResourceDeployments -> pageable (deployments results)
GetDeploymentDeleteFromResourcesStatus -> job status
GetDeploymentResources -> pageable (deployment resources results)
GetLoadSnapshotStatus -> job status
GetUnassignDeploymentResourcesStatus -> job status
LoadSnapshot -> LRO (no result)
UnassignDeploymentResources -> LRO (no result)

**Comment by heaths** [comment]
@mikaelsitruk @mhurst-microsoft could you help answer this? From looking over the added job status monitors I don't think these are wrong as authored, but confirmation would be appreciated.

**Comment by mhurst-microsoft** [comment]
Hi Heath - can you provide the reference / link?

Matt
________________________________

**Comment by heaths** [comment]
Sorry, but I'm not sure to what link you reference. The description in the original issue post lists the newly-added CLU authoring operations and what those operations result in. For LROs, for example, the operation returns a 202 with an `Operation-Location` header; however, for *some* operations in the SDK we end up polling that location until a terminal state is found, then we GET a resource - the final state URI, if you will. So where I say, "LRO (no result)" it means there was no obvious final state URI and I just wanted to confirm that was correct. Most of these long-running operations seem like they don't *eventually* return a model beyond the state monitor. Is that correct?

**Comment by mikaelsitruk** [comment]
I cannot really answer for CLU authoring, but LRO without a job status seems strange.

**Comment by heaths** [comment]
The LRO has job status. I'm asking if any of these LROs eventually result in a model. Example flow:

1. POST returns an Operation-Location
2. While status != terminal, GET operation location
3. If status == success, GET ??? to get final result

Alternatively, the status object might also end up with extra properties when status == "success", though those are technically supposed to be nested within a "results" property: https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs

Mainly, what we're wondering is whether our code generator did the right thing here. None of these LROs return anything more than a job status. Who could help confirm that?

**Comment by mhurst-microsoft** [comment]
It missed my attention that this was an authoring question - @Hadeer ***@***.***> to field this one.

Matt
________________________________

**Comment by mhurst-microsoft** [comment]
+Abdelrahman., DRI to check the issue.

**Comment by mhurst-microsoft** [comment]
Hello,

For such LROs that should return results (e.g., export operation) you'll find "resultUri" property next to the "status" when you reach a terminal state, you can hit that "resultUri" to get your model.
Please let me know if that answers your questions.
From: Hadeer Magdy ***@***.***>
Sent: Thursday, November 3, 2022 12:08 PM
To: Matthew Hurst ***@***.***>; Azure/azure-sdk-for-python ***@***.***>; Azure/azure-sdk-for-python ***@***.***>
Cc: Mention ***@***.***>; Basma Emara ***@***.***>; Abdelrhman Magdy ***@***.***>
Subject: RE: [Azure/azure-sdk-for-python] [CLU] authoring LROs may need return types (Issue #26933)

+Abdelrahman., DRI to check the issue.

**Comment by kristapratico** [comment]
@mhurst-microsoft does that mean our above assumptions are correct? And only in the situation of a JobState returning a resultUri, we should follow that Uri?

**Comment by heaths** [comment]
Such an LRO is not supported by our code generators, nor is standard. See https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-long-running-operation-options for what is supported. The standard is actually [defined here](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs).

Since we're generating DPGs, this is not something we currently can support, and have already GA'd SDKs with LROs either returning just a job status or, when following our current standard or older ARM standards, whatever LRO is supposed by the `final-state-via` documented above (the first link).

@johanste any suggestions?

**Comment by mhurst-microsoft** [comment]
Please work with @Hadeer ***@***.***> on authoring related topics.

Thanks,

Matt
________________________________

**Comment by heaths** [comment]
@hadeer if we could find a way to support this - and we may have to because it's an authenticated call, for which our client is configured already - could you describe why CLU only supports the "format=Conversation" query parameter pair, while "format" for Question Answering supports "csv", "tsv", and "json"? This is incongruent and a little confusing. Comparing with QA and looking at [your swagger](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/40f5247a48ff1eec044c8441c422af0628a8a288/specification/cognitiveservices/data-plane/Language/preview/2022-10-01-preview/analyzeconversations-authoring.json), seems "Conversation" should be valid for your `assetKind` property.

/cc @mayurid @peytonfraser

**Comment by heaths** [comment]
@johanste, @hadeer, would it make sense to effectively copy "Conversation" and "Luis" enums to `assetKind` and add support for "json", "tsv", and "excel" like QA has to `format` but still support "Conversation" and "Luis" as JSON-only. While we can't fix the past, we can improve the future and make QA and CLU consistent.

**Comment by ziyadss** [comment]
> if we could find a way to support this - and we may have to because it's an authenticated call, for which our client is configured already

How can it be supported? Do we have to make changes on our side? Since the APIs are GA'd, any changes would have to be non-breaking. I'll look into the supported LRO polling methods and see what can be done there.

> could you describe why CLU only supports the "format=Conversation" query parameter pair

`format` can be "Conversation" or "Luis", for the import API it lets us know if we're dealing with a CLU project file, or one that's migrating from LUIS. It's still a query parameter for the export API but only "Conversation" format exports are currently allowed.

> seems "Conversation" should be valid for your `assetKind` property.

The `assetKind` property indicates which project assets to include in the exported project, it can take values of "intents", "entities", "utterances", "conversations", or "*", the last meaning to include assets of the four kinds.

**Comment by heaths** [comment]
About support, I was talking specifically about the SDK. Even then, I don't think there's a good way to solve this. But please make sure LROs follow [guidance](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs) henceforth so that our SDKs do the right thing. And we would've supported even this LRO though it's an older LRO style, except that the "resultUrl" property was non-standard. It should've been, IIRC, `resourceLocation`. I can't find the docs for this older LRO style, so that name is only from memory.

`format` for other Language services was the export file format. Clearly it's too late to change now, though there could be a back compat story but maybe it's not worth it.

Can you update the swaggers on `assetKind` to document those values? Even if you don't make an enum and just document them, that's something. Right now there's no way for the customer to know how to use `assetKind` in the REST API or SDK.

**Comment by kristapratico** [comment]
Created a work item in DO to update `assetKind` with possible values: https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/16378155
