### ISSUE TITLE
AppendBlob doesn't works with .txt files

### ISSUE THREAD

**Issue by mkhusid** [Azure/azure-sdk-for-python#27161]
`ContainerClient.upload_blob` method doesn't work correctly when using `blob_type == 'AppendBlob'` for blobs that has `.txt ` file extension. It throws the next exception:
`ResourceExistsError: The blob type is invalid for this operation.`
If the blob extension has another format, e.g. '.csv', everything works fine despite the source files being in the '.txt' format.

If that is expected behavior for TXT files, at least it should have a more informative error message, because the current one is confusing ('The blob type' can refer to the blob types from the package itself, not the file format).

From my perspective, it's a problem that should be fixed and I can't see any reason why TXT files can't be treated as any other blobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37584723-65eb-0794-8ec5-fcae40b28717
* Version Independent ID: 21d8c29d-77a6-6743-25b2-1cbf855e37a3
* Content: [azure.storage.blob.ContainerClient class](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-get-blob-client)
* Content Source: [docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-storage-blob/azure.storage.blob.ContainerClient.yml)
* Service: **storage**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
Hi @mkhusid - Thanks for your feedback! We'll take a look at this asap!

**Comment by vincenttran-msft** [comment]
Hi @mkhusid thanks for your inquiry. As mentioned above by @swathipil, if you could provide the version of the `azure-storage-blob` package that would be great. In any case, it is always recommended to use the latest version when available.

Unfortunately, I was unable to reproduce your findings locally on our end. If possible, could you please attach a code sample (with sensitive information redacted) in order to get a better idea of what exactly you are doing to encounter this error? I attempted to reproduce your findings similar to what is documented in our code sample regarding `AppendBlob`:
https://github.com/Azure/azure-sdk-for-python/blob/87fa4a73fd098116fbeecfe387fafe02b8c0545d/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py#L166-L189

And can confirm that the sample is working as expected. Note how in the sample both the `SOURCE_FILE` and `DEST_FILE` are both `.txt` extension, and so I would have expected them to **fail** as described by your original post.
https://github.com/Azure/azure-sdk-for-python/blob/87fa4a73fd098116fbeecfe387fafe02b8c0545d/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py#L23-L24

I also made an adjustment to the sample code when testing, namely to change the blob stored on Storage from `myappendblob` (as seen in the original sample) to `myappendblob.txt` to see if the `.txt` extension had an adverse effect. I was still unable to reproduce your error.
https://github.com/Azure/azure-sdk-for-python/blob/87fa4a73fd098116fbeecfe387fafe02b8c0545d/sdk/storage/azure-storage-blob/samples/blob_samples_hello_world.py#L180

With that being said, please take a look at the sample and see if perhaps you are doing something incorrectly, and if you are still unsure, providing a code sample and the package version of `azure-storage-blob` would be a great next step to help us diagnose this problem.

Thanks!
