### ISSUE TITLE
How do you know a blob connection has been properly established?

### ISSUE THREAD

**Issue by brupelo** [Azure/azure-sdk-for-python#27257]
Consider this little snippet:

        blob_service_client = BlobServiceClient.from_connection_string(
            config.get("AZURE_BLOB_CONNECTION_STRING")
        )
        blob_service_client.get_service_properties()

Let's say `AZURE_BLOB_CONNECTION_STRING` env var is pointing out locally to [azurite](https://www.npmjs.com/package/azurite) but I don't have azurite up and running, this code would obviously lead to raise

    azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPConnection object at 0x0647CE98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

Which it's good, problem being it's that's taking quite a while to do so... So my question, is there any way to reduce the timeout for this specific request? And if there isn't, what'd the best way to check if the blob_service_client can connect with the server without waiting so much?

Thanks!

**Comment by jalauzon-msft** [comment]
Hi @brupelo Bruno, the delay in this error being shown is likely because of the automatic retry policy that the SDK has in place. This type of an error is a retriable error and therefore the retry policy will attempt the request a few times with some time in between each.

The default configuration for the retry policy results in usually around 90 seconds before any error would be shown due to a base delay of 15 seconds and exponential backoff. We are aware this is probably not the correct configuration and will probably be updating this to be much faster in an upcoming release but luckily, it's also configurable today. Some of this configuration can be found in the [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/README.md#retry-policy-configuration); specifically, settings around retry count.

If you want to see the error immediately you can disable retries by setting `retry_total=0` on your call to `from_connection_string`. Or you could set it to just `1` to still have retry but cut down on the wait time.

Additionally, you could configure the timing between retries be replacing the entire retry policy with one of your own. For example, you could construct your own instance of `ExponentialRetry` (our default retry policy) with different timing values like this:

```py
from azure.storage.blob import BlobServiceClient, ExponentialRetry

# Create a retry policy with much faster timing
faster_retry = ExponentialRetry(initial_backoff=1, increment_base=1)
blob_service_client = BlobServiceClient.from_connection_string('<Connection String>', retry_policy=faster_retry)
```

Hopefully that helps. Thanks

**Comment by jalauzon-msft** [comment]
Closing this issue, please let me know if you have any more questions. Thanks.
