### ISSUE TITLE
HttpResponseError: InvalidHeaderValue When appending to file in ADLSv2 storage account container

### ISSUE THREAD

**Issue by michaelmingram** [Azure/azure-sdk-for-python#27319]
- azure-storage-file-datalake
- 12.9.1
- Ubuntu 20.04.4 LTS
- 3.8.10

**Describe the bug**
I am running a batch job that creates a file in an ADLSv2 storage account, then retrieves data from a remote system in 2000 record pages, processes them lightly, and appends the records to the file in ADLS. Intermittently when appending data to the file I receive an azure.core.exceptions.HttpResponseError: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.

```
  File "./example.py", line 586, in datalake_process
    file_client.append_data(data=bio.getvalue(), offset=bio_size, length=bio.getbuffer().nbytes, flush=True)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/storage/filedatalake/_data_lake_file_client.py", line 529, in append_data
    process_storage_error(error)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/storage/filedatalake/_deserialize.py", line 215, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "", line 1, in 
azure.core.exceptions.HttpResponseError: (InvalidHeaderValue) The value for one of the HTTP headers is not in the correct format.
RequestId:0193acfe-b017-4579-b11e-e091399edfc9
Time:2022-11-06T05:02:06.9071578Z
Code: InvalidHeaderValue
Message: The value for one of the HTTP headers is not in the correct format.
RequestId:0193acfe-b017-4579-b11e-e091399edfc9
Time:2022-11-06T05:02:06.9071578Z
```

**To Reproduce**
1. Create a file in ADLS v2 storage account container
2. Append data to the file
3. Keep appending data until you reproduce the bug

**Expected behavior**
All appends to succeed.

**Additional context**
I experience the bug consistently in my batch job, but not consistently in any particular job or place in the file. For reference the example above was the 2855th append to the file. The previous 2854 appends had worked without issue.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by michaelmingram** [comment]
Hi @vincenttran-msft:

1. RequestId:a45df50e-e01f-009d-2ed3-f01814000000, Time:2022-11-05T05:00:41.0157658Z
2. I'm appending to the file sequentially. The batch job is running in parallel with multiprocess, but each process is concerned with a different file.

Regards,
Mike

**Comment by vincenttran-msft** [comment]
Hi @michaelmingram Mike, thanks for the follow up. After taking a look into the `RequestID` provided above, I believe to have identified the cause. The exception `azure.core.exceptions.HttpResponseError: (InvalidHeaderValue)` you are receiving in this particular case is due to your header failing a null or empty check. I was able to reproduce this error locally by making an append call that attempts to append empty data (i.e. `data= b''`).

With that being said, I would recommend you to not use the "workaround" `api_version="2019-12-12"` as it is generally more advisable to always use the latest version when available, and I believe this "workaround" may not have actually solved anything here. Furthermore, to avoid running into this exception, I would recommend doing an empty or null check on your data before passing it to the append call. 

Hopefully this resolves your issue.

Thanks!
