### ISSUE TITLE
When reading a blob content, the first time returns the value, second time returns empty string

### ISSUE THREAD

**Issue by mabecke** [Azure/azure-sdk-for-python#27666]
- **Package Name**: azure-storage-blob
- **Package Version**:  12.14.0
- **Operating System**: Docker python:3.7.15-slim-buster
- **Python Version**: 3.7.15

**Describe the bug**
When reading a blob content, the first time returns the value, second time returns empty string

**To Reproduce**

```
from azure.storage.blob import BlobServiceClient
from azure.identity import DefaultAzureCredential

account_name="..."
container_name="..."
blob_name="..."

def empty_content_bug(account_name, container_name, blob_name):
	default_credential = DefaultAzureCredential()
	account_url=f"https://{account_name}.blob.core.windows.net"
	blob_service_client = BlobServiceClient(account_url, credential=default_credential)
	blob_client=blob_service_client.get_blob_client(container_name, blob_name)
	blob=blob_client.download_blob()
	return blob.content_as_text() == blob.content_as_text()


empty_content_bug(account_name, container_name, blob_name)
```

When installing 12.13.1
`pip install azure-storage-blob==12.13.1`
prints `True`

When installing 12.14.0
`pip install azure-storage-blob==12.14.0`
prints `False`

**Expected behavior**
blob content should work when using it more then once

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @mabecke, the issue here is that `content_as_text` is only meant to be called once as it will stream the data from the response. You can think of the return type of `download_blob`, `StorageStreamDownloader`, as a stream that is (currently) not seekable and calling `content_as_text` will read all data from the stream. So, the second call to `content_as_text` will not return any data since the stream is already read to the end. You should save the output of `content_as_text` somewhere if you need to reference it multiple times.

I would also like to note that `content_as_text` is deprecated and will produce warnings in your code, so we recommend you switch to using `readall()` instead. By default, `readall` will give you `bytes` back but if still want an encoded string, you can provide the `encoding` keyword on you call to `download_blob`. Here is a sample of all that.

```py
blob_service_client = BlobServiceClient(account_url, credential=<creds>)
blob_client = blob_service_client.get_blob_client(container_name, blob_name)
downloader = blob_client.download_blob(encoding='UTF-8')
content = downloader.readall()
```

Hopefully that helps. Thanks.

**Comment by maximbr** [comment]
hi @jalauzon-msft thank you for the detailed response. As I understand from your comment `readall()` still has the same implicit "only meant to be called once", this is not documented in any way I could find https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.storagestreamdownloader?view=azure-python#azure-storage-blob-storagestreamdownloader-readall, if this is intended, should be explicit and must be addressed in docs and class+method docs. Until this change, passing along a `StorageStreamDownloader` instance was valid with no need to guarantee if and how many times `readll()` is invoked down the line

**Comment by jalauzon-msft** [comment]
Hi again @mabecke Max, the `StorageStreamDownloader` is intended to be used like a standard Python stream with standard `readall` and `read` methods. For this reason, I'm not really sure this needs to be explicitly documented as it is well-known that streams are intended to be read once (unless you seek backwards, which is currently not supported, but may be in the future).

Just to add why this is the case for `StroageStreamDownloader`: when reading data from the downloaded, it may, depending on the blob size, need to actually make additional requests to the service to fetch more data. By default, only the first 32 MiB are requested in `download_blob` and populated to this class, any more data will be requested in 4 MiB chunks. Reading this stream multiple times would result in requesting the data from the service multiple times since the entire size is not stored in memory.

Hopefully this makes sense. Thanks.
