### ISSUE TITLE
Conversation Analysis samples issues

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-python#27747]
1.

Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_conv_response.py#L71):

![image](https://user-images.githubusercontent.com/80307197/204719736-b7ccb7b9-1980-4959-a204-cc6e464e7c46.png)

Reason:
TypeError: list indices must be integers or slices, not str.

Suggestion:
Change code to `0`

2.

Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_conv_response.py#L73):

![image](https://user-images.githubusercontent.com/80307197/204720031-49525ec0-c845-4685-8832-2336dd2ad155.png)

Reason:
KeyError: 'targetProjectKind'.

Suggestion:
Change code to `result['result']['prediction']['projectKind']`

3.

Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_conv_response.py#L79):

![image](https://user-images.githubusercontent.com/80307197/204720138-d12dddd5-39f4-41b5-832f-9d0d0f5bfd22.png)

Reason:
KeyError: 'result'.

Suggestion:
Change code to 
```
print(f"\ntop intent: {result['result']['prediction']['topIntent']}")
print(f"category: {result['result']['prediction']['intents'][0]['category']}")
print(f"confidence score: {result['result']['prediction']['intents'][0]['confidenceScore']}\n")
```

4.

Section [link](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_conv_response.py#L84):

![image](https://user-images.githubusercontent.com/80307197/204720458-f062fc84-dc90-47bf-a43f-f7e5ef10e245.png)

Reason:
KeyError: 'result'.

Suggestion:
Change code to `result['result']['prediction']['entities']`

@lmazuel , @achandmsft , @mayurid , @kristapratico for notification.

**Comment by kristapratico** [comment]
@AFengKK the described errors arise from a Conversation (project_name/deployment_name) being used in the sample where an Orchestration project should be used instead. You can read about the differences [here](https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/orchestration-workflow/overview). The result output is different between Conversation vs. Orchestration predictions which is why you're seeing the errors. The env vars across samples are uniquely named to try to communicate these differences.

If you think this is still not clear, I could add something to the sample code, e.g.:

```python
if result['result']['prediction']['projectKind'] != "Orchestration":
    print(f"This sample outputs Orchestration prediction results. "
          f"Please see sample_analyze_conversation_app.py for Conversation project result output.")
    return
```

Let me know.
