### ISSUE TITLE
Export azure.identity._constants.EnvironmentVariables

### ISSUE THREAD

**Issue by mpicard** [Azure/azure-sdk-for-python#27964]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated redefining the same azure environment variable definitions. 

**Describe the solution you'd like**

Export azure.identity._constants.EnvironmentVariables so that everyone can use them.

**Describe alternatives you've considered**

Redefining the environment variables in a private package but that is also not necessarily the best because azure could change something and it would stop working.

**Comment by kristapratico** [comment]
Hi @mpicard thanks for your feedback, we'll look into this as soon as possible.

**Comment by pvaneck** [comment]
Hey, thanks for the issue This seems reasonable and seems like we already ⁠[export](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/__init__.py#L9) some of the classes in _constants, so this would just be a matter of adding EnvironmentVariables. 

@xiangyan99 Are you aware of any reason why these weren't or shouldn't be exported? 

(side note: resolution might be delayed due to much of the team on vacation)

**Comment by xiangyan99** [comment]
@mpicard Could you help to share more details how you want to use variables?

They are just constants. Do you want to use them programably?

**Comment by mpicard** [comment]
These values are useful as they are sometimes passed to other azure python
modules as parameters.

**Comment by xiangyan99** [comment]
Sorry for the delay.

Could you provide some specific examples of the environment variables you intend to use and how you'd like to use them? 

This will help us determine the best place to set them.
