### ISSUE TITLE
After multiple timeouts, the authorization header may be invalid because it is too old

### ISSUE THREAD

**Issue by zlevow** [Azure/azure-sdk-for-python#27968]
- **Package Name**: azure-sdk-for-python
- **Package Version**: azure_core-1.26.1 , azure_storage_blob-12.14.1
- **Operating System**: linux
- **Python Version**: 3.9.11

Based on timeout configuration, the azure sdk makes multiple attempts to reach the azure storage blob api.
Unfortunately, the authorization header is not regenerated each time with the current time/date.  If the retries result in a request after a cumulative delay of > 15 minutes, even a successful request is denied because the authorization header has expired.

**To Reproduce**
1. Induce artificial network packet loss (iptables drop packet to blob storage host)
2. Send a request and set the timeout to a large value (901 seconds)
3. After the initial request is dropped, remove the firewall rule
4. Wait for the sdk to perform an internal retry after the timeout

**Expected behavior**
Authorization header should be regenerated for every retry

**Screenshots**

**Additional context**

**Comment by kristapratico** [comment]
Thanks for your issue @zlevow, we'll take a look and get back to you as soon as possible.

**Comment by jalauzon-msft** [comment]
Hi @zlevow, you are correct that this _could_ happen. The real reason it could happen is not because we don't refresh the auth header each retry (we do) but because we don't update the Date header on each retry. So, it would then be possible that the request has a date header that is older than 15 minutes which the service will reject.

That being said, I'm not sure how big of an issue this is because I believe, given our default timeouts, retry counts, and retry timings, I don't think it would be possible to get a request that is older than 15 minutes. Our default retry policy has 3 retries with an initial backoff of 15 seconds and an exponential increase from there. This usually results in about a maximum for 90 seconds. We also have client-side network timeouts which default to 20 seconds for connection and 60 seconds for read. So, assuming each request times out based on network delay while reading (worst case), we'd still only be at around 270 seconds of total delay to get to the last retry.

So, with the SDKs defaults, I don't think this would really be possible to hit but I see in your example you are manually setting the timeout quite high to get the error. Is there an actual scenario where you'd want to be doing this? And/or have you hit this issue in one of your applications?

NOTE: Before blob version 12.14.0, the default read timeout was set very high, so it would have been more possible to hit this.

**Comment by zlevow** [comment]
Thanks for the reply.  During periods of high congestion/packet loss on our network, medium sized uploads (200mb) would sometimes take > 300 seconds to complete. If there was a timeout during this period, a retry would be caused. Four of those retries would put us over the 15 minute mark. (we upped the retry count because of these periodic timeouts)

**Comment by jalauzon-msft** [comment]
Hi @zlevow, assuming you are using the standard upload method, `upload_blob` with default settings, the SDK is performing larger uploads in a series of blocks that are 4 MiB by default, with each block being a completely separate request. If a timeout occurs, only that single block will need to be retried, not the entire upload. So, while the whole upload operation may take 300+ seconds, it is likely each individual request is not taking that full time and therefore it is less likely you would hit the 15-minute mark on a single block, even with many retires.

The default threshold for when a blob is split into chunks is 64 MiB, so if a blob is larger than that, it will be uploaded in 4 MiB chunks instead of all at once. Both this threshold and the chunk size itself are configurable on any client constructor using the `max_single_put_size` and `max_block_size` respectively. I believe they are also settable per individual operation. See here:

https://github.com/Azure/azure-sdk-for-python/blob/97a5929db5ba274229934e16725c8c77943aed84/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L121-L125

You can try playing around with these settings to avoid timeouts all together or just tune things better for your network conditions. Tuning these settings could help eliminate any possibility of hitting a request that is too old if there is one.
