### ISSUE TITLE
Azure Mgmt Network 2022-05-01 Was Removed

### ISSUE THREAD

**Issue by Itay4** [Azure/azure-sdk-for-python#27995]
- **Package Name**:  azure-mgmt-network
- **Package Version**: 22.2.0

**Describe the bug**
api version 2022-05-01 was removed in https://github.com/Azure/azure-sdk-for-python/commit/8e0101d075ea16f680d36516452e8b99c1b3d000

**Expected behavior**
backward compatibility should be kept

**Additional context**
1. why are api versions removed?
2. why is it not documented in the release notes?
3. is this expected that backward compatibility broken?
4. should we not rely on new versions and lock on older version?

**Comment by Wzb123456789** [comment]
Hi @Itay4 

Regarding why the 2022-05-01 version is deleted, it is because directly generating a new version on this basis will cause conflicts.

api version 2022-07-01 is compatible with 2022-05-01. You can remove the specified version when using it, which should solve your problem.

**Comment by Itay4** [comment]
> Hi @Itay4
> 
> Regarding why the 2022-05-01 version is deleted, it is because directly generating a new version on this basis will cause conflicts.
> 
> api version 2022-07-01 is compatible with 2022-05-01. You can remove the specified version when using it, which should solve your problem.

hi @Wzb123456789 

why is it not documented in the release notes?

the problem is not with upgrading to the new api version, but the fact that it breaks the code without the user is aware of it

in my opinion, this is bad practice, which blocks us from using this sdk, and should be resolved in the code generation

**Comment by Wzb123456789** [comment]
Thank you for your reminder, I will pay attention to it when I update the version next time.

**Comment by msyyc** [comment]
> > Hi @Itay4
> > Regarding why the 2022-05-01 version is deleted, it is because directly generating a new version on this basis will cause conflicts.
> > api version 2022-07-01 is compatible with 2022-05-01. You can remove the specified version when using it, which should solve your problem.
> 
> hi @Wzb123456789
> 
> why is it not documented in the release notes?
> 
> the problem is not with upgrading to the new api version, but the fact that it breaks the code without the user is aware of it
> 
> in my opinion, this is bad practice, which blocks us from using this sdk, and should be resolved in the code generation

(1) It is not recommended to use multiapi package like 
```
NetworkManagementClient(..., api-version="xxx)
```
instead, there is no need to care about api-version so the following code is absolutely fine:
```
NetworkManagementClient(...)
```
If you use package with the latter way, you will not be broken since 2022-07 is totally compatible with 2022-05.

(2) why do we remove 2022-05?
As you can see, network is such a big package that many customers are complaining about the size. To make the size not bigger, we remove the old api-version if new api-version is totally compatible with old. And you won't be broken with recommended way.
(3)  why is it not documented in the release notes?
We don't want users care about api-version. In most case, users even needn't know which api-version SDK is using. They just need to care about the api and its function.
