### ISSUE TITLE
Question: Should `file_path` accept a `str | os.PathLike | pathlib.PurePosixPath` object?

### ISSUE THREAD

**Issue by stdedos** [Azure/azure-sdk-for-python#28036]
When using `pathlib`, it might be useful to allow providing those objects as-is, and internally convert to strings if required.

https://github.com/Azure/azure-sdk-for-python/blob/5625581056184d46cbb539ea998a77931f90725b/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_share_client.py#L256-L257

This also applies to all other related arguments (`file_path`-named or not)

**Comment by jalauzon-msft** [comment]
Hi @stdedos Stavros, thanks for the suggestion but I'm not sure accepting `pathlib` types directly is a good approach for us. `pathlib` is mostly intended to be used with OS filesystems and may produce different string representations based on what platform someone is working with. This file-share library only works with URL like paths since they need to be sent to the service in the HTTP URL.

While it may be possible for us to ensure we always extract the correct type of string value, it may add some complexity and/or give the impression we support multiple path types, which we currently do not.

All that being said, thanks again for the suggestion and we will keep it in mind for the future.

**Comment by stdedos** [comment]
> `pathlib` is mostly intended to be used with OS filesystems and may produce different string representations based on what platform someone is working with.

That is why `PurePath`s were created: https://docs.python.org/3/library/pathlib.html#pure-paths:~:text=Pure%20paths%20are,OS%2Daccessing%20operations.

> This file-share library only works with URL like paths since they need to be sent to the service in the HTTP URL.

I may be wrong, but most of the paths accessed here, URL-like-or-not, appear to be `PurePosixPath`s. It can benefit the users from "going away" from `str == path` duality, and also have some useful characteristics (e.g., `join` with simply `/`).

**Comment by jalauzon-msft** [comment]
Hi @annatisch, any thoughts on whether we should support this?
