### ISSUE TITLE
Container Client undocumented parameters?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-sdk-for-python#28124]
Hello,

The ContainerClient documented [here](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-list-blobs) has a `prefix` parameter, but its not documented. I learned about it based on a CGPT suggestion. The parameter is valid, but its unclear what its doing. Any insights would be helpful.

**Comment by mccoyp** [comment]
Hi @SeaDude, thank you for opening an issue! This method does seem to have a prefix parameter, but its current name is `name_starts_with`.

If the CGPT example explicitly passed `prefix` to `list_blobs`, it's possible that it was giving advice based on old code that's no longer used. I've seen some examples of this, where the generated samples use libraries/code patterns that have since been deprecated. It also may have been referencing internal code from the `list_blobs` method that does use a `prefix` parameter in a different context: https://github.com/Azure/azure-sdk-for-python/blob/2f1987d77d234200280e5be8ea93c975ac79acc3/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L790-L792

In either case, I'll tag some folks from the Storage team who can double-check -- we'll get back to you as soon as possible.

**Comment by SeaDude** [comment]
Interesting. When I used the ContainerClient `name_starts_with` parameter to list blobs in a container that start with a list of values, I receive 650 values. When using the `prefix` parameter, I received over 212k values. That discrepancy is what lead me to the docs. 

No worries, I've since refactored the code because I couldn't get a reliable result (there are only 424 blobs in the container!).
