### ISSUE TITLE
[BUG] Spark Pipeline stuck in permanent preparing state

### ISSUE THREAD

**Issue by pradogab** [Azure/azure-sdk-for-python#28360]
- **Package Name**:  azure-ai-ml
- **Package Version**: 1.0.0 / 1.1.0 / 1.2.0
- **Operating System**: Linux/Windows
- **Python Version**: 3.7,3.8,3.9,3.10

**Describe the bug**
Spark Jobs as part of a pipeline get stuck in a permanent "preparing" state.

**To Reproduce**
Just follow the tutorial here: [TUTORIAL](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=sdk) https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=sdk#spark-component-in-a-pipeline-job as it does not work. 

**Expected behavior**
Pipeline jobs can have spark jobs or spark steps with the Spark automatic compute cluster, just as standalone spark jobs.

**Screenshots**
![image](https://user-images.githubusercontent.com/95860796/212697620-e4e3bb42-5c84-43b0-a7bf-89fbe0edae2b.png)
![image](https://user-images.githubusercontent.com/95860796/212698705-0f9d7860-a6f3-4c03-bfa4-d73067c0b23d.png)
![image](https://user-images.githubusercontent.com/95860796/212698850-ce352005-65d8-40d6-82f6-cd74c9889cb5.png)

**Additional context**
Upon analysing the code base it seems also SparkComponents don't even accept the "resources" attribute which is required for the sprak cluster deployment.

**Comment by swathipil** [comment]
@luigiw - Thanks for your report! @azureml-github - Can you take a look at this?

**Comment by luigiw** [comment]
@pradogab this is an issue need to investigated by the backend team rather than an SDK bug. Do you have a customer representative to reach out to?

**Comment by Ioannis-Mykelos** [comment]
Hi, I was trying to implement a two step pipeline in SDKV2, with a Spark component as the first step.
I am facing the same problem. 

Describe the bug
Spark Jobs as part of a pipeline get stuck in a permanent "preparing" state.

Expected behaviour
Pipeline jobs can have spark jobs or spark steps with the Spark automatic compute cluster, just as standalone spark jobs.

The execution log is the following 
`[2023-02-28 10:36:52Z] Job is in progress. Execution status: Preparing.`
The pipeline is stuck in the Spark component for about 3 to 4 hours until failure.
When the pipeline fails I am getting the following error:
`Job failed, Error: {"Error":{"Code":"ServiceError","Severity":null,"Message":"InternalServerError","MessageFormat":null,"MessageParameters":null,"ReferenceCode":null,"DetailsUri":null,"Target":null,"Details":[],"InnerError":null,"DebugInfo":null,"AdditionalInfo":null}, ...,"ComponentName":"Execution"}`

and 

`InternalServerError`

I created a simple standalone spark job (read delta files from the data lake) and it works absolutely fine.

For the 2 step pipeline I am not trying to do something extreme, just read delta files, preprocess and train a simple model. 

For this 2 step pipeline I am defining:
1. a spark job as a pipeline component (1st step), and
2. a training component (using a yml file).

<img width="574" alt="Screenshot 2023-02-28 at 11 58 44" src="https://user-images.githubusercontent.com/54843968/221834593-3f3f37fc-bc30-4f18-94ac-0f8e47594217.png">
<img width="574" alt="Screenshot 2023-02-28 at 11 59 39" src="https://user-images.githubusercontent.com/54843968/221834751-bc16954e-7e5d-45c1-b27a-4e596375dba1.png">
