### ISSUE TITLE
Add parquet support for MLFlow models 

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [Azure/azure-sdk-for-python#28431]
**Is your feature request related to a problem? Please describe.**
Currently you can only use `csv `for running MLFlow models deployed as managed batch endpoints in Azure Machine Learning as described here: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-mlflow-batch?tabs=cli#files-types-support . Often MLFlow models have signatures which have strong dtype requirements which can sometimes be a issue with csv that need to be parsed.

**Describe the solution you'd like**
Add `parquet` support for MLFlow models deployed to batch endpoint such that there is a fileformat with types. With `csv `and `parquet` all normal cases for tabular data is supported.

**Comment by swathipil** [comment]
Hi @thomasfrederikhoeck - Thanks for opening a feature request! @azureml-github - Would you be able to take a look at this?

**Comment by santiagxf** [comment]
Thanks @thomasfrederikhoeck. We are already working on expanding the supported types for MLflow deployments on Batch Endpoints, including Parquet. I will update this thread once this capability is included.

**Comment by thomasfrederikhoeck** [comment]
@swathipil @santiagxf thanks for the swift response! Looking forward to seeing it 👍🏻

**Comment by jxmyrup95** [comment]
I run into similar problem when creating a batch endpoint. Just to emphasise the problem I get the following exception:

INFO:azureml:Enforcing datatypes:{'ValueDateTimeUTC': dtype('<M8'), 'A': dtype('float64'), 'B': dtype('float64'), 'C': dtype('float64'), 'D': dtype('float64')}
INFO:azureml:Reading csv input file into pandas dataframe because the model specifies column based input signature or no signature.
ERROR:azureml:Error processing input file: '/mnt/azureml/cr/j/c55f100575724b1a801497f16987fbf4/cap/data-capability/wd/INPUT_dataset_param_config/X_test.csv'. Exception:the dtype datetime64 is not supported for parsing, pass this column using parse_dates instead
INFO:azureml:Reading csv input file into pandas dataframe because the model specifies column based input signature or no signature.
ERROR:azureml:Error processing input file: '/mnt/azureml/cr/j/c55f100575724b1a801497f16987fbf4/cap/data-capability/wd/INPUT_dataset_param_config/X_test.csv'. Exception:the dtype datetime64 is not supported for parsing, pass this column using parse_dates instead
INFO:azureml:Reading csv input file into pandas dataframe because the model specifies column based input signature or no signature.
ERROR:azureml:Error processing input file: '/mnt/azureml/cr/j/c55f100575724b1a801497f16987fbf4/cap/data-capability/wd/INPUT_dataset_param_config/X_test.csv'. Exception:the dtype datetime64 is not supported for parsing, pass this column using parse_dates instead

I believe this would be solved by using parquet files instead of CSV

**Comment by thomasfrederikhoeck** [comment]
Hi @santiagxf  any progress or update on this? :-)

**Comment by santiagxf** [comment]
Hi @thomasfrederikhoeck @jxmyrup95. A new version of the service has been deployed and now parquet inputs files are being supported in MLflow models. We are in the process of updating documentation but you can try that out now. I'll close this issue as resolved but please let me know if there is any other feedback about it!

**Comment by santiagxf** [comment]
> @santiagxf sounds great! Would that require me to redeploy the batch to update the auto-generated scoring script? 

No, this feature should be enabled for any existing deployment. Please let us know if you find any issue with it.

**Comment by thomasfrederikhoeck** [comment]
@santiagxf One of my colleagues just tried it out and it worked. Thank you for adding it! :-)
