### ISSUE TITLE
Permanent delete for blobs

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [Azure/azure-sdk-for-python#28479]
I would like to preface this with - I don't know currently if permanent delete has been implemented in the SDK or not. Happy to hear it already has, and would love to hear how to use it! :)

PS: You guys do a great job at maintaining this repo.

**Is your feature request related to a problem? Please describe.**
I am currently using the sdk to delete versions of blobs. However we have the soft delete policy turned on as the account is used in production. Though I would like to permanently delete some old versions of blobs. 

**Describe the solution you'd like**
A parameter in the delete_blob function to permanently delete the blob if you have the given credentials.

**Describe alternatives you've considered**
There is a community post to do this in shell script, however I don't feel confident running it within production without better understanding that interface. 
https://techcommunity.microsoft.com/t5/azure-paas-blog/azure-storage-permanent-delete-soft-deleted-objects/ba-p/3600967

**Additional context**
See preface :)

**Comment by jalauzon-msft** [comment]
Hi @AWendland-CryptoCompare Alex, we explicitly chose not to officially support the permanent delete feature in the SDK as permanent delete is not something that should be used regularly as it directly goes against the Soft Delete concept and can result in data loss if not used carefully.

That being said, there is an undocumented keyword argument on `delete_blob` that can allow you to use permanent delete. You can set `blob_delete_type='permanent'` to permanently delete a blob. Again, please be very cautious if you choose to use this feature as data that is permanently deleted is not recoverable. Since this is undocumented, it is subject to change in the future, and we strongly recommend you do not use this feature in your production application code.

**Comment by AWendland-CryptoCompare** [comment]
Hi Jacob, thanks for letting me know about this feature. I promise not to come back to you if I mess this up! Thank you for all the support in my multiple issues I have raised. It is greatly appreciated.
