### ISSUE TITLE
Default value for query_blob function

### ISSUE THREAD

**Issue by AWendland-CryptoCompare** [Azure/azure-sdk-for-python#28634]
**Is your feature request related to a problem? Please describe.**
When I use the query_blob function from BlobClient using the Blob Storage package on a blob that has not been formatted correctly to have the right amount of columns on one row I get an Azure error.

**Describe the solution you'd like**
Could the query_blob function or the Dialect classes have a default value to replace missing values. Either this or it be default replaces them with Nan.

**Describe alternatives you've considered**
Within my system, I catch such errors pull the blob and query on my side. However this solutions increases costs and the performance of the application. 

I also moan at the team that produces these files to get it right.

**Comment by YalinLi0312** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by AlexWendland** [comment]
Hi again Jacob, yeah i think your interpretation is correct so a blob might be
```
A,B,C
1,2,3
4,5,6
7
```
Right now a query would return an error due to the missing values of B and C in the last row. It would be good for it by default to error but if provided with an addition parameter like 'default_value' to instead generate a table with these values in the position of the missing elements.

Or potentially you could have a skip incomplete row.

Though thinking through how to do this, it would be kinda horrible and not that high impact. Also as you said how need to change on the API not the SDK.

Happy for you to close it if there is nothing to be done.
