### ISSUE TITLE
HTTP Challenge response tenant id is used even with verify_challenge_resource=False

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-sdk-for-python#28648]
Initializing ClientSecretCredential as follows:
```
    credentials = ClientSecretCredential(
        client_id = config['clientId'],
        client_secret = config['clientSecret'],
        tenant_id = config['tenantId'], # Passed as GUID.
        authority = "https://...com/adfs/" # Note that this ends in "adfs/".
    )
```
https://github.com/Azure-Samples/Hybrid-Python-Samples/blob/195a415d1cd2eefe4ce5a40e6c2db3d3802bcdfe/keyvault/example.py#L38

And `verify_challenge_resource=False` is passed to SecretClient here:
https://github.com/Azure-Samples/Hybrid-Python-Samples/blob/195a415d1cd2eefe4ce5a40e6c2db3d3802bcdfe/keyvault/example.py#L116

The code-flow still executes HTTP challenge requests during setting of Key Vault secret:
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py#L126

The HTTP challenge request is made here:
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L91

Here it will check that `self._verify_challenge_resource` is False, and thus skip the if-statement:
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L97

But as can be seen on this line, the challenge tenant id `tenant_id=challenge.tenant_id` is still used for `authorize_request`:
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L112

This causes the error `ClientAuthenticationError` to be thrown:
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/identity/azure-identity/azure/identity/_internal/utils.py#L74

I have verified that if `default_tenant` was used by removing `tenant_id=challenge.tenant_id` from below call:
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L112

It would not have thrown this error. Ideally, since `self._verify_challenge_resource` is `False`, it shouldn't be using the tenant ID returned by HTTP challenge request.

- **Package Name and Version**: 
adal                        1.2.7
azure-common                1.1.28
azure-core                  1.26.1
azure-identity              1.13.0b1
azure-keyvault              4.2.0
azure-keyvault-certificates 4.6.0
azure-keyvault-keys         4.7.0
azure-keyvault-secrets      4.6.0
- **Operating System**:
Windows Server 2016 Datacenter
- **Python Version**: 
Python 3.7.9

**Describe the bug**
Tenant ID from HTTP challenge request is used even though `verify_challenge_resource=False` is passed to SecretClient constructor.

**To Reproduce**
1. Run the following sample in an on-premise Azure Stack Hub ADFS environment:
https://github.com/Azure-Samples/Hybrid-Python-Samples/blob/update-keyvault/keyvault/example.py

**Expected behavior**
It should not use HTTP challenge response's tenant ID since it actually returns the wrong one for a user who configured their tenant ID manually in `ClientSecretCredential` constructor to use the tenant GUID. The default tenant should be used as configured by the user in the credential objects such as `ClientSecretCredential`.

**Comment by mccoyp** [comment]
Hi @TheOnlyWei, thank you for opening an issue! I appreciate that you've debugged this on your end and provided details about what works, what doesn't, and where the exception is cropping up.

To explain the behavior you're seeing, it's intentional to provide a tenant ID to token requests even when `verify_challenge_resource=False`. Challenge resource verification is specifically verifying that the resource in authentication challenges matches the domain of the vault associated with a client. Disabling this check doesn't mean that we intend to opt out of other challenge authentication measures like using the challenge-provided scope and tenant ID. The authentication scope and tenant ID in a challenge response are assumed to be necessary for authentication.

The full exception that you're getting from `azure-identity` explains that the issue is with the permissions granted to your credential, since the token request is being made for a tenant that the credential doesn't have permission to acquire tokens for: https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/identity/azure-identity/azure/identity/_internal/utils.py#L74-L79

That doesn't necessarily mean that providing the tenant ID to token requests would fail; in fact, I would be surprised if you can make successful requests to the key vault if that were the case. The error just means that the credential needs to be initialized with the correct permissions via the [`additionally_allowed_tenants` keyword argument](https://github.com/Azure/azure-sdk-for-python/blob/e639e361085424f3901cae764d0ade3512fb2be4/sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py#L22).

I would suggest trying this code again and providing `additionally_allowed_tenants` to the credential, using either the `*` wildcard or the specific tenant that you expect the vault to be in. If the service principal belongs to a different tenant than the key vault (which is true if the challenge response's tenant is different), then explicitly allowing the credential to perform cross-tenant authentication with `additionally_allowed_tenants` is the intended process.

**Comment by TheOnlyWei** [comment]
@mccoyp If I add `additionally_allowed_tenants` like this:
```
    credentials = ClientSecretCredential(
        client_id = config['clientId'],
        client_secret = config['clientSecret'],
        tenant_id = config['tenantId'],
        authority = mystack_cloud.endpoints.active_directory,
        additionally_allowed_tenants = ["adfs"]
    )
```

I get a 503 service error due to bad URL:
`https://...com/adfs/adfs`
This is the value of `"{}/{}".format(self._authority, tenant_id)` from here:
https://github.com/Azure/azure-sdk-for-python/blob/c6b119be5bafb75a1805d5715b3d1a5daa1ffa4b/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L80

This is because `self._authority` is `https://...com/adfs/` and the tenant ID "adfs" is appended to the end since `resolve_tenant` returns "adfs" from here:
https://github.com/Azure/azure-sdk-for-python/blob/c21d8cb6081c8eecb5a54b8fd60a6c1cf73e6152/sdk/identity/azure-identity/azure/identity/_internal/utils.py#L73

It then constructs such a tenant discovery endpoint URL like this:
`https://...com:443/adfs/adfs/.well-known/openid-configuration`
From here: https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/d6db249df990f81cadecb4166936afddc475294a/msal/authority.py#L112

Then it throws this error:
```
Content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
```

The work-around is the following that requires some modification of the active directory endpoint:
```
    credentials = ClientSecretCredential(
        client_id = config['clientId'],
        client_secret = config['clientSecret'],
        tenant_id = "adfs",
        authority = config['activeDirectoryEndpointUrl'] # Base URL without "adfs/" ending by taking active directory from metadata endpoints and trimming off the "adfs/" ending
    )
```
Other resource provider samples work using the following without needing user modification of active directory URL, all except `SecretClient` due to HTTP challenge using a different tenant ID:
```
    credentials = ClientSecretCredential(
        client_id = config['clientId'],
        client_secret = config['clientSecret'],
        tenant_id = config['tenantId'] # tenant GUID,
        authority = mystack_cloud.endpoints.active_directory # active directory endpoint directly from metadata endpoint without needing to modify the URL and remove the ending "adfs/"
    )
```

**Comment by mccoyp** [comment]
@TheOnlyWei thank you for investigating. This looks like it might be an edge case caused by a unique challenge resource.

Just to double-check, @xiangyan99, have you seen anything like this before/do you have any ideas for fixes that could come from Identity's side? If not, we can look at making a change on the Key Vault side of things -- off the top of my head, it's sounding like we would need to possibly add another option to disable tenant discovery (I don't think we want to directly tie that to challenge resource verification). We may instead want to add logic to account for this type of edge case, depending on what the challenge resource looks like.

**Comment by keystroke** [comment]
Yes this behavior comes from KeyVault service advertising the wrong authority URI in the www-authenticate header, combined with confusing SDK usage of "authority" and "tenantId" incorrectly. When Azure SDK asks for authority and for tenantId what they really want is "give the pieces of the authority URL so I can internally concat them". It doesn't actually want or need the "tenantId" like what the value of the "tid" claim would be in an actual token at the end of the day. It just wants to build the authority URL in this convoluted way.

Because KeyVault advertises /adfs/tenantId as the authority URL (incorrectly, and declined to fix service-side), fixes must be made to accommodate this behavior in all clients. Typically, they will check for "/adfs" being the first segment of an authority URI and remove the other segments.

Internally, ADAL / MSAL in .net does this on behalf of calling code. However, it seems either MSAL.py does not does that here, or the KeyVault SDK code is building the auth values differently.

I see here that it this code has its own http challenge method and ends-up returning the first segment of the response (/adfs) as the "tenantId":
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py#L48

So although KeyVault service advertises a nonsense authority URI, this code parsed-out the "/adfs" segment of that and "saves it for later", though it looks like it ends-up being concatenated:
https://github.com/Azure/azure-sdk-for-python/blob/c6b119be5bafb75a1805d5715b3d1a5daa1ffa4b/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L80

So it seems the MSAL.py credential wants "base authority" as the "authority" value, so it internally can build the actual authority url by appending the first "segement" of the authority URL which it calls "tenantId".

@TheOnlyWei if we configure the environment to have the "base" authority URI in endpoint I think this will work, however that implies a setup where end-user code is having to setup the Azure env in a careful way. Is there a natural place in Python Azure SDK where this can be handled? As other Azure SDK tools must be handling this somewhere else as well (with "/adfs" being detected). Can you confirm that for AzurePS for example that SDK works as-is without user configuration needing to "game" the SDK misuse of "authority" and "tenantId"?

**Comment by mccoyp** [comment]
Looping in @rayluo for visibility on Python's MSAL library.

@keystroke or @TheOnlyWei, do you have an example of the full `WWW-Authenticate` header in Key Vault's challenge response? Specifically, is the authorization URI being provided in the style of `https://login.windows.net/adfs`, or instead like `https://login.windows.net/adfs/tenant-id`, where `tenant-id` is a GUID? The former would make sense if "adfs" is the tenant; the latter would surprise me.

I can't speak for what "should" be the accepted format of the authority endpoint, but you're correct that the SDK assumes it does not include a tenant ID. For example, in the [msrestazure.azure_cloud](https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_cloud.py) module that's referenced in the Azure Stack Hub sample, each of the listed authority endpoints is what you refer to as a "base authority".

**Comment by keystroke** [comment]
@mccoyp as mentioned, the keyvault www-authenticate header returns a url like "/adfs/tenant-id". It should return just "/adfs" because that is actually the oauth2 authority value. However, that behavior isn;t what is causing the issue here, because the SDK in this case is not using the authority URL as-is (which would be the correct thing to do) and it instead tries to parse out segments of that and rebuilding an authority URL internally...

Because of above, it manages to ignore the "extra tenant-id" segment spurious included in the ww-authenticate header. In the end, this SDK code manages to extract "/adfs" from the www-authenticate header regardless, by taking the [0] segment.

The problem is that in the SDK, they ask for "authority" in the environment / credential configuration, which should be the resulting full URL for an authority (whether that authority is /adfs or /tenant-id or w/e. But instead, it really means "base authority" and actually fails to handle scenarios correctly for both AAD and ADFS clouds.

When you call ARM in a cloud, it returns a "login endpoint" that many tools like Azure CLI, AzurePS / users use to figure-out configuration:
https://management.azure.com/metadata/endpoints?api-version=2015-01-01

For AAD environments, this login endpoint is incomplete and represents a "base" URI one would / could use as an authority URI in an oauth2 interaction. For ADFS environments, this login endpoint includes "/adfs" as a complete authority URI. Lazy code was written that just always asked a user for "tenant ID" and concatenated it with whatever comes back from this metadata endpoint as-is. This is how you get services like KeyVault advertising /adfs/tenant-id service-side.

Within ADAL / MSAL (in .net at least) special accommodations were made to detect incoming authority URIs that began with "/adfs/" in cause such code were used in front of MSAL to build a spurious authority URI. It could be that MSAL PY does not have such logic in it (and perhaps wouldn't want to introduce it). This would then mean that Azure SDK would need to handle this authority URL manipulation, so users can configure their python script in the same way whether the target cloud is AAD or ADFS. Currently, as shared by @TheOnlyWei, end-user code has to configure the MSAL credential in two different ways depending on whether the env is AAD or ADFS.

What is interesting is whether other Azure SDK operations work in the regular setup, or if something is uniquely broken here for  the keyvault interaction. @TheOnlyWei if you configure the python env / cred with "authority" value of "/adfs" AND give the guid tenantId value for "tenant", do other operations like calling ARM etc. work? and just the KeyVault interaction fails? If so, the elsewhere in python SDK here, the authority URI is being "normalized" correctly, and something is just missed for this special KeyVault interaction.

**Comment by keystroke** [comment]
It seems something is broken only in the flow for acquiring a KeyVault secret. For other operations like calling ARM etc., the MSAL credential is configured with "/adfs" as the authority and "<guid>" as the tenantId. Somehow those are able to be combined or processed so that token can be acquired successfully. In the KeyVault WWW-Authenticate flow, it ends-up with same authority value, but a tenantId of "adfs" from taking the first segment of the response header URI. Either that difference or something else in the flow is different resulting in the error...

**Comment by TheOnlyWei** [comment]
@keystroke Yea, I think Python SDK can trim any appended segments to obtain only the base active directory URL here:
https://github.com/Azure/msrestazure-for-python/blob/8e3def8c9927a349596e575de93df76de7a3a2b6/msrestazure/azure_cloud.py#L222
The library above helps get metadata endpoint values, but not sure of any unintended effects of such a change. In theory, as long as default active directory URL doesn't have any tenant ID segments, then such a change should only affect ADFS environments where there is an "adfs/" appended to the active directory URL returned from a metadata endpoint query.

Regarding user-experience with other clients within Python SDK, there is no required trimming of the "adfs/". **Usage B** works for other Python SDK clients without any user modification required to the authority or active directory URL (such as for storage, resource group, and VM clients). Example of successful tenant discovery endpoint during a resource group creation call as shown previously:
`https://...com:443/adfs/1111aabb-11aa-aa11-1a1a-111aa111aa11/.well-known/openid-configuration`
Again this is the tenant discovery endpoint: https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/d6db249df990f81cadecb4166936afddc475294a/msal/authority.py#L112

By the following line in the code-flow of resource group creation (which works as opposed to HTTP challenge code-flow):
https://github.com/Azure/azure-sdk-for-python/blob/c6b119be5bafb75a1805d5715b3d1a5daa1ffa4b/sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py#L80
The authority parameter looks like this:
`https://...com/adfs/1111aabb-11aa-aa11-1a1a-111aa111aa11`
Again, the above represents a successful code-flow. The only reason for this GitHub issue is because that authority is different after HTTP challenge for Secret Client setting of a secret because it uses a tenant ID retrieved from the HTTP challenge and you get the double "adfs/adfs" instead of "adfs/<tenant GUID>".

Regarding user-experience with other language SDKs, it is likely the same issue might occur, I have encountered similar issues in the past in Golang SDK, but for older sample libraries. The issue never moved anywhere. So, I assume this issue will occur for Key Vault secret clients for all SDKs as the SDK teams have no capability to test their features on any Azure Stack Hub ADFS environments.

@mccoyp Within this function:
https://github.com/Azure/azure-sdk-for-python/blob/990d01dbbf1dc11e5eae9f1f48cf583f0a049eee/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L45

The `challenge` variable has these values:
```
function variables:
  scheme:'Bearer'
  server_encryption_key:None
  server_signature_key:None
  source_authority:'kv-sample9366.adminvault.<location>...com'
  source_uri:'https://kv-sample9366.adminvault.<location>...com/secrets/auth-sample-secret?api-version=7.1'
  tenant_id:'adfs'

_parameters:
  function variables:
    'authorization':'https://adfs.<location>...com/adfs/1111aabb-11aa-aa11-1a1a-111aa111aa11'
    'resource':'https://adminvault.adfs...com/1111aabb-11aa-aa11-1a1a-111aa111aa11'
    len():2
```
The HTTP challenge uses `tenant_id` from the challenge, which is always `adfs` for and ADFS environment presumably.

**Comment by mccoyp** [comment]
@keystroke thank you for confirming the service's authentication header response, and @TheOnlyWei thank you for confirming the behavior in other libraries and KV challenge content.

I'll try summarizing the reason the KV SDK fails to authenticate when others succeed. KV libraries are unique across the Python SDK in that they always attempt to provide a tenant ID to token requests (in recent versions). Because other libraries don't call the `get_token` method with a `tenant_id` keyword, token requests are sent with a full authority endpoint -- i.e. authority endpoint plus tenant ID -- of `authority + tenant ID given to credential`.

When a credential is initialized with an authority of `https://...com/adfs/` and tenant ID of `{GUID}`, like in the **Usage B** example that @TheOnlyWei described, the full authority becomes `https://...com/adfs/{GUID}` -- the request succeeds.

With KV libraries, though, the full authority endpoint is instead `authority + tenant ID parsed from challenge response`. As @keystroke pointed out, our authentication policy assumes the tenant ID will be the first segment of the authorization URI's path: https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py#L48

Up until now, that assumption has been successful. Whether the ADFS response format is incorrect or not, it does break this assumption and results in KV libraries picking `adfs` as the tenant ID instead of the GUID at the end of the URI. The full authority then becomes `https://...com/adfs/adfs`, and the request fails.

In the **Usage A** example that @TheOnlyWei described, where the authority has the `adfs` suffix removed, authentication succeeds. That means the KV library's options are to:
1. Exclude the `tenant_id` keyword from token requests (with either an option or for all ADFS requests)
  a. This results in the same behavior as other libraries
3. Parse the challenge's authorization URI differently (by either grabbing the final section of the path or handling ADFS requests uniquely)
  a. If a challenge response contains a different tenant than the one given to the credential, this results in cross-tenant token requests that other libraries don't make

Another option would be to handle this issue in either MSAL or Identity. We'll need to have some conversations on the SDK's side to figure out which solution is best.

**Comment by mccoyp** [comment]
Hi again, @TheOnlyWei! This month we released new beta versions of KV libraries that account for the AD FS authentication issue you saw here. Could I ask you to try installing [`azure-keyvault-secrets==4.8.0b1`](https://pypi.org/project/azure-keyvault-secrets/4.8.0b1/) and testing this with your initial setup (i.e. using an `authority` that ends in "adfs")?
