### ISSUE TITLE
Azure Function APP 

### ISSUE THREAD

**Issue by rimpi23** [Azure/azure-sdk-for-python#28732]
Request URL: 'https://blobdatafetch.blob.core.windows.net/salesforcedata_sale?restype=REDACTED&comp=REDACTED' Request method: 'GET' Request headers: 'x-ms-version': 'REDACTED' 'Accept': 'application/xml' 'User-Agent': 'azsdk-python-storage-blob/12.14.1 Python/3.8.16 (Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.2.5)' 'x-ms-date': 'REDACTED' 'x-ms-client-request-id': '********************' 'Authorization': 'REDACTED' No body was attached to the request

**Comment by kashifkhan** [comment]
Hi @rimpi23 , can you provide some more details around the issue so that we can help you better. Details such as name of the library, version, python version, OS , small snippet of code to reproduce the problem, exception stack will help a lot.

**Comment by rimpi23** [comment]
Over here we are trying to pull data from the Blob container and pushing it into POSTGRESQL.
Code was running well in my local app. After we published the code into Azure Function APP, via Visual Studio, the code failed, after it triggered at desired time.

**Comment by annatisch** [comment]
Thanks @rimpi23 for the clarification - in order to be able to diagnose this, we will need more information.
The log statement above appears to show a GET request on a container, but I'm not sure what SDK operation was being run, nor whether or not the response was successful.
You mention that "the code failed" - what kind of errors did you see? Are you able to give us more details on the code that failed? For example, code snippets showing which SDK operations failed?
