### ISSUE TITLE
ErrorCode: CannotVerifyCopySource when using start_copy_from_url() but upload_blob_from_url() worked

### ISSUE THREAD

**Issue by callaway-chris-yang** [Azure/azure-sdk-for-python#28836]
- **Package Name**: azure.storage.blob
- **Package Version**: 12.13.1
- **Operating System**: win64
- **Python Version**: 3.9.13

**Describe the bug**
Try to copy one blob file from one subscription to another subscription.

Example of how I build connection.

    credential = DefaultAzureCredential()

    SOURCE_ACCOUNT_URL = 'https://xxx.blob.core.windows.net/'

    source_service_client = BlobServiceClient(account_url=SOURCE_ACCOUNT_URL, credential=credential)

When try start_copy_from_url(), the 'CannotVerifyCopySource ' came out. 

But, upload_blob_from_url() worked and successfully copied the file.

Could you give me some guidance?

**Comment by catalinaperalta** [comment]
Thanks for the question @chrisyang-callaway! Routing to the right people to help answer this.

**Comment by vincenttran-msft** [comment]
Hi @chrisyang-callaway Chris thanks for your inquiry. Unfortunately, I do not have a great answer for you as I require a little bit more information about what type of error you are receiving. 

Could you please respond back with the following information:

- What is the full error for `CannotVerifyCopySource`
- Can you please post a larger sample code (with sensitive information redacted) as I would like to see what parameters you are using for each API call
- Can you please verify the tier of the source blob is not `Archive`? Blobs with the `Archive` tier cannot be copied without being rehydrated first. See more [here](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob#copying-an-archived-blob) if this is applicable


With that being said, my current hypothesis is that this is something permissions related. As stated in the documentation for the [start_copy_from_url](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-start-copy-from-url) API, note the restrictions on the `source_url` parameter, specifically: 
`If the source is in another account, the source must either be public or must be authenticated via a shared access signature.`

Furthermore, please ensure that the credentials that are gathered by your `credential = DefaultAzureCredential()` has the necessary permissions to upload and download from your source Azure subscription account.

One other possibility you can attempt to use is the `source_authorization` parameter which is listed in the documentation above (and is a valid parameter to both APIs you are using).

Lastly, one final possibility is to check your firewall settings for both the source and destination Storage subscriptions.

Hopefully this helps unblock your workflow, otherwise please respond back with the necessary additional information so that we may further investigate.

Thanks!

**Comment by hahahahahaiyiwen** [comment]
I came across the same issue when trying to upload blob from a public url. I will get 405 `CannotVerifyCopySource` if I have the `overwrite=True`. And the upload will succeed once I remove `overwrite=True`. I believe this is a bug and the upload should succeed regardless of `overwrite` value. Could someone help take a look?
