### ISSUE TITLE
Custom Vision: TrainingAPI.get_account_info() method removed in 0.2.0??

### ISSUE THREAD

**Issue by cosbyr** [Azure/azure-sdk-for-python#2887]
@areddish 

I noticed that the get_account_info method was removed from the TrainingApi  in version 0.2.0.

Is there any method I can use that would replicate this functionality?

We were relying pretty heavily upon it to retrieve the corresponding Prediction Key programmatically

Related question:

If we are using the 0.1.0 version of the Python Custom Vision package, is the trainingapi method's rest calls forwarded to 1.0 version of the underlying rest api? I hope so

**Comment by lmazuel** [comment]
@areddish for question 1

For question 2, [0.1.0 is 1.2](https://github.com/Azure/azure-sdk-for-python/blob/azure-cognitiveservices-vision-customvision_0.1.0/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/training_api.py#L36) and [0.2.0 is 2.0](https://github.com/Azure/azure-sdk-for-python/blob/azure-cognitiveservices-vision-customvision_0.2.0/azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/training_api.py#L36).

**Comment by cosbyr** [comment]
@lmazuel 

How long will the 1.2 REST API be up and running?

**Comment by lmazuel** [comment]
Question for @areddish from the service team as well, I'm just a regular Python guy :)

**Comment by areddish** [comment]
@cosbyr Yes - we've removed the get_account_info in the latest versions due to changes in how we report back the usage/limits. There isn't any replacement at the moment - especially for retrieving the prediction key programmatically. The recommendation would be to add the prediction key to your project vs retrieve it programmatically.

1.2 REST API continues to function and there's no immediate plans to deprecate it, if that changes we'll communicate it with time to migrate off.

**Comment by lmazuel** [comment]
Closing since the initial question is answered. Feel free to open any new issues or questions. Thanks!
