### ISSUE TITLE
POST https://myresource.cognitiveservices.azure.com/ 404 not found

### ISSUE THREAD

**Issue by bharathkumar192** [Azure/azure-sdk-for-python#28894]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: 
- **Python Version**: 

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

Language Quickstart Feedback
* Content: [Quickstart: Sentiment analysis and opinion mining - Azure Cognitive Services](https://learn.microsoft.com/azure/cognitive-services/language-service/sentiment-opinion-mining/quickstart?pivots=programming-language-python)
* Content Source: [articles/cognitive-services/language-service/sentiment-opinion-mining/quickstart.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/language-service/sentiment-opinion-mining/quickstart.md)
* Section: **Code-example**
* Service: **cognitive-services**
* Sub-service: **language-service**

**Comment by bharathkumar192** [comment]
hi i am using azure text analysis api for angular website. when i am calling the post API to the endpoint given , it says 404 error and i cant troubleshoot it in azure. 

endpoints i've tried:
https://ang-blog.cognitiveservices.azure.com
https://ang-blog.cognitiveservices.azure.com/en/:analyze-text?api-version=2022-05-01

http post request i used :

this.http.post<any>(API, [{"text": "Great atmosphere. Close to plenty of restaurants, hotels, and transit! Staff are friendly and helpful."}], {headers:headers})

**Comment by kristapratico** [comment]
@bharathkumar192 this repo is for the Python SDK. If using the REST API, you'll need to form your request like shown in this example: https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/sentiment-opinion-mining/quickstart?pivots=rest-api&tabs=windows#create-a-json-file-with-the-example-request-body

For the endpoint, I think you're seeing 404 because of the replacement of "language" with "en". Here "language" means we're accessing the Language service APIs. Try:

> https://ang-blog.cognitiveservices.azure.com/language/:analyze-text?api-version=2022-05-01
