### ISSUE TITLE
Servicebus logging unclosed connections

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [Azure/azure-sdk-for-python#28907]
- **Package Name**: servicebus
- **Package Version**: 7.8.2
- **Operating System**: linux, OSX
- **Python Version**: 3.10

**Describe the bug**

I am receiving and sending messages via servicebus and I regularly (though not always) experience an error message in the log coming out of `aiohttp` and as far s I can see it seem related to servicebus client connection.

```
2023-02-20 08:09:07.875888] level=ERROR    message="Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x104ffd960>"
[2023-02-20 08:09:07.876530] level=ERROR   message="Unclosed connector connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x105058040>, 3692.632925916), (<aiohttp.client_proto.ResponseHandler object at 0x104fd76a0>, 3700.041593875)]'] connector: <aiohttp.connector.TCPConnector object at 0x104fff790>"
```
My guess is that it might be related to the fact that I am creating a connection client every time, actually two nested ones.

**To Reproduce**
Steps to reproduce the behavior: a code snippet similar to the following:
```
    servicebus_client = await ServiceBusClient.from_connection_string(conn_str=connection_string)

    async with servicebus_client:
        receiver = servicebus_client.get_queue_receiver(
            queue_name='listen-to-foo',
            receive_mode=ServiceBusReceiveMode.RECEIVE_AND_DELETE,
        )
        async with receiver:
            async for msg in receiver:
                if msg:
                    # do stuff for a while
                    service_bus_client = ServiceBusClient.from_connection_string(conn_str=connection_string)
                    async with service_bus_client:
                        sender = service_bus_client.get_queue_sender(queue_name='notify-foo')
                        async with sender:
                            await sender.send_messages(ServiceBusMessage(msg_str))

 
```

**Expected behavior**
No errors and/ or exceptions.

**Screenshots**

<img width="1337" alt="Screenshot 2023-02-20 at 09 02 48" src="https://user-images.githubusercontent.com/70192688/220047126-25fd647c-bc42-49ef-8368-7866de717628.png">

**Comment by annatisch** [comment]
Thanks for the report @andrea-cassioli-maersk!
Is there any possibility that you're using any other Azure SDK packages alongside ServiceBus?
I ask because ServiceBus is not an HTTP-based SDK, sending and receiving messages is done via the AMQP protocol, which doesn't use an HTTP lib like aiohttp.

There are a couple of areas where this could still be happening - one is the credential object. However I would only expect that for a credential from `azure-identity`, like `DefaultAzureCredential` which maintains an HTTP connection, I don't think using a connection string like the snippet above would cause this...

The other possibility is the `servicebus.aio.management.ServiceBusAdministrationClient` which uses simple HTTP operations for managing resources - however this does not appear to be used in the code snippet above.

We can keep digging to see where else an HTTP connection might be slipping into normal AMQP operations. If it's happening intermittently, that could imply something like auth token renewel (however this mechanism also takes place over the AMQP connection....), but would be good to eliminate the possibility that any other Azure SDK packages are involved.

**Comment by andrea-cassioli-maersk** [comment]
@annatisch indeed we also use blob storage and appConfiguration. I am assuming service bus because I can the log printed out when we process messages and still we have not access the storage. But indeed it might be appConfiguration as well.

**Comment by kashifkhan** [comment]
I would have lean on another Azure SDK package being the root cause as well due to the reasons @annatisch pointed out. I went ahead and did a double check on the code to see if there were any obvious imports for `aiohttp` in the coded base and there were none. No admin client calls under the hood and even `ServiceBusSASTokenCredential` doesn't derive from `TokenCredential`. 

Cursory look doesn't show anything obvious, but I'll run the repro code to see if something does pop up.

**Comment by andrea-cassioli-maersk** [comment]
Digging a bit deeper and thank for your investigation (@kashifkhan @annatisch), I think the issue is actually due to a dangling blob storage client. 

I am gonna make some tests and once I can confirm It is the blob storage, then I will close this issue.

**Comment by andrea-cassioli-maersk** [comment]
Sorry for the delay. I can confirm it was actually caused by a dangling connection on a blob storage client.
