### ISSUE TITLE
Finding Azure Batch Python client in Conda packaging

### ISSUE THREAD

**Issue by apjanke-demex** [Azure/azure-sdk-for-python#29164]
- **Package Name**: azure-batch
- **Package Version**: 13.0.0
- **Operating System**: Linux & Windows
- **Python Version**:  3.9

Sorry for deviating from the regular bug report format in the template here, but this is a question about packaging and discovery, not actual program behavior, so the default sections didn't seem relevant.

I've started working with Azure Batch and use Python, with my Python environment managed by Anaconda. I'd like to install the [Azure Batch Client Library](https://learn.microsoft.com/en-us/python/api/overview/azure/batch-readme?view=azure-python) and [Azure Batch Management Client Library](https://learn.microsoft.com/en-us/python/api/overview/azure/mgmt-batch-readme?view=azure-python) from the [Azure SDK for Python](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-overview) in my Anaconda environments, preferably using conda instead of pip.

These are the azure.batch and azure.mgmt.batch modules (or "module packages"; whatever they're called), found in the azure-batch and azure-mgmt-batch PyPI packages. But I don't know where to find them in the Conda packaging of Azure SDK for Python.

The Azure SDK for Python introduced [a Conda packaging of it](https://devblogs.microsoft.com/azure-sdk/python-conda-sdk-preview/) back in 2021, and its use is described in the ["How to install Azure library packages for Python" page](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-install?source=recommendations&tabs=conda). The Conda packaging differs from the PyPI packaging. The Python Azure SDK modules are packaged in to a smaller number of packages in the Conda form, with sometimes different naming.

Is the Azure Batch client library available in the Microsoft-supplied Conda packages somewhere (the ones in the microsoft conda channel, instead of the conda-forge channel)? If so, which Conda package?

And more generally, if I know what Azure SDK for Python module I want, or what PyPI package it's in, how can I find out which microsoft-channel Conda package it's in? I haven't been able to find a list of which module is in which Conda package anywhere.

There's an [azure-batch conda package in the conda-forge channel](https://anaconda.org/conda-forge/azure-batch) (instead of the microsoft channel). But if I understand correctly, those conda-forge Azure packages are the old ones from before the 2021 introduction of the microsoft conda channel's packaging, and have different dependencies and stuff.

I'd prefer to install the Azure Batch client from the microsoft-channel Conda packages, instead of the conda-forge channel package or from PyPI/pip, for consistency with my other Azure Python packages, which are all installed from the microsoft-channel Conda packages. I've read that mixing interdependent packages from different channels can sometimes cause problems, and if you're mixing conda-managed and pip-managed packages in an Anaconda environment, you're supposed to install all the conda packages first, then the pip packages, and then don't go back and install or update any conda packages afterwards, or something like that.

**Comment by kristapratico** [comment]
Hi @apjanke-demex thanks for your detailed question.

The official conda Microsoft channel can be found here: https://anaconda.org/microsoft/repo
You can also take a look at the release logs to see versioning details for each package: https://github.com/Azure/azure-sdk-for-python/tree/main/conda-releaselogs

That being said, it doesn't look like we currently publish `azure-batch` or `azure-mgmt-batch` (under `azure-mgmt`) on the official channel. Adding @xiangyan99 @rohit-ganguly to look into this and comment.

**Comment by apjanke-demex** [comment]
> [...] it doesn't look like we currently publish azure-batch or azure-mgmt-batch (under azure-mgmt) on the official channel.

Well, that would sure explain why I couldn't find them. :)

I tried installing the azure-batch package from the conda-forge channel instead, and it seemed to work okay. This installation was done into a conda env with several of the other microsoft-channel conda packages installed, and it didn't alter any of the existing package installations. I'm guessing that means either its dependency versions close enough to what's in the microsoft packages that it didn't alter anything?

```
(base) PS C:\Windows\system32> conda install -c conda-forge azure-batch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - azure-batch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    azure-batch-13.0.0         |     pyhd8ed1ab_0         127 KB  conda-forge
    msrestazure-0.6.2          |             py_0          28 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         155 KB

The following NEW packages will be INSTALLED:

  adal               conda-forge/noarch::adal-1.2.7-pyhd8ed1ab_0
  azure-batch        conda-forge/noarch::azure-batch-13.0.0-pyhd8ed1ab_0
  msrestazure        conda-forge/noarch::msrestazure-0.6.2-py_0


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) PS C:\Windows\system32>
```

Or maybe that's actually because it only depends on azure-common amongst the other Azure packages, and I already had a conda-forge version of azure-common due to some previous installation I did before and forgot about.

```
(base) PS C:\Windows\system32> conda search azure-batch=13.0.0 --info
Loading channels: done
azure-batch 13.0.0 pyhd8ed1ab_0
-------------------------------
file name   : azure-batch-13.0.0-pyhd8ed1ab_0.tar.bz2
name        : azure-batch
version     : 13.0.0
build       : pyhd8ed1ab_0
build number: 0
size        : 127 KB
license     : MIT
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/azure-batch-13.0.0-pyhd8ed1ab_0.tar.bz2
md5         : 15605b60153a1e7c1af31f8789d2d90f
timestamp   : 2022-11-10 13:14:05 UTC
dependencies:
  - azure-common >=1.1,<2.dev0
  - msrestazure >=0.4.32,<2.0.0
  - python >=3.6


(base) PS C:\Windows\system32> conda list | Select-String -pattern azure-

azure-ai-ml               2022.12.01                 py_0    microsoft
azure-batch               13.0.0             pyhd8ed1ab_0    conda-forge
azure-common              1.1.28             pyhd8ed1ab_0    conda-forge
azure-core                2023.03.01                 py_0    microsoft
azure-cosmos              3.1.2                      py_0
azure-identity            2022.12.01                 py_0    microsoft
azure-keyvault            2022.12.01                 py_0    microsoft
azure-mgmt                2022.12.01                 py_0    microsoft
azure-storage             2022.12.01                 py_0    microsoft


(base) PS C:\Windows\system32>
```

I couldn't find an azure-mgmt-batch package in the conda-forge channel, so I guess that has to be a pip install for now?

**Comment by xiangyan99** [comment]
@apjanke-demex Thanks for reaching out.

https://anaconda.org/microsoft/repo only contains track 2 libraries.

Unfortunately, azure-batch has not migrated to track 2 yet.

Hence it is not on https://anaconda.org/microsoft/repo yet.

And you are right. You need to use conda-forge or pypi to install them.

To answer your question:
I'm guessing that means either its dependency versions close enough to what's in the microsoft packages that it didn't alter anything?

Because it is still track 1, it depends on different libraries from other track 2 libraries. :)

Thanks.

**Comment by apjanke** [comment]
/unresolve

Getting pretty close, but I've got a couple lingering problems.

It looks like the Track 1 and Track 2 libraries as published to Conda have mostly different dependencies, but they have a couple common indirect dependencies, which may be causing a version or similar conflict if you mix and match them.

That sounds about right to me. Doing conda search --info, I see the following dependencies (pkgs are conda-forge unless specified otherwise):
* azure-batch -> azure-common, msrestazure
* microsoft/azure-storage -> aiohttp, azure-core, azure-identity, cryptography, isodate, msrest, requests-oauthlib
* [microsoft/msrest](https://anaconda.org/microsoft/msrest) -> azure-core, certifi, isodate, requests, requests-oauthlib
* [conda-forge/msrest](https://anaconda.org/conda-forge/msrest) -> azure-core, certifi, isodate, requests, requests-oauthlib

I think that means we have a conflict in that these two dependency chains will lead to msrest and azure-core:
* conda-forge/azure-batch -> msrestazure -> msrest -> azure-core
* microsoft/azure-storage -> (msrest, azure-core)
* [pypi/azure-mgmt-batch](https://pypi.org/project/azure-mgmt-batch/) -> azure-mgmt-core, azure-common …
  * based on `pip install --dry-run` output. No azure-mgmt-common dep!
* [azure-mgmt-core](https://anaconda.org/conda-forge/azure-mgmt-core) -> azure-core

I'm not exactly sure how conda will handle that in terms of selecting a package to fulfill the dependencies. I think it'll treat the msrest and azure-core packages of the same name in the different channels as the same package, and then select based on version? I think that means if the version requirements in the dependencies are simple `>=` values, then it will pick one of the microsoft-channel ones, because its "yyyy.mm.dd" version scheme is always going to look larger than any "major.minor.patch" version from the old conda-forge packages? But if there's a dependency on a (min, max) range of versions in the old conda-forge packages, there might be a resolution problem.

The azure-mgmt-batch PyPI package depends on azure-mgmt-core. I tried installing azure-mgmt-core with conda, to keep as many of my packages conda-managed as I can. Didn't work out, due to a conflict of some sort. On my machine, I ran the following. It ran for over a day "examining conflicts" before I eventually killed it with Ctrl-C.

```
(base) PS C:\Users\Andrew.Janke> Get-Date; conda install -c conda-forge azure-mgmt-core; Get-Date

Tuesday, March 7, 2023 8:42:30 AM
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining scipy:   1%|▋                                                                                                             | 4/595 [00:18<44:27,  4.51s/it]/Examining tblib:   2%|█▊                                                                                                           | 10/595 [00:48<30:17,  3.11s/it]|
```

So I fell back to doing a `pip install azure-mgmt-batch`, and it picked up azure-mgmt-core through pip. pip accepted the existing conda-installed azure-core and msrest to satisfy its dependencies. That ought to work, right?

```
(base) PS C:\Windows\system32> Get-Date; pip install azure-mgmt-batch; Get-Date

Thursday, March 9, 2023 10:31:18 AM
Collecting azure-mgmt-batch
  Using cached azure_mgmt_batch-17.0.0-py3-none-any.whl (157 kB)
Requirement already satisfied: azure-common~=1.1 in c:\programdata\anaconda3\lib\site-packages (from azure-mgmt-batch) (1.1.28)
Requirement already satisfied: msrest>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from azure-mgmt-batch) (0.7.1)
Requirement already satisfied: azure-mgmt-core<2.0.0,>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from azure-mgmt-batch) (1.3.2)
Requirement already satisfied: azure-core<2.0.0,>=1.24.0 in c:\programdata\anaconda3\lib\site-packages (from azure-mgmt-core<2.0.0,>=1.3.2->azure-mgmt-batch) (1.26.3)
Requirement already satisfied: requests-oauthlib>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from msrest>=0.7.1->azure-mgmt-batch) (1.3.1)
Requirement already satisfied: requests~=2.16 in c:\programdata\anaconda3\lib\site-packages (from msrest>=0.7.1->azure-mgmt-batch) (2.28.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from msrest>=0.7.1->azure-mgmt-batch) (2022.12.7)
Requirement already satisfied: isodate>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from msrest>=0.7.1->azure-mgmt-batch) (0.6.1)
Requirement already satisfied: six>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure-mgmt-batch) (1.16.0)
Requirement already satisfied: typing-extensions>=4.0.1 in c:\programdata\anaconda3\lib\site-packages (from azure-core<2.0.0,>=1.24.0->azure-mgmt-core<2.0.0,>=1.3.2->azure-mgmt-batch) (4.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.16->msrest>=0.7.1->azure-mgmt-batch) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.16->msrest>=0.7.1->azure-mgmt-batch) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.16->msrest>=0.7.1->azure-mgmt-batch) (3.4)
Requirement already satisfied: oauthlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests-oauthlib>=0.5.0->msrest>=0.7.1->azure-mgmt-batch) (3.2.2)
Installing collected packages: azure-mgmt-batch
Successfully installed azure-mgmt-batch-17.0.0
Thursday, March 9, 2023 10:31:23 AM
```

BTW, the conda-forge and microsoft versions of azure-core depend on differently-named [“typing-extensions”](https://anaconda.org/conda-forge/typing-extensions) and [“typing_extensions”](https://anaconda.org/conda-forge/typing_extensions), it looks like. Is that going to cause an issue?

```
(base) PS C:\Windows\system32> conda search --info azure-core==1.26.3 | sls typing
  - typing-extensions >=4.0.1
(base) PS C:\Windows\system32> conda search --info azure-core==2023.03.01 | sls typing
  - typing_extensions
```

---

And would it be crazy of me to want to run the [Azure SDK for Python test suite](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/mgmt/tests.md) against our Python environment to validate that this mixed microsoft/conda-forge/PyPI installation setup works correctly?

**Comment by xiangyan99** [comment]
Sorry for the late reply as I was on vacation last week.

azure-core is completely backwards compatible. You can always install the latest one (the latest conda one) and it should work in all scenarios.

The latest conda azure-core also contains azure-mgmt-core. You can try not install azure-mgmt-core separately.

azure-common has not been changed for a while (~one year). No matter you install it from conda-forge or microsoft channel, they are exactly the same.

Hope this helps.

**Comment by apjanke-demex** [comment]
Great! Yes, that helps, and tells me what I needed to know. We can close this ticket out now.

Thanks for your responsiveness here! And never apologize for taking a vacation. ;)
