### ISSUE TITLE
exclude_shared_token_cache_credential default value is False in Python version SDK.

### ISSUE THREAD

**Issue by Kit-Law-42** [Azure/azure-sdk-for-python#29462]
- **Package Name**: azure.identity
- **Package Version**: 1.13
- **Operating System**: Windows10
- **Python Version**: 3.9.16

**Describe the bug**
exclude_shared_token_cache_credential default value is False in DefaultAzureCredential() class

**To Reproduce**
Initiate DefaultAzureCredential class.

**Expected behavior**
Expecting same behaviour between .NET and Python, default value is True.

**DIscussion threads on .NET SDK in 2020
https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet
https://github.com/Azure/azure-sdk-for-net/issues/17052
https://github.com/Azure/azure-sdk/issues/1970

**Screenshots**
![image](https://user-images.githubusercontent.com/8088801/226396955-97a71dc3-1ea3-41e5-8ca2-ce17b0d5ece8.png)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by xiangyan99** [comment]
@Kit-Law-42 Thanks for pointing out the inconsistencies.

.net deprecated SharedTokenCacheCredential from DefaultAzureCredential because they added VisualStudioCredential to take care of the scenario that users want to use the login information from VS to authenticate.

While for Python, we still rely on SharedTokenCacheCredential for such scenario. And this is the reason we keep it in the DefaultAzureCredential.

Thank you.
