### ISSUE TITLE
ContainerClient.list_blobs doesn't list hidden (dot) files

### ISSUE THREAD

**Issue by drkennetz** [Azure/azure-sdk-for-python#29520]
- **azure_storage_blob**: 
- **12.9.0**: 
- **Red Hat Enterpride Linux Server 7.7 (Maipo)**:
- **3.7.4**: 

**Describe the bug**
I have dot files in a container:
```
container/path/.myfile.txt
```
and the following:
```
container_client.list_blobs(container)
```
lists all the blobs in the tree, except for the ones that start with a "."

**To Reproduce**
1. Add a hidden file (with content, not 0 length file) to a container in path that is not at the base of the container. Example, if your container is called "mycontainer", then make the path `mycontainer/dummypath/.myfile.txt`
2. Add some other non-hidden, regular files to the container. Examples `mycontainer/dummypath/fun1.txt`, `mycontainer/dummypath/fun2.txt`
3. Connect to the container `container_client = ContainerClient(account_url=account_url, container_name="mycontainer", credential=sas_token)`
4. list the blobs: `blobs = container_client.list_blobs("dummypath")`
5. print the blob names: `[print(b.name) for b in blobs]`

**Expected behavior**
I would expect to see `dummypath/.myfile.txt`, `dummypath/fun1.txt`, and `dummypath/fun2.txt`

**Comment by mccoyp** [comment]
Hi @drkennetz, thank you for opening an issue! I'll tag some folks who should be able to help and we'll get back to you as soon as possible.

**Comment by vincenttran-msft** [comment]
Hi @drkennetz Dennis, thanks for your inquiry. Unfortunately, I have not been able to reproduce your findings locally. Here is a code sample (and output from said code sample) that I used to attempt to reproduce this issue. Please let me know if there is anything that I have done that does not accurately represent your scenario:
```
from azure.storage.blob import BlobServiceClient, ContainerClient

# Constants
ACCOUNT_URL = f"https://XXXXXXX.blob.core.windows.net"
CONN_STR = "DefaultEndpointsProtocol=https;AccountName=XXXX;AccountKey=XXXXXXX;EndpointSuffix=core.windows.net"
data = b'helloworld'

# Setup
bsc = BlobServiceClient.from_connection_string(CONN_STR)
container_client = bsc.get_container_client(container='mycontainer')
container_client.create_container()

bc1 = container_client.get_blob_client('dummypath/.myfile.txt')
bc1.upload_blob(data=data)

bc2 = container_client.get_blob_client('dummypath/fun1.txt')
bc2.upload_blob(data=data * 2)

bc2 = container_client.get_blob_client('dummypath/fun2.txt')
bc2.upload_blob(data=data * 3)


# Repro
sas_token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
container_client = ContainerClient(account_url=ACCOUNT_URL, container_name="mycontainer", credential=sas_token)
blobs = container_client.list_blobs("dummypath")
[print(b.name) for b in blobs]
```
Output:
![image](https://user-images.githubusercontent.com/101599632/227361987-716ca8f5-6b55-4335-8e94-cf2ec437f08c.png)

I have attempted to reproduce this on both HNS-enabled and non-HNS enabled accounts, and both your package version (12.9.0) and latest version (12.15.0) and could not reproduce your findings.

With that being said, here are some things to look into on your end:

- If possible, use the latest package version of `azure-storage-blob` (current: 12.15.0)
- The SAS token I used was full permission (read, add, create, write, delete, list). This may be good to check, although I would think you would hit a permissions error and not just silently swallow the "hidden" file from being listed
- If you are generally interfacing with files and directories, consider using the `azure-storage-file-datalake` package which supports hierarchical namespace
- Please note that if you are currently using an HNS-enabled Storage account (you can check this under the "Overview" tab of your Storage account, under Properties-> Data Lake Storage-> Hierarchical namespace (will be `Enabled` or `Disabled`) with the `azure-storage-blob` package, this is not technically an officially supported scenario and we cannot provide in depth support or guarantees. The officially support scenarios include: `azure-storage-blob` + HNS-disabled accounts OR `azure-storage-file-share` + HNS-enabled accounts

With that being said, hopefully the provided information can help you identify this behavior. Please let me know if you can identify the root cause of this behavior or if the issue is resolved!
Thanks!

**Comment by drkennetz** [comment]
@vincenttran-msft thank you so much for the detailed information - that was incredible feedback! I will do my best to track down the root cause of the issue, and update back with the information I find. I really appreciate this! I was actually hoping this would be the case, as that means it should be supported, and perhaps there is just something incorrect on my end.
Thanks for your help!

**Comment by drkennetz** [comment]
@vincenttran-msft thank you for looking into this - it turns out we actually have a few cases where this hidden file failed to transfer, complicated by the fact that it also didn't exist on our current filesystem. When I went to list the blobs, it wasn't there because it actually wasn't there. This was a pretty rare edge case, and so it sent me down the wrong path. Your help led me down the right path! Thank you for your time, and sorry for the red herring. Feel free to close!
