### ISSUE TITLE
Get Bearer Token for Azure Cloud for Sustainability API

### ISSUE THREAD

**Issue by Madhava24** [Azure/azure-sdk-for-python#29587]
**The Issue:**
I'm working on Microsoft Cloud for Sustainability REST APIs. Each of these APIs require a bearer token for authorization except the Metadata API.

For example, I made a GET request on Emissions By Enrollment API. I have my primary and secondary keys (subscription keys) with me. Now, I'm unable to find a way to get a bearer token from these subscription keys. I have tried passing the subscription key in the header, but that did not work as I get this - "401 unauthorized" error. In the response header, I am seeing that the Bearer token is required for authorization.

**Request:**
I need a way to get bearer token for these sustainability APIs using the subscription keys. Or any other better auth method and better of way getting the data from these APIs using Postman and/or Python. 

A module for accessing these APIs using the available auth methods will be a great solution. 

Thanks in advance.

**Comment by SaurabhSharma-MSFT** [comment]
@Madhava24 Have you looked at [document](https://learn.microsoft.com/en-us/industry/sustainability/api-overview#get-started-with-cloud-for-sustainability-apis) to get a token for accessing api?

**Comment by Madhava24** [comment]
@SaurabhSharma-MSFT  Sorry for the late reply. I have checked this [document](https://learn.microsoft.com/en-us/industry/sustainability/api-overview#get-started-with-cloud-for-sustainability-apis) already. But it says the '_Authorization_' field is auto-populated (under Try the APIs). I want to know, which parameters w.r.t the  Microsoft Cloud for Sustainability(Mcfs) are required to get the access token if we want to generate it manually.

Previously, I obtained the access token for Azure Cost Management API using _tenant_ID, client_ID, client_secret_ . Should I get the access token for Mcfs also in the same way or is there any better way? If so, where should I use my primary and secondary subscription keys?

**Comment by SaurabhSharma-MSFT** [comment]
@Madhava24 sorry for the delay.  I haven't been able to use the Sustainability API due to my environment restrictions but yes you can try getting the access token using tenant_id, client_id and client_secret.  You don't need to provide the subscription key in the call instead you need to use `c3163bf1-092f-436b-b260-7ade5973e5b9/.default` as 'Resource'/scope to get the required access token.  As a prerequisite you need to give **App.Emissions.Read** permission of Sustainability API to your registered application.  
![image](https://user-images.githubusercontent.com/38112130/236546435-6f62e113-b4aa-4651-8e3d-cfc9f6e310d5.png)
Please refer to the [documentation](https://learn.microsoft.com/en-us/industry/sustainability/api-overview#how-do-i-configure-an-app-to-call-the-mcfs-api) for details.  Hope this helps. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@Madhava24 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
