### ISSUE TITLE
Improve "not logged in" checking for CLI-credentials.

### ISSUE THREAD

**Issue by teesana** [Azure/azure-sdk-for-python#29649]
- **Package Name**: azure-identity
- **Package Version**: 1.12.0
- **Operating System**: Mac OS
- **Python Version**: 3.9.6

**Describe the bug**
Using the `AzureCliCredential()` sometimes fails with

```
azure.identity._exceptions.CredentialUnavailableError: Please run 'az login' to set up an account
Error: Please run 'az login' to set up an account
```

However, after running `az login`, that error message persists, so that doesn't seem to be the problem.

Adding a line like `print(ex.stderr)` [here](https://github.com/Azure/azure-sdk-for-python/blob/dffd1a608c295d843ef2035f27591d92eab12a24/sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py#L167) reveals the actual issue:

```
ERROR: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2023-03-28T09:14:41.4963738Z and the maximum allowed lifetime for this request is 14400.
Trace ID: b6948a5f-63c8-43a3-8b4d-bbe261058e00
Correlation ID: d6233070-2453-410f-8209-d5fd4b6dca5e
Timestamp: 2023-03-29 08:19:57Z
Interactive authentication is needed. Please run:
az login --scope https://graph.microsoft.com/.default
```

The code only checks for the presence of `az login` in the error message and assumes that the user is not logged in. But I *am* logged in, i.e. an `az login` that I run just before returned a valid subscription and prints the usual JSON object to stdout.

Maybe instead of
```python
raise CredentialUnavailableError(message=NOT_LOGGED_IN)
```
we should do
```python
raise CredentialUnavailableError(message=ex.stderr)
```

What do you think? Does that seem reasonable?

**To Reproduce**
1. I don't know the minimum required steps to reproduce this, but it happens fairly consistently to me.

**Expected behavior**
It should print the actual error.

**Comment by pvaneck** [comment]
Thanks for the feedback and investigation. I agree that simply checking for "az login" doesn't seem to be sufficient enough to cover cases where a user might actually be logged in, but has a different error message that also happens to include "az login".

I think propagating a sanitized `ex.stderr` in the `CredentialUnavailableError` is probably fine for this case, or we could also make the string comparison more specific so that this case would be raised by the `ClientAuthenticationError` instead which does already propagate the `ex.stderr` (for example, check for "'az login' to setup account" instead of just "az login". 

@xiangyan99 wdyt?

**Comment by joshfree** [comment]
Updating title for easier tracking cross language repos
