### ISSUE TITLE
ImportError: cannot import name 'StorageErrorException' from 'azure.storage.blob._generated.models' 

### ISSUE THREAD

**Issue by prerna-tesser** [Azure/azure-sdk-for-python#29760]
I am stuck at this bug in analyzing the deprecation issue.

Would anyone have an idea on this?  

Exception: ImportError: cannot import name 'StorageErrorException' from 'azure.storage.blob._generated.models' (/Users/prernaladha/Documents/Tesser/Git/TesserInsights/tipro-py-tai/.venv/lib/python3.8/site-packages/azure/storage/blob/_generated/models/__init__.py). Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound

 

I have all these packages installed: 

azure-storage==0.36

azure-storage-blob==12.13.0

 

I have also tried azure-storage-blob==12.15.0 version and it still gave me the same error.

**Comment by kashifkhan** [comment]
HI @prerna-tesser, thank you for your feedback. We will investigate and get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @prerna-tesser, I believe your issue may be happening because you have `azure-storage` installed. This is a deprecated package that contains old versions of the Storage SDKs and therefore is not needed and should not be installed alongside a modern version of the SDK.  You should just need `azure-storage-blob` and its dependencies.

One other thing to check is your version of `azure-core`, please try everything with the latest version of that as well.

It is probably best to start with a clean environment and just do `pip install azure-storage-blob`. This will grab the latest version of the Blob SDK and Core and should be all you need. Thanks.

**Comment by prerna-tesser** [comment]
Hi, I just updated the packages and used the latest versions and that helped me out. Thank you.
