### ISSUE TITLE
DefaultAzureCredential fails if managed identity don't work

### ISSUE THREAD

**Issue by mlongtin0** [Azure/azure-sdk-for-python#29883]
- **Package Name**: azure-identity
- **Package Version**: 1.12
- **Operating System**: ubuntu
- **Python Version**: 3.10

**Describe the bug**
1. We have a VM that has Managed Identities assigned (one or more)
2. We are signed in using the Azure cli
3. We try to access a storage account using DefaultAzureCredential.
4. None of the managed identities have access to the storage account
5. We get an AuthorizationPermissionMismatch exception

I would expect that if managed identity doesn't work, then proceed to the other methods, like AzureCliCredential.

In this particular case, we're using a blob storage with hierarchical namespace.

**To Reproduce**
See description

**Expected behavior**
I would expect that if managed identity doesn't work, then proceed to the other methods, like AzureCliCredential.

**Screenshots**
N/A

**Additional context**

**Comment by xiangyan99** [comment]
@mlongtin0 Thanks for your feedback.

It is by design that if DefaultAzureCredential finds a managed identity but it does not work, we stop and fail the application rather than silently swallow the issue and continue.

Managed identity is designed as a production identity and cli is designed as a development identity.

If a production identity fails, we want to explicitly call it out and let developers be aware and take care of it.

In your case, I would suggest you can use AzureCliCredential directly instead of DefaultAzureCredential if you don't have to use managed identity.

Thanks.
