### ISSUE TITLE
Exportable keys must have release policy error

### ISSUE THREAD

**Issue by AnneNamuli** [Azure/azure-sdk-for-python#29945]
- **Package Name**: Azure Key Vault Keys
- **Package Version**: 4.8.0
- **Operating System**: MacOS
- **Python Version**: 3.10

**Describe the bug**
Trying to use the above package to create key in AKV with attached SKR policy 

**To Reproduce**
```
rsa_key = key_client.create_key(
                project_name,
                hardware_protected=True,
                size=key_size,
                key_operations=key_ops,
                exportable=True,
                hardware_protected=True,
                release_policy=release_policy,
            )
my SKR policy follow the format described in the documentation here: https://learn.microsoft.com/en-us/azure/confidential-computing/concept-skr-attestation
```

**Expected behavior**
To return the 200 and json with metadata

**Screenshots**
azure.core.exceptions.HttpResponseError: (BadParameter) Exportable keys must have release policy (Activity ID:XXXXXXXXX-a72d-XXXXXXXXXX)
Code: BadParameter
Message: Exportable keys must have release policy (Activity ID: <UUID>)

**Additional context**
same command works with az-cli on my terminal
`az keyvault key create --exportable true --vault-name "vault name from step 1" --kty RSA-HSM --name "keyname" --policy "jsonpolicyfromstep3 -can be a path to JSON" --protection hsm --vault-name "name of vault created from step1"`
`

**Comment by mccoyp** [comment]
Hi @AnneNamuli, thank you for opening an issue! It's odd that you're seeing this error message even when specifying a `release_policy`; if it were just a policy formatting issue, I would expect a different response. I have just a few questions to sort out what might be the cause:

1. How did you create the `release_policy` that's being passed to the key creation request? Did you pass a `content_type` or `immutable` parameter to the `KeyReleasePolicy` constructor?
2. Do you know the SKU of your Key Vault resource (i.e. if it's standard or premium)?
3. Are you able to share the content of the release policy that you're using, with any sensitive content redacted? This would be helpful just to verify the exact structure.

**Comment by AnneNamuli** [comment]
> Hi @AnneNamuli, thank you for opening an issue! It's odd that you're seeing this error message even when specifying a `release_policy`; if it were just a policy formatting issue, I would expect a different response. I have just a few questions to sort out what might be the cause:
> 
> 1. How did you create the `release_policy` that's being passed to the key creation request? Did you pass a `content_type` or `immutable` parameter to the `KeyReleasePolicy` constructor?
> 2. Do you know the SKU of your Key Vault resource (i.e. if it's standard or premium)?
> 3. Are you able to share the content of the release policy that you're using, with any sensitive content redacted? This would be helpful just to verify the exact structure.

Hi @mccoyp,

Thanks for the prompt response. This is the content of the release policy. Let me also get back to you on point 2.
{
   "content_type":"application/json; charset=utf-8",
   "encoded_policy":{
      "anyOf":[
         {
            "allOf":[
               {
                  "claim":"x-ms-attestation-type",
                  "equals":"sevsnpvm"
               },
               {
                  "claim":"x-ms-compliance-status",
                  "equals":"azure-compliant-uvm"
               },
               {
                  "claim":"x-ms-sevsnpvm-hostdata",
                  "equals":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
               }
            ],
            "authority":"https://<maa_name>.weu.attest.azure.net"
         }
      ],
      "version":"1.0.0"
   },
   "immutable":false
}

**Comment by AnneNamuli** [comment]
@mccoyp SKU is standard

**Comment by mccoyp** [comment]
Hi @AnneNamuli, thank you for the details. I believe it's expected that this operation would fail, since hardware-protected keys and secure key release are only available with Premium-SKU Key Vault and Managed HSM: https://learn.microsoft.com/azure/confidential-computing/concept-skr-attestation#skr-support-with-akv-offerings

That being said, the error response is still odd. I tried reproducing the error a few different ways on my end -- including using the same release policy format as yours -- but the only error I could yield with a standard-SKU vault was what I would expect:
```
azure.core.exceptions.HttpResponseError: (Forbidden) Hardware key operation not allowed on standard vault
```

After re-reading the issue, though, I just noticed that you said the command worked with the Azure CLI (I thought you had seen the same behavior/error with the CLI on first read). Do you mean that you were able to create the key, with the same release policy, using the CLI? Were you able to verify that the key was actually created as expected?

**Comment by mccoyp** [comment]
Hi again @AnneNamuli, I just tried reproducing this a few ways with the Azure CLI. Unfortunately I'm getting the same error I got with the SDK when using your command in a standard-SKU vault:
```
(Forbidden) Hardware key operation not allowed on standard vault
```
Since you're able to create a hardware-protected key, I think your vault must be either premium-SKU or an HSM.

More importantly though, I think I might have found the source of the issue 🙂 When I try creating an exportable key with the SDK and provide a release policy that was created with a string instead of bytes, I get your error. For example, running:
```python
from azure.keyvault.keys import KeyReleasePolicy

# Policy uses the format in your scenario; abbreviated here for readability
release_policy = KeyReleasePolicy(
    '{"content_type":"application/json; charset=utf-8"... ,"immutable":false}}'
)

rsa_key = key_client.create_key(
    "keyname",
    exportable=True,
    hardware_protected=True,
    release_policy=release_policy,
)
```
yields
```
azure.core.exceptions.HttpResponseError: (BadParameter) AKV.SKR.1004: Exportable keys must have release policy.
```
This is the case whether the release policy is valid or not; using an empty string in the `KeyReleasePolicy` constructor returns the same error.

This is because the [`KeyReleasePolicy` constructor](https://learn.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.keyreleasepolicy?view=azure-python) expects bytes instead of a string. If we pass the policy as bytes, the responses from the service are more like what we expect:
```python
from azure.keyvault.keys import KeyReleasePolicy

# Policy uses the format in your scenario; abbreviated here for readability
release_policy = KeyReleasePolicy(
    b'{"content_type":"application/json; charset=utf-8"... ,"immutable":false}}'
)
```
yields
```
azure.core.exceptions.HttpResponseError: (BadParameter) AKV.SKR.1008: Release policy version must be specified. Valid values are 0.2 and 1.0.0.
```
If we pass in empty bytes instead -- `b""` -- I get a different error from the server failing to parse the policy:
```
azure.core.exceptions.HttpResponseError: (ServerError) ActivityId: {ID}, ActivityName: KeyCreate
```

All of this is to say that you might be getting this error from the `KeyReleasePolicy` not being constructed as we expect. Please try encoding your policy as bytes if you're not already; if you already are, please send the full code snippet of constructing the policy and passing it to the `create_key` method (again, with anything sensitive redacted).

Whether this is the failure case you're hitting or not, I am going to open an issue for making the error more obvious when a `KeyReleasePolicy` is created with a string instead of bytes.

**Comment by AnneNamuli** [comment]
> Hi again @AnneNamuli, I just tried reproducing this a few ways with the Azure CLI. Unfortunately I'm getting the same error I got with the SDK when using your command in a standard-SKU vault:
> 
> ```
> (Forbidden) Hardware key operation not allowed on standard vault
> ```
> 
> Since you're able to create a hardware-protected key, I think your vault must be either premium-SKU or an HSM.
> 
> More importantly though, I think I might have found the source of the issue 🙂 When I try creating an exportable key with the SDK and provide a release policy that was created with a string instead of bytes, I get your error. For example, running:
> 
> ```python
> from azure.keyvault.keys import KeyReleasePolicy
> 
> # Policy uses the format in your scenario; abbreviated here for readability
> release_policy = KeyReleasePolicy(
>     '{"content_type":"application/json; charset=utf-8"... ,"immutable":false}}'
> )
> 
> rsa_key = key_client.create_key(
>     "keyname",
>     exportable=True,
>     hardware_protected=True,
>     release_policy=release_policy,
> )
> ```
> 
> yields
> 
> ```
> azure.core.exceptions.HttpResponseError: (BadParameter) AKV.SKR.1004: Exportable keys must have release policy.
> ```
> 
> This is the case whether the release policy is valid or not; using an empty string in the `KeyReleasePolicy` constructor returns the same error.
> 
> This is because the [`KeyReleasePolicy` constructor](https://learn.microsoft.com/python/api/azure-keyvault-keys/azure.keyvault.keys.keyreleasepolicy?view=azure-python) expects bytes instead of a string. If we pass the policy as bytes, the responses from the service are more like what we expect:
> 
> ```python
> from azure.keyvault.keys import KeyReleasePolicy
> 
> # Policy uses the format in your scenario; abbreviated here for readability
> release_policy = KeyReleasePolicy(
>     b'{"content_type":"application/json; charset=utf-8"... ,"immutable":false}}'
> )
> ```
> 
> yields
> 
> ```
> azure.core.exceptions.HttpResponseError: (BadParameter) AKV.SKR.1008: Release policy version must be specified. Valid values are 0.2 and 1.0.0.
> ```
> 
> If we pass in empty bytes instead -- `b""` -- I get a different error from the server failing to parse the policy:
> 
> ```
> azure.core.exceptions.HttpResponseError: (ServerError) ActivityId: {ID}, ActivityName: KeyCreate
> ```
> 
> All of this is to say that you might be getting this error from the `KeyReleasePolicy` not being constructed as we expect. Please try encoding your policy as bytes if you're not already; if you already are, please send the full code snippet of constructing the policy and passing it to the `create_key` method (again, with anything sensitive redacted).
> 
> Whether this is the failure case you're hitting or not, I am going to open an issue for making the error more obvious when a `KeyReleasePolicy` is created with a string instead of bytes.

Hi @mccoyp, Looking again at the keyrelease constructor,  only the encoded policy is parsed as bytes, content_type is a string and immutable is a boolean. This is what I did for it to work:

release_policy = KeyReleasePolicy(content_type="application/json; charset=utf-8",encoded_policy=b'{"anyOf":[{"allOf":[{"claim":"x-ms-attestation-type","equals":"sevsnpvm"},{"claim":"x-ms-compliance-status","equals":"azure-compliant-uvm"},{"claim":"x-ms-sevsnpvm-hostdata","equals":"*********************************************"}],"authority":"https://<maa-name>.azure.net"}],"version":"1.0.0"}',immutable=False)

Thanks for all the help!

**Comment by AnneNamuli** [comment]
@mccoyp happy to close this :)

**Comment by mccoyp** [comment]
I did some more investigation of the service's behavior in an effort to improve the error experience for SDK users. It turns out that we don't always get an error when an invalid release policy is provided; the service actually ignores some invalid policies and can drop them silently. This is what happens when a string policy is sent instead of bytes.

An error (`Exportable keys must have release policy`) was raised in this issue's case because the `exportable` flag was set to True during the `create_key` request. However, if `create_key` is used with an invalid release policy and _without_ `exportable=True`, the key is successfully created. This key just won't have a release policy at all -- but a user wouldn't know this unless they inspect the created key.

cc @jackrichins
