### ISSUE TITLE
How to use Async Azure Service Bus Queue with Trio

### ISSUE THREAD

**Issue by BeyondEvil** [Azure/azure-sdk-for-python#30011]
**Is your feature request related to a problem? Please describe.**
Using Azure Service Bus Queue async example, fails with:

```
azure.servicebus.exceptions.ServiceBusError: Handler failed: trio.run received unrecognized yield message <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.10/asyncio/tasks.py:857]>. Are you trying to use a library written for some other framework like asyncio? That won't work without some kind of compatibility shim..
```

**Describe the solution you'd like**
Azure Service Bus Queue should be agnostic (or at least be easily extendible) to the underlying async lib.

**Comment by kashifkhan** [comment]
Thank you for the feedback @BeyondEvil . Will discuss with the team and update this

**Comment by BeyondEvil** [comment]
Thank you!

Please let me know if you need any more info etc.

Happy to provide it.

**Comment by BeyondEvil** [comment]
I experimented with:

```
from azure.core.pipeline.transport._requests_trio import TrioRequestsTransport

servicebus_client = ServiceBusClient.from_connection_string(
        conn_str=CONNECTION_STR, transport_type=TrioRequestsTransport
    )
```

But that gave me:

```
    if transport_type and transport_type.value == TransportType.AmqpOverWebsocket.value or http_proxy is not None:
AttributeError: type object 'TrioRequestsTransport' has no attribute 'value'
```

**Comment by annatisch** [comment]
I don't believe this will be possible today. Both the underlying uamqp and pyamqp transports rely on a couple of asyncio features. When initially working on Pyamqp we attempted to make it async-agnostic using a 3rd party library that exposed a consistent async interface supporting different event loops, however at the time this resulted in massive performance loss, which was a non-starter for EventHubs (which shares the pyamqp transport layer, and where we were initially focusing the dev effort).

We should definitely investigate adding support back for this - as @BeyondEvil suggested, if we go with a "point of extension" design, rather than depending on a 3rd party lib, perhaps we can escape the perf loss. @kashifkhan - I think we should put this down for a future milestone - perhaps part of the process of spinning pyamqp off into a standalone library. I don't think this should be targeted before the SB-pyamqp GA though.

As an aside, I would not recommend attempting async agnostic support in uamqp - because of the way the C lib we are wrapping works, the async support was a hacky add-on using asyncio's running coroutines in background threads feature.

**Comment by BeyondEvil** [comment]
Thank you for your thorough answer @annatisch 

I’m not familiar enough with the async(io) implementation to suggest ways to become agnostic.

But I think long term it’s a good practice to allow consumers of the SDK to choose which async lib to work with.

With that said, I ended up not using the async version of the service bus. It’s a very small queue with not a lot of messages, so I’m fine with receiving them sync.

Then I use Trio to process each message async.
