### ISSUE TITLE
Is any plan to support Python37?

### ISSUE THREAD

**Issue by qzqsmile** [Azure/azure-sdk-for-python#3010]
i selected Python37 released last month as my default interpter, but it raised some error tips when i try to import this library. is there any plan to support it?

**Comment by lmazuel** [comment]
What library when you say "this"? 3.7 is tested and part of our CI and everything works. CLI of Azure is already shipped with Python 3.7.

**Comment by qzqsmile** [comment]
The libraries import keyring. The error is caused by the library keyring from my tips. I tried to import keyring in python terminal. it also failed even i have installed it.
My dev: win10 64bit

**Comment by lmazuel** [comment]
`keyring` is an optional package for token caching. It prints weird things I admit, but it's disabled on the fly where `keyring` cannot be configured or run. This does NOT block any SDK usage, see our Travis job for instance:
https://travis-ci.org/Azure/azure-sdk-for-python/jobs/409164873

`keyring` will be removed as a dependency is the next version of the runtime, because we're moving to another cache system more reliable. In the meantime, you can uninstall safely `keyring` on Python 3.7, the code already ready to act without it and you won't get any `ImportError`.

Closing, since I believe the question is answered. Feel free to still comment if want to add or ask anything else.
Thanks,
