### ISSUE TITLE
Unexpected behaviour while downloading blob with match conditions

### ISSUE THREAD

**Issue by tejasvi-v-raut** [Azure/azure-sdk-for-python#30233]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.16.0
- **Operating System**: Linux
- **Python Version**: 3.9.16

**Describe the bug**
While downloading a blob, multiple requests are made in the background depending on parameters "max_single_get_size" (default 32MB) and "max_chunk_get_size" (default 4MB). For example, to download a blob of size 50MB, six requests are made, which will download 32MB, 4MB, 4MB, 4MB, 4MB and 2MB sized chunks each, in that order. If we specify some additional match conditions, however, those are applied only to first request and the subsequent requests use a different header (the etag retrieved in response of first request). We expect the subsequent requests to use the same match conditions as the first one.
Example,
Size of blob to be downloaded : 50 MB
Request 1: 'If-Match': '*'
Response 1: 'ETag': 'xyz', 'Content-Length': '33554432'
Request 2: 'If-Match': 'xyz'
Response 2: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 3: 'If-Match': 'xyz'
Response 3: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 4: 'If-Match': 'xyz'
Response 4: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 5: 'If-Match': 'xyz'
Response 5: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 6: 'If-Match': 'xyz'
Response 6: 'ETag': 'xyz', 'Content-Length': '2097152'

**To Reproduce**
1. Ensure the blob to be downloaded is greater than 32MB in size.
2. Import azure-storage-blob module
3. Create instance of BlobClient by specifying storage account url, container name, blob name and credential
4. Download blob by specifying match conditions as shown (Here, a wildcard match condition is specified)
```
from azure.storage.blob import BlobClient
from azure.core import MatchConditions

blob = BlobClient(account_url="<blob_account_url>", container_name="<blob_location>", blob_name="<blob_name>", credential="<access_key>")
data = blob.download_blob(etag='*', match_condition=MatchConditions.IfNotModified).readall().decode("UTF-8").split("\n")
```

**Expected behavior**
We expect the subsequent requests to use the same match conditions as the first one.

Example,
Size of blob to be downloaded : 50 MB
Request 1: 'If-Match': *
Response 1: 'ETag': 'xyz', 'Content-Length': '33554432'
Request 2: 'If-Match': *
Response 2: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 3: 'If-Match': *
Response 3: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 4: 'If-Match': *
Response 4: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 5: 'If-Match': *
Response 5: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 6: 'If-Match': *
Response 6: 'ETag': 'xyz', 'Content-Length': '2097152'

**Additional context**
Multiple requests are made to download a single blob. Sometimes, it happens that, by the time nth request is made, the blob is updated by a different process. This changes the etag value and "ConditionNotMet" exception is raised.

**Comment by jalauzon-msft** [comment]
Hi @tejasvi-v-raut, thanks for reaching out. This behavior that you describe is by design. When downloading a blob we download it in chunks, as you have noted, where each chunk is downloaded using a ranged download where we download a portion of the blob. These chunks are then put together (or streamed) to form the final full blob. This is done to be more efficent with network and memory use.

The reason we set the If-Match to the Etag of the blob for each request is that its crucial we ensure the blob does not change while we are downloading it in chunks. Otherwise, you may end up with a corrupted final blob with different chunks from different versions of the blob. If we allowed `If-Match:*` there is no guarantee the chunk is from the original version of the blob.

We can't really change this behavior for our chunked download for the reasons above so you would either need to ensure your blob does not change while it is being downloaded (see [here](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage) for some options on dealing with concurrency) or download the blob in a single request. The Python SDK does not currently offer a "full download" API but what you can do is set `max_single_get_size` to something larger than your largest blob. Just note, this means the whole blob will be downloaded in a single request and loaded into memory so there are network and memory considerations when doing that. But if your system can handle that, it should be fine.

**Comment by tejasvi-v-raut** [comment]
Hi @jalauzon-msft, thanks for the detailed explanation.

I had referred the [concurrency management document](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage) and chose the optimistic concurrency route by passing the `If-Match` header. I understand now why `If-Match:*` is not allowed. But is there any way to download the same version of blob, even if blob is updated by a different process during the download operation?

Using the same example of downloading a blob of size 50MB, 
Request 1: 'If-Match': '*'
Response 1: 'ETag': 'xyz', 'Content-Length': '33554432'
Request 2: 'If-Match': 'xyz'
Response 2: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 3: 'If-Match': 'xyz'
Response 3: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 4: 'If-Match': 'xyz'
Response 4: 'ETag': 'xyz', 'Content-Length': '4194304'
Request 5: 'If-Match': 'xyz'
**Response 5: 'ETag': 'xyy'** (412 ConditionNotMet exception)
_(Not executed)_ Request 6: 'If-Match': 'xyz'
_(Not executed)_ Response 6: 'ETag': 'xyz', 'Content-Length': '2097152'

Here, by the time 5th request is made, the blob is updated by a different process. Now, the `etag` value changes and we get "ConditionNotMet" error. Is there a way to continue downloading chunks of the older version (`'ETag': 'xyy'`)?

**Comment by jalauzon-msft** [comment]
Hi @tejasvi-v-raut, unfortunately there is no way to read from a previous version of the blob by default. You could consider using [versioning](https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview) or [snapshots](https://learn.microsoft.com/en-us/azure/storage/blobs/snapshots-overview) to maintain older versions of blobs but that would add a bit of complexity and storage cost. I would probably only recommend this if you actually wanted to maintain old copies of your blob.

The other recommendation, if you cannot read the entire blob in one request, would probably be to switch a [pessimistic approach to concurrency](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage#pessimistic-concurrency-for-blobs) where you use leases to lock the blob for reading and writing. This would obviously require some logic changes and probably will come with a bit of a perf hit to your application.
