### ISSUE TITLE
ServiceBusAdministationClient does not work with DefaultAzureCredentials. get_token was never awaited

### ISSUE THREAD

**Issue by ceramey1997** [Azure/azure-sdk-for-python#30368]
- **Package Name**: `azure-servicebus==7.10.0`
- **Operating System**: `WSL Ubuntu 22.04 Python 3.10.0`

**Describe the bug**
When an instance of the ServiceBusAdministrationClient is created using DefaultAzureCredentials, then a call to `get_queue_runtime_properties()` is awaited, an error occurs stating `sys:1: RuntimeWarning: coroutine 'DefaultAzureCredential.get_token` was never awaited`

**To Reproduce**
```sh
pip install azure-servicebus==7.10.0
pip install azure-identity==8.2.0
```
```python
from azure.identity.aio import DefaultAzureCredential
from azure.servicebus.management import ServiceBusAdministrationClient
import os

fqns = os.getenv("FULLY_QUALIFIED_NAMESPACE")

manager = ServiceBusAdministrationClient(fqns, DefaultAzureCredential())
queue_properties = manager.get_queue_runtime_properties("myQueuesName") # await or don't await, fails both ways
```

**Expected behavior**
The manager should grab a Token from Azure successfully with my Default Credentials. The `ServiceBusClient` functions wonderfully with DefaultAzureCredentials, and the `ServiceBusManagementClient` functions great with a connection_string. But, for our purposes I would like to use DefaultAzureCredentials. 

**Screenshots**
Stacktrace below, its the result of the show python snippet above.
```sh
sys:1: RuntimeWarning: coroutine 'DefaultAzureCredential.get_token' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/azure/servicebus/management/_management_client.py", line 301, in get_queue_runtime_properties
    entry_ele = self._get_entity_element(queue_name, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/azure/servicebus/management/_management_client.py", line 185, in _get_entity_element
    self._impl.entity.get(entity_name, enrich=enrich, **kwargs),
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/azure/servicebus/management/_generated/operations/_operations.py", line 478, in get
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 3 more times]
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 448, in send
    response = self.next.send(request)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 109, in send
    self.on_request(request)
  File "/home/user/.local/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 89, in on_request
    self._update_headers(request.http_request.headers, self._token.token)
AttributeError: 'coroutine' object has no attribute 'token'
```

**Additional context**
Seems like the bad call root is `azure > core > pipeline > policies > _authentication.py ` line 88

**Comment by kashifkhan** [comment]
Hi @ceramey1997, thank you for your feedback. Can you please try making the following changes:

`from azure.servicebus.management import ServiceBusAdministrationClient` 

to 

`from azure.servicebus.aio.management import ServiceBusAdministrationClient`

**Comment by ceramey1997** [comment]
@kashifkhan Thank you so much for directing me to that. It did work, is there something that I missed in the documentation that would have helped point me there earlier? Or, may I ask what the difference between those two are?

**Comment by kashifkhan** [comment]
Glad that it worked for you @ceramey1997 . 

Simply put, the difference is that one is the sync client versus the other one is the async client and is designed with that in mind. So passing in an async credential into the sync client would not work, as there are no await etc in there. 

The servicebus [samples](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/servicebus/azure-servicebus/samples) show how to use our client libraries in a variety of scenarios. They also list the async version of those scenarios. I would like to know the documentation that you used, so that they can be improved.

**Comment by ceramey1997** [comment]
Thanks for the information, I wasn't looking hard enough. I was using [this example](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/servicebus/azure-servicebus/samples/sync_samples/mgmt_subscription.py) and never went back a directory to see the async version

**Comment by ceramey1997** [comment]
@kashifkhan  While i've got you actually. On a different topic why does the `ServiceBusReceiver`'s method `receive_messages` return back a seemingly random amount of messages every time even if the `max_message_count` is the total messages in the queue. The documentation says that it only awaits for the first message and then goes, but I would like to await for the entire list of messages, and then extent the message locks if needed

**Comment by kashifkhan** [comment]
@ceramey1997 there is not currently a way to guarantee the minimum or exact number of messages returned on a call. 
When messages are requested, the prioritization is to return data to your application quickly so that the locks for the messages that have been received do not expire waiting for the additional messages needed to fill the batch, and so that your application doesn't sit idle. You are not guaranteed to receive the number of messages requested, even if the queue or subscription has that many messages available at that time

Prefetch can help by making more messages available to the batch, but they have to be streamed in over the network. Depending on the size of messages, it can take a bit to stream in enough to fill the prefetch cache and if you're consuming messages faster than the network can stream them, the cache will run dry.

An important consideration for prefetch is to remember that messages held in the prefetch cache are locked by the service, and those locks will expire if they are not consumed quickly enough.
