### ISSUE TITLE
ContainerClient.list_blobs(): Add support for showonly parameter (to filter files or directories)

### ISSUE THREAD

**Issue by krissmilne** [Azure/azure-sdk-for-python#30470]
**Is your feature request related to a problem? Please describe.**
When calling Azure Storage Container Client list_blobs() on a container that has hierarchical namespace enabled. Directories are also returned in the list of blobs.

Based on an assessment of all properties returned for a blob it is impossible to distinguish between a Directory and a File. There is no property or attribute that uniquely identifies a Directory.

This creates numerous unexpected behavior issues when downloading blobs as Directories are downloaded as zero byte files.

**Describe the solution you'd like**
The Azure Container List Blobs REST API has support for a property called `showonly` that can filter on files or directories for Storage Accounts that have hierarchical namespace enabled.

The preferable solution would also be that Directories and Files have a property or attribute that identifies them as a file or directory so that the client can handle them accordingly.

**Describe alternatives you've considered**
The only alternative available is to use a combination of properties to assume a Blob is a directory (size, content-type and content-md5) are all null for a Directory, where as a zero byte file still appears to have a content-type and content-md5.

**Additional context**
It is important for a client to be able to distinguish between a Directory and a File when programmatically interfacing with the Storage Account Container Blob service. There is a distinct difference between Directories and Files. The current implementation there is no discernable difference between a Directory and a zero byte file when using list_blobs with hierarchical namespace enabled.

**Comment by jalauzon-msft** [comment]
Hi @krissmilne Kriss, thanks for reaching out. For accounts with hierarchical namespace enabled, we recommend you use our ADLS Gen 2 SDK, [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake/), as this SDK is designed to work with these types of accounts. We try and avoid adding HNS specific concepts, like files/directories, to the `azure-storage-blob` SDK as normal, or "flat" accounts do not have these concepts.

If you were to switch to the Datalake SDK, you could use the `FileSystemClient.get_paths` API instead to list your blobs. This would return a list of [PathProperties](https://learn.microsoft.com/en-us/python/api/azure-storage-file-datalake/azure.storage.filedatalake.pathproperties?view=azure-python) objects which contain the `is_directory` boolean property which can be used to distinguish between files/directories. Ideally the `PathProperties` would also still contain all other information you need about the blobs. This API internanly uses the [List - Paths API](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/list) from the DFS Storage endpoint instead of List Blobs.

Hopefully this helps, thanks.
