### ISSUE TITLE
enable_auto_scaling misbehavior

### ISSUE THREAD

**Issue by NitroAMD** [Azure/azure-sdk-for-python#30544]
- **Package Name**: 
azure.mgmt.containerservice

- **Package Version**: 
23.0.0

- **Operating System**:
Windows 11

- **Python Version**: 
3.10

**Describe the bug**
While using underscore parameters/properties for the autoscaler ("enable_auto_scaling", "max_count", "min_count") the AKS cluster node pool changes from Autoscale to Manual.

**To Reproduce**
1. Create an AKS cluster and set the Autoscaler (1 - 10) for the node pool
2. Use underscores for the parameters/properties and Run the code:

```
from azure.identity import DefaultAzureCredential
from azure.mgmt.containerservice import ContainerServiceClient

def main():
    client = ContainerServiceClient(
        credential=DefaultAzureCredential(exclude_interactive_browser_credential=False),
        subscription_id="PLACEHOLDER"
    )

    response = client.agent_pools.begin_create_or_update(
        resource_group_name="PLACEHOLDER",
        resource_name="PLACEHOLDER",
        agent_pool_name="PLACEHOLDER",
        parameters={
            "properties": {
                "type": "VirtualMachineScaleSets",
                "enable_auto_scaling": True,
                "max_count": 10,
                "min_count": 1,
                "osType": "Linux"
                #"mode": "System"
            }
        },
    ).result()
    print(response)

if __name__ == "__main__":
    main()
```

3 The output reports "...'max_count': None, 'min_count': None, 'enable_auto_scaling': None..." (Process finished with exit code 0)

**Expected behavior**
It should throw out an error at validation or it should not change the AKS autoscaler to manual/"None" (keep the Autoscaler enabled as it was set at AKS cluster creation time).

**Screenshots**
NA

**Additional context**
NA

**Comment by kashifkhan** [comment]
Thank you for the feedback @NitroAMD . We will investigate and get back to you asap.

**Comment by msyyc** [comment]
Hi @NitroAMD When you input `dict` into model, the key name shall be camel-case instead of snake-case:
```json
...
"maxCount": 10,
"minCount": 1,
...
```
Here is the sample reference: https://github.com/Azure/azure-sdk-for-python/blob/b0e9822238b878140ba07328e8e7d30b13364776/sdk/containerservice/azure-mgmt-containerservice/generated_samples/agent_pools_update.py#L40-L41

**Comment by NitroAMD** [comment]
Thanks and yes enableAutoScaling, maxCount, minCount works as expected, but my reported issue is related to properties with an underscore:

"enable_auto_scaling", "max_count", "min_count"

Why I get no error at validation and/or why it is removing the Autoscaler and putting it to "Manual" with these Properties?
3 The output reports "...'**max_count': None**, **'min_count': None**, **'enable_auto_scaling': None**..." (Process finished with exit code 0)

**Comment by msyyc** [comment]
Let me introduce more about operation https://github.com/Azure/azure-sdk-for-python/blob/97511f2358a8fcbedfdb0de9962a21534368e613/sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2023_04_01/operations/_agent_pools_operations.py#L762-L771.

For convenient usage, Python SDK accept two kinds of type for `parameters`.
(1) model
```python
from azure.mgmt.containerservice.models import AgentPool

client.agent_pools.begin_create_or_update(..., parameters=AgentPool(
    max_count=10, min_count=1, enable_auto_scaling=True
))
```
(2) json-like object
```python
client.agent_pools.begin_create_or_update(...,
                                          parameters={
                                              "properties": {
                                                  "enableAutoScaling": True,
                                                  "maxCount": 10,
                                                  "minCount": 1,
                                              }})
```
We can see: with model, the attribute is snake-case which follows python naming pattern; with json-like object, the name pattern becomes camel-case which is same with [swagger definion](https://github.com/Azure/azure-rest-api-specs/blob/b9ce503202d918a37d8a537fbd2a785e3850f836/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-04-01/managedClusters.json#L2727-L2731). Users can choose the way they like to input.

**Comment by msyyc** [comment]
Here is my sample file: https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/containerservice/manage_agent_pool.py. After running it, `Autoscaling` is still `enabled`:
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/2bdf37db-6494-4bbc-a164-46c5c950df33)

So I guess maybe customer change it configuration in other way with negligence?

**Comment by msyyc** [comment]
1. It is by design
2. `Again, while running the model approach with camel case (see 1 above - the wrong way) this time`
-> 
![image](https://github.com/Azure/azure-sdk-for-python/assets/70930885/9f669532-378c-44ed-ad37-7269e0ab759c)
I want to emphasize again about the right way to use model. And here is the sample: https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/containerservice/manage_agent_pool.py

**Comment by xuexu6666** [comment]
Hi, for this issue, AKS has an internal meeting and decided to change the current agent pool update behavior for cluster autoscaler setting. If users do not provide any cluster autoscaler related setting, AKS resource provider would keep the old cluster autoscaler setting instead of disable it. This PR will go with July 16, 2023 release. So, please allow 2-3 weeks for the code to release to global.
