### ISSUE TITLE
Unable to fetch billing details from CSP Azure accounts

### ISSUE THREAD

**Issue by indumathyn** [Azure/azure-sdk-for-python#3060]
Am using Following api call to fetch billing,
commerce_client  = UsageManagementClient(credentials, subscription_id)
usage_list = commerce_client.usage_aggregates.list(start, end)
rate = commerce_client.rate_card.get(
    "OfferDurableId eq 'MS-AZR-0062P' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'"
)		
usage_list = commerce_client.usage_aggregates.list(start, end)

will be working fine for EA account,but operation return an invalid status code exception thrown for CSP Account.

**Comment by lmazuel** [comment]
Not every type of account can access to billing, tagging team for answer. Thanks.

**Comment by ewongbb** [comment]
Hi, I believe I have a similar issue here.  When I do a rate=commerce_client.rate_card.get(
"OfferDurableId eq 'MS-AZR-0062P' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'")
I get an "Unknown Error" from the rate = line.

I took a gander at [1] https://docs.microsoft.com/en-us/previous-versions/azure/reference/mt219004%28v=azure.100%29#response

and then looked at the response object as returned in  
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-commerce/azure/mgmt/commerce/operations/rate_card_operations.py#L91

looking at the response.request object, it shows the "Authorization" header having
been set.  From [1], this isn't supposed to be set.  

Am I correct?

**Comment by ewongbb** [comment]
On second thoughts, I think I misunderstood it.  I now that the response code is 302 and
that's a Redirect, which means I need to follow that redirect to the new target.

**Comment by ewongbb** [comment]
an addendum:
I followed the code to msrest's  service_client.py and noticed that (in theory and aiui),  with the following code:

response = session.request(request.method, request.url, data=request.data, headers=request.headers, **kwargs)

the response.status_code is 302, so it's a redirect.  Looking at the response.headers, there's no "location" key, so there's no way of finding where the redirection goes to.

So since in line https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-commerce/azure/mgmt/commerce/operations/rate_card_operations.py#L93

it compares with just [200],   Since I'm not familiar with the code, I doubt adding 302 to that
list will help.

any help appreciated.

**Comment by lmazuel** [comment]
Redirect should be done automatically for you, this might indeed be a RestAPI issue. @johanste ?

**Comment by ewongbb** [comment]
I finally figured out my issue.  It's basically because I didn't have the Billing API access required.  Once the accounts manager gave me access (can't remember which api management permission), I can get the information needed.   That said, I'm not sure why I get a 302, when I should actually get an authorization error.

**Comment by johanste** [comment]
There is a limit on the size of responses for Azure control plane/management operations. I believe the current limit is 8Mb, but that is subject to change. Any service that may return larger responses typically redirects to a separate storage location (which includes a sas token or similar for authentication). 

I suspect that what happened is that the location header was not included since @ewongbb did not have the right permissions. Technically, [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.4.3) only says that a Location header SHOULD be included for a 302 response, but I do agree that a authorization error would be preferable here.
