### ISSUE TITLE
[azure-mgmt-web] checked needed about web_apps.list_metadata_slot method(reopen)

### ISSUE THREAD

**Issue by ImMin5** [Azure/azure-sdk-for-python#30745]
- **Package Name**: azure-mgmt-web
- **Package Version**: 7.0.0
- **Operating System**: Mac OS 
- **Python Version**: 3.8

**Describe the bug**
This issue re-opened issue because of my question
![image](https://github.com/Azure/azure-sdk-for-python/assets/38625842/7e1869e4-5f05-43b8-9854-6f93522f6325)

* #28329 

I created `Function App` Service at Azure Portal.
and then i tried to connect all git repository like github, bitbucket, local, and external.

I expected to get results from all options that I can connect.
but if i connect local git repository, I couldn't get any useful result.

**To Reproduce**
1.  Create Function App with at least `Premium V2`.
2. Create Deployment Slot.
3. Create Deployment Center at your Deployment slot.
4. Request via python sdk.
```
azure_client = WebSiteManagementClient(...)
...
azure_client.web_apps.list_metadata_slot(resource_group_name=resource_group_name, name=name, slot=slot)
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/38625842/212249492-8252f2eb-5e90-49a8-a4df-a75c06dea006.png)

**Additional context**

**Comment by kashifkhan** [comment]
Thank you for the feedback @ImMin5 . We will investigate and get back to you asap.

**Comment by ImMin5** [comment]
Hello, Is there any change?

**Comment by SaurabhSharma-MSFT** [comment]
@ImMin5 Sorry for the delay on this one.  I have tried this with local Git only and able to get the properties.  If you are still having issues please can you create an [Azure Support Ticket](https://aka.ms/azsupt) so that an engineer could work with you to identify the root cause of this issue. In case you have limitations in your support plan to open support ticket please let me know.
