### ISSUE TITLE
Async Eventhub Consumer : Link Detached after some time

### ISSUE THREAD

**Issue by sebrouss** [Azure/azure-sdk-for-python#30931]
- **Package Name**: azure-eventhub
- **Package Version**:  5.11.2
- **Operating System**:  Kubernetes pod based on python:3.11-slim
- **Python Version**: 3.11

**Describe the bug**
After some time, some of our pods are unable to successfully consume new data from our event hubs.
Resulting in this error :
[ERROR] Unable to attach new link: ValueError('Invalid link')

Our consumers are never able to resume consumption even after the pod are restarted.
Deleting the underlying containers where checkpoints are stored allows to fix the issue, but we also lose track of the consumer group offset in the process ... and end up in reprocessing everything from the start.

After setting log-level to DEBUG for our application, we have been able to correlate these "User Errors" with some errors in socket management in the _pyamqp module of the azure-eventhub package (see more details below).

Our consumer's log volume (when set at DEBUG) show errors within the link being detached.
here are a few samples (full log will be provided in attachement)

23-06-2023 11:31:12 [INFO] An error occurred when detaching the link: AMQPConnectionError('Error condition: ErrorCondition.InternalError\n Error Description: Link already closed.')
..
23-06-2023 11:31:12 [INFO] Link state changed: <LinkState.DETACHED: 0> -> <LinkState.ATTACH_SENT: 1>
23-06-2023 11:31:13 [DEBUG] <- AttachFrame(name=b'aed5b88e-4544-41ec-85f3-e9675c99be00', handle=2, role=False, send_settle_mode=None, rcv_settle_mode=None, source=None, target=None, unsettled=None, incomplete_unsettled=None, initial_delivery_count=None, max_message_size=None, offered_capabilities=None, desired_capabilities=None, properties=None)
23-06-2023 11:31:13 [INFO] Cannot get source or target. Detaching link
23-06-2023 11:31:13 [INFO] Link state changed: <LinkState.ATTACH_SENT: 1> -> <LinkState.DETACHED: 0>
23-06-2023 11:31:13 [ERROR] Unable to attach new link: ValueError('Invalid link')

**To Reproduce**
None to provide at the moment 

**Expected behavior**
- Stability and No "User Errors" between the client and the checkpoint store.
- Possibility to restart/reset connections after a pod restart (still a workaround but better than loosing the offset).
- Also, less important but surprising behavior in _pyamqp module: many errors in this library are called out in log.info calls (not log.error?), so not readily apparent with our typical logging setups 

**Screenshots**
Many user errors are reported in the metrics dashboard
![image](https://github.com/Azure/azure-sdk-for-python/assets/40765072/924203a1-7824-4871-b37a-05962987ef33)

**Additional context**

**Comment by tjprescott** [comment]
Thanks @sebrouss for the issue. @kashifkhan can you, @l0lawrence or @swathipil take a look at this?

**Comment by kashifkhan** [comment]
Thank you for the detailed issue @sebrouss. Can you provide some details about the setup of your Event Hubs such as partition count, message size being sent, number of messages so that we can try to repro. 

For this particular error `[INFO] An error occurred when detaching the link: AMQPConnectionError('Error condition: ErrorCondition.InternalError\n Error Description: Link already closed.')` I am working on a PR to fix this issue, so hopefully they will clear up in our next release cycle. 

Without seeing the full DEBUG log, this line caught my eye as the service itself is sending back an ATTACH without a source or a target. Are there any issues popping up over on the event hubs side that yall can see?

<- AttachFrame(name=b'aed5b88e-4544-41ec-85f3-e9675c99be00', handle=2, role=False, send_settle_mode=None, rcv_settle_mode=None, **source=None, target=None**, unsettled=None, incomplete_unsettled=None, initial_delivery_count=None, max_message_size=None, offered_capabilities=None, desired_capabilities=None, properties=None)

**Comment by sebrouss** [comment]
Hi @kashifkhan ,

we have 4 partitions.
I can share some messages if you want, and also the full log that includes debug traces (can I share them by email ?).

Here is a screenshot showing the metrics you requested (if you want different ones, please tell me which ones you would like):

![image](https://github.com/Azure/azure-sdk-for-python/assets/40765072/498423bd-af52-45af-9f59-661810a3ec83)

To answer your question, I did not see more errors in our client. Should I look somewhere else ?

**Comment by sebrouss** [comment]
Also a few 404 on the blob storage side :
![image](https://github.com/Azure/azure-sdk-for-python/assets/40765072/a4ce3458-dea7-40e0-8b8d-474c313fbdbe)

**Comment by kashifkhan** [comment]
Hi @sebrouss, 

yes you can send me the detailed logs at my email - my github username @ my employer :)

I would also like to know if during this process the event hub that the client is pointing to gets recreated / moved or something else on the infrastructure happens. Reason being is that empty attach I see in the partial logs, that usually happens when the client sends in a request to an Event Hub that is no longer there or using the wrong url ( the blob not being found either is causing me to think this )

**Comment by kashifkhan** [comment]
@sebrouss thanks for sending over the logs. Will be taking a look at them

**Comment by kashifkhan** [comment]
Hi @sebrouss, after taking a look at the logs I'm seeing the following pattern show up

* The client library gets an offset from the checkpoint ->  `25789595200`
* Using that checkpoint as an offset it tries to connect to the Event Hub (the attach frame with `amqp.annotation.x-opt-offset > '25789595200'`)
* The service replies back with an error `"The supplied offset '25789595200' is invalid. The last offset in the system is '-1'`

This is looking like a mismatch between the Event Hub and the check point store. Is somewhere in your process a brand new Event Hub being created with the same name? 

If that is the case the recommended way would be to configure a new storage container or delete the existing blobs from the container.

**Comment by sebrouss** [comment]
Hi @kashifkhan ,

All our event hubs are being created through terraform scripts.

If I look at the history of this issue : we can see when it occured
![image](https://github.com/Azure/azure-sdk-for-python/assets/40765072/1d2e7827-bfcd-4bb8-8d59-2d0f55908153)

If I focus on the 22nd of June, when this error started to pop up again : it started at 4:30pm
![image](https://github.com/Azure/azure-sdk-for-python/assets/40765072/50375135-d77e-4fd5-af35-483a2a281c41)

If I look at the git history of the event hub tf config file:
![image](https://github.com/Azure/azure-sdk-for-python/assets/40765072/48a4d5da-ccc9-441b-9c99-c3ed65b56198)

There is indeed an update made right before the problem reappeared ...
I checked with the team responsible for the tf and underlying pipeline. They will confirm that, but there is good chance that when an update is made on the file, all event hubs are being recreated (even for the ones that did not get any update).

So I guess your explanation is correct.

thanks a lot for your help !

**Comment by kashifkhan** [comment]
Glad to hear we are getting closer to the root case @sebrouss . Hopefully the resolution is quick for yall :)

**Comment by sebrouss** [comment]
root cause identified
