### ISSUE TITLE
Minor Rendering issue

### ISSUE THREAD

**Issue by CalvoM** [Azure/azure-sdk-for-python#30986]
The code snippet formatting/rendering does not work correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5203416-1c3b-d4db-d770-ac6567526595
* Version Independent ID: 33aa78ff-963d-5a8b-235b-92ad19677115
* Content: [azure.mgmt.compute.v2022_08_01.models.UefiSettings class](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.models.uefisettings?view=azure-python)
* Content Source: [docs-ref-autogen/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.models.UefiSettings.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.models.UefiSettings.yml)
* Service: **virtual-machines**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by swathipil** [comment]
Hi @CalvoM - thanks for opening an issue! Tagging people who can take a look.

In the meantime, would you be able to provide the following information?
- More details on the bug. i.e. What do you see "not working correctly" vs. what is the expected behavior?
- Steps to reproduce this issue and any additional context/screenshots.

**Comment by msyyc** [comment]
I think it is related with wrong swagger definition in old api version [stable/2022-08-01/computeRPCommon.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-08-01/computeRPCommon.json#L1080-L1087). And it has been fixed in [stable/2023-03-01/computeRPCommon.json](https://github.com/Azure/azure-rest-api-specs/blob/26cac4f70e9ce0e1c2f77de8303b47d1faa9ad33/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-03-01/computeRPCommon.json#L1079-L1090). So could you make a PR to fix it in swagger? @CalvoM 
After swagger fixed, we can release a new SDK version to fix the issue in doc.

**Comment by navba-MSFT** [comment]
@CalvoM Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by CalvoM** [comment]
Oh, just noticed this email today. @msyyc I had not seen your comment. Thank you for update.
