### ISSUE TITLE
azure-keyvault-secrets 4.7.0 throws 401 then 200 with managed identity and one call get_secret()

### ISSUE THREAD

**Issue by SvenSowa** [Azure/azure-sdk-for-python#31228]
- **Package Name**: 
azure-keyvault-secrets
- **Package Version**: 
4.7.0 
- **Operating System**:
Linux (Azure Function Linux-5.10.102.2-microsoft-standard-x86_64-with-glibc2.31)
- **Python Version**: 
3.10.11

**Describe the bug**
Azure Function App with a managed identity enabled throws a 401 and then 200, even though the SecretClient() gets initialized with ManagedIdentityCredential() and get_secret() is only called once.

**To Reproduce**
1. create a Python Function App in Azure
2. assign an identity
3. create a keyvault "name-of-your-keyvault"
4. add the identity to the keyvault policy with List/Get secrets
5. create a secret "name-your-secret"
6. your python requirements.txt should contain 
azure-identity==1.13.0
azure-keyvault-secrets==4.7.0
8. your python code can look like this, in my case it was part of an event hub trigger function
```
from azure.identity import ManagedIdentityCredential
from azure.keyvault.secrets import SecretClient
mi_credential = ManagedIdentityCredential()
KV_NAME = 'name-of-your-keyvault'
kv_uri = f"https://{KV_NAME}.vault.azure.net"
kv_client = SecretClient(vault_url=kv_uri, credential=mi_credential)
wif_kv_value = kv_client.get_secret("name-your-secret").value
```
9. Goto Functions, select your function, Monitor, Invocations, open the log
10. Look for the detailed calls to your keyvault, similar to this "https://name-of-your-keyvault.vault.azure.net/secrets/name-your-secret/"
11. Note a "Response status: 401"
12. after that a call to "http://localhost:8081/msi/token"
13. AppServiceCredential.get_token succeeded
14. ManagedIdentityCredential.get_token succeeded
15. then a "Response status: 200"

**Expected behavior**
The SecretClient and/or call to get_secret() should get the token from the Azure Function Managed Service Identity endpoint ("http://localhost:8081/msi/token") and then call they keyvault api.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/16253984/88ca62f8-eea7-4ead-b51e-ffe745f747a2)

**Additional context**
Nothing to add right now.

**Comment by mccoyp** [comment]
Hi @SvenSowa, thank you for opening an issue! This behavior is expected, though I realize it can be surprising to see. We've had similar issues opened in the past -- for example: https://github.com/Azure/azure-sdk-for-python/issues/23252.

To re-share what I commented on the issue linked above:
> Seeing a 401 response on your first service request is expected because Key Vault uses challenge-based authentication. For example, our test recordings will show a [401 Unauthorized response](https://github.com/Azure/azure-sdk-for-python/blob/a7e3bf4ece801e49f3cfcf7e098881326a731158/sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_crud_operations_7_2.yaml#L19), which includes [auth challenge details](https://github.com/Azure/azure-sdk-for-python/blob/a7e3bf4ece801e49f3cfcf7e098881326a731158/sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_crud_operations_7_2.yaml#L38), at the start of each test.
> When we don't have a cached challenge for a request URL, the first service request won't include an access token. This prompts the Unauthorized error, from which we can fetch details to get a token and authorize future requests. The exception isn't raised by the SDK because we expect this interaction and silently handle the error.

We also have a Key Vault troubleshooting guide that [mentions this scenario](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/keyvault/TROUBLESHOOTING.md#http-401-errors). That said, I think we could better document this behavior so users know to anticipate it rather than react to it. I opened an issue, https://github.com/Azure/azure-sdk-for-python/issues/31233, to track this work.

I'll mark this issue as resolved, but I'd be happy to hear any feedback you have about documentation that could have helped here, @SvenSowa.
