### ISSUE TITLE
Ability to override `prefered_temporality` in the constructor of `AzureMonitorMetricExporter`

### ISSUE THREAD

**Issue by fswane** [Azure/azure-sdk-for-python#31290]
**Feature description**

When an `AzureMonitorMetricExporter` is instantiated, there is no clear way via the public API to provide a non-default `preferred_temporality`.  It would be convenient to be able to override `APPLICATION_INSIGHTS_METRIC_TEMPORALITIES` via
constructor arguments of `AzureMonitorMetricExporter`

https://github.com/Azure/azure-sdk-for-python/blob/6f79e8e724499cb49d2d727765ff80e3078c823b/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py#L63

**Describe the solution you'd like**
Provide a constructor argument for the `AzureMonitorMetricExporter` to be able to provide a `preferred_temporality`.

**Describe alternatives you've considered**
As a work around I am setting the prefered_temporality on an already-created exporter:

```
exporter = AzureMonitorMetricExporter(connection_string)
exporter._preferred_temporality[Counter] = AggregationTemporality.CUMULATIVE
```
This does work but not via a public API.

**Additional context**
For my application I need to set the temporality of my counters to be `CUMULATIVE` as opposed to the default of `DELTA`.

**Comment by lzchen** [comment]
@fswane 

We set metric temporalities to a [default](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/metrics/_exporter.py#L46) because Application insights backend expects temporalities coming from these instruments to be that specific temporality for the metrics explorer view (the graphs that you see when you observe metric values over time). The reason we do not allow configuration of this is because changing the temporality on the exporter side will aggregate the data with a different temporality but will not change the behavior of the backend, which in turn would make your metric views not make sense (and not truly reflective of what you are measuring).

**Comment by fswane** [comment]
Ok, thanks for the response.

**Comment by lzchen** [comment]
Closing this issue.
