### ISSUE TITLE
Unable to Instantiate Class Implementing AsyncTokenCredential

### ISSUE THREAD

**Issue by williamdphillips** [Azure/azure-sdk-for-python#31573]
- **Package Name**: azure-core
- **Package Version**: 1.29.1
- **Operating System**: Linux
- **Python Version**: 3.8

**Describe the bug**
After the release of 1.29.1, some of our libraries started failing due to inability to instantiate an instance of our custom class which inherits from AsyncTokenCredential. I've narrowed the problem to this commit: https://github.com/Azure/azure-sdk-for-python/commit/8685103afb5d1dab81614a9c6c840179cafe554c

The error message is:
`TypeError: Can't instantiate abstract class DeviceCodeFlowMsalAsync with abstract method __aexit__`

**To Reproduce**
1. Create a subclass that inherits from AsyncTokenCredential and implement method get_token.
2. Attempt to instantiate class

**Expected behavior**
Class should be instantiated and object created with no error

**Comment by williamdphillips** [comment]
Hi @xiangyan99 I see you have the change ready. Thanks for looking into this. Would changes typically take some time to be pushed into a new release or would it be able to be pushed today?

**Comment by xiangyan99** [comment]
Thanks for reporting the issue. We will make a new release asap.

**Comment by lmazuel** [comment]
@williamdphillips I would expect to be able to release a fix Monday. In the meantime, you can use the previous azure-core, or implement an empty aexit in your code.
To be honest, we never intended to provide an empty default implementation of aexit ion the first place, and it's why we didn't caught it. But since we shipped it like that in the past, we will bring it back, no worries.

**Comment by xiangyan99** [comment]
azure-core 1.29.2 is released.

Please try the new version and let us know if it does not work.

**Comment by williamdphillips** [comment]
This is working now, thank you!
