### ISSUE TITLE
Service Bus Management API does not report Schedule Message Count

### ISSUE THREAD

**Issue by hexadite-grishak** [Azure/azure-sdk-for-python#3158]
Hi team,

We’re using the Python Azure Management SDK to monitor our production service buses. 
We have a scheduler job which creates a `SubscriptionsOperations` object (`azure.mgmt.servicebus.operations.subscriptions_operations.SubscriptionsOperations`) and we call its `list_by_topic` method to get a list of objects describing each subscription on that particular topic.
For each subscription returned we get a `count_details` object (`azure.servicemanagement.models.CountDetails`) which is just a wrapper for the counters we’re looking for: 
```python
class CountDetails(WindowsAzureData):

    def __init__(self):
        self.active_message_count = 0
        self.dead_letter_message_count = 0
        self.scheduled_message_count = 0
        self.transfer_message_count = 0
        self.transfer_dead_letter_message_count = 0
```

When we examine the `active_message_count` and `dead_letter_message_count` attributes we get reasonable values. 
However, when we examine the `scheduled_message_count` attribute we always get a 0 (zero) value. 
I know for sure that we use message scheduling. I also performed an off-line test on a service-bus that we use for development. I scheduled a message to be delivered in 2 minutes. All calls to the above APIs return zero for `scheduled_message_count` and after 2 minutes the message was delivered as expected.

Any ideas?

Thanks.

**Comment by lmazuel** [comment]
Hi @hexadite-grishak 
First, you're mixing-up two packages that does not relate to each:
- azure-mgmt-servicebus (`azure.mgmt.servicebus.operations.subscriptions_operations.SubscriptionsOperations`) which is calling the ARM endpoint
- azure-servicemanagement-legacy: (`azure.servicemanagement.models.CountDetails`) which is calling the legacy deprecated endpoint called ASM (or RDFE)

Assuming you're talking about the first one (the recommended one), list_by_topic will return a [SBSubscription object](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicebus/azure.mgmt.servicebus.models.sbsubscription?view=azure-python), which contains a count_details typed [MessageCountDetails](https://docs.microsoft.com/en-us/python/api/azure-mgmt-servicebus/azure.mgmt.servicebus.models.messagecountdetails?view=azure-python). MessageCountDetails and CoundDetails (the one you mention) have the same fields, but not belong to the same SDK or even endpoint. Not the point of your question, but I though it was important to mention this still, because if you try to debug something using `CountDetails` and calling `list_by_topic`, that won't work.

Could you check the content of "additional_properties"?In other word, assuming you have a variable "my_count_details", do a:
```python
from pprint import pprint
pprint(my_count_details.additional_properties)
```
It should be empty, if not please show us what you get.

Adding @v-Ajnava for idea on this, from SB team.

**Comment by hexadite-grishak** [comment]
Hi and thanks for replying!
Your first comment is absolutely correct, I did mix up the 2 libraries (must've been a mix-up in my PyCharm config). The object attributed as `count_details` is indeed of type `azure.mgmt.servicebus.models.message_count_details.MessageCountDetails`, thanks for noticing.
When I check its `additional_properties` attribute, I get an empty dict in return. 
Here's some code to make the picture clearer (there is a little-bit of proprietary code but it is just a wrapper for the original library):
```python
>>> subscriptions = get_sb_subscriptions(service_client, AZURE_RESOURCE_GROUP_NAME, sb_config.namespace, AIRS_INTERNAL_TOPIC)
>>> s0 = subscriptions[0]
>>> s0
<azure.mgmt.servicebus.models.sb_subscription.SBSubscription object at 0x7fdfb0f759d0>
>>> s0.count_details
<azure.mgmt.servicebus.models.message_count_details.MessageCountDetails object at 0x7fdfb15f0050>
>>> s.additional_properties
{u'location': *****}
>>> s0.count_details.additional_properties
{}
```

Thanks!

**Comment by v-Ajnava** [comment]
got it, will look into it and update accordingly.

**Comment by jfggdl** [comment]
Assigned to v-Ajnava.

**Comment by jfggdl** [comment]
@axisc, Would you please comment on the feasibility or not of this feature. You may want to consult v-ajnava, if needed.

**Comment by axisc** [comment]
@hexadite-grishak  there is a slight difference in the semantics.

The send happens on a topic, and in case of regular sends, the messages are immediately sent to the subscription. 

Scheduled messages live on the topic, and as soon as they are made live, they are also sent to the subscription. 

Admittedly, the scheduled messages count field should be removed from the subscription count details because they are specific to the topic.

closing it for now, but feel free to reopen for any follow up questions.
