### ISSUE TITLE
Create container contains illegal character

### ISSUE THREAD

**Issue by ValTay80** [Azure/azure-sdk-for-python#31639]
- **Package Name**:  azure-cosmos
- **Package Version**: 4.4.0
- **Operating System**: Windows 10 enterprise
- **Python Version**: python 3 in databricks

**Describe the bug**
I used the used the container_management.py in the samples area to created my containers.  I have run the code but the container name inadvertently had a tab character at the end of the name.  

The container exists within the database, but I am unable to delete it manually or with the delete container script.  The script generates this error -CosmosHttpResponseError: Status code: 400

**To Reproduce**
1.  Copy all the code from https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/container_management.py into new notebook and where the container_id is set add a tab to the end of the name.  The container should create as expected.
2. using the same notebook, using the delete_container function try to delete the container with the tab.

**Expected behavior**
I would have hoped that any illegal characters would have failed the create container function.

**Screenshots**
The below is the container in cosmos as you can see it looks like there are 2 container with the same name. At the bottom the container cant be read due to the qla_pupil_results_maths1_2023-2\t container havinig a tab char at the end.
![image](https://github.com/Azure/azure-sdk-for-python/assets/142247214/17ef78e4-9901-4b17-8cd9-4cc81edc25b7)

**Additional context**
Is there any way to delete this container?

**Comment by simorenoh** [comment]
Hi @ValTay80, thank you for opening this issue and using our SDK. Unfortunately, it seems like you've found a gap for our SDK in which we do not check for tab characters on the client side when creating the container - which then causes an issue since the service cannot read resource id's with tab characters.

To delete the container, in this case you will have to use the rids that are unique to the database and container respectively, and use those in conjunction as opposed to their ids. Your code will look something like this:
![image](https://github.com/Azure/azure-sdk-for-python/assets/30335873/5845287f-d93e-4c48-81a2-bdf4dd8897b5)


I will be pushing a PR to address this gap and other gaps we may have with our resource validation. Truly sorry that you ran into this - do let me know if the solution does not work for some reason.

**Comment by simorenoh** [comment]
Closing since PR is out. Should be available in the next release we have. Thanks again for pointing this out @ValTay80.
