### ISSUE TITLE
Ability to deploy a Bicep file without having to transpile  it to ARM/.json first.

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/azure-sdk-for-python#31806]
Is there any way in Python to deploy a Bicep template without having to convert it to a ARM template first?
The API only supports ARM templates and not .bicep templates.
Is this on the backlog to support .bicep templates as a first class citizen in the future?

thanks

**Comment by kristapratico** [comment]
@AaronSaikovski can you share which API you are describing? Please provide more details like which client library you are using, the version, and example code so we can help.

**Comment by AaronSaikovski** [comment]
Sure thing...


```python

from azure.identity import AzureCliCredential
from azure.mgmt.resource.resources.models import DeploymentMode

return self.resource_client.deployments.begin_create_or_update(
            self.resource_group_name, deployment_name, 
            {"properties": deployment_params} 

```


client.deployments.begin_create_or_update - This API call only seems to allow for ARM templates only and not being able to pass Bicep files directly into it. They need to be build into .json files first then it works
Is this on the backlog?

**Comment by ChenxiJiang333** [comment]
Hi, @AaronSaikovski. For actual information, please call the service team https://github.com/Azure/azure-rest-api-specs/issues.

Yet I guess Bicep files cannot be directly read by the service, it has to be converted to ARM through Bicep cli at first.
As in [azure cli](https://github.com/polatengin/azure-cli/blob/main/src/azure-cli/azure/cli/command_modules/resource/_bicep.py#L310), the Bicep cli commands was included in the code to convert bicep files before deployment:
`process = subprocess.run(["bicep", "--build"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

Since python sdk is generated from swagger and it's just a tool to call the api, I don't whether there would be the possibility to add such a feature. For now, maybe you could try to install [Bicep cli](https://learn.microsoft.com/zh-cn/azure/azure-resource-manager/bicep/install#windows) and add its commands in your code like that way.

**Comment by sardobi** [comment]
+1 on this feature request. Would make it a lot easier to write Python code which deploys Azure resources - it's a much nicer to work with Bicep than ARM templates.

**Comment by LiliDeng** [comment]
+1

**Comment by msyyc** [comment]
create an issue for arm team: https://github.com/Azure/azure-rest-api-specs/issues/36510
