### ISSUE TITLE
Difference in output json structure of azure form recognizer for python sdk and rest api call

### ISSUE THREAD

**Issue by netrasagarmal** [Azure/azure-sdk-for-python#32103]
**Is your feature request related to a problem? Please describe.**
I am using the Azure Form Recognizer endpoint in two ways:
1. With the Python SDK.
2. With a REST API call.

I am facing a challenge in reading the JSON output response returned by both the Python SDK and the REST API. The JSON key names and the JSON structure are different, so I need to write different JSON parsing logic for both cases. I have attached a screenshot for reference below.

<img width="1629" alt="Screenshot 2023-09-08 at 12 57 25 PM copy" src="https://github.com/Azure/azure-sdk-for-python/assets/55647831/3f715da6-c55f-408f-9ff4-698659a8494f">

**Describe the solution you'd like**
I'm expecting same json structure and same key names in both the output responses so that we dont need to write different parsing logics for different methods.

**Comment by pvaneck** [comment]
Hey, thanks for the feedback. Looks like you've noticed a discrepancy in the field naming conventions between the JSON response from the REST API (camel case) and the response from the Python SDK (snake case).

The use of snake case in the Python SDK is intentional and aligns with Python's PEP8 naming conventions for variables and functions, keeping things idiomatic and familiar to Python developers.

It's not typical that a user is trying to use both the REST API and Python SDK concurrently, but in your case, additional parsing logic would be needed. Don't think this can be avoided.

**Comment by catalinaperalta** [comment]
Thanks for reaching out @netrasagarmal! As @pvaneck mentioned, this is by design for the SDK. However, if you are attempting to access the raw response from the method, you can use the `raw_response_hook` to access it. Here is an example: 

```
    def callback(raw_response):
        print("Process raw response here...")
 
    with open(path_to_sample_documents, "rb") as f:
        poller = document_analysis_client.begin_analyze_document(
            "prebuilt-document", document=f, raw_response_hook=callback
        )

```
