### ISSUE TITLE
Service Limit inconsistency / Sample workbook change

### ISSUE THREAD

**Issue by wiperpaul** [Azure/azure-sdk-for-python#32282]
- **Package Name**: 
azure-monitor-query  aio
- **Package Version**: 
- 1.2.0
- **Operating System**:
- Windows 11
- **Python Version**: 
3.10

**Describe the bug**
https://github.com/Azure/azure-sdk-for-python/blob/dfbaf61313fbe5acb5255c1a03a7aeaf307591c4/sdk/monitor/azure-monitor-query/samples/notebooks/sample_large_query.ipynb

Firstly thank you @pvaneck for this workbook it was immensely helpful, prior to this I also had an implementation of paging + async and was struggling with limitations of the service. I was instead extending a new row within my query called pagenumber and then iterating the page number to make a list of queries to grab large datasets. Your method using estimate data size is great.

However, I wanted to point out that here in the Azure Monitor Service Limits page it says 100MiB
https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits#log-analytics-workspaces

You also use this in your workbook in the max byte size for queries however I have found in practice I run into this error:

`{'code': 'EngineError', 'message': 'Something went wrong processing your query on the server.', 'innererror': {'code': '-2133196797', 'message': 'The results of this query exceed the set limit of 64000000 bytes, so not all records were returned (E_QUERY_RESULT_SET_TOO_LARGE, 0x80DA0003)`

It links to this page which shows the limit as 64MiB
https://learn.microsoft.com/en-us/azure/data-explorer/kusto/concepts/querylimits#limit-on-result-set-size-result-truncation

Edit - I should add I am running against a dedicated private LA cluster

**To Reproduce**
1. Use the workbook to call a table that will hit the data size limit before row limit

p.s. queries with fields that vary a lot in size such as those with a raw column are the reason I ran into this. I wonder if a max could be used on the largest row within the queryresult. Either that or I have to use the maximum row size for log analytics and divide by 64MB right ?

**Comment by xiangyan99** [comment]
Thank you for the feedback.

We will investigate ASAP.

**Comment by pvaneck** [comment]
Hey, @wiperpaul. Glad the notebook has been helpful. Admittingly, the Azure Monitor service limits aren't something I'm absolutely clear on. According to the Azure Monitor docs, The ~100MiB limit is for raw data assuming the compressed size is <= 64MB. When I wrote this notebook, it was unclear to me if this compression was happening, so it very well may just be 64MB as the limit in practice. I believe that's why I added the `MAX_BYTES_PER_QUERY = int(MAX_BYTES_PER_QUERY_SERVICE_LIMIT * 0.6)` line to bring the default value under this.  I think for consistency, I can update the notebook to state 64MB as the limit since essentially that's what we're going with.

This is something I can try and get clarity from the Azure Monitor service team on.

**Comment by pvaneck** [comment]
Apologies for getting back to this so late. But I made some adjustments a while back to the notebook (https://github.com/Azure/azure-sdk-for-python/pull/32334) which does a bit to emphasize the 64MB limit. It's best to assume 64MB is the upper bound and do calculations based on that (which the notebook does).
