### ISSUE TITLE
`azure-mgmt-web` TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ava-silver** [Azure/azure-sdk-for-python#32993]
- **Package Name**: 
`azure-mgmt-web`
- **Package Version**: 
azure-mgmt-web==7.1.0
- **Operating System**:
Linux/Ubuntu 20.04
- **Python Version**: 
Python 3.10

**Describe the bug**

Occasionally, when making calls from client.web_apps.list_continuous_web_jobs(), we get the an error with the following traceback when iterating through the results:
```
  File "/usr/local/lib/python3.10/site-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.10/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/web/v2022_09_01/operations/_web_apps_operations.py", line 22317, in extract_data
    return deserialized.next_link or None, iter(list_of_elem)
TypeError: 'NoneType' object is not iterable
```

**To Reproduce**
This behavior is difficult to reproduce directly, as it is likely due to inconsistencies in the API response.

**Expected behavior**
We expect the client to not error with an error like this, either by returning an empty result or explicitly erroring with a helpful error message, whichever would be more appropriate.

**Additional context**
Although I'm not sure exactly how this comes up/the root cause, it seems like it should be fairly simple to mitigate regardless of how it comes up.

**Comment by kristapratico** [comment]
@ava-silver thanks for your issue, we'll investigate and get back to you as soon as possible.

**Comment by msyyc** [comment]
Hi @ava-silver, according to trace back, I think the reason is inconsistency between service behavior and API definition. More specifically, service shall aways return [value](https://github.com/Azure/azure-rest-api-specs/blob/42e2c0bcd77b0de6c523404668fa63511484d485/specification/web/resource-manager/Microsoft.Web/stable/2022-09-01/WebApps.json#L24708-L24714) as `[]` instead of `null`. Before transfer this issue to service team, could you follow https://github.com/Azure/azure-sdk-for-python/wiki/Common-issues-about-Python-SDK#debug-guide to get more detailed log which may help service team find the root cause quickly?

**Comment by ava-silver** [comment]
Hi @msyyc, Unfortunately because we make requests on behalf of customers who I cannot share their information publicly here, so I cannot share the logging details. However, I can say that we specifically see it in `list_continuous_web_jobs` and `list_triggered_web_jobs`, and are not seeing the error elsewhere. Would you be able to either forward this onto your backend team or treat the null value as `[]` in the client?

**Comment by msyyc** [comment]
@ava-silver Got it. Since it is service issue, please open an issue in https://github.com/Azure/azure-rest-api-specs/issues.
