### ISSUE TITLE
InteractiveBrowserCredential returns localhost URL in GitHub Codespaces

### ISSUE THREAD

**Issue by rohit-ganguly** [Azure/azure-sdk-for-python#33021]
- **Package Name**: azure-identity
- **Package Version**: 1.15.0
- **Operating System**: Ubuntu Linux
- **Python Version**: 3.10.0

**Describe the bug**
Creating an InteractiveBrowserCredential in GitHub Codespaces does not work as intended. Another browser tab opens for sign in, and after selecting an account to sign in with, the user is redirected to localhost:8400. The redirect server isn't set up outside of GH Codespaces, giving a 'refused to connect' error. 

**To Reproduce**
1. Create a GitHub Codespace with InteractiveBrowserCredential
2. Run code and attempt to create a credential object

**Expected behavior**
The expected behavior would be being prompted with a new window to sign in, and returning to the GitHub Codespace with your code running.

**Screenshots**

**Additional context**

**Comment by rohit-ganguly** [comment]
cc @scottaddie @pvaneck @xiangyan99

**Comment by pvaneck** [comment]
Thanks for the feedback. This problem is a bit tricky, and the only way I see around it is if we can open a browser within Codespaces.

Even if we were to say the Codespaces URI should be redirected to with something like `redirect_uri="https://legendary-space-tribble-77r6759x99cx9p4.github.dev:8400")`, Entra will complain since the common Entra application we use for this credential doesn't allow such redirect URLs, and I believe it is only configured to redirect to `localhost`.

We should document this behavior, and perhaps just recommend using DeviceCodeCredential within Codespaces.

**Comment by scottaddie** [comment]
@xiangyan99 As discussed in office hours, please open a PR to update docs with the known limitation for the default app. We'll recommend `DeviceCodeCredential` as a workaround.

**Comment by xiangyan99** [comment]
We decided to add the limitation into README doc and reevaluate it if we get more requests from customers.

https://github.com/Azure/azure-sdk-for-python/pull/33190

**Comment by pvaneck** [comment]
Closing, as this limitation is noted in our README via #33190, and I don't believe this is something we can support for.
