### ISSUE TITLE
Blob storage download is slow because it's always chunked

### ISSUE THREAD

**Issue by mathieulongtin** [Azure/azure-sdk-for-python#33194]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.17.0
- **Operating System**: Ubuntu
- **Python Version**: 3.10.12

**Describe the bug**
Downloading large blobs (>1GB) is slow.

It turns out that `BlobClient.download().readall()` always reads in chunks of 4MB, no matter what. This limits download speed to about 100MB/s, since each HTTP requests takes at 20-50ms. Increasing `max_concurrency` makes it faster, but not that much.

By comparison, using a pure `request` session, and asking for the entire content, downloads much faster (my test VM maxes out at 900MB/s, but that's the stated network capacity).

**Expected behavior**
When calling `download()` without specifying `max_concurrency`, don't chunk the request, make one large request.

**Comment by l0lawrence** [comment]
Hi @mathieulongtin thanks for the feedback, we will get back to you asap.

**Comment by jalauzon-msft** [comment]
Hi @mathieulongtin, what you are describing is the default behavior of the SDK but this can be configured. There are two keywords that can be passed during **client construction** that can configure this behavior, `max_single_get_size` and `max_chunk_get_size`. See here (this is `BlobClient` for example but all client constructors should support the same)
https://github.com/Azure/azure-sdk-for-python/blob/58586f7ac14ba1abb5db632d69b77985b92584a3/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L133-L136

As the docs state, `max_single_get_size` will configure the threshold for when the SDK switches to chunking and `max_chunk_get_size` will control the chunk size that is used. You can try playing around with these values, along with `max_concurrency` to see if that can help with performance. Do note though, due to extra processing/etc. the SDK may not reach the same speeds as using `requests` raw like you described but hopefully you can get closer.

Something you may also want to be aware of when you start messing with these above sizes is the client-side network timeouts. If you start to run into network timeouts based in your request sizes, you can also configure the timeouts which are described in the README here (`connection_timeout` and `read_timeout`):
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/README.md#other-client--per-operation-configuration

**Comment by mathieulongtin** [comment]
I stumbled upon those settings, however, coming from either from `ContainerClient.get_blob_client` or the Datalake API, which uses the _blob_client, they are not exposed.

I'm also found out that `DataLakeFileClient._client.path.read()` behaves as expected.

**Comment by jalauzon-msft** [comment]
Hi again @mathieulongtin, while `get_blob_client` does not support these keywords, the constructor for `CotnainerClient` does as well as the constructor for `BlobServiceClient` if you use that. So whatever client you are starting with, you should be able to pass these keywords and they will be copied over when using `get_x_client` methods.
https://github.com/Azure/azure-sdk-for-python/blob/fdaa9cfcd153a6c9b153d75bee37ec8abb2839c5/sdk/storage/azure-storage-blob/azure/storage/blob/_container_client.py#L121-L124

Additionally, while `DataLakeFileClient` does not document the use of these keywords, if you pass the same keywords when constructing a `DataLakeFileClient` or `DataLakeDirectoryClient` they should be passed through to the underlying `BlobClient` and work as intended. This may not work with the `FileSystemClient` constructor though.

We highly discourage the use of `DataLakeFileClient._client.path.read()` directly as that is a private API meant to be used internally. It calls a completely different API (from the dfs endpoint) and ignores any extra logic of the SDK.
