### ISSUE TITLE
create_file fails if file_last_write_time is passed a datatime object

### ISSUE THREAD

**Issue by AdrianJMartin** [Azure/azure-sdk-for-python#33317]
```python
file_client.upload_file( data=data , file_last_write_time=dt )
```

fails with header incorrect format

```
Time:2023-11-28T17:53:36.9725865Z</Message><HeaderName>x-ms-file-last-write-time</HeaderName><HeaderValue>2023-05-22T13:09:540Z</HeaderValue></Error>
```

from observation of other datetime headers, I noticed they had more preccision in the seconds, this works.:

```python
ts = last_write_time.isoformat() + ".0000000Z"
file_client.upload_file( data=data , file_last_write_time=ts)
```

**Comment by pvaneck** [comment]
Thanks for the feedback. I've tagged some people who may be able to help.


Also, is that the full error message? How are you constructing the `datetime` object that's being passed to the `upload_file` method?

**Comment by AdrianJMartin** [comment]
I was using:

```python
datetime.fromtimestamp( int( f.last_write_time )) 
```
where ```f.last_write_time``` was 1684760994.893201, the code above truncates the double and losing the fractional seconds

I have since changed my code to 
```python
datetime.utcfromtimestamp( f.last_write_time)) 
```
which retains the nanosecs

```python

## interactive in debug console

>datetime.fromtimestamp( int( f.last_write_time ) )
datetime.datetime(2023, 5, 22, 13, 9, 54)
>datetime.fromtimestamp( int( f.last_write_time ) ).isoformat()
'2023-05-22T13:09:54'

>datetime.utcfromtimestamp( f.last_write_time )
datetime.datetime(2023, 5, 22, 13, 9, 54, 893201)

>datetime.utcfromtimestamp( f.last_write_time ).isoformat()
'2023-05-22T13:09:54.893201'
```

It seems to me that the module, might be assuming that python will always include the fractional seconds, but if a truncated datetime is used this is not always the case.

**Comment by jalauzon-msft** [comment]
Hi @AdrianJMartin Adrian, thanks for reaching out. This is sort of a known issue with how we serialize datetime objects to send to the service. As you have correctly identified, this issue comes down to fractional seconds. The Storage service expects 7 digits of precision whereas Python maintains only 6. So, we have to manually convert all `Datetime` objects to strings and append the extra digit before sending to the service. 

Currently we have a very naive way of doing this that does not support most datetime objects unfortunately. We simply append an extra `0Z` to the end of `isoformat()`.
https://github.com/Azure/azure-sdk-for-python/blob/34050702e19e1f2e83e01aad24a2d52f716701e7/sdk/storage/azure-storage-file-share/azure/storage/fileshare/_parser.py#L44

We realize this code is severely inadequate (it also falls apart if `tzinfo` is provided) and have a plan to improve this logic which we hope to implement soon and get into an upcoming release.

For now, the workaround of making sure your `datetime` object has all 6 digits of fractional seconds should work. The other option is to give the SDK a raw string that your build yourself, but it would need to include 7 digits of fractional seconds and be in UTC time with the `Z` at the end.
