### ISSUE TITLE
Add block size parameter to start_copy_from_url

### ISSUE THREAD

**Issue by marijncv** [Azure/azure-sdk-for-python#33315]
I'm looking into copying data from archive into hot storage between two storage accounts. The recommended approach seems to be to use `start_copy_from_url`. But it results in a large number of read operations on the archived storage (which are expensive). It seems that the storage service sends a Get Blob requests for each block in the blob. 

In order to control costs, it would be nice to be able to specify the block size that is used by the storage service when copying data from archive into hot between two storage accounts. When copying between two storage accounts in hot tier with azcopy,  the block size is configurable (with the ` --block-size-mb` parameter)

**Comment by jalauzon-msft** [comment]
Hi @marijncv Marijn, unfortunately this is not really possible today due to service limitations. The Copy Blob operation from the service, which is necessary to rehydrate an archive Blob, does not support setting any sort of block size. The service dictates how it is going to read the source blob and does not provide configuration for this. As this is a service limitation, there is not much we can do from the client side on this issue. If you wish you can communicate this ask to the service team via upvoting or creating a new idea at [https://aka.ms/AzStorageFeedback](https://aka.ms/AzStorageFeedback).

I know you mentioned that this is between two Storage accounts but I'll just mention that if the Blobs could somehow be rehydrated to the same account, another thing you can try is using [Set Blob Tier](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-tier) (`BlobClient.set_standard_blob_tier` in the Python SDK) to move your Blobs from Archive to Hot tier. I am not very familiar with the differences in operations/cost associated with this but there is a chance this does not incur the same costs as copying the Blob. There are some stipulations around this method though so please read through the documentation [here](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview#setting-or-changing-a-blobs-tier) and [here](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-tier?tabs=microsoft-entra-id#remarks). Specifically, there could be an early deletion cost with this method I believe. Setting tiers can also be done in batches via [Blob Batch](https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch) (`ContainerClient.set_standard_blob_tier_blobs` in Python SDK).

A Note on `--block-size-mb` in AzCopy: This would not be supported when copying Archive Blobs as AzCopy uses a series of Put Block from URL to copy individual blocks at a time, hence the block size can be configured. Put Block from URL is not supported with Archive Blobs.

Sorry I don't have a more helpful answer for you, but this is purely a service limitation. Perhaps there is a way you can work Set Blob Tier into your workflow that could have a chance to save cost. Thanks.
