### ISSUE TITLE
Add an example of proxy usage

### ISSUE THREAD

**Issue by lostpassword** [Azure/azure-sdk-for-python#33344]
Would be great to add an example of proxy usage here, as it's not working as expected on the ground (at least for me).
https://stackoverflow.com/questions/77571588/how-do-i-specify-the-proxy-configuration-for-cosmosclient-class-object
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 150423cd-8d18-e9ca-48fa-79292157c082
* Version Independent ID: 79f2e12a-efd4-6027-87fc-8e0ab96400f9
* Content: [azure.cosmos.ProxyConfiguration class](https://learn.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.proxyconfiguration?view=azure-python)
* Content Source: [docs-ref-autogen/azure-cosmos/azure.cosmos.ProxyConfiguration.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-cosmos/azure.cosmos.ProxyConfiguration.yml)
* Service: **cosmos-db**
* GitHub Login: @lmazuel
* Microsoft Alias: **lmazuel**

**Comment by bambriz** [comment]
@lostpassword Thank you for bringing this issue up. From that link I can see the sample there is correctly written, the issue is more likely an issue with the configuration of the proxy or network. Alternatively another way to set up the proxy for cosmos db is by the following:
`connection_policy = ConnectionPolicy()
        connection_policy.ProxyConfiguration = ProxyConfiguration()
        connection_policy.ProxyConfiguration.Host = 'http://127.0.0.1'
        connection_policy.ProxyConfiguration.Port = 7777
        client = cosmos_client.CosmosClient(self.host, self.masterKey, consistency_level="Session",
                                            connection_policy=connection_policy)`
But passing in proxy_config does the same thing as this essentially.
