### ISSUE TITLE
begin_analyze_document_from_url / prebuilt-invoice / InvalidContent / Azurite

### ISSUE THREAD

**Issue by Ioannis-Pikoulis** [Azure/azure-sdk-for-python#33376]
I'm trying to debug a python Azure Function App locally. I've activated Azurite and uploaded a pdf file within the storage emulator. When running the app, I'm trying to apply `begin_analyze_document_from_url` using the `DocumentAnalysisClient` class. I get the `InvalidContent` error. I've also tried to use SAS token but no success whatsoever.

**Comment by swathipil** [comment]
Hi @Ioannis-Pikoulis - Thanks for opening an issue. Would you be able to provide the following information as well?

* Package Name
* Package Version
* Python Version
* Steps/Code snippet to reproduce behavior
* Error Stack Trace

**Comment by YalinLi0312** [comment]
Hi @Ioannis-Pikoulis , you don't need to pass SAS token URL when analyzing a doc. 
Additionally, we have an example that you can follow: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_receipts_from_url.py#L45

**Comment by Ioannis-Pikoulis** [comment]
@YalinLi0312 I have followed all given samples and examples: The problem is that when using ```begin_analyze_document_from_url``` on top of a URL that points to storage emulator, the function returns `InvalidContent` error. This basically renders local debugging sessions impossible, when trying to use `DocumentAnaalysisClient`.

**Comment by YalinLi0312** [comment]
@Ioannis-Pikoulis There are several possibilities, it could because the document content is invalid, or something wrong to get the document content.
Did you try with a file stored in local instead from Storage? It could help to figure out where the issue comes from. 

Also, can you provide more details which would help us to investigate?
- Steps/Code snippet to reproduce behavior
- Error Stack Trace
