### ISSUE TITLE
"ValueError: Required Content-Range response header is missing or malformed" when accessing files via Standard Tier Frontdoor CDN

### ISSUE THREAD

**Issue by 11braemm** [Azure/azure-sdk-for-python#33443]
- **Operating System**: Windows 10 Enterprise
- **Python Version**: 3.9.0

**Describe the bug**
Accessing files via my Standard Tier Frontdoor CDN does not seen to work via the python SDK and gives a ValueError: Required Content-Range response header is missing or malformed. However downloading files from the storage account directly works as expected.

**To Reproduce**
1.  Run the following code as written, accessing the storage account directly and it should all work as expected

async def download_blob():
    base_url = "https://aseanonymouscdnbugdemo.blob.core.windows.net/ase-bug-demo/"
    base_url_via_cdn = "https://anonymous-access-a9engahagrb4dudx.z01.azurefd.net/ase-bug-demo/"
    blob_url = f"{base_url}demo-file-0.txt"

    async with BlobClient.from_blob_url(blob_url) as blob_client:
        blob_downloader: StorageStreamDownloader = await blob_client.download_blob(
            encoding="UTF-8"
        )
        contents = await blob_downloader.readall()
        print(contents)

asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
asyncio.run(download_blob())

2. Edit the blob_url line to be as follows blob_url = f"{base_url_via_cdn}demo-file-0.txt" (accessing via the cdn)

You should get the following error
ValueError: Required Content-Range response header is missing or malformed

**Expected behavior**
The download to work via the cdn

**Additional context**
My set up is a publicly accessible cdn and storage container.

I have seen [here](https://github.com/Azure/azure-sdk-for-python/issues/22297#issuecomment-1165031164) there is known issues with a microsoft classic tier cdn prodcuing this exact error however I am using the standard tier cdn so am unsure if this is a known issue and what the workarounds are?

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by jalauzon-msft** [comment]
Hi @11braemm, I did some testing with this today and yes, it does seem like this is the same issue as with the Microsoft Classic CDN tier. To summarize, the CDN relies on the presence of the HTTP Range header to know if a request is for a byte range of the data, which it needs to know, presumably for its caching algorithm. When the CDN does not see this, it actually requests the full data from the Storage service and returns the full data back to the client, meaning there is no `Content-Range` header in the response (and more data than requested may be returned). The issue is the SDK does not use the standard HTTP Range header and instead uses the custom `x-ms-range` header to specify a range download request. Additionally, all requests from the `download_blob` API are ranged download requests regardless of Blob size.

So, this unfortunately means, the SDK is not really compatible with Azure Frontdoor as this time. There are some workarounds I can suggest but they are not perfect solutions.

- Disable caching on your CDN. If caching is disabled on the CDN, this issue will not occur. I do realize; however, this likely defeats the purpose of the CDN for your purposes.
- The workaround I suggested in the other issue should still apply here. Essentially you can apply a request hook to replace the `x-ms-range` header with `Range` as the Storage service supports both. I have tested this to work with frontdoor but do note it would be an unsupported scenario from our end as we use `x-ms-range`. Additionally, someone had reported other issues with this method on the other thread (though again, it worked for me in testing). Also note, **this will not work with Shared Key authentication** as the `x-ms-range` header is part of the authorization header calculation. It should work for publicly accessible blobs without authentication and maybe SAS (untested)

```py
def range_request_hook(request):
    range = request.http_request.headers.pop('x-ms-range', None)
    if range:
        request.http_request.headers['Range'] = range

async with BlobClient.from_blob_url(blob_url, raw_request_hook=range_request_hook) as blob_client:
    blob_downloader: StorageStreamDownloader = await blob_client.download_blob(
        encoding="UTF-8"
    )
    contents = await blob_downloader.readall()
    print(contents)
```
