### ISSUE TITLE
azure.monitor.opentelemetry - monitor - exporter - configure_azure_monitor hangs

### ISSUE THREAD

**Issue by mathrb** [Azure/azure-sdk-for-python#33441]
- **azure.monitor.opentelemetry**: 
- **1.1.1**: 
- **Ubuntu 22.04.3**:
- **3.10.12**: 

**Describe the bug**
`configure_azure_monitor` blocks the code and diplays some exception messages:
`Exception  in detector <opentelemetry.resource.detector.azure.vm.AzureVMResourceDetector object at 0x7f9698b12170>, ignoring`

**To Reproduce**
1. Create the following script:
```python
from azure.monitor.opentelemetry import configure_azure_monitor

configure_azure_monitor(connection_string="<<appinsight connection string>>")
print("done")
```
2. Done is never printed, and the following messages are displayed every ~5 minutes
`Exception  in detector <opentelemetry.resource.detector.azure.vm.AzureVMResourceDetector object at 0x7f9698b3d5a0>, ignoring`

Here are the endpoints in the connection string:
`IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/`

**Expected behavior**
Configuration ends normally.

**Comment by Anakin100100** [comment]
I'm experiencing the same issue

**Comment by Anakin100100** [comment]
@xiangyan99 is anybody from Microsoft working on this?

**Comment by Anakin100100** [comment]
@mathrb does this affect every version or just some?

**Comment by jeremydvoss** [comment]
1. Is this happening locally, on App Service, or in another environment?
2. You can disable the VM resource detector using an OpenTelemetry environment variable. See the README's [Usage section](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry/README.md#usage) on details. Let me know if the function hangs even without the Resource Detector.

I am unable to reproduce this issue. That script works fine for me locally. As the message says, whatever error is taking place is _ignored_ and should not cause an issue. You can see that code [here](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L398). My guess is there is something else causing OpenTelemetry setup to repeat.

Are you using any OpenTelemetry environment variables to configure?

**Comment by johnliu55-msft** [comment]
I also encountered this issue and I think the root cause is how OpenTelemetry handles resource detection, where it uses [ThreadPoolExecutor with `future.result(timeout)`](https://github.com/open-telemetry/opentelemetry-python/blob/975733c71473cddddd0859c6fcbd2b02405f7e12/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L386) to aggregate data from multiple detectors. Those futures will keep running even though timeout has occurred and captured by `future.result()`, so the context created by `with ThreadPoolExecutor` will not exit until all the futures have completed.

The Azure VM resource detection tries to retrieve data from endpoint `http://169.254.169.254/metadata/instance/compute?api-version=2021-12-13&format=json`, and on my env this would take 2-3 minutes to fail eventually, thus blocks the whole OpenTelemetry configuration.

The workaround for me now is setting environment variable `OTEL_EXPERIMENTAL_RESOURCE_DETECTORS` to `otel` to override the [default](https://github.com/Azure/azure-sdk-for-python/blob/2c1b886c3a578e1c9beff1f6bb93f285da6f63f8/sdk/monitor/azure-monitor-opentelemetry/azure/monitor/opentelemetry/_configure.py#L106):
```
export OTEL_EXPERIMENTAL_RESOURCE_DETECTORS=otel
```

I tried set it to an empty string but that breaks the code. After reading the code [here](https://github.com/open-telemetry/opentelemetry-python/blob/975733c71473cddddd0859c6fcbd2b02405f7e12/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L184), I think it's safe to set the value to `otel` for now as it will be added by OpenTelemetry if missing.

**Comment by jeremydvoss** [comment]
The issue stems from an unclear timeout in the OTel SDK. My [fix](https://github.com/open-telemetry/opentelemetry-python/pull/3645) will be in the next release. In order to not trigger the 5 second timeout, the VM Resource Detector now sets its own timeout to 4s. Please update to opentelemetry-resource-detector-azure=0.1.3
