### ISSUE TITLE
Broken Markdown table on Azure Key Vault keys page

### ISSUE THREAD

**Issue by daviewales** [Azure/azure-sdk-for-python#33453]
![image](https://github.com/Azure/azure-sdk-for-python/assets/2499066/0e936ad7-4823-4692-bc4e-8a9416f591d0)

Direct link: https://learn.microsoft.com/en-us/python/api/overview/azure/keyvault-keys-readme?view=azure-python#next-steps
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 219cdd4e-807c-d2d1-0441-2c72fc9f53b6
* Version Independent ID: 735041f7-05c6-2bd1-439f-a01433f8cb7d
* Content: [Azure Key Vault Keys client library for Python](https://learn.microsoft.com/en-us/python/api/overview/azure/keyvault-keys-readme?view=azure-python)
* Content Source: [docs-ref-services/latest/keyvault-keys-readme.md](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-services/latest/keyvault-keys-readme.md)
* Service: **keyvault**
* GitHub Login: @azure-sdk
* Microsoft Alias: **azsdkdocs**

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by mccoyp** [comment]
Hi @daviewales, thank you for the report! This issue is a little surprising since the markdown table renders correctly in other contexts, but the pattern is inconsistent with other libraries. I'll reformat this section to align with other SDK libraries, and this should be fixed with our next package release.
