### ISSUE TITLE
Unable to send email with attachments using azure.communication.email

### ISSUE THREAD

**Issue by andrewrussell-forecast** [Azure/azure-sdk-for-python#33495]
- **Package Name**:  azure-communication-email
- **Package Version**: 1.00
- **Operating System**: Windows 10 Business
- **Python Version**: 3.10.13

**Describe the bug**
I am trying to create an azure function that sends an email with an attachment. I have successfully managed to send a plain text email using the azure-communication-email package but cannot get any attachments to work. 

At first I thought this was maybe because I was trying to send an xlsx file and something was messed up with my encoding, but I have tried sending a simple text file using exactly the steps laid out here in [this tutorial](https://learn.microsoft.com/en-us/python/api/overview/azure/communication-email-readme?view=azure-python#send-email-with-attachments)

And I always receive the same http response error

```
HttpResponseError: (BadRequest) Request body validation error. See property 'attachments[0].contentType'
```

**To Reproduce**
1. Download and install azure-communication-email
2. Connect to email client 
3. Try to run the code from the tutorial about sending email attachments

**Expected behavior**
I expect to at least be able to send simple files as shown in the documentation

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/73475200/0ca0acc4-4b21-47dc-a1f6-ed53005b652e)

**Comment by annatisch** [comment]
Hi @andrewrussell-forecast - I notice that the SDK sample differs from the one you linked to very slightly in that reads from the file as binary rather than text and encoding to utf-8:
```python
with open(attachment_path, "rb") as file:
    file_bytes = file.read()

file_bytes_b64 = base64.b64encode(file_bytes)
```
Source:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-email/samples/send_email_with_attachments_sample.py#L45-L48

Would you be able to try this?

**Comment by andrewrussell-forecast** [comment]
Hello, thanks for the suggestion I gave this a go but receiving the same error. Here is my code just in case I am missing something really obvious 

```
# send the email
email_connection_strong = os.getenv("AZURE_EMAIL_CONNECTION_STRING")
email_sender = os.getenv("AZURE_EMAIL_SENDER")

client = EmailClient.from_connection_string(email_connection_strong)

with open("hello.txt", "rb") as file:
    file_contents = file.read()

file_bytes_b64 = base64.b64encode(file_contents)

message = {
    "content": {
        "subject": "This is the subject",
        "plainText": "This is the body",
        "html": "<html><h1>This is the body</h1></html>"
    },
    "recipients": {
        "to": [
            {
                "address": "andrew.russell@kinandcarta.com",
                "displayName": "Andrew Russell"
            }
        ]
    },
    "senderAddress": f"{email_sender}",
    "attachments": [
        {
            "name": "hello.txt",
            "attachmentType": "text/plain",
            "contentInBase64": file_bytes_b64.decode()
        }
    ]
}

poller = client.begin_send(message)
result = poller.result()
```

![image](https://github.com/Azure/azure-sdk-for-python/assets/73475200/327877e5-05de-4cff-8167-bf7bf89f2312)

```

**Comment by annatisch** [comment]
Thanks @andrewrussell-forecast - I think I see the issue:
I believe the field name should be `"contentType"` instead of `"attachmentType"` - which is what seems to be documented in the code generated from the service definition here:
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/communication/azure-communication-email/azure/communication/email/_generated/operations/_operations.py#L326-L334

That would also explain the particular wording of the error. Let me know if that helps!

**Comment by annatisch** [comment]
Pending your confirmation - I have started a PR here to fix the tutorial:
https://github.com/Azure/azure-sdk-for-python/pull/33501

**Comment by andrewrussell-forecast** [comment]
Hello, I just tested the fix and it works! Thank you for the help, I probably should have picked that one up from the error message.

**Comment by annatisch** [comment]
Good to hear! Thanks for reaching out!
