### ISSUE TITLE
HTTP Challenge response tenant id is used even with verify_challenge_resource=False

### ISSUE THREAD

**Issue by AMEvers** [Azure/azure-sdk-for-python#33621]
This bug mirrors the issue in [this issue](https://github.com/Azure/azure-sdk-for-python/issues/28648) which I don't believe is actually resolved.  Noticing the same problem with adfs, I attempted to use @mccoyp's [azure-keyvault-secrets==4.8.0b1](https://pypi.org/project/azure-keyvault-secrets/4.8.0b1/). This appeared to partially address the bug but still had an issue. 

If I attempted to create two sets of credentials and clients connecting to the same `vault_url`, the first client would successfully connect and retrieve a secret, the second instance would fail with `ClientAuthenticationError`.
https://github.com/Azure/azure-sdk-for-python/blob/8354b4476d036135876741efdbba3106e70c46fe/sdk/identity/azure-identity/azure/identity/_internal/utils.py#L74-L79

Specifically, `"The current credential is not configured to acquire tokens for tenant adfs."`

If the second client is to a different vault_url, there is no problem, it's only when a second client is instantiated to the same vault endpoint as a previous client. I admittedly haven't dug to the same level as the first reporter but half suspect that this is related to the token being cached in memory being incorrect.

**Environment**
- **package version**
  azure-common              1.1.28
  azure-core                     1.29.5
  azure-identity                1.15.0
  azure-keyvault-secrets   4.8.0b1
- **os version**
  RHEL 9.2 (plow)
- **Python Version**
  3.11.6

**Describe the Bug**
With [azure-keyvault-secrets==4.8.0b1](https://pypi.org/project/azure-keyvault-secrets/4.8.0b1/), creating more than one client to the same keyvault when using adfs to authenticate results in an `ClientAuthenticationError`

**To Reproduce**

Run this code against ADFS on ASH
```
cred = ClientSecretCredential(
                     client_id=app_id,
                     client_secret=app_secret,
                     tenant_id=tenant_id,
                     authority=adfs_endpoint
                     )
client = SecretClient(
                     vault_url=url,
                     credential=cred,
                     verify_challenge_resource=False,
                     api_version=ApiVersion.v7_1
                     )
secret = client.get_secret("secret").value       # Works, returning the secret

cred = ClientSecretCredential(
                     client_id=app_id,
                     client_secret=app_secret,
                     tenant_id=tenant_id,
                     authority=adfs_endpoint
                     )
client = SecretClient(
                     vault_url=url,
                     credential=cred,
                     verify_challenge_resource=False,
                     api_version=ApiVersion.v7_1
                     )
secret = client.get_secret("secret").value       # Fails, triggering a ClientAuthenticationError
```

**Expected behavior**
You can create multiple clients against the same keyvault.

**Comment by pvaneck** [comment]
Hey, thanks for the issue. @mccoyp, perhaps you might know what could be going on here in the adfs case? Quite peculiar that the first instance works, but the second does not.

@AMEvers, Out of curiosity, does adding `additionally_allowed_tenants=["*"]` as a keyword arg to the second `ClientSecretCredential` help at all?

**Comment by mccoyp** [comment]
Hi @AMEvers, thank you for the issue report and details! I think I found the cause of this behavior. The first client's request succeeds because we correctly account for AD FS, by excluding a tenant ID in our token request, when responding to the initial authentication challenge: https://github.com/Azure/azure-sdk-for-python/blob/c41c06e52679f2520010759dd7de8a4665eec597/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L119-L122

This challenge is cached locally, mapping the vault URL to the auth challenge details we received from KV. A second client that targets a different vault won't find a cache entry for the new URL, so we'll repeat the same (correct) interaction to get a token.

If the second client targets the original vault instead, we'll pick up the cached challenge and follow a different code path to check if we have an existing token: https://github.com/Azure/azure-sdk-for-python/blob/c41c06e52679f2520010759dd7de8a4665eec597/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/challenge_auth_policy.py#L77-L80

`self._need_new_token` is True since this is a new client, so we make another token request -- but this request doesn't account for AD FS, and includes a tenant ID. This causes the error you mentioned (and correctly identified as matching the one from https://github.com/Azure/azure-sdk-for-python/issues/28648).

We can fix this on the KV SDK's side, but there should be ways to resolve the issue through Identity in the meantime. One way would be by setting the `AZURE_IDENTITY_DISABLE_MULTITENANTAUTH` environment variable to True, but it would be preferable to use `additionally_allowed_tenants`, like @pvaneck suggested. I'm not sure why it didn't work on your end though; Paul, would you be able to help with that?

**Comment by AMEvers** [comment]
> We can fix this on the KV SDK's side, but there should be ways to resolve the issue through Identity in the meantime. One way would be by setting the `AZURE_IDENTITY_DISABLE_MULTITENANTAUTH` environment variable to True, but it would be preferable to use `additionally_allowed_tenants`, like @pvaneck suggested. I'm not sure why it didn't work on your end though; Paul, would you be able to help with that?

@mccoyp Thank you for the break down, I really appreciate it. Sounds like I was at least in the vicinity of the right trail suspecting the token caching as being the culprit. I retried setting `additionally_allowed_tenants=["*"]` and appears I misspoke earlier. It didn't result in a `ClientAuthenticationError`. Rather, the second request resulted in the same 503 error [described in #28648](https://github.com/Azure/azure-sdk-for-python/issues/28648#issuecomment-1420143926). 

I also experimented with setting `AZURE_IDENTITY_DISABLE_MULTITENANTAUTH=True` and that definitely worked. That seems like a preferable immediate solution to caching clients so thank you for pointing me to it.
