### ISSUE TITLE
BlobServiceClient gives timeout socket read

### ISSUE THREAD

**Issue by PrathamSoni** [Azure/azure-sdk-for-python#33786]
- **Package Name**:  azure-storage-blob
- **Package Version**: 12.19.0
- **Operating System**: Mac/Linux
- **Python Version**: 3.11.5

**Describe the bug**
Have say 10-100 async blob uploads running, prolonged socket timeout errors across files.

**To Reproduce**
Upload several large files to blob storage concurrently.

**Expected behavior**
Files should upload.

**Comment by kashifkhan** [comment]
Hi @PrathamSoni, can you also provide some sample code that help the team reproduce this issue please ?

**Comment by jalauzon-msft** [comment]
Hi @PrathamSoni Pratham, this sounds like it's more an issue with the client machine / network being overloaded and/or caused by other external issues. Or perhaps you just start more uploads concurrently than your client machine can handle. I would definietly check the health metrics of your client machine and/or network metrics. 

There isn't too much we can investigate without more information / code samples but just to share some settings that you can tweak to possibly tune the performance of the SDK. You can tune network timeouts by using the `connection_timeout` keyword argument on client construction (or `read_timeout` but that is more for download). See [README](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-blob/README.md#other-client--per-operation-configuration).

Additionally, assuming your blobs are larger than 64 MiB in size, they will be uploaded in chunks with the default chunk size being 4 MiB. You can also tune the chunk size as well as the threashold for when chunking is performed using various keyword arguments on client construction. See the code documentation [here](https://github.com/Azure/azure-sdk-for-python/blob/65337c2692b6306e0ace91ed5cf7fed8c6839241/sdk/storage/azure-storage-blob/azure/storage/blob/_blob_client.py#L124-L128).

Other than that please provide more info specific to your scenario as well as code samples for further investigation. Thanks.
