### ISSUE TITLE
`az keyvault key encrypt` does not support expected value length

### ISSUE THREAD

**Issue by marvinbuss** [Azure/azure-sdk-for-python#34094]
- **Package Name**: azure-keyvault-keys
- **Package Version**: 4.9.0b3
- **Operating System**: Windows 11
- **Python Version**: 3.11.6

**Describe the bug**
When using the `az keyvault key encrypt ...` command in Azure CLI, it calls the Azure SDK for Python Key Vault Key clients to encrypt a provided value (ref: https://github.com/Azure/azure-cli/blob/88165864f95eb311db905f16d133b92bf9671070/src/azure-cli/azure/cli/command_modules/keyvault/custom.py#L1174). When testing this command, we discovered that the max expected lengths of the provided values are not supported resulting in the following error message:
![image](https://github.com/Azure/azure-sdk-for-python/assets/34542414/45851604-2b85-4b1e-a713-1e4df8f7657a)

We compared the results with the behavior of the Key Vault REST API. The Key Vault REST API works as expected and returned the expected results for the provided value lengths. REST API Reference: https://learn.microsoft.com/en-us/rest/api/keyvault/keys/encrypt/encrypt?view=rest-keyvault-keys-7.4&tabs=HTTP

The following results were discovered:
| Encryption Algorithm | Expected max. message length in bytes | Supported length via REST API in bytes | Supported length in SDK in bytes |
|:------------------------|:------------------------|:------------------------|:------------------------|
| RSA-OAEP-256 | 448 | 448 | 446 |
| RSA-OAEP | 508 | 508 | 470 |

**To Reproduce**
1. Create a Key Vault.
2. Create a key of type `RSA` with length `4096`.
3. Use Azure CLI 2.54 or 2.56
4. Run the following command (value has 508 bytes): `az keyvault key encrypt --name "<your-key-name>" --vault-name "<your-vault-name>" --algorithm "RSA-OAEP-256" --value "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" --data-type "plaintext"`
5. Do the same using the Key Vault REST API.
6. You will see different behaviors of the Azure CLI.

**Expected behavior**
No error when running the above Azure CLI command.

**Screenshots**
Screenshot shared above of error message.

**Additional context**
None

**Comment by kashifkhan** [comment]
Thank you for the feedback @marvinbuss . We will investigate and get back to you asap.

**Comment by mccoyp** [comment]
Hi @marvinbuss, thank you again for opening this issue. I tested this with the SDK and was able to reproduce the "Bad Length" error that you're seeing; I agree that this is unexpected and that the SDK's behavior should align with the REST API's. I'm still looking to why this difference in behavior exists and can update this thread when I have more information.

**Comment by mccoyp** [comment]
Hi again! After a lot of trial and error, I think this ended up being an encoding issue. The CLI command should work if `--data-type` is provided as "base64" instead of "plaintext"; I explain why below. Please let me know if this resolves your issue or if anything's unclear 🙂

When I try the command you provided (with RSA-OAEP, to align with the 508-length maximum in the table you provided), I'm able to reproduce the issue (I shortened the `value` for readability, but it's 508 characters long):
```bash
$ az keyvault key encrypt --name "<key-name>" --vault-name "<vault-name>" --algorithm "RSA-OAEP" --value "aaa...a" --data-type "plaintext"

This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Local encrypt operation failed: Encryption/decryption failed.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/crypto/_client.py", line 246, in encrypt
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/crypto/_providers/local_provider.py", line 66, in encrypt
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/crypto/_internal/rsa_key.py", line 173, in encrypt
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/keyvault/keys/crypto/_internal/algorithms/rsa_encryption.py", line 54, in transform
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/rsa.py", line 484, in encrypt
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/rsa.py", line 75, in _enc_dec_rsa
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/rsa.py", line 133, in _enc_dec_rsa_pkey_ctx
ValueError: Encryption/decryption failed.
(BadParameter) Bad Length.

Code: BadParameter
Message: Bad Length.
```

I found the same behavior when using the SDK directly; i.e. calling
```python
message = b"a" * 508
crypto_client.encrypt(EncryptionAlgorithm.rsa_oaep, message)
```
results in the same "Bad Length" error, as I mentioned yesterday. After some investigation, it's because the client will automatically base64-encode the plaintext; we end up sending a value to the service that's double-encoded.

This command succeeds when we provide raw bytes instead of base64-encoded bytes, since that's what the client method expects:
```python
import base64
message = base64.b64decode(b"a" * 508)
crypto_client.encrypt(EncryptionAlgorithm.rsa_oaep, message)
```

It seems that the CLI expects a similar approach; since our plaintext is base64-encoded, we should specify "base64" as the `data-type`:
```bash
$ az keyvault key encrypt --name "<key-name>" --vault-name "<vault-name>" --algorithm "RSA-OAEP" --value "aaa...a" --data-type "base64"
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "aad": null,
  "algorithm": "RSA-OAEP",
  "iv": null,
  "kid": "https://<vault-name>.vault.azure.net/keys/<key-name>/<version>",
  "result": "avRmb8YvTjkZjO7Ij+kEcfjYaQ9P7YAXhmBYoaiqT1h/Ks/8MRcaijBMLLltTHYVLxlkH3ekkP2MijRVM2oBvy7t8jtPHNIUtsaR+rfKKuryRU/sqS8qufP4w3owWxR6VTqsGZlcF3Su5M4CCY4wF486kVDUiDbsvejNjTjI6bX+Kr6CyBoh2kLj20iPEYTQuiXJ9fjWpRAxLQ3KqsN54fhXl96YuHVxXYoA4UZwcvrxH7Wqvv6sdojWSoKxN2W3RYWA5Orgr+cyziHP6iyPea9s+n2YcuIWljb58yy7571va8/wE9pjlIRqWqLoaRcbnprTOug+YvC1IlwQbCokSKRIh9H1Jr/kwq6HnYJO97RhH36JGsiJxAaOzCH1sApJM9pXIEBiCURP6leLagtnudV0GlCWHDGJzJ7vwiYYodpA8wskKme+/IiESOLYt4Ukll3lEOhi0q5LirajsUBxCPEbc4BINE+LgIXJSTuIcDUfuZpeXgE9ILOVBbk/2efeNNzig0hns4PFdAWrWsg7Yu94Pa5KdgUZmPH4mX2nBu+MhzsZHc+h8E/l/xbrF11AlGE4sS8wDlMvgM9bGUSYtwCCnNb3Gi/U6iSFRewhjGjzteDu2xkkn+v2CGg/+s3iwtovjPUsMWCmR+knpCCI0gzdFPm2krEKiZUqGfgeSiQ=",
  "tag": null
}
```

Throwing the (also base64-encoded) result into the `decrypt` command, we get back the original plaintext:
```bash
$ az keyvault key decrypt --name "<key-name>" --vault-name "<vault-name>" --algorithm "RSA-OAEP" --value "avR...Q=" --data-type "base64"
This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
{
  "algorithm": "RSA-OAEP",
  "kid": "https://mcpatinokvt.vault.azure.net/keys/livekvtestmaxlenff5a304f/8c4089a60dc1418da4e6e74904fe1e1c",
  "result": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}
```

**Comment by simondrake** [comment]
Thanks for the assessment @mccoyp,  but I'm not convinced that is a fix; at best it's a workaround. 

Setting the data type to base64 is confusing, because the passed string isn't base64 encoded. 

So it sounds like there's more to do to figure out why the plaintext data type doesn't work as intended?

**Comment by mccoyp** [comment]
Hi @simondrake, thanks for the response. I don't think I explained the source of the discrepancy well in my answer; the main mix-up here is with the plaintext encoding that's expected by the REST API. The REST API expects the plaintext to be base64url-encoded for transport, but the SDK expects raw bytes as input.

This means that when we send `"aaa...a"` as the `value` in a REST encryption request, this is assumed to be the base64url-encoded value of our plaintext. The "raw" plaintext being used for encryption is actually the decoded value:
```
>>> base64.b64decode("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
b'i\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9ai\xa6\x9a'
```

This also explains the accepted plaintext lengths that were reported in the issue description. As [this Stack Exchange thread discusses](https://crypto.stackexchange.com/questions/42097/what-is-the-maximum-size-of-the-plaintext-message-for-rsa-oaep/42100#42100), the maximum message length for [RSA-OAEP encryption](https://learn.microsoft.com/azure/key-vault/keys/about-keys-details#wrapkeyunwrapkey-encryptdecrypt) with a 4096-bit key is 470 bytes; the maximum for RSA-OAEP-256 is 446 bytes.

This matches up with the maximum lengths we see in CLI/SDK encryption, since the expectation (when `--data-type` is "plaintext") is that the plaintext is in raw bytes. The SDK client automatically encodes the plaintext before the HTTP request is sent to Key Vault in order to make it JSON-safe and meet Key Vault's API specifications.

If we mean to encrypt plaintext `A`, we should provide `A` as-is to the SDK's `encrypt` method or the CLI's `key encrypt` command (with `--data-type` set to "plaintext"). If using the REST API (or the CLI with `--data-type` as "base64"), we should instead provide the base64url-encoded value of `A`.

**Comment by simondrake** [comment]
Thanks @mccoyp - at least half the issue will be me not fully understanding, rather than you not explaining well :slightly_smiling_face: 

I'm still somewhat confused, but if I'm understanding the previous two responses the "issue" is with the different data types that are supported in the API and CLI/SDK?

The API **only** supports base64 encoded values, so whatever is sent it assumes it is already encoded. I.e. -

* If the payload is sent to the API - it assumes it's already base64 encoded and sends the text straight to be encrypted.
* If the payload is sent to the CLI/SDK as plaintext, it base64 encodes them before sending it to the API. 

If I'm understanding that correctly, a payload of 446 `a` (446 bytes) via the CLI/SDK becomes a payload of 595 bytes and a payload of 447 `a` (447 bytes) via the SLI/SDK becomes a payload of 596 bytes. 

But both 595 and 596 are over the expected byte limit, so I'm assuming I'm still missing _something_ as I can't then understand why the former would work and the latter wouldn't

```
## This payload (size of 446 bytes)

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

## Base64 URL encoded, becomes 595 bytes

YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE

## This payload (447 bytes)

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

## Base64 URL encoded, becomes 596 bytes

YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh
```

**Comment by simondrake** [comment]
Follow-up: If the answer is RSA-OAEP-256 with a 4096 bit key only supports 446 bytes as [the Stack Exchange post you linked mentions](https://crypto.stackexchange.com/questions/42097/what-is-the-maximum-size-of-the-plaintext-message-for-rsa-oaep/42100#42100), that makes sense to me. 

I'm still confused how 4097 bytes work through the API but not the CLI/SDK, but I'm assuming that can be attributed to what I'm not understanding about the conversion to Base64 URL encoded strings?

**Comment by mccoyp** [comment]
Hi @simondrake, you're correct about the encoding assumptions for the plaintext:

> - If the payload is sent to the API - it assumes it's already base64 encoded and sends the text straight to be encrypted.
> - If the payload is sent to the CLI/SDK as plaintext, it base64 encodes them before sending it to the API.

I think the confusion is around understanding what the "plaintext" is in each scenario. When we're using the REST API directly, the `value` we send isn't the plaintext; it's the **base64url-encoded value** of the plaintext.

Let's call our plaintext `A`, and its base64url-encoded value `B`:

`A`:
- Value: `b"a" * 446`
- Length: 446 bytes

`B`:
- Value: `base64.b64encode(A) = base64.b64encode(b"a" * 446)`
- Length: 596 bytes

In this scenario, we want to encrypt the plaintext `A`, which is the maximum-length plaintext we can encode using RSA-OAEP-256 with a 4096-bit key. Below is a table showing how we can do this for each method we're concerned with:

| Tool | User input | Value sent over wire | Plaintext used for encryption |
|-----|-----|-----|-----|
| **REST API** | `B` | `B` | `A` |
| **CLI (`--data-type "base64"`)** | `B` | `B` | `A` |
| **CLI (`--data-type "plaintext"`)** | `A` | `B` | `A` |
| **SDK** | `A` | `B` | `A` |

At the end of the day, each method is using the same plaintext for encryption: `A`. The input we should provide just depends on the context, based on what each tool expects. The REST API assumes that the user has already base64url-encoded their plaintext; I assume this is why the [API documentation](https://learn.microsoft.com/rest/api/keyvault/keys/encrypt/encrypt?view=rest-keyvault-keys-7.4&tabs=HTTP) refers to the input as "`value`", rather than "`plaintext`", since `value` is actually the encoded form of the plaintext.

Similarly, the `--data-type` options for the CLI command hint at the same assumption. `"plaintext"` should be used when you're providing the actual plaintext as-is; `"base64"` should be used when you're providing the encoded value of the plaintext.

This also explains why the encoded payload, `B` -- which is over 446 bytes -- still works for encryption: the encoded payload isn't actually the plaintext being encrypted, and only the length of `A` matters. If we change `A` to be 447 bytes, then testing on my end shows that the encryption fails for each method.

**Comment by simondrake** [comment]
Thanks @mccoyp, it _almost_ all makes sense now. 

The only remaining question/confusion I have is, when @marvinbuss was conducting testing, they were able to send 448 bytes direct to the API.

If the plaintext (`A`) is always used for encryption, wouldn't the byte limit be the same (446 bytes) regardless of whether the API, CLI, or SDK is used? 

**Reference table from the issue description (RSA-OAEP purposefully omitted):**

| Encryption | Expected max. message length in bytes | Supported length via REST API in bytes | Supported length in SDK in bytes |
|--------|--------|--------|--------|
| RSA-OAEP-256 | 448 | 448 | 446 |

**Comment by mccoyp** [comment]
Hi @simondrake, I think there must have been either a mistake in the 448-byte encryption (e.g. actually providing a shorter plaintext) or a misunderstanding of what the plaintext was (i.e. confusing `A` and `B`, per above). I gave this a try on my end, using the REST API, to confirm.

This is the result of encrypting with a maximum-length, 446-byte plaintext (`value` is the result of `base64.b64encode(b"a" * 446)`):
<img width="926" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/39780829/cf2daca1-b38a-4234-b9e3-b9aa75f1e8ee">

And below is the result of encrypting with a 448-byte plaintext (`value` is the result of `base64.b64encode(b"a" * 448)`):
<img width="923" alt="image" src="https://github.com/Azure/azure-sdk-for-python/assets/39780829/63d8c372-595f-4214-8c46-49073357e5aa">

I also tried with a 447-byte plaintext just to be sure, and got the same "BadParameter" response as the latter example. Fortunately I see the same behavior with the CLI (for either `--data-type`) and the SDK 🙂

I hope this clarifies things; this conversation actually helped me better understand the input expectations of each tool, and I'll make sure to improve the Python SDK's documentation around this. Please let me know if you have any questions, but I'll mark this issue as resolved for the time being. Thank you for your patience!

**Comment by simondrake** [comment]
Thanks @marvinbuss @mccoyp for the discussion/answers. What was at the root of the issue was my misunderstanding of what the maximum byte limit is - I _thought_ the maximum was 4096 bits / 512 bytes, as I was confusing the payload size and the key size. 

What would help is if the [Azure documentation for Key types, algorithms, and operations](https://learn.microsoft.com/en-us/azure/key-vault/keys/about-keys-details) could be updated to include a reference to the calculation needed to determine the maximum payload size.

@marvinbuss - I assume that's a different team, unrelated to the Python SDK? 

This issue can now be closed. Thanks for all the effort, I appreciate it.
