### ISSUE TITLE
urllib3.connection.HTTPSConnection SDK error for Azure Resource Graph

### ISSUE THREAD

**Issue by tsaindane-cloudwiz** [Azure/azure-sdk-for-python#34097]
- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
We are using python SDK for azure.mgmt.resourcegraph for querying the assets. But SDK most of the time giving us follwoing error stating: `<urllib3.connection.HTTPSConnection object at 0x3ed9892d49a0>: Failed to establish a new connection: [Errno 110] Connection timed out`

**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by l0lawrence** [comment]
Hi @tsaindane-cloudwiz thank you for the feedback, we will investigate and get back to you asap. Could you please share the package version, operating system and python version you are running on?

**Comment by tsaindane-cloudwiz** [comment]
package version of azure.mgmt.resourcegraph is 7.0.0
Its running on google's cloud function V1 with Python version: Python 3.9

**Comment by ChenxiJiang333** [comment]
Hi @tsaindane-cloudwiz 
You mean you are using the `ResourceGraphClient.resource` method like in this [sample](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/resources/azure-mgmt-resourcegraph/generated_samples/resources_basic_query.py#L31)? Yet with that, I failed to reproduce this issue. Please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to provide detailed log for deep investigation.

**Comment by tsaindane-cloudwiz** [comment]
@ChenxiJiang333 Yes I am using `ResourceGraphClient.resource` method. So, this issue is not happening consistently, so in our architecture, we have 15-20 may be more parallel requests calling this function and for some of the request we faced this issue.

**Comment by ChenxiJiang333** [comment]
@tsaindane-cloudwiz Please know that python SDK is just a tool to send/receive http request/response, like what the method `ResourceGraphClient.resource` doing is just to call the api [resources](https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph/resources/resources?view=rest-azureresourcegraph-resourcegraph-2022-10-01&tabs=HTTP). Since it was an error returned by service, it's suggested to seek help from service team by opening issue at https://github.com/Azure/azure-rest-api-specs/tree/main. And I still hope you can follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to provide a log to help service team address the issue.
