### ISSUE TITLE
The stream=True parameter does not control the actual return of the interface verbatim. As a result, the interface still returns the generated content in batches.

### ISSUE THREAD

**Issue by Hkaisense** [Azure/azure-sdk-for-python#34145]
When calling Azure's openai interface, I chose stream=True, and the first word generation was very long, about 6 seconds or more. After observation, I found that it is basically generated in one go, which is completely different from the streaming I understand. I hope it can be streamed like the openai interface, with word-by-word output.

**Comment by kristapratico** [comment]
@Hkaisense can you please fill out the following template to help us better assist? Is this issue for the Python [openai](https://github.com/openai/openai-python) library?

- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
