### ISSUE TITLE
Nameless arguments for managed run command is not working

### ISSUE THREAD

**Issue by GauravChawda** [Azure/azure-sdk-for-python#34397]
- **Package Name**: azure-mgmt-compute
- **Package Version**: 29.1.0
- **Operating System**: Windows 10 22H2
- **Python Version**: 3.11.1
- **VM Operating System**: Ubuntu 20.04.6 LTS

**Describe the bug**
The target script cannot access the nameless arguments because it is not getting passed to the script. 
Used following python code to create managed run command.
```
from azure.mgmt.compute import ComputeManagementClient
from azure.mgmt.compute.models import RunCommandInputParameter
from azure.identity import DefaultAzureCredential

credential = DefaultAzureCredential()

client = ComputeManagementClient(credential, "<subscription-id>")

client.virtual_machine_run_commands.begin_create_or_update(
    resource_group_name="<resource-group>", 
    vm_name="<vm-name>",
    run_command_name="temp",
    run_command={
        "location": "eastus",
        "source": {
            "script": "/script.py",
        },
        "parameters": [
            RunCommandInputParameter(name="", value="abc"),
            RunCommandInputParameter(name="", value="xyz"),
        ],
        "async_execution": True
    }
)
```

script.py
```
#!/usr/bin/env python3
import sys
print(sys.argv)
```

Current Output:
```
['./script.py']
```

**To Reproduce**
1. Create any Linux based VM
2. Copy script.py to / in VM
3. Run above python code to create managed run command

**Expected behavior**
```
['./script.py', 'abc', 'xyz']
```

**Comment by swathipil** [comment]
Hi @GauravChawda - thanks for opening an issue! We'll take a look asap.

**Comment by ChenxiJiang333** [comment]
Strangely it somehow works with bash code `echo $@` to print nameless arguments but failed when running a python file. 
Since we are not domain expert, please open an issue at https://github.com/Azure/azure-rest-api-specs/issues to seek help from service team, and please follow https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md to provide detailed log for service team to do deep investigation. @GauravChawda
