### ISSUE TITLE
[Storage] `ContainerClient.delete_blobs` would return `list_iterator` instead of `AsyncIterator` with empty blobs.

### ISSUE THREAD

**Issue by wenleix** [Azure/azure-sdk-for-python#34447]
- **Package Name**: 
azure-storage-blob
- **Package Version**: 
12.14.1
- **Operating System**:
Linux
- **Python Version**: 
3.11

**Describe the bug**
`ContainerClient.delete_blobs` would return `list_iterator` instead of `AsyncIterator` with empty blobs.

**To Reproduce**
```python
blob_names = []
res = await container_client.delete_blobs(*blob_names, raise_on_any_failure=False)
async for r in res:
    print(r.status_code)
```

Get the following error:
```
...
    async for r in res:
TypeError: 'async for' requires an object with __aiter__ method, got list_iterator
```

**Expected behavior**
It returns `AsyncIterator` and the above code works. 

**Screenshots**
N/A

**Additional context**

Change the following code: https://github.com/Azure/azure-sdk-for-python/blob/be4fbbce47c072ea75a138b5ab2e22afce77d4b1/sdk/storage/azure-storage-blob/azure/storage/blob/aio/_container_client_async.py#L1268-L1269

to be
```python
if len(blobs) == 0:
    return AsyncList([])
```

Should work.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by vincenttran-msft** [comment]
Hi @wenleix Wenlei, thanks for your inquiry. I am actually working on a typing overhaul for the `azure-storage-file-datalake` package currently, and I have incorporated this feedback into that pull-request. However, because that is part of a larger typing effort, it will likely not be released anytime in the future. Is this something that is currently blocking your workflow? Otherwise, it will be fixed and this issue will be closed when the fix is merged into the feature branch. Please let me know if that is not the case, then I can look to expediting this to be part of our next general release.

Thanks!

**Comment by wenleix** [comment]
Thanks @vincenttran-msft . it's not blocking (we can work around it by not calling `container_client.delete_blobs` if `blob_names` is empty. And I see https://github.com/Azure/azure-sdk-for-python/pull/34314 merged (how do i check which new client library would contain the fix?) . Thanks so much!
