### ISSUE TITLE
Doc for `read_item` method of CosmosDB `ContainerProxy` class misses the `CosmosResourceNotFoundError` in `Exceptions` section

### ISSUE THREAD

**Issue by RollerKnobster** [Azure/azure-sdk-for-python#34652]
### Type of issue

Missing information

### Description

Doc for `read_item` method of CosmosDB `ContainerProxy` class misses the `CosmosResourceNotFoundError` in `Exceptions` section. This information was used as reference during development, and resulted in incomplete exception handling, causing problems and creating a bug in the system. Please do update the doc for this method (as well as in the source code, since [the docstring for this method there](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/azure/cosmos/container.py#L213) also lacks the `raises ~azure.cosmos.exceptions.CosmosResourceNotFoundError` line).

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.container.containerproxy?view=azure-python#azure-cosmos-container-containerproxy-read-item

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-cosmos/azure.cosmos.container.ContainerProxy.yml

### Document Version Independent Id

3c745306-3c71-b694-e621-eecb115923cd

### Article author

@lmazuel

### Metadata

* ID: 9f4a7941-9eb0-3ec5-6412-29b5d6e77bda 
* Service: **cosmos-db**

**Comment by simorenoh** [comment]
Hi @RollerKnobster, I was wondering what the issue was here since the documentation does point out the fact that the error happens when a resource is not found, and the CosmosResourceNotFound exception inherits CosmosHttpResponseError so there should be no issues with error handling doing either of the two - these two are equivalent for the method outlined:


![Image](https://github.com/user-attachments/assets/5b369b34-35d8-46aa-82cd-972a1565e969)


Can you expand on what the problem is here?
