### ISSUE TITLE
Typing error with 

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-sdk-for-python#34744]
- **Package Name**: azure-keyvault-secrets
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**

Starting with this code:

```
from azure.keyvault.secrets.aio import SecretClient

async with SecretClient(
    vault_url=f"https://{key_vault_name}.vault.azure.net", credential=azure_credential
) as key_vault_client:
    search_key = (await key_vault_client.get_secret(search_secret_name)).value
```

Then running "python -m mypy", we get this typing error:

 error: "AsyncKeyVaultClientBase" has no attribute "get_secret"  [attr-defined]

The error only happens when I use it as an async context manager.

**Comment by schaabs** [comment]
@mccoyp Could you take a look?

**Comment by mccoyp** [comment]
Hi @pamelafox, sorry about the delay on this. It looks like this typing confusion comes from how we implement the `__aenter__` method to make the client a context manager. Specifically, the method is implemented in the base client that `SecretClient` inherits from, and its return type is typed accordingly: https://github.com/Azure/azure-sdk-for-python/blob/c41c06e52679f2520010759dd7de8a4665eec597/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py#L69

Because of this, within the `async with` block, `mypy` interprets the `key_vault_client` as an `AsyncKeyVaultClientBase` instead of a `SecretClient` -- hence, the error it raises. This also appears with the synchronous client, since it has an analogous implementation.

I'll open a PR to shift out these context manager methods to the user-facing clients to avoid this issue, per how other clients in the SDK handle this. Thank you for raising this issue!
