### ISSUE TITLE
grainparameter not accepted in client.benefit_utilization_summaries.list_by_savings_plan_id

### ISSUE THREAD

**Issue by darushah** [Azure/azure-sdk-for-python#35034]
- **Package Name**:  azure-mgmt-costmanagement
- **Package Version**:  0.2.0
- **Operating System**: Win 11
- **Python Version**:  3.10.11

**Describe the bug**
Currently in the SDK client.benefit_utilization_summaries.list_by_savings_plan_id there is a grain_parameter which we can define for Monthly. Where in the backend API call it adds the below in the API URL:

&grainParameter=Monthly

However, this is not getting accepted and the response always returns with daily grain.

However, if we call the REST API directly with this parameter &grain=Monthly, it accepts the grain parameter and gives the data with monthly grain.

**To Reproduce**
1.  We can use the below code to reproduce the issue:

```python
from azure.identity import ClientSecretCredential
from azure.mgmt.costmanagement import CostManagementClient

def main():
    client = CostManagementClient(
        credential=ClientSecretCredential('{TenantId}','{ClientId}', '{ClientSecret}'),
    )

    response = client.benefit_utilization_summaries.list_by_savings_plan_id(
        savings_plan_order_id="{SavingsPlanOrderId}",
        savings_plan_id="{SavingsPlanId}",
        grain_parameter="Monthly",
        ##filter = "properties/usageDate ge 2024-01-01 and properties/usageDate le 2024-03-31"
    )
    for item in response:
        print(item)

if __name__ == "__main__":
    main()

```

**Expected behavior**

The correct parameter for grain should be reflected in the REST which is &grain=Monthly instead of the wrong one &grainParameter=Monthly.

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by ChenxiJiang333** [comment]
Hi, @darushah could you provide the package version you're using?

**Comment by darushah** [comment]
@ChenxiJiang333 it is azure-mgmt-costmanagement==4.0.0b1

**Comment by ChenxiJiang333** [comment]
Python sdk was auto generated by the swagger definitions, and the parameter `grainParameter` follows the swagger definition in [here](
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-11-01/costmanagement.benefits.json#L1414).
Yet since the service accepts parameter `grain` instead of `grainParameter`, I have opened an [issue](https://github.com/Azure/azure-rest-api-specs/issues/28638) to turn to the service team to make an update for the swagger. Once the swagger is updated, python sdk would release a new version for fix as well.
