### ISSUE TITLE
what a joke, you create the new issue from the ticket you've ignored for 2 years!

### ISSUE THREAD

**Issue by jbernardini** [Azure/azure-sdk-for-python#35063]
Hi @jbernardini, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.

_Originally posted by @github-actions[bot] in https://github.com/Azure/azure-sdk-for-python/issues/18217#issuecomment-2035266707_

**Comment by ronniegeraghty** [comment]
Hi @jbernardini , 
I apologize for the inconvenience caused by the automatic closure of your issue. Our system is designed to close issues that are older than 2 years and have not seen any updates in the last 30 days. This process helps us keep our issue queue relevant and allows us to focus on issues that require our immediate attention. Unfortunately, your issue was mistakenly identified as irrelevant by this system, which I assure you was not the case.
I will open a new issue to ensure that it is properly addressed and track down the correct people to handle it. I appreciate your patience and understanding in this matter.
Additionally, I would like to remind you of the importance of adhering to our [Code of Conduct](https://github.com/Azure/azure-sdk-for-python/blob/main/CODE_OF_CONDUCT.md) when contributing to our repository. The title of your issue has been noted to have an aggressive and disrespectful tone, which is not in line with the respectful communication we encourage. When opening new issues, please ensure that the language used is professional and courteous.
Thank you for bringing this to our attention, and rest assured that we will take the necessary steps to prevent such occurrences in the future.

**Comment by ronniegeraghty** [comment]
New issue created for the bug: https://github.com/Azure/azure-sdk-for-python/issues/35073

Once I've tracked down the proper person to resolve the issue, I'll remove myself as the assignee and assign them.
