### ISSUE TITLE
Azure Search calls wrong API URL

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-sdk-for-python#35082]
- **Package Name**:  azure-cognitiveservices-search-websearch
- **Package Version**: 2.0.0
- **Operating System**: macOS
- **Python Version**: python 3.11

**Describe the bug**

Any attempt to search using the search SDK fails with a 404 because it tries to call the wrong REST API. It will call: `https://api.bing.microsoft.com/bing/v7.0/search?mkt=en-us&q=Azure%20Bicep`.

This is not the right base URL.

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitiveservices/azure-cognitiveservices-search-websearch/azure/cognitiveservices/search/websearch/_configuration.py#L38

It also doesn't seem to set the `Ocp-Apim-Subscription-Key` header in the request?

The correct base URL is : 
https://api.bing.microsoft.com/v7.0/search?mkt=en-us&q=Azure%20Bicep see this link https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/endpoints

```python
import os
import dotenv
import json
from azure.cognitiveservices.search.websearch import WebSearchClient
from msrest.authentication import CognitiveServicesCredentials

# Load environment variables
dotenv.load_dotenv()


creds= CognitiveServicesCredentials(os.environ.get('AZURE_SEARCH_KEY'))
search = WebSearchClient(endpoint=os.environ.get('AZURE_SEARCH_ENDPOINT'), credentials=creds)
print(search.web.search(query="Azure Bicep"))
```

**Comment by lmazuel** [comment]
Hey @tonybaloney , 
As we discussed offline, the Bing team is working on a solution to this on this repo:
https://github.com/microsoft/bing-search-sdk-for-python

While the solution is not available yet, I'm closing this issue since it will not come from this repo, being `azure-cognitiveservices-search-websearch` is a deprecated package. We are working in parallel to mark this deprecation effective.
