### ISSUE TITLE
azure-mgmt-datalake-nspkg  installation issues.

### ISSUE THREAD

**Issue by hdost** [Azure/azure-sdk-for-python#3512]
With the transition to azure-nspkg 3.0.0. I understand that moving forward it is only supported in Python 2.7. However the reliance has broken multiple different projects and how they install. As of right now I am forced to pin versions of nspkg so that the packages will install properly. It's not that I directly want to use nspkg it is that my applications can't cleanly install the packages without the pinnings.

Edit: I believe I have found the issue. Currently, there are a whole bunch of listings for "extras_require" to pin it, but as I understand it the qualifications should instead be done this way https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

**Comment by lmazuel** [comment]
Hi @hdost 
There was nothing wrong with azure-nspkg 3.0.0, but I discovered that indeed too much third-parties installer were not respecting the PyPI protocol. See #3447 

Then, I released a version 3.0.2 to simplify even if you have a broken proxy that does not respect the PyPI protocol. You should not see any troubles now.

I'm closing the issue, since I truly think there is nothing more to do on that topic. Please still commend on it if there is more I don't see.

Thank you,
