### ISSUE TITLE
Blob properties show that there are N number of tags but the tags are None

### ISSUE THREAD

**Issue by ravilnicki** [Azure/azure-sdk-for-python#35199]
- **Package Name**: azure-storage-blob
- **Package Version**: 12.15.0b1
- **Operating System**: Debian GNU/Linux 12 (bookworm)
- **Python Version**: 3.11.2

**Describe the bug**
Blob properties show that there are N number of tags but the tags are None.

**To Reproduce**
1. Create a ContainerClient
2. Use get_blob_client() method of ContainerClient to get a BlobClient
3. Use upload_blob() method of BlobClient
4. Use get_blob_properties() method to get the properties
5. In properties check the number of tags (tag_count) which is equal to 2
6. Check the tags which are None

in code:
`from azure.storage.blob import ContainerClient

account_url = ""
container_name = ""
shared_access_key = ""

container_client = ContainerClient(account_url=account_url, container_name=container_name, credential=shared_access_key)
blob = container_client.get_blob_client("temp_file")  # temp_file does not exist at this point
blob.upload_blob(b"hello world", tags={"hello": "world", "wild": "blue"})
p = blob.get_blob_properties()
print(p.tag_count)  # 2
print(p.tags)  # None
`

**Expected behavior**
p.tags should return correct tags

**Comment by jalauzon-msft** [comment]
Hi @ravilnicki, thanks for reaching out. The behavior you describe is expected as `get_blob_properties` does not return the Blob Tags, only the tag count. See [REST docs](https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-properties?tabs=microsoft-entra-id#response-headers). If you wish to fetch the tags you need to call [get_blob_tags](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.blobclient?view=azure-python#azure-storage-blob-blobclient-get-blob-tags) instead. Tags are also returned from `list_blobs` when you specify `include=['tags']`.

The reason the `BlobProperties` model has a `tags` property is because the model is shared with the response of `list_blobs` where `tags` could be populated.

**Comment by jalauzon-msft** [comment]
I'll close this issue but please let us know if you have any other questions.

**Comment by ravilnicki** [comment]
Thanks for the response @jalauzon-msft I could have read the docs more carefully.
