### ISSUE TITLE
Parameters/Variables do not have descriptions

### ISSUE THREAD

**Issue by vandreiradu** [Azure/azure-sdk-for-python#35241]
### Type of issue

Missing information

### Description

While looking at real-time data answers some of my questions, it would be good (and faster) to have these descriptions in documentation.

e.g.
key - possible values, what do they mean
renewal_period - is it in seconds

Thank you!

### Page URL

https://learn.microsoft.com/en-us/python/api/azure-mgmt-cognitiveservices/azure.mgmt.cognitiveservices.models.throttlingrule?view=azure-python

### Content source URL

https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-cognitiveservices/azure.mgmt.cognitiveservices.models.ThrottlingRule.yml

### Document Version Independent Id

37ffa09c-23f8-6235-7c4b-3fb38e187b99

### Article author

@lmazuel

### Metadata

* ID: fdc0b930-1496-3327-3717-0e3925023294 
* Service: **azure-ai-services**

**Comment by ChenxiJiang333** [comment]
Hi @vandreiradu The doc content is generated by swagger definition, the related definition is [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2023-05-01/cognitiveservices.json#L2671) and seems there's no description wrote for these properties. Since we are not domain expert, please open an issue at https://github.com/Azure/azure-rest-api-specs/tree/main to turn to the service team to help add the descriptions.

**Comment by xiangyan99** [comment]
This issue needs to be fixed in the swagger.

Please open issues in [https://github.com/Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/tree/main) repo.
