### ISSUE TITLE
LUIS and QnA Maker deprecated/retired, replaced by CLU and Custom QA 

### ISSUE THREAD

**Issue by d-kleine** [Azure/azure-sdk-for-python#35561]
**Is your feature request related to a problem? Please describe.**
As of 1st April, you cannot create new LUIS services anymore, it has been replaced by Conversational Language Understanding (CLU), see [https://www.luis.ai/](https://www.luis.ai/)
![grafik](https://github.com/microsoft/BotBuilder-Samples/assets/53251018/4624de65-4e5c-4f20-9efe-bc758f225ebb)

Also QnA Maker is deprecated and has been replaced by Custom Question Answering, see [https://www.qnamaker.ai/](https://www.qnamaker.ai/)
![grafik](https://github.com/Azure/azure-sdk-for-python/assets/53251018/966d6910-67f9-41da-8e6d-6f988bcf17b8)

Therefore, the Python code samples provided [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples) don't work anymore.

**Describe the solution you'd like**
We need updated Python code samples reflecting the transition from LUIS to CLU and from QnA Maker to Custom QA. This includes any necessary changes to the import statements, class instantiation, and method calls to ensure compatibility with the new services.

**Describe alternatives you've considered**
One alternative is to manually modify the existing code samples to align with the changes in services. However, this approach is time-consuming and error-prone, especially for developers unfamiliar with the intricacies of the transition. Therefore, having officially updated Python code samples provided by Azure would greatly expedite the process for developers migrating to CLU and Custom QA.

**Comment by kristapratico** [comment]
@d-kleine thanks for your issue. We're currently working on cleaning up deprecated libraries and documentation so that it's more clear which client libraries to use. Our libraries that target LUIS and QnAMaker will soon be deprecated:

LUIS: [azure-cognitiveservices-language-luis](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitiveservices/azure-cognitiveservices-language-luis)
QnAMaker: [azure-cognitiveservices-knowledge-qnamaker](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker)

The libraries you should use for CLU and QA include the following:

CLU: [azure-ai-language-conversations](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitivelanguage/azure-ai-language-conversations)
QA: [azure-ai-language-questionanswering](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitivelanguage/azure-ai-language-questionanswering)

> Therefore, the Python code samples provided [here](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples) don't work anymore.

For CLU, there is a sample that shows how to use the old LUIS service ([sample_analyze_orchestration_app_luis_response.py](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_luis_response.py)) and we will remove it. The other samples should work with the current CLU service. Is there something you found that didn't work?

**Comment by d-kleine** [comment]
Thanks! I was just asking to update these [Azure SDK for Python samples](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples) to be working with CLU and Custom QA, along with an updated documentation and code comments.
* CLU: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_luis_response.py
* Custom QA: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_qna_response.py

I haven't tested it yet because the Python samples looked deprecated. I wanted to try to set up an [QA Bot](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_qna_response.py) with Azure Bot with Python (as there are no Python samples in the BotBuilder Samples provided for that).

**Comment by quentinRobinson** [comment]
@d-kleine from my understanding you want an example of using CLU and Custom QA on an orchestration project. The samples you need are 
- Custom QA: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_qna_response.py
-  CLU: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_conv_response.py

The only sample that will be deprecated is the 
- LUIS: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_analyze_orchestration_app_luis_response.py

[But click here for more information on Orchestration workflow](https://learn.microsoft.com/en-us/azure/ai-services/language-service/orchestration-workflow/overview)

**Comment by swathipil** [comment]
Hi @d-kleine - Thanks for your patience! We're in the process of removing the deprecated `sample_analyze_orchestration_app_luis_response.py` sample to remove any confusion there.

We've also officially deprecated these packages:
- https://pypi.org/project/azure-cognitiveservices-language-luis/
- https://pypi.org/project/azure-cognitiveservices-knowledge-qnamaker/
