### ISSUE TITLE
For virtual WAN/virtual Hub, there is no way to fetch the HubVirtualNetworkConnectionStatus

### ISSUE THREAD

**Issue by danielchiu-MSFT** [Azure/azure-sdk-for-python#35773]
The is the ask from ARR/Strategic customer (from CSS support case).

In Azure Portal, it is possible to check the virtual network connectivity status in virtual WAN/hub:
![image](https://github.com/Azure/azure-sdk-for-python/assets/127278719/ed0afff5-8eb6-4704-abf4-509c392df07e)

With Azure SDK for Python, the only relevant method is through HubVirtualNetworkConnections Operations Class:
https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.operations.hubvirtualnetworkconnectionsoperations?view=azure-python

But this would not return the connectivity status of virtual network connection:
https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.models.hubvirtualnetworkconnection?view=azure-python

However; the connectivity status of hub virtual network connection actually exists in this model:
https://learn.microsoft.com/en-us/python/api/azure-mgmt-network/azure.mgmt.network.models.hubvirtualnetworkconnectionstatus?view=azure-python

But there is no operation/class to fetch this data.

Please suggest if this is going to be implement in the future or there is any workaround for it.

**Comment by ChenxiJiang333** [comment]
Hi @danielchiu-MSFT, python sdk is generated by swagger definitions, so we can't decide its features. 
About why [HubVirtualNetworkConnectionStatus](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-11-01/virtualWan.json#L8078) exists but there's no model or operation to fetch it, since it was originally designed in the swagger, please open an issue at https://github.com/Azure/azure-rest-api-specs/issues to turn to the service team for support.
