### ISSUE TITLE
parameter parsing failed when function call

### ISSUE THREAD

**Issue by diana1919zhong** [Azure/azure-sdk-for-python#35776]
My code is as follows：

client = AzureOpenAI(
    api_version=api_version,
    api_key=api_key,
    azure_endpoint=f"https://{resource_name}.openai.azure.com",
)

completion = client.chat.completions.create(
    model=deployment_name,
    stream=False,
    n=1,
    temperature=0.7,
    tools=[
            {'type': 'function',
                'function':
                    {'name': 'bingSearch',
                     'description': 'You can search the Internet',
                     'parameters':
                         {'type': 'object',
                          'properties':{'query': {'description': 'Search content', 'type': 'string'}},
                          'required': ['query']
                          }
                     }
             }
    ],
    messages=[{'content': 'You can search the Internet', 'role': 'system'},
              {'content': 'Types of Christmas trees', 'role': 'user'}],
)

b = time.time()

print("tool query：", completion.choices[0].message.tool_calls[0].function.arguments)

The result returned is：
tool query： {"query":"\n\n"}

Parameter parsing failed. How can I solve this problem

**Comment by kristapratico** [comment]
@diana1919zhong can you help me understand the issue by filling out this template?

- **Package Name**: 
- **Package Version**: 
- **Operating System**:
- **Python Version**: 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. 

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.
