### ISSUE TITLE
Sample broken... 

### ISSUE THREAD

**Issue by jainparakh** [Azure/azure-sdk-for-python#35893]
Steps to reproduce -

1. Create a new Doc Intelligence Resource
2. Try to use the python SDK sample 

Expected:
* it works? Not sure what the result is

Actual:
Throws:

Inner error: {
    "code": "ParameterMissing",
    "message": "The parameter urlSource or base64Source is required."

**Comment by jainparakh** [comment]
Same issue as here - https://learn.microsoft.com/en-us/answers/questions/1639700/unable-to-use-new-api-for-document-intelligence

Please fix this

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by YalinLi0312** [comment]
Hi @jainparakh , I've tried the layout model sample in this doc([link](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/quickstarts/get-started-sdks-rest-api?view=doc-intel-4.0.0&pivots=programming-language-python#layout-model)) but didn't see any errors. Based on the error you got, I looks the issue is from using `begin_analyze_document()`. Can you provide the package name, package version and code snippet for how you're using `begin_analyze_document()`? These would help us to reproduce and investigate the issue.

In general, if you're analyzing a doc from local, you can pass it directly or wrap it to a `AnalyzeDocumentRequest` object.
e.g.
```python
with open(path_to_sample_documents, "rb") as f:
    poller = document_intelligence_client.begin_analyze_document(
        "prebuilt-layout",
        analyze_request=f, # pass it directly
        content_type="application/octet-stream",
    )
result = poller.result()
```
```python
with open(path_to_sample_documents, "rb") as f:
    poller = document_intelligence_client.begin_analyze_document(
        "prebuilt-layout",
        AnalyzeDocumentRequest(bytes_source=f.read()), # pass it to "AnalyzeDocumentRequest"
    )
result = poller.result()
```
Note: we've changed the parameter name in "AnalyzeDocumentRequest" from "base64_source" to "bytes_source" since `azure-ai-documentintelligence` package version `1.0.0b2` as we expect the input in bytes, not in base64 encoded.
If you're analyzing a doc from remote, you can pass the url in "AnalyzeDocumentRequest" like this:
```python
poller = document_intelligence_client.begin_analyze_document(
    "prebuilt-layout", AnalyzeDocumentRequest(url_source=url)
)
```
