### ISSUE TITLE
Many versions of one secret in Key Vault

### ISSUE THREAD

**Issue by jasperkpi** [Azure/azure-sdk-for-python#35923]
**Is your feature request related to a problem? Please describe.**
I'm using Azure Key Vault for API keys that rotate every 10 minutes. It uses an OAuth2 flow, where the access_token is valid for 600 seconds. We safe the new refresh_token that is generated every rotation in the key vault. This means I have secrets with as much as 20.000 versions. When I use the [SecretClient.list_properties_of_secret_versions](https://github.com/Azure/azure-sdk-for-python/blob/73cf501eacd74e8efc2ee19a860e2c3220697aa7/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py#L212C9-L212C43) it takes minutes to load all the versions. Is there any way to fix this?

**Describe the solution you'd like**
How can I prevent having to load so many versions? I try to get the latest 10 versions, not all 20k.

**Describe alternatives you've considered**
I've considered:
* Deleting old versions, which seems not to be possible. There's no "retention time" for versions. Only completely soft-delete the secret manually and rewrite as the same name - maybe?
* Sorting the request, but versions don't come date-sorted on the [Get Secret Versions](https://learn.microsoft.com/en-us/rest/api/keyvault/secrets/get-secret-versions/get-secret-versions?view=rest-keyvault-secrets-7.4&tabs=HTTP) as I've found. They come hexadecimally sorted based on the version id, which is kinda useless? 

I don't care there are 20k versions, I'm fine Azure apparently wants to keep them. I just want to view the last 10 or so. How would this be possible? Am I forgetting about an option? Thanks.

**Comment by mccoyp** [comment]
Hi @jasperkpi, thank you for opening an issue -- I see how this scenario could be frustrating. @jlichwa, do you know if there's an option on the service's end to restrict the number of results we get from this operation?

**Comment by mccoyp** [comment]
@jasperkpi I tried reproducing your issue and found the same behavior; iterating over the full set of versions (after I had created 20,000) took a long time, and the sorting was deterministic but not chronological.

If your primary goal is just to get a small batch of secret versions for inspection, I would recommend using the [by_page()](https://learn.microsoft.com/python/api/azure-core/azure.core.paging.itempaged?view=azure-python#azure-core-paging-itempaged-by-page) method on the `ItemPaged` object you get back from `list_properties_of_secret_versions`. This will group the response into smaller pages that can be rapidly inspected. For example:
```python
versions = client.list_properties_of_secret_versions(secret_name)
pages = versions.by_page()
single_page = next(pages)
for secret_properties in single_page:
    print(secret_properties.version)
```

The default page size is 25 entries, but you can change this by passing a smaller integer through a `max_page_size` keyword argument to `list_properties_of_secret_versions`.

If you specifically need the most _recent_ versions of the secret, this seems to unfortunately require manual sorting (unless @jlichwa can comment on an alternative once he's back in the office). The other alternative could be to create new secrets instead of a new version of the same secret, though I understand how having a single secret name could be a requirement for shared referencing and simplicity.

**Comment by jasperkpi** [comment]
@mccoyp Thanks for your answer. I thought this would be the case. Unfortunately, I am looking for the most _recent_ versions just to recover the not-current-but-last key. So only the recent 2 or 3 would be enough... This now means I have to get all 17.000 secret versions (with a OAuth refresh time of 10 minutes, versions are made at a rapid pace) and then sort them on changeddate.

```py
versionlist = []
versions = client.list_properties_of_secret_versions(secret_name)
for version in versions:
    versionlist += [f'{str(version.created_on)[:19]} {{{version.version}}} ']
sortedversionlist = sorted(versionlist, reverse=1)
```
I just hoped I was completely missing out a function of list_properties_of_secret_versions that delivered a sorted list or something. Thanks!

**Comment by mccoyp** [comment]
@jasperkpi it may be more performant to use metadata, such as [`tags`](https://aka.ms/azsdk/python/keyvault-secrets/docs#azure.keyvault.secrets.SecretClient.set_secret), to record recent versions of the secret. That way you could fetch the most recent version of the key, inspect the tags, and then fetch the specific versions that are recorded. It would require multiple service requests, but it may save time overall.

I did discuss this with the service team and chronological version sorting unfortunately doesn't appear to be an option at this time. I'll mark this issue as resolved, but we'll be sure to incorporate this feedback into future planning. Thank you again for opening an issue!
