### ISSUE TITLE
az keyvault certificate create - validation too strict

### ISSUE THREAD

**Issue by Splaxi** [Azure/azure-sdk-for-python#35926]
Windows 11
```PowerShell
PS C:\>az version 
{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {}
}
```

**Describe the bug**
Trying to create a new certificate, based on the input that I'm required from portal.azure.com or the Az.KeyVault PowerShell module. The validation is to strict in the following code:

https://github.com/Azure/azure-sdk-for-python/blob/a624a225aaaeff49471553a3613b2f88dbc189de/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py#L94-L96

**To Reproduce**
Policy - as json
```json
{
    "policy": {
        "key_props": {
            "kty": "RSA",
            "key_size": 2048,
            "reuse_key": false
        },
        "secret_props": {
            "contentType": "application/x-pkcs12"
        },
        "x509_props": {
            "subject": "CN=testing.contoso.com",
            "validity_months": 12
        },
        "issuer": {
            "name": "Unknown"
        },
        "attributes": {
            "enabled": true
        }
    }
}
```

Az Cli command executed, in PowerShell 7+
```PowerShell
az keyvault certificate create --vault-name this-is-keyvault --name this-is-a-cert --policy $policyJson
```

I'm confident that I have handled the quotation issues within powershell, as I'm able to post the above policy directly via:
```PowerShell
az rest --resource https://vault.azure.net --method post --uri https://this-is-keyvault.vault.azure.net/certificates/this-is-a-cert/create?api-version=7.4 --body $policyJson
```

The error code / message posted:
`You need to set either subject or one of the subject alternative names parameters in the policy`

**Expected behavior**
I'm expecting it to create a valid, pending, certificate. Just like it would via the portal.azure.com, Az.KeyVault PowerShell module or the Azure REST API for KeyVault / Certificates

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/8750181/30182f9d-156b-4b54-96e3-5156f4816e38)

**Additional context**

**Comment by mccoyp** [comment]
Hi @Splaxi -- thank you for opening an issue, and I apologize for the delayed response. I was able to reproduce your issue today and did some digging for the cause. Given that your example policy includes a subject, the error message made me think that the CLI may not be processing the policy as intended.

I found the [`build_certificate_policy` method](https://github.com/Azure/azure-cli/blob/87606b1af08c531b4be8f3845e04daf341cf79cc/src/azure-cli/azure/cli/command_modules/keyvault/_validators.py#L737) in the CLI's source code, which is where the policy parameter seems to actually be processed. I noticed that the anticipated format was a little different from your JSON; `key_properties` was expected instead of `key_props`, `validity_in_months` instead of `validity_months`, etc. I ended up setting the following `$policyJson` based on the CLI's expectations:
```json
{
  "key_properties": {
    "key_type": "RSA",
    "key_size": 2048,
    "reuse_key": false
  },
  "secret_properties": {
    "content_type": "application/x-pkcs12"
  },
  "x509_certificate_properties": {
    "subject": "CN=testing.contoso.com",
    "validity_in_months": 12
  },
  "issuer_parameters": {
    "name": "Unknown"
  },
  "attributes": {
    "enabled": true
  }
}
```

With this `$policyJson`, the same `az keyvault certificate create` command now worked -- it seems that the issue was coming from the format.

I found an old issue about the unclear guidance on certificate policy formatting: https://github.com/Azure/azure-cli/issues/9423. The [`az keyvault certificate get-default-policy --scaffold`](https://learn.microsoft.com/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-get-default-policy) command does give a helpful guide for policy formatting -- the policy scaffold uses `camelCase` instead of `snake_case`, and I found that replacing the parameter casing of the `policyJson` above also works with the `az keyvault certificate create` command.

cc @evelyn-ys to forward CLI feedback.
