### ISSUE TITLE
azure-ai-documentintelligence AIO capability is not working

### ISSUE THREAD

**Issue by jacky0218** [Azure/azure-sdk-for-python#36217]
- **Package Name**: 
azure-ai-documentintelligence
- **Package Version**: 
1.0.0b2
- **Operating System**:
Linux
- **Python Version**: 
3.10.14

**Describe the bug**
The AIO version runs no faster than without AIO

**To Reproduce**
I just followed the code example as below.
(https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/samples/aio/sample_analyze_general_documents_async.py)

**Expected behavior**
AIO-level speed.

**Comment by kristapratico** [comment]
@jacky0218 thanks for your feedback, @YalinLi0312 will take a look and get back to you as soon as possible. Can I ask how you're measuring speed between sync and async?

**Comment by jacky0218** [comment]
@kristapratico 
Thanks for the support.
I've tested a 5-page PDF, and the speed from sync is **0.12936785444617271**. Async yields a speed of **0.12989125028252602**.

**Comment by lmazuel** [comment]
Hi @jacky0218 

AIO programming means that the HTTP IOs under the hood are managed using async/await and an asyncio event loop, in order to avoid blocking code on sockets. If the Azure service needs 11 seconds to process your PDF, you can't finish faster than what the service will do, you just do a better usage of your local CPU and socket usage with aio. Therefore, the times you got here sounds reasonable given your limitation is service related, not Python related. To say it differently, if you run the same PDF through C# or Java SDK, you will still get 11 seconds, since the SDK is just a messenger here and there isn't heavy processing done by the SDK in this specific scenario.
