### ISSUE TITLE
Missing websocket-client dependency for azure-servicebus

### ISSUE THREAD

**Issue by green-digger** [Azure/azure-sdk-for-python#36256]
- **Package Name**: azure-servicebus
- **Package Version**: 7.11.4
- **Operating System**: Windows 11
- **Python Version**: Python 3.11.8

**Describe the bug**

Missing `websocket-client` dependency cause azure service bus to throw an exception when using the `azure-servicebus` sdk

**To Reproduce**

Assuming a fresh virtual env

```

pip install azure-servicebus==7.11.4

python -c 'from azure.servicebus._pyamqp._transport import WebSocketTransport; test_websocket_transport = WebSocketTransport("test_host"); test_websocket_transport.connect()'
```

Returns

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<path to env>\.venv\Lib\site-packages\azure\servicebus\_pyamqp\_transport.py", line 731, in connect    
    raise ImportError(
ImportError: Please install websocket-client library to use sync websocket transport

```

The environment contains

```
pip freeze
```

Returns

```
azure-core==1.30.2
azure-servicebus==7.11.4
certifi==2024.6.2
charset-normalizer==3.3.2
idna==3.7
isodate==0.6.1
requests==2.32.3
six==1.16.0
typing_extensions==4.12.2
urllib3==2.2.2
```

**Expected behavior**

Expect no import error exception to be returned

I would expect the dependency to be defined as part of the package dependencies and installed when installing the azure-servicebus package.

**Screenshots**

**Additional context**

The workaround is simple as can just add the dependency directly. I would just expect this to be defined as part of the package dependencies, either required or as an extra.

**Comment by kristapratico** [comment]
@green-digger thanks for your issue, the team will take a look and get back to you as soon as possible.

**Comment by swathipil** [comment]
Hi @green-digger - `websocket-client` is not currently a required dependency since that would force users who are not using websockets to install an unnecessary package. It is up the app developer to determine whether they need this dependency and install it.

If the dependency were to be added to extras, users would still need to modify their install to, for example, `pip install azure-servicebus["websocket-client"]` rather than `pip install azure-servicebus websocket-client` as it is now. Is there a particular reason you'd prefer this package be added to extras?

**Comment by green-digger** [comment]
I would just expect the package to be responsible for defining its direct dependencies as part of it's definition.

Then I can select what flavour of the package I want without being concerned about the underlying dependencies.

I can then define my dependencies using the web socket flavour of the service bus package.

Instead I have to know and maintain the dependencies of the service bus package. 

If I can just select the websocket flavour of the service bus package then I dont have to care what is installed and will guarantee I'll always get a working websocket version of the package.

**Comment by swathipil** [comment]
Hi @green-digger - Thanks for your response!

Since using sync websocket only requires a single dependency (`websocket-client`), we didn’t create a separate extras definition for it.

> I can then define my dependencies using the web socket flavour of the service bus package.
> Instead I have to know and maintain the dependencies of the service bus package.

If we were to create an extras definition for this dependency, it would be named websocket-client rather than websocket. This approach allows us to add other websocket implementations to extras in the future. Therefore, users would need to know the specific dependency to install it using extras.

Installing websocket-client directly will ensure you get the latest version, which should not cause any version conflict issues with the Service Bus library. The only scenario where maintenance might be required is if you pin the dependency version and need to update it. In such cases, adding an extras definition wouldn’t help since we only set a minimum dependency.

Is there another consideration we might be missing?

**Comment by green-digger** [comment]
There's no more I can add. Thanks for taking the time to respond. Feel free to close the issue.
