### ISSUE TITLE
SpanKind.Client not supported

### ISSUE THREAD

**Issue by king-11** [Azure/azure-sdk-for-python#36328]
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**: ^1.6.0
- **Operating System**: Mariner
- **Python Version**: 3.9.7

**Describe the bug**
setting the `kind` of span to `SpanKind.CLIENT` results in it being shown as of type `N/A` in app insights dependency table and end-to-end transaction detail

**To Reproduce**
Create a span and set the kind as client.
```python
tracer = get_tracer(__name__)

@tracer.start_as_current_span(name="update_inference_run", kind=SpanKind.CLIENT)
def update_inference_run():
  print("hello world")
```

**Expected behavior**
Client kind should have a proper type instead of being N/A

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-python/assets/52061363/8556bf45-590b-41e4-9c9d-7636db55e4c7)

![image](https://github.com/Azure/azure-sdk-for-python/assets/52061363/762feded-f824-4c14-ad38-cdf6d903e5fc)

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by lzchen** [comment]
@king-11 

`SpanKind` maps to `itemType` not `type` field in AppInsights. `SpanKind.Cient` maps to `dependency` type telemetry and `SpanKind.Server` maps to `requests` telemetry.

**Comment by king-11** [comment]
@lzchen but in the end to end transaction history it's being shown as N/A and not dependency

**Comment by lzchen** [comment]
The reason you are getting "N/A" for the TYPE field is because application insights expects manually created spans (spans that are created using start_as_current_span) to be of type "InProc", which is the default if you do not set a span kind.  ApplicationInsights only expects `SpanKind.Client` spans created automatically from instrumentations.

```
tracer = get_tracer(__name__)

@tracer.start_as_current_span(name="update_inference_run")
def update_inference_run():
  print("hello world")
```

**Comment by king-11** [comment]
What would it take to support this particular scenario, I can try implementing it if it makes sense to have this feature?

My specific use case is that am familiar that the provided function makes multiple call to Azure SQL which are shown as dependency but then the overall function being a single span can be declared as type `Client`.

**Comment by lzchen** [comment]
> My specific use case is that am familiar that the provided function makes multiple call to Azure SQL which are shown as dependency but then the overall function being a single span can be declared as type Client.

I am not fully understanding the use case here. `InProc` spans are exported as `dependencies` type telemetry as well. If the request is to be able to manually modify the `data.type` field to a specific value, this scenario is not supported.

If you would like to group together your telemetry, there are a lot of other ways you can achieve this, most nobly using [span attibutes](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=python#add-span-attributes)

**Comment by king-11** [comment]
@Izchen the ask is to be able to create spans with `SpanKind.Client` because as a user am familiar that the operation am doing is an external call to some other system. I am able to set in other kinds as they do appear nicely in app insights like `Server`, `Consumer` and `Producer`.

**Comment by lzchen** [comment]
@king-11 

You are indeed able to spans with any `SpanKind` you'd like manually (even SpanKind.Client) with the `start_as_current_span` api. The only thing that is unsupported is the population for the `type` field, which is only populated correctly if you do not override the intended `SpanKind` of manually created spans (which is SpanKind.Internal). This is only specific to `dependency` type telemetry because it is the only one with a `type` field.

**Comment by king-11** [comment]
>The only thing that is unsupported is the population for the type field, which is only populated correctly if you do not override the intended SpanKind of manually created spans (which is SpanKind.Internal).

I don't think that's true setting to `SpanKind.Producer` results in `messaging` `type`. Also `SpanKind.Server` and `SpanKind.Consumer` are taken as requests so that just leaves `SpanKind.Client`.

>As a separate question, when you say Client kind should have a proper type instead of being N/A, what does "proper type" mean?

I think given we can't really provide this detail with `start_as_current_span` as that is a generic api. I am making a `sql` call so I would want the ability like setting in an attribute which can provide this additional detail to app insights if required, would that make sense?

**Comment by lzchen** [comment]
> I don't think that's true setting to SpanKind.Producer results in messaging type. Also SpanKind.Server and SpanKind.Consumer are taken as requests so that just leaves SpanKind.Client.

It is true. Internally, we map `SpanKind.Producer` into `messaging` types but these should be from `Span`s who's `SpanKind` are originally `SpanKind.Producer` types, like the ones generated automatically by an [instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/f8f58ee411ac2e318512717378cd365ba4aa7a66/instrumentation/opentelemetry-instrumentation-celery/src/opentelemetry/instrumentation/celery/__init__.py#L228). Setting the `SpanKind` manually through the api to populate `type`, is an unsupported scenario, although it may "seem" to work because we simply do a mapping internally. If you look internally in the logic, even if you hack the `type` to be `messaging`, it is not really treated as a `messaging` span (notice that `data.target` is missing from your telemetry. If this doesn't matter to you and you would still like this to be a supported scenario, we can treat this as a feature request.

> I think given we can't really provide this detail with start_as_current_span as that is a generic api. I am making a sql call so I would want the ability like setting in an attribute which can provide this additional detail to app insights if required, would that make sense?

`start_with_current_span` is an OpenTelemetry api, and not anything related to Azure monitor. The `type` field is an Azure monitor specific concept. So, if you would like to see the `type` be populated automatically, we already support this scenario based off of what kind of span it is and what attributes the span, usually from ones that are autogenerated from instrumentations. If you would like the SDK to treated MANUALLY created spans also automatically, you must look at the logic and follow the format that is expected since this is not an originally supported scenario. For example, spans generated from db related instrumentations, it is expected to have certain [span attributes](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py#L438) to idenfify 1. they are database related 2. What type of database it is (mysql, mongo, etc) and 3. database related attributes that maps to important fields in AppInsights. Only if the span LOOKS like a db span will AppInsights fully treat it as a piece of telemetry originating from a database. 

Again, this is hacky and prone to error since you will have to manually mimic the span exactly, which is why the recommended and currently only supported scenario is to rely on automatically collected spans from instrumentations.

**Comment by king-11** [comment]
One more information I recently had was in java setting `SpanKind.Client` gets treated as `InProc` which is fine too I guess. From a code perspective I am able to specify that kind is this and app-insights can treat it as it wants to the `N/A` part atleast is gone.

So I see two options:
- manually setting the attributes for span to look like MySQL span what would those attributes be can I know? Given that I don't think `pyodbc` isn't supported for auto instrumentation yet.
- would it make sense to make manually set client span with no data as inproc instead? Just like Java agent does.

**Comment by lzchen** [comment]
I am not sure how those two options are related, they seem to address two different things. 

> manually setting the attributes for span to look like MySQL span what would those attributes be can I know? Given that I don't think pyodbc isn't supported for auto instrumentation yet.

To make the type be `mysql`, set `db.system` attribute span attribute to be `mysql`.

> would it make sense to make manually set client span with no data as inproc instead? Just like Java agent does.

We would rather not change our mappings for a very specific use case such as this. Any reason why you cannot simply use the default behavior which sets the spankind to `Internal`? This defaults to `InProc` type.

If you really must have this behavior, you can replicate it by creating a custom `SpanProcessor` as shown [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=python#add-a-custom-property-to-a-span).

```
from opentelemetry.sdk.trace import SpanProcessor

class ClientToInProcProcessor(SpanProcessor):

    def on_end(self, span):
        if span._kind is SpanKind.CLIENT:
           span._kind = SpanKind.INTERNAL
```

This way you can still call `trace.start_as_current_span("client_span", kind=SpanKind.CLIENT)` but this will be treated as an InProc span still.
