### ISSUE TITLE
Permit users to choose latest preview version or latest stable version in pypi to compare

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-for-python#36371]
Now Mgmt SDK follow the following rule to generate changelog:
- If we are going to release preview package, we will compare with **latest public package no matter it is preview or stable** to generate changelog
- If we are going to release stable package, we will compare with **latest public stable package** to generate SDK

So we hope breaking change detector could add config like `--latest-stable`,
- when true, compare with latest stable version in pypi
- when false, compared with latest version in pypi, no matter it is stable or preview.

For example, if a package named "azure-mgmt-test" has already `1.0.0b1, 1.0.0, 1.1.0b1` in pypi,

- if is going to release new preview version, there is need to compare with `1.1.0b1`
- if is gong to release new  stale version, there is need to compare with `1.00`

**Comment by raych1** [comment]
@catalinaperalta 
please prioritize this issue as it is blocking the integration with the spec PR pipeline.

**Comment by catalinaperalta** [comment]
looking into this

**Comment by catalinaperalta** [comment]
FYI I have a PR addressing this issue. Adding a `--latest-pypi-version` flag to the tool that you'll be able to pass for the mgmt plane cases where you need to compare against the last published preview. Since data-plane will also be using the tool, I'm leaving comparing for breaking changes as the last published stable version as the default scenario.
