### ISSUE TITLE
OpenTelemetry exporter installation error

### ISSUE THREAD

**Issue by TaoChenOSU** [Azure/azure-sdk-for-python#36948]
- **Package Name**: azure-monitor-opentelemetry-exporter
- **Package Version**: 1.0.0b28
- **Operating System**: Windows
- **Python Version**: 3.12

**Describe the bug**
Installing the above package automatically installs opentelemetry-sdk~=1.26.0 and opentelemetry-semantic-conventions 0.47b0, which will cause incompatibility issues later on. 

Error message:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.       
opentelemetry-exporter-otlp-proto-grpc 1.24.0 requires opentelemetry-sdk~=1.24.0, but you have opentelemetry-sdk 1.26.0 which is incompatible.
opentelemetry-instrumentation-asgi 0.45b0 requires opentelemetry-semantic-conventions==0.45b0, but you have opentelemetry-semantic-conventions 0.47b0 which is incompatible.
opentelemetry-instrumentation-fastapi 0.45b0 requires opentelemetry-semantic-conventions==0.45b0, but you have opentelemetry-semantic-conventions 0.47b0 which is incompatible.
```

**To Reproduce**
1. `pip install azure-monitor-opentelemetry-exporter`

**Expected behavior**
Package successfully installed.

**Additional context**
I am able to install version 1.0.0b24.

**Comment by lzchen** [comment]
@TaoChenOSU 

These dependency conflicts are issues in upstream OpenTelemetry Python and unrelated to the azure monitor exporter. Please open up an issue [here](https://github.com/open-telemetry/opentelemetry-python/issues/new/choose) and someone from the community will get back to you.

As for identifying the actual dependency conflicts, I've addressed them below:

1. opentelemetry-exporter-otlp-proto-grpc 1.24.0 requires opentelemetry-sdk~=1.24.0, but you have opentelemetry-sdk 1.26.0 which is incompatible.

The issue lies in the [otlp exporter](https://github.com/open-telemetry/opentelemetry-python/blob/v1.26.0/exporter/opentelemetry-exporter-otlp-proto-grpc/pyproject.toml#L35) dependency on opentelemetry-sdk. The dependency should be `opentelemetry-sdk ~= 1.26` instead of `opentelemetry-sdk ~= 1.26.0`

2. opentelemetry-instrumentation-asgi 0.45b0 requires opentelemetry-semantic-conventions==0.45b0, but you have opentelemetry-semantic-conventions 0.47b0 which is incompatible.
3. opentelemetry-instrumentation-fastapi 0.45b0 requires opentelemetry-semantic-conventions==0.45b0, but you have opentelemetry-semantic-conventions 0.47b0 which is incompatible.

Simply upgrade your `opentelemetry-instrumentation-asgi` and `opentelemetry-instrumentation-fastapi` to versions 0.47b0 for each.
