### ISSUE TITLE
Type Hints Missing In containerservice

### ISSUE THREAD

**Issue by pkrauss-prot** [Azure/azure-sdk-for-python#37234]
- **Package Name**: azure-mgmt-containerservice
- **Package Version**: tested 31.0.0 and 28.0.0
- **Operating System**: MacOS Sonoma 14.6.1
- **Python Version**: python 3.9

**Describe the bug**
I am able to use type hints with vscode for most resources in the package. However `managed_clusters` and `agent_pools` refuses to display any type hints.

**To Reproduce**
1. pip install azure-mgmt-containerservice in a vscode env
2. dot walk the two listed objects.

**Expected behavior**

I would expect it to recognize the method signature like this: 

```
(method) list: ((**kwargs: Any) -> Iterable[azure.mgmt.containerservice.v2022_02_02_preview.models._models_py3.ManagedClusterSnapshot]) | ((**kwargs: Any) -> 
```

**Screenshots**

it can be subtle, but the two I am referring to are white text, indicating no type hints, where as the others are yellow.

![image](https://github.com/user-attachments/assets/25963f38-63fd-413f-9006-e581303cdc66)

**Additional context**
I am using python in a conda setup.

**Comment by kristapratico** [comment]
@pkrauss-prot thanks for bringing to our attention, the team will take a look and respond as soon as possible.

**Comment by msyyc** [comment]
@ChenxiJiang333 please help on this issue

**Comment by ChenxiJiang333** [comment]
@pkrauss-prot, it's because the client's properties `managed_clusters` & `agent_pools` got their type hints compressed when they have too many alternative invocations. It's not an issue of SDK and does not affect its function.
![image](https://github.com/user-attachments/assets/fa385c04-3ceb-4c42-a83b-2d301f6961d3)
![image](https://github.com/user-attachments/assets/feb8ad23-8ed1-4ed8-8940-71c78b135762)
