### ISSUE TITLE
Azure SDK is over 1.2GB and growing on every release.

### ISSUE THREAD

**Issue by sodul** [Azure/azure-sdk-for-python#37303]
When installing the Azure SDK and CLI the azure packages take 1.2GB+ of disk space, which is an issue when working with AWS Lambdas and to a lesser extend with containers in general. This was *only* 500MB back in 2021.

Output from running https://github.com/clumio-code/azure-sdk-trim:
```
/Users/stephane/.pyenv/versions/3.12.6/lib/python3.12/site-packages/azure is using 1.2 GB.
Detected az cli with 39 SDKs to keep.
/Users/stephane/.pyenv/versions/3.12.6/lib/python3.12/site-packages/azure is now using 603.3 MB.
Saved 622.8 MB.
```

This is a duplicate of #17801 which is now read only for external contributors.

**Comment by kristapratico** [comment]
@sodul I apologize - I didn't realize that the github actions bot locked the conversation. I just unlocked https://github.com/Azure/azure-sdk-for-python/issues/17801 so that external contributors can comment once again. Would you mind if we used the original issue to track this? We've fixed the bot such that it will not try to auto-close or lock the issue. Thanks for understanding.

**Comment by sodul** [comment]
Yes that's fine. I had no other way to communicate that the prior issue was locked.
