### ISSUE TITLE
apiversion string included in list_topics(), only on premium sku

### ISSUE THREAD

**Issue by motsu35** [Azure/azure-sdk-for-python#3765]
I developed my code around a basic sku, and now that i switched to premium the code fails due to the inclusion of an apiversion string.  (on standard/basic, the topic foo will return as foo, but on premium returns as foo?apiversion=xxxx).

When passing the topic into other functions, the inclusion on apiversion causes an error.

**Comment by lmazuel** [comment]
Hi @motsu35 
I don't have enough context to understand what you explain: what package are you referring? what version of Python on what env? Example of code before/after that represents your issue, etc.

I'm not able to relate to any behavior of the SDK with just what you describe.

Thank you,

**Comment by motsu35** [comment]
sorry, got here from google and didnt realize that this was for more than just servicebus, which is what this issue is about.

---

code example to reproduce:
    BUS_SERVICE = azure.servicebus.ServiceBusService(service_namespace="some premium servicebus", shared_access_key_name="foo", shared_access_key_value="bar")
    [x.name for x in BUS_SERVICE.list_topics()]

code above will return `['my-topic-name?api-version=2013-10']` if you instead try this with a non premium (standard or basic) service bus, you get `['my-topic-name']` instead.

---
python info:
azure-mgmt-servicebus==0.5.2
azure-servicebus==0.21.1

python 3.6.6, running on linux

**Comment by lmazuel** [comment]
We are deprecating this package, and in the process to replace it with a branch new version from scratch. @annatisch could you confirm if this operation will be available trough AMQP, or if it's control plan still.

**Comment by annatisch** [comment]
Hi @motsu35, @lmazuel,

This will need to be fixed in the control plane SDK, which has not been modified in the current preview release of the new SDK. It's actually related to issue #4247 and is due to be fixed in the next preview release.

Thanks!

**Comment by yunhaoling** [comment]
Hey @motsu35 ,

Apologize for reaching out to you so late.

We're in the process of releasing a new generation of python servicebus sdk v7.0.0 (currently in preview status) and we'll bring fix into our next preview release -- v7.0.0b3.

I'm sorry to tell you that we've decided not to bring any control plane fixes into v0.50. We're focusing our main efforts on v7. v0.50 is a preview version which would be deprecated after v7 becomes GA and maintaining it costs extra resources. 

Apologize for the inconvenience we bring to you and thanks for your understanding.

We'll let you know once v7.0.0b3 is out so that you could have a try.
