### ISSUE TITLE
Azure Storage Blob - Custom Metadata extraction function is incorrectly case-sensitive

### ISSUE THREAD

**Issue by docuinn-mw** [Azure/azure-sdk-for-python#37774]
- **Package Name**: 
azure.storage.blob

- **Package Version**: 
12.23.1

- **Operating System**:
OS X

- **Python Version**: 
Python 3.11.9

**Describe the bug**

Function deserialize_metadata is intended to extract metadata header names from a case insensitive dict, but it does so in a comprehension that calls .items() on the dict which causes the case insensitvity to be lost.
```
def deserialize_metadata(response, obj, headers):  # pylint: disable=unused-argument
    try:
        raw_metadata = {k: v for k, v in response.http_response.headers.items() if k.startswith("x-ms-meta-")}
```
https://github.com/Azure/azure-sdk-for-python/blob/9079caf686e2a29a3fcda96517fa15c547035667/sdk/storage/azure-storage-blob/azure/storage/blob/_shared/response_handlers.py#L63

**To Reproduce**
It's not trivial to reproduce, in our case we are working on an API compatible virtual storage. But the Azure SDK must receive a request with headers of the mixed case format 'X-Ms-Meta-Example', which it will then fail to parse into the returned Metadata.

**Expected behavior**
The above field should be recognised as a custom metadata field named 'example'.

**Comment by weirongw23-msft** [comment]
Hi @docuinn-mw Daithi, thanks for the question! We were able to locally reproduce the issues, and saw that `X-Ms-Meta-Example` is not processed correctly when sending the request. We're currently working on a fix. I linked the PR here that will resolve the issue once we finalize the design, implementation, and testing.

**Comment by jalauzon-msft** [comment]
Hi @docuinn-mw Daithi, I just merged the PR that contains the fix for this, and it will be available in our next release (scheduled for early November).

Just a note for future reference as well as others that may end up here: Using the SDK against anything other than the official Azure Storage service is not recommended or supported. The Storage SDKs are designed to work with **only** the official Azure Storage service and we do not generally take fixes/requests for any other API-compatible services as we just don't have the resourcing to support other random services. Azurite is the one exception here since it is an internally maintained product.

In this particular case, I'm fairly sure the service would not return any case but `x-ms-meta` so this was not technically an issue. We took the fix in this case because it was a simple fix that ultimately hardens the SDK but as I mentioned, this is not something we would normally take.
