### ISSUE TITLE
credential set tenant_id ignored in get_token() - always falling back to default tenant

### ISSUE THREAD

**Issue by cforce** [Azure/azure-sdk-for-python#38000]
version 1.31.0
azure\core\pipeline\policies\_authentication.py@96

self._token = cast(TokenCredential, self._credential).get_token(*scopes, **kwargs)

self._credential has _tenant_id set but get_token_info() -mixin-> azure\identity\_internal\get_token_mixin.py@60 has empty tenant_id which leads to using a default(in my case wrong) tenant id

**Comment by cforce** [comment]
Workaround is to set additionally_allowed_tenants as it seems .. But that shall not be needed

default_creds = ClientSecretCredential(
                tenant_id=self.azure_tenant_id,
                client_id=self.azure_deploy_id,
                client_secret=self.azure_deploy_secret,
                additionally_allowed_tenants=[self.azure_tenant_id]  # Ensure only correct tenant is used
            )

**Comment by xiangyan99** [comment]
Thanks for reporting the issue.

@pvaneck could you help to take a look?

**Comment by cforce** [comment]
I have worked around by  azd logout, az logout on the same shell, however this "sticky session" (stored /cached/somewhere) shall be overriden when i use id, secret and tenantid in my code. I don't the stack trace anymore :/

**Comment by pvaneck** [comment]
I can't seem to recreate whatever issue you are facing. The tenant that is passed in to the constructor of `ClientSecretCredential` will be the one used in the token request.  The `get_token` calls from the `BearerTokenCredentialPolicy` in `azure-core` doesn't pass in a tenant_id in this call: `self._token = cast(TokenCredential, self._credential).get_token(*scopes, **kwargs)`. I would need more info regarding your usage to help debug.

Were you encountering this through usage of the `DefaultAzureCredential` and did you have `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, and `AZURE_CLIENT_SECRET` environment variables set? Typically, azd/az CLI caches shouldn't affect the usage of `ClientSecretCredential`, so that's also puzzling.

**Comment by cforce** [comment]
None of the env var are set and even then they shall not overrule method params, do they?
As i can't reproduce it any more and you can't either, lets close., i will reopen if it returns and  next time give more infos/reproducible
