### ISSUE TITLE
Getting None in input_endpoints of a vm have no endpoint

### ISSUE THREAD

**Issue by zhitongLBN** [Azure/azure-sdk-for-python#391]
When i use `get_role()` to get information of `configuration_set` of a vm, if this vm have no endpoints, i will get None in `input_endpoints`, so if i use this `configuration_set` to update my vm(`update_role()`), it will cause error when the `network_configuration_to_xml` wants to loop for the endpoints.

so i propose we can't fixe this  inconvenience by checking `input_endponts` is None so dont loop, or we can return empty list when we have no Input Endpoints.

Thank you very much

**Comment by lmazuel** [comment]
This code is part of azure-servicemanagement-legacy, since the endpoint in question was replaced by ARM API.
We are not updating this package anymore, and then I'm closing this issue.
I'm sorry we were not able to tackle this issue when it was still making sense and brings value for you :(. Be sure that if you have any issues with more recent SDK we will answer more accurately.
Thank you.
