### ISSUE TITLE
Change PasswordProfile for 

### ISSUE THREAD

**Issue by sfonteneau** [Azure/azure-sdk-for-python#4018]
Hello

I am currently updating my users' passwords with a python script that uses the azure.graphrbac.models API with UserUpdateParameters and PasswordProfile.
The problem is that PasswordProfile needs to have the password clear text, it bothers me a little. I store the passwords of my users in several formats.

Is it possible to send you the password hash in AZURE? (SHA256, SHA512, NTLM)?

Simon

**Comment by lmazuel** [comment]
Hi @sfonteneau 

@yugangw-msft do you know?

**Comment by yugangw-msft** [comment]
The password will have to be in clear text, but it is through HTTPS protocol, so should be safe.

**Comment by sfonteneau** [comment]
@yugangw-msft. So its impossible ?

**Comment by sfonteneau** [comment]
up ?

**Comment by d-cardon** [comment]
Hi everyone,

this issue is quite annoying. HTTPS is only for transport security, and one should have a cleartext password for a longer period of time than necessary (this would be a security issue). What if a user change its password on the local LAN and the internet connection is down, then AzureSync wouldn't work if it was requiring cleartext password... Or it would need to store it cleartext somewhere, which I doubt AzureSync would be doing.

Google Sync python API allows to push Crypt SHA256 password hash... I guess AzureSync API can do it too, so AzureSync python API should too (or at least push NT hash).

In the webpage linked by Simon above, it clearly says "Password hash synchronization" : https://docs.microsoft.com/en-us/azure/active-directory/hybrid/media/how-to-connect-password-hash-synchronization/usersignin2.png

This may be some documentation issue, should I raise a dochelp enquiry?

Cheers,

Denis

**Comment by yugangw-msft** [comment]
This question is beyond my knowledge. I suggest raise up the question in [stack overflow ](https://stackoverflow.com/questions/tagged/azure-active-directory) where Azure AD team encourages users to post the question over there.

**Comment by lmazuel** [comment]
Closing as not Python specific, and AD related. Thanks.

**Comment by sfonteneau** [comment]
Hello

We have more and more customers who want to use Office 365 with samba4. This implementation would be really useful (it already exists because azure ad connect connections use it but I don't know how to use it). Can you help me or tell me who could help me with this? (I am aware that this is not specific to the python API)

I have the hashnt, it would be really practical to be able to send it to azure ad like "azure ad connect"
