### ISSUE TITLE
get_web_site_container_logs_zip does not return all logs

### ISSUE THREAD

**Issue by heshamnaim** [Azure/azure-sdk-for-python#4126]
az webapp log download --resource-group {###} --name {###} returns a zip of container logs for at least the last 10 days, however when i use the python sdk get_web_site_container_logs_zip, I only get the last days. Any way to retrieve them all?

**Comment by lmazuel** [comment]
@yugangw-msft could you explain the black magic of the CLI?

**Comment by yugangw-msft** [comment]
CLI use the kudu endpoint: `https://<webname>.scm.azurewebsites.net/dump`

**Comment by heshamnaim** [comment]
@yugangw-msft how to I configure the azure sdk to utilize that endpoint?

**Comment by lmazuel** [comment]
@heshamnaim There is no Kudu SDK so far, you will have to do your own call using `requests` to it :(. I refer you to them to see how (and if possible) filter by period of time
https://github.com/projectkudu/kudu/wiki/REST-API

You might consider creating an issue to ask a Python SDK for Kudu, and further questions about Kudu:
https://github.com/projectkudu/kudu/issues

but that won't be our team to handle it, but the webapp team, so I can't give you more details unfortunately... :(

Closing, because we won't take action on it here, I wish I could provide a Kudu SDK...

**Comment by heshamnaim** [comment]
@lmazuel get_web_site_container_logs_zip actually doesn't return the full days logs, it only returns the last "page" as in if the logs span more than one .log file, you will only retrieve the last one. So there is no way to scan the full days logs. I feel like that is an issue with the sdk that should be addressed no?
