### ISSUE TITLE
ResourceManagementClient update_by_id() requires sku for Microsoft.Web/serverfarms resources

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-python#4148]
```
            generic_resource = GenericResource(location=az_resource.location,
                                               tags=tags,
                                               properties=az_resource.properties,
                                               kind=az_resource.kind,
                                               managed_by=az_resource.managed_by,
                                               identity=az_resource.identity)

                client.resources.update_by_id(resource['id'], api_version, generic_resource)
```

This code fails with `Error: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.Web/serverfarms/<appserviceplan>?api-version=2018-11-01` if we don't specify `sku` parameter. Works fine if we pass anything as a sku for `GenericResource`

I believe this code was working for AppServicePlans before.. So, looks like some regression.

You can see more details in related issue: https://github.com/cloud-custodian/cloud-custodian/issues/3327

**Comment by stefangordon** [comment]
Yeah so this is the update_by_id (patch) failing when we try to update tags on a service plan but succeeding on other resource types.  Is it safe to pass an empty `sku={}`? Is this expected?

**Comment by lmazuel** [comment]
Hi @stefangordon @logachev , sorry for the late answer. 
Did you change the api-version? I see you use 2018-11-01, which seems really recent to me, so when you say "this code was working [...] before", what is the exact scenarion?
If you change this api-version, that would be expected.
Thank you

**Comment by logachev** [comment]
Hi @lmazuel 
I just checked the old API and I was wrong -- it returns 400 Bad request either. (we used different API before, probably this is why I though it was working).

In that case, is it expected for `azure.mgmt.resource.ResourceManagementClient.update_by_id()` to fail, if `sku` parameter is not provided? (it is not required for a other resources we tested)

**Comment by lmazuel** [comment]
`update_by_id` is by design not tight to specific provider implementation, it's why the input class in `GenericResource` which means we cannot provide required/optional checking and will let the RestAPI raise an exception if the built payload is incorrect.

So your question should actually be: "Does the Microsoft.Web provider require a `sku` key for PATCH on serverfarms?" 

This is a service team question, so I'm not sure :/
Based on `azure-mgmt-web`, `sku` is not mentionned as a possible PATCH parameter:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-web/azure/mgmt/web/models/app_service_plan_patch_resource_py3.py

So to me the service team says in `azure-mgmt-web` that it's not required and should work (again, this is guess from me at this point).

@yugangw-msft @johanste any opinions here?

**Comment by stefangordon** [comment]
For context in this case, we only want to set generic resource fields - we really just want a reliable way to write tags to generic resources.

I went and looked at how the CLI does this - they do a GET and dump all that data into a PUT for `az resource tag` - which is something we tried originally and quickly dropped because it seemed like a bad idea (and in practice was destructive in production).  If I recall the main issues here are three fold
- If someone else is editing this resource you can overwrite them
- I think not all resource API's were reliably taking a PUT (vs patch) populated from a GET in a non-destructive way
- It is very expensive to have to individually call GET before every PUT for larger tagging operations in terms of both time and rate limits

Unless adding a null SKU to patch is a magical fix (unclear its safe/consistent across any generic ARM resource) it feels like an ongoing gap here? Setting generic fields/tags should be easy! :)

**Comment by lmazuel** [comment]
@ravbhatnagar what do you think?

**Comment by johanste** [comment]
All tracked resources must support PATCH of tags, no? I believe the problem is that there is no way to just add a single tag to the set of pre-existing tags on a given resource, thus the GET/PUT dance.

**Comment by logachev** [comment]
@lmazuel @johanste do you know if there was some progress with this issue?
