### ISSUE TITLE
python custom build scripts upgrade from 2.0 to 4.0

### ISSUE THREAD

**Issue by dikadali** [Azure/azure-sdk-for-python#4261]
```
vm.storage_profile.os_disk.managed_disk.id = new_os_disk.id
vm.storage_profile.os_disk.name = new_os_disk.name
computeclient.virtual_machines.create_or_update(
		'rgname',
		vm.name,
		vm
)

```
Above osdisk swap code works With Azure 4.0.0  successfully.
However, one of scripts are broken due to switch to Azure 4.0.0.
 
Eg.  consider following code - 
 disk_obj = ComputeManagementClient.disks.get(resgrp, name)
with Azure 2.0.0 “disk_obj” has attribute “account_type”, whereas, with Azure 4.0.0 it is no more attribute of “disk_obj”. 
There are multiple such examples.
 
1.Can you point me to the documentations that specifically talks about API changes and backward compatibility between Azure 2.0.0 and 4.0.0?
2.May I know any best practices/procedures to follow when we would upgrade from Azure 2.0.0 to Azure 4.0.0 is supported so that, old functionality is not broken?
3.Any other valuable recommendations to make this task simpler(or automated) would be greatly appreciated.

Thanks

**Comment by lmazuel** [comment]
Hi @dikadali 
ChangeLog are specific to service packages. From azure 2.0.0 to 4.0.0, you're moving from compute 3.0.0 to 4.0.0. Compute changelog will help:
https://pypi.org/project/azure-mgmt-compute/

Best practices would be to read the ChangeLog of each service you use, because "azure" is a rollup package but actually the changes depends a lot of the service involved.

Hope this helps! Let me know otherwise.

**Comment by dikadali** [comment]
Thank you
