### ISSUE TITLE
Help to developted azure python sdk.

### ISSUE THREAD

**Issue by SokolovVV** [Azure/azure-sdk-for-python#439]
Hi guys, how can i help with developing azure python sdk?
I work with sdk two weeks and i want help to developted this sdk.
Can i help?

About myself:
I am senior python developer from Russia, Moscow.
Work with python over 2 years, with MS .Net over 1.5 years.

**Comment by huguesv** [comment]
Thanks!  We have big changes in progress (https://github.com/Azure/azure-sdk-for-python/issues/440), and we'll need help testing the new packages once they are on PyPI.  After that, we can look at our TODO list (and storage's) and see if there's anything you can help with!

**Comment by lmazuel** [comment]
Hi,

I will close this post since this is not exactly an issue, this does not mean that you can't help :)
Since the new SDK is now Auto-generated, the best way to help currently is testing, to allows us to cover every kind of scenarios. You can do a PR from your fork and we will discuss around that.
Thank you for your support!
