### ISSUE TITLE
Azure loganalytics python SDK always throws MissingApiVersionParameter exception

### ISSUE THREAD

**Issue by dennissian** [Azure/azure-sdk-for-python#4544]
Original post was [here](https://stackoverflow.com/questions/55106788/azure-loganalytics-python-sdk-always-throws-missingapiversionparameter-exception?noredirect=1#comment96960450_55106788).

----
I try to follow MS official doc to get the log from my resource in Azure Log Monitor but never success. My code is like below.

```
from azure.loganalytics import LogAnalyticsDataClient
from azure.common.client_factory import get_client_from_cli_profile
from azure.loganalytics.models import QueryBody

log_client = get_client_from_cli_profile(LogAnalyticsDataClient)

myWorkSpaceId = '1234567890...'
result = log_client.query(myWorkSpaceId, QueryBody(**{'query': 'Heartbeat| limit 50'}))
```
And I always get exception like below:

```
result = log_client.query(myWorkSpaceId, QueryBody(**{'query': 'Heartbeat| limit 50'}))
File ".../lib/python2.7/site-packages/azure/loganalytics/log_analytics_data_client.py", line 121, in query
raise models.ErrorResponseException(self._deserialize, response)
azure.loganalytics.models.error_response.ErrorResponseException: (MissingApiVersionParameter) 
The api-version query parameter (?api-version=) is required for all requests
```

I trace code into library in /azure/loganalytics/log_analytics_data_client.py, and dump the url string used for query like below.

```
print(url, query_parameters, header_parameters, body_content)
request = self._client.post(url, query_parameters)
response = self._client.send(request, header_parameters, body_content, stream=False, **operation_config)

```

The output of the url and query information is like below and it look like no version information in between and I doubt this is why I get the exception: 
```
('https://management.azure.com/workspaces/1234567890.../query', {}, {'Content-Type': 'application/json; charset=utf-8'}, {'query': 'Heartbeat| limit 50'})
```

My azure SDK version is 4.0.0, and my azure-loganalytics library version is v0.1.0, running on Ubuntu. Does anyone run into same issue or know how to fix this?

Thanks.

**Comment by lmazuel** [comment]
@alexeldeib any idea? Because in your [query test](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-loganalytics/tests/recordings/test_query.test_query.yaml), there is no API version, so I'm quite confused about what is happening here? Is this an authentication problem with an incorrect message?

**Comment by alexeldeib** [comment]
@dennissian it's because of `get_client_from_cli_profile`:
```
log_client = get_client_from_cli_profile(LogAnalyticsDataClient)
```

This does two things which will cause issues for data plane calls: [uses management.azure.com as the authorization resource](https://github.com/Azure/azure-sdk-for-python/blob/b78a4fd36062b16a18980a5bfcdea4825b271ac5/azure-common/azure/common/client_factory.py#L37-L47), and[ sets the base_url](https://github.com/Azure/azure-sdk-for-python/blob/b78a4fd36062b16a18980a5bfcdea4825b271ac5/azure-common/azure/common/client_factory.py#L93) to the same. 

You can pass `base_url='https://api.loganalytics.io/v1` as a keyword argument to `get_client_from_cli_profile`, but the token resource will still be wrong. I think the best way is probably to do something like:

```
creds, _ = get_azure_cli_credentials(resource="https://api.loganalytics.io")
client = LogAnalyticsDataClient(creds)
```

@lmazuel modifying `get_client_from_cli_profile` to support a `resource` kwarg instead of using [this line](https://github.com/Azure/azure-sdk-for-python/blob/b78a4fd36062b16a18980a5bfcdea4825b271ac5/azure-common/azure/common/client_factory.py#L91) and [this function](https://github.com/Azure/azure-sdk-for-python/blob/b78a4fd36062b16a18980a5bfcdea4825b271ac5/azure-common/azure/common/client_factory.py#L37-L47) could work. I see Key Vault required some customization, could also go that route.

**Comment by alexeldeib** [comment]
BTW, the debug URL hints at the issue here: `https://management.azure.com/workspaces/1234567890.../query` doesn't have the structure of an Azure resource URL like `https://management.azure.com/subscriptions/GUID/resourceGroups/STRING/etc...`

**Comment by dennissian** [comment]
@alexeldeib @lmazuel
Thanks for your help, the provided solution can work.
