### ISSUE TITLE
Add support ReceiveBatch in servicebus.py

### ISSUE THREAD

**Issue by lezi226** [Azure/azure-sdk-for-python#459]
Hi, currently servicebus.py only support to get one message at a time. It's slow if I have many message to handle.
Can you add ReceiveBatch support? ReceiveBatch exist in C# library.

Thanks

**Comment by huguesv** [comment]
Unfortunately, in this case, there doesn't seem to be a REST API that provides batch receive.
https://msdn.microsoft.com/en-us/library/azure/hh780762.aspx

FYI: C# doesn't go through the REST API, that's why they are both faster and have a different set of functionality.

**Comment by lezi226** [comment]
Actually, I don't care about the underline transport. 
Why can't you change the transport to the one C# use to provider better functionality?

**Comment by huguesv** [comment]
If I was you, I wouldn't care about that either.  I reached out to someone from the service bus team to let them know about your request.  You're not the first to ask/complain about service bus REST API poor performance compared to C#.

**Comment by lmazuel** [comment]
Just had a discussion with the ServiceBus team. For problem around performance and missing features, the current recommendation from the ServiceBus team is to use AMQP instead of HTTP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/

The ServiceBus team were not able to propose better performance using HTTP, due to HTTP limit.
