### ISSUE TITLE
Error importing ComputerVisionAPI

### ISSUE THREAD

**Issue by RohitMungi-MSFT** [Azure/azure-sdk-for-python#4636]
It looks like in the new release of azure-cognitiveservices-vision-computervision the import of ComputerVisionAPI fails. 

Here is a reference to the original issue from [azure-docs](https://github.com/MicrosoftDocs/azure-docs/issues/27600)

It looks like the new import should be:
`from azure.cognitiveservices.vision.computervision import ComputerVisionClient`

Could you please document the same at [azure-cognitiveservices-vision-computervision](https://pypi.org/project/azure-cognitiveservices-vision-computervision/) page?

**Comment by lmazuel** [comment]
Hi @Rohit-MSFT 
You're right, the doc is not up to date. Note that I documented this change in the ChangeLog on PyPI:
https://pypi.org/project/azure-cognitiveservices-vision-computervision/

I'm closing your issue, because it's technically not a SDK issue (no changes are needed in this particular repo), the initial issue you created in the doc repo is the right one.

Thanks!
