### ISSUE TITLE
VM id and UUID are not the same

### ISSUE THREAD

**Issue by shawnswlin** [Azure/azure-sdk-for-python#4740]
This was found when I tried to get vm id with python sdk. The vm_id and system uuid are not the same. see as below

using python sdk
\>\>\> vm
<azure.mgmt.compute.v2018_10_01.models.virtual_machine.VirtualMachine object at 0x7ff5c9abcf10>
\>\>\> vm.vm_id
u'7cdc1f83-c56c-4e5e-9f1f-60b0072ec8e6'

using dmidecode 
root@vm:~# dmidecode -s system-uuid
831FDC7C-6CC5-5E4E-9F1F-60B0072EC8E6

This issue might be related to a bug: [[SRU] Handle changing UUID endian-ness on Azure in cloud-init](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1551419)

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by lmazuel** [comment]
Hi @shawnswlin 

I would suggest to open a support ticket on this one, since the Python SDK is just a messenger from RestAPI to Python: we don't post-process in anyways the `vm_id` and you get straight from RestAPI what was presented (and I have no context at the Python level to know what is right or wrong). Your command dmidecode is inside the VM, and out of scope of what I know.

Closing this issue out of scope of this SDK,
Thank you,
