### ISSUE TITLE
mocking a KeyVaultClient is difficult due to models / client_impl

### ISSUE THREAD

**Issue by avoltz** [Azure/azure-sdk-for-python#4743]
I am using pytest + mock to test a wrapper library which uses KeyVaultClient, but I ran into an issue mocking the KeyVaultClient class. The issue occurred moving from 0.3.7 to 1.1.0...

If you pass the KeyVaultClient as the spec, the spec is empty due to the way models pull in versioned model clients. I'd rather not use MagicMock for this, as it would not catch the case when we upgrade again and an api function goes away or changes. 

For now, I created this (kind of ugly) workaround:

```
@pytest.fixture
def mock_key_vault():
    # creating a dummy client will implement the api
    client = KeyVaultClient('cred', None)
    # this is gross, but the KeyVaultClient uses implementation models
    # grab one from the attribute on the client class
    client.get_secret
    return Mock(spec=client._client_impls.values()[0])
```

This fixture ensures that there is an implementation object which can be used as a spec, by accessing one of the attributes on the client object to construct it. 

I wonder, is there a better way to do this? 

Perhaps KeyVaultClient could add a classmethod to return a mockable client for testing like this? I'm wary of this fixture I wrote--I'm not sure if there may be multiple _client_impl objects which could be used by the client. It would be handy if I could change the fixture to something like:

```
@pytest.fixture
def mock_key_vault():
    return Mock(spec=KeyVaultClient.latest_api_impl())
```

Thanks for your help.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @schaabs

**Comment by chlowell** [comment]
I'm sorry this response has been so long in coming. I think your workaround is reasonable and don't know a better way to do it. The client should have exactly one implementation and if a test breaks due to the client loading an unexpected one, I'd call that a helpful test. Normally I would caution against relying on a private API like `_client_impls` but I think it's a small risk here because we don't plan to make major changes to `KeyVaultClient`. Our feature development is focused on the azure-keyvault-secrets, -keys, and -certificates packages, whose clients incidentally have static APIs and are therefore easier to mock and consistent across Key Vault versions. I suggest considering migrating to those packages. But if that migration is daunting and you don't need the latest Key Vault features, I think it's alright to continue with azure-keyvault 1.1.0 and this fixture.
