### ISSUE TITLE
Cannot receive messages from Service Bus persistent queue

### ISSUE THREAD

**Issue by haxoza** [Azure/azure-sdk-for-python#493]
Hi there!

What I want to to build is a simple listener using Service Bus persistent queue. Here is my code:

https://gist.github.com/haxoza/72e19c8522202a578b09

The code is pretty simple and looks fine according to the [examples](https://azure.microsoft.com/en-us/documentation/articles/service-bus-python-how-to-use-queues/).

Service Bus I'm connecting is created in my Azure account from the command line using ACS settings. Then I created a queue directly from the Azure panel. Afterwards I integrated the queue with Microsoft Dynamics CRM Online which sends messages on specific actions in the system. Now I want to receive those messages to process them.

However it looks like the code linked above cannot receive any message from the persistent queue. Here is what happens when the queue is not empty and I run the code:

```
$ python listener.py
INFO:__main__:Waiting for a message ...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): testnamespacexxx-sb.accesscontrol.windows.net
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): testnamespacexxx.servicebus.windows.net
Traceback (most recent call last):
  File "listener.py", line 23, in <module>
    message = service_bus.receive_queue_message(AZURE_SERVICE_BUS_QUEUE_NAME, peek_lock=True)
  File "/Users/haxoza/dev/virtualenvs/azure_service_bus/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 950, in receive_queue_message
    return self.peek_lock_queue_message(queue_name, timeout)
  File "/Users/haxoza/dev/virtualenvs/azure_service_bus/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 851, in peek_lock_queue_message
    response = self._perform_request(request)
  File "/Users/haxoza/dev/virtualenvs/azure_service_bus/lib/python2.7/site-packages/azure/servicebus/servicebusservice.py", line 1111, in _perform_request
    return _service_bus_error_handler(ex)
  File "/Users/haxoza/dev/virtualenvs/azure_service_bus/lib/python2.7/site-packages/azure/servicebus/_serialization.py", line 579, in _service_bus_error_handler
    return _general_error_handler(http_error)
  File "/Users/haxoza/dev/virtualenvs/azure_service_bus/lib/python2.7/site-packages/azure/servicebus/_common_error.py", line 47, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
AzureHttpError: Internal Server Error
<Error><Code>500</Code><Detail>The server was unable to process the request; please retry the operation. If the problem persists, please contact your Service Bus administrator and provide the tracking id. TrackingId:c570939b-5709-46c7-b4ec-ba6ebc5ed7d1_G41,TimeStamp:10/16/2015 8:36:24 AM</Detail></Error>
INFO:__main__:Waiting for a message ...
```

For some reason Azure replies with 500 error on its end and no message is returned.

What's more interesting when I run similar program in C# based on the [examples from the SDK](https://msdn.microsoft.com/en-us/library/jj899557.aspx) it works like a charm receiving the messages from the queue.

Any idea what is causing the issue? Maybe Python Service Bus SDK expects different queue contract than persistent queue? Is that possible?

Looking forward to hearing from you! And thanks for building Python SDK!

**Comment by huguesv** [comment]
Hi haxoza,

This is a new error that I've never seen reported here before.

I'm also not familiar with the term "persistent queue", which is used in the Dynamics CRM docs. I don't know if it's something new or just a different term for what we've always had.  I requested some assistance from the service bus team.

If at all possible, I would suggest you try it out with the node.js sdk, to see whether it works with it or not.  The node.js sdk implements the same REST API as the python sdk. The C# implementation is completely different and has more functionality.

Another user here had to manually set a listen policy in order to successfully receive messages from Python.  Check the last post.  No idea if that's related to your issue.  
https://github.com/Azure/azure-sdk-for-python/issues/430

**Comment by huguesv** [comment]
It looks like we'll need to look at logs of the http traffic in order to diagnose the issue.  You can use fiddler (with decrypt https traffic option) to capture those (I'm not sure of what equivalent traffic capture app can be used on Linux or OS X).

On the `ServiceBusService` class, you can call `set_proxy('localhost', 8888)` to have it go through fiddler.

Once you have the log, you can email them to `'hu' + 'valo' + '@microsoft.com'` and I'll forward that to the service bus team.

**Comment by michaelarnauts** [comment]
I have the same issue with the PHP SDK, also with processing messages from Dynamics CRM. The Service Bus Explorer is displaying the messages fine, but the PHP SDK (and it seems the python sdk also) isn't. I've also noticed that it seems to be related with the `CorrelationId` property. When I manually resubmit a message to a different queue, and leave out the `CorrelationId`, the messages is returned fine.

This seems to be a bug in the Service Bus itself, or maybe with Dynamics CRM that is creating wrong messages somehow?

**Comment by lmazuel** [comment]
Just had a discussion with the ServiceBus team. The current recommendation from the ServiceBus team is to use AMQP instead of HTTP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/
