### ISSUE TITLE
The Deployments of hosted_service is NULL? Could you please fix that

### ISSUE THREAD

**Issue by kingliantop** [Azure/azure-sdk-for-python#502]
Hi,

I try to iterate all my hosted services and deployments, while I find the Deployments of hosted_service is NULL:

result = sms.list_hosted_services()
for hosted_service in result:

{......, 'deployments': None, ......}

Thanks!

**Comment by huguesv** [comment]
I don't think that the REST API for list hosted services is capable of returning that data.
https://msdn.microsoft.com/en-us/library/azure/ee460781.aspx

I know you can use `get_hosted_service_properties(service_name, embed_detail=True)` as in this test:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicemanagement-legacy/tests/test_legacy_mgmt_misc.py#L783

The reason you are seeing deployments field at all when calling `list_hosted_services` is because the same model class is shared between both APIs.

**Comment by lmazuel** [comment]
Hi,

Thank you for your report. I agree with @huguesv, `deployments` will only be filled if you use `embed_details` in `get_hosted_service_properties`, as the Azure documentation says:

https://msdn.microsoft.com/en-us/library/azure/ee460806.aspx
```
embed-detail=true: Optional. Specifies that properties should be returned for all deployments in the cloud service.
```

But I agree that the docstring of `list_hosted_services`  should be implicit on this point since we return a `deployments` property on the result. I will update that asap.

**Comment by lmazuel** [comment]
Documentation update
https://github.com/Azure/azure-sdk-for-python/pull/506
