### ISSUE TITLE
Is Azure DNS supported?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-python#508]
I use Azure DNS to create and modify DNS zones and records hosted within Azure.
https://msdn.microsoft.com/en-us/library/azure/mt163862.aspx

It seems that azure-sdk-for-python does not support Azure DNS, right?

**Comment by lmazuel** [comment]
Hello,

The legacy API is not able to handle Azure DNS. But the ARM version of the library provided with the Python SDK 1.0 will allow you to do this. You will have to build a AzureDNS template in JSON, for instance:
https://github.com/Azure/azure-quickstart-templates/tree/master/101-azure-dns-new-zone

And to use it as a template using the ARM library:
https://azure-sdk-for-python.readthedocs.org/en/latest/resourcemanagement.html#create-deployment-from-template

Please note that the ARM Python API is in preview in the SDK 1.0 and should change in the beginning of 2016. But since you will using the ARM JSON template model (so the complex part will be in JSON, not in Python), code adaptation should be minor.

At the end, we should have a direct AzureDNS Python API (without JSON needed), but I'm not able to give you an estimated date.

**Comment by bingosummer** [comment]
Thanks @lmazuel 
I believe that a direct AzureDNS Python API is better since it allows me not only to create Azure DNS, but also to query the information (e.g. domain name server name) of Azure DNS.

**Comment by bviktor** [comment]
I see 2.0.0rc3 is out, is there any update on this?

**Comment by lmazuel** [comment]
Hi @bviktor 

The DNS service is not yet available, but the Swagger meta-description used to generate it is in progress:
https://github.com/Azure/azure-rest-api-specs/pull/278

Once this file is published, we would be able to publish a DNS preview for Python soon after.

**Comment by bviktor** [comment]
Thanks, Laurent!
