### ISSUE TITLE
Error: Connection reset by peer  and Queries on new version of Python SDK for Azure

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-sdk-for-python#509]
-	I was using Azure service management SDK (v0.11.1) to create VM’s and was intermittently getting “Connection reset by peer”.

-	I have seen similar issue being resolved with new version of SDK as specified inlink : https://github.com/Azure/azure-sdk-for-python/issues/304

 We really want to transfer to the azure-sdk-for-python V2.0, but as the architecture changed, we still have some problems should be solved before that, wish your suggestions.
1.	We have defined some self-defined images base on public provider, but the python SDK for V2.0, we could only search image by publisher, sku etc, how could use self-defined image?
2.	For V1.0 we have cloud service and we can include the VMs which have the same function in it, and then with the Virtual Network and Sub Network, we could make all roles between cloud service transfer data via private IPs, For V2.0, we do not sure how to use it yet.

For existing Connection reset by peer issue, we just want to know if there has any max parallel connections or timeout limits, As we also meet this error when try to connect to Service Bus, we want to find the root cause and avoid it.

**Comment by lmazuel** [comment]
If you use the old API in production, I think you should wait before doing anything, because:
-	The “old” API is legacy, and anyway in the SDK 1.0 there is some package name changes
-	The ARM SDK is in preview and will change with the final release.
So, in both situations, trying to adapt will imply using API that will change (I can’t give you a date sorry)

But, I’m wondering if the problem should come from external libraries like `requests`. The last version 2.9.1 works nice with a new `urllib3` library embedded. It should help.

**Comment by lmazuel** [comment]
For ServiceBus, just had a discussion with the ServiceBus team. For problem around performance and missing features, the current recommendation from the ServiceBus team is to use AMQP instead of HTTP:
https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-python/

The ServiceBus team were not able to propose better performance using HTTP, due to HTTP limit.

For ServiceManagement, connection problem is something that could appear and should be solved in the ARM version.

I close this issue since I think it's not still accurate, please feel free to open a new issue if necessary.
Thanks!
