### ISSUE TITLE
[Azure.Core] Provide common configuration store for process-wide configuration values

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#5126]
Some settings are 'global' in the sense that it makes sense to share the same value for all instances of all clients:

[ ] Log level for the 'azure' root logger
[ ] Proxy settings
[ ] Telemetry enabled/disabled
[ ] Tracing enabled/disabled

azure-core should provide entry points for getting/setting these shared configuration values. Default values (values not explicitly specified) can be specified using environment variables.

See https://github.com/Azure/azure-sdk/pull/328 for more details.

**Comment by bryevdv** [comment]
@johanste What re:

>The Azure SDK can be configured by a variety of sources, some of which are necessarily language-dependent
>
>	1. System settings
>	2. Environment variables
>	3. Global configuration store (code)
>	4. Runtime parameters

What does it mean for a library (in Python, at least) to be configured by runtime parameters? I would expect those only to enter in to play at the application level, and that a the application would be responsible for preferring runtime args (because only the app knows what those flags are and how to get them) in favor of a `Settings` object. 

That is, I'd normally only expect a `Settings` object to be responsible for mediating 1-3 and that an application would be responsible for mediating between `Settings` and 4

**Comment by xiangyan99** [comment]
merged
