### ISSUE TITLE
The error thrown by run() is wrong when the port is blocked

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#5309]
@settlersxp commented on [Tue Apr 02 2019](https://github.com/Azure/azure-event-hubs-python/issues/102)

https://github.com/Azure/azure-event-hubs-python/blob/737c5f966557ada2cf10fa0d8f3c19671ae96348/examples/send.py#L36

The error shown is "Please confirm target hostname exists" which is incorrect after a very long wait time. Probably the wait time is equal to the timeout I have set, did not bother to check.

Steps to reproduce:
1) Set valid azure credentials and project information
2) Do not set a proxy
3) Block with a firewall the ports 5671 and 5672
4) Try to open a new consumer and notice that the error message is "Please confirm target hostname exists"  instead of anything related to blocked ports.

---

@annatisch commented on [Tue Apr 02 2019](https://github.com/Azure/azure-event-hubs-python/issues/102#issuecomment-479033727)

Thanks for this report @settlersxp!
I would say it's likely that the underlying error raised if the same in this case (something like "endpoint could not be reached") - which is why it isn't distinguished.
I'll see if there's anything that can be done at the uAMQP level to address this :)

---

@settlersxp commented on [Tue Apr 02 2019](https://github.com/Azure/azure-event-hubs-python/issues/102#issuecomment-479043433)

Makes sense, if it's difficult to distinguish the two errors adding the bit with "or make sure the ports 5671 and 5672 are open in the firewall" should do the trick. Afterall some techy people will use the SDK, there is some tolerance to debug and workarounds.

**Comment by sandy-lcq** [comment]
@yunhaoling , Hi,  I still met similar error with read_device_to_cloud_messages_sync.py under iot-hub/Quickstarts/read-d2c-messages

when run above scripts, below error printed:
EventProcessor instance '38b7c210-6a89-4252-a91c-9a74163b785b' of eventhub 'iothub-ehub-iotzy-5817228-77db27f20f' consumer group '$Default'. An error occurred while load-balancing and claiming ownership. The exception is AuthenticationError("Unable to open authentication session on connection b'82aba880-ede3-4af4-a01b-c95879831eab'.\nPlease confirm target hostname exists: b'ihsuprodkwres038dednamespace.servicebus.windows.net'\nUnable to open authentication session on connection b'82aba880-ede3-4af4-a01b-c95879831eab'.\nPlease confirm target hostname exists: b'ihsuprodkwres038dednamespace.servicebus.windows.net'"). Retrying after 11.374749498916175 seconds
An exception: Unable to open authentication session on connection b'82aba880-ede3-4af4-a01b-c95879831eab'.
Please confirm target hostname exists: b'ihsuprodkwres038dednamespace.servicebus.windows.net'
Unable to open authentication session on connection b'82aba880-ede3-4af4-a01b-c95879831eab'.
Please confirm target hostname exists: b'ihsuprodkwres038dednamespace.servicebus.windows.net' occurred during the load balance process.

I  am sure that my connect string is correct,  I copy it from portal web. 
I tried both 2 shared access key:   sercvice and iothubowner.   All have this error.   

Could you give some hint about  how I debug what is the real problem?  I run read_device_to_cloud_messages_sync.py on ubuntu 18.04,  and I don't enable firewall on my host,  so I guess it should not because port 5671 and 5672 is blocked by firewall.  

Thanks

**Comment by sandy-lcq** [comment]
@yunhaoling  

I also met below error during send_c2d_message:

    if not self._client_ready():
  File "/azure/venv/lib/python3.8/site-packages/uamqp/client.py", line 525, in _client_ready
    self.message_handler.open()
  File "/azure/venv/lib/python3.8/site-packages/uamqp/sender.py", line 211, in open
    raise errors.AMQPConnectionError(
uamqp.errors.AMQPConnectionError: Failed to open Message Sender. Please confirm credentials and target URI.

my connect string is correct, since I can use that to handle direct method test.
