### ISSUE TITLE
"Top" for listing resource groups doesn't work

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-sdk-for-python#541]
rmc = ResourceManagementClient...
rmc.resource_groups.list(top=1)

returns all groups.  Should return just top 1

**Comment by lmazuel** [comment]
@annatisch ? What do you think?

**Comment by annatisch** [comment]
Are you able to give us the complete URL that's used to make the request?
This should be logged in debug.

**Comment by BurtBiel** [comment]
Here's one: https://management.azure.com/subscriptions/<subID>/resourcegroups?api-version=2015-11-01&%24top=1&%24filter=tagname+eq+%27Arm%27&%24skiptoken=<token>0%3d HTTP/1.1

For some reason the request is also very slow when Top is used

**Comment by annatisch** [comment]
Thanks!
I suspect that these query parameters are being url-encoded when they're not supposed to be.... I will investigate.

**Comment by lmazuel** [comment]
Hi @BurtBiel @annatisch 

I was curious to investigate this one, so I just try.
In fact, there is a problem around what `top` semantic is. The REST API consider that `top` is the number of elements in each page. I agree that the doc is not explicit on this:
https://msdn.microsoft.com/en-us/library/azure/dn790529.aspx

But even with `top=2`, you get the `nextLink` link to get another page of 2 elements and so on.

I think the purpose of `top` is for paging in websites scenario (do not load all pages, load 10 elements and load the others when the user scroll down). One point in that way is that you do not have a `order by` keyword. What is the point to get only 2 random elements? Every limit system comes usually with a "order by" counterpart.

So, doing:
```python
elements = list(rmc.resource_groups.list(top=1))
```
will always get to the entire list, it's just the number of HTTP request under the hood that will change.

If you really want only one random element, you could do that:
```python
elements = rmc.resource_groups.list(top=1).next()
```
which will return only 1 element (i.e. the first page)

I agree that the documentation is not helping here, it's because the gap between the `top` semantic in the REST API and what people expect in Python since @annatisch created an automatic paging class.

**Comment by lmazuel** [comment]
For the record, website ARM API is not clear:
```pytohn
top (str) – List page size. If specified, results are paged.
```

**Comment by lmazuel** [comment]
I close this issue, please feel free to reopen it if you have additional questions!
