### ISSUE TITLE
Return Virtual Machine Instance View from list() or list_all() methods

### ISSUE THREAD

**Issue by chouseknecht** [Azure/azure-sdk-for-python#573]
Is there a way to get an instance view returned from the list() or list_all() methods of the VirtualMachineOperations class?

Building the Azure inventory script for Ansible. Fetching the list of machines for a subscription of for a specific resource group returns data within 3 or 4 seconds. However, the machine objects do not include the instance view and thus no power state information. To get that information I'm calling the get() method for each machine and providing an expand parameter value of 'instanceView', which makes the overall process very slow.

Is there a more efficient way to do this?

**Comment by lmazuel** [comment]
It seems that the REST API itself does not provide this feature:
https://msdn.microsoft.com/en-us/library/azure/mt163572.aspx

@devigned do you have someone in the Compute team which can help us here? The SDK 2.0.0rc2 is using the 2016-03-30 Swagger file.

**Comment by chouseknecht** [comment]
Any insights on this one?

**Comment by krushmike** [comment]
I agree completely on this!  Having to call VirtualMachines.Get on every machine in a LIst() is terribly inefficient and very slow.  Been over a year and no progress :-(

**Comment by devigned** [comment]
@squillace what do you think about making this happen?

**Comment by pparamalingam** [comment]
Is this feature still being considered to be added to the REST API?

**Comment by jogipraveen** [comment]
I'm trying to fetch the VM instances with the status. It would be great if we get the all VM details (VM size, memory, IP, status, etc..) in one place.

**Comment by devigned** [comment]
@squillace or @singhkays any feedback on this issue?

**Comment by singhkays** [comment]
@nibhat should be able to answer decisively once he's back from leave but I haven't heard anything about this being considered as an add to the REST API over the many other priorities for the Compute team.

**Comment by devigned** [comment]
Thank you, @singhkays!

**Comment by davidbairdala** [comment]
Has there been any progress on this issue, or is anyone from Microsoft able to comment on this? I see that the REST [(documentation)](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/listall#virtualmachine) for List All virtual machines now includes in results 'properties.instanceView', but when I call this api directly the instance view is not returned.

**Comment by squillace** [comment]
apologies, @davidbairdala I'll ping the appropriate people. I'm not the one to handle it.

**Comment by davidbairdala** [comment]
Thank @squillace

**Comment by squillace** [comment]
@lmazuel can you have a look? Thanks so much.

**Comment by lmazuel** [comment]
As far as I know, this is still not supported. We are investigating alternative ways, but nothing solid enough to be documented and suggested yet.

**Comment by ioannisas** [comment]
This would be a really nice enhancement to have. It's impossible, as far as processing time is concerned, to have the power state along with other VM info. Any update on this?

**Comment by jpdiazsidaras** [comment]
Hey Team! I'm doing some report right now, using PowerBI and the Azure API's, It will be great, if the status of the machine cannot be added to the standard ListAll VMs call, at least have a ListAll for the instaceView, so you can call all the instanceView at once and after that cross the information. Thanks!

**Comment by ricardobranco777** [comment]
Adding this would benefit the cli as well.

**Comment by woosley** [comment]
I want this too, because i have to create new http for every VM to get the instanceView, which makes the program very slow.

**Comment by shandilvarun** [comment]
To get the power state for the instances in bulk you can use following CLI option. 

az vmss list-instances --expand instanceView --select instanceView --resource-group <resourceGroupName>  --subscription <subID>  --name <vmssName>

**Comment by lmazuel** [comment]
Hi @shandilvarun 
Thank you for your answer, but first this is the SDK repo, so the CLI command doesn't answer the question, and second this CLI is looping through every instances to get the instanceView, then it's not a bulk call. CLI is using this very SDK to do the call and has the same internal limitation.

**Comment by mobilemeneer** [comment]
Good request. Having to query all vm's and then the instanceviews per vm to get the powerstate takes too long. Please add the instanceview to the list or listall. That will make things easier and much faster.

**Comment by welabbar1** [comment]
I am bumping this as well. Please consider this!

**Comment by jjohndrow** [comment]
I think this feature needed and I have for a long time. Right now if you need to do this through the API you have to make n+1 API requests where n is the number of VM's. This means if you have 500 VM's, 501 API calls are made to list and get each machine instead of a big paginated list.  Is there somewhere else this issue lives as well? This is an deeper issue than just python SDK. We use the rest service exclusively these days and would love to see this resolved.

**Comment by welabbar1** [comment]
I wonder now... Is this why the power state of the VMs is always slow  and lagging behind when you get the full list of VMs on the AzureStack portal??? 😬😬😬

**Comment by welabbar1** [comment]
I have managed to workaround this using:

1.  Flask-SocketIO to emit a dictionary of VM information ( list_all().next().as_dict() ) to the frontend's knockout JS observables (name, rg, type, size, subid, status showing loading gif, and extensions showing loading gif)

2.For every VM that gets processed, it would immediately write a row in the paginated jQuery Datatable to display to the user immediately and make an asynchronous AJAX call with the parameters of vmname, vmrg, region, and subid to the "vmstatus" api that i have waiting in Flask.

3. When the AJAX response is received, the results are imposed on the respective knockout observable for the VM and the DataTable rows are invalidated in order to replace the loading gif with the required information (datatable.rows().invalidate())

The experience is exactly like the one using the Ibiza portal. The user gets, what appears to be, an immediate response I am quite happy with it!

**Comment by prajaktasd** [comment]
Is this resolved yet or one still needs to perform get call by lopping over the list of vms to get the status.

**Comment by edrogers** [comment]
For those looking to get the instance status for all VMs without having to make API calls for each VM one-by-one, I had success using the [`ComputeManagementClient.virtual_machines.list_all(status_only=True)`](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.operations.virtualmachinesoperations?view=azure-python#azure-mgmt-compute-v2022-08-01-operations-virtualmachinesoperations-list-all) method. (Surprising to see this issue was closed without mentioning it.)

Hope that helps!

**Comment by ricardobranco777** [comment]
> For those looking to get the instance status for all VMs without having to make API calls for each VM one-by-one, I had success using the [`ComputeManagementClient.virtual_machines.list_all(status_only=True)`](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.operations.virtualmachinesoperations?view=azure-python#azure-mgmt-compute-v2022-08-01-operations-virtualmachinesoperations-list-all) method. (Surprising to see this issue was closed without mentioning it.)
> 
> Hope that helps!

This only returns the statuses but not the instance views.

**Comment by davidbairdala** [comment]
If you are wanting to get instance view properties for a list of VMs in an efficient manner you might consider just using the Graph API instead (see https://learn.microsoft.com/en-us/graph/use-the-api)

**Comment by zsandrus** [comment]
> For those looking to get the instance status for all VMs without having to make API calls for each VM one-by-one, I had success using the [`ComputeManagementClient.virtual_machines.list_all(status_only=True)`](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2022_08_01.operations.virtualmachinesoperations?view=azure-python#azure-mgmt-compute-v2022-08-01-operations-virtualmachinesoperations-list-all) method. (Surprising to see this issue was closed without mentioning it.)
> 
> Hope that helps!

Thanks, this works for my use case. It's still one additional call, but that's better than one call per VM.
