### ISSUE TITLE
Service Bus message direct to Dead Letter with message and stack trace is missing

### ISSUE THREAD

**Issue by grayjeremy** [Azure/azure-sdk-for-python#5749]
There is no method or example to send a message directly to a dead letter queue.  The .net sdk has a DeadLetter method that accepts a reason and a stacktrace.  If this exists, I can't find it and we need some examples or how to deal with error logic. 

The case here is a malformed message that will never be able to process doesn't need to be retried 10 times.  Those 10 retries can incur expense in other services and are wasteful in a consumption environment.  

I should be able to create an Azure Function in python, import the azure.service bus python package and do msg.dead_letter("reason",stacktrace/additional info) and have the message go directly to the SB's dead letter queue.

**Comment by lmazuel** [comment]
@annatisch ?

**Comment by KieranBrantnerMagee** [comment]
Hey Gray; 
Sorry this fell through the cracks, but in the hope of providing some breadcrumbs, if only for others who see this thread:

There seem to be two sub-points to be touched on here, and I'll address them both.
1. Immediate deadlettering.  Per your example (msg.dead_letter) that's precisely the API we currently offer.  While I'll be the first to admit in grepping around for pointers for this that we don't seem to have obvious docs for this scenario, (We're bolstering them substantially for our upcoming GA release) I'd point you at this sample for deferral [here ](https://github.com/Azure/azure-sdk-for-python/blob/300d00e56a80711230902fcd285e347ac0de121b/sdk/servicebus/azure-servicebus/samples/sync_samples/test_examples.py#L333)and mention that the dead lettering pattern is isomorphic, per the function defined [here](https://github.com/Azure/azure-sdk-for-python/blob/300d00e56a80711230902fcd285e347ac0de121b/sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py#L331)
2. Dead lettering with both a description and reason parameter.  We currently only support Description; This is a known bug in the underlying UAMQP implementation that we're currently addressing in that lib, and hope to have included for the final 0.50.3 release.  (Final due to that the 0.* lib is being deprecated as we roll out the GA release, version 7.0.0, currently in preview.  Kindly excuse the large version gap, it's to align with other MS SDKs.)

Closing this for now assuming the above should cover all our angles, but if there's any further issue/bits that need clarification, don't hesitate to reach out and/or reopen.

**Comment by zargaryanlilit** [comment]
I've encountered the same issue, but when trying to dead_letter, I get this error. Result: Failure Exception: AttributeError: 'ServiceBusMessage' object has no attribute 'dead_letter'. 
For python runtime, we cannot set autocomplete to false and deadletter the message either using ServiceBusReceiver because the message is not of type ServiceBusReceivedMessage or directly calling the method on the object as object has no attribute 'dead_letter'.
