### ISSUE TITLE
Resource group deployment failures don't return error text 

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-sdk-for-python#592]
Deploy an ARM template for VM Create and choose a password of "123".  

Expected: Password is too weak message (error message from Azure)

Actual: Long running operation failed (no details about what actually went wrong)

Note: running the SDK at the Debug log level shows that the error message is indeed sent down in the response, but it is not surfaced to the user.

**Comment by lmazuel** [comment]
Hi @BurtBiel 

If you get a CloudError exception, this should contains the response as attribute I think?

I check that asap.

**Comment by lmazuel** [comment]
Hi @BurtBiel 

The exception you got has a `message` attribute:
![image](https://cloud.githubusercontent.com/assets/1050156/15157095/e858c098-169e-11e6-96be-1cff4ddf660a.png)

You also have the `response` attribute with the full response:
![image](https://cloud.githubusercontent.com/assets/1050156/15157125/0bc4696a-169f-11e6-8857-7c6417157e04.png)

I close this bug since I think I answered your question, please feel free to open it again if it's not enough.
Thanks!

**Comment by BurtBiel** [comment]
Hi Laurent,

I don’t have permissions to re-open the issue, but here is what I found.

To get at the useful error message (detail of what went wrong instead of ‘deployment failed’), I have to do this:

message = json.loads(json.loads(json.loads(client_exception.error.content.decode("utf-8"))['error']['details'][0]['message'])['error']['details'][0]['details'][0]['message'])['error']['message’]

Is this different in recent SDK versions?  If not, it would be great to get this error surfaced as a first class property.

Thanks!

Burt

**Comment by lmazuel** [comment]
@annatisch Do you know why there is so much level here?

**Comment by annatisch** [comment]
Eek, that certainly is well buried... I will investigate!

**Comment by lmazuel** [comment]
@obsoleted, is this a reason why you decided to do a recursive lookup in the Ansible module?
https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/azure/azure_rm_deployment.py#L527

**Comment by obsoleted** [comment]
I think I was just copying logic I found in azure cli (https://github.com/Azure/azure-xplat-cli/blob/dev/lib/commands/arm/group/groupUtils._js#L406). I assumed it is because the deployment fans out into so many operations each of which can have their own failures (and perhaps sub operations?). But I honestly didn't look that closely at the resulting format as I mostly cared that we weren't loosing any error information that could be returned back.

**Comment by lmazuel** [comment]
Fixed by https://github.com/Azure/autorest/pull/1300
