### ISSUE TITLE
from azure.servicebus import ServiceBusClient does not work

### ISSUE THREAD

**Issue by larsoleruben** [Azure/azure-sdk-for-python#6263]
Hi
I installed the complete Azure SDK by **pip install Azure**
Then this:
from azure.servicebus import ServiceBusClient does not work
from azure.servicebus..control_client import ServiceBusClient does not work
On windows 8.1 I have python 3.7 and "pip install Azure"
All I can import is ServiceBusService!
I then made a new environment and **pip install azure-servicebus==0.50.1**
And now I can import as per **your tutorial?**
I tried to install the azure_servicebus in the Azure 4.00 env, but could not? (I needed azure_servicebus 0.2xx)

**Comment by lmazuel** [comment]
Hi @larsoleruben 
The `azure` meta-package we don't release very often, since it's consider a quickstart with some basic packages. The latest one is bringing `azure-servicebus` 0.21.x, which does not contain the `control_client` module.
Indeed, if you install the package directly, you will get the latest version that correspond to the tutorial, version 0.50.0

If you need for some reasons to stick to 0.20.x, this tutorial might help:
https://github.com/Azure/azure-sdk-for-python/blob/azure-servicebus_0.21.1/doc/servicebus.rst

Does that answer your question?
Thank you

**Comment by annatisch** [comment]
Looks like this is now resolved - let me know if I need to re-open :)
