### ISSUE TITLE
failed to create credential

### ISSUE THREAD

**Issue by zhaojohn** [Azure/azure-sdk-for-python#630]
I am using Python 2.7.9 and current Azure SDK.   When I tried to get credentials, I got the following error.

from azure.common.credentials import UserPassCredentials
UserPassCredentials('myaccount', 'mypassword',)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/share/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 336, in __init__
    self.set_token()
  File "/usr/share/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 371, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/share/lib/python2.7/site-packages/msrest/exceptions.py", line 50, in raise_with_traceback
    raise error
AuthenticationError: , InvalidGrantError: (invalid_grant) AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
Trace ID: 99d27b27-e4d4-4862-b409-d4dfb5fbd5e7
Correlation ID: c4c9d302-a5ba-41f5-acfc-ae63e2fa581c
Timestamp: 2016-06-16 19:38:54Z

**Comment by prashanthmadi** [comment]
https://azure-sdk-for-python.readthedocs.io/en/latest/resourcemanagementauthentication.html
has the sample code zhao is refeering and username,password is not a recommended approach

Below code works

```
from azure.common.credentials import ServicePrincipalCredentials

credentials = ServicePrincipalCredentials(
    client_id = 'ABCDEFGH-1234-ABCD-1234-ABCDEFGHIJKL',
    secret = 'XXXXXXXXXXXXXXXXXXXXXXXX',
    tenant = 'ABCDEFGH-1234-ABCD-1234-ABCDEFGHIJKL'
)
```


below link has details on how to get client_id, secret and tenant. 

https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/

**Comment by zhaojohn** [comment]
got a different error this time.
from azure.mgmt.authorization import AuthorizationManagementClient
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource.resources import ResourceManagementClient

credentials = ServicePrincipalCredentials(
    client_id = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    secret = 'XXXXXXXXXXXXXXXXXXXXXXXX',
    tenant = 'XXXXXXXX"
)
authorization_client = AuthorizationManagementClient(
    credentials,
    subscription_id
)


resource_client = ResourceManagementClient(
    credentials,
    subscription_id
)
resource_client.providers.register('Microsoft.Authorization')



CloudError: The client 'xxxxxx' with object id 'xxxxxx' does not have authorization to perfor
m action 'Microsoft.Compute/locations/publishers/read' over scope '/subscriptions/xxxxxxxxxxxxxxxxx'.

**Comment by zooba** [comment]
(On a vaguely related note - why validate credentials on construction? We should really wait until they're used, or provide a function to create the credentials rather than instantiate a class...)

**Comment by zhaojohn** [comment]
I am switching from AWS to Azure, so try to validate the login and set up the dev environment.

**Comment by lmazuel** [comment]
Hi @zhaojohn 

You have role problem with your account used for the connection:
https://azure.microsoft.com/en-us/documentation/articles/role-based-access-control-configure/

According to this:
https://azure.microsoft.com/en-us/documentation/articles/role-based-access-built-in-roles/

You need to add “Reader” or “Virtual Machine Contributor” role to the user you use to connect.

**Comment by lmazuel** [comment]
Hi @zhaojohn 

@prashanthmadi just told me that that the above links solved your problem. Then, I close this issue. Feel free to open new issue if necessary.

Thank you,

**Comment by songyangeric** [comment]
Hi, @lmazuel 
I encountered this login issue recently. I am now using my corp's account to login Azure. Both the username and the password match my corp's account. The error message is like below:

  File "/home/songe1/.local/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 335, in __init__
    self.set_token()
  File "/home/songe1/.local/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 370, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/home/songe1/.local/lib/python2.7/site-packages/msrest/exceptions.py", line 50, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , InvalidGrantError: (invalid_grant) AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
Trace ID: 6cff533a-2895-4a51-990e-f5873565d679
Correlation ID: 72dff910-2c2e-4709-855e-fe8c1bd7ac5e
Timestamp: 2016-12-14 02:44:32Z

My account is not granted the permission to create Service Principal so that I can't try the way prashanthmadi suggested. How should I manage the permission if I want to use UserPassCredentials to login? I read the comment you gave above, but I find it deals with the access permission for resource groups. When we use UserPassCredentials to login, we do not deal with resource group immediately, is that right?

Hope for your reply. Thanks.

**Comment by lmazuel** [comment]
Hi @songyangeric 

You cannot connect using corp and `UserPassCredentials`, this is a limitation. Please connect using ADAL:
https://github.com/AzureAD/azure-activedirectory-library-for-python

And then use the ADAL wrapper to get a valid credentials instance:
http://azure-sdk-for-python.readthedocs.io/en/latest/quickstart_authentication.html#using-adal
