### ISSUE TITLE
Azcopy sync support

### ISSUE THREAD

**Issue by wewark** [Azure/azure-sdk-for-python#6306]
I am currently using the command `azcopy sync` by running it as a command inside my program, is there something in the sdk that is similar to it? If not, I think there should be.

**Comment by wewark** [comment]
Also, the `azcopy cp` command to copy from one container/account to another. I mean the whole Azcopy functionalities should be available in the sdk, this is useful for interaction with the UI like progress bars, I can't make a progress bar when running them as commands.

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.
CC: @lmazuel

**Comment by zezha-msft** [comment]
@wewark thanks for reaching out!

You could actually use the flag `--output-type=json` to get updates that can be parsed and report the progress in your UI. AzCopy is integrated into other tools this way.

We do have an item in the backlog to provide a Python wrapper to the tool, so that it's easier to leverage it, but unfortunately I don't have an ETA right now.

**Comment by zezha-msft** [comment]
Tracking here: https://msazure.visualstudio.com/One/_workitems/edit/5355751

**Comment by tasherif-msft** [comment]
Duplicate https://github.com/Azure/azure-sdk-for-python/issues/14433

**Comment by tasherif-msft** [comment]
We have added this to our future backlog. I will close this issue.
