### ISSUE TITLE
PowerBI embedded preview client

### ISSUE THREAD

**Issue by chuckus** [Azure/azure-sdk-for-python#635]
In the next release candidate, could you be able to add a PowerBI embedded preview client please?

I have attempted to do it myself. I used Docker to pull `azuresdk/autorest:latest` and the [latest PowerBI embedded swagger specs as of today](https://github.com/mattmazzola/azure-rest-api-specs/blob/63f0ba43360ec396eba6f84f1f7ea697f68c7aa8/arm-powerbiembedded/2016-01-29/swagger/powerbiembedded.json) to generate an Azure.Python client, but the interface does not match the current python-sdk RC4.

**Comment by lmazuel** [comment]
Hi @chuckus !

I will check the state of the file ([the official is this one](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-powerbiembedded/2016-01-29/swagger/powerbiembedded.json)) with the team and try to do it for the next release, no problem :)

@devigned is this Docker image still valid? Automatically rebuild? Manually rebuild?

**Comment by devigned** [comment]
@lmazuel it is automatic and latest was updated as of 3 days ago.

**Comment by lmazuel** [comment]
Hi @chuckus 

I just released a preview of this library:
https://pypi.python.org/pypi/azure-mgmt-powerbiembedded/0.30.0rc5

I didn't have the time to make string testing of it, it's why it's a preview right now. IF you encounter any troubles, please open an issue I will be happy to look at it!

I close this issue right now because the main purpose of this issue was releasing the preview client, but as I said feel free to open issue about the client itself if necessary.

**Comment by chuckus** [comment]
@lmazuel Thanks for that!
