### ISSUE TITLE
[Python Track2] [STG69] EchoClientRequestId

### ISSUE THREAD

**Issue by zezha-msft** [Azure/azure-sdk-for-python#6437]

**Comment by xiafu-msft** [comment]
The dev task for this one was done, but it will break the existing test once we re-record the existing test. The reason is the response will have echoed client request id once we rerecord, so when we run in playback mode it will check if the client request id matches the one in recorded response(absolutely it's not matching). This should be fixed by next Monday.

**Comment by xiafu-msft** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/7350
