### ISSUE TITLE
WebApplicationFirewallPoliciesOperations.create_or_update Unable to deserialize to object

### ISSUE THREAD

**Issue by mmyyrroonn** [Azure/azure-sdk-for-python#6483]
https://github.com/Azure/azure-cli/issues/10011

**Comment by lmazuel** [comment]
Hi @MyronFanQiu 
Deserialization issue are 99% of the time Swagger problems, please open a Swagger issue with:
- A JSON payload you can reproduce
- The deserialization problem (e.g. should be a list, declared as string, etc). 

Please do NOT mention Python, since a Swagger issue it not Python specific, however please mention this issue as reference.

@zikalino I recommend to keep this kind of issued opened until you released a SDK with the fixed Swagger

**Comment by lmazuel** [comment]
Side note `AttributeError: 'str' object has no attribute 'get'` usually means that the Swagger is saying `string` where it should an object (based on experience).

**Comment by MyronFanQiu** [comment]
@lmazuel Thanks for the explanation. I will check that. It's quite helpful.

**Comment by SaurabhSharma-MSFT** [comment]
@lmazuel Following to know if you have any actions items pending on this issue.
