### ISSUE TITLE
Result 100 max for list function

### ISSUE THREAD

**Issue by sfonteneau** [Azure/azure-sdk-for-python#653]
Hello

The list function in " user_operation " returns a maximum of 100 users. Is it done way to return more ?

Thank you

**Comment by lmazuel** [comment]
100 is the default number of users on one page, we should automatically fetch the next page using this kind of code:
```python
for user in client.users.list():
    print(user)
```

We are investigating why it's not working.

Also note that I was about giving you a workaround, but we miss the "top" parameter for that, I open a bug on this in the Swagger repo:
https://github.com/Azure/azure-rest-api-specs/issues/373

At short terms, if you have less than 999 users and are ready to patch the code, you can add "$top=999" inside the url here:
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-graphrbac/azure/graphrbac/operations/users_operations.py#L140

like this:
```python
query_parameters['$top']=999
```

**Comment by sfonteneau** [comment]
I have more than 999 users.

**Comment by lmazuel** [comment]
Hi @sfonteneau 

There is clearly a bug, I'm working on the exact cause and might link new bugs I'll open in some other SDK core repo here. I'll do my best to give you update.

Thank you,

**Comment by lmazuel** [comment]
Hi @sfonteneau 

We fixed the bug on our dev branch. The fix will need a new "msrest" and "azure-graphrbac" package to work. We need to do more testing, since the bug is inside the code generator, we need to check that we don't break any other clients by an unexpected side-effect. Monday being an holiday in the US, we might have on official release around Wednesday 6th.
If you wish and are still in dev mode, I might be able to provide to you today an alpha package that you could try. Just tell me what is better for you and I can try to make this happen.
Thank you!

**Comment by lmazuel** [comment]
Hi @sfonteneau 

We don't forget you, the problem is really complex to solve.
https://github.com/Azure/autorest/issues/1232

**Comment by lmazuel** [comment]
Hi @sfonteneau 

We finally were able to fix this one. It was a design issue that needed several layers to be fixed, it's why it took so much time.
Release [0.30.0rc6](https://pypi.python.org/pypi/azure-graphrbac/0.30.0rc6) has the fix.

Update instructions:
* You can create a new venv installing `azure-graphrbac` 0.30.0rc6,
* Directly update `azure-graphrbac` to 0.30.0rc6 and `msrest` to 0.4.4 in your current (v)env

Thanks for the feedback! You helped all the languages SDK at the same time :)
