### ISSUE TITLE
undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv

### ISSUE THREAD

**Issue by NetGH** [Azure/azure-sdk-for-python#6752]
Steps to re-pro:

1. Clone python sdk git in raspberry pi 4 or 2 in root permission (latest Raspbian Buster)
2. ./azure-iot-sdk-python/build_all/linux/setup.sh --python-version 3.5
3. ./azure-iot-sdk-python/build_all/linux/build.sh --build-python 3.5

Result:
[100%] Built target iothub_service_client_python
completed run...
Sun 11 Aug 17:04:44 BST 2019
Test project /home/pi/code/azure-iot-sdk-python/c/cmake/iotsdk_linux
No tests were found!!!
/home/pi/code/azure-iot-sdk-python
copy iothub_client library to samples folder
copy iothub_client_mock library to tests folder
copy iothub_service_client library to samples folder
copy iothub_service_client_mock library to tests folder
copy provisioning_device_client library to samples folder
copy provisioning_device_client_mock library to tests folder
python3.5 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: /home/pi/code/azure-iot-sdk-python/device/tests/iothub_client_mock.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv

**Comment by loarabia** [comment]
Issue moved to [Azure/azure-iot-sdk-python #282](https://github.com/Azure/azure-iot-sdk-python/issues/282) via [**ZenHub**](https://www.zenhub.com/)

**Comment by loarabia** [comment]
Hi @NetGH  I moved this issue to the iot sdk for python repo given the description. I think the team there will be able to help.

**Comment by loarabia** [comment]
Hi again @NetGH  the IoT team was looking into this in the repository i moved it to. This is what they said back. Not sure if you want to continue the conversation over there.

"""
it looks like an issue when building the service client - that's due to the fact that raspbian buster probably doesn't ship with the version of the boost library that was being used to build this version of the SDK (built with Stretch and not Buster).
We also realize the experience of having to rebuild the SDK is subpar so we've undertaken the task of rewriting it in pure python. our new device implementation has been pushed to the master branch today so i would encourage you to follow the readme instructions if you're looking for the device SDK (given you're using this in a raspberry pi, i'm assuming that's what you're after).

if you're looking for the service sdk, unfortunately we don't have a good option right now except to suggest moving back to raspian stretch. we're working on a service SDK that will be purely python and won't require rebuilding for different OS versions, more to come on that side during the months of september and october.
"""
