### ISSUE TITLE
new keyvault doesn't support Storage Accounts

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-python#6989]
The latest version of azure.keyvault removes support for managing storage account keys.

Sample that used this functionality in the previous versions:

https://github.com/Azure-Samples/key-vault-python-storage-accounts

**Comment by mayurid** [comment]
@chlowell: Please follow up

**Comment by chlowell** [comment]
Because Azure Active Directory is recommended for controlling access to storage accounts (see e.g. [Key Vault's documentation](https://docs.microsoft.com/en-us/azure/key-vault/key-vault-ovw-storage-keys)), we don't plan to support managed storage accounts in new Key Vault libraries (azure-keyvault-*).

However, the feature is still supported by the prior Key Vault library, [azure-keyvault](https://pypi.org/project/azure-keyvault/1.1.0/#history) (versions < 4.0.0).
