### ISSUE TITLE
Can't figure out ComputeManagementClient, documentation is out of date.

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-sdk-for-python#704]
To make this simple, here's the code:

	#!/usr/bin/python3

	from azure.common.credentials import ServicePrincipalCredentials
	from azure.mgmt.compute import ComputeManagementClient

	credentials = ServicePrincipalCredentials(
	    client_id = '...',
	    secret = '...',
	    tenant = '...'
	)
	subscription_id = '...'
	compute_client = ComputeManagementClient(credentials, subscription_id)  # line 18
	resource_group_name = '...'
	compute_client.virtual_machines.list(resource_group_name)

Here's the bug:

	~/ » python azureboto.py 
	Traceback (most recent call last):
	  File "azureboto.py", line 18, in <module>
	    subscription_id
	TypeError: __init__() takes 2 positional arguments but 3 were given

So I'm obviously not using the ComputeManagementClient correctly. I go to the docs, http://azure-sdk-for-python.readthedocs.io/en/latest/_modules/azure/mgmt/compute/compute_management_client.html#ComputeManagementClient and the init method takes three positional arguments. That means the docs are out of date. I try to permute by only putting the subscription id or the credentials in the initialization, but neither works. 

	~/ » python azureboto.py
	Traceback (most recent call last):
	  File "azureboto.py", line 20, in <module>
	    compute_client.virtual_machines.list(resource_group_name)
	  File ".../py3env/lib/python3.5/site-packages/azure/mgmt/compute/computemanagement.py", line 10098, in list
	    if self.client.credentials.subscription_id is not None:
	AttributeError: 'ServicePrincipalCredentials' object has no attribute 'subscription_id'

I've tried a fair number of permutations at this point, but can't get it to work. I might be doing something wrong, or there may be a bug, or it may just be outdated documentation. Hoping to hear back soon, in any case.

**Comment by lmazuel** [comment]
The `latest` documentation points on the 2.0.0RC5 version of the SDK. Since it's a release candidate, you have to install it using the `--pre` flag:
http://azure-sdk-for-python.readthedocs.io/en/latest/#installation

Could then confirm with a `pip freeze` that you are using the 2.0.0RC5 version? We plan to release the stable version which will avoid using `--pre` very soon (this month probably).

You might also be interested in the official sample for Compute and Python:
https://github.com/Azure-Samples/virtual-machines-python-manage

**Comment by lmazuel** [comment]
Hi @zfrenchee , could we close this bug? If not, could you tell me what do you need to consider this bug fixed?
Thanks!
