### ISSUE TITLE
Add advanced dependency version check in pylint

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-python#7341]
Currently we have some dependency versions w/o any upper check, e.g. aiohttp>=3.0. This makes an assumption that our libraries are compatible with all future aiohttp releases even it has a major version jump (indicating there are breaking changes). This brings potential risks that our library may break silently and it will be very hard for customers to diagnose.  

We want to add a pylint rule that for any dependency versions with >=, they must have < as well.

**Comment by kurtzeborn** [comment]
@scbedd and @johanste should we require upper bounds on these for Python?

**Comment by scbedd** [comment]
I'm on board for at least filtering to a "less than next major major version"

**Comment by kurtzeborn** [comment]
@weshaggard and I talked and while we agree this could result in a build break when an incompatible version of a dependency is released, we'd rather keep it open ended and support as many versions of a dependency as we can.  When we do find breaks (as mentioned in the issue description) we would want to add the "ceiling" for the dependency at that time (after taking a look at whether we can make a code change and support both).  Basically, we think we should follow a case-by-case decision strategy rather than a blanket policy as is being suggested here.  If we had a general policy here we would be causing more issues where people cannot consume our libraries because we've artificially limited dependency versions even though they would actually work.

@scbedd and @johanste I'm going to close this based on that thinking.  If you disagree, please reactivate and lets discuss further.
