### ISSUE TITLE
[Cosmos] Rename 'parameter' docs directives to use 'keyword'

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#7729]
Also add any currently undocumented keyword args

**Comment by bryevdv** [comment]
@srinathnarayanan I'd like to make a PR documenting all of these currently undocumented keywords args:

https://github.com/Azure/azure-sdk-for-python/blob/9a9e393985cad0729b1612b29f6e9b685af042ae/sdk/cosmos/azure-cosmos/azure/cosmos/_base.py#L43-L67

but I am not familiar with most of them. Rather than me speculate, can you provide the line description for each, and I will get them added to the documentation in a consistent way.

**Comment by annatisch** [comment]
Added listing of Optional Configuration kwargs to readme in PR #8297
