### ISSUE TITLE
Virtual Network occasionally 404 errors when delete/create vnet with the same name. 

### ISSUE THREAD

**Issue by kfolkes** [Azure/azure-sdk-for-python#7771]
When using the azure-mgmt-network library.
Issue: When with my dummy script (that just loops over vnet delete/vnet create/subnet create).  
Sample Snippet Code:

print('Deleting VNET {}'.format(datetime.datetime.now()))
    poller = nm_client.virtual_networks.delete(rg_name, vnet_name)
    print('VNET Delete Started {}'.format(datetime.datetime.now()))
    poller.status()
    poller.wait()
    print('VNET Delete Completed {}'.format(datetime.datetime.now()))
    poller.status()
    if not poller.done():
        raise RuntimeError('Not Done - VNET Delete')

print('Creating VNET {}'.format(datetime.datetime.now()))
    poller = nm_client.virtual_networks.create_or_update(rg_name, vnet_name, vnet_params)
    print('VNET Create Started {}'.format(datetime.datetime.now()))
    poller.status()
    poller.wait()
    print('VNET Create Completed {}'.format(datetime.datetime.now()))
    poller.status()
    if not poller.done():
        raise RuntimeError('Not Done - VNET Create')

Output Results 
Found the Following VNETS
Perf-RG-1 babbb0b1-2197-4bfc-a308-77fe08d7543d
TEST 64a36159-0ca0-48f9-8e2d-173aba67ff0f
Creating Subnet
Subnet Create Started
'InProgress'
Subnet Create Completed
'Succeeded'

Deleting VNET 2019-09-23 14:39:34.009801
VNET Delete Started 2019-09-23 14:39:34.590361
'InProgress'

VNET Delete Completed 2019-09-23 14:39:46.462263
'Succeeded'

Creating VNET 2019-09-23 14:39:46.462463
VNET Create Started 2019-09-23 14:39:47.119752
'InProgress'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 390, in run
    self._poll()
  File "/usr/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 426, in _poll
    self._operation.parse_resource(self._response)
  File "/usr/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 286, in parse_resource
    self._raise_if_bad_http_status_and_method(response)
  File "/usr/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 140, in _raise_if_bad_http_status_and_method
    "Invalid return status for {!r} operation".format(self.method))
msrestazure.polling.arm_polling.BadStatus: Invalid return status for 'PUT' operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/usr/lib/python3.6/site-packages/msrest/polling/poller.py", line 201, in wait
    raise self._exception  # type: ignore
  File "/usr/lib/python3.6/site-packages/msrest/polling/poller.py", line 152, in _start
    self._polling_method.run()
  File "/usr/lib/python3.6/site-packages/msrestazure/polling/arm_polling.py", line 393, in run
    raise CloudError(self._response)
msrestazure.azure_exceptions.CloudError: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/virtualNetworks/TEST' under resource group 'vpnperf' was not found.

[pythonSDK_calls.zip](https://github.com/Azure/azure-sdk-for-python/files/3713598/pythonSDK_calls.zip)

Attaching Files of the behavior pulled from Support Engineers.

**Comment by kaerm** [comment]
@kfolkes thanks for reporting this! I am tagging the right team to take a look at this

**Comment by kfolkes** [comment]
Any updates?

**Comment by kfolkes** [comment]
@zikalino  Any updates from your end on this?

**Comment by kfolkes** [comment]
@zikalino  Do you have any findings ?

**Comment by miksanch** [comment]
Having debugged this a bit more.  The issue seems to be a disconnect between the backend and the frontend on when a VNET delete operation is actually complete.  The below steps seem to seem to reproduce the issue reasonably reliably.

1) Delete an existing VNET and wait for the LRO to return as complete.
2) At this point, if you check to see if the VNET is there with the SDK, it will not be there, as expected. 
3) Re-create the VNET, and wait for that LRO to return as complete.
4) At this point, if you check to see if the VNET is there with the SDK, it will be there, as expected
5) Wait some time (1 minute seems good).  Check to see if the VNET is there.  It will be gone, unexpectedly.

If you check the activity logs, and cross reference those timestamps with the SDK calls, it seems like after step 1 above, the delete operation is still actually going on in the background as it hasn't returned 'Succeeded' yet per the activity logs.  That means that at step 3, it's not really a create operation being done, but an update operation on that VNET.  When the delete operation finally finishes up, it deletes the VNET, which was just thought to be created.

**Comment by nickzhums** [comment]
@RodgeFu could you have someone take a look at this, thanks!

**Comment by RodgeFu** [comment]
This seems a resource status consistency problem in the backend when you keep CRUD a resource with no interval between the operations. + service attention label for the PG team to investigate and double confirm. thanks.

**Comment by Suryanarayanapotla** [comment]
Hello Rodge, 
As we discussed offline, based on our backend( azure network support) TA investigation the Python polling should depends on the Activity Logs but in this case its not.

This is causing the issue because the activity logs are the entry point all the operations(CRUD).

Kindly please look into the issue, Thank you.

**Comment by nickzhums** [comment]
@Suryanarayanapotla as noted by Rodge this needs service team's attention, we will route to Network team to take a look at this, thanks

**Comment by RodgeFu** [comment]
@kfolkes, per comment from Suryanarayanapotla from azure network support, you will need to check the Activity Logs instead of operation result in this case to get accurate status. thanks.

**Comment by allegradomel** [comment]
Is there any request for SDN product team?

**Comment by jl-ms** [comment]
#please-close
