### ISSUE TITLE
Change azure-keyvault package to a metapackage that installs the various azure-keyvault-* packages

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-for-python#7954]
The existing azure-keyvault package is currently incompatible with the new libraries. We need to do something about this. 

My strong recommendation is to make it a metapackage that installs the various keyvault subpackages. This retains the current behavior as closely as possible.

Alternatively we would push a new version that warns on install and tells people not to use it anymore and direct them to the new packages.

**Comment by mayurid** [comment]
Assigning to @lmazuel to load balance

**Comment by lmazuel** [comment]
After investigation, the potential problem is the ownership of `azure/keyvault/__init__.py`:
- On Python 3, both track1 and track2 can co-exists, since there is no "azure-keyvault-nspkg" involved, so no co-ownership
- On Python 2, `azure-keyvault` and `azure-keyvault-nspkg` both owns `azure/keyvault/__init__.py` with different content, so depending on the order of installs, track1 can work or not. Fun part is that track2 will always work, because it does not rely on the content of this file (just its presence)
