### ISSUE TITLE
Rename azure-storage-file to azure-storage-fileshare

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-for-python#8140]

**Comment by bsiegel** [comment]
Just as a note about consistency, we have been using the following pattern where the library name is the plural of the service name:

Azure Blob storage -> azure-storage-blobs
Azure Queue storage -> azure-storage-queues

It would be nice to be consistent about pluralization here too (though I get that the pattern is broken because the service is now just called "Azure Files")

**Comment by annatisch** [comment]
@bsiegel 
Currently we have `azure-storage-blob` and `azure-storage-queue` because GA versions of these packages already exist.
Would it not be best to remain consistent within our storage packages and use `azure-storage-fileshare`? Or am I misunderstanding? :)

**Comment by bsiegel** [comment]
@annatisch, yep you're right - apologies. My memory of this was from working on the READMEs yesterday, where we refer to the libraries as the "Azure Storage Blobs client library" or "Azure Storage Queues client library"

**Comment by annatisch** [comment]
Hi @johanste - as part of this change - would you prefer the user-agent to display the package name ("file-share") or the namespace ("fileshare")?

**Comment by johanste** [comment]
file-share.
