### ISSUE TITLE
Filter VM size under availability set based on premium support

### ISSUE THREAD

**Issue by AReshma** [Azure/azure-sdk-for-python#8142]
https://docs.microsoft.com/en-us/rest/api/compute/availabilitysets/listavailablesizes is listing the VMsize available under the availabilty set, but there is no filter to see if that support premium disk or not , or it doesnt have attribute to indicate if it support premium.
current sample response of this format,,

```
{
"memory_in_mb": 512,
"number_of_cores": 1,
"resource_disk_size_in_mb": 1024,
"max_data_disk_count": 2,
"name": "Standard_B1ls",
"os_disk_size_in_mb": 1047552
}
```
Is there any API to get the required details?

**Comment by Drewm3** [comment]
Hi @kaerm, you will need to use the API above to determine which sizes are available to add to the Availability Set, and then use the Resource SKUs API (https://docs.microsoft.com/en-us/rest/api/compute/resourceskus/list) to get the full details of the individual VM size. 

Unfortunately, the Resource SKU API is a little unwieldy because it returns the details for all sizes in all regions. We are adding filtering abilities to the Resource SKU API which is tracked by this item in our feedback site (https://feedback.azure.com/forums/216843-virtual-machines/suggestions/37154362-impossible-to-filter-the-azure-rest-api-sku-inform). Feel free to track that item to get notice when the filtering is available. 

Let me know if this works for you.

**Comment by AReshma** [comment]
@Drewm3  - Thanks for responding. Resource SKU API response is huge. Is there any api, python sdk function, where we can send the VM size name Standard_B1ls and get details of it(along with premium details)

**Comment by Drewm3** [comment]
The REST API for Resource SKU does provide a regional filter now; however it seems that our public documentation is not yet updated. 

The filter we added looks like this:

`/subscriptions/{subscriptionId}/providers/Microsoft.Compute/skus?api-version={apiVersion}&$filter=location eq '{location}'`

where {location} is one of our supported locations and it should work for all api versions.

I am working to get the documentation updated, but this should reduce the size of the response. We do not currently support further filtering down to a specific SKU.

**Comment by Drewm3** [comment]
The API documentation has been updated with an example of a regional SKU query here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-04-01/examples/ListAvailableResourceSkusForARegion.json. 

I'll close this issue once the documentation has made it to docs.microsoft.com.

**Comment by Drewm3** [comment]
Closing this now that the documentation has been updated
