### ISSUE TITLE
Network Metrics

### ISSUE THREAD

**Issue by Gopalvenu** [Azure/azure-sdk-for-python#857]
Hi ,

I need to collect network bandwidth usage for all vm machines in azure. How can i get that using python?
Any sample code is there?

Thanks,
Gopal.

**Comment by lmazuel** [comment]
Hi @Gopalvenu ,

This is a feature included in [Azure Monitor](https://azure.microsoft.com/en-us/blog/announcing-the-public-preview-of-azure-monitor/).
We are working on two packages "azure-monitor" (get the actual data) and "azure-mgmt-monitor" (create monitor account, set alerts, etc.)

I close your bug since there is already an issue about metrics and this package: https://github.com/Azure/azure-sdk-for-python/issues/555. You can follow availability on these packages by following this issue.

This is close on the roadmap, I'm actively working on it. I should be able to release a preview package with some samples this week (this is just an ETA).

Thanks,

**Comment by Gopalvenu** [comment]
Hi lmazuel,

Thanks for your update. I will wait for this feature. Let me know once get completed.

Thanks,
Gopal.
