### ISSUE TITLE
How To - How can I increase the expiry for the bearer token ?

### ISSUE THREAD

**Issue by LazzariPaolo** [Azure/azure-sdk-for-python#8714]
I am getting the token as follows:

```python
profile = azure.common.credentials.get_cli_profile()
token = profile.get_raw_token(resource = resource_host, subscription = subscription_id)
```

but the token always expires in 3600 seconds.
Is it possible to increase the life of this token? If so, how?

Thanks.

**Comment by kaerm** [comment]
@LazzariPaolo thanks for reaching out to us //cc: @mayurid

**Comment by LazzariPaolo** [comment]
@kaerm @mayurid 
I see from this documentation page:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes

that I should be able to use the refresh token to refresh the access token:

> The refresh token is used to obtain new access/refresh token pairs when the current access token expires.

but how can this be done with the sdk for Python? I did not find any examples.

**Comment by chlowell** [comment]
3600 seconds is the default lifetime for an access token, and in this case you won't be able to extend its validity because you're using a token obtained for the CLI. What are you using the token for?

**Comment by LazzariPaolo** [comment]
I need the token to validate HTTP requests against the Azure Cloud Partner Portal.

**Comment by chlowell** [comment]
I'm closing this as it's gone quite stale. To answer outstanding questions for future readers:
- the example in the first comment is actually invoking [Azure CLI code](https://github.com/Azure/azure-cli/blob/06cce5b0bf3fe807280b59600001c8213390745c/src/azure-cli-core/azure/cli/core/_profile.py#L623), not part of the Azure SDK
- setting that aside, the Azure SDK has no API to configure the lifetime of access tokens
- Azure AD sets the lifetime of access tokens. This may be configurable as described in the document linked above.
- refresh tokens are used to request new access tokens, not extend the validity of existing ones 

With the caveat that I'm not familiar with the Azure CLI code here, I'd suggest requesting a new access token shortly before the current one expires. You must do that in any case because all access tokens have an immutable, finite lifetime. Azure AD doesn't enable extending the validity of an issued access token.
