### ISSUE TITLE
tox fails on azure-storage-file-datalake

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-python#8789]
When running tox in `azure-storage-file-datalake`

`azure-sdk-for-python\sdk\storage\azure-storage-file-datalake>tox -c ../../../eng/tox/tox.in`

Get the following error:

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'dev_requirements.txt'`

The dev_requirements.txt file doesn't exist in that service subfolder.

**Comment by amishra-dev** [comment]
@xiafu-msft Emily, can you please take a look at this bug.

**Comment by xiafu-msft** [comment]
Hi @jongio 

We can add dev_requirements.txt if it will be used.
Currently all dependencies for it will be automatically added by running python script/dev_setup.py under azure-sdk-for python, because it is using the same dependencies as some other packages.

BTW what were you trying to generate by calling tox? (what role dev_requirement.txt is performing there?)

**Comment by jongio** [comment]
tox is used to run tests in venvs configured for various python versions and environment settings. Please see the contributing guide for more info.

**Comment by xiafu-msft** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/8828

**Comment by xiafu-msft** [comment]
The pr has been merged, close this for now, feel free to reopen it if you have any concern! ^_^
