### ISSUE TITLE
Different metric results using different tools

### ISSUE THREAD

**Issue by bulkware** [Azure/azure-sdk-for-python#8803]
Hello =)

I get different results when I'm making queries using different tools. The Kusto-query is the only one that doesn't get data from an Application Insights resource. The system developer told me that the correct answer is the one made using Kusto-query. Also, I don't quite understand how a requests/count metric could be a float anyway. Maybe someone could help me understand why this is different using the Kusto-query?

**Azure SDK for Python:**
```
#!/usr/bin/python

import adal
import json

from azure.mgmt.monitor import MonitorManagementClient
from msrestazure.azure_active_directory import AADTokenCredentials
from msrestazure.azure_cloud import AZURE_PUBLIC_CLOUD

client_id = "<client_id>"
pemfile = "</path/to/pemfile.pem>"
resource_id = "/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Insights/components/<resource>"
rolename = "<cloud/roleName>"
tenant_id = "<tenant_id>"
thumbprint = "<thumbprint>"

with open(pemfile, "r") as file:
  certificate = file.read()

LOGIN_ENDPOINT = AZURE_PUBLIC_CLOUD.endpoints.active_directory
RESOURCE = AZURE_PUBLIC_CLOUD.endpoints.active_directory_resource_id
context = adal.AuthenticationContext(LOGIN_ENDPOINT + "/" + tenant_id)

MANAGEMENT_TOKEN = context.acquire_token_with_client_certificate(
  RESOURCE, client_id, certificate, thumbprint
)

credentials = AADTokenCredentials(MANAGEMENT_TOKEN, "<client_id>")
client = MonitorManagementClient(credentials, "<subscription_id>")

metrics_data = client.metrics.list(
    resource_id,
    aggregation="Total",
    filter="cloud/roleName eq '{}'".format(rolename),
    interval="PT1M",
    metricnames="requests/count",
    timespan="2019-11-21 12:04:00/2019-11-21 12:05:00"
)

for item in metrics_data.value:
  for timeserie in item.timeseries:
      for data in timeserie.data:
          print(data.total)
```
Result: 626.9268

**Azure CLI**
```
az monitor metrics list --resource "/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Insights/components/<application_insights_resource>" --aggregation "Total" --interval PT1M --start-time "2019-11-21 12:04:00" --end-time "2019-11-21 12:05:00" --metric "requests/count" --filter "cloud/roleName eq '<cloud/roleName>'"
```
Result: 626.9268

**Kusto-query**
```
requests | project cloud_RoleName, timestamp | where timestamp between(datetime('2019-11-21 12:04:00') .. datetime('2019-11-21 12:05:00')) and cloud_RoleName =~ '<cloud/roleName>' | count
```
Result: 5

**Comment by vgorbenko** [comment]
@bulkware , [this article explains]( https://docs.microsoft.com/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics ) the difference between log-based metrics and standard pre-aggregated metrics. As article explains, the metrics may show _slightly_ different results as log-based metrics use statistical approximations with sampling. However, in your example, the results are _very_ different because you also have an error in the query: 

requests | project cloud_RoleName, timestamp | where timestamp between(datetime('2019-11-21 12:04:00') .. datetime('2019-11-21 12:05:00')) and cloud_RoleName =~ '<cloud/roleName>' | **count**

In your query, **count** shows how many  records (measurements) were captured, probably not something that you are looking for. To get the number of server requests, you need to run the following query (note the **sum(itemCount)** part:

requests
| summarize sum(itemCount) by bin(timestamp, 5m)

**For a complete list of underlying queries for each of AppInsights metric** follow [this link](https://docs.microsoft.com/azure/azure-monitor/platform/app-insights-metrics)

Thank you,
Vitaly
Azure Monitor PM

**Comment by bulkware** [comment]
Hello,
And thank you for your answer =)

Running a Kusto-query:
`requests | project cloud_RoleName, itemCount, timestamp | where timestamp between(datetime('2019-11-21 12:04:00') .. datetime('2019-11-21 12:05:00')) and cloud_RoleName =~ '<cloud/roleName>' | summarize sum(itemCount) by bin(timestamp, 5m)`

Returns: 5

So these changes do not change the end result. Of course it could be that this query is correct and the other ones are incorrect, but I fail to see how.
