### ISSUE TITLE
[DataFactory] Python SDK don't retrive parameters on pipelines

### ISSUE THREAD

**Issue by Racknaraock** [Azure/azure-sdk-for-python#8907]
The calls to extract the corresponding JSON from the different elements of the datafactory do not recover the total content of the same.

To reproduce the error, it is only necessary to create a pipeline with parameters and extract the JSON from this element using the SDK.

When inspecting the element we can realize that in the key parameters, it comes with elements different from those that can be found in the JSON produced by the UI.

![imagen](https://user-images.githubusercontent.com/41477241/69898788-2eb9bf00-135e-11ea-9acf-2eb1489a9d0a.png)

![imagen](https://user-images.githubusercontent.com/41477241/69898794-4133f880-135e-11ea-9893-94db16a8a4ce.png)

**Comment by hvermis** [comment]
I'm not in ADF anymore, reassigning.

**Comment by zhangyd2015** [comment]
Adding @shawnxzq, the new ADF SDK owner.

**Comment by RodgeFu** [comment]
python SDK didn't manipulate the json content. add "Service Attention" label for service team to double confirm the behavior difference from portal and SDK (which is a pass-through from restful call). thanks.

**Comment by lmy269** [comment]
@shawnxzq to take a look

**Comment by shawnxzq** [comment]
@Racknaraock Sorry for the delayed response since I can't see this issue my dashboard, instead I found we have your issue from a different report. 
I'm not sure whether I fully get what you mean, the two pictures you showed to us is actually the same meaning, could you please explain a little bit more details? Besides, we may have one related bug fix in Phython SDK, which will be release by end of this month, thanks!

**Comment by Racknaraock** [comment]
Close this issue. After almost a year I don't know if this problem is still happening.We stopped using data factory due to the failures we are having.
