### ISSUE TITLE
Error when exeucting  Commerce - Billing API

### ISSUE THREAD

**Issue by kvenkazure** [Azure/azure-sdk-for-python#912]
![image](https://cloud.githubusercontent.com/assets/3600818/21080676/6f102e36-bf83-11e6-8ae0-ab989146f150.png)

**Comment by lmazuel** [comment]
Hi @kvenkazure 

You're not inside a class, you cannot use the "self" keyword.

I realize I made a mistake while writing the sample, it is fixed now:
https://github.com/Azure/azure-sdk-for-python/commit/04447f4865044bd716ba6539b821c134d4b8e48d

I close this issue since the documentation is fixed.

Thank you!
