### ISSUE TITLE
recent azure-cli-core and azure==4.0.0 are incompatible

### ISSUE THREAD

**Issue by rmb938** [Azure/azure-sdk-for-python#9195]
I am trying to auth using cli credentials

```
from azure.common.credentials import get_azure_cli_credentials

credentials = get_azure_cli_credentials()
```

And I receive the following error

```
ImportError: You need to install 'azure-cli-core' to load CLI credentials
```

I am using poetry for dependency management and when I try and install `azure-cli-core` I get the following error

```
Using version ^2.0.77 for azure-cli-core

Updating dependencies
Resolving dependencies... (3.1s)

[SolverProblemError]
Because no versions of azure-cli-core match >2.0.77,<3.0.0
 and azure-cli-core (2.0.77) depends on azure-mgmt-resource (>=4.0,<5.0), azure-cli-core (>=2.0.77,<3.0.0) requires azure-mgmt-resource (>=4.0,<5.0).
Because azure-mgmt (4.0.0) depends on azure-mgmt-resource (>=2.0,<3.0)
 and no versions of azure-mgmt match >4.0,<5.0, azure-mgmt (>=4.0,<5.0) requires azure-mgmt-resource (>=2.0,<3.0).
Thus, azure-cli-core (>=2.0.77,<3.0.0) is incompatible with azure-mgmt (>=4.0,<5.0).
And because azure (4.0.0) depends on azure-mgmt (>=4.0,<5.0)
 and no versions of azure match >4.0.0,<5.0.0, azure-cli-core (>=2.0.77,<3.0.0) is incompatible with azure (>=4.0.0,<5.0.0).
So, because prm-azure-instance-agent depends on both azure (^4.0.0) and azure-cli-core (^2.0.77), version solving failed.
```

Any ideas on what specific versions of these libraries I need to make everything happy?

**Comment by lmazuel** [comment]
Hi @rmb938 
The usage of `azure` is not recommended anymore, since this meta-package have some design trouble that force it to old version. I would suggest if you want to use the CLI authentication, that you don't use `azure` but directly the services you need (i.e. `azure-mgmt-compute`, etc.).

I'm renaming slightly your issue to make it clear this is a conflict between `azure` and latest `azure-cli-core`. We plan to address the `azure` soon, and I'll close your issue when I've confirmed whatever solution fixes this one as well.

Thanks for your report!

**Comment by rmb938** [comment]
Oh I see, is there a list somewhere were I can see which python packages map to which azure service?

**Comment by lmazuel** [comment]
This link is supposed to explain enough:
https://github.com/Azure/azure-sdk-for-python#packages-available

If it's not enough, let me know and I take this as a doc feedback to make it better :). There is no actual list, but it's supposed to be clear enough so you get what you need.

**Comment by lmazuel** [comment]
`azure` meta-package has been officially deprecated. The list of available packages can be found here:
https://aka.ms/azsdk/python/all
