### ISSUE TITLE
"python setup.py install" failing on azure-mgmt-keyvault setup (invalid install_requires)

### ISSUE THREAD

**Issue by hosungsmsft** [Azure/azure-sdk-for-python#922]
If I run 'python setup.py install' on the current master branch, I get the following error (while I don't get that error if I do the same on v2.0.0rc6 tag). Looking at the azure-mgmt-keyvault/setup.py's install_requires param, it looks like 'msrestazure~=0.4.6' entry is causing the issue. Am I doing something wrong, or if it's a bug?

**Comment by lmazuel** [comment]
Hi @hosungsmsft 

As we discussed more directly since, your `setuptools` lib is to old for the ~= syntax (@brettcannon to re-confirm). Especially on an Ubuntu 12.04 where you don't even have pip (as you said).

[Please install pip](https://pip.pypa.io/en/stable/installing/) and update your setuptools lib (pip install -U setuptools).

I close this issue for now, feel free to still comment on it if necessary.

Thanks!
