### ISSUE TITLE
[EventHubs] Wrong Auth type in _create_auth

### ISSUE THREAD

**Issue by yunhaoling** [Azure/azure-sdk-for-python#9325]
Should the auth class here be SASTokenAuth (async accordingly)?

https://github.com/Azure/azure-sdk-for-python/blob/f74cfa1aed972ded2a7b196f22fba281c52c3fe6/sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py#L164-L175

**Comment by annatisch** [comment]
No - the actual class here doesn't matter - in fact I changed it to the JWT token class because I needed the dynamic mechanism to actually generate/gather the token at auth time, rather than cache a static string.
If you see on line 169 - the actual type of the token is still being set to "servicebus.windows.net:sastoken"

**Comment by yunhaoling** [comment]
thanks for the explanation, closing this
