### ISSUE TITLE
User-focused documentation of transport configuration

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-python#9400]
The extant documentation (https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport) is written for client library developers. We should have a document describing how users can configure transport.

**Comment by xiangyan99** [comment]
@chlowell do you have any users data that they want to configure a transport by themselves? In #9397, it seems to me they wanted to use aiohttp but saw non-helpful errors. We have #9399 to track that issue.

**Comment by chlowell** [comment]
What I was looking for here is a document describing to users the prerequisites and configuration options for async transports. Something to link to from another library's readme so I can write "you need to install aiohttp for the default async stuff to work but there are other options, see this other document for more information". The best candidate I found is [CLIENT_LIBRARY_DEVELOPER.md](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#transport), which was written for SDK developers.

**Comment by xiangyan99** [comment]
Seems like we are on same page. 

What I plan to solve is:
1. Describe the prerequisites for async transports by solving #9399
2. A link to the documentation of transport options (https://aka.ms/azsdk/python/transport-configuration). I prefer to use aka.ms rather than hard-coding into README so we can have the flexibility of maintaining multiple versions and can always point user to the latest one by default.

Your options?

**Comment by chlowell** [comment]
A better error message and more durable link are part of it but I'm thinking more about the document itself here. It has the best description I know of our async transport implementations and how to use them but from a user's perspective it contains a lot of noise about internal types and concepts. I opened this issue because it seems like we should have documentation for users who want to know more about transport selection and configuration, and the best we have is this one written for the SDK team.

**Comment by xiangyan99** [comment]
The link points users to the available options for transport (we plan to uniform the transports so every transport expose same options by default). It looks like:


Parameters | Description
-- | --
connection_timeout | A single float in seconds for the connection timeout. Defaults to 300 seconds.
read_timeout | A single float in seconds for the read timeout. Defaults to 300 seconds.
connection_verify | SSL certificate verification. Enabled by default. Set to False to disable, alternatively can be set to the path to a CA_BUNDLE file or directory with certificates of trusted CAs.
connection_cert | Client-side certificates. You can specify a local cert to use as client side certificate, as a single file (containing the private key and the certificate) or as a tuple of both files' paths.
proxies | Dictionary mapping protocol or protocol and hostname to the URL of the proxy.
cookies | Dict or CookieJar object to send with the Request.
stream | whether to immediately download the response content. Defaults to False.
connection_data_block_size | The block size of data sent over the connection. Defaults to 4096 bytes.

Did I miss anything?

**Comment by chlowell** [comment]
Looks like all the relevant kwargs to me but I'm questioning whether that document is the right place for it. I think it's strange to point a user who wants to configure a proxy to a document that covers that and also the difference between SansIOHTTPPolicy and HTTPPolicy. Shouldn't we separate documentation for users from documentation for SDK developers?

**Comment by xiangyan99** [comment]
Good question!

Now we have two options:

1. Have a separate documentation which only focuses on transport configurations. And the cons is we need to maintain multiple copies of the information.
2. We create the link which points to the transport configuration section in developer doc. like https://aka.ms/azsdk/python/transport-configuration. 

@lmazuel @johanste any suggestions?

**Comment by johanste** [comment]
I agree with @chlowell - we have two different audiences; client library developers and developers using our client libraries.

The former should start with our python design guidelines. The latter should find a link that does not get into how the sausage is made. I don't think that they will be copies. And while there will be overlap, the client library developers should already understand/know how their stuff is supposed to be used, so that piece of documentation doesn't have to repeat things in detail.

**Comment by johanste** [comment]
There may also be a third set of developers; people who want to extend our library without being client library developer. The information they need should be in an advanced section on how things work.

**Comment by lmazuel** [comment]
The current PR duplicates too many things to me, by experience they will go inconsistent at some point in time:
https://github.com/Azure/azure-sdk-for-python/pull/15856

I see the README as valuable for both dev and sdk write, while client_dev.md for dev only.

In the case of transport kwargs, I see no reason to keep them SDK write only, since these are flags people will pass.

**Comment by xiangyan99** [comment]
Fixed
