### ISSUE TITLE
Object has no attribute 'signed_session'

### ISSUE THREAD

**Issue by Mejato** [Azure/azure-sdk-for-python#9432]
- **Package Name**: azure.mgmt.subscription
- **Package Version**: 0.5.0
- **Operating System**: Windows and Ubuntu
- **Python Version**: 3.7 and 3.8

**Describe the bug**
I'm following the get started guide and i can't seem to get any SDK API call going. I have tried all the available authentication methods as described in https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate

**To Reproduce**

```

from azure.common.client_factory import get_azure_cli_credentials
from azure.mgmt.resource import SubscriptionClient


class Connect:

    def __init__(self):
        credentials = get_azure_cli_credentials()

        subscription_client = SubscriptionClient(credentials)
        subscription = next(subscription_client.subscriptions.list())
        self.subscription_id = subscription.subscription_id


def run_example():
    azure_client = Connect()
    print(azure_client.subscription_id)


if __name__ == "__main__":
    run_example()
```

**Expected behavior**
Print at least 1 subscription id.

**Screenshots**

![image](https://user-images.githubusercontent.com/41669982/72292028-7c437e80-36b5-11ea-855e-0e15971d51e8.png)

**Comment by v-xuto** [comment]
Hi @Mejato,
Change **credentials = get_azure_cli_credentials()** to **credentials = get_azure_cli_credentials()[0]**

Because Method [get_azure_cli_credentials()](https://github.com/Azure/azure-sdk-for-python/blob/1a627cd1c39c530ead2e804371ff6cf9a5ef1c24/sdk/core/azure-common/azure/common/credentials.py#L81) returns a tuple containing **Credentials** and **SubscriptionID**. But we only need the Credentials.

Other method follow [CLI-based authentication ](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-cli):
```
from azure.common.client_factory import get_client_from_cli_profile
from azure.mgmt.resource import SubscriptionClient

sub_client = get_client_from_cli_profile(SubscriptionClient)
for sub in sub_client.subscriptions.list():
    print(sub.subscription_id)
```
@jongio

**Comment by Mejato** [comment]
Awesome, thanks v-xuto! I got the hang of the SDK now and your assistance is much appreciated!
