### ISSUE TITLE
Config name mismatch - long_running_operation_timeout vs long_running_operation_retry_timeout

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/azure-sdk-for-python#962]
The ComputeManagementClient build config with a parameter 'long_running_operation_retry_timeout' but all the operations are looking for 'long_running_operation_timeout'. 

Config definition:  (https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/compute_management_client.py#L56)

Example (mis)usage: https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-compute/azure/mgmt/compute/operations/virtual_machines_operations.py#L126-L131

**Comment by lmazuel** [comment]
@clarkbreyman-yammer 
This is a known issue, but since we got the discussion with the CLI team, no issue was created here (thank you for that :)). However, the solution is already described in this `msrestazure` issue:
https://github.com/Azure/msrestazure-for-python/issues/13

We will remove the `__init__` parameter, and the only way to define this parameter will be:
```python
client = Client(credentials, subscription_id)
client.config.long_running_operation_retry_timeout = 666
```
It's already ok if you want to use it.

**Comment by clarkbreyman-yammer** [comment]
Thanks @lmazuel . We've just started using wait() instead of polling done() directly and have been specifying per-operation timeout. Will that still be supported?

**Comment by lmazuel** [comment]
- You should not use `done()` anyway since it's a non-blocking call. Use `wait` (returns `None`) or `result` (if you expect your LRO to return something.)
- The timeout in `wait` / `result` is the Python one: we will exit with an exception if your total length on the operation is reached. By default it's `None`, i.e. wait until it's done forever.
- The `long_running_operation_timeout ` timeout is for time *between* the calls to Azure. You want to change that if you're afraid to be blacklisted by Azure by polling too much, or you want faster reaction (minimal time for LRO is this timeout: initial call + wait this timeout + first polling). Note that if `retry-after` is set by the service, this value is used (and this timeout ignored).

**Comment by lmazuel** [comment]
azure-mgmt-compute is now released without the `long_running_operation_retry_timeout` parameter as expected, so this issue can be closed.
Please fell free to ask me to re-open it or open a new issue if necessary.
Thank you!
