### ISSUE TITLE
EntitySearchClient.entities.search returns NoneType as entities results

### ISSUE THREAD

**Issue by siminchengithub** [Azure/azure-sdk-for-python#9732]
- **azure.cognitiveservices.search.entitysearch**: 
- **2.0.0/1.0.0*: 
- **Linux**:
- **3.6**: 

**Describe the bug**
The EntitySearch python sdk returns NoneType as entity search results for query "RED BAY HOSPITAL". However on https://azure.microsoft.com/en-us/services/cognitive-services/bing-entity-search-api/ it returns the correct entity. 

**To Reproduce**
1. Install azure.cognitiveservices.search.entitysearch 2.0.0
2. Run following code
`from azure.cognitiveservices.search.entitysearch import EntitySearchClient
from msrest.authentication import CognitiveServicesCredentials
key = <your-key>
client = EntitySearchClient('https://api.cognitive.microsoft.com', CognitiveServicesCredentials(key))
entity_data = client.entities.search(query="RED BAY HOSPITAL", market = 'en-US')
if entity_data.entities.value:
    main_entities = [entity for entity in entity_data.entities.value
                     if entity.entity_presentation_info.entity_scenario == "DominantEntity"]
    if main_entities:
        print(main_entities[0].description)`

**Expected behavior**
I expect no error

**Screenshots**

**Additional context**

**Comment by v-xuto** [comment]
Hi @siminchengithub，
Please update **"if entity_data.entities.value:"** to **"if entity_data.places.value:"** in code. 
 
Because the Entity Search API lets you send a search query to Bing and get back search results that include entities and places: 
- Place results include restaurants, hotel, or other local businesses. For places, the query can specify the name of the local business or it can ask for a list (for example, restaurants near me).  
- Entity results include persons, places, or things. Place in this context is tourist attractions, states, countries, etc. 
  
The detailed code is shown below for how to use rename_file (here is the official  [sample](https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/master/samples/search/entity_search_samples.py) ): 
```
from azure.cognitiveservices.search.entitysearch import EntitySearchClient  
from msrest.authentication import CognitiveServicesCredentials  
  
key = <your-key> 
client = EntitySearchClient('https://api.cognitive.microsoft.com', CognitiveServicesCredentials(key)) 
  
entity_data = client.entities.search(query="RED BAY HOSPITAL",market = 'en-US')  
# Your question appears this step. 
if entity_data.places.value: 
    hospital = entity_data.places.value[0] 
    try: 
        telephone = hospital.telephone 
        print( 
            'Searched for "RED BAY HOSPITAL" and found a hospital with this phone number:') 
        print(telephone) 
    except AttributeError: 
        print("Couldn't find a place!") 
else: 
    print("Didn't see any data..") 
```
@jongio

**Comment by v-xuto** [comment]
Hi @siminchengithub ,
How is this issue going? Feel free to let us know if further help is needed.

**Comment by tzhanl** [comment]
We are going to close this issue because we haven’t heard from you in a few days, but please re-open it if the issue still persists.
