### ISSUE TITLE
Allow customers to parse certificate, key, and secret IDs from URLs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-python#9908]
We will add methods to parse URLs into VaultUri, Collection, Name, and optional Version components for Certificates, Keys, and Secrets

**Comment by chlowell** [comment]
Due to the complexity of doing this across Key Vault libraries and the simplicity of [our internal parsing code](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py), I'm closing this issue until there's a compelling reason to tackle its complexities. In the meantime, we can direct users to [our internal parsing code](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/__init__.py) and, if there's enough demand, add a sample demonstrating the same.
