### ISSUE TITLE
[Storage] Enable configuring live tests to run against specific API version

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-python#9911]
Live tests will fail when testing SDKs against an un-rolled-out API version.
We need to either update the live-test CI endpoint to run against staging/canary, or some other means of configuring the live tests to run against an available API version.

cc @rakshith91 , @scbedd , @praveenkuttappan

**Comment by xiafu-msft** [comment]
For new features, we should develop using a feature branch instead of master, and the feature branch will not be merged until service is released. So enable overriding doesn't help test new features.
Besides, any old features update should be merged into master, so we also don't need to config anything for live test.

So SDK couldn't help much on this.

**Comment by lmazuel** [comment]
I believe the plan here now is to do a fallback from live to recording, so storage crew can work on faster. This means I'm clsoing this issue for now
