### ISSUE TITLE
[QUESTION] How to copy an existing database using python sdk? 

### ISSUE THREAD

**Issue by User1000** [Azure/azure-sdk-for-python#9971]
Is there any possibility to run command:
`az sql db copy`
using python sdk?

**Comment by lmazuel** [comment]
Hi @User1000 

The CLI is written using the SDK only, it means it's always possible :). Doesn't mean it has to be as simple as CLI though, since usually CLI is abstracting a little more than SDK.

I recommend you look into the CLI code of this operation:
https://github.com/Azure/azure-cli/blob/9387d5859ce028467061ac50ee47aa1ec73d4de2/src/azure-cli/azure/cli/command_modules/sql/custom.py#L753

Thanks!

**Comment by User1000** [comment]
Thanks a lot!
